#include "parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 14
#define STATE_COUNT 132
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 75
#define ALIAS_COUNT 0
#define TOKEN_COUNT 44
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 6
#define PRODUCTION_ID_COUNT 1

enum ts_symbol_identifiers {
  anon_sym_COLON = 1,
  anon_sym_SEMI = 2,
  anon_sym_COMMA = 3,
  sym_open_squiggly = 4,
  sym_close_squiggly = 5,
  sym_open_square = 6,
  sym_close_square = 7,
  sym_open_arrow = 8,
  sym_close_arrow = 9,
  anon_sym_SLASH = 10,
  anon_sym_DOT = 11,
  sym_identifier = 12,
  anon_sym_DASH = 13,
  anon_sym_SQUOTE = 14,
  anon_sym_DQUOTE = 15,
  sym_single_string_contents = 16,
  sym_double_string_contents = 17,
  anon_sym_BSLASHa = 18,
  anon_sym_BSLASHb = 19,
  anon_sym_BSLASHf = 20,
  anon_sym_BSLASHn = 21,
  anon_sym_BSLASHr = 22,
  anon_sym_BSLASHt = 23,
  anon_sym_BSLASHv = 24,
  anon_sym_BSLASH_QMARK = 25,
  anon_sym_BSLASH_DQUOTE = 26,
  anon_sym_BSLASH_SQUOTE = 27,
  anon_sym_BSLASH = 28,
  anon_sym_BSLASHx = 29,
  anon_sym_BSLASHu = 30,
  anon_sym_BSLASHU000 = 31,
  anon_sym_BSLASHU010 = 32,
  sym_oct = 33,
  sym_hex = 34,
  anon_sym_0 = 35,
  aux_sym_dec_int_token1 = 36,
  sym_oct_int = 37,
  sym_hex_int = 38,
  aux_sym_float_lit_token1 = 39,
  aux_sym_exp_token1 = 40,
  aux_sym_float_token1 = 41,
  anon_sym_POUND = 42,
  aux_sym_comment_token1 = 43,
  sym_message = 44,
  sym_field = 45,
  sym_message_field = 46,
  sym_scalar_field = 47,
  sym_message_value = 48,
  sym_message_list = 49,
  sym_field_name = 50,
  sym_extension_name = 51,
  sym_any_name = 52,
  sym_type_name = 53,
  sym_domain = 54,
  sym_signed_identifier = 55,
  sym_scalar_value = 56,
  sym_scalar_list = 57,
  sym_string = 58,
  sym_single_string = 59,
  sym_double_string = 60,
  sym_string_escape = 61,
  sym_number = 62,
  sym_dec_int = 63,
  sym_float_lit = 64,
  sym_exp = 65,
  sym_float = 66,
  sym_comment = 67,
  aux_sym_message_repeat1 = 68,
  aux_sym_message_list_repeat1 = 69,
  aux_sym_type_name_repeat1 = 70,
  aux_sym_scalar_value_repeat1 = 71,
  aux_sym_scalar_list_repeat1 = 72,
  aux_sym_single_string_repeat1 = 73,
  aux_sym_double_string_repeat1 = 74,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_COLON] = ":",
  [anon_sym_SEMI] = ";",
  [anon_sym_COMMA] = ",",
  [sym_open_squiggly] = "open_squiggly",
  [sym_close_squiggly] = "close_squiggly",
  [sym_open_square] = "open_square",
  [sym_close_square] = "close_square",
  [sym_open_arrow] = "open_arrow",
  [sym_close_arrow] = "close_arrow",
  [anon_sym_SLASH] = "/",
  [anon_sym_DOT] = ".",
  [sym_identifier] = "identifier",
  [anon_sym_DASH] = "-",
  [anon_sym_SQUOTE] = "'",
  [anon_sym_DQUOTE] = "\"",
  [sym_single_string_contents] = "single_string_contents",
  [sym_double_string_contents] = "double_string_contents",
  [anon_sym_BSLASHa] = "\\a",
  [anon_sym_BSLASHb] = "\\b",
  [anon_sym_BSLASHf] = "\\f",
  [anon_sym_BSLASHn] = "\\n",
  [anon_sym_BSLASHr] = "\\r",
  [anon_sym_BSLASHt] = "\\t",
  [anon_sym_BSLASHv] = "\\v",
  [anon_sym_BSLASH_QMARK] = "\\\?",
  [anon_sym_BSLASH_DQUOTE] = "\\\"",
  [anon_sym_BSLASH_SQUOTE] = "\\'",
  [anon_sym_BSLASH] = "\\",
  [anon_sym_BSLASHx] = "\\x",
  [anon_sym_BSLASHu] = "\\u",
  [anon_sym_BSLASHU000] = "\\U000",
  [anon_sym_BSLASHU010] = "\\U010",
  [sym_oct] = "oct",
  [sym_hex] = "hex",
  [anon_sym_0] = "0",
  [aux_sym_dec_int_token1] = "dec_int_token1",
  [sym_oct_int] = "oct_int",
  [sym_hex_int] = "hex_int",
  [aux_sym_float_lit_token1] = "float_lit_token1",
  [aux_sym_exp_token1] = "exp_token1",
  [aux_sym_float_token1] = "float_token1",
  [anon_sym_POUND] = "#",
  [aux_sym_comment_token1] = "comment_token1",
  [sym_message] = "message",
  [sym_field] = "field",
  [sym_message_field] = "message_field",
  [sym_scalar_field] = "scalar_field",
  [sym_message_value] = "message_value",
  [sym_message_list] = "message_list",
  [sym_field_name] = "field_name",
  [sym_extension_name] = "extension_name",
  [sym_any_name] = "any_name",
  [sym_type_name] = "type_name",
  [sym_domain] = "domain",
  [sym_signed_identifier] = "signed_identifier",
  [sym_scalar_value] = "scalar_value",
  [sym_scalar_list] = "scalar_list",
  [sym_string] = "string",
  [sym_single_string] = "single_string",
  [sym_double_string] = "double_string",
  [sym_string_escape] = "string_escape",
  [sym_number] = "number",
  [sym_dec_int] = "dec_int",
  [sym_float_lit] = "float_lit",
  [sym_exp] = "exp",
  [sym_float] = "float",
  [sym_comment] = "comment",
  [aux_sym_message_repeat1] = "message_repeat1",
  [aux_sym_message_list_repeat1] = "message_list_repeat1",
  [aux_sym_type_name_repeat1] = "type_name_repeat1",
  [aux_sym_scalar_value_repeat1] = "scalar_value_repeat1",
  [aux_sym_scalar_list_repeat1] = "scalar_list_repeat1",
  [aux_sym_single_string_repeat1] = "single_string_repeat1",
  [aux_sym_double_string_repeat1] = "double_string_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_COLON] = anon_sym_COLON,
  [anon_sym_SEMI] = anon_sym_SEMI,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [sym_open_squiggly] = sym_open_squiggly,
  [sym_close_squiggly] = sym_close_squiggly,
  [sym_open_square] = sym_open_square,
  [sym_close_square] = sym_close_square,
  [sym_open_arrow] = sym_open_arrow,
  [sym_close_arrow] = sym_close_arrow,
  [anon_sym_SLASH] = anon_sym_SLASH,
  [anon_sym_DOT] = anon_sym_DOT,
  [sym_identifier] = sym_identifier,
  [anon_sym_DASH] = anon_sym_DASH,
  [anon_sym_SQUOTE] = anon_sym_SQUOTE,
  [anon_sym_DQUOTE] = anon_sym_DQUOTE,
  [sym_single_string_contents] = sym_single_string_contents,
  [sym_double_string_contents] = sym_double_string_contents,
  [anon_sym_BSLASHa] = anon_sym_BSLASHa,
  [anon_sym_BSLASHb] = anon_sym_BSLASHb,
  [anon_sym_BSLASHf] = anon_sym_BSLASHf,
  [anon_sym_BSLASHn] = anon_sym_BSLASHn,
  [anon_sym_BSLASHr] = anon_sym_BSLASHr,
  [anon_sym_BSLASHt] = anon_sym_BSLASHt,
  [anon_sym_BSLASHv] = anon_sym_BSLASHv,
  [anon_sym_BSLASH_QMARK] = anon_sym_BSLASH_QMARK,
  [anon_sym_BSLASH_DQUOTE] = anon_sym_BSLASH_DQUOTE,
  [anon_sym_BSLASH_SQUOTE] = anon_sym_BSLASH_SQUOTE,
  [anon_sym_BSLASH] = anon_sym_BSLASH,
  [anon_sym_BSLASHx] = anon_sym_BSLASHx,
  [anon_sym_BSLASHu] = anon_sym_BSLASHu,
  [anon_sym_BSLASHU000] = anon_sym_BSLASHU000,
  [anon_sym_BSLASHU010] = anon_sym_BSLASHU010,
  [sym_oct] = sym_oct,
  [sym_hex] = sym_hex,
  [anon_sym_0] = anon_sym_0,
  [aux_sym_dec_int_token1] = aux_sym_dec_int_token1,
  [sym_oct_int] = sym_oct_int,
  [sym_hex_int] = sym_hex_int,
  [aux_sym_float_lit_token1] = aux_sym_float_lit_token1,
  [aux_sym_exp_token1] = aux_sym_exp_token1,
  [aux_sym_float_token1] = aux_sym_float_token1,
  [anon_sym_POUND] = anon_sym_POUND,
  [aux_sym_comment_token1] = aux_sym_comment_token1,
  [sym_message] = sym_message,
  [sym_field] = sym_field,
  [sym_message_field] = sym_message_field,
  [sym_scalar_field] = sym_scalar_field,
  [sym_message_value] = sym_message_value,
  [sym_message_list] = sym_message_list,
  [sym_field_name] = sym_field_name,
  [sym_extension_name] = sym_extension_name,
  [sym_any_name] = sym_any_name,
  [sym_type_name] = sym_type_name,
  [sym_domain] = sym_domain,
  [sym_signed_identifier] = sym_signed_identifier,
  [sym_scalar_value] = sym_scalar_value,
  [sym_scalar_list] = sym_scalar_list,
  [sym_string] = sym_string,
  [sym_single_string] = sym_single_string,
  [sym_double_string] = sym_double_string,
  [sym_string_escape] = sym_string_escape,
  [sym_number] = sym_number,
  [sym_dec_int] = sym_dec_int,
  [sym_float_lit] = sym_float_lit,
  [sym_exp] = sym_exp,
  [sym_float] = sym_float,
  [sym_comment] = sym_comment,
  [aux_sym_message_repeat1] = aux_sym_message_repeat1,
  [aux_sym_message_list_repeat1] = aux_sym_message_list_repeat1,
  [aux_sym_type_name_repeat1] = aux_sym_type_name_repeat1,
  [aux_sym_scalar_value_repeat1] = aux_sym_scalar_value_repeat1,
  [aux_sym_scalar_list_repeat1] = aux_sym_scalar_list_repeat1,
  [aux_sym_single_string_repeat1] = aux_sym_single_string_repeat1,
  [aux_sym_double_string_repeat1] = aux_sym_double_string_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_COLON] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SEMI] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [sym_open_squiggly] = {
    .visible = true,
    .named = true,
  },
  [sym_close_squiggly] = {
    .visible = true,
    .named = true,
  },
  [sym_open_square] = {
    .visible = true,
    .named = true,
  },
  [sym_close_square] = {
    .visible = true,
    .named = true,
  },
  [sym_open_arrow] = {
    .visible = true,
    .named = true,
  },
  [sym_close_arrow] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_SLASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DOT] = {
    .visible = true,
    .named = false,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_DASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SQUOTE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DQUOTE] = {
    .visible = true,
    .named = false,
  },
  [sym_single_string_contents] = {
    .visible = true,
    .named = true,
  },
  [sym_double_string_contents] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_BSLASHa] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_BSLASHb] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_BSLASHf] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_BSLASHn] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_BSLASHr] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_BSLASHt] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_BSLASHv] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_BSLASH_QMARK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_BSLASH_DQUOTE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_BSLASH_SQUOTE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_BSLASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_BSLASHx] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_BSLASHu] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_BSLASHU000] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_BSLASHU010] = {
    .visible = true,
    .named = false,
  },
  [sym_oct] = {
    .visible = true,
    .named = true,
  },
  [sym_hex] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_0] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_dec_int_token1] = {
    .visible = false,
    .named = false,
  },
  [sym_oct_int] = {
    .visible = true,
    .named = true,
  },
  [sym_hex_int] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_float_lit_token1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_exp_token1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_float_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_POUND] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_comment_token1] = {
    .visible = false,
    .named = false,
  },
  [sym_message] = {
    .visible = true,
    .named = true,
  },
  [sym_field] = {
    .visible = true,
    .named = true,
  },
  [sym_message_field] = {
    .visible = true,
    .named = true,
  },
  [sym_scalar_field] = {
    .visible = true,
    .named = true,
  },
  [sym_message_value] = {
    .visible = true,
    .named = true,
  },
  [sym_message_list] = {
    .visible = true,
    .named = true,
  },
  [sym_field_name] = {
    .visible = true,
    .named = true,
  },
  [sym_extension_name] = {
    .visible = true,
    .named = true,
  },
  [sym_any_name] = {
    .visible = true,
    .named = true,
  },
  [sym_type_name] = {
    .visible = true,
    .named = true,
  },
  [sym_domain] = {
    .visible = true,
    .named = true,
  },
  [sym_signed_identifier] = {
    .visible = true,
    .named = true,
  },
  [sym_scalar_value] = {
    .visible = true,
    .named = true,
  },
  [sym_scalar_list] = {
    .visible = true,
    .named = true,
  },
  [sym_string] = {
    .visible = true,
    .named = true,
  },
  [sym_single_string] = {
    .visible = true,
    .named = true,
  },
  [sym_double_string] = {
    .visible = true,
    .named = true,
  },
  [sym_string_escape] = {
    .visible = true,
    .named = true,
  },
  [sym_number] = {
    .visible = true,
    .named = true,
  },
  [sym_dec_int] = {
    .visible = true,
    .named = true,
  },
  [sym_float_lit] = {
    .visible = true,
    .named = true,
  },
  [sym_exp] = {
    .visible = true,
    .named = true,
  },
  [sym_float] = {
    .visible = true,
    .named = true,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_message_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_message_list_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_type_name_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_scalar_value_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_scalar_list_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_single_string_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_double_string_repeat1] = {
    .visible = false,
    .named = false,
  },
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 13,
  [15] = 11,
  [16] = 12,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 17,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 21,
  [25] = 25,
  [26] = 18,
  [27] = 23,
  [28] = 19,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 39,
  [40] = 40,
  [41] = 41,
  [42] = 42,
  [43] = 43,
  [44] = 44,
  [45] = 44,
  [46] = 46,
  [47] = 47,
  [48] = 48,
  [49] = 49,
  [50] = 50,
  [51] = 51,
  [52] = 52,
  [53] = 53,
  [54] = 54,
  [55] = 55,
  [56] = 56,
  [57] = 57,
  [58] = 58,
  [59] = 59,
  [60] = 60,
  [61] = 61,
  [62] = 36,
  [63] = 33,
  [64] = 64,
  [65] = 65,
  [66] = 66,
  [67] = 67,
  [68] = 68,
  [69] = 40,
  [70] = 70,
  [71] = 71,
  [72] = 72,
  [73] = 73,
  [74] = 74,
  [75] = 75,
  [76] = 76,
  [77] = 77,
  [78] = 78,
  [79] = 79,
  [80] = 80,
  [81] = 81,
  [82] = 82,
  [83] = 83,
  [84] = 84,
  [85] = 85,
  [86] = 86,
  [87] = 87,
  [88] = 88,
  [89] = 89,
  [90] = 90,
  [91] = 91,
  [92] = 92,
  [93] = 93,
  [94] = 94,
  [95] = 95,
  [96] = 96,
  [97] = 97,
  [98] = 98,
  [99] = 99,
  [100] = 100,
  [101] = 101,
  [102] = 102,
  [103] = 103,
  [104] = 96,
  [105] = 105,
  [106] = 106,
  [107] = 107,
  [108] = 108,
  [109] = 109,
  [110] = 110,
  [111] = 111,
  [112] = 112,
  [113] = 113,
  [114] = 114,
  [115] = 115,
  [116] = 116,
  [117] = 117,
  [118] = 118,
  [119] = 119,
  [120] = 120,
  [121] = 117,
  [122] = 116,
  [123] = 114,
  [124] = 107,
  [125] = 115,
  [126] = 105,
  [127] = 120,
  [128] = 101,
  [129] = 100,
  [130] = 111,
  [131] = 131,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(14);
      if (lookahead == '"') ADVANCE(30);
      if (lookahead == '#') ADVANCE(63);
      if (lookahead == '\'') ADVANCE(29);
      if (lookahead == ',') ADVANCE(17);
      if (lookahead == '-') ADVANCE(28);
      if (lookahead == '.') ADVANCE(25);
      if (lookahead == '/') ADVANCE(24);
      if (lookahead == '0') ADVANCE(54);
      if (lookahead == ':') ADVANCE(15);
      if (lookahead == ';') ADVANCE(16);
      if (lookahead == '<') ADVANCE(22);
      if (lookahead == '>') ADVANCE(23);
      if (lookahead == '[') ADVANCE(20);
      if (lookahead == '\\') ADVANCE(47);
      if (lookahead == ']') ADVANCE(21);
      if (lookahead == '{') ADVANCE(18);
      if (lookahead == '}') ADVANCE(19);
      if (lookahead == 'F' ||
          lookahead == 'f') ADVANCE(27);
      if (lookahead == '8' ||
          lookahead == '9') ADVANCE(53);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0)
      if (('1' <= lookahead && lookahead <= '7')) ADVANCE(52);
      if (('A' <= lookahead && lookahead <= 'E') ||
          ('a' <= lookahead && lookahead <= 'e')) ADVANCE(27);
      if (('G' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('g' <= lookahead && lookahead <= 'z')) ADVANCE(27);
      END_STATE();
    case 1:
      if (lookahead == '\n') SKIP(1)
      if (lookahead == '"') ADVANCE(30);
      if (lookahead == '#') ADVANCE(64);
      if (lookahead == '\\') ADVANCE(47);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(34);
      if (('0' <= lookahead && lookahead <= '7')) ADVANCE(36);
      if (lookahead != 0) ADVANCE(36);
      END_STATE();
    case 2:
      if (lookahead == '\n') SKIP(2)
      if (lookahead == '#') ADVANCE(65);
      if (lookahead == '\'') ADVANCE(29);
      if (lookahead == '\\') ADVANCE(47);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(31);
      if (('0' <= lookahead && lookahead <= '7')) ADVANCE(33);
      if (lookahead != 0) ADVANCE(33);
      END_STATE();
    case 3:
      if (lookahead == '\n') SKIP(3)
      if (lookahead == '#') ADVANCE(65);
      if (lookahead == '\'') ADVANCE(29);
      if (lookahead == '\\') ADVANCE(47);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(32);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(33);
      if (lookahead != 0) ADVANCE(33);
      END_STATE();
    case 4:
      if (lookahead == '\n') SKIP(4)
      if (lookahead == '"') ADVANCE(30);
      if (lookahead == '#') ADVANCE(64);
      if (lookahead == '\\') ADVANCE(47);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(35);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(36);
      if (lookahead != 0) ADVANCE(36);
      END_STATE();
    case 5:
      if (lookahead == '#') ADVANCE(63);
      if (lookahead == ',') ADVANCE(17);
      if (lookahead == '.') ADVANCE(25);
      if (lookahead == ']') ADVANCE(21);
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(61);
      if (lookahead == 'F' ||
          lookahead == 'f') ADVANCE(62);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(5)
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(59);
      END_STATE();
    case 6:
      if (lookahead == '#') ADVANCE(63);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(6)
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(53);
      END_STATE();
    case 7:
      if (lookahead == '#') ADVANCE(63);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(7)
      if (('0' <= lookahead && lookahead <= '7')) ADVANCE(52);
      END_STATE();
    case 8:
      if (lookahead == '0') ADVANCE(11);
      END_STATE();
    case 9:
      if (lookahead == '0') ADVANCE(50);
      END_STATE();
    case 10:
      if (lookahead == '0') ADVANCE(51);
      END_STATE();
    case 11:
      if (lookahead == '0') ADVANCE(9);
      if (lookahead == '1') ADVANCE(10);
      END_STATE();
    case 12:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(58);
      END_STATE();
    case 13:
      if (eof) ADVANCE(14);
      if (lookahead == '"') ADVANCE(30);
      if (lookahead == '#') ADVANCE(63);
      if (lookahead == '\'') ADVANCE(29);
      if (lookahead == ',') ADVANCE(17);
      if (lookahead == '-') ADVANCE(28);
      if (lookahead == '.') ADVANCE(25);
      if (lookahead == '/') ADVANCE(24);
      if (lookahead == '0') ADVANCE(55);
      if (lookahead == ';') ADVANCE(16);
      if (lookahead == '<') ADVANCE(22);
      if (lookahead == '>') ADVANCE(23);
      if (lookahead == '[') ADVANCE(20);
      if (lookahead == ']') ADVANCE(21);
      if (lookahead == '{') ADVANCE(18);
      if (lookahead == '}') ADVANCE(19);
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(26);
      if (lookahead == 'F' ||
          lookahead == 'f') ADVANCE(27);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(13)
      if (('1' <= lookahead && lookahead <= '9')) ADVANCE(56);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(27);
      END_STATE();
    case 14:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(anon_sym_COLON);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(anon_sym_SEMI);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(sym_open_squiggly);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(sym_close_squiggly);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(sym_open_square);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(sym_close_square);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(sym_open_arrow);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(sym_close_arrow);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(anon_sym_SLASH);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(anon_sym_DOT);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == '+' ||
          lookahead == '-') ADVANCE(60);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(27);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(sym_identifier);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(27);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(anon_sym_DASH);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(anon_sym_SQUOTE);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(anon_sym_DQUOTE);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(sym_single_string_contents);
      if (lookahead == '#') ADVANCE(65);
      if (lookahead == '\t' ||
          (11 <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(31);
      if (('0' <= lookahead && lookahead <= '7')) ADVANCE(33);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\'' &&
          lookahead != '\\') ADVANCE(33);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(sym_single_string_contents);
      if (lookahead == '#') ADVANCE(65);
      if (lookahead == '\t' ||
          (11 <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(32);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(33);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\'' &&
          lookahead != '\\') ADVANCE(33);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(sym_single_string_contents);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\'' &&
          lookahead != '\\') ADVANCE(33);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(sym_double_string_contents);
      if (lookahead == '#') ADVANCE(64);
      if (lookahead == '\t' ||
          (11 <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(34);
      if (('0' <= lookahead && lookahead <= '7')) ADVANCE(36);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '"' &&
          lookahead != '\\') ADVANCE(36);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(sym_double_string_contents);
      if (lookahead == '#') ADVANCE(64);
      if (lookahead == '\t' ||
          (11 <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(35);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(36);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '"' &&
          lookahead != '\\') ADVANCE(36);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(sym_double_string_contents);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '"' &&
          lookahead != '\\') ADVANCE(36);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(anon_sym_BSLASHa);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(anon_sym_BSLASHb);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(anon_sym_BSLASHf);
      END_STATE();
    case 40:
      ACCEPT_TOKEN(anon_sym_BSLASHn);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(anon_sym_BSLASHr);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(anon_sym_BSLASHt);
      END_STATE();
    case 43:
      ACCEPT_TOKEN(anon_sym_BSLASHv);
      END_STATE();
    case 44:
      ACCEPT_TOKEN(anon_sym_BSLASH_QMARK);
      END_STATE();
    case 45:
      ACCEPT_TOKEN(anon_sym_BSLASH_DQUOTE);
      END_STATE();
    case 46:
      ACCEPT_TOKEN(anon_sym_BSLASH_SQUOTE);
      END_STATE();
    case 47:
      ACCEPT_TOKEN(anon_sym_BSLASH);
      if (lookahead == '"') ADVANCE(45);
      if (lookahead == '\'') ADVANCE(46);
      if (lookahead == '?') ADVANCE(44);
      if (lookahead == 'U') ADVANCE(8);
      if (lookahead == 'a') ADVANCE(37);
      if (lookahead == 'b') ADVANCE(38);
      if (lookahead == 'f') ADVANCE(39);
      if (lookahead == 'n') ADVANCE(40);
      if (lookahead == 'r') ADVANCE(41);
      if (lookahead == 't') ADVANCE(42);
      if (lookahead == 'u') ADVANCE(49);
      if (lookahead == 'v') ADVANCE(43);
      if (lookahead == 'x') ADVANCE(48);
      END_STATE();
    case 48:
      ACCEPT_TOKEN(anon_sym_BSLASHx);
      END_STATE();
    case 49:
      ACCEPT_TOKEN(anon_sym_BSLASHu);
      END_STATE();
    case 50:
      ACCEPT_TOKEN(anon_sym_BSLASHU000);
      END_STATE();
    case 51:
      ACCEPT_TOKEN(anon_sym_BSLASHU010);
      END_STATE();
    case 52:
      ACCEPT_TOKEN(sym_oct);
      END_STATE();
    case 53:
      ACCEPT_TOKEN(sym_hex);
      END_STATE();
    case 54:
      ACCEPT_TOKEN(anon_sym_0);
      END_STATE();
    case 55:
      ACCEPT_TOKEN(anon_sym_0);
      if (lookahead == 'X' ||
          lookahead == 'x') ADVANCE(12);
      if (('0' <= lookahead && lookahead <= '7')) ADVANCE(57);
      END_STATE();
    case 56:
      ACCEPT_TOKEN(aux_sym_dec_int_token1);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(56);
      END_STATE();
    case 57:
      ACCEPT_TOKEN(sym_oct_int);
      if (('0' <= lookahead && lookahead <= '7')) ADVANCE(57);
      END_STATE();
    case 58:
      ACCEPT_TOKEN(sym_hex_int);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(58);
      END_STATE();
    case 59:
      ACCEPT_TOKEN(aux_sym_float_lit_token1);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(59);
      END_STATE();
    case 60:
      ACCEPT_TOKEN(aux_sym_exp_token1);
      END_STATE();
    case 61:
      ACCEPT_TOKEN(aux_sym_exp_token1);
      if (lookahead == '+' ||
          lookahead == '-') ADVANCE(60);
      END_STATE();
    case 62:
      ACCEPT_TOKEN(aux_sym_float_token1);
      END_STATE();
    case 63:
      ACCEPT_TOKEN(anon_sym_POUND);
      END_STATE();
    case 64:
      ACCEPT_TOKEN(anon_sym_POUND);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '"' &&
          lookahead != '\\') ADVANCE(36);
      END_STATE();
    case 65:
      ACCEPT_TOKEN(anon_sym_POUND);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\'' &&
          lookahead != '\\') ADVANCE(33);
      END_STATE();
    case 66:
      ACCEPT_TOKEN(anon_sym_POUND);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(68);
      END_STATE();
    case 67:
      ACCEPT_TOKEN(aux_sym_comment_token1);
      if (lookahead == '#') ADVANCE(66);
      if (lookahead == '\t' ||
          (11 <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(67);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(68);
      END_STATE();
    case 68:
      ACCEPT_TOKEN(aux_sym_comment_token1);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(68);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 13},
  [2] = {.lex_state = 13},
  [3] = {.lex_state = 13},
  [4] = {.lex_state = 1},
  [5] = {.lex_state = 2},
  [6] = {.lex_state = 1},
  [7] = {.lex_state = 2},
  [8] = {.lex_state = 2},
  [9] = {.lex_state = 13},
  [10] = {.lex_state = 1},
  [11] = {.lex_state = 1},
  [12] = {.lex_state = 2},
  [13] = {.lex_state = 3},
  [14] = {.lex_state = 4},
  [15] = {.lex_state = 2},
  [16] = {.lex_state = 1},
  [17] = {.lex_state = 1},
  [18] = {.lex_state = 1},
  [19] = {.lex_state = 2},
  [20] = {.lex_state = 2},
  [21] = {.lex_state = 2},
  [22] = {.lex_state = 1},
  [23] = {.lex_state = 2},
  [24] = {.lex_state = 1},
  [25] = {.lex_state = 2},
  [26] = {.lex_state = 2},
  [27] = {.lex_state = 1},
  [28] = {.lex_state = 1},
  [29] = {.lex_state = 13},
  [30] = {.lex_state = 13},
  [31] = {.lex_state = 13},
  [32] = {.lex_state = 13},
  [33] = {.lex_state = 13},
  [34] = {.lex_state = 13},
  [35] = {.lex_state = 13},
  [36] = {.lex_state = 13},
  [37] = {.lex_state = 13},
  [38] = {.lex_state = 13},
  [39] = {.lex_state = 13},
  [40] = {.lex_state = 13},
  [41] = {.lex_state = 13},
  [42] = {.lex_state = 13},
  [43] = {.lex_state = 13},
  [44] = {.lex_state = 13},
  [45] = {.lex_state = 13},
  [46] = {.lex_state = 13},
  [47] = {.lex_state = 13},
  [48] = {.lex_state = 13},
  [49] = {.lex_state = 13},
  [50] = {.lex_state = 13},
  [51] = {.lex_state = 13},
  [52] = {.lex_state = 13},
  [53] = {.lex_state = 13},
  [54] = {.lex_state = 13},
  [55] = {.lex_state = 13},
  [56] = {.lex_state = 13},
  [57] = {.lex_state = 13},
  [58] = {.lex_state = 13},
  [59] = {.lex_state = 13},
  [60] = {.lex_state = 13},
  [61] = {.lex_state = 13},
  [62] = {.lex_state = 5},
  [63] = {.lex_state = 5},
  [64] = {.lex_state = 0},
  [65] = {.lex_state = 13},
  [66] = {.lex_state = 13},
  [67] = {.lex_state = 13},
  [68] = {.lex_state = 13},
  [69] = {.lex_state = 5},
  [70] = {.lex_state = 13},
  [71] = {.lex_state = 13},
  [72] = {.lex_state = 13},
  [73] = {.lex_state = 13},
  [74] = {.lex_state = 13},
  [75] = {.lex_state = 5},
  [76] = {.lex_state = 0},
  [77] = {.lex_state = 0},
  [78] = {.lex_state = 13},
  [79] = {.lex_state = 13},
  [80] = {.lex_state = 0},
  [81] = {.lex_state = 0},
  [82] = {.lex_state = 0},
  [83] = {.lex_state = 0},
  [84] = {.lex_state = 13},
  [85] = {.lex_state = 5},
  [86] = {.lex_state = 0},
  [87] = {.lex_state = 0},
  [88] = {.lex_state = 0},
  [89] = {.lex_state = 0},
  [90] = {.lex_state = 5},
  [91] = {.lex_state = 0},
  [92] = {.lex_state = 0},
  [93] = {.lex_state = 13},
  [94] = {.lex_state = 0},
  [95] = {.lex_state = 67},
  [96] = {.lex_state = 6},
  [97] = {.lex_state = 5},
  [98] = {.lex_state = 5},
  [99] = {.lex_state = 0},
  [100] = {.lex_state = 6},
  [101] = {.lex_state = 6},
  [102] = {.lex_state = 5},
  [103] = {.lex_state = 0},
  [104] = {.lex_state = 6},
  [105] = {.lex_state = 6},
  [106] = {.lex_state = 5},
  [107] = {.lex_state = 6},
  [108] = {.lex_state = 0},
  [109] = {.lex_state = 5},
  [110] = {.lex_state = 0},
  [111] = {.lex_state = 6},
  [112] = {.lex_state = 0},
  [113] = {.lex_state = 5},
  [114] = {.lex_state = 6},
  [115] = {.lex_state = 6},
  [116] = {.lex_state = 6},
  [117] = {.lex_state = 7},
  [118] = {.lex_state = 0},
  [119] = {.lex_state = 5},
  [120] = {.lex_state = 6},
  [121] = {.lex_state = 7},
  [122] = {.lex_state = 6},
  [123] = {.lex_state = 6},
  [124] = {.lex_state = 6},
  [125] = {.lex_state = 6},
  [126] = {.lex_state = 6},
  [127] = {.lex_state = 6},
  [128] = {.lex_state = 6},
  [129] = {.lex_state = 6},
  [130] = {.lex_state = 6},
  [131] = {(TSStateId)(-1)},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [0] = {
    [sym_comment] = STATE(0),
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_COLON] = ACTIONS(1),
    [anon_sym_SEMI] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
    [sym_open_squiggly] = ACTIONS(1),
    [sym_close_squiggly] = ACTIONS(1),
    [sym_open_square] = ACTIONS(1),
    [sym_close_square] = ACTIONS(1),
    [sym_open_arrow] = ACTIONS(1),
    [sym_close_arrow] = ACTIONS(1),
    [anon_sym_SLASH] = ACTIONS(1),
    [anon_sym_DOT] = ACTIONS(1),
    [sym_identifier] = ACTIONS(1),
    [anon_sym_DASH] = ACTIONS(1),
    [anon_sym_SQUOTE] = ACTIONS(1),
    [anon_sym_DQUOTE] = ACTIONS(1),
    [anon_sym_BSLASHa] = ACTIONS(1),
    [anon_sym_BSLASHb] = ACTIONS(1),
    [anon_sym_BSLASHf] = ACTIONS(1),
    [anon_sym_BSLASHn] = ACTIONS(1),
    [anon_sym_BSLASHr] = ACTIONS(1),
    [anon_sym_BSLASHt] = ACTIONS(1),
    [anon_sym_BSLASHv] = ACTIONS(1),
    [anon_sym_BSLASH_QMARK] = ACTIONS(1),
    [anon_sym_BSLASH_DQUOTE] = ACTIONS(1),
    [anon_sym_BSLASH_SQUOTE] = ACTIONS(1),
    [anon_sym_BSLASH] = ACTIONS(1),
    [anon_sym_BSLASHx] = ACTIONS(1),
    [anon_sym_BSLASHu] = ACTIONS(1),
    [anon_sym_BSLASHU000] = ACTIONS(1),
    [anon_sym_BSLASHU010] = ACTIONS(1),
    [sym_oct] = ACTIONS(1),
    [sym_hex] = ACTIONS(1),
    [anon_sym_0] = ACTIONS(1),
    [aux_sym_float_token1] = ACTIONS(1),
    [anon_sym_POUND] = ACTIONS(3),
  },
  [1] = {
    [sym_message] = STATE(118),
    [sym_field] = STATE(73),
    [sym_message_field] = STATE(72),
    [sym_scalar_field] = STATE(72),
    [sym_field_name] = STATE(64),
    [sym_extension_name] = STATE(77),
    [sym_any_name] = STATE(77),
    [sym_comment] = STATE(1),
    [aux_sym_message_repeat1] = STATE(31),
    [sym_open_square] = ACTIONS(5),
    [sym_identifier] = ACTIONS(7),
    [anon_sym_POUND] = ACTIONS(3),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 22,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(9), 1,
      sym_open_squiggly,
    ACTIONS(11), 1,
      sym_open_square,
    ACTIONS(13), 1,
      sym_open_arrow,
    ACTIONS(15), 1,
      anon_sym_DOT,
    ACTIONS(17), 1,
      sym_identifier,
    ACTIONS(19), 1,
      anon_sym_DASH,
    ACTIONS(21), 1,
      anon_sym_SQUOTE,
    ACTIONS(23), 1,
      anon_sym_DQUOTE,
    ACTIONS(25), 1,
      anon_sym_0,
    ACTIONS(27), 1,
      aux_sym_dec_int_token1,
    STATE(2), 1,
      sym_comment,
    STATE(29), 1,
      aux_sym_scalar_value_repeat1,
    STATE(36), 1,
      sym_dec_int,
    STATE(42), 1,
      sym_string,
    STATE(48), 1,
      sym_float,
    STATE(119), 1,
      sym_float_lit,
    ACTIONS(29), 2,
      sym_oct_int,
      sym_hex_int,
    STATE(37), 2,
      sym_single_string,
      sym_double_string,
    STATE(50), 2,
      sym_signed_identifier,
      sym_number,
    STATE(53), 2,
      sym_message_value,
      sym_message_list,
    STATE(61), 2,
      sym_scalar_value,
      sym_scalar_list,
  [72] = 22,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(9), 1,
      sym_open_squiggly,
    ACTIONS(13), 1,
      sym_open_arrow,
    ACTIONS(15), 1,
      anon_sym_DOT,
    ACTIONS(17), 1,
      sym_identifier,
    ACTIONS(21), 1,
      anon_sym_SQUOTE,
    ACTIONS(23), 1,
      anon_sym_DQUOTE,
    ACTIONS(31), 1,
      sym_close_square,
    ACTIONS(33), 1,
      anon_sym_DASH,
    ACTIONS(35), 1,
      anon_sym_0,
    ACTIONS(37), 1,
      aux_sym_dec_int_token1,
    STATE(3), 1,
      sym_comment,
    STATE(29), 1,
      aux_sym_scalar_value_repeat1,
    STATE(42), 1,
      sym_string,
    STATE(48), 1,
      sym_float,
    STATE(62), 1,
      sym_dec_int,
    STATE(82), 1,
      sym_message_value,
    STATE(89), 1,
      sym_scalar_value,
    STATE(119), 1,
      sym_float_lit,
    ACTIONS(29), 2,
      sym_oct_int,
      sym_hex_int,
    STATE(37), 2,
      sym_single_string,
      sym_double_string,
    STATE(50), 2,
      sym_signed_identifier,
      sym_number,
  [142] = 10,
    ACTIONS(39), 1,
      anon_sym_DQUOTE,
    ACTIONS(41), 1,
      sym_double_string_contents,
    ACTIONS(47), 1,
      anon_sym_BSLASH,
    ACTIONS(50), 1,
      anon_sym_BSLASHx,
    ACTIONS(56), 1,
      anon_sym_BSLASHU000,
    ACTIONS(59), 1,
      anon_sym_POUND,
    STATE(22), 1,
      sym_string_escape,
    ACTIONS(53), 2,
      anon_sym_BSLASHu,
      anon_sym_BSLASHU010,
    STATE(4), 2,
      sym_comment,
      aux_sym_double_string_repeat1,
    ACTIONS(44), 10,
      anon_sym_BSLASHa,
      anon_sym_BSLASHb,
      anon_sym_BSLASHf,
      anon_sym_BSLASHn,
      anon_sym_BSLASHr,
      anon_sym_BSLASHt,
      anon_sym_BSLASHv,
      anon_sym_BSLASH_QMARK,
      anon_sym_BSLASH_DQUOTE,
      anon_sym_BSLASH_SQUOTE,
  [184] = 11,
    ACTIONS(59), 1,
      anon_sym_POUND,
    ACTIONS(61), 1,
      anon_sym_SQUOTE,
    ACTIONS(63), 1,
      sym_single_string_contents,
    ACTIONS(67), 1,
      anon_sym_BSLASH,
    ACTIONS(69), 1,
      anon_sym_BSLASHx,
    ACTIONS(73), 1,
      anon_sym_BSLASHU000,
    STATE(5), 1,
      sym_comment,
    STATE(8), 1,
      aux_sym_single_string_repeat1,
    STATE(25), 1,
      sym_string_escape,
    ACTIONS(71), 2,
      anon_sym_BSLASHu,
      anon_sym_BSLASHU010,
    ACTIONS(65), 10,
      anon_sym_BSLASHa,
      anon_sym_BSLASHb,
      anon_sym_BSLASHf,
      anon_sym_BSLASHn,
      anon_sym_BSLASHr,
      anon_sym_BSLASHt,
      anon_sym_BSLASHv,
      anon_sym_BSLASH_QMARK,
      anon_sym_BSLASH_DQUOTE,
      anon_sym_BSLASH_SQUOTE,
  [228] = 11,
    ACTIONS(59), 1,
      anon_sym_POUND,
    ACTIONS(75), 1,
      anon_sym_DQUOTE,
    ACTIONS(77), 1,
      sym_double_string_contents,
    ACTIONS(81), 1,
      anon_sym_BSLASH,
    ACTIONS(83), 1,
      anon_sym_BSLASHx,
    ACTIONS(87), 1,
      anon_sym_BSLASHU000,
    STATE(6), 1,
      sym_comment,
    STATE(10), 1,
      aux_sym_double_string_repeat1,
    STATE(22), 1,
      sym_string_escape,
    ACTIONS(85), 2,
      anon_sym_BSLASHu,
      anon_sym_BSLASHU010,
    ACTIONS(79), 10,
      anon_sym_BSLASHa,
      anon_sym_BSLASHb,
      anon_sym_BSLASHf,
      anon_sym_BSLASHn,
      anon_sym_BSLASHr,
      anon_sym_BSLASHt,
      anon_sym_BSLASHv,
      anon_sym_BSLASH_QMARK,
      anon_sym_BSLASH_DQUOTE,
      anon_sym_BSLASH_SQUOTE,
  [272] = 11,
    ACTIONS(59), 1,
      anon_sym_POUND,
    ACTIONS(63), 1,
      sym_single_string_contents,
    ACTIONS(67), 1,
      anon_sym_BSLASH,
    ACTIONS(69), 1,
      anon_sym_BSLASHx,
    ACTIONS(73), 1,
      anon_sym_BSLASHU000,
    ACTIONS(89), 1,
      anon_sym_SQUOTE,
    STATE(5), 1,
      aux_sym_single_string_repeat1,
    STATE(7), 1,
      sym_comment,
    STATE(25), 1,
      sym_string_escape,
    ACTIONS(71), 2,
      anon_sym_BSLASHu,
      anon_sym_BSLASHU010,
    ACTIONS(65), 10,
      anon_sym_BSLASHa,
      anon_sym_BSLASHb,
      anon_sym_BSLASHf,
      anon_sym_BSLASHn,
      anon_sym_BSLASHr,
      anon_sym_BSLASHt,
      anon_sym_BSLASHv,
      anon_sym_BSLASH_QMARK,
      anon_sym_BSLASH_DQUOTE,
      anon_sym_BSLASH_SQUOTE,
  [316] = 10,
    ACTIONS(59), 1,
      anon_sym_POUND,
    ACTIONS(91), 1,
      anon_sym_SQUOTE,
    ACTIONS(93), 1,
      sym_single_string_contents,
    ACTIONS(99), 1,
      anon_sym_BSLASH,
    ACTIONS(102), 1,
      anon_sym_BSLASHx,
    ACTIONS(108), 1,
      anon_sym_BSLASHU000,
    STATE(25), 1,
      sym_string_escape,
    ACTIONS(105), 2,
      anon_sym_BSLASHu,
      anon_sym_BSLASHU010,
    STATE(8), 2,
      sym_comment,
      aux_sym_single_string_repeat1,
    ACTIONS(96), 10,
      anon_sym_BSLASHa,
      anon_sym_BSLASHb,
      anon_sym_BSLASHf,
      anon_sym_BSLASHn,
      anon_sym_BSLASHr,
      anon_sym_BSLASHt,
      anon_sym_BSLASHv,
      anon_sym_BSLASH_QMARK,
      anon_sym_BSLASH_DQUOTE,
      anon_sym_BSLASH_SQUOTE,
  [358] = 18,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(15), 1,
      anon_sym_DOT,
    ACTIONS(17), 1,
      sym_identifier,
    ACTIONS(21), 1,
      anon_sym_SQUOTE,
    ACTIONS(23), 1,
      anon_sym_DQUOTE,
    ACTIONS(33), 1,
      anon_sym_DASH,
    ACTIONS(35), 1,
      anon_sym_0,
    ACTIONS(37), 1,
      aux_sym_dec_int_token1,
    STATE(9), 1,
      sym_comment,
    STATE(29), 1,
      aux_sym_scalar_value_repeat1,
    STATE(42), 1,
      sym_string,
    STATE(48), 1,
      sym_float,
    STATE(62), 1,
      sym_dec_int,
    STATE(92), 1,
      sym_scalar_value,
    STATE(119), 1,
      sym_float_lit,
    ACTIONS(29), 2,
      sym_oct_int,
      sym_hex_int,
    STATE(37), 2,
      sym_single_string,
      sym_double_string,
    STATE(50), 2,
      sym_signed_identifier,
      sym_number,
  [416] = 11,
    ACTIONS(59), 1,
      anon_sym_POUND,
    ACTIONS(77), 1,
      sym_double_string_contents,
    ACTIONS(81), 1,
      anon_sym_BSLASH,
    ACTIONS(83), 1,
      anon_sym_BSLASHx,
    ACTIONS(87), 1,
      anon_sym_BSLASHU000,
    ACTIONS(111), 1,
      anon_sym_DQUOTE,
    STATE(4), 1,
      aux_sym_double_string_repeat1,
    STATE(10), 1,
      sym_comment,
    STATE(22), 1,
      sym_string_escape,
    ACTIONS(85), 2,
      anon_sym_BSLASHu,
      anon_sym_BSLASHU010,
    ACTIONS(79), 10,
      anon_sym_BSLASHa,
      anon_sym_BSLASHb,
      anon_sym_BSLASHf,
      anon_sym_BSLASHn,
      anon_sym_BSLASHr,
      anon_sym_BSLASHt,
      anon_sym_BSLASHv,
      anon_sym_BSLASH_QMARK,
      anon_sym_BSLASH_DQUOTE,
      anon_sym_BSLASH_SQUOTE,
  [460] = 4,
    ACTIONS(59), 1,
      anon_sym_POUND,
    ACTIONS(115), 1,
      sym_oct,
    STATE(11), 1,
      sym_comment,
    ACTIONS(113), 17,
      anon_sym_DQUOTE,
      sym_double_string_contents,
      anon_sym_BSLASHa,
      anon_sym_BSLASHb,
      anon_sym_BSLASHf,
      anon_sym_BSLASHn,
      anon_sym_BSLASHr,
      anon_sym_BSLASHt,
      anon_sym_BSLASHv,
      anon_sym_BSLASH_QMARK,
      anon_sym_BSLASH_DQUOTE,
      anon_sym_BSLASH_SQUOTE,
      anon_sym_BSLASH,
      anon_sym_BSLASHx,
      anon_sym_BSLASHu,
      anon_sym_BSLASHU000,
      anon_sym_BSLASHU010,
  [489] = 4,
    ACTIONS(59), 1,
      anon_sym_POUND,
    ACTIONS(119), 1,
      sym_oct,
    STATE(12), 1,
      sym_comment,
    ACTIONS(117), 17,
      anon_sym_SQUOTE,
      sym_single_string_contents,
      anon_sym_BSLASHa,
      anon_sym_BSLASHb,
      anon_sym_BSLASHf,
      anon_sym_BSLASHn,
      anon_sym_BSLASHr,
      anon_sym_BSLASHt,
      anon_sym_BSLASHv,
      anon_sym_BSLASH_QMARK,
      anon_sym_BSLASH_DQUOTE,
      anon_sym_BSLASH_SQUOTE,
      anon_sym_BSLASH,
      anon_sym_BSLASHx,
      anon_sym_BSLASHu,
      anon_sym_BSLASHU000,
      anon_sym_BSLASHU010,
  [518] = 4,
    ACTIONS(59), 1,
      anon_sym_POUND,
    ACTIONS(121), 1,
      sym_hex,
    STATE(13), 1,
      sym_comment,
    ACTIONS(113), 17,
      anon_sym_SQUOTE,
      sym_single_string_contents,
      anon_sym_BSLASHa,
      anon_sym_BSLASHb,
      anon_sym_BSLASHf,
      anon_sym_BSLASHn,
      anon_sym_BSLASHr,
      anon_sym_BSLASHt,
      anon_sym_BSLASHv,
      anon_sym_BSLASH_QMARK,
      anon_sym_BSLASH_DQUOTE,
      anon_sym_BSLASH_SQUOTE,
      anon_sym_BSLASH,
      anon_sym_BSLASHx,
      anon_sym_BSLASHu,
      anon_sym_BSLASHU000,
      anon_sym_BSLASHU010,
  [547] = 4,
    ACTIONS(59), 1,
      anon_sym_POUND,
    ACTIONS(123), 1,
      sym_hex,
    STATE(14), 1,
      sym_comment,
    ACTIONS(113), 17,
      anon_sym_DQUOTE,
      sym_double_string_contents,
      anon_sym_BSLASHa,
      anon_sym_BSLASHb,
      anon_sym_BSLASHf,
      anon_sym_BSLASHn,
      anon_sym_BSLASHr,
      anon_sym_BSLASHt,
      anon_sym_BSLASHv,
      anon_sym_BSLASH_QMARK,
      anon_sym_BSLASH_DQUOTE,
      anon_sym_BSLASH_SQUOTE,
      anon_sym_BSLASH,
      anon_sym_BSLASHx,
      anon_sym_BSLASHu,
      anon_sym_BSLASHU000,
      anon_sym_BSLASHU010,
  [576] = 4,
    ACTIONS(59), 1,
      anon_sym_POUND,
    ACTIONS(125), 1,
      sym_oct,
    STATE(15), 1,
      sym_comment,
    ACTIONS(113), 17,
      anon_sym_SQUOTE,
      sym_single_string_contents,
      anon_sym_BSLASHa,
      anon_sym_BSLASHb,
      anon_sym_BSLASHf,
      anon_sym_BSLASHn,
      anon_sym_BSLASHr,
      anon_sym_BSLASHt,
      anon_sym_BSLASHv,
      anon_sym_BSLASH_QMARK,
      anon_sym_BSLASH_DQUOTE,
      anon_sym_BSLASH_SQUOTE,
      anon_sym_BSLASH,
      anon_sym_BSLASHx,
      anon_sym_BSLASHu,
      anon_sym_BSLASHU000,
      anon_sym_BSLASHU010,
  [605] = 4,
    ACTIONS(59), 1,
      anon_sym_POUND,
    ACTIONS(127), 1,
      sym_oct,
    STATE(16), 1,
      sym_comment,
    ACTIONS(117), 17,
      anon_sym_DQUOTE,
      sym_double_string_contents,
      anon_sym_BSLASHa,
      anon_sym_BSLASHb,
      anon_sym_BSLASHf,
      anon_sym_BSLASHn,
      anon_sym_BSLASHr,
      anon_sym_BSLASHt,
      anon_sym_BSLASHv,
      anon_sym_BSLASH_QMARK,
      anon_sym_BSLASH_DQUOTE,
      anon_sym_BSLASH_SQUOTE,
      anon_sym_BSLASH,
      anon_sym_BSLASHx,
      anon_sym_BSLASHu,
      anon_sym_BSLASHU000,
      anon_sym_BSLASHU010,
  [634] = 3,
    ACTIONS(59), 1,
      anon_sym_POUND,
    STATE(17), 1,
      sym_comment,
    ACTIONS(129), 17,
      anon_sym_DQUOTE,
      sym_double_string_contents,
      anon_sym_BSLASHa,
      anon_sym_BSLASHb,
      anon_sym_BSLASHf,
      anon_sym_BSLASHn,
      anon_sym_BSLASHr,
      anon_sym_BSLASHt,
      anon_sym_BSLASHv,
      anon_sym_BSLASH_QMARK,
      anon_sym_BSLASH_DQUOTE,
      anon_sym_BSLASH_SQUOTE,
      anon_sym_BSLASH,
      anon_sym_BSLASHx,
      anon_sym_BSLASHu,
      anon_sym_BSLASHU000,
      anon_sym_BSLASHU010,
  [660] = 3,
    ACTIONS(59), 1,
      anon_sym_POUND,
    STATE(18), 1,
      sym_comment,
    ACTIONS(131), 17,
      anon_sym_DQUOTE,
      sym_double_string_contents,
      anon_sym_BSLASHa,
      anon_sym_BSLASHb,
      anon_sym_BSLASHf,
      anon_sym_BSLASHn,
      anon_sym_BSLASHr,
      anon_sym_BSLASHt,
      anon_sym_BSLASHv,
      anon_sym_BSLASH_QMARK,
      anon_sym_BSLASH_DQUOTE,
      anon_sym_BSLASH_SQUOTE,
      anon_sym_BSLASH,
      anon_sym_BSLASHx,
      anon_sym_BSLASHu,
      anon_sym_BSLASHU000,
      anon_sym_BSLASHU010,
  [686] = 3,
    ACTIONS(59), 1,
      anon_sym_POUND,
    STATE(19), 1,
      sym_comment,
    ACTIONS(133), 17,
      anon_sym_SQUOTE,
      sym_single_string_contents,
      anon_sym_BSLASHa,
      anon_sym_BSLASHb,
      anon_sym_BSLASHf,
      anon_sym_BSLASHn,
      anon_sym_BSLASHr,
      anon_sym_BSLASHt,
      anon_sym_BSLASHv,
      anon_sym_BSLASH_QMARK,
      anon_sym_BSLASH_DQUOTE,
      anon_sym_BSLASH_SQUOTE,
      anon_sym_BSLASH,
      anon_sym_BSLASHx,
      anon_sym_BSLASHu,
      anon_sym_BSLASHU000,
      anon_sym_BSLASHU010,
  [712] = 3,
    ACTIONS(59), 1,
      anon_sym_POUND,
    STATE(20), 1,
      sym_comment,
    ACTIONS(129), 17,
      anon_sym_SQUOTE,
      sym_single_string_contents,
      anon_sym_BSLASHa,
      anon_sym_BSLASHb,
      anon_sym_BSLASHf,
      anon_sym_BSLASHn,
      anon_sym_BSLASHr,
      anon_sym_BSLASHt,
      anon_sym_BSLASHv,
      anon_sym_BSLASH_QMARK,
      anon_sym_BSLASH_DQUOTE,
      anon_sym_BSLASH_SQUOTE,
      anon_sym_BSLASH,
      anon_sym_BSLASHx,
      anon_sym_BSLASHu,
      anon_sym_BSLASHU000,
      anon_sym_BSLASHU010,
  [738] = 3,
    ACTIONS(59), 1,
      anon_sym_POUND,
    STATE(21), 1,
      sym_comment,
    ACTIONS(135), 17,
      anon_sym_SQUOTE,
      sym_single_string_contents,
      anon_sym_BSLASHa,
      anon_sym_BSLASHb,
      anon_sym_BSLASHf,
      anon_sym_BSLASHn,
      anon_sym_BSLASHr,
      anon_sym_BSLASHt,
      anon_sym_BSLASHv,
      anon_sym_BSLASH_QMARK,
      anon_sym_BSLASH_DQUOTE,
      anon_sym_BSLASH_SQUOTE,
      anon_sym_BSLASH,
      anon_sym_BSLASHx,
      anon_sym_BSLASHu,
      anon_sym_BSLASHU000,
      anon_sym_BSLASHU010,
  [764] = 3,
    ACTIONS(59), 1,
      anon_sym_POUND,
    STATE(22), 1,
      sym_comment,
    ACTIONS(137), 17,
      anon_sym_DQUOTE,
      sym_double_string_contents,
      anon_sym_BSLASHa,
      anon_sym_BSLASHb,
      anon_sym_BSLASHf,
      anon_sym_BSLASHn,
      anon_sym_BSLASHr,
      anon_sym_BSLASHt,
      anon_sym_BSLASHv,
      anon_sym_BSLASH_QMARK,
      anon_sym_BSLASH_DQUOTE,
      anon_sym_BSLASH_SQUOTE,
      anon_sym_BSLASH,
      anon_sym_BSLASHx,
      anon_sym_BSLASHu,
      anon_sym_BSLASHU000,
      anon_sym_BSLASHU010,
  [790] = 3,
    ACTIONS(59), 1,
      anon_sym_POUND,
    STATE(23), 1,
      sym_comment,
    ACTIONS(117), 17,
      anon_sym_SQUOTE,
      sym_single_string_contents,
      anon_sym_BSLASHa,
      anon_sym_BSLASHb,
      anon_sym_BSLASHf,
      anon_sym_BSLASHn,
      anon_sym_BSLASHr,
      anon_sym_BSLASHt,
      anon_sym_BSLASHv,
      anon_sym_BSLASH_QMARK,
      anon_sym_BSLASH_DQUOTE,
      anon_sym_BSLASH_SQUOTE,
      anon_sym_BSLASH,
      anon_sym_BSLASHx,
      anon_sym_BSLASHu,
      anon_sym_BSLASHU000,
      anon_sym_BSLASHU010,
  [816] = 3,
    ACTIONS(59), 1,
      anon_sym_POUND,
    STATE(24), 1,
      sym_comment,
    ACTIONS(135), 17,
      anon_sym_DQUOTE,
      sym_double_string_contents,
      anon_sym_BSLASHa,
      anon_sym_BSLASHb,
      anon_sym_BSLASHf,
      anon_sym_BSLASHn,
      anon_sym_BSLASHr,
      anon_sym_BSLASHt,
      anon_sym_BSLASHv,
      anon_sym_BSLASH_QMARK,
      anon_sym_BSLASH_DQUOTE,
      anon_sym_BSLASH_SQUOTE,
      anon_sym_BSLASH,
      anon_sym_BSLASHx,
      anon_sym_BSLASHu,
      anon_sym_BSLASHU000,
      anon_sym_BSLASHU010,
  [842] = 3,
    ACTIONS(59), 1,
      anon_sym_POUND,
    STATE(25), 1,
      sym_comment,
    ACTIONS(139), 17,
      anon_sym_SQUOTE,
      sym_single_string_contents,
      anon_sym_BSLASHa,
      anon_sym_BSLASHb,
      anon_sym_BSLASHf,
      anon_sym_BSLASHn,
      anon_sym_BSLASHr,
      anon_sym_BSLASHt,
      anon_sym_BSLASHv,
      anon_sym_BSLASH_QMARK,
      anon_sym_BSLASH_DQUOTE,
      anon_sym_BSLASH_SQUOTE,
      anon_sym_BSLASH,
      anon_sym_BSLASHx,
      anon_sym_BSLASHu,
      anon_sym_BSLASHU000,
      anon_sym_BSLASHU010,
  [868] = 3,
    ACTIONS(59), 1,
      anon_sym_POUND,
    STATE(26), 1,
      sym_comment,
    ACTIONS(131), 17,
      anon_sym_SQUOTE,
      sym_single_string_contents,
      anon_sym_BSLASHa,
      anon_sym_BSLASHb,
      anon_sym_BSLASHf,
      anon_sym_BSLASHn,
      anon_sym_BSLASHr,
      anon_sym_BSLASHt,
      anon_sym_BSLASHv,
      anon_sym_BSLASH_QMARK,
      anon_sym_BSLASH_DQUOTE,
      anon_sym_BSLASH_SQUOTE,
      anon_sym_BSLASH,
      anon_sym_BSLASHx,
      anon_sym_BSLASHu,
      anon_sym_BSLASHU000,
      anon_sym_BSLASHU010,
  [894] = 3,
    ACTIONS(59), 1,
      anon_sym_POUND,
    STATE(27), 1,
      sym_comment,
    ACTIONS(117), 17,
      anon_sym_DQUOTE,
      sym_double_string_contents,
      anon_sym_BSLASHa,
      anon_sym_BSLASHb,
      anon_sym_BSLASHf,
      anon_sym_BSLASHn,
      anon_sym_BSLASHr,
      anon_sym_BSLASHt,
      anon_sym_BSLASHv,
      anon_sym_BSLASH_QMARK,
      anon_sym_BSLASH_DQUOTE,
      anon_sym_BSLASH_SQUOTE,
      anon_sym_BSLASH,
      anon_sym_BSLASHx,
      anon_sym_BSLASHu,
      anon_sym_BSLASHU000,
      anon_sym_BSLASHU010,
  [920] = 3,
    ACTIONS(59), 1,
      anon_sym_POUND,
    STATE(28), 1,
      sym_comment,
    ACTIONS(133), 17,
      anon_sym_DQUOTE,
      sym_double_string_contents,
      anon_sym_BSLASHa,
      anon_sym_BSLASHb,
      anon_sym_BSLASHf,
      anon_sym_BSLASHn,
      anon_sym_BSLASHr,
      anon_sym_BSLASHt,
      anon_sym_BSLASHv,
      anon_sym_BSLASH_QMARK,
      anon_sym_BSLASH_DQUOTE,
      anon_sym_BSLASH_SQUOTE,
      anon_sym_BSLASH,
      anon_sym_BSLASHx,
      anon_sym_BSLASHu,
      anon_sym_BSLASHU000,
      anon_sym_BSLASHU010,
  [946] = 8,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(21), 1,
      anon_sym_SQUOTE,
    ACTIONS(23), 1,
      anon_sym_DQUOTE,
    STATE(29), 1,
      sym_comment,
    STATE(30), 1,
      aux_sym_scalar_value_repeat1,
    STATE(42), 1,
      sym_string,
    STATE(37), 2,
      sym_single_string,
      sym_double_string,
    ACTIONS(141), 8,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_COMMA,
      sym_close_squiggly,
      sym_open_square,
      sym_close_square,
      sym_close_arrow,
      sym_identifier,
  [979] = 7,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(145), 1,
      anon_sym_SQUOTE,
    ACTIONS(148), 1,
      anon_sym_DQUOTE,
    STATE(42), 1,
      sym_string,
    STATE(30), 2,
      sym_comment,
      aux_sym_scalar_value_repeat1,
    STATE(37), 2,
      sym_single_string,
      sym_double_string,
    ACTIONS(143), 8,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_COMMA,
      sym_close_squiggly,
      sym_open_square,
      sym_close_square,
      sym_close_arrow,
      sym_identifier,
  [1010] = 10,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(5), 1,
      sym_open_square,
    ACTIONS(7), 1,
      sym_identifier,
    STATE(31), 1,
      sym_comment,
    STATE(32), 1,
      aux_sym_message_repeat1,
    STATE(64), 1,
      sym_field_name,
    STATE(73), 1,
      sym_field,
    STATE(72), 2,
      sym_message_field,
      sym_scalar_field,
    STATE(77), 2,
      sym_extension_name,
      sym_any_name,
    ACTIONS(151), 3,
      ts_builtin_sym_end,
      sym_close_squiggly,
      sym_close_arrow,
  [1045] = 9,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(155), 1,
      sym_open_square,
    ACTIONS(158), 1,
      sym_identifier,
    STATE(64), 1,
      sym_field_name,
    STATE(73), 1,
      sym_field,
    STATE(32), 2,
      sym_comment,
      aux_sym_message_repeat1,
    STATE(72), 2,
      sym_message_field,
      sym_scalar_field,
    STATE(77), 2,
      sym_extension_name,
      sym_any_name,
    ACTIONS(153), 3,
      ts_builtin_sym_end,
      sym_close_squiggly,
      sym_close_arrow,
  [1078] = 8,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(163), 1,
      anon_sym_DOT,
    ACTIONS(165), 1,
      sym_identifier,
    ACTIONS(167), 1,
      aux_sym_exp_token1,
    ACTIONS(169), 1,
      aux_sym_float_token1,
    STATE(33), 1,
      sym_comment,
    STATE(106), 1,
      sym_exp,
    ACTIONS(161), 6,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_COMMA,
      sym_close_squiggly,
      sym_open_square,
      sym_close_arrow,
  [1108] = 11,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(5), 1,
      sym_open_square,
    ACTIONS(7), 1,
      sym_identifier,
    ACTIONS(171), 1,
      sym_close_squiggly,
    STATE(31), 1,
      aux_sym_message_repeat1,
    STATE(34), 1,
      sym_comment,
    STATE(64), 1,
      sym_field_name,
    STATE(73), 1,
      sym_field,
    STATE(99), 1,
      sym_message,
    STATE(72), 2,
      sym_message_field,
      sym_scalar_field,
    STATE(77), 2,
      sym_extension_name,
      sym_any_name,
  [1144] = 11,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(5), 1,
      sym_open_square,
    ACTIONS(7), 1,
      sym_identifier,
    ACTIONS(171), 1,
      sym_close_arrow,
    STATE(31), 1,
      aux_sym_message_repeat1,
    STATE(35), 1,
      sym_comment,
    STATE(64), 1,
      sym_field_name,
    STATE(73), 1,
      sym_field,
    STATE(103), 1,
      sym_message,
    STATE(72), 2,
      sym_message_field,
      sym_scalar_field,
    STATE(77), 2,
      sym_extension_name,
      sym_any_name,
  [1180] = 8,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(163), 1,
      anon_sym_DOT,
    ACTIONS(167), 1,
      aux_sym_exp_token1,
    ACTIONS(169), 1,
      aux_sym_float_token1,
    ACTIONS(175), 1,
      sym_identifier,
    STATE(36), 1,
      sym_comment,
    STATE(106), 1,
      sym_exp,
    ACTIONS(173), 6,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_COMMA,
      sym_close_squiggly,
      sym_open_square,
      sym_close_arrow,
  [1210] = 3,
    ACTIONS(3), 1,
      anon_sym_POUND,
    STATE(37), 1,
      sym_comment,
    ACTIONS(177), 10,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_COMMA,
      sym_close_squiggly,
      sym_open_square,
      sym_close_square,
      sym_close_arrow,
      sym_identifier,
      anon_sym_SQUOTE,
      anon_sym_DQUOTE,
  [1229] = 3,
    ACTIONS(3), 1,
      anon_sym_POUND,
    STATE(38), 1,
      sym_comment,
    ACTIONS(179), 10,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_COMMA,
      sym_close_squiggly,
      sym_open_square,
      sym_close_square,
      sym_close_arrow,
      sym_identifier,
      anon_sym_SQUOTE,
      anon_sym_DQUOTE,
  [1248] = 3,
    ACTIONS(3), 1,
      anon_sym_POUND,
    STATE(39), 1,
      sym_comment,
    ACTIONS(181), 10,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_COMMA,
      sym_close_squiggly,
      sym_open_square,
      sym_close_square,
      sym_close_arrow,
      sym_identifier,
      anon_sym_SQUOTE,
      anon_sym_DQUOTE,
  [1267] = 4,
    ACTIONS(3), 1,
      anon_sym_POUND,
    STATE(40), 1,
      sym_comment,
    ACTIONS(185), 3,
      sym_identifier,
      aux_sym_exp_token1,
      aux_sym_float_token1,
    ACTIONS(183), 7,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_COMMA,
      sym_close_squiggly,
      sym_open_square,
      sym_close_arrow,
      anon_sym_DOT,
  [1288] = 3,
    ACTIONS(3), 1,
      anon_sym_POUND,
    STATE(41), 1,
      sym_comment,
    ACTIONS(187), 10,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_COMMA,
      sym_close_squiggly,
      sym_open_square,
      sym_close_square,
      sym_close_arrow,
      sym_identifier,
      anon_sym_SQUOTE,
      anon_sym_DQUOTE,
  [1307] = 3,
    ACTIONS(3), 1,
      anon_sym_POUND,
    STATE(42), 1,
      sym_comment,
    ACTIONS(189), 10,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_COMMA,
      sym_close_squiggly,
      sym_open_square,
      sym_close_square,
      sym_close_arrow,
      sym_identifier,
      anon_sym_SQUOTE,
      anon_sym_DQUOTE,
  [1326] = 3,
    ACTIONS(3), 1,
      anon_sym_POUND,
    STATE(43), 1,
      sym_comment,
    ACTIONS(191), 10,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_COMMA,
      sym_close_squiggly,
      sym_open_square,
      sym_close_square,
      sym_close_arrow,
      sym_identifier,
      anon_sym_SQUOTE,
      anon_sym_DQUOTE,
  [1345] = 10,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(15), 1,
      anon_sym_DOT,
    ACTIONS(35), 1,
      anon_sym_0,
    ACTIONS(37), 1,
      aux_sym_dec_int_token1,
    ACTIONS(193), 1,
      sym_identifier,
    STATE(44), 1,
      sym_comment,
    STATE(52), 1,
      sym_float,
    STATE(63), 1,
      sym_dec_int,
    STATE(119), 1,
      sym_float_lit,
    ACTIONS(195), 2,
      sym_oct_int,
      sym_hex_int,
  [1377] = 10,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(15), 1,
      anon_sym_DOT,
    ACTIONS(25), 1,
      anon_sym_0,
    ACTIONS(27), 1,
      aux_sym_dec_int_token1,
    ACTIONS(193), 1,
      sym_identifier,
    STATE(33), 1,
      sym_dec_int,
    STATE(45), 1,
      sym_comment,
    STATE(52), 1,
      sym_float,
    STATE(119), 1,
      sym_float_lit,
    ACTIONS(195), 2,
      sym_oct_int,
      sym_hex_int,
  [1409] = 3,
    ACTIONS(3), 1,
      anon_sym_POUND,
    STATE(46), 1,
      sym_comment,
    ACTIONS(197), 8,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_COMMA,
      sym_close_squiggly,
      sym_open_square,
      sym_close_square,
      sym_close_arrow,
      sym_identifier,
  [1426] = 3,
    ACTIONS(3), 1,
      anon_sym_POUND,
    STATE(47), 1,
      sym_comment,
    ACTIONS(199), 8,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_COMMA,
      sym_close_squiggly,
      sym_open_square,
      sym_close_square,
      sym_close_arrow,
      sym_identifier,
  [1443] = 3,
    ACTIONS(3), 1,
      anon_sym_POUND,
    STATE(48), 1,
      sym_comment,
    ACTIONS(173), 8,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_COMMA,
      sym_close_squiggly,
      sym_open_square,
      sym_close_square,
      sym_close_arrow,
      sym_identifier,
  [1460] = 3,
    ACTIONS(3), 1,
      anon_sym_POUND,
    STATE(49), 1,
      sym_comment,
    ACTIONS(201), 8,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_COMMA,
      sym_close_squiggly,
      sym_open_square,
      sym_close_square,
      sym_close_arrow,
      sym_identifier,
  [1477] = 3,
    ACTIONS(3), 1,
      anon_sym_POUND,
    STATE(50), 1,
      sym_comment,
    ACTIONS(141), 8,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_COMMA,
      sym_close_squiggly,
      sym_open_square,
      sym_close_square,
      sym_close_arrow,
      sym_identifier,
  [1494] = 3,
    ACTIONS(3), 1,
      anon_sym_POUND,
    STATE(51), 1,
      sym_comment,
    ACTIONS(203), 8,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_COMMA,
      sym_close_squiggly,
      sym_open_square,
      sym_close_square,
      sym_close_arrow,
      sym_identifier,
  [1511] = 3,
    ACTIONS(3), 1,
      anon_sym_POUND,
    STATE(52), 1,
      sym_comment,
    ACTIONS(161), 8,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_COMMA,
      sym_close_squiggly,
      sym_open_square,
      sym_close_square,
      sym_close_arrow,
      sym_identifier,
  [1528] = 4,
    ACTIONS(3), 1,
      anon_sym_POUND,
    STATE(53), 1,
      sym_comment,
    ACTIONS(207), 2,
      anon_sym_SEMI,
      anon_sym_COMMA,
    ACTIONS(205), 5,
      ts_builtin_sym_end,
      sym_close_squiggly,
      sym_open_square,
      sym_close_arrow,
      sym_identifier,
  [1546] = 4,
    ACTIONS(3), 1,
      anon_sym_POUND,
    STATE(54), 1,
      sym_comment,
    ACTIONS(211), 2,
      anon_sym_SEMI,
      anon_sym_COMMA,
    ACTIONS(209), 5,
      ts_builtin_sym_end,
      sym_close_squiggly,
      sym_open_square,
      sym_close_arrow,
      sym_identifier,
  [1564] = 3,
    ACTIONS(3), 1,
      anon_sym_POUND,
    STATE(55), 1,
      sym_comment,
    ACTIONS(213), 7,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_COMMA,
      sym_close_squiggly,
      sym_open_square,
      sym_close_arrow,
      sym_identifier,
  [1580] = 3,
    ACTIONS(3), 1,
      anon_sym_POUND,
    STATE(56), 1,
      sym_comment,
    ACTIONS(215), 7,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_COMMA,
      sym_close_squiggly,
      sym_open_square,
      sym_close_arrow,
      sym_identifier,
  [1596] = 3,
    ACTIONS(3), 1,
      anon_sym_POUND,
    STATE(57), 1,
      sym_comment,
    ACTIONS(217), 7,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_COMMA,
      sym_close_squiggly,
      sym_open_square,
      sym_close_arrow,
      sym_identifier,
  [1612] = 3,
    ACTIONS(3), 1,
      anon_sym_POUND,
    STATE(58), 1,
      sym_comment,
    ACTIONS(219), 7,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_COMMA,
      sym_close_squiggly,
      sym_open_square,
      sym_close_arrow,
      sym_identifier,
  [1628] = 3,
    ACTIONS(3), 1,
      anon_sym_POUND,
    STATE(59), 1,
      sym_comment,
    ACTIONS(221), 7,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_COMMA,
      sym_close_squiggly,
      sym_open_square,
      sym_close_arrow,
      sym_identifier,
  [1644] = 3,
    ACTIONS(3), 1,
      anon_sym_POUND,
    STATE(60), 1,
      sym_comment,
    ACTIONS(217), 7,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_COMMA,
      sym_close_squiggly,
      sym_open_square,
      sym_close_arrow,
      sym_identifier,
  [1660] = 4,
    ACTIONS(3), 1,
      anon_sym_POUND,
    STATE(61), 1,
      sym_comment,
    ACTIONS(225), 2,
      anon_sym_SEMI,
      anon_sym_COMMA,
    ACTIONS(223), 5,
      ts_builtin_sym_end,
      sym_close_squiggly,
      sym_open_square,
      sym_close_arrow,
      sym_identifier,
  [1678] = 7,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(163), 1,
      anon_sym_DOT,
    ACTIONS(227), 1,
      aux_sym_exp_token1,
    ACTIONS(229), 1,
      aux_sym_float_token1,
    STATE(62), 1,
      sym_comment,
    STATE(106), 1,
      sym_exp,
    ACTIONS(173), 2,
      anon_sym_COMMA,
      sym_close_square,
  [1701] = 7,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(163), 1,
      anon_sym_DOT,
    ACTIONS(227), 1,
      aux_sym_exp_token1,
    ACTIONS(229), 1,
      aux_sym_float_token1,
    STATE(63), 1,
      sym_comment,
    STATE(106), 1,
      sym_exp,
    ACTIONS(161), 2,
      anon_sym_COMMA,
      sym_close_square,
  [1724] = 7,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(9), 1,
      sym_open_squiggly,
    ACTIONS(13), 1,
      sym_open_arrow,
    ACTIONS(231), 1,
      anon_sym_COLON,
    ACTIONS(233), 1,
      sym_open_square,
    STATE(64), 1,
      sym_comment,
    STATE(54), 2,
      sym_message_value,
      sym_message_list,
  [1747] = 4,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(235), 2,
      sym_close_square,
      anon_sym_SLASH,
    ACTIONS(237), 2,
      anon_sym_DOT,
      sym_identifier,
    STATE(65), 2,
      sym_comment,
      aux_sym_type_name_repeat1,
  [1763] = 3,
    ACTIONS(3), 1,
      anon_sym_POUND,
    STATE(66), 1,
      sym_comment,
    ACTIONS(240), 5,
      ts_builtin_sym_end,
      sym_close_squiggly,
      sym_open_square,
      sym_close_arrow,
      sym_identifier,
  [1777] = 3,
    ACTIONS(3), 1,
      anon_sym_POUND,
    STATE(67), 1,
      sym_comment,
    ACTIONS(242), 5,
      ts_builtin_sym_end,
      sym_close_squiggly,
      sym_open_square,
      sym_close_arrow,
      sym_identifier,
  [1791] = 3,
    ACTIONS(3), 1,
      anon_sym_POUND,
    STATE(68), 1,
      sym_comment,
    ACTIONS(205), 5,
      ts_builtin_sym_end,
      sym_close_squiggly,
      sym_open_square,
      sym_close_arrow,
      sym_identifier,
  [1805] = 3,
    ACTIONS(3), 1,
      anon_sym_POUND,
    STATE(69), 1,
      sym_comment,
    ACTIONS(183), 5,
      anon_sym_COMMA,
      sym_close_square,
      anon_sym_DOT,
      aux_sym_exp_token1,
      aux_sym_float_token1,
  [1819] = 6,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(244), 1,
      sym_close_square,
    ACTIONS(246), 1,
      anon_sym_SLASH,
    STATE(65), 1,
      aux_sym_type_name_repeat1,
    STATE(70), 1,
      sym_comment,
    ACTIONS(248), 2,
      anon_sym_DOT,
      sym_identifier,
  [1839] = 6,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(250), 1,
      sym_close_square,
    ACTIONS(252), 1,
      anon_sym_SLASH,
    STATE(70), 1,
      aux_sym_type_name_repeat1,
    STATE(71), 1,
      sym_comment,
    ACTIONS(248), 2,
      anon_sym_DOT,
      sym_identifier,
  [1859] = 3,
    ACTIONS(3), 1,
      anon_sym_POUND,
    STATE(72), 1,
      sym_comment,
    ACTIONS(254), 5,
      ts_builtin_sym_end,
      sym_close_squiggly,
      sym_open_square,
      sym_close_arrow,
      sym_identifier,
  [1873] = 3,
    ACTIONS(3), 1,
      anon_sym_POUND,
    STATE(73), 1,
      sym_comment,
    ACTIONS(256), 5,
      ts_builtin_sym_end,
      sym_close_squiggly,
      sym_open_square,
      sym_close_arrow,
      sym_identifier,
  [1887] = 5,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(250), 1,
      sym_close_square,
    STATE(74), 1,
      sym_comment,
    STATE(79), 1,
      aux_sym_type_name_repeat1,
    ACTIONS(248), 2,
      anon_sym_DOT,
      sym_identifier,
  [1904] = 6,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(227), 1,
      aux_sym_exp_token1,
    ACTIONS(258), 1,
      aux_sym_float_lit_token1,
    ACTIONS(260), 1,
      aux_sym_float_token1,
    STATE(75), 1,
      sym_comment,
    STATE(98), 1,
      sym_exp,
  [1923] = 6,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(9), 1,
      sym_open_squiggly,
    ACTIONS(13), 1,
      sym_open_arrow,
    ACTIONS(262), 1,
      sym_close_square,
    STATE(76), 1,
      sym_comment,
    STATE(82), 1,
      sym_message_value,
  [1942] = 3,
    ACTIONS(3), 1,
      anon_sym_POUND,
    STATE(77), 1,
      sym_comment,
    ACTIONS(264), 4,
      anon_sym_COLON,
      sym_open_squiggly,
      sym_open_square,
      sym_open_arrow,
  [1955] = 3,
    ACTIONS(3), 1,
      anon_sym_POUND,
    STATE(78), 1,
      sym_comment,
    ACTIONS(266), 4,
      sym_close_square,
      anon_sym_SLASH,
      anon_sym_DOT,
      sym_identifier,
  [1968] = 5,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(244), 1,
      sym_close_square,
    STATE(65), 1,
      aux_sym_type_name_repeat1,
    STATE(79), 1,
      sym_comment,
    ACTIONS(248), 2,
      anon_sym_DOT,
      sym_identifier,
  [1985] = 3,
    ACTIONS(3), 1,
      anon_sym_POUND,
    STATE(80), 1,
      sym_comment,
    ACTIONS(268), 4,
      anon_sym_COLON,
      sym_open_squiggly,
      sym_open_square,
      sym_open_arrow,
  [1998] = 3,
    ACTIONS(3), 1,
      anon_sym_POUND,
    STATE(81), 1,
      sym_comment,
    ACTIONS(270), 4,
      anon_sym_COLON,
      sym_open_squiggly,
      sym_open_square,
      sym_open_arrow,
  [2011] = 5,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(272), 1,
      anon_sym_COMMA,
    ACTIONS(274), 1,
      sym_close_square,
    STATE(82), 1,
      sym_comment,
    STATE(86), 1,
      aux_sym_message_list_repeat1,
  [2027] = 4,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(276), 1,
      anon_sym_COMMA,
    ACTIONS(279), 1,
      sym_close_square,
    STATE(83), 2,
      sym_comment,
      aux_sym_scalar_list_repeat1,
  [2041] = 5,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(281), 1,
      sym_identifier,
    STATE(84), 1,
      sym_comment,
    STATE(108), 1,
      sym_domain,
    STATE(112), 1,
      sym_type_name,
  [2057] = 5,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(227), 1,
      aux_sym_exp_token1,
    ACTIONS(260), 1,
      aux_sym_float_token1,
    STATE(85), 1,
      sym_comment,
    STATE(98), 1,
      sym_exp,
  [2073] = 5,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(272), 1,
      anon_sym_COMMA,
    ACTIONS(283), 1,
      sym_close_square,
    STATE(86), 1,
      sym_comment,
    STATE(87), 1,
      aux_sym_message_list_repeat1,
  [2089] = 4,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(285), 1,
      anon_sym_COMMA,
    ACTIONS(288), 1,
      sym_close_square,
    STATE(87), 2,
      sym_comment,
      aux_sym_message_list_repeat1,
  [2103] = 5,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(9), 1,
      sym_open_squiggly,
    ACTIONS(13), 1,
      sym_open_arrow,
    STATE(88), 1,
      sym_comment,
    STATE(94), 1,
      sym_message_value,
  [2119] = 5,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(290), 1,
      anon_sym_COMMA,
    ACTIONS(292), 1,
      sym_close_square,
    STATE(89), 1,
      sym_comment,
    STATE(91), 1,
      aux_sym_scalar_list_repeat1,
  [2135] = 5,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(227), 1,
      aux_sym_exp_token1,
    ACTIONS(294), 1,
      aux_sym_float_token1,
    STATE(90), 1,
      sym_comment,
    STATE(102), 1,
      sym_exp,
  [2151] = 5,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(290), 1,
      anon_sym_COMMA,
    ACTIONS(296), 1,
      sym_close_square,
    STATE(83), 1,
      aux_sym_scalar_list_repeat1,
    STATE(91), 1,
      sym_comment,
  [2167] = 3,
    ACTIONS(3), 1,
      anon_sym_POUND,
    STATE(92), 1,
      sym_comment,
    ACTIONS(279), 2,
      anon_sym_COMMA,
      sym_close_square,
  [2178] = 4,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(298), 1,
      sym_identifier,
    STATE(93), 1,
      sym_comment,
    STATE(110), 1,
      sym_type_name,
  [2191] = 3,
    ACTIONS(3), 1,
      anon_sym_POUND,
    STATE(94), 1,
      sym_comment,
    ACTIONS(288), 2,
      anon_sym_COMMA,
      sym_close_square,
  [2202] = 3,
    ACTIONS(59), 1,
      anon_sym_POUND,
    ACTIONS(300), 1,
      aux_sym_comment_token1,
    STATE(95), 1,
      sym_comment,
  [2212] = 3,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(302), 1,
      sym_hex,
    STATE(96), 1,
      sym_comment,
  [2222] = 3,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(304), 1,
      aux_sym_float_lit_token1,
    STATE(97), 1,
      sym_comment,
  [2232] = 3,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(294), 1,
      aux_sym_float_token1,
    STATE(98), 1,
      sym_comment,
  [2242] = 3,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(306), 1,
      sym_close_squiggly,
    STATE(99), 1,
      sym_comment,
  [2252] = 3,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(308), 1,
      sym_hex,
    STATE(100), 1,
      sym_comment,
  [2262] = 3,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(310), 1,
      sym_hex,
    STATE(101), 1,
      sym_comment,
  [2272] = 3,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(312), 1,
      aux_sym_float_token1,
    STATE(102), 1,
      sym_comment,
  [2282] = 3,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(306), 1,
      sym_close_arrow,
    STATE(103), 1,
      sym_comment,
  [2292] = 3,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(314), 1,
      sym_hex,
    STATE(104), 1,
      sym_comment,
  [2302] = 3,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(316), 1,
      sym_hex,
    STATE(105), 1,
      sym_comment,
  [2312] = 3,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(260), 1,
      aux_sym_float_token1,
    STATE(106), 1,
      sym_comment,
  [2322] = 3,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(318), 1,
      sym_hex,
    STATE(107), 1,
      sym_comment,
  [2332] = 3,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(320), 1,
      anon_sym_SLASH,
    STATE(108), 1,
      sym_comment,
  [2342] = 3,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(322), 1,
      aux_sym_float_lit_token1,
    STATE(109), 1,
      sym_comment,
  [2352] = 3,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(324), 1,
      sym_close_square,
    STATE(110), 1,
      sym_comment,
  [2362] = 3,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(326), 1,
      sym_hex,
    STATE(111), 1,
      sym_comment,
  [2372] = 3,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(328), 1,
      sym_close_square,
    STATE(112), 1,
      sym_comment,
  [2382] = 3,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(330), 1,
      aux_sym_float_token1,
    STATE(113), 1,
      sym_comment,
  [2392] = 3,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(332), 1,
      sym_hex,
    STATE(114), 1,
      sym_comment,
  [2402] = 3,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(334), 1,
      sym_hex,
    STATE(115), 1,
      sym_comment,
  [2412] = 3,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(336), 1,
      sym_hex,
    STATE(116), 1,
      sym_comment,
  [2422] = 3,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(338), 1,
      sym_oct,
    STATE(117), 1,
      sym_comment,
  [2432] = 3,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(340), 1,
      ts_builtin_sym_end,
    STATE(118), 1,
      sym_comment,
  [2442] = 3,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(229), 1,
      aux_sym_float_token1,
    STATE(119), 1,
      sym_comment,
  [2452] = 3,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(342), 1,
      sym_hex,
    STATE(120), 1,
      sym_comment,
  [2462] = 3,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(344), 1,
      sym_oct,
    STATE(121), 1,
      sym_comment,
  [2472] = 3,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(346), 1,
      sym_hex,
    STATE(122), 1,
      sym_comment,
  [2482] = 3,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(348), 1,
      sym_hex,
    STATE(123), 1,
      sym_comment,
  [2492] = 3,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(350), 1,
      sym_hex,
    STATE(124), 1,
      sym_comment,
  [2502] = 3,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(352), 1,
      sym_hex,
    STATE(125), 1,
      sym_comment,
  [2512] = 3,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(354), 1,
      sym_hex,
    STATE(126), 1,
      sym_comment,
  [2522] = 3,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(356), 1,
      sym_hex,
    STATE(127), 1,
      sym_comment,
  [2532] = 3,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(358), 1,
      sym_hex,
    STATE(128), 1,
      sym_comment,
  [2542] = 3,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(360), 1,
      sym_hex,
    STATE(129), 1,
      sym_comment,
  [2552] = 3,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(362), 1,
      sym_hex,
    STATE(130), 1,
      sym_comment,
  [2562] = 1,
    ACTIONS(364), 1,
      ts_builtin_sym_end,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 72,
  [SMALL_STATE(4)] = 142,
  [SMALL_STATE(5)] = 184,
  [SMALL_STATE(6)] = 228,
  [SMALL_STATE(7)] = 272,
  [SMALL_STATE(8)] = 316,
  [SMALL_STATE(9)] = 358,
  [SMALL_STATE(10)] = 416,
  [SMALL_STATE(11)] = 460,
  [SMALL_STATE(12)] = 489,
  [SMALL_STATE(13)] = 518,
  [SMALL_STATE(14)] = 547,
  [SMALL_STATE(15)] = 576,
  [SMALL_STATE(16)] = 605,
  [SMALL_STATE(17)] = 634,
  [SMALL_STATE(18)] = 660,
  [SMALL_STATE(19)] = 686,
  [SMALL_STATE(20)] = 712,
  [SMALL_STATE(21)] = 738,
  [SMALL_STATE(22)] = 764,
  [SMALL_STATE(23)] = 790,
  [SMALL_STATE(24)] = 816,
  [SMALL_STATE(25)] = 842,
  [SMALL_STATE(26)] = 868,
  [SMALL_STATE(27)] = 894,
  [SMALL_STATE(28)] = 920,
  [SMALL_STATE(29)] = 946,
  [SMALL_STATE(30)] = 979,
  [SMALL_STATE(31)] = 1010,
  [SMALL_STATE(32)] = 1045,
  [SMALL_STATE(33)] = 1078,
  [SMALL_STATE(34)] = 1108,
  [SMALL_STATE(35)] = 1144,
  [SMALL_STATE(36)] = 1180,
  [SMALL_STATE(37)] = 1210,
  [SMALL_STATE(38)] = 1229,
  [SMALL_STATE(39)] = 1248,
  [SMALL_STATE(40)] = 1267,
  [SMALL_STATE(41)] = 1288,
  [SMALL_STATE(42)] = 1307,
  [SMALL_STATE(43)] = 1326,
  [SMALL_STATE(44)] = 1345,
  [SMALL_STATE(45)] = 1377,
  [SMALL_STATE(46)] = 1409,
  [SMALL_STATE(47)] = 1426,
  [SMALL_STATE(48)] = 1443,
  [SMALL_STATE(49)] = 1460,
  [SMALL_STATE(50)] = 1477,
  [SMALL_STATE(51)] = 1494,
  [SMALL_STATE(52)] = 1511,
  [SMALL_STATE(53)] = 1528,
  [SMALL_STATE(54)] = 1546,
  [SMALL_STATE(55)] = 1564,
  [SMALL_STATE(56)] = 1580,
  [SMALL_STATE(57)] = 1596,
  [SMALL_STATE(58)] = 1612,
  [SMALL_STATE(59)] = 1628,
  [SMALL_STATE(60)] = 1644,
  [SMALL_STATE(61)] = 1660,
  [SMALL_STATE(62)] = 1678,
  [SMALL_STATE(63)] = 1701,
  [SMALL_STATE(64)] = 1724,
  [SMALL_STATE(65)] = 1747,
  [SMALL_STATE(66)] = 1763,
  [SMALL_STATE(67)] = 1777,
  [SMALL_STATE(68)] = 1791,
  [SMALL_STATE(69)] = 1805,
  [SMALL_STATE(70)] = 1819,
  [SMALL_STATE(71)] = 1839,
  [SMALL_STATE(72)] = 1859,
  [SMALL_STATE(73)] = 1873,
  [SMALL_STATE(74)] = 1887,
  [SMALL_STATE(75)] = 1904,
  [SMALL_STATE(76)] = 1923,
  [SMALL_STATE(77)] = 1942,
  [SMALL_STATE(78)] = 1955,
  [SMALL_STATE(79)] = 1968,
  [SMALL_STATE(80)] = 1985,
  [SMALL_STATE(81)] = 1998,
  [SMALL_STATE(82)] = 2011,
  [SMALL_STATE(83)] = 2027,
  [SMALL_STATE(84)] = 2041,
  [SMALL_STATE(85)] = 2057,
  [SMALL_STATE(86)] = 2073,
  [SMALL_STATE(87)] = 2089,
  [SMALL_STATE(88)] = 2103,
  [SMALL_STATE(89)] = 2119,
  [SMALL_STATE(90)] = 2135,
  [SMALL_STATE(91)] = 2151,
  [SMALL_STATE(92)] = 2167,
  [SMALL_STATE(93)] = 2178,
  [SMALL_STATE(94)] = 2191,
  [SMALL_STATE(95)] = 2202,
  [SMALL_STATE(96)] = 2212,
  [SMALL_STATE(97)] = 2222,
  [SMALL_STATE(98)] = 2232,
  [SMALL_STATE(99)] = 2242,
  [SMALL_STATE(100)] = 2252,
  [SMALL_STATE(101)] = 2262,
  [SMALL_STATE(102)] = 2272,
  [SMALL_STATE(103)] = 2282,
  [SMALL_STATE(104)] = 2292,
  [SMALL_STATE(105)] = 2302,
  [SMALL_STATE(106)] = 2312,
  [SMALL_STATE(107)] = 2322,
  [SMALL_STATE(108)] = 2332,
  [SMALL_STATE(109)] = 2342,
  [SMALL_STATE(110)] = 2352,
  [SMALL_STATE(111)] = 2362,
  [SMALL_STATE(112)] = 2372,
  [SMALL_STATE(113)] = 2382,
  [SMALL_STATE(114)] = 2392,
  [SMALL_STATE(115)] = 2402,
  [SMALL_STATE(116)] = 2412,
  [SMALL_STATE(117)] = 2422,
  [SMALL_STATE(118)] = 2432,
  [SMALL_STATE(119)] = 2442,
  [SMALL_STATE(120)] = 2452,
  [SMALL_STATE(121)] = 2462,
  [SMALL_STATE(122)] = 2472,
  [SMALL_STATE(123)] = 2482,
  [SMALL_STATE(124)] = 2492,
  [SMALL_STATE(125)] = 2502,
  [SMALL_STATE(126)] = 2512,
  [SMALL_STATE(127)] = 2522,
  [SMALL_STATE(128)] = 2532,
  [SMALL_STATE(129)] = 2542,
  [SMALL_STATE(130)] = 2552,
  [SMALL_STATE(131)] = 2562,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT(95),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT(84),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(77),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(34),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(35),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(97),
  [17] = {.entry = {.count = 1, .reusable = true}}, SHIFT(50),
  [19] = {.entry = {.count = 1, .reusable = true}}, SHIFT(45),
  [21] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [23] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [25] = {.entry = {.count = 1, .reusable = false}}, SHIFT(40),
  [27] = {.entry = {.count = 1, .reusable = true}}, SHIFT(40),
  [29] = {.entry = {.count = 1, .reusable = true}}, SHIFT(48),
  [31] = {.entry = {.count = 1, .reusable = true}}, SHIFT(60),
  [33] = {.entry = {.count = 1, .reusable = true}}, SHIFT(44),
  [35] = {.entry = {.count = 1, .reusable = false}}, SHIFT(69),
  [37] = {.entry = {.count = 1, .reusable = true}}, SHIFT(69),
  [39] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_double_string_repeat1, 2),
  [41] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_double_string_repeat1, 2), SHIFT_REPEAT(22),
  [44] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_double_string_repeat1, 2), SHIFT_REPEAT(18),
  [47] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_double_string_repeat1, 2), SHIFT_REPEAT(121),
  [50] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_double_string_repeat1, 2), SHIFT_REPEAT(122),
  [53] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_double_string_repeat1, 2), SHIFT_REPEAT(129),
  [56] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_double_string_repeat1, 2), SHIFT_REPEAT(114),
  [59] = {.entry = {.count = 1, .reusable = false}}, SHIFT(95),
  [61] = {.entry = {.count = 1, .reusable = false}}, SHIFT(38),
  [63] = {.entry = {.count = 1, .reusable = false}}, SHIFT(25),
  [65] = {.entry = {.count = 1, .reusable = false}}, SHIFT(26),
  [67] = {.entry = {.count = 1, .reusable = false}}, SHIFT(117),
  [69] = {.entry = {.count = 1, .reusable = false}}, SHIFT(116),
  [71] = {.entry = {.count = 1, .reusable = false}}, SHIFT(100),
  [73] = {.entry = {.count = 1, .reusable = false}}, SHIFT(123),
  [75] = {.entry = {.count = 1, .reusable = false}}, SHIFT(41),
  [77] = {.entry = {.count = 1, .reusable = false}}, SHIFT(22),
  [79] = {.entry = {.count = 1, .reusable = false}}, SHIFT(18),
  [81] = {.entry = {.count = 1, .reusable = false}}, SHIFT(121),
  [83] = {.entry = {.count = 1, .reusable = false}}, SHIFT(122),
  [85] = {.entry = {.count = 1, .reusable = false}}, SHIFT(129),
  [87] = {.entry = {.count = 1, .reusable = false}}, SHIFT(114),
  [89] = {.entry = {.count = 1, .reusable = false}}, SHIFT(43),
  [91] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_single_string_repeat1, 2),
  [93] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_single_string_repeat1, 2), SHIFT_REPEAT(25),
  [96] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_single_string_repeat1, 2), SHIFT_REPEAT(26),
  [99] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_single_string_repeat1, 2), SHIFT_REPEAT(117),
  [102] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_single_string_repeat1, 2), SHIFT_REPEAT(116),
  [105] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_single_string_repeat1, 2), SHIFT_REPEAT(100),
  [108] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_single_string_repeat1, 2), SHIFT_REPEAT(123),
  [111] = {.entry = {.count = 1, .reusable = false}}, SHIFT(39),
  [113] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_string_escape, 2),
  [115] = {.entry = {.count = 1, .reusable = false}}, SHIFT(16),
  [117] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_string_escape, 3),
  [119] = {.entry = {.count = 1, .reusable = false}}, SHIFT(21),
  [121] = {.entry = {.count = 1, .reusable = false}}, SHIFT(23),
  [123] = {.entry = {.count = 1, .reusable = false}}, SHIFT(27),
  [125] = {.entry = {.count = 1, .reusable = false}}, SHIFT(12),
  [127] = {.entry = {.count = 1, .reusable = false}}, SHIFT(24),
  [129] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_string_escape, 5),
  [131] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_string_escape, 1),
  [133] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_string_escape, 6),
  [135] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_string_escape, 4),
  [137] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_double_string_repeat1, 1),
  [139] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_single_string_repeat1, 1),
  [141] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_scalar_value, 1),
  [143] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_scalar_value_repeat1, 2),
  [145] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_scalar_value_repeat1, 2), SHIFT_REPEAT(7),
  [148] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_scalar_value_repeat1, 2), SHIFT_REPEAT(6),
  [151] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_message, 1),
  [153] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_message_repeat1, 2),
  [155] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_message_repeat1, 2), SHIFT_REPEAT(84),
  [158] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_message_repeat1, 2), SHIFT_REPEAT(77),
  [161] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_number, 2),
  [163] = {.entry = {.count = 1, .reusable = true}}, SHIFT(75),
  [165] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_number, 2),
  [167] = {.entry = {.count = 1, .reusable = false}}, SHIFT(109),
  [169] = {.entry = {.count = 1, .reusable = false}}, SHIFT(49),
  [171] = {.entry = {.count = 1, .reusable = true}}, SHIFT(46),
  [173] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_number, 1),
  [175] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_number, 1),
  [177] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_string, 1),
  [179] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_single_string, 3),
  [181] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_double_string, 3),
  [183] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_dec_int, 1),
  [185] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_dec_int, 1),
  [187] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_double_string, 2),
  [189] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_scalar_value_repeat1, 1),
  [191] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_single_string, 2),
  [193] = {.entry = {.count = 1, .reusable = true}}, SHIFT(51),
  [195] = {.entry = {.count = 1, .reusable = true}}, SHIFT(52),
  [197] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_message_value, 2),
  [199] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_message_value, 3),
  [201] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_float, 2),
  [203] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_signed_identifier, 2),
  [205] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_message_field, 3),
  [207] = {.entry = {.count = 1, .reusable = true}}, SHIFT(66),
  [209] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_message_field, 2),
  [211] = {.entry = {.count = 1, .reusable = true}}, SHIFT(68),
  [213] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_message_list, 4),
  [215] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_scalar_list, 3),
  [217] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_message_list, 2),
  [219] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_scalar_list, 4),
  [221] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_message_list, 3),
  [223] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_scalar_field, 3),
  [225] = {.entry = {.count = 1, .reusable = true}}, SHIFT(67),
  [227] = {.entry = {.count = 1, .reusable = true}}, SHIFT(109),
  [229] = {.entry = {.count = 1, .reusable = true}}, SHIFT(49),
  [231] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [233] = {.entry = {.count = 1, .reusable = true}}, SHIFT(76),
  [235] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_type_name_repeat1, 2),
  [237] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_type_name_repeat1, 2), SHIFT_REPEAT(78),
  [240] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_message_field, 4),
  [242] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_scalar_field, 4),
  [244] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_type_name, 2),
  [246] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_domain, 2),
  [248] = {.entry = {.count = 1, .reusable = true}}, SHIFT(78),
  [250] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_type_name, 1),
  [252] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_domain, 1),
  [254] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_field, 1),
  [256] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_message_repeat1, 1),
  [258] = {.entry = {.count = 1, .reusable = true}}, SHIFT(90),
  [260] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_float_lit, 2),
  [262] = {.entry = {.count = 1, .reusable = true}}, SHIFT(57),
  [264] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_field_name, 1),
  [266] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_type_name_repeat1, 1),
  [268] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_any_name, 5),
  [270] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_extension_name, 3),
  [272] = {.entry = {.count = 1, .reusable = true}}, SHIFT(88),
  [274] = {.entry = {.count = 1, .reusable = true}}, SHIFT(59),
  [276] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_scalar_list_repeat1, 2), SHIFT_REPEAT(9),
  [279] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_scalar_list_repeat1, 2),
  [281] = {.entry = {.count = 1, .reusable = true}}, SHIFT(71),
  [283] = {.entry = {.count = 1, .reusable = true}}, SHIFT(55),
  [285] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_message_list_repeat1, 2), SHIFT_REPEAT(88),
  [288] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_message_list_repeat1, 2),
  [290] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [292] = {.entry = {.count = 1, .reusable = true}}, SHIFT(56),
  [294] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_float_lit, 3),
  [296] = {.entry = {.count = 1, .reusable = true}}, SHIFT(58),
  [298] = {.entry = {.count = 1, .reusable = true}}, SHIFT(74),
  [300] = {.entry = {.count = 1, .reusable = false}}, SHIFT(131),
  [302] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [304] = {.entry = {.count = 1, .reusable = true}}, SHIFT(85),
  [306] = {.entry = {.count = 1, .reusable = true}}, SHIFT(47),
  [308] = {.entry = {.count = 1, .reusable = true}}, SHIFT(120),
  [310] = {.entry = {.count = 1, .reusable = true}}, SHIFT(105),
  [312] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_float_lit, 4),
  [314] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [316] = {.entry = {.count = 1, .reusable = true}}, SHIFT(107),
  [318] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [320] = {.entry = {.count = 1, .reusable = true}}, SHIFT(93),
  [322] = {.entry = {.count = 1, .reusable = true}}, SHIFT(113),
  [324] = {.entry = {.count = 1, .reusable = true}}, SHIFT(80),
  [326] = {.entry = {.count = 1, .reusable = true}}, SHIFT(101),
  [328] = {.entry = {.count = 1, .reusable = true}}, SHIFT(81),
  [330] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_exp, 2),
  [332] = {.entry = {.count = 1, .reusable = true}}, SHIFT(130),
  [334] = {.entry = {.count = 1, .reusable = true}}, SHIFT(104),
  [336] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [338] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [340] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [342] = {.entry = {.count = 1, .reusable = true}}, SHIFT(115),
  [344] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [346] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [348] = {.entry = {.count = 1, .reusable = true}}, SHIFT(111),
  [350] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [352] = {.entry = {.count = 1, .reusable = true}}, SHIFT(96),
  [354] = {.entry = {.count = 1, .reusable = true}}, SHIFT(124),
  [356] = {.entry = {.count = 1, .reusable = true}}, SHIFT(125),
  [358] = {.entry = {.count = 1, .reusable = true}}, SHIFT(126),
  [360] = {.entry = {.count = 1, .reusable = true}}, SHIFT(127),
  [362] = {.entry = {.count = 1, .reusable = true}}, SHIFT(128),
  [364] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_comment, 2),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_textproto() {
  static const TSLanguage language = {
    .version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
