package forest

import (
	"errors"
	"fmt"
	"os"
	"path/filepath"
	"reflect"
	"slices"
	"strings"
	"sync"
	"testing"

	"golang.org/x/exp/maps"
)

func TestFTDetectorLoad(t *testing.T) {
	t.Skip("Tested implicitly via the entire test suite: if it passes, then the loading worked as expected")
}

func TestDetectLanguage(t *testing.T) { //nolint:funlen,tparallel // no, subtests MUST NOT call t.Parallel here!
	t.Parallel()

	// Patterns starting with dot will be interpreted as file extensions
	// and be prefixed with "foobar". If you want to test an actual file
	// starting with a dot, simply use a path in front of it (foo/.somefile).
	testCases := []struct{ s, exp string }{
		{".4th", "forth"},
		{".6502", "merlin6502"},
		{".C", "cpp"},
		{".F03", "fortran"},
		{".F08", "fortran"},
		{".F77", "fortran"},
		{".F90", "fortran"},
		{".F95", "fortran"},
		{".FOR", "fortran"},
		{".FPP", "fortran"},
		{".FTN", "fortran"},
		{".H", "cpp"},
		{".INI", "ini"},
		{".L", "commonlisp"},
		{".M", "matlab"},
		{".PL", "perl"},
		{".R", "r"},
		{".Rnw", "rnoweb"},
		{".S", "asm"},
		{".S6502", "merlin6502"},
		{".Snw", "rnoweb"},
		{".abap", "abap"},
		{".ada", "ada"},
		{".adb", "ada"},
		{".ads", "ada"},
		{".agda", "agda"},
		{".aiken", "aiken"},
		{".amber", "amber"},
		{".angular", "angular"},
		{".apex", "apex"},
		{".asm", "nasm"},
		{".astro", "astro"},
		{".august", "august"},
		{".awk", "awk"},
		{".bash", "bash"},
		{".bass", "bass"},
		{".bb", "bitbake"},
		{".bbappend", "bitbake"},
		{".bbclass", "bitbake"},
		{".beancount", "beancount"},
		{".bend", "bend"},
		{".bib", "bibtex"},
		{".bibtex", "bibtex"},
		{".bicep", "bicep"},
		{".bicepparam", "bicep"},
		{".blade", "blade"},
		{".blp", "blueprint"},
		{".bp", "bp"},
		{".brs", "brightscript"},
		{".bsv", "bluespec"},
		{".builder", "ruby"},
		{".bzl", "starlark"},
		{".c", "c"},
		{".c++", "cpp"},
		{".ca65", "ca65"},
		{".cairo", "cairo"},
		{".cake", "c_sharp"},
		{".calc", "calc"},
		{".capnp", "capnp"},
		{".cbl", "cobol"},
		{".cc", "cpp"},
		{".ccp", "cobol"},
		{".cds", "cds"},
		{".cedar", "cedar"},
		{".cel", "cel"},
		{".cg", "cg"},
		{".chatito", "chatito"},
		{".chem", "pic"},
		{".circom", "circom"},
		{".cl", "commonlisp"},
		{".clar", "clarity"},
		{".cleancopy", "cleancopy"},
		{".clingo", "clingo"},
		{".clj", "clojure"},
		{".cljc", "clojure"},
		{".cljs", "clojure"},
		{".cljx", "clojure"},
		{".cmake", "cmake"},
		{".cmdl", "cmdl"},
		{".cob", "cobol"},
		{".cobol", "cobol"},
		{".cognate", "cognate"},
		{".comment", "comment"},
		{".cook", "cooklang"},
		{".corn", "corn"},
		{".cpon", "cpon"},
		{".cpp", "cpp"},
		{".cpy", "cobol"},
		{".cr", "crystal"},
		{".cs", "c_sharp"},
		{".csh", "bash"},
		{".csl", "kusto"},
		{".css", "css"},
		{".csv", "csv"},
		{".csx", "c_sharp"},
		{".cu", "cuda"},
		{".cue", "cue"},
		{".cuh", "cuda"},
		{".d", "d"},
		{".dale", "dale"},
		{".dart", "dart"},
		{".dbml", "dbml"},
		{".dhall", "dhall"},
		{".di", "d"},
		{".diff", "diff"},
		{".disassembly", "disassembly"},
		{".djot", "djot"},
		{".dockerfile", "dockerfile"},
		{".dot", "dot"},
		{".drt", "dart"},
		{".dsp", "faust"},
		{".dtd", "dtd"},
		{".dts", "devicetree"},
		{".ebnf", "ebnf"},
		{".eds", "eds"},
		{".eex", "eex"},
		{".el", "commonlisp"},
		{".elm", "elm"},
		{".elsa", "elsa"},
		{".elv", "elvish"},
		{".embedded_template", "embedded_template"},
		{".env", "dotenv"},
		{".erl", "erlang"},
		{".ex", "elixir"},
		{".exs", "elixir"},
		{".f", "fortran"},
		{".f03", "fortran"},
		{".f08", "fortran"},
		{".f77", "fortran"},
		{".f90", "fortran"},
		{".f95", "fortran"},
		{".facility", "facility"},
		{".familymarkup", "familymarkup"},
		{".fastbuild", "fastbuild"},
		{".feature", "gherkin"},
		{".fidl", "fidl"},
		{".filter", "poe_filter"},
		{".fin", "fin"},
		{".fir", "firrtl"},
		{".fish", "fish"},
		{".flamingo", "flamingo"},
		{".fluentbit", "fluentbit"},
		{".fnl", "fennel"},
		{".foam", "foam"},
		{".for", "fortran"},
		{".fortran", "fortran"},
		{".fpp", "fortran"},
		{".fs", "fsharp"},
		{".fsh", "fsh"},
		{".fsi", "fsharp"},
		{".fsx", "fsharp"},
		{".ft", "forth"},
		{".fth", "forth"},
		{".ftn", "fortran"},
		{".fun", "sml"},
		{".func", "func"},
		{".fusion", "fusion"},
		{".gawk", "awk"},
		{".gd", "gdscript"},
		{".gdnlib", "godot_resource"},
		{".gdns", "godot_resource"},
		{".gdshader", "gdshader"},
		{".gemspec", "ruby"},
		{".gjs", "glimmer"},
		{".gleam", "gleam"},
		{".glint", "glint"},
		{".glsl", "glsl"},
		{".gn", "gn"},
		{".gni", "gn"},
		{".gnu", "gnuplot"},
		{".gnuplot", "gnuplot"},
		{".go", "go"},
		{".gobra", "gobra"},
		{".goctl", "goctl"},
		{".godot", "godot_resource"},
		{".goo", "gooscript"},
		{".gp", "gnuplot"},
		{".gpg", "gpg"},
		{".gpi", "gnuplot"},
		{".gpi", "gnuplot"},
		{".gpr", "ada"},
		{".gql", "graphql"},
		{".gradle", "groovy"},
		{".graphql", "graphql"},
		{".graphqls", "graphql"},
		{".gren", "gren"},
		{".groovy", "groovy"},
		{".gstlaunch", "gstlaunch"},
		{".gts", "glimmer"},
		{".gv", "dot"},
		{".h", "c"},
		{".ha", "hare"},
		{".hack", "hack"},
		{".hackpartial", "hack"},
		{".haml", "haml"},
		{".hcl", "hcl"},
		{".heex", "heex"},
		{".helm", "helm"},
		{".hh", "cpp"},
		{".hjson", "hjson"},
		{".hlsl", "hlsl"},
		{".hlsli", "hlsl"},
		{".hocon", "hocon"},
		{".hoon", "hoon"},
		{".hpp", "cpp"},
		{".hrl", "erlang"},
		{".hs", "haskell"},
		{".hs-boot", "haskell"},
		{".hsc", "haskell"},
		{".hsig", "haskell"},
		{".htm", "html"},
		{".html", "html"},
		{".htmlaskama", "htmlaskama"},
		{".htmldjango", "htmldjango"},
		{".http", "http"},
		{".http2", "http2"},
		{".hungarian", "hungarian"},
		{".hurl", "hurl"},
		{".hyprlang", "hyprlang"},
		{".idl", "idl"},
		{".idr", "idris"},
		{".ignis", "ignis"},
		{".ini", "ini"},
		{".ink", "ink"},
		{".inko", "inko"},
		{".ino", "arduino"},
		{".ipd", "starlark"},
		{".ispc", "ispc"},
		{".jade", "pug"},
		{".janet", "janet_simple"},
		{".jav", "java"},
		{".java", "java"},
		{".jl", "julia"},
		{".journal", "ledger"},
		{".jq", "jq"},
		{".js", "javascript"},
		{".jsdoc", "jsdoc"},
		{".json", "json"},
		{".json5", "json5"},
		{".jsonc", "jsonc"},
		{".jsonnet", "jsonnet"},
		{".just", "just"},
		{".kcl", "kcl"},
		{".kconfig", "kconfig"},
		{".kdl", "kdl"},
		{".koan", "koan"},
		{".kojo", "scala"},
		{".koto", "koto"},
		{".kql", "kusto"},
		{".ksh", "bash"},
		{".kt", "kotlin"},
		{".ktm", "kotlin"},
		{".kts", "kotlin"},
		{".l", "commonlisp"},
		{".lalrpop", "lalrpop"},
		{".ld", "linkerscript"},
		{".ldg", "ldg"},
		{".lds", "linkerscript"},
		{".ledger", "ledger"},
		{".leo", "leo"},
		{".lexc", "lexc"},
		{".lexd", "lexd"},
		{".libsonnet", "jsonnet"},
		{".lidr", "idris"},
		{".liq", "liquidsoap"},
		{".liquid", "liquid"},
		{".lisp", "commonlisp"},
		{".ll", "llvm"},
		{".lox", "lox"},
		{".lsp", "commonlisp"},
		{".lua", "lua"},
		{".luadoc", "luadoc"},
		{".luap", "luap"},
		{".luau", "luau"},
		{".m", "objc"},
		{".m3u", "hlsplaylist"},
		{".m3u8", "hlsplaylist"},
		{".m68k", "m68k"},
		{".magik", "magik"},
		{".mak", "make"},
		{".make", "make"},
		{".makefile", "make"},
		{".markdown_inline", "markdown_inline"},
		{".mcfuncx", "mcfuncx"},
		{".md", "markdown"},
		{".menhir", "menhir"},
		{".mermaid", "mermaid"},
		{".mk", "make"},
		{".mkfile", "make"},
		{".mkii", "context"},
		{".mkiv", "context"},
		{".mklx", "context"},
		{".mkvi", "context"},
		{".mkxl", "context"},
		{".ml", "ocaml"},
		{".mli", "ocaml"},
		{".mlip", "ocaml"},
		{".mlir", "mlir"},
		{".mll", "ocaml"},
		{".mlp", "ocaml"},
		{".mlt", "ocaml"},
		{".mly", "ocaml"},
		{".mmd", "mermaid"},
		{".mmdc", "mermaid"},
		{".mo", "motoko"},
		{".move", "move"},
		{".move_on_aptos", "move_on_aptos"},
		{".muttrc", "muttrc"},
		{".nasm", "nasm"},
		{".nesfab", "nesfab"},
		{".nickel", "nickel"},
		{".nim", "nim"},
		{".nim_format_string", "nim_format_string"},
		{".nimble", "nim"},
		{".nims", "nim"},
		{".ninja", "ninja"},
		{".nix", "nix"},
		{".norg", "norg"},
		{".note", "note"},
		{".nqc", "nqc"},
		{".nut", "squirrel"},
		{".objdump", "objdump"},
		{".ocaml_interface", "ocaml_interface"},
		{".ocamllex", "ocamllex"},
		{".odin", "odin"},
		{".org", "org"},
		{".org_archive", "org"},
		{".ott", "ott"},
		{".p", "gnuplot"},
		{".pas", "pascal"},
		{".patch", "diff"},
		{".pdb", "prolog"},
		{".pde", "arduino"},
		{".pem", "pem"},
		{".persistentmodels", "haskell_persistent"},
		{".php", "php"},
		{".php_only", "php_only"},
		{".phpdoc", "phpdoc"},
		{".pic", "pic"},
		{".pio", "pioasm"},
		{".pl", "perl"},
		{".plot", "gnuplot"},
		{".plt", "gnuplot"},
		{".po", "po"},
		{".pod", "pod"},
		{".pony", "pony"},
		{".pot", "po"},
		{".pp", "pascal"},
		{".printf", "printf"},
		{".prisma", "prisma"},
		{".pro", "prolog"},
		{".problog", "problog"},
		{".prolog", "prolog"},
		{".promql", "promql"},
		{".properties", "properties"},
		{".proto", "proto"},
		{".prp", "pyrope"},
		{".prql", "prql"},
		{".psv", "psv"},
		{".pug", "pug"},
		{".puppet", "puppet"},
		{".purs", "purescript"},
		{".py", "python"},
		{".pymanifest", "pymanifest"},
		{".qc", "quakec"},
		{".ql", "ql"},
		{".qll", "ql"},
		{".qmldir", "qmldir"},
		{".qmljs", "qmljs"},
		{".quark", "supercollider"},
		{".rake", "ruby"},
		{".ralph", "ralph"},
		{".rasi", "rasi"},
		{".rb", "ruby"},
		{".rbs", "rbs"},
		{".re2c", "re2c"},
		{".readline", "readline"},
		{".regex", "regex"},
		{".rego", "rego"},
		{".resource", "robot"},
		{".risor", "risor"},
		{".rkt", "racket"},
		{".rktd", "racket"},
		{".rktl", "racket"},
		{".rnw", "rnoweb"},
		{".robot", "robot"},
		{".roc", "roc"},
		{".rockspec", "lua"},
		{".ron", "ron"},
		{".rq", "sparql"},
		{".rs", "rust"},
		{".rss", "xml"},
		{".rtx", "rtx"},
		{".sbt", "scala"},
		{".sc", "sincere"},
		{".scala", "scala"},
		{".scd", "supercollider"},
		{".scfg", "scfg"},
		{".scheme", "scheme"},
		{".scm", "scheme"},
		{".scss", "scss"},
		{".sdml", "sdml"},
		{".sexp", "commonlisp"},
		{".sface", "surface"},
		{".sh", "bash"},
		{".shader", "gdshader"},
		{".sig", "sml"},
		{".slang", "slang"},
		{".sld", "scheme"},
		{".slim", "slim"},
		{".slint", "slint"},
		{".smali", "smali"},
		{".smithy", "smithy"},
		{".smk", "snakemake"},
		{".sml", "sml"},
		{".snw", "rnoweb"},
		{".sol", "solidity"},
		{".soql", "soql"},
		{".sosl", "sosl"},
		{".sp", "sourcepawn"},
		{".sparql", "sparql"},
		{".sql", "sql"},
		{".sql_bigquery", "sql_bigquery"},
		{".sqlite", "sqlite"},
		{".ss", "scheme"},
		{".star", "starlark"},
		{".starlark", "starlark"},
		{".story", "gherkin"},
		{".stp", "systemtap"},
		{".strace", "strace"},
		{".styled", "styled"},
		{".surface", "surface"},
		{".surql", "surrealql"},
		{".sus", "sus"},
		{".sv", "systemverilog"},
		{".svelte", "svelte"},
		{".svh", "systemverilog"},
		{".swift", "swift"},
		{".sy", "syphon"},
		{".t32", "t32"},
		{".tact", "tact"},
		{".tal", "uxntal"},
		{".tape", "vhs"},
		{".tcl", "tcl"},
		{".td", "tablegen"},
		{".templ", "templ"},
		{".tex", "latex"},
		{".textproto", "textproto"},
		{".tf", "terraform"},
		{".tfstate", "json"},
		{".tfvars", "hcl"},
		{".thrift", "thrift"},
		{".tig", "tiger"},
		{".tl", "teal"},
		{".tla", "tlaplus"},
		{".tmpl", "gotmpl"},
		{".tmux", "tmux"},
		{".tnsl", "tnsl"},
		{".todolang", "todolang"},
		{".toml", "toml"},
		{".tort", "tort"},
		{".tres", "godot_resource"},
		{".ts", "typescript"},
		{".tscn", "godot_resource"},
		{".tsp", "typespec"},
		{".tsv", "tsv"},
		{".tsx", "tsx"},
		{".ttl", "turtle"},
		{".tup", "tup"},
		{".twig", "twig"},
		{".twol", "twolc"},
		{".typ", "typst"},
		{".typoscript", "typoscript"},
		{".u", "unison"},
		{".ungram", "ungrammar"},
		{".usd", "usd"},
		{".usda", "usd"},
		{".uu", "unison"},
		{".v", "verilog"},
		{".v3", "virgil"},
		{".vala", "vala"},
		{".vapi", "vala"},
		{".vh", "systemverilog"},
		{".vim", "vim"},
		{".vimdoc", "vimdoc"},
		{".virdant", "virdant"},
		{".vlang", "v"},
		{".vsh", "v"},
		{".vto", "vento"},
		{".vue", "vue"},
		{".vv", "v"},
		{".walnut", "walnut"},
		{".webapp", "json"},
		{".webmanifest", "json"},
		{".wgsl", "wgsl"},
		{".wgsl_bevy", "wgsl_bevy"},
		{".wing", "wing"},
		{".wit", "wit"},
		{".woml", "woml"},
		{".x", "linkerscript"},
		{".xfst", "xfst"},
		{".xml", "xml"},
		{".yaml", "yaml"},
		{".yang", "yang"},
		{".yml", "yaml"},
		{".yuck", "yuck"},
		{".zed", "authzed"},
		{".zeek", "zeek"},
		{".zig", "zig"},
		{".zon", "zig"},
		{".zsh", "bash"},
		{".zsh-theme", "bash"},
		{"/etc/ssh/ssh_config", "ssh_config"},
		{"/etc/ssh/ssh_config.d/foobar", "ssh_config"},
		{"/etc/ssh/sshd_config", "ssh_config"},
		{"/foo/udev/rules.d/foo.conf", "udev"},
		{"/home/foobar/.gitattributes", "gitattributes"},
		{"/home/foobar/.ignore", "gitignore"},
		{"/home/foobar/.ssh/config", "ssh_client_config"},
		{"9fs", "bash"},
		{"BSDmakefile", "make"},
		{"COMMIT_EDITMSG", "gitcommit"},
		{"Capfile", "ruby"},
		{"Cargo.lock", "toml"},
		{"Cask", "commonlisp"},
		{"Containerfile", "dockerfile"},
		{"Dockerfile", "dockerfile"},
		{"Doxyfile", "doxygen"},
		{"EDIT_DESCRIPTION", "gitcommit"},
		{"Earthfile", "earthfile"},
		{"GNUmakefile", "make"},
		{"Gemfile", "ruby"},
		{"Gemfile.lock", "gemfilelock"},
		{"JUSTFILE", "just"},
		{"Justfile", "just"},
		{"MERGE_MSG", "gitcommit"},
		{"Makefile", "make"},
		{"Makefile.am", "make"},
		{"Makefile.boot", "make"},
		{"Makefile.frag", "make"},
		{"Makefile.in", "make"},
		{"Makefile.inc", "make"},
		{"Makefile.wat", "make"},
		{"NOTES_EDITMSG", "gitcommit"},
		{"PKGBUILD", "bash"},
		{"Pipfile", "toml"},
		{"Pipfile.lock", "json"},
		{"Puppetfile", "ruby"},
		{"Rakefile", "ruby"},
		{"Snakefile", "snakemake"},
		{"TAG_EDITMSG", "gitcommit"},
		{"Tupfile", "tup"},
		{"Vagrantfile", "ruby"},
		{"XCompose", "xcompose"},
		{"bash_aliases", "bash"},
		{"bash_logout", "bash"},
		{"bash_profile", "bash"},
		{"bashrc", "bash"},
		{"bogus", "unknown"},
		{"composer.lock", "json"},
		{"constraints.txt", "requirements"},
		{"cshrc", "bash"},
		{"deno.lock", "json"},
		{"dockerfile", "dockerfile"},
		{"flake.lock", "json"},
		{"foo/.JUSTFILE", "just"},
		{"foo/.Justfile", "just"},
		{"foo/.Rprofile", "r"},
		{"foo/.XCompose", "xcompose"},
		{"foo/.atomignore", "gitignore"},
		{"foo/.babelignore", "gitignore"},
		{"foo/.babelrc", "json"},
		{"foo/.babelrc", "json"},
		{"foo/.bash_aliases", "bash"},
		{"foo/.bash_functions", "bash"},
		{"foo/.bash_history", "bash"},
		{"foo/.bash_logout", "bash"},
		{"foo/.bash_profile", "bash"},
		{"foo/.bashrc", "bash"},
		{"foo/.bzrignore", "gitignore"},
		{"foo/.clang-format", "yaml"},
		{"foo/.clang-tidy", "yaml"},
		{"foo/.coffeelintignore", "gitignore"},
		{"foo/.cshrc", "bash"},
		{"foo/.cvsignore", "gitignore"},
		{"foo/.dockerignore", "gitignore"},
		{"foo/.editorconfig", "editorconfig"},
		{"foo/.eleventyignore", "gitignore"},
		{"foo/.emacs", "commonlisp"},
		{"foo/.emacs.desktop", "commonlisp"},
		{"foo/.env", "dotenv"},
		{"foo/.env.development", "dotenv"},
		{"foo/.env.production", "dotenv"},
		{"foo/.envrc", "bash"},
		{"foo/.eslintignore", "gitignore"},
		{"foo/.eslintrc", "json"},
		{"foo/.exrc", "vim"},
		{"foo/.flaskenv", "bash"},
		{"foo/.gemrc", "yaml"},
		{"foo/.git/config", "git_config"},
		{"foo/.gitattributes", "gitattributes"},
		{"foo/.gitconfig", "git_config"},
		{"foo/.gitignore", "gitignore"},
		{"foo/.gitignore", "gitignore"},
		{"foo/.gitmodules", "git_config"},
		{"foo/.gvimrc", "vim"},
		{"foo/.ignore", "gitignore"},
		{"foo/.irb_history", "ruby"},
		{"foo/.irbrc", "ruby"},
		{"foo/.justfile", "just"},
		{"foo/.kshrc", "bash"},
		{"foo/.login", "bash"},
		{"foo/.markdownlintignore", "gitignore"},
		{"foo/.nodemonignore", "gitignore"},
		{"foo/.npmignore", "gitignore"},
		{"foo/.nvimrc", "vim"},
		{"foo/.prettierignore", "gitignore"},
		{"foo/.prettierrc", "json"},
		{"foo/.profile", "bash"},
		{"foo/.stylelintignore", "gitignore"},
		{"foo/.tmux.conf", "bash"},
		{"foo/.trans", "clojure"},
		{"foo/.vercelignore", "gitignore"},
		{"foo/.vimrc", "vim"},
		{"foo/.viper", "commonlisp"},
		{"foo/.vscodeignore", "gitignore"},
		{"foo/.zlogin", "bash"},
		{"foo/.zlogout", "bash"},
		{"foo/.zprofile", "bash"},
		{"foo/.zshenv", "bash"},
		{"foo/.zshrc", "bash"},
		{"foo/init.vim", "vim"},
		{"foo/udev/foo.conf", "udev"},
		{"git-rebase-todo", "git_rebase"},
		{"glide.lock", "yaml"},
		{"go-sitter-forest/foobar/folds.scm", "query"},
		{"go.mod", "gomod"},
		{"go.sum", "gosum"},
		{"go.work", "gowork"},
		{"go.work.sum", "gosum"},
		{"gradlew", "bash"},
		{"hyprfoo.conf", "hyprlang"},
		{"init.trans", "clojure"},
		{"internal/testdata/modeline_prolog1", "prolog"},
		{"internal/testdata/modeline_v1.v", "v"},
		{"internal/testdata/modeline_verilog1.v", "verilog"},
		{"irb_history", "ruby"},
		{"irbrc", "ruby"},
		{"justfile", "just"},
		{"kshrc", "bash"},
		{"ld.script", "linkerscript"},
		{"login", "bash"},
		{"makefile", "make"},
		{"makefile.sco", "make"},
		{"man", "bash"},
		{"meson.build", "meson"},
		{"meson_options.txt", "meson"},
		{"mkfile", "make"},
		{"nginx/a/b/c/d/foo", "unknown"},
		{"nginx/conf", "nginx"},
		{"nginx/platform1/server3/base.conf", "nginx"},
		{"nginx/server1/conf", "nginx"},
		{"nginx/server2/common.conf", "nginx"},
		{"nginx/some.conf", "nginx"},
		{"passwd", "passwd"},
		{"passwd-", "passwd"},
		{"profile", "bash"},
		{"queries/foo.scm", "query"},
		{"queries/foo/bar.scm", "query"},
		{"queries/foo/bar/baz.scm", "query"},
		{"queries/foo/bar/baz/foobar.scm", "scheme"},
		{"requirements-dev.txt", "requirements"},
		{"requirements.in", "requirements"},
		{"requirements.txt", "requirements"},
		{"robots.txt", "robots"},
		{"sxhkdrc", "sxhkdrc"},
		{"tmux.conf", "bash"},
		{"todo.txt", "todotxt"},
		{"udev/foo.conf", "udev"},
		{"udev/rules.d/foo.conf", "udev"},
		{"xcompose", "xcompose"},
		{"yarn.lock", "yaml"},
		{"zathurarc", "zathurarc"},
		{"zlogin", "bash"},
		{"zlogout", "bash"},
		{"zprofile", "bash"},
		{"zshenv", "bash"},
		{"zshrc", "bash"},
	}

	allLangs, _ := filepath.Glob("*/binding.go")
	for i, lang := range allLangs {
		allLangs[i] = filepath.Dir(lang)
	}

	testedLangs := &sync.Map{}
	testedComponents := &sync.Map{}
	for _, tc := range testCases {
		s := tc.s
		testedComponents.Store(tc.s, true)
		t.Run(tc.s+":"+tc.exp, func(t *testing.T) {
			if strings.HasPrefix(s, ".") {
				s = "foobar" + s
			}

			if act := DetectLanguage(s); act != tc.exp {
				t.Fatalf("Expected %q got %q", tc.exp, act)
			}

			testedLangs.Store(tc.exp, true)
		})

		// Only try out this scenario with non-paths (basically, extensions+basename).
		// With paths, we may actually need to find the file on disk.
		if !strings.Contains(s, string(os.PathSeparator)) {
			s = filepath.Join("foo", "bar", "baz", s)
			t.Run(s+":"+tc.exp, func(t *testing.T) {
				if act := DetectLanguage(s); act != tc.exp {
					t.Fatalf("Expected %q got %q", tc.exp, act)
				}
			})
		}
	}

	testedLangs.Range(func(k, _ any) bool {
		allLangs = slices.DeleteFunc(allLangs, func(s string) bool { return s == k.(string) })
		return true
	})

	if len(allLangs) > 0 {
		t.Fatalf("These langs have no test cases: %v", allLangs)
	}

	exts := maps.Keys(ft.Ext)
	bases := maps.Keys(ft.Basename)

	testedComponents.Range(func(k, _ any) bool {
		key := k.(string)
		fn := func(s string) bool { return s == key || filepath.Base(key) == s || filepath.Ext(key) == s }
		exts, bases = slices.DeleteFunc(exts, fn), slices.DeleteFunc(bases, fn)
		return true
	})

	if len(exts) > 0 {
		t.Fatalf("These exts have no test cases: %v", exts)
	}

	if len(bases) > 0 {
		t.Fatalf("These bases have no test cases: %v", bases)
	}
}

func TestRegisterLanguage(t *testing.T) {
	d := ftDetector{}
	zero := ftDetector{}
	ftTodolang := ftDetector{
		Glob:     map[string]string{"foos/*.foo": "todolang", ".foos/bar/.foo": "todolang"},
		Basename: map[string]string{"foo": "todolang"},
		Ext:      map[string]string{".foo": "todolang"},
	}
	testCases := []struct {
		pat, lang string
		expErr    error
		exp       ftDetector
	}{
		{"", "", errMissingPattern, zero},
		{"", "go", errMissingPattern, zero},
		{"foo", "", errMissingLanguage, zero},
		{"foo", "bogus", errInvalidLanguage, zero},
		{"foos/*.foo", "todolang", nil, ftDetector{
			Glob: map[string]string{"foos/*.foo": "todolang"},
		}},
		{".foos/bar/.foo", "todolang", nil, ftDetector{
			Glob: map[string]string{"foos/*.foo": "todolang", ".foos/bar/.foo": "todolang"},
		}},
		{".foo", "todolang", nil, ftDetector{
			Glob: map[string]string{"foos/*.foo": "todolang", ".foos/bar/.foo": "todolang"},
			Ext:  map[string]string{".foo": "todolang"},
		}},
		{"foo", "todolang", nil, ftTodolang},
		// Repeat the above (should be no difference).
		{"foos/*.foo", "todolang", nil, ftTodolang},
		{".foos/bar/.foo", "todolang", nil, ftTodolang},
		{".foo", "todolang", nil, ftTodolang},
		{"foo", "todolang", nil, ftTodolang},
		// Repeat, but this time change lang (must overwrite it).
		{"foos/*.foo", "comment", nil, ftDetector{
			Glob:     map[string]string{"foos/*.foo": "comment", ".foos/bar/.foo": "todolang"},
			Basename: map[string]string{"foo": "todolang"},
			Ext:      map[string]string{".foo": "todolang"},
		}},
		{".foos/bar/.foo", "comment", nil, ftDetector{
			Glob:     map[string]string{"foos/*.foo": "comment", ".foos/bar/.foo": "comment"},
			Basename: map[string]string{"foo": "todolang"},
			Ext:      map[string]string{".foo": "todolang"},
		}},
		{".foo", "comment", nil, ftDetector{
			Glob:     map[string]string{"foos/*.foo": "comment", ".foos/bar/.foo": "comment"},
			Basename: map[string]string{"foo": "todolang"},
			Ext:      map[string]string{".foo": "comment"},
		}},
		{"foo", "comment", nil, ftDetector{
			Glob:     map[string]string{"foos/*.foo": "comment", ".foos/bar/.foo": "comment"},
			Basename: map[string]string{"foo": "comment"},
			Ext:      map[string]string{".foo": "comment"},
		}},
		// Repeat, but this time change pat (should add it).
		{"foosa/*.foo", "comment", nil, ftDetector{
			Glob: map[string]string{
				"foos/*.foo": "comment", "foosa/*.foo": "comment",
				".foos/bar/.foo": "comment",
			},
			Basename: map[string]string{"foo": "comment"},
			Ext:      map[string]string{".foo": "comment"},
		}},
		{".foosa/bar/.foo", "comment", nil, ftDetector{
			Glob: map[string]string{
				"foos/*.foo": "comment", "foosa/*.foo": "comment",
				".foos/bar/.foo": "comment", ".foosa/bar/.foo": "comment",
			},
			Basename: map[string]string{"foo": "comment"},
			Ext:      map[string]string{".foo": "comment"},
		}},
		{".foosa", "comment", nil, ftDetector{
			Glob: map[string]string{
				"foos/*.foo": "comment", "foosa/*.foo": "comment",
				".foos/bar/.foo": "comment", ".foosa/bar/.foo": "comment",
			},
			Basename: map[string]string{"foo": "comment"},
			Ext:      map[string]string{".foo": "comment", ".foosa": "comment"},
		}},
		{"foosa", "comment", nil, ftDetector{
			Glob: map[string]string{
				"foos/*.foo": "comment", "foosa/*.foo": "comment",
				".foos/bar/.foo": "comment", ".foosa/bar/.foo": "comment",
			},
			Basename: map[string]string{"foo": "comment", "foosa": "comment"},
			Ext:      map[string]string{".foo": "comment", ".foosa": "comment"},
		}},
	}

	for _, tc := range testCases {
		t.Run(tc.pat+":"+tc.lang, func(t *testing.T) {
			if err := d.register(tc.pat, tc.lang); !errors.Is(err, tc.expErr) {
				t.Fatalf("Expected error %v got %v", tc.expErr, err)
			} else if !reflect.DeepEqual(d, tc.exp) {
				t.Fatalf("Expected %v got %#v", tc.exp, d)
			}
		})
	}
}

type modeTest struct {
	modeline, exp string
}

func TestDetectByModeline(t *testing.T) {
	t.Skip("Tested implicitly via TestDetectLanguage()")
}

func TestExtractFromModeline(t *testing.T) {
	testCases := []modeTest{
		{"", ""},
		{"ft=go", ""},
		{"filetype=go", ""},
		{":filetype=go:", ""},
		{":set filetype=go:", ""},
	}

	for _, vi := range []string{"Vim", "Vi", "vim", "vi", "ex", "Vox", "vox"} {
		for _, pre := range []string{"", " ", "ts=4 ", " ts=4 ", "ts=4:", " ts=4 : ", "set ", " set ", "set ts=4 "} {
			for _, cmd := range []string{"ft", "filetype", "syntax", "ft ", "filetype ", "syntax ", "ft     ", "filetype\t\t\t  ", "syntax   \t\t   \t\t   "} {
				for _, post := range []string{"", " ", "\t", "    ", "   \t   \t   "} {
					testCases = append(testCases, modeTest{fmt.Sprintf("%s:%s%s=%sgo:", vi, pre, cmd, post), "go"})
				}
			}
		}
	}

	for _, tc := range testCases {
		t.Run(tc.modeline, func(t *testing.T) {
			if act := extractFromModeline(tc.modeline); act != tc.exp {
				t.Fatalf("Expected %q got %q for %q", tc.exp, act, tc.modeline)
			}
		})
	}
}
