#include "parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 14
#define STATE_COUNT 148
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 48
#define ALIAS_COUNT 2
#define TOKEN_COUNT 27
#define EXTERNAL_TOKEN_COUNT 4
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 6
#define PRODUCTION_ID_COUNT 5

enum ts_symbol_identifiers {
  anon_sym_SLASH = 1,
  anon_sym_SPACE = 2,
  anon_sym_LPAREN = 3,
  anon_sym_RPAREN = 4,
  sym_id = 5,
  sym_name = 6,
  sym_class_name = 7,
  anon_sym_DASH_POUND = 8,
  anon_sym_LBRACK = 9,
  anon_sym_RBRACK = 10,
  anon_sym_DOT = 11,
  sym_attribute_name = 12,
  anon_sym_EQ = 13,
  anon_sym_SQUOTE = 14,
  anon_sym_DQUOTE = 15,
  sym__text = 16,
  sym__comment_content = 17,
  sym_text_content = 18,
  anon_sym_DASH = 19,
  anon_sym_POUND = 20,
  sym_ruby_expression = 21,
  sym__html_identifier = 22,
  sym__newline = 23,
  sym__indent = 24,
  sym__dedent = 25,
  sym_ruby_attributes = 26,
  sym_source_file = 27,
  sym_tag = 28,
  sym__children = 29,
  sym__children_choice = 30,
  sym_html_attributes = 31,
  sym_attributes = 32,
  sym_comment = 33,
  sym__comment_line = 34,
  sym__comment_block = 35,
  sym_comment_condition = 36,
  sym_class = 37,
  sym_attribute = 38,
  sym_quoted_attribute_value = 39,
  sym_ruby_block_output = 40,
  sym_ruby_block_run = 41,
  sym_ruby_interpolation = 42,
  aux_sym_source_file_repeat1 = 43,
  aux_sym_tag_repeat1 = 44,
  aux_sym__children_repeat1 = 45,
  aux_sym_html_attributes_repeat1 = 46,
  aux_sym__comment_line_repeat1 = 47,
  alias_sym_ruby_code = 48,
  alias_sym_self_close_slash = 49,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_SLASH] = "/",
  [anon_sym_SPACE] = " ",
  [anon_sym_LPAREN] = "(",
  [anon_sym_RPAREN] = ")",
  [sym_id] = "id",
  [sym_name] = "name",
  [sym_class_name] = "class_name",
  [anon_sym_DASH_POUND] = "-#",
  [anon_sym_LBRACK] = "[",
  [anon_sym_RBRACK] = "]",
  [anon_sym_DOT] = ".",
  [sym_attribute_name] = "attribute_name",
  [anon_sym_EQ] = "=",
  [anon_sym_SQUOTE] = "'",
  [anon_sym_DQUOTE] = "\"",
  [sym__text] = "_text",
  [sym__comment_content] = "_comment_content",
  [sym_text_content] = "text_content",
  [anon_sym_DASH] = "-",
  [anon_sym_POUND] = "#",
  [sym_ruby_expression] = "ruby_expression",
  [sym__html_identifier] = "attribute_value",
  [sym__newline] = "_newline",
  [sym__indent] = "_indent",
  [sym__dedent] = "_dedent",
  [sym_ruby_attributes] = "ruby_attributes",
  [sym_source_file] = "source_file",
  [sym_tag] = "tag",
  [sym__children] = "_children",
  [sym__children_choice] = "_children_choice",
  [sym_html_attributes] = "html_attributes",
  [sym_attributes] = "attributes",
  [sym_comment] = "comment",
  [sym__comment_line] = "_comment_line",
  [sym__comment_block] = "_comment_block",
  [sym_comment_condition] = "comment_condition",
  [sym_class] = "class",
  [sym_attribute] = "attribute",
  [sym_quoted_attribute_value] = "quoted_attribute_value",
  [sym_ruby_block_output] = "ruby_block_output",
  [sym_ruby_block_run] = "ruby_block_run",
  [sym_ruby_interpolation] = "ruby_interpolation",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_tag_repeat1] = "tag_repeat1",
  [aux_sym__children_repeat1] = "_children_repeat1",
  [aux_sym_html_attributes_repeat1] = "html_attributes_repeat1",
  [aux_sym__comment_line_repeat1] = "_comment_line_repeat1",
  [alias_sym_ruby_code] = "ruby_code",
  [alias_sym_self_close_slash] = "self_close_slash",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_SLASH] = anon_sym_SLASH,
  [anon_sym_SPACE] = anon_sym_SPACE,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [sym_id] = sym_id,
  [sym_name] = sym_name,
  [sym_class_name] = sym_class_name,
  [anon_sym_DASH_POUND] = anon_sym_DASH_POUND,
  [anon_sym_LBRACK] = anon_sym_LBRACK,
  [anon_sym_RBRACK] = anon_sym_RBRACK,
  [anon_sym_DOT] = anon_sym_DOT,
  [sym_attribute_name] = sym_attribute_name,
  [anon_sym_EQ] = anon_sym_EQ,
  [anon_sym_SQUOTE] = anon_sym_SQUOTE,
  [anon_sym_DQUOTE] = anon_sym_DQUOTE,
  [sym__text] = sym__text,
  [sym__comment_content] = sym__comment_content,
  [sym_text_content] = sym_text_content,
  [anon_sym_DASH] = anon_sym_DASH,
  [anon_sym_POUND] = anon_sym_POUND,
  [sym_ruby_expression] = sym_ruby_expression,
  [sym__html_identifier] = sym__html_identifier,
  [sym__newline] = sym__newline,
  [sym__indent] = sym__indent,
  [sym__dedent] = sym__dedent,
  [sym_ruby_attributes] = sym_ruby_attributes,
  [sym_source_file] = sym_source_file,
  [sym_tag] = sym_tag,
  [sym__children] = sym__children,
  [sym__children_choice] = sym__children_choice,
  [sym_html_attributes] = sym_html_attributes,
  [sym_attributes] = sym_attributes,
  [sym_comment] = sym_comment,
  [sym__comment_line] = sym__comment_line,
  [sym__comment_block] = sym__comment_block,
  [sym_comment_condition] = sym_comment_condition,
  [sym_class] = sym_class,
  [sym_attribute] = sym_attribute,
  [sym_quoted_attribute_value] = sym_quoted_attribute_value,
  [sym_ruby_block_output] = sym_ruby_block_output,
  [sym_ruby_block_run] = sym_ruby_block_run,
  [sym_ruby_interpolation] = sym_ruby_interpolation,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_tag_repeat1] = aux_sym_tag_repeat1,
  [aux_sym__children_repeat1] = aux_sym__children_repeat1,
  [aux_sym_html_attributes_repeat1] = aux_sym_html_attributes_repeat1,
  [aux_sym__comment_line_repeat1] = aux_sym__comment_line_repeat1,
  [alias_sym_ruby_code] = alias_sym_ruby_code,
  [alias_sym_self_close_slash] = alias_sym_self_close_slash,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_SLASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SPACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [sym_id] = {
    .visible = true,
    .named = true,
  },
  [sym_name] = {
    .visible = true,
    .named = true,
  },
  [sym_class_name] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_DASH_POUND] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DOT] = {
    .visible = true,
    .named = false,
  },
  [sym_attribute_name] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SQUOTE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DQUOTE] = {
    .visible = true,
    .named = false,
  },
  [sym__text] = {
    .visible = false,
    .named = true,
  },
  [sym__comment_content] = {
    .visible = false,
    .named = true,
  },
  [sym_text_content] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_DASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_POUND] = {
    .visible = true,
    .named = false,
  },
  [sym_ruby_expression] = {
    .visible = true,
    .named = true,
  },
  [sym__html_identifier] = {
    .visible = true,
    .named = true,
  },
  [sym__newline] = {
    .visible = false,
    .named = true,
  },
  [sym__indent] = {
    .visible = false,
    .named = true,
  },
  [sym__dedent] = {
    .visible = false,
    .named = true,
  },
  [sym_ruby_attributes] = {
    .visible = true,
    .named = true,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym_tag] = {
    .visible = true,
    .named = true,
  },
  [sym__children] = {
    .visible = false,
    .named = true,
  },
  [sym__children_choice] = {
    .visible = false,
    .named = true,
  },
  [sym_html_attributes] = {
    .visible = true,
    .named = true,
  },
  [sym_attributes] = {
    .visible = true,
    .named = true,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [sym__comment_line] = {
    .visible = false,
    .named = true,
  },
  [sym__comment_block] = {
    .visible = false,
    .named = true,
  },
  [sym_comment_condition] = {
    .visible = true,
    .named = true,
  },
  [sym_class] = {
    .visible = true,
    .named = true,
  },
  [sym_attribute] = {
    .visible = true,
    .named = true,
  },
  [sym_quoted_attribute_value] = {
    .visible = true,
    .named = true,
  },
  [sym_ruby_block_output] = {
    .visible = true,
    .named = true,
  },
  [sym_ruby_block_run] = {
    .visible = true,
    .named = true,
  },
  [sym_ruby_interpolation] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_tag_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym__children_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_html_attributes_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym__comment_line_repeat1] = {
    .visible = false,
    .named = false,
  },
  [alias_sym_ruby_code] = {
    .visible = true,
    .named = true,
  },
  [alias_sym_self_close_slash] = {
    .visible = true,
    .named = true,
  },
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
  [1] = {
    [1] = alias_sym_ruby_code,
  },
  [2] = {
    [1] = alias_sym_self_close_slash,
  },
  [3] = {
    [2] = alias_sym_self_close_slash,
  },
  [4] = {
    [3] = alias_sym_self_close_slash,
  },
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 3,
  [5] = 5,
  [6] = 5,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 9,
  [12] = 10,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 17,
  [26] = 26,
  [27] = 15,
  [28] = 16,
  [29] = 18,
  [30] = 19,
  [31] = 20,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 13,
  [38] = 38,
  [39] = 39,
  [40] = 40,
  [41] = 41,
  [42] = 42,
  [43] = 43,
  [44] = 44,
  [45] = 45,
  [46] = 46,
  [47] = 47,
  [48] = 14,
  [49] = 49,
  [50] = 50,
  [51] = 21,
  [52] = 22,
  [53] = 23,
  [54] = 39,
  [55] = 32,
  [56] = 56,
  [57] = 40,
  [58] = 44,
  [59] = 41,
  [60] = 34,
  [61] = 42,
  [62] = 43,
  [63] = 45,
  [64] = 35,
  [65] = 47,
  [66] = 46,
  [67] = 38,
  [68] = 36,
  [69] = 49,
  [70] = 50,
  [71] = 24,
  [72] = 33,
  [73] = 73,
  [74] = 74,
  [75] = 74,
  [76] = 73,
  [77] = 77,
  [78] = 77,
  [79] = 79,
  [80] = 80,
  [81] = 81,
  [82] = 82,
  [83] = 83,
  [84] = 84,
  [85] = 85,
  [86] = 83,
  [87] = 87,
  [88] = 88,
  [89] = 81,
  [90] = 80,
  [91] = 91,
  [92] = 92,
  [93] = 93,
  [94] = 94,
  [95] = 95,
  [96] = 96,
  [97] = 97,
  [98] = 97,
  [99] = 99,
  [100] = 100,
  [101] = 92,
  [102] = 102,
  [103] = 95,
  [104] = 104,
  [105] = 105,
  [106] = 106,
  [107] = 107,
  [108] = 108,
  [109] = 109,
  [110] = 108,
  [111] = 105,
  [112] = 112,
  [113] = 109,
  [114] = 114,
  [115] = 115,
  [116] = 116,
  [117] = 117,
  [118] = 118,
  [119] = 119,
  [120] = 120,
  [121] = 121,
  [122] = 118,
  [123] = 123,
  [124] = 124,
  [125] = 125,
  [126] = 126,
  [127] = 127,
  [128] = 128,
  [129] = 123,
  [130] = 127,
  [131] = 131,
  [132] = 132,
  [133] = 125,
  [134] = 119,
  [135] = 135,
  [136] = 136,
  [137] = 124,
  [138] = 114,
  [139] = 120,
  [140] = 135,
  [141] = 121,
  [142] = 142,
  [143] = 143,
  [144] = 116,
  [145] = 142,
  [146] = 131,
  [147] = 147,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(15);
      ADVANCE_MAP(
        '"', 31,
        '#', 42,
        '%', 12,
        '\'', 30,
        '(', 18,
        ')', 19,
        '-', 41,
        '.', 27,
        '/', 16,
        '=', 29,
        '[', 24,
        ']', 26,
        '{', 8,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      END_STATE();
    case 1:
      if (lookahead == '\n') SKIP(1);
      if (lookahead == '#') ADVANCE(42);
      if (lookahead == '%') ADVANCE(39);
      if (lookahead == '-') ADVANCE(41);
      if (lookahead == '.') ADVANCE(27);
      if (lookahead == '/') ADVANCE(16);
      if (lookahead == '=') ADVANCE(29);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(37);
      if (lookahead != 0) ADVANCE(40);
      END_STATE();
    case 2:
      if (lookahead == '\n') SKIP(2);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(38);
      if (lookahead != 0) ADVANCE(40);
      END_STATE();
    case 3:
      if (lookahead == '\n') SKIP(3);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(32);
      if (lookahead != 0) ADVANCE(33);
      END_STATE();
    case 4:
      if (lookahead == ' ') ADVANCE(17);
      if (lookahead == '#') ADVANCE(11);
      if (lookahead == '%') ADVANCE(12);
      if (lookahead == '(') ADVANCE(18);
      if (lookahead == '.') ADVANCE(27);
      if (lookahead == '/') ADVANCE(16);
      if (lookahead == '=') ADVANCE(29);
      if (('\t' <= lookahead && lookahead <= '\r')) SKIP(4);
      END_STATE();
    case 5:
      if (lookahead == ' ') ADVANCE(17);
      if (lookahead == '#') ADVANCE(13);
      if (lookahead == ')') ADVANCE(19);
      if (lookahead == '=') ADVANCE(29);
      if (('\t' <= lookahead && lookahead <= '\r')) SKIP(5);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= ':') ||
          ('@' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(28);
      END_STATE();
    case 6:
      if (lookahead == '"') ADVANCE(31);
      if (lookahead == '\'') ADVANCE(30);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(6);
      if (('-' <= lookahead && lookahead <= ':') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(44);
      END_STATE();
    case 7:
      if (lookahead == '#') ADVANCE(13);
      if (lookahead == ')') ADVANCE(19);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(7);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= ':') ||
          ('@' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(28);
      END_STATE();
    case 8:
      if (lookahead == '}') ADVANCE(43);
      if (lookahead != 0) ADVANCE(8);
      END_STATE();
    case 9:
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(9);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9')) ADVANCE(10);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(22);
      END_STATE();
    case 10:
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9')) ADVANCE(10);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(22);
      END_STATE();
    case 11:
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(20);
      END_STATE();
    case 12:
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= ':') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(21);
      END_STATE();
    case 13:
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= ':') ||
          ('@' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(28);
      END_STATE();
    case 14:
      if (eof) ADVANCE(15);
      if (lookahead == '\n') SKIP(14);
      if (lookahead == '#') ADVANCE(42);
      if (lookahead == '%') ADVANCE(39);
      if (lookahead == '-') ADVANCE(41);
      if (lookahead == '.') ADVANCE(27);
      if (lookahead == '/') ADVANCE(16);
      if (lookahead == '=') ADVANCE(29);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(37);
      if (lookahead != 0) ADVANCE(40);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(anon_sym_SLASH);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(anon_sym_SPACE);
      if (lookahead == ' ') ADVANCE(17);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(sym_id);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(20);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(sym_name);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= ':') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(21);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(sym_class_name);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9')) ADVANCE(22);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(22);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(anon_sym_DASH_POUND);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(anon_sym_LBRACK);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(anon_sym_LBRACK);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(36);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(anon_sym_RBRACK);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(anon_sym_DOT);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(sym_attribute_name);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= ':') ||
          ('@' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(28);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(anon_sym_EQ);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(anon_sym_SQUOTE);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(anon_sym_DQUOTE);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(sym__text);
      if (lookahead == '\t' ||
          (0x0b <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(32);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead)) ADVANCE(33);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(sym__text);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(33);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(sym__comment_content);
      if (lookahead == '[') ADVANCE(25);
      if (lookahead == '\t' ||
          (0x0b <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(34);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead)) ADVANCE(36);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(sym__comment_content);
      if (lookahead == '\t' ||
          (0x0b <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(35);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead)) ADVANCE(36);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(sym__comment_content);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(36);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(sym_text_content);
      if (lookahead == '\n') SKIP(1);
      if (lookahead == '#') ADVANCE(42);
      if (lookahead == '%') ADVANCE(39);
      if (lookahead == '-') ADVANCE(41);
      if (lookahead == '.') ADVANCE(27);
      if (lookahead == '/') ADVANCE(16);
      if (lookahead == '=') ADVANCE(29);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(37);
      if (lookahead != 0) ADVANCE(40);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(sym_text_content);
      if (lookahead == '\n') SKIP(2);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(38);
      if (lookahead != 0) ADVANCE(40);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(sym_text_content);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= ':') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(21);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(40);
      END_STATE();
    case 40:
      ACCEPT_TOKEN(sym_text_content);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(40);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(anon_sym_DASH);
      if (lookahead == '#') ADVANCE(23);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(anon_sym_POUND);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(20);
      END_STATE();
    case 43:
      ACCEPT_TOKEN(sym_ruby_expression);
      END_STATE();
    case 44:
      ACCEPT_TOKEN(sym__html_identifier);
      if (('-' <= lookahead && lookahead <= ':') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(44);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0, .external_lex_state = 1},
  [1] = {.lex_state = 0},
  [2] = {.lex_state = 14, .external_lex_state = 2},
  [3] = {.lex_state = 14, .external_lex_state = 2},
  [4] = {.lex_state = 14, .external_lex_state = 2},
  [5] = {.lex_state = 14},
  [6] = {.lex_state = 14},
  [7] = {.lex_state = 0},
  [8] = {.lex_state = 0},
  [9] = {.lex_state = 4, .external_lex_state = 3},
  [10] = {.lex_state = 4, .external_lex_state = 3},
  [11] = {.lex_state = 4, .external_lex_state = 3},
  [12] = {.lex_state = 4, .external_lex_state = 3},
  [13] = {.lex_state = 14, .external_lex_state = 4},
  [14] = {.lex_state = 14, .external_lex_state = 4},
  [15] = {.lex_state = 14, .external_lex_state = 4},
  [16] = {.lex_state = 14, .external_lex_state = 4},
  [17] = {.lex_state = 14, .external_lex_state = 4},
  [18] = {.lex_state = 14, .external_lex_state = 4},
  [19] = {.lex_state = 14, .external_lex_state = 4},
  [20] = {.lex_state = 14, .external_lex_state = 4},
  [21] = {.lex_state = 14, .external_lex_state = 5},
  [22] = {.lex_state = 14, .external_lex_state = 5},
  [23] = {.lex_state = 14, .external_lex_state = 4},
  [24] = {.lex_state = 14, .external_lex_state = 2},
  [25] = {.lex_state = 0, .external_lex_state = 6},
  [26] = {.lex_state = 4, .external_lex_state = 3},
  [27] = {.lex_state = 0, .external_lex_state = 6},
  [28] = {.lex_state = 0, .external_lex_state = 6},
  [29] = {.lex_state = 0, .external_lex_state = 6},
  [30] = {.lex_state = 0, .external_lex_state = 6},
  [31] = {.lex_state = 0, .external_lex_state = 6},
  [32] = {.lex_state = 14, .external_lex_state = 2},
  [33] = {.lex_state = 14, .external_lex_state = 2},
  [34] = {.lex_state = 14, .external_lex_state = 2},
  [35] = {.lex_state = 14, .external_lex_state = 2},
  [36] = {.lex_state = 14, .external_lex_state = 2},
  [37] = {.lex_state = 0, .external_lex_state = 6},
  [38] = {.lex_state = 14, .external_lex_state = 2},
  [39] = {.lex_state = 14, .external_lex_state = 2},
  [40] = {.lex_state = 14, .external_lex_state = 2},
  [41] = {.lex_state = 14, .external_lex_state = 2},
  [42] = {.lex_state = 14, .external_lex_state = 2},
  [43] = {.lex_state = 14, .external_lex_state = 2},
  [44] = {.lex_state = 14, .external_lex_state = 2},
  [45] = {.lex_state = 14, .external_lex_state = 2},
  [46] = {.lex_state = 14, .external_lex_state = 2},
  [47] = {.lex_state = 14, .external_lex_state = 2},
  [48] = {.lex_state = 0, .external_lex_state = 6},
  [49] = {.lex_state = 14, .external_lex_state = 2},
  [50] = {.lex_state = 14, .external_lex_state = 2},
  [51] = {.lex_state = 0, .external_lex_state = 7},
  [52] = {.lex_state = 0, .external_lex_state = 7},
  [53] = {.lex_state = 0, .external_lex_state = 6},
  [54] = {.lex_state = 0},
  [55] = {.lex_state = 0},
  [56] = {.lex_state = 4, .external_lex_state = 3},
  [57] = {.lex_state = 0},
  [58] = {.lex_state = 0},
  [59] = {.lex_state = 0},
  [60] = {.lex_state = 0},
  [61] = {.lex_state = 0},
  [62] = {.lex_state = 0},
  [63] = {.lex_state = 0},
  [64] = {.lex_state = 0},
  [65] = {.lex_state = 0},
  [66] = {.lex_state = 0},
  [67] = {.lex_state = 0},
  [68] = {.lex_state = 0},
  [69] = {.lex_state = 0},
  [70] = {.lex_state = 0},
  [71] = {.lex_state = 0},
  [72] = {.lex_state = 0},
  [73] = {.lex_state = 4, .external_lex_state = 7},
  [74] = {.lex_state = 4, .external_lex_state = 7},
  [75] = {.lex_state = 4, .external_lex_state = 7},
  [76] = {.lex_state = 4, .external_lex_state = 7},
  [77] = {.lex_state = 4, .external_lex_state = 7},
  [78] = {.lex_state = 4, .external_lex_state = 7},
  [79] = {.lex_state = 4, .external_lex_state = 7},
  [80] = {.lex_state = 34, .external_lex_state = 7},
  [81] = {.lex_state = 4, .external_lex_state = 7},
  [82] = {.lex_state = 4, .external_lex_state = 7},
  [83] = {.lex_state = 4, .external_lex_state = 7},
  [84] = {.lex_state = 7},
  [85] = {.lex_state = 5},
  [86] = {.lex_state = 4, .external_lex_state = 7},
  [87] = {.lex_state = 4, .external_lex_state = 7},
  [88] = {.lex_state = 7},
  [89] = {.lex_state = 4, .external_lex_state = 7},
  [90] = {.lex_state = 34, .external_lex_state = 7},
  [91] = {.lex_state = 7},
  [92] = {.lex_state = 35, .external_lex_state = 2},
  [93] = {.lex_state = 35, .external_lex_state = 2},
  [94] = {.lex_state = 5},
  [95] = {.lex_state = 35, .external_lex_state = 2},
  [96] = {.lex_state = 5},
  [97] = {.lex_state = 35, .external_lex_state = 2},
  [98] = {.lex_state = 35, .external_lex_state = 2},
  [99] = {.lex_state = 0},
  [100] = {.lex_state = 5},
  [101] = {.lex_state = 35, .external_lex_state = 2},
  [102] = {.lex_state = 5},
  [103] = {.lex_state = 35, .external_lex_state = 2},
  [104] = {.lex_state = 35, .external_lex_state = 2},
  [105] = {.lex_state = 35},
  [106] = {.lex_state = 6},
  [107] = {.lex_state = 6},
  [108] = {.lex_state = 35},
  [109] = {.lex_state = 35},
  [110] = {.lex_state = 35},
  [111] = {.lex_state = 35},
  [112] = {.lex_state = 7},
  [113] = {.lex_state = 35},
  [114] = {.lex_state = 2},
  [115] = {.lex_state = 0},
  [116] = {.lex_state = 0, .external_lex_state = 6},
  [117] = {.lex_state = 0, .external_lex_state = 7},
  [118] = {.lex_state = 0, .external_lex_state = 7},
  [119] = {.lex_state = 3},
  [120] = {.lex_state = 3},
  [121] = {.lex_state = 0},
  [122] = {.lex_state = 0, .external_lex_state = 7},
  [123] = {.lex_state = 2},
  [124] = {.lex_state = 2},
  [125] = {.lex_state = 2},
  [126] = {.lex_state = 0},
  [127] = {.lex_state = 2},
  [128] = {.lex_state = 0},
  [129] = {.lex_state = 2},
  [130] = {.lex_state = 2},
  [131] = {.lex_state = 0, .external_lex_state = 7},
  [132] = {.lex_state = 3},
  [133] = {.lex_state = 2},
  [134] = {.lex_state = 3},
  [135] = {.lex_state = 2},
  [136] = {.lex_state = 0},
  [137] = {.lex_state = 2},
  [138] = {.lex_state = 2},
  [139] = {.lex_state = 3},
  [140] = {.lex_state = 2},
  [141] = {.lex_state = 0},
  [142] = {.lex_state = 0, .external_lex_state = 6},
  [143] = {.lex_state = 0, .external_lex_state = 7},
  [144] = {.lex_state = 0, .external_lex_state = 6},
  [145] = {.lex_state = 0, .external_lex_state = 6},
  [146] = {.lex_state = 0, .external_lex_state = 7},
  [147] = {.lex_state = 9},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [0] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_SLASH] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [sym_id] = ACTIONS(1),
    [sym_name] = ACTIONS(1),
    [anon_sym_DASH_POUND] = ACTIONS(1),
    [anon_sym_LBRACK] = ACTIONS(1),
    [anon_sym_RBRACK] = ACTIONS(1),
    [anon_sym_DOT] = ACTIONS(1),
    [anon_sym_EQ] = ACTIONS(1),
    [anon_sym_SQUOTE] = ACTIONS(1),
    [anon_sym_DQUOTE] = ACTIONS(1),
    [anon_sym_DASH] = ACTIONS(1),
    [anon_sym_POUND] = ACTIONS(1),
    [sym_ruby_expression] = ACTIONS(1),
    [sym__newline] = ACTIONS(1),
    [sym__indent] = ACTIONS(1),
    [sym__dedent] = ACTIONS(1),
    [sym_ruby_attributes] = ACTIONS(1),
  },
  [1] = {
    [sym_source_file] = STATE(115),
    [sym_tag] = STATE(8),
    [sym_comment] = STATE(8),
    [sym__comment_line] = STATE(55),
    [sym__comment_block] = STATE(55),
    [sym_class] = STATE(9),
    [sym_ruby_block_output] = STATE(8),
    [sym_ruby_block_run] = STATE(8),
    [sym_ruby_interpolation] = STATE(8),
    [aux_sym_source_file_repeat1] = STATE(8),
    [ts_builtin_sym_end] = ACTIONS(3),
    [anon_sym_SLASH] = ACTIONS(5),
    [sym_id] = ACTIONS(7),
    [sym_name] = ACTIONS(7),
    [anon_sym_DASH_POUND] = ACTIONS(5),
    [anon_sym_DOT] = ACTIONS(9),
    [anon_sym_EQ] = ACTIONS(11),
    [anon_sym_DASH] = ACTIONS(13),
    [anon_sym_POUND] = ACTIONS(15),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 11,
    ACTIONS(25), 1,
      anon_sym_DOT,
    ACTIONS(28), 1,
      anon_sym_EQ,
    ACTIONS(31), 1,
      sym_text_content,
    ACTIONS(34), 1,
      anon_sym_DASH,
    ACTIONS(37), 1,
      anon_sym_POUND,
    STATE(11), 1,
      sym_class,
    ACTIONS(17), 2,
      sym__dedent,
      ts_builtin_sym_end,
    ACTIONS(19), 2,
      anon_sym_SLASH,
      anon_sym_DASH_POUND,
    ACTIONS(22), 2,
      sym_id,
      sym_name,
    STATE(32), 2,
      sym__comment_line,
      sym__comment_block,
    STATE(2), 7,
      sym_tag,
      sym__children_choice,
      sym_comment,
      sym_ruby_block_output,
      sym_ruby_block_run,
      sym_ruby_interpolation,
      aux_sym__children_repeat1,
  [44] = 12,
    ACTIONS(40), 1,
      ts_builtin_sym_end,
    ACTIONS(46), 1,
      anon_sym_DOT,
    ACTIONS(48), 1,
      anon_sym_EQ,
    ACTIONS(50), 1,
      sym_text_content,
    ACTIONS(52), 1,
      anon_sym_DASH,
    ACTIONS(54), 1,
      anon_sym_POUND,
    ACTIONS(56), 1,
      sym__dedent,
    STATE(11), 1,
      sym_class,
    ACTIONS(42), 2,
      anon_sym_SLASH,
      anon_sym_DASH_POUND,
    ACTIONS(44), 2,
      sym_id,
      sym_name,
    STATE(32), 2,
      sym__comment_line,
      sym__comment_block,
    STATE(2), 7,
      sym_tag,
      sym__children_choice,
      sym_comment,
      sym_ruby_block_output,
      sym_ruby_block_run,
      sym_ruby_interpolation,
      aux_sym__children_repeat1,
  [90] = 12,
    ACTIONS(40), 1,
      ts_builtin_sym_end,
    ACTIONS(46), 1,
      anon_sym_DOT,
    ACTIONS(48), 1,
      anon_sym_EQ,
    ACTIONS(50), 1,
      sym_text_content,
    ACTIONS(52), 1,
      anon_sym_DASH,
    ACTIONS(54), 1,
      anon_sym_POUND,
    ACTIONS(58), 1,
      sym__dedent,
    STATE(11), 1,
      sym_class,
    ACTIONS(42), 2,
      anon_sym_SLASH,
      anon_sym_DASH_POUND,
    ACTIONS(44), 2,
      sym_id,
      sym_name,
    STATE(32), 2,
      sym__comment_line,
      sym__comment_block,
    STATE(2), 7,
      sym_tag,
      sym__children_choice,
      sym_comment,
      sym_ruby_block_output,
      sym_ruby_block_run,
      sym_ruby_interpolation,
      aux_sym__children_repeat1,
  [136] = 10,
    ACTIONS(46), 1,
      anon_sym_DOT,
    ACTIONS(48), 1,
      anon_sym_EQ,
    ACTIONS(52), 1,
      anon_sym_DASH,
    ACTIONS(54), 1,
      anon_sym_POUND,
    ACTIONS(60), 1,
      sym_text_content,
    STATE(11), 1,
      sym_class,
    ACTIONS(42), 2,
      anon_sym_SLASH,
      anon_sym_DASH_POUND,
    ACTIONS(44), 2,
      sym_id,
      sym_name,
    STATE(32), 2,
      sym__comment_line,
      sym__comment_block,
    STATE(3), 7,
      sym_tag,
      sym__children_choice,
      sym_comment,
      sym_ruby_block_output,
      sym_ruby_block_run,
      sym_ruby_interpolation,
      aux_sym__children_repeat1,
  [176] = 10,
    ACTIONS(46), 1,
      anon_sym_DOT,
    ACTIONS(48), 1,
      anon_sym_EQ,
    ACTIONS(52), 1,
      anon_sym_DASH,
    ACTIONS(54), 1,
      anon_sym_POUND,
    ACTIONS(62), 1,
      sym_text_content,
    STATE(11), 1,
      sym_class,
    ACTIONS(42), 2,
      anon_sym_SLASH,
      anon_sym_DASH_POUND,
    ACTIONS(44), 2,
      sym_id,
      sym_name,
    STATE(32), 2,
      sym__comment_line,
      sym__comment_block,
    STATE(4), 7,
      sym_tag,
      sym__children_choice,
      sym_comment,
      sym_ruby_block_output,
      sym_ruby_block_run,
      sym_ruby_interpolation,
      aux_sym__children_repeat1,
  [216] = 10,
    ACTIONS(64), 1,
      ts_builtin_sym_end,
    ACTIONS(72), 1,
      anon_sym_DOT,
    ACTIONS(75), 1,
      anon_sym_EQ,
    ACTIONS(78), 1,
      anon_sym_DASH,
    ACTIONS(81), 1,
      anon_sym_POUND,
    STATE(9), 1,
      sym_class,
    ACTIONS(66), 2,
      anon_sym_SLASH,
      anon_sym_DASH_POUND,
    ACTIONS(69), 2,
      sym_id,
      sym_name,
    STATE(55), 2,
      sym__comment_line,
      sym__comment_block,
    STATE(7), 6,
      sym_tag,
      sym_comment,
      sym_ruby_block_output,
      sym_ruby_block_run,
      sym_ruby_interpolation,
      aux_sym_source_file_repeat1,
  [255] = 10,
    ACTIONS(9), 1,
      anon_sym_DOT,
    ACTIONS(11), 1,
      anon_sym_EQ,
    ACTIONS(13), 1,
      anon_sym_DASH,
    ACTIONS(15), 1,
      anon_sym_POUND,
    ACTIONS(84), 1,
      ts_builtin_sym_end,
    STATE(9), 1,
      sym_class,
    ACTIONS(5), 2,
      anon_sym_SLASH,
      anon_sym_DASH_POUND,
    ACTIONS(7), 2,
      sym_id,
      sym_name,
    STATE(55), 2,
      sym__comment_line,
      sym__comment_block,
    STATE(7), 6,
      sym_tag,
      sym_comment,
      sym_ruby_block_output,
      sym_ruby_block_run,
      sym_ruby_interpolation,
      aux_sym_source_file_repeat1,
  [294] = 12,
    ACTIONS(46), 1,
      anon_sym_DOT,
    ACTIONS(86), 1,
      anon_sym_SLASH,
    ACTIONS(88), 1,
      anon_sym_SPACE,
    ACTIONS(90), 1,
      anon_sym_LPAREN,
    ACTIONS(94), 1,
      anon_sym_EQ,
    ACTIONS(96), 1,
      sym__newline,
    ACTIONS(98), 1,
      sym_ruby_attributes,
    STATE(72), 1,
      sym_ruby_block_output,
    STATE(74), 1,
      sym_attributes,
    STATE(87), 1,
      sym_html_attributes,
    ACTIONS(92), 2,
      sym_id,
      sym_name,
    STATE(10), 2,
      sym_class,
      aux_sym_tag_repeat1,
  [333] = 12,
    ACTIONS(46), 1,
      anon_sym_DOT,
    ACTIONS(90), 1,
      anon_sym_LPAREN,
    ACTIONS(94), 1,
      anon_sym_EQ,
    ACTIONS(98), 1,
      sym_ruby_attributes,
    ACTIONS(100), 1,
      anon_sym_SLASH,
    ACTIONS(102), 1,
      anon_sym_SPACE,
    ACTIONS(106), 1,
      sym__newline,
    STATE(64), 1,
      sym_ruby_block_output,
    STATE(73), 1,
      sym_attributes,
    STATE(87), 1,
      sym_html_attributes,
    ACTIONS(104), 2,
      sym_id,
      sym_name,
    STATE(26), 2,
      sym_class,
      aux_sym_tag_repeat1,
  [372] = 12,
    ACTIONS(46), 1,
      anon_sym_DOT,
    ACTIONS(48), 1,
      anon_sym_EQ,
    ACTIONS(90), 1,
      anon_sym_LPAREN,
    ACTIONS(98), 1,
      sym_ruby_attributes,
    ACTIONS(108), 1,
      anon_sym_SLASH,
    ACTIONS(110), 1,
      anon_sym_SPACE,
    ACTIONS(114), 1,
      sym__newline,
    STATE(33), 1,
      sym_ruby_block_output,
    STATE(75), 1,
      sym_attributes,
    STATE(87), 1,
      sym_html_attributes,
    ACTIONS(112), 2,
      sym_id,
      sym_name,
    STATE(12), 2,
      sym_class,
      aux_sym_tag_repeat1,
  [411] = 12,
    ACTIONS(46), 1,
      anon_sym_DOT,
    ACTIONS(48), 1,
      anon_sym_EQ,
    ACTIONS(90), 1,
      anon_sym_LPAREN,
    ACTIONS(98), 1,
      sym_ruby_attributes,
    ACTIONS(116), 1,
      anon_sym_SLASH,
    ACTIONS(118), 1,
      anon_sym_SPACE,
    ACTIONS(120), 1,
      sym__newline,
    STATE(35), 1,
      sym_ruby_block_output,
    STATE(76), 1,
      sym_attributes,
    STATE(87), 1,
      sym_html_attributes,
    ACTIONS(104), 2,
      sym_id,
      sym_name,
    STATE(26), 2,
      sym_class,
      aux_sym_tag_repeat1,
  [450] = 4,
    ACTIONS(126), 1,
      sym__indent,
    STATE(35), 1,
      sym__children,
    ACTIONS(122), 2,
      sym__dedent,
      ts_builtin_sym_end,
    ACTIONS(124), 9,
      anon_sym_SLASH,
      sym_id,
      sym_name,
      anon_sym_DASH_POUND,
      anon_sym_DOT,
      anon_sym_EQ,
      sym_text_content,
      anon_sym_DASH,
      anon_sym_POUND,
  [472] = 4,
    ACTIONS(126), 1,
      sym__indent,
    STATE(39), 1,
      sym__children,
    ACTIONS(128), 2,
      sym__dedent,
      ts_builtin_sym_end,
    ACTIONS(130), 9,
      anon_sym_SLASH,
      sym_id,
      sym_name,
      anon_sym_DASH_POUND,
      anon_sym_DOT,
      anon_sym_EQ,
      sym_text_content,
      anon_sym_DASH,
      anon_sym_POUND,
  [494] = 4,
    ACTIONS(126), 1,
      sym__indent,
    STATE(42), 1,
      sym__children,
    ACTIONS(132), 2,
      sym__dedent,
      ts_builtin_sym_end,
    ACTIONS(134), 9,
      anon_sym_SLASH,
      sym_id,
      sym_name,
      anon_sym_DASH_POUND,
      anon_sym_DOT,
      anon_sym_EQ,
      sym_text_content,
      anon_sym_DASH,
      anon_sym_POUND,
  [516] = 4,
    ACTIONS(126), 1,
      sym__indent,
    STATE(43), 1,
      sym__children,
    ACTIONS(136), 2,
      sym__dedent,
      ts_builtin_sym_end,
    ACTIONS(138), 9,
      anon_sym_SLASH,
      sym_id,
      sym_name,
      anon_sym_DASH_POUND,
      anon_sym_DOT,
      anon_sym_EQ,
      sym_text_content,
      anon_sym_DASH,
      anon_sym_POUND,
  [538] = 4,
    ACTIONS(126), 1,
      sym__indent,
    STATE(40), 1,
      sym__children,
    ACTIONS(140), 2,
      sym__dedent,
      ts_builtin_sym_end,
    ACTIONS(142), 9,
      anon_sym_SLASH,
      sym_id,
      sym_name,
      anon_sym_DASH_POUND,
      anon_sym_DOT,
      anon_sym_EQ,
      sym_text_content,
      anon_sym_DASH,
      anon_sym_POUND,
  [560] = 4,
    ACTIONS(126), 1,
      sym__indent,
    STATE(46), 1,
      sym__children,
    ACTIONS(144), 2,
      sym__dedent,
      ts_builtin_sym_end,
    ACTIONS(146), 9,
      anon_sym_SLASH,
      sym_id,
      sym_name,
      anon_sym_DASH_POUND,
      anon_sym_DOT,
      anon_sym_EQ,
      sym_text_content,
      anon_sym_DASH,
      anon_sym_POUND,
  [582] = 4,
    ACTIONS(126), 1,
      sym__indent,
    STATE(38), 1,
      sym__children,
    ACTIONS(148), 2,
      sym__dedent,
      ts_builtin_sym_end,
    ACTIONS(150), 9,
      anon_sym_SLASH,
      sym_id,
      sym_name,
      anon_sym_DASH_POUND,
      anon_sym_DOT,
      anon_sym_EQ,
      sym_text_content,
      anon_sym_DASH,
      anon_sym_POUND,
  [604] = 4,
    ACTIONS(126), 1,
      sym__indent,
    STATE(24), 1,
      sym__children,
    ACTIONS(152), 2,
      sym__dedent,
      ts_builtin_sym_end,
    ACTIONS(154), 9,
      anon_sym_SLASH,
      sym_id,
      sym_name,
      anon_sym_DASH_POUND,
      anon_sym_DOT,
      anon_sym_EQ,
      sym_text_content,
      anon_sym_DASH,
      anon_sym_POUND,
  [626] = 3,
    ACTIONS(160), 1,
      sym__newline,
    ACTIONS(156), 2,
      sym__dedent,
      ts_builtin_sym_end,
    ACTIONS(158), 9,
      anon_sym_SLASH,
      sym_id,
      sym_name,
      anon_sym_DASH_POUND,
      anon_sym_DOT,
      anon_sym_EQ,
      sym_text_content,
      anon_sym_DASH,
      anon_sym_POUND,
  [645] = 3,
    ACTIONS(166), 1,
      sym__newline,
    ACTIONS(162), 2,
      sym__dedent,
      ts_builtin_sym_end,
    ACTIONS(164), 9,
      anon_sym_SLASH,
      sym_id,
      sym_name,
      anon_sym_DASH_POUND,
      anon_sym_DOT,
      anon_sym_EQ,
      sym_text_content,
      anon_sym_DASH,
      anon_sym_POUND,
  [664] = 3,
    ACTIONS(172), 1,
      sym__indent,
    ACTIONS(168), 2,
      sym__dedent,
      ts_builtin_sym_end,
    ACTIONS(170), 9,
      anon_sym_SLASH,
      sym_id,
      sym_name,
      anon_sym_DASH_POUND,
      anon_sym_DOT,
      anon_sym_EQ,
      sym_text_content,
      anon_sym_DASH,
      anon_sym_POUND,
  [683] = 2,
    ACTIONS(174), 2,
      sym__dedent,
      ts_builtin_sym_end,
    ACTIONS(176), 9,
      anon_sym_SLASH,
      sym_id,
      sym_name,
      anon_sym_DASH_POUND,
      anon_sym_DOT,
      anon_sym_EQ,
      sym_text_content,
      anon_sym_DASH,
      anon_sym_POUND,
  [699] = 4,
    ACTIONS(178), 1,
      sym__indent,
    STATE(57), 1,
      sym__children,
    ACTIONS(142), 2,
      anon_sym_DASH,
      anon_sym_POUND,
    ACTIONS(140), 7,
      ts_builtin_sym_end,
      anon_sym_SLASH,
      sym_id,
      sym_name,
      anon_sym_DASH_POUND,
      anon_sym_DOT,
      anon_sym_EQ,
  [719] = 5,
    ACTIONS(187), 1,
      anon_sym_DOT,
    ACTIONS(184), 2,
      sym_id,
      sym_name,
    STATE(26), 2,
      sym_class,
      aux_sym_tag_repeat1,
    ACTIONS(180), 3,
      anon_sym_SLASH,
      anon_sym_LPAREN,
      anon_sym_EQ,
    ACTIONS(182), 3,
      sym__newline,
      sym_ruby_attributes,
      anon_sym_SPACE,
  [741] = 4,
    ACTIONS(178), 1,
      sym__indent,
    STATE(61), 1,
      sym__children,
    ACTIONS(134), 2,
      anon_sym_DASH,
      anon_sym_POUND,
    ACTIONS(132), 7,
      ts_builtin_sym_end,
      anon_sym_SLASH,
      sym_id,
      sym_name,
      anon_sym_DASH_POUND,
      anon_sym_DOT,
      anon_sym_EQ,
  [761] = 4,
    ACTIONS(178), 1,
      sym__indent,
    STATE(62), 1,
      sym__children,
    ACTIONS(138), 2,
      anon_sym_DASH,
      anon_sym_POUND,
    ACTIONS(136), 7,
      ts_builtin_sym_end,
      anon_sym_SLASH,
      sym_id,
      sym_name,
      anon_sym_DASH_POUND,
      anon_sym_DOT,
      anon_sym_EQ,
  [781] = 4,
    ACTIONS(178), 1,
      sym__indent,
    STATE(66), 1,
      sym__children,
    ACTIONS(146), 2,
      anon_sym_DASH,
      anon_sym_POUND,
    ACTIONS(144), 7,
      ts_builtin_sym_end,
      anon_sym_SLASH,
      sym_id,
      sym_name,
      anon_sym_DASH_POUND,
      anon_sym_DOT,
      anon_sym_EQ,
  [801] = 4,
    ACTIONS(178), 1,
      sym__indent,
    STATE(67), 1,
      sym__children,
    ACTIONS(150), 2,
      anon_sym_DASH,
      anon_sym_POUND,
    ACTIONS(148), 7,
      ts_builtin_sym_end,
      anon_sym_SLASH,
      sym_id,
      sym_name,
      anon_sym_DASH_POUND,
      anon_sym_DOT,
      anon_sym_EQ,
  [821] = 4,
    ACTIONS(178), 1,
      sym__indent,
    STATE(71), 1,
      sym__children,
    ACTIONS(154), 2,
      anon_sym_DASH,
      anon_sym_POUND,
    ACTIONS(152), 7,
      ts_builtin_sym_end,
      anon_sym_SLASH,
      sym_id,
      sym_name,
      anon_sym_DASH_POUND,
      anon_sym_DOT,
      anon_sym_EQ,
  [841] = 2,
    ACTIONS(190), 2,
      sym__dedent,
      ts_builtin_sym_end,
    ACTIONS(192), 9,
      anon_sym_SLASH,
      sym_id,
      sym_name,
      anon_sym_DASH_POUND,
      anon_sym_DOT,
      anon_sym_EQ,
      sym_text_content,
      anon_sym_DASH,
      anon_sym_POUND,
  [857] = 2,
    ACTIONS(122), 2,
      sym__dedent,
      ts_builtin_sym_end,
    ACTIONS(124), 9,
      anon_sym_SLASH,
      sym_id,
      sym_name,
      anon_sym_DASH_POUND,
      anon_sym_DOT,
      anon_sym_EQ,
      sym_text_content,
      anon_sym_DASH,
      anon_sym_POUND,
  [873] = 2,
    ACTIONS(194), 2,
      sym__dedent,
      ts_builtin_sym_end,
    ACTIONS(196), 9,
      anon_sym_SLASH,
      sym_id,
      sym_name,
      anon_sym_DASH_POUND,
      anon_sym_DOT,
      anon_sym_EQ,
      sym_text_content,
      anon_sym_DASH,
      anon_sym_POUND,
  [889] = 2,
    ACTIONS(140), 2,
      sym__dedent,
      ts_builtin_sym_end,
    ACTIONS(142), 9,
      anon_sym_SLASH,
      sym_id,
      sym_name,
      anon_sym_DASH_POUND,
      anon_sym_DOT,
      anon_sym_EQ,
      sym_text_content,
      anon_sym_DASH,
      anon_sym_POUND,
  [905] = 2,
    ACTIONS(128), 2,
      sym__dedent,
      ts_builtin_sym_end,
    ACTIONS(130), 9,
      anon_sym_SLASH,
      sym_id,
      sym_name,
      anon_sym_DASH_POUND,
      anon_sym_DOT,
      anon_sym_EQ,
      sym_text_content,
      anon_sym_DASH,
      anon_sym_POUND,
  [921] = 4,
    ACTIONS(178), 1,
      sym__indent,
    STATE(64), 1,
      sym__children,
    ACTIONS(124), 2,
      anon_sym_DASH,
      anon_sym_POUND,
    ACTIONS(122), 7,
      ts_builtin_sym_end,
      anon_sym_SLASH,
      sym_id,
      sym_name,
      anon_sym_DASH_POUND,
      anon_sym_DOT,
      anon_sym_EQ,
  [941] = 2,
    ACTIONS(198), 2,
      sym__dedent,
      ts_builtin_sym_end,
    ACTIONS(200), 9,
      anon_sym_SLASH,
      sym_id,
      sym_name,
      anon_sym_DASH_POUND,
      anon_sym_DOT,
      anon_sym_EQ,
      sym_text_content,
      anon_sym_DASH,
      anon_sym_POUND,
  [957] = 2,
    ACTIONS(202), 2,
      sym__dedent,
      ts_builtin_sym_end,
    ACTIONS(204), 9,
      anon_sym_SLASH,
      sym_id,
      sym_name,
      anon_sym_DASH_POUND,
      anon_sym_DOT,
      anon_sym_EQ,
      sym_text_content,
      anon_sym_DASH,
      anon_sym_POUND,
  [973] = 2,
    ACTIONS(148), 2,
      sym__dedent,
      ts_builtin_sym_end,
    ACTIONS(150), 9,
      anon_sym_SLASH,
      sym_id,
      sym_name,
      anon_sym_DASH_POUND,
      anon_sym_DOT,
      anon_sym_EQ,
      sym_text_content,
      anon_sym_DASH,
      anon_sym_POUND,
  [989] = 2,
    ACTIONS(144), 2,
      sym__dedent,
      ts_builtin_sym_end,
    ACTIONS(146), 9,
      anon_sym_SLASH,
      sym_id,
      sym_name,
      anon_sym_DASH_POUND,
      anon_sym_DOT,
      anon_sym_EQ,
      sym_text_content,
      anon_sym_DASH,
      anon_sym_POUND,
  [1005] = 2,
    ACTIONS(206), 2,
      sym__dedent,
      ts_builtin_sym_end,
    ACTIONS(208), 9,
      anon_sym_SLASH,
      sym_id,
      sym_name,
      anon_sym_DASH_POUND,
      anon_sym_DOT,
      anon_sym_EQ,
      sym_text_content,
      anon_sym_DASH,
      anon_sym_POUND,
  [1021] = 2,
    ACTIONS(210), 2,
      sym__dedent,
      ts_builtin_sym_end,
    ACTIONS(212), 9,
      anon_sym_SLASH,
      sym_id,
      sym_name,
      anon_sym_DASH_POUND,
      anon_sym_DOT,
      anon_sym_EQ,
      sym_text_content,
      anon_sym_DASH,
      anon_sym_POUND,
  [1037] = 2,
    ACTIONS(214), 2,
      sym__dedent,
      ts_builtin_sym_end,
    ACTIONS(216), 9,
      anon_sym_SLASH,
      sym_id,
      sym_name,
      anon_sym_DASH_POUND,
      anon_sym_DOT,
      anon_sym_EQ,
      sym_text_content,
      anon_sym_DASH,
      anon_sym_POUND,
  [1053] = 2,
    ACTIONS(218), 2,
      sym__dedent,
      ts_builtin_sym_end,
    ACTIONS(220), 9,
      anon_sym_SLASH,
      sym_id,
      sym_name,
      anon_sym_DASH_POUND,
      anon_sym_DOT,
      anon_sym_EQ,
      sym_text_content,
      anon_sym_DASH,
      anon_sym_POUND,
  [1069] = 2,
    ACTIONS(222), 2,
      sym__dedent,
      ts_builtin_sym_end,
    ACTIONS(224), 9,
      anon_sym_SLASH,
      sym_id,
      sym_name,
      anon_sym_DASH_POUND,
      anon_sym_DOT,
      anon_sym_EQ,
      sym_text_content,
      anon_sym_DASH,
      anon_sym_POUND,
  [1085] = 2,
    ACTIONS(152), 2,
      sym__dedent,
      ts_builtin_sym_end,
    ACTIONS(154), 9,
      anon_sym_SLASH,
      sym_id,
      sym_name,
      anon_sym_DASH_POUND,
      anon_sym_DOT,
      anon_sym_EQ,
      sym_text_content,
      anon_sym_DASH,
      anon_sym_POUND,
  [1101] = 4,
    ACTIONS(178), 1,
      sym__indent,
    STATE(54), 1,
      sym__children,
    ACTIONS(130), 2,
      anon_sym_DASH,
      anon_sym_POUND,
    ACTIONS(128), 7,
      ts_builtin_sym_end,
      anon_sym_SLASH,
      sym_id,
      sym_name,
      anon_sym_DASH_POUND,
      anon_sym_DOT,
      anon_sym_EQ,
  [1121] = 2,
    ACTIONS(226), 2,
      sym__dedent,
      ts_builtin_sym_end,
    ACTIONS(228), 9,
      anon_sym_SLASH,
      sym_id,
      sym_name,
      anon_sym_DASH_POUND,
      anon_sym_DOT,
      anon_sym_EQ,
      sym_text_content,
      anon_sym_DASH,
      anon_sym_POUND,
  [1137] = 2,
    ACTIONS(230), 2,
      sym__dedent,
      ts_builtin_sym_end,
    ACTIONS(232), 9,
      anon_sym_SLASH,
      sym_id,
      sym_name,
      anon_sym_DASH_POUND,
      anon_sym_DOT,
      anon_sym_EQ,
      sym_text_content,
      anon_sym_DASH,
      anon_sym_POUND,
  [1153] = 3,
    ACTIONS(234), 1,
      sym__newline,
    ACTIONS(158), 2,
      anon_sym_DASH,
      anon_sym_POUND,
    ACTIONS(156), 7,
      ts_builtin_sym_end,
      anon_sym_SLASH,
      sym_id,
      sym_name,
      anon_sym_DASH_POUND,
      anon_sym_DOT,
      anon_sym_EQ,
  [1170] = 3,
    ACTIONS(236), 1,
      sym__newline,
    ACTIONS(164), 2,
      anon_sym_DASH,
      anon_sym_POUND,
    ACTIONS(162), 7,
      ts_builtin_sym_end,
      anon_sym_SLASH,
      sym_id,
      sym_name,
      anon_sym_DASH_POUND,
      anon_sym_DOT,
      anon_sym_EQ,
  [1187] = 3,
    ACTIONS(238), 1,
      sym__indent,
    ACTIONS(170), 2,
      anon_sym_DASH,
      anon_sym_POUND,
    ACTIONS(168), 7,
      ts_builtin_sym_end,
      anon_sym_SLASH,
      sym_id,
      sym_name,
      anon_sym_DASH_POUND,
      anon_sym_DOT,
      anon_sym_EQ,
  [1204] = 2,
    ACTIONS(204), 2,
      anon_sym_DASH,
      anon_sym_POUND,
    ACTIONS(202), 7,
      ts_builtin_sym_end,
      anon_sym_SLASH,
      sym_id,
      sym_name,
      anon_sym_DASH_POUND,
      anon_sym_DOT,
      anon_sym_EQ,
  [1218] = 2,
    ACTIONS(192), 2,
      anon_sym_DASH,
      anon_sym_POUND,
    ACTIONS(190), 7,
      ts_builtin_sym_end,
      anon_sym_SLASH,
      sym_id,
      sym_name,
      anon_sym_DASH_POUND,
      anon_sym_DOT,
      anon_sym_EQ,
  [1232] = 2,
    ACTIONS(242), 3,
      sym__newline,
      sym_ruby_attributes,
      anon_sym_SPACE,
    ACTIONS(240), 6,
      anon_sym_SLASH,
      anon_sym_LPAREN,
      sym_id,
      sym_name,
      anon_sym_DOT,
      anon_sym_EQ,
  [1246] = 2,
    ACTIONS(150), 2,
      anon_sym_DASH,
      anon_sym_POUND,
    ACTIONS(148), 7,
      ts_builtin_sym_end,
      anon_sym_SLASH,
      sym_id,
      sym_name,
      anon_sym_DASH_POUND,
      anon_sym_DOT,
      anon_sym_EQ,
  [1260] = 2,
    ACTIONS(216), 2,
      anon_sym_DASH,
      anon_sym_POUND,
    ACTIONS(214), 7,
      ts_builtin_sym_end,
      anon_sym_SLASH,
      sym_id,
      sym_name,
      anon_sym_DASH_POUND,
      anon_sym_DOT,
      anon_sym_EQ,
  [1274] = 2,
    ACTIONS(146), 2,
      anon_sym_DASH,
      anon_sym_POUND,
    ACTIONS(144), 7,
      ts_builtin_sym_end,
      anon_sym_SLASH,
      sym_id,
      sym_name,
      anon_sym_DASH_POUND,
      anon_sym_DOT,
      anon_sym_EQ,
  [1288] = 2,
    ACTIONS(196), 2,
      anon_sym_DASH,
      anon_sym_POUND,
    ACTIONS(194), 7,
      ts_builtin_sym_end,
      anon_sym_SLASH,
      sym_id,
      sym_name,
      anon_sym_DASH_POUND,
      anon_sym_DOT,
      anon_sym_EQ,
  [1302] = 2,
    ACTIONS(208), 2,
      anon_sym_DASH,
      anon_sym_POUND,
    ACTIONS(206), 7,
      ts_builtin_sym_end,
      anon_sym_SLASH,
      sym_id,
      sym_name,
      anon_sym_DASH_POUND,
      anon_sym_DOT,
      anon_sym_EQ,
  [1316] = 2,
    ACTIONS(212), 2,
      anon_sym_DASH,
      anon_sym_POUND,
    ACTIONS(210), 7,
      ts_builtin_sym_end,
      anon_sym_SLASH,
      sym_id,
      sym_name,
      anon_sym_DASH_POUND,
      anon_sym_DOT,
      anon_sym_EQ,
  [1330] = 2,
    ACTIONS(220), 2,
      anon_sym_DASH,
      anon_sym_POUND,
    ACTIONS(218), 7,
      ts_builtin_sym_end,
      anon_sym_SLASH,
      sym_id,
      sym_name,
      anon_sym_DASH_POUND,
      anon_sym_DOT,
      anon_sym_EQ,
  [1344] = 2,
    ACTIONS(142), 2,
      anon_sym_DASH,
      anon_sym_POUND,
    ACTIONS(140), 7,
      ts_builtin_sym_end,
      anon_sym_SLASH,
      sym_id,
      sym_name,
      anon_sym_DASH_POUND,
      anon_sym_DOT,
      anon_sym_EQ,
  [1358] = 2,
    ACTIONS(154), 2,
      anon_sym_DASH,
      anon_sym_POUND,
    ACTIONS(152), 7,
      ts_builtin_sym_end,
      anon_sym_SLASH,
      sym_id,
      sym_name,
      anon_sym_DASH_POUND,
      anon_sym_DOT,
      anon_sym_EQ,
  [1372] = 2,
    ACTIONS(224), 2,
      anon_sym_DASH,
      anon_sym_POUND,
    ACTIONS(222), 7,
      ts_builtin_sym_end,
      anon_sym_SLASH,
      sym_id,
      sym_name,
      anon_sym_DASH_POUND,
      anon_sym_DOT,
      anon_sym_EQ,
  [1386] = 2,
    ACTIONS(200), 2,
      anon_sym_DASH,
      anon_sym_POUND,
    ACTIONS(198), 7,
      ts_builtin_sym_end,
      anon_sym_SLASH,
      sym_id,
      sym_name,
      anon_sym_DASH_POUND,
      anon_sym_DOT,
      anon_sym_EQ,
  [1400] = 2,
    ACTIONS(130), 2,
      anon_sym_DASH,
      anon_sym_POUND,
    ACTIONS(128), 7,
      ts_builtin_sym_end,
      anon_sym_SLASH,
      sym_id,
      sym_name,
      anon_sym_DASH_POUND,
      anon_sym_DOT,
      anon_sym_EQ,
  [1414] = 2,
    ACTIONS(228), 2,
      anon_sym_DASH,
      anon_sym_POUND,
    ACTIONS(226), 7,
      ts_builtin_sym_end,
      anon_sym_SLASH,
      sym_id,
      sym_name,
      anon_sym_DASH_POUND,
      anon_sym_DOT,
      anon_sym_EQ,
  [1428] = 2,
    ACTIONS(232), 2,
      anon_sym_DASH,
      anon_sym_POUND,
    ACTIONS(230), 7,
      ts_builtin_sym_end,
      anon_sym_SLASH,
      sym_id,
      sym_name,
      anon_sym_DASH_POUND,
      anon_sym_DOT,
      anon_sym_EQ,
  [1442] = 2,
    ACTIONS(176), 2,
      anon_sym_DASH,
      anon_sym_POUND,
    ACTIONS(174), 7,
      ts_builtin_sym_end,
      anon_sym_SLASH,
      sym_id,
      sym_name,
      anon_sym_DASH_POUND,
      anon_sym_DOT,
      anon_sym_EQ,
  [1456] = 2,
    ACTIONS(124), 2,
      anon_sym_DASH,
      anon_sym_POUND,
    ACTIONS(122), 7,
      ts_builtin_sym_end,
      anon_sym_SLASH,
      sym_id,
      sym_name,
      anon_sym_DASH_POUND,
      anon_sym_DOT,
      anon_sym_EQ,
  [1470] = 5,
    ACTIONS(94), 1,
      anon_sym_EQ,
    ACTIONS(244), 1,
      anon_sym_SLASH,
    ACTIONS(246), 1,
      anon_sym_SPACE,
    ACTIONS(248), 1,
      sym__newline,
    STATE(57), 1,
      sym_ruby_block_output,
  [1486] = 5,
    ACTIONS(94), 1,
      anon_sym_EQ,
    ACTIONS(100), 1,
      anon_sym_SLASH,
    ACTIONS(102), 1,
      anon_sym_SPACE,
    ACTIONS(106), 1,
      sym__newline,
    STATE(64), 1,
      sym_ruby_block_output,
  [1502] = 5,
    ACTIONS(48), 1,
      anon_sym_EQ,
    ACTIONS(116), 1,
      anon_sym_SLASH,
    ACTIONS(118), 1,
      anon_sym_SPACE,
    ACTIONS(120), 1,
      sym__newline,
    STATE(35), 1,
      sym_ruby_block_output,
  [1518] = 5,
    ACTIONS(48), 1,
      anon_sym_EQ,
    ACTIONS(250), 1,
      anon_sym_SLASH,
    ACTIONS(252), 1,
      anon_sym_SPACE,
    ACTIONS(254), 1,
      sym__newline,
    STATE(40), 1,
      sym_ruby_block_output,
  [1534] = 4,
    ACTIONS(48), 1,
      anon_sym_EQ,
    ACTIONS(256), 1,
      anon_sym_SPACE,
    ACTIONS(258), 1,
      sym__newline,
    STATE(36), 1,
      sym_ruby_block_output,
  [1547] = 4,
    ACTIONS(94), 1,
      anon_sym_EQ,
    ACTIONS(260), 1,
      anon_sym_SPACE,
    ACTIONS(262), 1,
      sym__newline,
    STATE(68), 1,
      sym_ruby_block_output,
  [1560] = 2,
    ACTIONS(264), 2,
      anon_sym_SLASH,
      anon_sym_EQ,
    ACTIONS(266), 2,
      sym__newline,
      anon_sym_SPACE,
  [1569] = 4,
    ACTIONS(268), 1,
      anon_sym_LBRACK,
    ACTIONS(270), 1,
      sym__comment_content,
    ACTIONS(272), 1,
      sym__newline,
    STATE(131), 1,
      sym_comment_condition,
  [1582] = 4,
    ACTIONS(94), 1,
      anon_sym_EQ,
    ACTIONS(274), 1,
      anon_sym_SPACE,
    ACTIONS(276), 1,
      sym__newline,
    STATE(65), 1,
      sym_ruby_block_output,
  [1595] = 2,
    ACTIONS(278), 2,
      anon_sym_SLASH,
      anon_sym_EQ,
    ACTIONS(280), 2,
      sym__newline,
      anon_sym_SPACE,
  [1604] = 4,
    ACTIONS(94), 1,
      anon_sym_EQ,
    ACTIONS(282), 1,
      anon_sym_SPACE,
    ACTIONS(284), 1,
      sym__newline,
    STATE(59), 1,
      sym_ruby_block_output,
  [1617] = 4,
    ACTIONS(286), 1,
      anon_sym_RPAREN,
    ACTIONS(288), 1,
      sym_attribute_name,
    STATE(88), 1,
      aux_sym_html_attributes_repeat1,
    STATE(94), 1,
      sym_attribute,
  [1630] = 3,
    ACTIONS(290), 1,
      anon_sym_SPACE,
    ACTIONS(294), 1,
      anon_sym_EQ,
    ACTIONS(292), 2,
      anon_sym_RPAREN,
      sym_attribute_name,
  [1641] = 4,
    ACTIONS(48), 1,
      anon_sym_EQ,
    ACTIONS(296), 1,
      anon_sym_SPACE,
    ACTIONS(298), 1,
      sym__newline,
    STATE(41), 1,
      sym_ruby_block_output,
  [1654] = 2,
    ACTIONS(300), 2,
      anon_sym_SLASH,
      anon_sym_EQ,
    ACTIONS(302), 2,
      sym__newline,
      anon_sym_SPACE,
  [1663] = 4,
    ACTIONS(288), 1,
      sym_attribute_name,
    ACTIONS(304), 1,
      anon_sym_RPAREN,
    STATE(91), 1,
      aux_sym_html_attributes_repeat1,
    STATE(94), 1,
      sym_attribute,
  [1676] = 4,
    ACTIONS(48), 1,
      anon_sym_EQ,
    ACTIONS(306), 1,
      anon_sym_SPACE,
    ACTIONS(308), 1,
      sym__newline,
    STATE(47), 1,
      sym_ruby_block_output,
  [1689] = 4,
    ACTIONS(268), 1,
      anon_sym_LBRACK,
    ACTIONS(310), 1,
      sym__comment_content,
    ACTIONS(312), 1,
      sym__newline,
    STATE(146), 1,
      sym_comment_condition,
  [1702] = 4,
    ACTIONS(314), 1,
      anon_sym_RPAREN,
    ACTIONS(316), 1,
      sym_attribute_name,
    STATE(91), 1,
      aux_sym_html_attributes_repeat1,
    STATE(94), 1,
      sym_attribute,
  [1715] = 3,
    ACTIONS(319), 1,
      sym__comment_content,
    ACTIONS(321), 1,
      sym__dedent,
    STATE(93), 1,
      aux_sym__comment_line_repeat1,
  [1725] = 3,
    ACTIONS(323), 1,
      sym__comment_content,
    ACTIONS(326), 1,
      sym__dedent,
    STATE(93), 1,
      aux_sym__comment_line_repeat1,
  [1735] = 2,
    ACTIONS(328), 1,
      anon_sym_SPACE,
    ACTIONS(330), 2,
      anon_sym_RPAREN,
      sym_attribute_name,
  [1743] = 3,
    ACTIONS(319), 1,
      sym__comment_content,
    ACTIONS(332), 1,
      sym__dedent,
    STATE(93), 1,
      aux_sym__comment_line_repeat1,
  [1753] = 2,
    ACTIONS(334), 1,
      anon_sym_SPACE,
    ACTIONS(336), 2,
      anon_sym_RPAREN,
      sym_attribute_name,
  [1761] = 3,
    ACTIONS(319), 1,
      sym__comment_content,
    ACTIONS(338), 1,
      sym__dedent,
    STATE(93), 1,
      aux_sym__comment_line_repeat1,
  [1771] = 3,
    ACTIONS(319), 1,
      sym__comment_content,
    ACTIONS(340), 1,
      sym__dedent,
    STATE(93), 1,
      aux_sym__comment_line_repeat1,
  [1781] = 3,
    ACTIONS(342), 1,
      anon_sym_SQUOTE,
    ACTIONS(344), 1,
      anon_sym_DQUOTE,
    STATE(96), 1,
      sym_quoted_attribute_value,
  [1791] = 2,
    ACTIONS(346), 1,
      anon_sym_SPACE,
    ACTIONS(348), 2,
      anon_sym_RPAREN,
      sym_attribute_name,
  [1799] = 3,
    ACTIONS(319), 1,
      sym__comment_content,
    ACTIONS(350), 1,
      sym__dedent,
    STATE(93), 1,
      aux_sym__comment_line_repeat1,
  [1809] = 2,
    ACTIONS(352), 1,
      anon_sym_SPACE,
    ACTIONS(354), 2,
      anon_sym_RPAREN,
      sym_attribute_name,
  [1817] = 3,
    ACTIONS(319), 1,
      sym__comment_content,
    ACTIONS(356), 1,
      sym__dedent,
    STATE(93), 1,
      aux_sym__comment_line_repeat1,
  [1827] = 1,
    ACTIONS(326), 2,
      sym__dedent,
      sym__comment_content,
  [1832] = 2,
    ACTIONS(319), 1,
      sym__comment_content,
    STATE(97), 1,
      aux_sym__comment_line_repeat1,
  [1839] = 2,
    ACTIONS(358), 1,
      anon_sym_SQUOTE,
    ACTIONS(360), 1,
      sym__html_identifier,
  [1846] = 2,
    ACTIONS(358), 1,
      anon_sym_DQUOTE,
    ACTIONS(362), 1,
      sym__html_identifier,
  [1853] = 2,
    ACTIONS(319), 1,
      sym__comment_content,
    STATE(101), 1,
      aux_sym__comment_line_repeat1,
  [1860] = 2,
    ACTIONS(319), 1,
      sym__comment_content,
    STATE(95), 1,
      aux_sym__comment_line_repeat1,
  [1867] = 2,
    ACTIONS(319), 1,
      sym__comment_content,
    STATE(92), 1,
      aux_sym__comment_line_repeat1,
  [1874] = 2,
    ACTIONS(319), 1,
      sym__comment_content,
    STATE(98), 1,
      aux_sym__comment_line_repeat1,
  [1881] = 1,
    ACTIONS(314), 2,
      anon_sym_RPAREN,
      sym_attribute_name,
  [1886] = 2,
    ACTIONS(319), 1,
      sym__comment_content,
    STATE(103), 1,
      aux_sym__comment_line_repeat1,
  [1893] = 1,
    ACTIONS(364), 1,
      sym_text_content,
  [1897] = 1,
    ACTIONS(366), 1,
      ts_builtin_sym_end,
  [1901] = 1,
    ACTIONS(368), 1,
      sym__indent,
  [1905] = 1,
    ACTIONS(370), 1,
      sym__newline,
  [1909] = 1,
    ACTIONS(372), 1,
      sym__newline,
  [1913] = 1,
    ACTIONS(374), 1,
      sym__text,
  [1917] = 1,
    ACTIONS(376), 1,
      sym__text,
  [1921] = 1,
    ACTIONS(378), 1,
      sym_ruby_expression,
  [1925] = 1,
    ACTIONS(380), 1,
      sym__newline,
  [1929] = 1,
    ACTIONS(382), 1,
      sym_text_content,
  [1933] = 1,
    ACTIONS(384), 1,
      sym_text_content,
  [1937] = 1,
    ACTIONS(386), 1,
      sym_text_content,
  [1941] = 1,
    ACTIONS(388), 1,
      anon_sym_SQUOTE,
  [1945] = 1,
    ACTIONS(390), 1,
      sym_text_content,
  [1949] = 1,
    ACTIONS(388), 1,
      anon_sym_DQUOTE,
  [1953] = 1,
    ACTIONS(392), 1,
      sym_text_content,
  [1957] = 1,
    ACTIONS(394), 1,
      sym_text_content,
  [1961] = 1,
    ACTIONS(396), 1,
      sym__newline,
  [1965] = 1,
    ACTIONS(398), 1,
      sym__text,
  [1969] = 1,
    ACTIONS(400), 1,
      sym_text_content,
  [1973] = 1,
    ACTIONS(402), 1,
      sym__text,
  [1977] = 1,
    ACTIONS(404), 1,
      sym_text_content,
  [1981] = 1,
    ACTIONS(406), 1,
      anon_sym_RBRACK,
  [1985] = 1,
    ACTIONS(408), 1,
      sym_text_content,
  [1989] = 1,
    ACTIONS(410), 1,
      sym_text_content,
  [1993] = 1,
    ACTIONS(412), 1,
      sym__text,
  [1997] = 1,
    ACTIONS(414), 1,
      sym_text_content,
  [2001] = 1,
    ACTIONS(416), 1,
      sym_ruby_expression,
  [2005] = 1,
    ACTIONS(418), 1,
      sym__indent,
  [2009] = 1,
    ACTIONS(420), 1,
      sym__newline,
  [2013] = 1,
    ACTIONS(422), 1,
      sym__indent,
  [2017] = 1,
    ACTIONS(424), 1,
      sym__indent,
  [2021] = 1,
    ACTIONS(426), 1,
      sym__newline,
  [2025] = 1,
    ACTIONS(428), 1,
      sym_class_name,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 44,
  [SMALL_STATE(4)] = 90,
  [SMALL_STATE(5)] = 136,
  [SMALL_STATE(6)] = 176,
  [SMALL_STATE(7)] = 216,
  [SMALL_STATE(8)] = 255,
  [SMALL_STATE(9)] = 294,
  [SMALL_STATE(10)] = 333,
  [SMALL_STATE(11)] = 372,
  [SMALL_STATE(12)] = 411,
  [SMALL_STATE(13)] = 450,
  [SMALL_STATE(14)] = 472,
  [SMALL_STATE(15)] = 494,
  [SMALL_STATE(16)] = 516,
  [SMALL_STATE(17)] = 538,
  [SMALL_STATE(18)] = 560,
  [SMALL_STATE(19)] = 582,
  [SMALL_STATE(20)] = 604,
  [SMALL_STATE(21)] = 626,
  [SMALL_STATE(22)] = 645,
  [SMALL_STATE(23)] = 664,
  [SMALL_STATE(24)] = 683,
  [SMALL_STATE(25)] = 699,
  [SMALL_STATE(26)] = 719,
  [SMALL_STATE(27)] = 741,
  [SMALL_STATE(28)] = 761,
  [SMALL_STATE(29)] = 781,
  [SMALL_STATE(30)] = 801,
  [SMALL_STATE(31)] = 821,
  [SMALL_STATE(32)] = 841,
  [SMALL_STATE(33)] = 857,
  [SMALL_STATE(34)] = 873,
  [SMALL_STATE(35)] = 889,
  [SMALL_STATE(36)] = 905,
  [SMALL_STATE(37)] = 921,
  [SMALL_STATE(38)] = 941,
  [SMALL_STATE(39)] = 957,
  [SMALL_STATE(40)] = 973,
  [SMALL_STATE(41)] = 989,
  [SMALL_STATE(42)] = 1005,
  [SMALL_STATE(43)] = 1021,
  [SMALL_STATE(44)] = 1037,
  [SMALL_STATE(45)] = 1053,
  [SMALL_STATE(46)] = 1069,
  [SMALL_STATE(47)] = 1085,
  [SMALL_STATE(48)] = 1101,
  [SMALL_STATE(49)] = 1121,
  [SMALL_STATE(50)] = 1137,
  [SMALL_STATE(51)] = 1153,
  [SMALL_STATE(52)] = 1170,
  [SMALL_STATE(53)] = 1187,
  [SMALL_STATE(54)] = 1204,
  [SMALL_STATE(55)] = 1218,
  [SMALL_STATE(56)] = 1232,
  [SMALL_STATE(57)] = 1246,
  [SMALL_STATE(58)] = 1260,
  [SMALL_STATE(59)] = 1274,
  [SMALL_STATE(60)] = 1288,
  [SMALL_STATE(61)] = 1302,
  [SMALL_STATE(62)] = 1316,
  [SMALL_STATE(63)] = 1330,
  [SMALL_STATE(64)] = 1344,
  [SMALL_STATE(65)] = 1358,
  [SMALL_STATE(66)] = 1372,
  [SMALL_STATE(67)] = 1386,
  [SMALL_STATE(68)] = 1400,
  [SMALL_STATE(69)] = 1414,
  [SMALL_STATE(70)] = 1428,
  [SMALL_STATE(71)] = 1442,
  [SMALL_STATE(72)] = 1456,
  [SMALL_STATE(73)] = 1470,
  [SMALL_STATE(74)] = 1486,
  [SMALL_STATE(75)] = 1502,
  [SMALL_STATE(76)] = 1518,
  [SMALL_STATE(77)] = 1534,
  [SMALL_STATE(78)] = 1547,
  [SMALL_STATE(79)] = 1560,
  [SMALL_STATE(80)] = 1569,
  [SMALL_STATE(81)] = 1582,
  [SMALL_STATE(82)] = 1595,
  [SMALL_STATE(83)] = 1604,
  [SMALL_STATE(84)] = 1617,
  [SMALL_STATE(85)] = 1630,
  [SMALL_STATE(86)] = 1641,
  [SMALL_STATE(87)] = 1654,
  [SMALL_STATE(88)] = 1663,
  [SMALL_STATE(89)] = 1676,
  [SMALL_STATE(90)] = 1689,
  [SMALL_STATE(91)] = 1702,
  [SMALL_STATE(92)] = 1715,
  [SMALL_STATE(93)] = 1725,
  [SMALL_STATE(94)] = 1735,
  [SMALL_STATE(95)] = 1743,
  [SMALL_STATE(96)] = 1753,
  [SMALL_STATE(97)] = 1761,
  [SMALL_STATE(98)] = 1771,
  [SMALL_STATE(99)] = 1781,
  [SMALL_STATE(100)] = 1791,
  [SMALL_STATE(101)] = 1799,
  [SMALL_STATE(102)] = 1809,
  [SMALL_STATE(103)] = 1817,
  [SMALL_STATE(104)] = 1827,
  [SMALL_STATE(105)] = 1832,
  [SMALL_STATE(106)] = 1839,
  [SMALL_STATE(107)] = 1846,
  [SMALL_STATE(108)] = 1853,
  [SMALL_STATE(109)] = 1860,
  [SMALL_STATE(110)] = 1867,
  [SMALL_STATE(111)] = 1874,
  [SMALL_STATE(112)] = 1881,
  [SMALL_STATE(113)] = 1886,
  [SMALL_STATE(114)] = 1893,
  [SMALL_STATE(115)] = 1897,
  [SMALL_STATE(116)] = 1901,
  [SMALL_STATE(117)] = 1905,
  [SMALL_STATE(118)] = 1909,
  [SMALL_STATE(119)] = 1913,
  [SMALL_STATE(120)] = 1917,
  [SMALL_STATE(121)] = 1921,
  [SMALL_STATE(122)] = 1925,
  [SMALL_STATE(123)] = 1929,
  [SMALL_STATE(124)] = 1933,
  [SMALL_STATE(125)] = 1937,
  [SMALL_STATE(126)] = 1941,
  [SMALL_STATE(127)] = 1945,
  [SMALL_STATE(128)] = 1949,
  [SMALL_STATE(129)] = 1953,
  [SMALL_STATE(130)] = 1957,
  [SMALL_STATE(131)] = 1961,
  [SMALL_STATE(132)] = 1965,
  [SMALL_STATE(133)] = 1969,
  [SMALL_STATE(134)] = 1973,
  [SMALL_STATE(135)] = 1977,
  [SMALL_STATE(136)] = 1981,
  [SMALL_STATE(137)] = 1985,
  [SMALL_STATE(138)] = 1989,
  [SMALL_STATE(139)] = 1993,
  [SMALL_STATE(140)] = 1997,
  [SMALL_STATE(141)] = 2001,
  [SMALL_STATE(142)] = 2005,
  [SMALL_STATE(143)] = 2009,
  [SMALL_STATE(144)] = 2013,
  [SMALL_STATE(145)] = 2017,
  [SMALL_STATE(146)] = 2021,
  [SMALL_STATE(147)] = 2025,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0, 0, 0),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT(80),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(147),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(134),
  [13] = {.entry = {.count = 1, .reusable = false}}, SHIFT(139),
  [15] = {.entry = {.count = 1, .reusable = false}}, SHIFT(141),
  [17] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym__children_repeat1, 2, 0, 0),
  [19] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym__children_repeat1, 2, 0, 0), SHIFT_REPEAT(90),
  [22] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym__children_repeat1, 2, 0, 0), SHIFT_REPEAT(11),
  [25] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym__children_repeat1, 2, 0, 0), SHIFT_REPEAT(147),
  [28] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym__children_repeat1, 2, 0, 0), SHIFT_REPEAT(119),
  [31] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym__children_repeat1, 2, 0, 0), SHIFT_REPEAT(2),
  [34] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym__children_repeat1, 2, 0, 0), SHIFT_REPEAT(120),
  [37] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym__children_repeat1, 2, 0, 0), SHIFT_REPEAT(121),
  [40] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__children, 2, 0, 0),
  [42] = {.entry = {.count = 1, .reusable = false}}, SHIFT(90),
  [44] = {.entry = {.count = 1, .reusable = false}}, SHIFT(11),
  [46] = {.entry = {.count = 1, .reusable = false}}, SHIFT(147),
  [48] = {.entry = {.count = 1, .reusable = false}}, SHIFT(119),
  [50] = {.entry = {.count = 1, .reusable = false}}, SHIFT(2),
  [52] = {.entry = {.count = 1, .reusable = false}}, SHIFT(120),
  [54] = {.entry = {.count = 1, .reusable = false}}, SHIFT(121),
  [56] = {.entry = {.count = 1, .reusable = true}}, SHIFT(63),
  [58] = {.entry = {.count = 1, .reusable = true}}, SHIFT(45),
  [60] = {.entry = {.count = 1, .reusable = false}}, SHIFT(3),
  [62] = {.entry = {.count = 1, .reusable = false}}, SHIFT(4),
  [64] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [66] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(80),
  [69] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(9),
  [72] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(147),
  [75] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(134),
  [78] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(139),
  [81] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(141),
  [84] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [86] = {.entry = {.count = 1, .reusable = false}}, SHIFT(78),
  [88] = {.entry = {.count = 1, .reusable = true}}, SHIFT(137),
  [90] = {.entry = {.count = 1, .reusable = false}}, SHIFT(84),
  [92] = {.entry = {.count = 1, .reusable = false}}, SHIFT(10),
  [94] = {.entry = {.count = 1, .reusable = false}}, SHIFT(134),
  [96] = {.entry = {.count = 1, .reusable = true}}, SHIFT(37),
  [98] = {.entry = {.count = 1, .reusable = true}}, SHIFT(87),
  [100] = {.entry = {.count = 1, .reusable = false}}, SHIFT(83),
  [102] = {.entry = {.count = 1, .reusable = true}}, SHIFT(123),
  [104] = {.entry = {.count = 1, .reusable = false}}, SHIFT(26),
  [106] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [108] = {.entry = {.count = 1, .reusable = false}}, SHIFT(77),
  [110] = {.entry = {.count = 1, .reusable = true}}, SHIFT(124),
  [112] = {.entry = {.count = 1, .reusable = false}}, SHIFT(12),
  [114] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [116] = {.entry = {.count = 1, .reusable = false}}, SHIFT(86),
  [118] = {.entry = {.count = 1, .reusable = true}}, SHIFT(129),
  [120] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [122] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_tag, 2, 0, 0),
  [124] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_tag, 2, 0, 0),
  [126] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [128] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_tag, 3, 0, 2),
  [130] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_tag, 3, 0, 2),
  [132] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_ruby_block_output, 3, 0, 1),
  [134] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_ruby_block_output, 3, 0, 1),
  [136] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_ruby_block_run, 3, 0, 1),
  [138] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_ruby_block_run, 3, 0, 1),
  [140] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_tag, 3, 0, 0),
  [142] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_tag, 3, 0, 0),
  [144] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_tag, 4, 0, 3),
  [146] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_tag, 4, 0, 3),
  [148] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_tag, 4, 0, 0),
  [150] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_tag, 4, 0, 0),
  [152] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_tag, 5, 0, 4),
  [154] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_tag, 5, 0, 4),
  [156] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_ruby_block_output, 2, 0, 1),
  [158] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_ruby_block_output, 2, 0, 1),
  [160] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [162] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_ruby_block_run, 2, 0, 1),
  [164] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_ruby_block_run, 2, 0, 1),
  [166] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [168] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__comment_line, 3, 0, 0),
  [170] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__comment_line, 3, 0, 0),
  [172] = {.entry = {.count = 1, .reusable = true}}, SHIFT(113),
  [174] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_tag, 6, 0, 4),
  [176] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_tag, 6, 0, 4),
  [178] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [180] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_tag_repeat1, 2, 0, 0),
  [182] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_tag_repeat1, 2, 0, 0),
  [184] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_tag_repeat1, 2, 0, 0), SHIFT_REPEAT(26),
  [187] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_tag_repeat1, 2, 0, 0), SHIFT_REPEAT(147),
  [190] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_comment, 1, 0, 0),
  [192] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_comment, 1, 0, 0),
  [194] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_ruby_interpolation, 2, 0, 0),
  [196] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_ruby_interpolation, 2, 0, 0),
  [198] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_tag, 5, 0, 0),
  [200] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_tag, 5, 0, 0),
  [202] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_tag, 4, 0, 2),
  [204] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_tag, 4, 0, 2),
  [206] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_ruby_block_output, 4, 0, 1),
  [208] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_ruby_block_output, 4, 0, 1),
  [210] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_ruby_block_run, 4, 0, 1),
  [212] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_ruby_block_run, 4, 0, 1),
  [214] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__comment_block, 5, 0, 0),
  [216] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__comment_block, 5, 0, 0),
  [218] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__children, 3, 0, 0),
  [220] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__children, 3, 0, 0),
  [222] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_tag, 5, 0, 3),
  [224] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_tag, 5, 0, 3),
  [226] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__comment_line, 6, 0, 0),
  [228] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__comment_line, 6, 0, 0),
  [230] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__comment_block, 6, 0, 0),
  [232] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__comment_block, 6, 0, 0),
  [234] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [236] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [238] = {.entry = {.count = 1, .reusable = true}}, SHIFT(109),
  [240] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_class, 2, 0, 0),
  [242] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_class, 2, 0, 0),
  [244] = {.entry = {.count = 1, .reusable = false}}, SHIFT(81),
  [246] = {.entry = {.count = 1, .reusable = true}}, SHIFT(140),
  [248] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [250] = {.entry = {.count = 1, .reusable = false}}, SHIFT(89),
  [252] = {.entry = {.count = 1, .reusable = true}}, SHIFT(135),
  [254] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [256] = {.entry = {.count = 1, .reusable = true}}, SHIFT(127),
  [258] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [260] = {.entry = {.count = 1, .reusable = true}}, SHIFT(130),
  [262] = {.entry = {.count = 1, .reusable = true}}, SHIFT(48),
  [264] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_html_attributes, 3, 0, 0),
  [266] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_html_attributes, 3, 0, 0),
  [268] = {.entry = {.count = 1, .reusable = false}}, SHIFT(132),
  [270] = {.entry = {.count = 1, .reusable = false}}, SHIFT(118),
  [272] = {.entry = {.count = 1, .reusable = true}}, SHIFT(116),
  [274] = {.entry = {.count = 1, .reusable = true}}, SHIFT(114),
  [276] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
  [278] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_html_attributes, 2, 0, 0),
  [280] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_html_attributes, 2, 0, 0),
  [282] = {.entry = {.count = 1, .reusable = true}}, SHIFT(125),
  [284] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [286] = {.entry = {.count = 1, .reusable = true}}, SHIFT(82),
  [288] = {.entry = {.count = 1, .reusable = true}}, SHIFT(85),
  [290] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_attribute, 1, 0, 0),
  [292] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_attribute, 1, 0, 0),
  [294] = {.entry = {.count = 1, .reusable = false}}, SHIFT(99),
  [296] = {.entry = {.count = 1, .reusable = true}}, SHIFT(133),
  [298] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [300] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_attributes, 1, 0, 0),
  [302] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_attributes, 1, 0, 0),
  [304] = {.entry = {.count = 1, .reusable = true}}, SHIFT(79),
  [306] = {.entry = {.count = 1, .reusable = true}}, SHIFT(138),
  [308] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [310] = {.entry = {.count = 1, .reusable = false}}, SHIFT(122),
  [312] = {.entry = {.count = 1, .reusable = true}}, SHIFT(144),
  [314] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_html_attributes_repeat1, 2, 0, 0),
  [316] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_html_attributes_repeat1, 2, 0, 0), SHIFT_REPEAT(85),
  [319] = {.entry = {.count = 1, .reusable = true}}, SHIFT(143),
  [321] = {.entry = {.count = 1, .reusable = true}}, SHIFT(70),
  [323] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__comment_line_repeat1, 2, 0, 0), SHIFT_REPEAT(143),
  [326] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym__comment_line_repeat1, 2, 0, 0),
  [328] = {.entry = {.count = 1, .reusable = true}}, SHIFT(112),
  [330] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_html_attributes_repeat1, 1, 0, 0),
  [332] = {.entry = {.count = 1, .reusable = true}}, SHIFT(69),
  [334] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_attribute, 3, 0, 0),
  [336] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_attribute, 3, 0, 0),
  [338] = {.entry = {.count = 1, .reusable = true}}, SHIFT(58),
  [340] = {.entry = {.count = 1, .reusable = true}}, SHIFT(44),
  [342] = {.entry = {.count = 1, .reusable = true}}, SHIFT(106),
  [344] = {.entry = {.count = 1, .reusable = true}}, SHIFT(107),
  [346] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_quoted_attribute_value, 2, 0, 0),
  [348] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_quoted_attribute_value, 2, 0, 0),
  [350] = {.entry = {.count = 1, .reusable = true}}, SHIFT(50),
  [352] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_quoted_attribute_value, 3, 0, 0),
  [354] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_quoted_attribute_value, 3, 0, 0),
  [356] = {.entry = {.count = 1, .reusable = true}}, SHIFT(49),
  [358] = {.entry = {.count = 1, .reusable = true}}, SHIFT(100),
  [360] = {.entry = {.count = 1, .reusable = true}}, SHIFT(126),
  [362] = {.entry = {.count = 1, .reusable = true}}, SHIFT(128),
  [364] = {.entry = {.count = 1, .reusable = true}}, SHIFT(71),
  [366] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [368] = {.entry = {.count = 1, .reusable = true}}, SHIFT(105),
  [370] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_comment_condition, 3, 0, 0),
  [372] = {.entry = {.count = 1, .reusable = true}}, SHIFT(53),
  [374] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [376] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [378] = {.entry = {.count = 1, .reusable = true}}, SHIFT(34),
  [380] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [382] = {.entry = {.count = 1, .reusable = true}}, SHIFT(57),
  [384] = {.entry = {.count = 1, .reusable = true}}, SHIFT(35),
  [386] = {.entry = {.count = 1, .reusable = true}}, SHIFT(66),
  [388] = {.entry = {.count = 1, .reusable = true}}, SHIFT(102),
  [390] = {.entry = {.count = 1, .reusable = true}}, SHIFT(39),
  [392] = {.entry = {.count = 1, .reusable = true}}, SHIFT(40),
  [394] = {.entry = {.count = 1, .reusable = true}}, SHIFT(54),
  [396] = {.entry = {.count = 1, .reusable = true}}, SHIFT(142),
  [398] = {.entry = {.count = 1, .reusable = true}}, SHIFT(136),
  [400] = {.entry = {.count = 1, .reusable = true}}, SHIFT(46),
  [402] = {.entry = {.count = 1, .reusable = true}}, SHIFT(51),
  [404] = {.entry = {.count = 1, .reusable = true}}, SHIFT(38),
  [406] = {.entry = {.count = 1, .reusable = true}}, SHIFT(117),
  [408] = {.entry = {.count = 1, .reusable = true}}, SHIFT(64),
  [410] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [412] = {.entry = {.count = 1, .reusable = true}}, SHIFT(52),
  [414] = {.entry = {.count = 1, .reusable = true}}, SHIFT(67),
  [416] = {.entry = {.count = 1, .reusable = true}}, SHIFT(60),
  [418] = {.entry = {.count = 1, .reusable = true}}, SHIFT(110),
  [420] = {.entry = {.count = 1, .reusable = true}}, SHIFT(104),
  [422] = {.entry = {.count = 1, .reusable = true}}, SHIFT(111),
  [424] = {.entry = {.count = 1, .reusable = true}}, SHIFT(108),
  [426] = {.entry = {.count = 1, .reusable = true}}, SHIFT(145),
  [428] = {.entry = {.count = 1, .reusable = true}}, SHIFT(56),
};

enum ts_external_scanner_symbol_identifiers {
  ts_external_token__newline = 0,
  ts_external_token__indent = 1,
  ts_external_token__dedent = 2,
  ts_external_token_ruby_attributes = 3,
};

static const TSSymbol ts_external_scanner_symbol_map[EXTERNAL_TOKEN_COUNT] = {
  [ts_external_token__newline] = sym__newline,
  [ts_external_token__indent] = sym__indent,
  [ts_external_token__dedent] = sym__dedent,
  [ts_external_token_ruby_attributes] = sym_ruby_attributes,
};

static const bool ts_external_scanner_states[8][EXTERNAL_TOKEN_COUNT] = {
  [1] = {
    [ts_external_token__newline] = true,
    [ts_external_token__indent] = true,
    [ts_external_token__dedent] = true,
    [ts_external_token_ruby_attributes] = true,
  },
  [2] = {
    [ts_external_token__dedent] = true,
  },
  [3] = {
    [ts_external_token__newline] = true,
    [ts_external_token_ruby_attributes] = true,
  },
  [4] = {
    [ts_external_token__indent] = true,
    [ts_external_token__dedent] = true,
  },
  [5] = {
    [ts_external_token__newline] = true,
    [ts_external_token__dedent] = true,
  },
  [6] = {
    [ts_external_token__indent] = true,
  },
  [7] = {
    [ts_external_token__newline] = true,
  },
};

#ifdef __cplusplus
extern "C" {
#endif
void *tree_sitter_haml_external_scanner_create(void);
void tree_sitter_haml_external_scanner_destroy(void *);
bool tree_sitter_haml_external_scanner_scan(void *, TSLexer *, const bool *);
unsigned tree_sitter_haml_external_scanner_serialize(void *, char *);
void tree_sitter_haml_external_scanner_deserialize(void *, const char *, unsigned);

#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_haml(void) {
  static const TSLanguage language = {
    .version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = ts_lex_modes,
    .lex_fn = ts_lex,
    .external_scanner = {
      &ts_external_scanner_states[0][0],
      ts_external_scanner_symbol_map,
      tree_sitter_haml_external_scanner_create,
      tree_sitter_haml_external_scanner_destroy,
      tree_sitter_haml_external_scanner_scan,
      tree_sitter_haml_external_scanner_serialize,
      tree_sitter_haml_external_scanner_deserialize,
    },
    .primary_state_ids = ts_primary_state_ids,
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
