#include "parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 14
#define STATE_COUNT 92
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 37
#define ALIAS_COUNT 0
#define TOKEN_COUNT 21
#define EXTERNAL_TOKEN_COUNT 4
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 6
#define PRODUCTION_ID_COUNT 1

enum ts_symbol_identifiers {
  anon_sym_SLASH = 1,
  anon_sym_SPACE = 2,
  anon_sym_LPAREN = 3,
  anon_sym_RPAREN = 4,
  sym_id = 5,
  sym_name = 6,
  sym_class = 7,
  sym_attribute_name = 8,
  anon_sym_EQ = 9,
  anon_sym_SQUOTE = 10,
  anon_sym_DQUOTE = 11,
  sym__text = 12,
  anon_sym_DASH = 13,
  anon_sym_POUND = 14,
  sym_ruby_expression = 15,
  sym__html_identifier = 16,
  sym__newline = 17,
  sym__indent = 18,
  sym__dedent = 19,
  sym_ruby_attributes = 20,
  sym_source_file = 21,
  sym_tag = 22,
  sym__children = 23,
  sym__children_choice = 24,
  sym_html_attributes = 25,
  sym_attributes = 26,
  sym_attribute = 27,
  sym_quoted_attribute_value = 28,
  sym_text_content = 29,
  sym_ruby_block_output = 30,
  sym_ruby_block_run = 31,
  sym_ruby_interpolation = 32,
  aux_sym_source_file_repeat1 = 33,
  aux_sym_tag_repeat1 = 34,
  aux_sym__children_repeat1 = 35,
  aux_sym_html_attributes_repeat1 = 36,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_SLASH] = "self_close_slash",
  [anon_sym_SPACE] = " ",
  [anon_sym_LPAREN] = "(",
  [anon_sym_RPAREN] = ")",
  [sym_id] = "id",
  [sym_name] = "name",
  [sym_class] = "class",
  [sym_attribute_name] = "attribute_name",
  [anon_sym_EQ] = "=",
  [anon_sym_SQUOTE] = "'",
  [anon_sym_DQUOTE] = "\"",
  [sym__text] = "_text",
  [anon_sym_DASH] = "-",
  [anon_sym_POUND] = "#",
  [sym_ruby_expression] = "ruby_expression",
  [sym__html_identifier] = "attribute_value",
  [sym__newline] = "_newline",
  [sym__indent] = "_indent",
  [sym__dedent] = "_dedent",
  [sym_ruby_attributes] = "ruby_attributes",
  [sym_source_file] = "source_file",
  [sym_tag] = "tag",
  [sym__children] = "_children",
  [sym__children_choice] = "_children_choice",
  [sym_html_attributes] = "html_attributes",
  [sym_attributes] = "attributes",
  [sym_attribute] = "attribute",
  [sym_quoted_attribute_value] = "quoted_attribute_value",
  [sym_text_content] = "text_content",
  [sym_ruby_block_output] = "ruby_block_output",
  [sym_ruby_block_run] = "ruby_block_run",
  [sym_ruby_interpolation] = "ruby_interpolation",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_tag_repeat1] = "tag_repeat1",
  [aux_sym__children_repeat1] = "_children_repeat1",
  [aux_sym_html_attributes_repeat1] = "html_attributes_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_SLASH] = anon_sym_SLASH,
  [anon_sym_SPACE] = anon_sym_SPACE,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [sym_id] = sym_id,
  [sym_name] = sym_name,
  [sym_class] = sym_class,
  [sym_attribute_name] = sym_attribute_name,
  [anon_sym_EQ] = anon_sym_EQ,
  [anon_sym_SQUOTE] = anon_sym_SQUOTE,
  [anon_sym_DQUOTE] = anon_sym_DQUOTE,
  [sym__text] = sym__text,
  [anon_sym_DASH] = anon_sym_DASH,
  [anon_sym_POUND] = anon_sym_POUND,
  [sym_ruby_expression] = sym_ruby_expression,
  [sym__html_identifier] = sym__html_identifier,
  [sym__newline] = sym__newline,
  [sym__indent] = sym__indent,
  [sym__dedent] = sym__dedent,
  [sym_ruby_attributes] = sym_ruby_attributes,
  [sym_source_file] = sym_source_file,
  [sym_tag] = sym_tag,
  [sym__children] = sym__children,
  [sym__children_choice] = sym__children_choice,
  [sym_html_attributes] = sym_html_attributes,
  [sym_attributes] = sym_attributes,
  [sym_attribute] = sym_attribute,
  [sym_quoted_attribute_value] = sym_quoted_attribute_value,
  [sym_text_content] = sym_text_content,
  [sym_ruby_block_output] = sym_ruby_block_output,
  [sym_ruby_block_run] = sym_ruby_block_run,
  [sym_ruby_interpolation] = sym_ruby_interpolation,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_tag_repeat1] = aux_sym_tag_repeat1,
  [aux_sym__children_repeat1] = aux_sym__children_repeat1,
  [aux_sym_html_attributes_repeat1] = aux_sym_html_attributes_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_SLASH] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_SPACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [sym_id] = {
    .visible = true,
    .named = true,
  },
  [sym_name] = {
    .visible = true,
    .named = true,
  },
  [sym_class] = {
    .visible = true,
    .named = true,
  },
  [sym_attribute_name] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SQUOTE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DQUOTE] = {
    .visible = true,
    .named = false,
  },
  [sym__text] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_DASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_POUND] = {
    .visible = true,
    .named = false,
  },
  [sym_ruby_expression] = {
    .visible = true,
    .named = true,
  },
  [sym__html_identifier] = {
    .visible = true,
    .named = true,
  },
  [sym__newline] = {
    .visible = false,
    .named = true,
  },
  [sym__indent] = {
    .visible = false,
    .named = true,
  },
  [sym__dedent] = {
    .visible = false,
    .named = true,
  },
  [sym_ruby_attributes] = {
    .visible = true,
    .named = true,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym_tag] = {
    .visible = true,
    .named = true,
  },
  [sym__children] = {
    .visible = false,
    .named = true,
  },
  [sym__children_choice] = {
    .visible = false,
    .named = true,
  },
  [sym_html_attributes] = {
    .visible = true,
    .named = true,
  },
  [sym_attributes] = {
    .visible = true,
    .named = true,
  },
  [sym_attribute] = {
    .visible = true,
    .named = true,
  },
  [sym_quoted_attribute_value] = {
    .visible = true,
    .named = true,
  },
  [sym_text_content] = {
    .visible = true,
    .named = true,
  },
  [sym_ruby_block_output] = {
    .visible = true,
    .named = true,
  },
  [sym_ruby_block_run] = {
    .visible = true,
    .named = true,
  },
  [sym_ruby_interpolation] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_tag_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym__children_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_html_attributes_repeat1] = {
    .visible = false,
    .named = false,
  },
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 2,
  [6] = 6,
  [7] = 3,
  [8] = 4,
  [9] = 9,
  [10] = 9,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 16,
  [23] = 23,
  [24] = 15,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 13,
  [31] = 31,
  [32] = 18,
  [33] = 19,
  [34] = 34,
  [35] = 17,
  [36] = 23,
  [37] = 28,
  [38] = 38,
  [39] = 38,
  [40] = 21,
  [41] = 20,
  [42] = 42,
  [43] = 26,
  [44] = 25,
  [45] = 29,
  [46] = 31,
  [47] = 27,
  [48] = 42,
  [49] = 34,
  [50] = 50,
  [51] = 51,
  [52] = 50,
  [53] = 53,
  [54] = 51,
  [55] = 53,
  [56] = 56,
  [57] = 57,
  [58] = 58,
  [59] = 59,
  [60] = 60,
  [61] = 61,
  [62] = 62,
  [63] = 63,
  [64] = 64,
  [65] = 65,
  [66] = 66,
  [67] = 67,
  [68] = 68,
  [69] = 69,
  [70] = 70,
  [71] = 68,
  [72] = 72,
  [73] = 69,
  [74] = 72,
  [75] = 75,
  [76] = 75,
  [77] = 77,
  [78] = 78,
  [79] = 79,
  [80] = 80,
  [81] = 81,
  [82] = 82,
  [83] = 83,
  [84] = 84,
  [85] = 82,
  [86] = 86,
  [87] = 80,
  [88] = 83,
  [89] = 84,
  [90] = 90,
  [91] = 90,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(11);
      if (lookahead == '"') ADVANCE(22);
      if (lookahead == '#') ADVANCE(26);
      if (lookahead == '%') ADVANCE(9);
      if (lookahead == '\'') ADVANCE(21);
      if (lookahead == '(') ADVANCE(14);
      if (lookahead == ')') ADVANCE(15);
      if (lookahead == '-') ADVANCE(25);
      if (lookahead == '.') ADVANCE(7);
      if (lookahead == '/') ADVANCE(12);
      if (lookahead == '=') ADVANCE(20);
      if (lookahead == '{') ADVANCE(6);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0)
      END_STATE();
    case 1:
      if (lookahead == '\n') SKIP(1)
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(23);
      if (lookahead != 0) ADVANCE(24);
      END_STATE();
    case 2:
      if (lookahead == ' ') ADVANCE(13);
      if (lookahead == '#') ADVANCE(8);
      if (lookahead == '%') ADVANCE(9);
      if (lookahead == '(') ADVANCE(14);
      if (lookahead == '-') ADVANCE(25);
      if (lookahead == '.') ADVANCE(7);
      if (lookahead == '/') ADVANCE(12);
      if (lookahead == '=') ADVANCE(20);
      if (('\t' <= lookahead && lookahead <= '\r')) SKIP(2)
      END_STATE();
    case 3:
      if (lookahead == ' ') ADVANCE(13);
      if (lookahead == '#') ADVANCE(10);
      if (lookahead == ')') ADVANCE(15);
      if (lookahead == '=') ADVANCE(20);
      if (('\t' <= lookahead && lookahead <= '\r')) SKIP(3)
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= ':') ||
          ('@' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(19);
      END_STATE();
    case 4:
      if (lookahead == '"') ADVANCE(22);
      if (lookahead == '\'') ADVANCE(21);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(4)
      if (('-' <= lookahead && lookahead <= ':') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(28);
      END_STATE();
    case 5:
      if (lookahead == '#') ADVANCE(10);
      if (lookahead == ')') ADVANCE(15);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(5)
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= ':') ||
          ('@' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(19);
      END_STATE();
    case 6:
      if (lookahead == '}') ADVANCE(27);
      if (lookahead != 0) ADVANCE(6);
      END_STATE();
    case 7:
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9')) ADVANCE(7);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(18);
      END_STATE();
    case 8:
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(16);
      END_STATE();
    case 9:
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= ':') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(17);
      END_STATE();
    case 10:
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= ':') ||
          ('@' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(19);
      END_STATE();
    case 11:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 12:
      ACCEPT_TOKEN(anon_sym_SLASH);
      END_STATE();
    case 13:
      ACCEPT_TOKEN(anon_sym_SPACE);
      if (lookahead == ' ') ADVANCE(13);
      END_STATE();
    case 14:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(sym_id);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(16);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(sym_name);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= ':') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(17);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(sym_class);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9')) ADVANCE(18);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(18);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(sym_attribute_name);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= ':') ||
          ('@' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(19);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(anon_sym_EQ);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(anon_sym_SQUOTE);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(anon_sym_DQUOTE);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(sym__text);
      if (lookahead == '\t' ||
          (11 <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(23);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(24);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(sym__text);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(24);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(anon_sym_DASH);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(anon_sym_POUND);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(16);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(sym_ruby_expression);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(sym__html_identifier);
      if (('-' <= lookahead && lookahead <= ':') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(28);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0, .external_lex_state = 1},
  [1] = {.lex_state = 0},
  [2] = {.lex_state = 2, .external_lex_state = 2},
  [3] = {.lex_state = 0, .external_lex_state = 3},
  [4] = {.lex_state = 2, .external_lex_state = 2},
  [5] = {.lex_state = 2, .external_lex_state = 2},
  [6] = {.lex_state = 0, .external_lex_state = 3},
  [7] = {.lex_state = 0, .external_lex_state = 3},
  [8] = {.lex_state = 2, .external_lex_state = 2},
  [9] = {.lex_state = 0, .external_lex_state = 4},
  [10] = {.lex_state = 0, .external_lex_state = 4},
  [11] = {.lex_state = 0},
  [12] = {.lex_state = 0},
  [13] = {.lex_state = 0, .external_lex_state = 5},
  [14] = {.lex_state = 2, .external_lex_state = 2},
  [15] = {.lex_state = 0, .external_lex_state = 5},
  [16] = {.lex_state = 0, .external_lex_state = 5},
  [17] = {.lex_state = 0, .external_lex_state = 5},
  [18] = {.lex_state = 0, .external_lex_state = 5},
  [19] = {.lex_state = 0, .external_lex_state = 5},
  [20] = {.lex_state = 0, .external_lex_state = 3},
  [21] = {.lex_state = 0, .external_lex_state = 3},
  [22] = {.lex_state = 0, .external_lex_state = 6},
  [23] = {.lex_state = 0, .external_lex_state = 3},
  [24] = {.lex_state = 0, .external_lex_state = 6},
  [25] = {.lex_state = 0, .external_lex_state = 3},
  [26] = {.lex_state = 0, .external_lex_state = 3},
  [27] = {.lex_state = 0, .external_lex_state = 3},
  [28] = {.lex_state = 0, .external_lex_state = 3},
  [29] = {.lex_state = 0, .external_lex_state = 3},
  [30] = {.lex_state = 0, .external_lex_state = 6},
  [31] = {.lex_state = 0, .external_lex_state = 3},
  [32] = {.lex_state = 0, .external_lex_state = 6},
  [33] = {.lex_state = 0, .external_lex_state = 6},
  [34] = {.lex_state = 0, .external_lex_state = 3},
  [35] = {.lex_state = 0, .external_lex_state = 6},
  [36] = {.lex_state = 0},
  [37] = {.lex_state = 0},
  [38] = {.lex_state = 2, .external_lex_state = 4},
  [39] = {.lex_state = 2, .external_lex_state = 4},
  [40] = {.lex_state = 0},
  [41] = {.lex_state = 0},
  [42] = {.lex_state = 2, .external_lex_state = 4},
  [43] = {.lex_state = 0},
  [44] = {.lex_state = 0},
  [45] = {.lex_state = 0},
  [46] = {.lex_state = 0},
  [47] = {.lex_state = 0},
  [48] = {.lex_state = 2, .external_lex_state = 4},
  [49] = {.lex_state = 0},
  [50] = {.lex_state = 2, .external_lex_state = 4},
  [51] = {.lex_state = 2, .external_lex_state = 4},
  [52] = {.lex_state = 2, .external_lex_state = 4},
  [53] = {.lex_state = 2, .external_lex_state = 4},
  [54] = {.lex_state = 2, .external_lex_state = 4},
  [55] = {.lex_state = 2, .external_lex_state = 4},
  [56] = {.lex_state = 2, .external_lex_state = 4},
  [57] = {.lex_state = 2, .external_lex_state = 4},
  [58] = {.lex_state = 2, .external_lex_state = 4},
  [59] = {.lex_state = 3},
  [60] = {.lex_state = 5},
  [61] = {.lex_state = 5},
  [62] = {.lex_state = 5},
  [63] = {.lex_state = 3},
  [64] = {.lex_state = 3},
  [65] = {.lex_state = 0},
  [66] = {.lex_state = 3},
  [67] = {.lex_state = 3},
  [68] = {.lex_state = 1},
  [69] = {.lex_state = 1},
  [70] = {.lex_state = 5},
  [71] = {.lex_state = 1},
  [72] = {.lex_state = 1},
  [73] = {.lex_state = 1},
  [74] = {.lex_state = 1},
  [75] = {.lex_state = 1},
  [76] = {.lex_state = 1},
  [77] = {.lex_state = 4},
  [78] = {.lex_state = 4},
  [79] = {.lex_state = 0},
  [80] = {.lex_state = 0},
  [81] = {.lex_state = 0},
  [82] = {.lex_state = 0, .external_lex_state = 4},
  [83] = {.lex_state = 0, .external_lex_state = 4},
  [84] = {.lex_state = 1},
  [85] = {.lex_state = 0, .external_lex_state = 4},
  [86] = {.lex_state = 0},
  [87] = {.lex_state = 0},
  [88] = {.lex_state = 0, .external_lex_state = 4},
  [89] = {.lex_state = 1},
  [90] = {.lex_state = 1},
  [91] = {.lex_state = 1},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [0] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_SLASH] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [sym_id] = ACTIONS(1),
    [sym_name] = ACTIONS(1),
    [sym_class] = ACTIONS(1),
    [anon_sym_EQ] = ACTIONS(1),
    [anon_sym_SQUOTE] = ACTIONS(1),
    [anon_sym_DQUOTE] = ACTIONS(1),
    [anon_sym_DASH] = ACTIONS(1),
    [anon_sym_POUND] = ACTIONS(1),
    [sym_ruby_expression] = ACTIONS(1),
    [sym__newline] = ACTIONS(1),
    [sym__indent] = ACTIONS(1),
    [sym__dedent] = ACTIONS(1),
    [sym_ruby_attributes] = ACTIONS(1),
  },
  [1] = {
    [sym_source_file] = STATE(81),
    [sym_tag] = STATE(11),
    [sym_ruby_block_output] = STATE(11),
    [sym_ruby_block_run] = STATE(11),
    [sym_ruby_interpolation] = STATE(11),
    [aux_sym_source_file_repeat1] = STATE(11),
    [ts_builtin_sym_end] = ACTIONS(3),
    [sym_id] = ACTIONS(5),
    [sym_name] = ACTIONS(5),
    [sym_class] = ACTIONS(5),
    [anon_sym_EQ] = ACTIONS(7),
    [anon_sym_DASH] = ACTIONS(9),
    [anon_sym_POUND] = ACTIONS(11),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 12,
    ACTIONS(13), 1,
      anon_sym_SLASH,
    ACTIONS(15), 1,
      anon_sym_SPACE,
    ACTIONS(17), 1,
      anon_sym_LPAREN,
    ACTIONS(21), 1,
      anon_sym_EQ,
    ACTIONS(23), 1,
      anon_sym_DASH,
    ACTIONS(25), 1,
      sym__newline,
    ACTIONS(27), 1,
      sym_ruby_attributes,
    STATE(8), 1,
      aux_sym_tag_repeat1,
    STATE(48), 1,
      sym_attributes,
    STATE(56), 1,
      sym_html_attributes,
    STATE(37), 2,
      sym_ruby_block_output,
      sym_ruby_block_run,
    ACTIONS(19), 3,
      sym_id,
      sym_name,
      sym_class,
  [40] = 8,
    ACTIONS(29), 1,
      ts_builtin_sym_end,
    ACTIONS(33), 1,
      anon_sym_EQ,
    ACTIONS(35), 1,
      anon_sym_DASH,
    ACTIONS(37), 1,
      anon_sym_POUND,
    ACTIONS(39), 1,
      sym__newline,
    ACTIONS(41), 1,
      sym__dedent,
    ACTIONS(31), 3,
      sym_id,
      sym_name,
      sym_class,
    STATE(6), 6,
      sym_tag,
      sym__children_choice,
      sym_ruby_block_output,
      sym_ruby_block_run,
      sym_ruby_interpolation,
      aux_sym__children_repeat1,
  [72] = 12,
    ACTIONS(17), 1,
      anon_sym_LPAREN,
    ACTIONS(27), 1,
      sym_ruby_attributes,
    ACTIONS(43), 1,
      anon_sym_SLASH,
    ACTIONS(45), 1,
      anon_sym_SPACE,
    ACTIONS(49), 1,
      anon_sym_EQ,
    ACTIONS(51), 1,
      anon_sym_DASH,
    ACTIONS(53), 1,
      sym__newline,
    STATE(14), 1,
      aux_sym_tag_repeat1,
    STATE(39), 1,
      sym_attributes,
    STATE(56), 1,
      sym_html_attributes,
    STATE(26), 2,
      sym_ruby_block_output,
      sym_ruby_block_run,
    ACTIONS(47), 3,
      sym_id,
      sym_name,
      sym_class,
  [112] = 12,
    ACTIONS(17), 1,
      anon_sym_LPAREN,
    ACTIONS(27), 1,
      sym_ruby_attributes,
    ACTIONS(49), 1,
      anon_sym_EQ,
    ACTIONS(51), 1,
      anon_sym_DASH,
    ACTIONS(55), 1,
      anon_sym_SLASH,
    ACTIONS(57), 1,
      anon_sym_SPACE,
    ACTIONS(61), 1,
      sym__newline,
    STATE(4), 1,
      aux_sym_tag_repeat1,
    STATE(42), 1,
      sym_attributes,
    STATE(56), 1,
      sym_html_attributes,
    STATE(28), 2,
      sym_ruby_block_output,
      sym_ruby_block_run,
    ACTIONS(59), 3,
      sym_id,
      sym_name,
      sym_class,
  [152] = 7,
    ACTIONS(68), 1,
      anon_sym_EQ,
    ACTIONS(71), 1,
      anon_sym_DASH,
    ACTIONS(74), 1,
      anon_sym_POUND,
    ACTIONS(77), 1,
      sym__newline,
    ACTIONS(63), 2,
      sym__dedent,
      ts_builtin_sym_end,
    ACTIONS(65), 3,
      sym_id,
      sym_name,
      sym_class,
    STATE(6), 6,
      sym_tag,
      sym__children_choice,
      sym_ruby_block_output,
      sym_ruby_block_run,
      sym_ruby_interpolation,
      aux_sym__children_repeat1,
  [182] = 8,
    ACTIONS(29), 1,
      ts_builtin_sym_end,
    ACTIONS(33), 1,
      anon_sym_EQ,
    ACTIONS(35), 1,
      anon_sym_DASH,
    ACTIONS(37), 1,
      anon_sym_POUND,
    ACTIONS(39), 1,
      sym__newline,
    ACTIONS(80), 1,
      sym__dedent,
    ACTIONS(31), 3,
      sym_id,
      sym_name,
      sym_class,
    STATE(6), 6,
      sym_tag,
      sym__children_choice,
      sym_ruby_block_output,
      sym_ruby_block_run,
      sym_ruby_interpolation,
      aux_sym__children_repeat1,
  [214] = 12,
    ACTIONS(17), 1,
      anon_sym_LPAREN,
    ACTIONS(21), 1,
      anon_sym_EQ,
    ACTIONS(23), 1,
      anon_sym_DASH,
    ACTIONS(27), 1,
      sym_ruby_attributes,
    ACTIONS(82), 1,
      anon_sym_SLASH,
    ACTIONS(84), 1,
      anon_sym_SPACE,
    ACTIONS(86), 1,
      sym__newline,
    STATE(14), 1,
      aux_sym_tag_repeat1,
    STATE(38), 1,
      sym_attributes,
    STATE(56), 1,
      sym_html_attributes,
    STATE(43), 2,
      sym_ruby_block_output,
      sym_ruby_block_run,
    ACTIONS(47), 3,
      sym_id,
      sym_name,
      sym_class,
  [254] = 6,
    ACTIONS(33), 1,
      anon_sym_EQ,
    ACTIONS(35), 1,
      anon_sym_DASH,
    ACTIONS(37), 1,
      anon_sym_POUND,
    ACTIONS(88), 1,
      sym__newline,
    ACTIONS(31), 3,
      sym_id,
      sym_name,
      sym_class,
    STATE(7), 6,
      sym_tag,
      sym__children_choice,
      sym_ruby_block_output,
      sym_ruby_block_run,
      sym_ruby_interpolation,
      aux_sym__children_repeat1,
  [280] = 6,
    ACTIONS(33), 1,
      anon_sym_EQ,
    ACTIONS(35), 1,
      anon_sym_DASH,
    ACTIONS(37), 1,
      anon_sym_POUND,
    ACTIONS(90), 1,
      sym__newline,
    ACTIONS(31), 3,
      sym_id,
      sym_name,
      sym_class,
    STATE(3), 6,
      sym_tag,
      sym__children_choice,
      sym_ruby_block_output,
      sym_ruby_block_run,
      sym_ruby_interpolation,
      aux_sym__children_repeat1,
  [306] = 6,
    ACTIONS(7), 1,
      anon_sym_EQ,
    ACTIONS(9), 1,
      anon_sym_DASH,
    ACTIONS(11), 1,
      anon_sym_POUND,
    ACTIONS(92), 1,
      ts_builtin_sym_end,
    ACTIONS(5), 3,
      sym_id,
      sym_name,
      sym_class,
    STATE(12), 5,
      sym_tag,
      sym_ruby_block_output,
      sym_ruby_block_run,
      sym_ruby_interpolation,
      aux_sym_source_file_repeat1,
  [331] = 6,
    ACTIONS(94), 1,
      ts_builtin_sym_end,
    ACTIONS(99), 1,
      anon_sym_EQ,
    ACTIONS(102), 1,
      anon_sym_DASH,
    ACTIONS(105), 1,
      anon_sym_POUND,
    ACTIONS(96), 3,
      sym_id,
      sym_name,
      sym_class,
    STATE(12), 5,
      sym_tag,
      sym_ruby_block_output,
      sym_ruby_block_run,
      sym_ruby_interpolation,
      aux_sym_source_file_repeat1,
  [356] = 4,
    ACTIONS(110), 1,
      anon_sym_POUND,
    ACTIONS(112), 1,
      sym__indent,
    STATE(20), 1,
      sym__children,
    ACTIONS(108), 8,
      sym__newline,
      sym__dedent,
      ts_builtin_sym_end,
      sym_id,
      sym_name,
      sym_class,
      anon_sym_EQ,
      anon_sym_DASH,
  [376] = 4,
    STATE(14), 1,
      aux_sym_tag_repeat1,
    ACTIONS(116), 3,
      sym__newline,
      sym_ruby_attributes,
      anon_sym_SPACE,
    ACTIONS(118), 3,
      sym_id,
      sym_name,
      sym_class,
    ACTIONS(114), 4,
      anon_sym_SLASH,
      anon_sym_LPAREN,
      anon_sym_EQ,
      anon_sym_DASH,
  [396] = 4,
    ACTIONS(112), 1,
      sym__indent,
    ACTIONS(123), 1,
      anon_sym_POUND,
    STATE(26), 1,
      sym__children,
    ACTIONS(121), 8,
      sym__newline,
      sym__dedent,
      ts_builtin_sym_end,
      sym_id,
      sym_name,
      sym_class,
      anon_sym_EQ,
      anon_sym_DASH,
  [416] = 4,
    ACTIONS(112), 1,
      sym__indent,
    ACTIONS(127), 1,
      anon_sym_POUND,
    STATE(21), 1,
      sym__children,
    ACTIONS(125), 8,
      sym__newline,
      sym__dedent,
      ts_builtin_sym_end,
      sym_id,
      sym_name,
      sym_class,
      anon_sym_EQ,
      anon_sym_DASH,
  [436] = 4,
    ACTIONS(112), 1,
      sym__indent,
    ACTIONS(131), 1,
      anon_sym_POUND,
    STATE(34), 1,
      sym__children,
    ACTIONS(129), 8,
      sym__newline,
      sym__dedent,
      ts_builtin_sym_end,
      sym_id,
      sym_name,
      sym_class,
      anon_sym_EQ,
      anon_sym_DASH,
  [456] = 4,
    ACTIONS(112), 1,
      sym__indent,
    ACTIONS(135), 1,
      anon_sym_POUND,
    STATE(25), 1,
      sym__children,
    ACTIONS(133), 8,
      sym__newline,
      sym__dedent,
      ts_builtin_sym_end,
      sym_id,
      sym_name,
      sym_class,
      anon_sym_EQ,
      anon_sym_DASH,
  [476] = 4,
    ACTIONS(112), 1,
      sym__indent,
    ACTIONS(139), 1,
      anon_sym_POUND,
    STATE(29), 1,
      sym__children,
    ACTIONS(137), 8,
      sym__newline,
      sym__dedent,
      ts_builtin_sym_end,
      sym_id,
      sym_name,
      sym_class,
      anon_sym_EQ,
      anon_sym_DASH,
  [496] = 2,
    ACTIONS(143), 1,
      anon_sym_POUND,
    ACTIONS(141), 8,
      sym__newline,
      sym__dedent,
      ts_builtin_sym_end,
      sym_id,
      sym_name,
      sym_class,
      anon_sym_EQ,
      anon_sym_DASH,
  [510] = 2,
    ACTIONS(131), 1,
      anon_sym_POUND,
    ACTIONS(129), 8,
      sym__newline,
      sym__dedent,
      ts_builtin_sym_end,
      sym_id,
      sym_name,
      sym_class,
      anon_sym_EQ,
      anon_sym_DASH,
  [524] = 4,
    ACTIONS(127), 1,
      anon_sym_POUND,
    ACTIONS(145), 1,
      sym__indent,
    STATE(40), 1,
      sym__children,
    ACTIONS(125), 6,
      ts_builtin_sym_end,
      sym_id,
      sym_name,
      sym_class,
      anon_sym_EQ,
      anon_sym_DASH,
  [542] = 2,
    ACTIONS(149), 1,
      anon_sym_POUND,
    ACTIONS(147), 8,
      sym__newline,
      sym__dedent,
      ts_builtin_sym_end,
      sym_id,
      sym_name,
      sym_class,
      anon_sym_EQ,
      anon_sym_DASH,
  [556] = 4,
    ACTIONS(123), 1,
      anon_sym_POUND,
    ACTIONS(145), 1,
      sym__indent,
    STATE(43), 1,
      sym__children,
    ACTIONS(121), 6,
      ts_builtin_sym_end,
      sym_id,
      sym_name,
      sym_class,
      anon_sym_EQ,
      anon_sym_DASH,
  [574] = 2,
    ACTIONS(153), 1,
      anon_sym_POUND,
    ACTIONS(151), 8,
      sym__newline,
      sym__dedent,
      ts_builtin_sym_end,
      sym_id,
      sym_name,
      sym_class,
      anon_sym_EQ,
      anon_sym_DASH,
  [588] = 2,
    ACTIONS(127), 1,
      anon_sym_POUND,
    ACTIONS(125), 8,
      sym__newline,
      sym__dedent,
      ts_builtin_sym_end,
      sym_id,
      sym_name,
      sym_class,
      anon_sym_EQ,
      anon_sym_DASH,
  [602] = 2,
    ACTIONS(157), 1,
      anon_sym_POUND,
    ACTIONS(155), 8,
      sym__newline,
      sym__dedent,
      ts_builtin_sym_end,
      sym_id,
      sym_name,
      sym_class,
      anon_sym_EQ,
      anon_sym_DASH,
  [616] = 2,
    ACTIONS(123), 1,
      anon_sym_POUND,
    ACTIONS(121), 8,
      sym__newline,
      sym__dedent,
      ts_builtin_sym_end,
      sym_id,
      sym_name,
      sym_class,
      anon_sym_EQ,
      anon_sym_DASH,
  [630] = 2,
    ACTIONS(161), 1,
      anon_sym_POUND,
    ACTIONS(159), 8,
      sym__newline,
      sym__dedent,
      ts_builtin_sym_end,
      sym_id,
      sym_name,
      sym_class,
      anon_sym_EQ,
      anon_sym_DASH,
  [644] = 4,
    ACTIONS(110), 1,
      anon_sym_POUND,
    ACTIONS(145), 1,
      sym__indent,
    STATE(41), 1,
      sym__children,
    ACTIONS(108), 6,
      ts_builtin_sym_end,
      sym_id,
      sym_name,
      sym_class,
      anon_sym_EQ,
      anon_sym_DASH,
  [662] = 2,
    ACTIONS(165), 1,
      anon_sym_POUND,
    ACTIONS(163), 8,
      sym__newline,
      sym__dedent,
      ts_builtin_sym_end,
      sym_id,
      sym_name,
      sym_class,
      anon_sym_EQ,
      anon_sym_DASH,
  [676] = 4,
    ACTIONS(135), 1,
      anon_sym_POUND,
    ACTIONS(145), 1,
      sym__indent,
    STATE(44), 1,
      sym__children,
    ACTIONS(133), 6,
      ts_builtin_sym_end,
      sym_id,
      sym_name,
      sym_class,
      anon_sym_EQ,
      anon_sym_DASH,
  [694] = 4,
    ACTIONS(139), 1,
      anon_sym_POUND,
    ACTIONS(145), 1,
      sym__indent,
    STATE(45), 1,
      sym__children,
    ACTIONS(137), 6,
      ts_builtin_sym_end,
      sym_id,
      sym_name,
      sym_class,
      anon_sym_EQ,
      anon_sym_DASH,
  [712] = 2,
    ACTIONS(110), 1,
      anon_sym_POUND,
    ACTIONS(108), 8,
      sym__newline,
      sym__dedent,
      ts_builtin_sym_end,
      sym_id,
      sym_name,
      sym_class,
      anon_sym_EQ,
      anon_sym_DASH,
  [726] = 4,
    ACTIONS(131), 1,
      anon_sym_POUND,
    ACTIONS(145), 1,
      sym__indent,
    STATE(49), 1,
      sym__children,
    ACTIONS(129), 6,
      ts_builtin_sym_end,
      sym_id,
      sym_name,
      sym_class,
      anon_sym_EQ,
      anon_sym_DASH,
  [744] = 2,
    ACTIONS(149), 1,
      anon_sym_POUND,
    ACTIONS(147), 6,
      ts_builtin_sym_end,
      sym_id,
      sym_name,
      sym_class,
      anon_sym_EQ,
      anon_sym_DASH,
  [756] = 2,
    ACTIONS(123), 1,
      anon_sym_POUND,
    ACTIONS(121), 6,
      ts_builtin_sym_end,
      sym_id,
      sym_name,
      sym_class,
      anon_sym_EQ,
      anon_sym_DASH,
  [768] = 6,
    ACTIONS(21), 1,
      anon_sym_EQ,
    ACTIONS(23), 1,
      anon_sym_DASH,
    ACTIONS(167), 1,
      anon_sym_SLASH,
    ACTIONS(169), 1,
      anon_sym_SPACE,
    ACTIONS(171), 1,
      sym__newline,
    STATE(40), 2,
      sym_ruby_block_output,
      sym_ruby_block_run,
  [788] = 6,
    ACTIONS(49), 1,
      anon_sym_EQ,
    ACTIONS(51), 1,
      anon_sym_DASH,
    ACTIONS(173), 1,
      anon_sym_SLASH,
    ACTIONS(175), 1,
      anon_sym_SPACE,
    ACTIONS(177), 1,
      sym__newline,
    STATE(21), 2,
      sym_ruby_block_output,
      sym_ruby_block_run,
  [808] = 2,
    ACTIONS(131), 1,
      anon_sym_POUND,
    ACTIONS(129), 6,
      ts_builtin_sym_end,
      sym_id,
      sym_name,
      sym_class,
      anon_sym_EQ,
      anon_sym_DASH,
  [820] = 2,
    ACTIONS(143), 1,
      anon_sym_POUND,
    ACTIONS(141), 6,
      ts_builtin_sym_end,
      sym_id,
      sym_name,
      sym_class,
      anon_sym_EQ,
      anon_sym_DASH,
  [832] = 6,
    ACTIONS(43), 1,
      anon_sym_SLASH,
    ACTIONS(45), 1,
      anon_sym_SPACE,
    ACTIONS(49), 1,
      anon_sym_EQ,
    ACTIONS(51), 1,
      anon_sym_DASH,
    ACTIONS(53), 1,
      sym__newline,
    STATE(26), 2,
      sym_ruby_block_output,
      sym_ruby_block_run,
  [852] = 2,
    ACTIONS(127), 1,
      anon_sym_POUND,
    ACTIONS(125), 6,
      ts_builtin_sym_end,
      sym_id,
      sym_name,
      sym_class,
      anon_sym_EQ,
      anon_sym_DASH,
  [864] = 2,
    ACTIONS(153), 1,
      anon_sym_POUND,
    ACTIONS(151), 6,
      ts_builtin_sym_end,
      sym_id,
      sym_name,
      sym_class,
      anon_sym_EQ,
      anon_sym_DASH,
  [876] = 2,
    ACTIONS(161), 1,
      anon_sym_POUND,
    ACTIONS(159), 6,
      ts_builtin_sym_end,
      sym_id,
      sym_name,
      sym_class,
      anon_sym_EQ,
      anon_sym_DASH,
  [888] = 2,
    ACTIONS(165), 1,
      anon_sym_POUND,
    ACTIONS(163), 6,
      ts_builtin_sym_end,
      sym_id,
      sym_name,
      sym_class,
      anon_sym_EQ,
      anon_sym_DASH,
  [900] = 2,
    ACTIONS(157), 1,
      anon_sym_POUND,
    ACTIONS(155), 6,
      ts_builtin_sym_end,
      sym_id,
      sym_name,
      sym_class,
      anon_sym_EQ,
      anon_sym_DASH,
  [912] = 6,
    ACTIONS(21), 1,
      anon_sym_EQ,
    ACTIONS(23), 1,
      anon_sym_DASH,
    ACTIONS(82), 1,
      anon_sym_SLASH,
    ACTIONS(84), 1,
      anon_sym_SPACE,
    ACTIONS(86), 1,
      sym__newline,
    STATE(43), 2,
      sym_ruby_block_output,
      sym_ruby_block_run,
  [932] = 2,
    ACTIONS(110), 1,
      anon_sym_POUND,
    ACTIONS(108), 6,
      ts_builtin_sym_end,
      sym_id,
      sym_name,
      sym_class,
      anon_sym_EQ,
      anon_sym_DASH,
  [944] = 5,
    ACTIONS(21), 1,
      anon_sym_EQ,
    ACTIONS(23), 1,
      anon_sym_DASH,
    ACTIONS(84), 1,
      anon_sym_SPACE,
    ACTIONS(86), 1,
      sym__newline,
    STATE(43), 2,
      sym_ruby_block_output,
      sym_ruby_block_run,
  [961] = 5,
    ACTIONS(21), 1,
      anon_sym_EQ,
    ACTIONS(23), 1,
      anon_sym_DASH,
    ACTIONS(169), 1,
      anon_sym_SPACE,
    ACTIONS(171), 1,
      sym__newline,
    STATE(40), 2,
      sym_ruby_block_output,
      sym_ruby_block_run,
  [978] = 5,
    ACTIONS(45), 1,
      anon_sym_SPACE,
    ACTIONS(49), 1,
      anon_sym_EQ,
    ACTIONS(51), 1,
      anon_sym_DASH,
    ACTIONS(53), 1,
      sym__newline,
    STATE(26), 2,
      sym_ruby_block_output,
      sym_ruby_block_run,
  [995] = 5,
    ACTIONS(21), 1,
      anon_sym_EQ,
    ACTIONS(23), 1,
      anon_sym_DASH,
    ACTIONS(179), 1,
      anon_sym_SPACE,
    ACTIONS(181), 1,
      sym__newline,
    STATE(49), 2,
      sym_ruby_block_output,
      sym_ruby_block_run,
  [1012] = 5,
    ACTIONS(49), 1,
      anon_sym_EQ,
    ACTIONS(51), 1,
      anon_sym_DASH,
    ACTIONS(175), 1,
      anon_sym_SPACE,
    ACTIONS(177), 1,
      sym__newline,
    STATE(21), 2,
      sym_ruby_block_output,
      sym_ruby_block_run,
  [1029] = 5,
    ACTIONS(49), 1,
      anon_sym_EQ,
    ACTIONS(51), 1,
      anon_sym_DASH,
    ACTIONS(183), 1,
      anon_sym_SPACE,
    ACTIONS(185), 1,
      sym__newline,
    STATE(34), 2,
      sym_ruby_block_output,
      sym_ruby_block_run,
  [1046] = 2,
    ACTIONS(189), 2,
      sym__newline,
      anon_sym_SPACE,
    ACTIONS(187), 3,
      anon_sym_SLASH,
      anon_sym_EQ,
      anon_sym_DASH,
  [1056] = 2,
    ACTIONS(193), 2,
      sym__newline,
      anon_sym_SPACE,
    ACTIONS(191), 3,
      anon_sym_SLASH,
      anon_sym_EQ,
      anon_sym_DASH,
  [1066] = 2,
    ACTIONS(197), 2,
      sym__newline,
      anon_sym_SPACE,
    ACTIONS(195), 3,
      anon_sym_SLASH,
      anon_sym_EQ,
      anon_sym_DASH,
  [1076] = 3,
    ACTIONS(199), 1,
      anon_sym_SPACE,
    ACTIONS(203), 1,
      anon_sym_EQ,
    ACTIONS(201), 2,
      anon_sym_RPAREN,
      sym_attribute_name,
  [1087] = 4,
    ACTIONS(205), 1,
      anon_sym_RPAREN,
    ACTIONS(207), 1,
      sym_attribute_name,
    STATE(61), 1,
      aux_sym_html_attributes_repeat1,
    STATE(64), 1,
      sym_attribute,
  [1100] = 4,
    ACTIONS(209), 1,
      anon_sym_RPAREN,
    ACTIONS(211), 1,
      sym_attribute_name,
    STATE(61), 1,
      aux_sym_html_attributes_repeat1,
    STATE(64), 1,
      sym_attribute,
  [1113] = 4,
    ACTIONS(207), 1,
      sym_attribute_name,
    ACTIONS(214), 1,
      anon_sym_RPAREN,
    STATE(60), 1,
      aux_sym_html_attributes_repeat1,
    STATE(64), 1,
      sym_attribute,
  [1126] = 2,
    ACTIONS(216), 1,
      anon_sym_SPACE,
    ACTIONS(218), 2,
      anon_sym_RPAREN,
      sym_attribute_name,
  [1134] = 2,
    ACTIONS(220), 1,
      anon_sym_SPACE,
    ACTIONS(222), 2,
      anon_sym_RPAREN,
      sym_attribute_name,
  [1142] = 3,
    ACTIONS(224), 1,
      anon_sym_SQUOTE,
    ACTIONS(226), 1,
      anon_sym_DQUOTE,
    STATE(66), 1,
      sym_quoted_attribute_value,
  [1152] = 2,
    ACTIONS(228), 1,
      anon_sym_SPACE,
    ACTIONS(230), 2,
      anon_sym_RPAREN,
      sym_attribute_name,
  [1160] = 2,
    ACTIONS(232), 1,
      anon_sym_SPACE,
    ACTIONS(234), 2,
      anon_sym_RPAREN,
      sym_attribute_name,
  [1168] = 2,
    ACTIONS(236), 1,
      sym__text,
    STATE(34), 1,
      sym_text_content,
  [1175] = 2,
    ACTIONS(236), 1,
      sym__text,
    STATE(26), 1,
      sym_text_content,
  [1182] = 1,
    ACTIONS(209), 2,
      anon_sym_RPAREN,
      sym_attribute_name,
  [1187] = 2,
    ACTIONS(238), 1,
      sym__text,
    STATE(49), 1,
      sym_text_content,
  [1194] = 2,
    ACTIONS(238), 1,
      sym__text,
    STATE(41), 1,
      sym_text_content,
  [1201] = 2,
    ACTIONS(238), 1,
      sym__text,
    STATE(43), 1,
      sym_text_content,
  [1208] = 2,
    ACTIONS(236), 1,
      sym__text,
    STATE(20), 1,
      sym_text_content,
  [1215] = 2,
    ACTIONS(236), 1,
      sym__text,
    STATE(21), 1,
      sym_text_content,
  [1222] = 2,
    ACTIONS(238), 1,
      sym__text,
    STATE(40), 1,
      sym_text_content,
  [1229] = 2,
    ACTIONS(240), 1,
      anon_sym_SQUOTE,
    ACTIONS(242), 1,
      sym__html_identifier,
  [1236] = 2,
    ACTIONS(240), 1,
      anon_sym_DQUOTE,
    ACTIONS(244), 1,
      sym__html_identifier,
  [1243] = 1,
    ACTIONS(246), 1,
      anon_sym_SQUOTE,
  [1247] = 1,
    ACTIONS(248), 1,
      sym_ruby_expression,
  [1251] = 1,
    ACTIONS(250), 1,
      ts_builtin_sym_end,
  [1255] = 1,
    ACTIONS(252), 1,
      sym__newline,
  [1259] = 1,
    ACTIONS(254), 1,
      sym__newline,
  [1263] = 1,
    ACTIONS(256), 1,
      sym__text,
  [1267] = 1,
    ACTIONS(258), 1,
      sym__newline,
  [1271] = 1,
    ACTIONS(246), 1,
      anon_sym_DQUOTE,
  [1275] = 1,
    ACTIONS(260), 1,
      sym_ruby_expression,
  [1279] = 1,
    ACTIONS(262), 1,
      sym__newline,
  [1283] = 1,
    ACTIONS(264), 1,
      sym__text,
  [1287] = 1,
    ACTIONS(266), 1,
      sym__text,
  [1291] = 1,
    ACTIONS(268), 1,
      sym__text,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 40,
  [SMALL_STATE(4)] = 72,
  [SMALL_STATE(5)] = 112,
  [SMALL_STATE(6)] = 152,
  [SMALL_STATE(7)] = 182,
  [SMALL_STATE(8)] = 214,
  [SMALL_STATE(9)] = 254,
  [SMALL_STATE(10)] = 280,
  [SMALL_STATE(11)] = 306,
  [SMALL_STATE(12)] = 331,
  [SMALL_STATE(13)] = 356,
  [SMALL_STATE(14)] = 376,
  [SMALL_STATE(15)] = 396,
  [SMALL_STATE(16)] = 416,
  [SMALL_STATE(17)] = 436,
  [SMALL_STATE(18)] = 456,
  [SMALL_STATE(19)] = 476,
  [SMALL_STATE(20)] = 496,
  [SMALL_STATE(21)] = 510,
  [SMALL_STATE(22)] = 524,
  [SMALL_STATE(23)] = 542,
  [SMALL_STATE(24)] = 556,
  [SMALL_STATE(25)] = 574,
  [SMALL_STATE(26)] = 588,
  [SMALL_STATE(27)] = 602,
  [SMALL_STATE(28)] = 616,
  [SMALL_STATE(29)] = 630,
  [SMALL_STATE(30)] = 644,
  [SMALL_STATE(31)] = 662,
  [SMALL_STATE(32)] = 676,
  [SMALL_STATE(33)] = 694,
  [SMALL_STATE(34)] = 712,
  [SMALL_STATE(35)] = 726,
  [SMALL_STATE(36)] = 744,
  [SMALL_STATE(37)] = 756,
  [SMALL_STATE(38)] = 768,
  [SMALL_STATE(39)] = 788,
  [SMALL_STATE(40)] = 808,
  [SMALL_STATE(41)] = 820,
  [SMALL_STATE(42)] = 832,
  [SMALL_STATE(43)] = 852,
  [SMALL_STATE(44)] = 864,
  [SMALL_STATE(45)] = 876,
  [SMALL_STATE(46)] = 888,
  [SMALL_STATE(47)] = 900,
  [SMALL_STATE(48)] = 912,
  [SMALL_STATE(49)] = 932,
  [SMALL_STATE(50)] = 944,
  [SMALL_STATE(51)] = 961,
  [SMALL_STATE(52)] = 978,
  [SMALL_STATE(53)] = 995,
  [SMALL_STATE(54)] = 1012,
  [SMALL_STATE(55)] = 1029,
  [SMALL_STATE(56)] = 1046,
  [SMALL_STATE(57)] = 1056,
  [SMALL_STATE(58)] = 1066,
  [SMALL_STATE(59)] = 1076,
  [SMALL_STATE(60)] = 1087,
  [SMALL_STATE(61)] = 1100,
  [SMALL_STATE(62)] = 1113,
  [SMALL_STATE(63)] = 1126,
  [SMALL_STATE(64)] = 1134,
  [SMALL_STATE(65)] = 1142,
  [SMALL_STATE(66)] = 1152,
  [SMALL_STATE(67)] = 1160,
  [SMALL_STATE(68)] = 1168,
  [SMALL_STATE(69)] = 1175,
  [SMALL_STATE(70)] = 1182,
  [SMALL_STATE(71)] = 1187,
  [SMALL_STATE(72)] = 1194,
  [SMALL_STATE(73)] = 1201,
  [SMALL_STATE(74)] = 1208,
  [SMALL_STATE(75)] = 1215,
  [SMALL_STATE(76)] = 1222,
  [SMALL_STATE(77)] = 1229,
  [SMALL_STATE(78)] = 1236,
  [SMALL_STATE(79)] = 1243,
  [SMALL_STATE(80)] = 1247,
  [SMALL_STATE(81)] = 1251,
  [SMALL_STATE(82)] = 1255,
  [SMALL_STATE(83)] = 1259,
  [SMALL_STATE(84)] = 1263,
  [SMALL_STATE(85)] = 1267,
  [SMALL_STATE(86)] = 1271,
  [SMALL_STATE(87)] = 1275,
  [SMALL_STATE(88)] = 1279,
  [SMALL_STATE(89)] = 1283,
  [SMALL_STATE(90)] = 1287,
  [SMALL_STATE(91)] = 1291,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(84),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(91),
  [11] = {.entry = {.count = 1, .reusable = false}}, SHIFT(87),
  [13] = {.entry = {.count = 1, .reusable = false}}, SHIFT(50),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(73),
  [17] = {.entry = {.count = 1, .reusable = false}}, SHIFT(62),
  [19] = {.entry = {.count = 1, .reusable = false}}, SHIFT(8),
  [21] = {.entry = {.count = 1, .reusable = false}}, SHIFT(84),
  [23] = {.entry = {.count = 1, .reusable = false}}, SHIFT(91),
  [25] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [27] = {.entry = {.count = 1, .reusable = true}}, SHIFT(56),
  [29] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__children, 2),
  [31] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [33] = {.entry = {.count = 1, .reusable = true}}, SHIFT(89),
  [35] = {.entry = {.count = 1, .reusable = true}}, SHIFT(90),
  [37] = {.entry = {.count = 1, .reusable = false}}, SHIFT(80),
  [39] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [41] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
  [43] = {.entry = {.count = 1, .reusable = false}}, SHIFT(54),
  [45] = {.entry = {.count = 1, .reusable = true}}, SHIFT(75),
  [47] = {.entry = {.count = 1, .reusable = false}}, SHIFT(14),
  [49] = {.entry = {.count = 1, .reusable = false}}, SHIFT(89),
  [51] = {.entry = {.count = 1, .reusable = false}}, SHIFT(90),
  [53] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [55] = {.entry = {.count = 1, .reusable = false}}, SHIFT(52),
  [57] = {.entry = {.count = 1, .reusable = true}}, SHIFT(69),
  [59] = {.entry = {.count = 1, .reusable = false}}, SHIFT(4),
  [61] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [63] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym__children_repeat1, 2),
  [65] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__children_repeat1, 2), SHIFT_REPEAT(5),
  [68] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__children_repeat1, 2), SHIFT_REPEAT(89),
  [71] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__children_repeat1, 2), SHIFT_REPEAT(90),
  [74] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym__children_repeat1, 2), SHIFT_REPEAT(80),
  [77] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__children_repeat1, 2), SHIFT_REPEAT(6),
  [80] = {.entry = {.count = 1, .reusable = true}}, SHIFT(46),
  [82] = {.entry = {.count = 1, .reusable = false}}, SHIFT(51),
  [84] = {.entry = {.count = 1, .reusable = true}}, SHIFT(76),
  [86] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [88] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [90] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [92] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1),
  [94] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2),
  [96] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(2),
  [99] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(84),
  [102] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(91),
  [105] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(87),
  [108] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_tag, 5),
  [110] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_tag, 5),
  [112] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [114] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_tag_repeat1, 2),
  [116] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_tag_repeat1, 2),
  [118] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_tag_repeat1, 2), SHIFT_REPEAT(14),
  [121] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_tag, 2),
  [123] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_tag, 2),
  [125] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_tag, 3),
  [127] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_tag, 3),
  [129] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_tag, 4),
  [131] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_tag, 4),
  [133] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_ruby_block_output, 3),
  [135] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_ruby_block_output, 3),
  [137] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_ruby_block_run, 3),
  [139] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_ruby_block_run, 3),
  [141] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_tag, 6),
  [143] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_tag, 6),
  [145] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [147] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_text_content, 1),
  [149] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_text_content, 1),
  [151] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_ruby_block_output, 4),
  [153] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_ruby_block_output, 4),
  [155] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_ruby_interpolation, 2),
  [157] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_ruby_interpolation, 2),
  [159] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_ruby_block_run, 4),
  [161] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_ruby_block_run, 4),
  [163] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__children, 3),
  [165] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__children, 3),
  [167] = {.entry = {.count = 1, .reusable = false}}, SHIFT(53),
  [169] = {.entry = {.count = 1, .reusable = true}}, SHIFT(71),
  [171] = {.entry = {.count = 1, .reusable = true}}, SHIFT(35),
  [173] = {.entry = {.count = 1, .reusable = false}}, SHIFT(55),
  [175] = {.entry = {.count = 1, .reusable = true}}, SHIFT(68),
  [177] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [179] = {.entry = {.count = 1, .reusable = true}}, SHIFT(72),
  [181] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [183] = {.entry = {.count = 1, .reusable = true}}, SHIFT(74),
  [185] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [187] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_attributes, 1),
  [189] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_attributes, 1),
  [191] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_html_attributes, 2),
  [193] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_html_attributes, 2),
  [195] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_html_attributes, 3),
  [197] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_html_attributes, 3),
  [199] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_attribute, 1),
  [201] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_attribute, 1),
  [203] = {.entry = {.count = 1, .reusable = false}}, SHIFT(65),
  [205] = {.entry = {.count = 1, .reusable = true}}, SHIFT(58),
  [207] = {.entry = {.count = 1, .reusable = true}}, SHIFT(59),
  [209] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_html_attributes_repeat1, 2),
  [211] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_html_attributes_repeat1, 2), SHIFT_REPEAT(59),
  [214] = {.entry = {.count = 1, .reusable = true}}, SHIFT(57),
  [216] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_quoted_attribute_value, 3),
  [218] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_quoted_attribute_value, 3),
  [220] = {.entry = {.count = 1, .reusable = true}}, SHIFT(70),
  [222] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_html_attributes_repeat1, 1),
  [224] = {.entry = {.count = 1, .reusable = true}}, SHIFT(77),
  [226] = {.entry = {.count = 1, .reusable = true}}, SHIFT(78),
  [228] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_attribute, 3),
  [230] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_attribute, 3),
  [232] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_quoted_attribute_value, 2),
  [234] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_quoted_attribute_value, 2),
  [236] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [238] = {.entry = {.count = 1, .reusable = true}}, SHIFT(36),
  [240] = {.entry = {.count = 1, .reusable = true}}, SHIFT(67),
  [242] = {.entry = {.count = 1, .reusable = true}}, SHIFT(79),
  [244] = {.entry = {.count = 1, .reusable = true}}, SHIFT(86),
  [246] = {.entry = {.count = 1, .reusable = true}}, SHIFT(63),
  [248] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [250] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [252] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [254] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [256] = {.entry = {.count = 1, .reusable = true}}, SHIFT(85),
  [258] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
  [260] = {.entry = {.count = 1, .reusable = true}}, SHIFT(47),
  [262] = {.entry = {.count = 1, .reusable = true}}, SHIFT(33),
  [264] = {.entry = {.count = 1, .reusable = true}}, SHIFT(82),
  [266] = {.entry = {.count = 1, .reusable = true}}, SHIFT(83),
  [268] = {.entry = {.count = 1, .reusable = true}}, SHIFT(88),
};

enum ts_external_scanner_symbol_identifiers {
  ts_external_token__newline = 0,
  ts_external_token__indent = 1,
  ts_external_token__dedent = 2,
  ts_external_token_ruby_attributes = 3,
};

static const TSSymbol ts_external_scanner_symbol_map[EXTERNAL_TOKEN_COUNT] = {
  [ts_external_token__newline] = sym__newline,
  [ts_external_token__indent] = sym__indent,
  [ts_external_token__dedent] = sym__dedent,
  [ts_external_token_ruby_attributes] = sym_ruby_attributes,
};

static const bool ts_external_scanner_states[7][EXTERNAL_TOKEN_COUNT] = {
  [1] = {
    [ts_external_token__newline] = true,
    [ts_external_token__indent] = true,
    [ts_external_token__dedent] = true,
    [ts_external_token_ruby_attributes] = true,
  },
  [2] = {
    [ts_external_token__newline] = true,
    [ts_external_token_ruby_attributes] = true,
  },
  [3] = {
    [ts_external_token__newline] = true,
    [ts_external_token__dedent] = true,
  },
  [4] = {
    [ts_external_token__newline] = true,
  },
  [5] = {
    [ts_external_token__newline] = true,
    [ts_external_token__indent] = true,
    [ts_external_token__dedent] = true,
  },
  [6] = {
    [ts_external_token__indent] = true,
  },
};

#ifdef __cplusplus
extern "C" {
#endif
void *tree_sitter_haml_external_scanner_create(void);
void tree_sitter_haml_external_scanner_destroy(void *);
bool tree_sitter_haml_external_scanner_scan(void *, TSLexer *, const bool *);
unsigned tree_sitter_haml_external_scanner_serialize(void *, char *);
void tree_sitter_haml_external_scanner_deserialize(void *, const char *, unsigned);

#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_haml() {
  static const TSLanguage language = {
    .version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = ts_lex_modes,
    .lex_fn = ts_lex,
    .external_scanner = {
      &ts_external_scanner_states[0][0],
      ts_external_scanner_symbol_map,
      tree_sitter_haml_external_scanner_create,
      tree_sitter_haml_external_scanner_destroy,
      tree_sitter_haml_external_scanner_scan,
      tree_sitter_haml_external_scanner_serialize,
      tree_sitter_haml_external_scanner_deserialize,
    },
    .primary_state_ids = ts_primary_state_ids,
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
