#include "parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 14
#define STATE_COUNT 108
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 52
#define ALIAS_COUNT 0
#define TOKEN_COUNT 26
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 5
#define PRODUCTION_ID_COUNT 1

enum ts_symbol_identifiers {
  anon_sym_let = 1,
  anon_sym_LBRACE = 2,
  anon_sym_RBRACE = 3,
  anon_sym_in = 4,
  anon_sym_EQ = 5,
  sym_input = 6,
  anon_sym_LBRACK = 7,
  anon_sym_RBRACK = 8,
  anon_sym_DOT = 9,
  aux_sym_path_seg_token1 = 10,
  anon_sym_SQUOTE = 11,
  anon_sym_DQUOTE = 12,
  sym_char = 13,
  anon_sym_DASH = 14,
  aux_sym_float_token1 = 15,
  anon_sym_e = 16,
  anon_sym_PLUS = 17,
  aux_sym__decimal_integer_token1 = 18,
  anon_sym_0x = 19,
  aux_sym__hex_integer_token1 = 20,
  anon_sym_true = 21,
  anon_sym_false = 22,
  sym_null = 23,
  anon_sym_DOT_DOT = 24,
  sym_comment = 25,
  sym_source_file = 26,
  sym_assign_block = 27,
  sym_assignment = 28,
  sym_value = 29,
  sym_object = 30,
  sym__object_value = 31,
  sym_array = 32,
  sym__array_value = 33,
  sym_pair = 34,
  sym_path = 35,
  sym_path_seg = 36,
  sym_string = 37,
  sym_float = 38,
  sym__exponent = 39,
  sym_integer = 40,
  sym__decimal_integer = 41,
  sym__hex_integer = 42,
  sym_boolean = 43,
  sym_spread = 44,
  aux_sym_assign_block_repeat1 = 45,
  aux_sym_object_repeat1 = 46,
  aux_sym_array_repeat1 = 47,
  aux_sym_path_repeat1 = 48,
  aux_sym_path_seg_repeat1 = 49,
  aux_sym_string_repeat1 = 50,
  aux_sym__decimal_integer_repeat1 = 51,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_let] = "let",
  [anon_sym_LBRACE] = "{",
  [anon_sym_RBRACE] = "}",
  [anon_sym_in] = "in",
  [anon_sym_EQ] = "=",
  [sym_input] = "input",
  [anon_sym_LBRACK] = "[",
  [anon_sym_RBRACK] = "]",
  [anon_sym_DOT] = ".",
  [aux_sym_path_seg_token1] = "path_seg_token1",
  [anon_sym_SQUOTE] = "'",
  [anon_sym_DQUOTE] = "\"",
  [sym_char] = "char",
  [anon_sym_DASH] = "-",
  [aux_sym_float_token1] = "float_token1",
  [anon_sym_e] = "e",
  [anon_sym_PLUS] = "+",
  [aux_sym__decimal_integer_token1] = "_decimal_integer_token1",
  [anon_sym_0x] = "0x",
  [aux_sym__hex_integer_token1] = "_hex_integer_token1",
  [anon_sym_true] = "true",
  [anon_sym_false] = "false",
  [sym_null] = "null",
  [anon_sym_DOT_DOT] = "..",
  [sym_comment] = "comment",
  [sym_source_file] = "source_file",
  [sym_assign_block] = "assign_block",
  [sym_assignment] = "assignment",
  [sym_value] = "value",
  [sym_object] = "object",
  [sym__object_value] = "_object_value",
  [sym_array] = "array",
  [sym__array_value] = "_array_value",
  [sym_pair] = "pair",
  [sym_path] = "path",
  [sym_path_seg] = "path_seg",
  [sym_string] = "string",
  [sym_float] = "float",
  [sym__exponent] = "_exponent",
  [sym_integer] = "integer",
  [sym__decimal_integer] = "_decimal_integer",
  [sym__hex_integer] = "_hex_integer",
  [sym_boolean] = "boolean",
  [sym_spread] = "spread",
  [aux_sym_assign_block_repeat1] = "assign_block_repeat1",
  [aux_sym_object_repeat1] = "object_repeat1",
  [aux_sym_array_repeat1] = "array_repeat1",
  [aux_sym_path_repeat1] = "path_repeat1",
  [aux_sym_path_seg_repeat1] = "path_seg_repeat1",
  [aux_sym_string_repeat1] = "string_repeat1",
  [aux_sym__decimal_integer_repeat1] = "_decimal_integer_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_let] = anon_sym_let,
  [anon_sym_LBRACE] = anon_sym_LBRACE,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [anon_sym_in] = anon_sym_in,
  [anon_sym_EQ] = anon_sym_EQ,
  [sym_input] = sym_input,
  [anon_sym_LBRACK] = anon_sym_LBRACK,
  [anon_sym_RBRACK] = anon_sym_RBRACK,
  [anon_sym_DOT] = anon_sym_DOT,
  [aux_sym_path_seg_token1] = aux_sym_path_seg_token1,
  [anon_sym_SQUOTE] = anon_sym_SQUOTE,
  [anon_sym_DQUOTE] = anon_sym_DQUOTE,
  [sym_char] = sym_char,
  [anon_sym_DASH] = anon_sym_DASH,
  [aux_sym_float_token1] = aux_sym_float_token1,
  [anon_sym_e] = anon_sym_e,
  [anon_sym_PLUS] = anon_sym_PLUS,
  [aux_sym__decimal_integer_token1] = aux_sym__decimal_integer_token1,
  [anon_sym_0x] = anon_sym_0x,
  [aux_sym__hex_integer_token1] = aux_sym__hex_integer_token1,
  [anon_sym_true] = anon_sym_true,
  [anon_sym_false] = anon_sym_false,
  [sym_null] = sym_null,
  [anon_sym_DOT_DOT] = anon_sym_DOT_DOT,
  [sym_comment] = sym_comment,
  [sym_source_file] = sym_source_file,
  [sym_assign_block] = sym_assign_block,
  [sym_assignment] = sym_assignment,
  [sym_value] = sym_value,
  [sym_object] = sym_object,
  [sym__object_value] = sym__object_value,
  [sym_array] = sym_array,
  [sym__array_value] = sym__array_value,
  [sym_pair] = sym_pair,
  [sym_path] = sym_path,
  [sym_path_seg] = sym_path_seg,
  [sym_string] = sym_string,
  [sym_float] = sym_float,
  [sym__exponent] = sym__exponent,
  [sym_integer] = sym_integer,
  [sym__decimal_integer] = sym__decimal_integer,
  [sym__hex_integer] = sym__hex_integer,
  [sym_boolean] = sym_boolean,
  [sym_spread] = sym_spread,
  [aux_sym_assign_block_repeat1] = aux_sym_assign_block_repeat1,
  [aux_sym_object_repeat1] = aux_sym_object_repeat1,
  [aux_sym_array_repeat1] = aux_sym_array_repeat1,
  [aux_sym_path_repeat1] = aux_sym_path_repeat1,
  [aux_sym_path_seg_repeat1] = aux_sym_path_seg_repeat1,
  [aux_sym_string_repeat1] = aux_sym_string_repeat1,
  [aux_sym__decimal_integer_repeat1] = aux_sym__decimal_integer_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_let] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_in] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ] = {
    .visible = true,
    .named = false,
  },
  [sym_input] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_LBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DOT] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_path_seg_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_SQUOTE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DQUOTE] = {
    .visible = true,
    .named = false,
  },
  [sym_char] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_DASH] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_float_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_e] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PLUS] = {
    .visible = true,
    .named = false,
  },
  [aux_sym__decimal_integer_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_0x] = {
    .visible = true,
    .named = false,
  },
  [aux_sym__hex_integer_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_true] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_false] = {
    .visible = true,
    .named = false,
  },
  [sym_null] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_DOT_DOT] = {
    .visible = true,
    .named = false,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym_assign_block] = {
    .visible = true,
    .named = true,
  },
  [sym_assignment] = {
    .visible = true,
    .named = true,
  },
  [sym_value] = {
    .visible = true,
    .named = true,
  },
  [sym_object] = {
    .visible = true,
    .named = true,
  },
  [sym__object_value] = {
    .visible = false,
    .named = true,
  },
  [sym_array] = {
    .visible = true,
    .named = true,
  },
  [sym__array_value] = {
    .visible = false,
    .named = true,
  },
  [sym_pair] = {
    .visible = true,
    .named = true,
  },
  [sym_path] = {
    .visible = true,
    .named = true,
  },
  [sym_path_seg] = {
    .visible = true,
    .named = true,
  },
  [sym_string] = {
    .visible = true,
    .named = true,
  },
  [sym_float] = {
    .visible = true,
    .named = true,
  },
  [sym__exponent] = {
    .visible = false,
    .named = true,
  },
  [sym_integer] = {
    .visible = true,
    .named = true,
  },
  [sym__decimal_integer] = {
    .visible = false,
    .named = true,
  },
  [sym__hex_integer] = {
    .visible = false,
    .named = true,
  },
  [sym_boolean] = {
    .visible = true,
    .named = true,
  },
  [sym_spread] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_assign_block_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_object_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_array_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_path_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_path_seg_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_string_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym__decimal_integer_repeat1] = {
    .visible = false,
    .named = false,
  },
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 2,
  [6] = 3,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 31,
  [33] = 30,
  [34] = 34,
  [35] = 9,
  [36] = 12,
  [37] = 11,
  [38] = 16,
  [39] = 17,
  [40] = 10,
  [41] = 14,
  [42] = 9,
  [43] = 12,
  [44] = 44,
  [45] = 45,
  [46] = 23,
  [47] = 45,
  [48] = 18,
  [49] = 24,
  [50] = 50,
  [51] = 25,
  [52] = 52,
  [53] = 27,
  [54] = 26,
  [55] = 28,
  [56] = 15,
  [57] = 29,
  [58] = 13,
  [59] = 59,
  [60] = 22,
  [61] = 61,
  [62] = 62,
  [63] = 16,
  [64] = 64,
  [65] = 14,
  [66] = 17,
  [67] = 19,
  [68] = 68,
  [69] = 20,
  [70] = 70,
  [71] = 21,
  [72] = 68,
  [73] = 73,
  [74] = 74,
  [75] = 75,
  [76] = 62,
  [77] = 77,
  [78] = 78,
  [79] = 79,
  [80] = 80,
  [81] = 81,
  [82] = 82,
  [83] = 83,
  [84] = 82,
  [85] = 85,
  [86] = 86,
  [87] = 87,
  [88] = 88,
  [89] = 89,
  [90] = 90,
  [91] = 91,
  [92] = 92,
  [93] = 93,
  [94] = 94,
  [95] = 89,
  [96] = 96,
  [97] = 97,
  [98] = 98,
  [99] = 88,
  [100] = 85,
  [101] = 101,
  [102] = 102,
  [103] = 93,
  [104] = 98,
  [105] = 94,
  [106] = 88,
  [107] = 107,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(29);
      ADVANCE_MAP(
        '"', 44,
        '\'', 43,
        '+', 53,
        '-', 49,
        '.', 39,
        '/', 41,
        '=', 34,
        '[', 36,
        ']', 37,
        '_', 42,
        'e', 52,
        '{', 31,
        '}', 32,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(42);
      if (lookahead != 0) ADVANCE(40);
      END_STATE();
    case 1:
      if (lookahead == '"') ADVANCE(44);
      if (lookahead == '$') ADVANCE(48);
      if (lookahead == '/') ADVANCE(47);
      if (lookahead == '\n' ||
          lookahead == '\r') SKIP(1);
      if (('\t' <= lookahead && lookahead <= '\f') ||
          lookahead == ' ') ADVANCE(46);
      if (lookahead != 0) ADVANCE(45);
      END_STATE();
    case 2:
      if (lookahead == '$') ADVANCE(26);
      if (lookahead == '.') ADVANCE(38);
      if (lookahead == '/') ADVANCE(9);
      if (lookahead == '_') ADVANCE(25);
      if (lookahead == '}') ADVANCE(32);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(2);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(54);
      END_STATE();
    case 3:
      if (lookahead == '\'') ADVANCE(43);
      if (lookahead == '.') ADVANCE(39);
      if (lookahead == '/') ADVANCE(41);
      if (lookahead == '_') ADVANCE(42);
      if (lookahead == '}') ADVANCE(32);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(3);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(42);
      if (lookahead != 0 &&
          lookahead != '=') ADVANCE(40);
      END_STATE();
    case 4:
      if (lookahead == '\'') ADVANCE(43);
      if (lookahead == '.') ADVANCE(7);
      if (lookahead == '/') ADVANCE(41);
      if (lookahead == 'e') ADVANCE(52);
      if (lookahead == '}') ADVANCE(32);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(4);
      if (lookahead != 0 &&
          lookahead != '=') ADVANCE(40);
      END_STATE();
    case 5:
      if (lookahead == '\'') ADVANCE(43);
      if (lookahead == '.') ADVANCE(7);
      if (lookahead == '/') ADVANCE(41);
      if (lookahead == '}') ADVANCE(32);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(5);
      if (lookahead != 0 &&
          lookahead != '=') ADVANCE(40);
      END_STATE();
    case 6:
      if (lookahead == '\'') ADVANCE(43);
      if (lookahead == '/') ADVANCE(41);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(6);
      if (lookahead != 0 &&
          lookahead != '.' &&
          lookahead != '/' &&
          lookahead != '=') ADVANCE(40);
      END_STATE();
    case 7:
      if (lookahead == '.') ADVANCE(60);
      END_STATE();
    case 8:
      if (lookahead == '.') ADVANCE(38);
      if (lookahead == '/') ADVANCE(41);
      if (lookahead == '=') ADVANCE(34);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(8);
      if (lookahead != 0) ADVANCE(40);
      END_STATE();
    case 9:
      if (lookahead == '/') ADVANCE(61);
      END_STATE();
    case 10:
      if (lookahead == '/') ADVANCE(9);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(10);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(56);
      END_STATE();
    case 11:
      if (lookahead == '/') ADVANCE(9);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(11);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(51);
      END_STATE();
    case 12:
      if (lookahead == 'a') ADVANCE(16);
      END_STATE();
    case 13:
      if (lookahead == 'e') ADVANCE(22);
      END_STATE();
    case 14:
      if (lookahead == 'e') ADVANCE(57);
      END_STATE();
    case 15:
      if (lookahead == 'e') ADVANCE(58);
      END_STATE();
    case 16:
      if (lookahead == 'l') ADVANCE(21);
      END_STATE();
    case 17:
      if (lookahead == 'l') ADVANCE(59);
      END_STATE();
    case 18:
      if (lookahead == 'l') ADVANCE(17);
      END_STATE();
    case 19:
      if (lookahead == 'n') ADVANCE(33);
      END_STATE();
    case 20:
      if (lookahead == 'r') ADVANCE(23);
      END_STATE();
    case 21:
      if (lookahead == 's') ADVANCE(15);
      END_STATE();
    case 22:
      if (lookahead == 't') ADVANCE(30);
      END_STATE();
    case 23:
      if (lookahead == 'u') ADVANCE(14);
      END_STATE();
    case 24:
      if (lookahead == 'u') ADVANCE(18);
      END_STATE();
    case 25:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(54);
      END_STATE();
    case 26:
      if (('A' <= lookahead && lookahead <= 'z')) ADVANCE(27);
      END_STATE();
    case 27:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'z')) ADVANCE(35);
      END_STATE();
    case 28:
      if (eof) ADVANCE(29);
      ADVANCE_MAP(
        '"', 44,
        '$', 26,
        '+', 53,
        '-', 49,
        '.', 39,
        '/', 9,
        '0', 50,
        '[', 36,
        ']', 37,
        '_', 25,
        'e', 52,
        'f', 12,
        'i', 19,
        'l', 13,
        'n', 24,
        't', 20,
        '{', 31,
        '}', 32,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(28);
      if (('1' <= lookahead && lookahead <= '9')) ADVANCE(51);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(anon_sym_let);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(anon_sym_in);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(anon_sym_EQ);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(sym_input);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'z')) ADVANCE(35);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(anon_sym_LBRACK);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(anon_sym_RBRACK);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(anon_sym_DOT);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(anon_sym_DOT);
      if (lookahead == '.') ADVANCE(60);
      END_STATE();
    case 40:
      ACCEPT_TOKEN(aux_sym_path_seg_token1);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(aux_sym_path_seg_token1);
      if (lookahead == '/') ADVANCE(61);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(aux_sym_path_seg_token1);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(54);
      END_STATE();
    case 43:
      ACCEPT_TOKEN(anon_sym_SQUOTE);
      END_STATE();
    case 44:
      ACCEPT_TOKEN(anon_sym_DQUOTE);
      END_STATE();
    case 45:
      ACCEPT_TOKEN(sym_char);
      END_STATE();
    case 46:
      ACCEPT_TOKEN(sym_char);
      if (lookahead == '$') ADVANCE(48);
      if (lookahead == '/') ADVANCE(47);
      if (lookahead == '\t' ||
          lookahead == 0x0b ||
          lookahead == '\f' ||
          lookahead == ' ') ADVANCE(46);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != '"') ADVANCE(45);
      END_STATE();
    case 47:
      ACCEPT_TOKEN(sym_char);
      if (lookahead == '/') ADVANCE(61);
      END_STATE();
    case 48:
      ACCEPT_TOKEN(sym_char);
      if (('A' <= lookahead && lookahead <= 'z')) ADVANCE(27);
      END_STATE();
    case 49:
      ACCEPT_TOKEN(anon_sym_DASH);
      END_STATE();
    case 50:
      ACCEPT_TOKEN(aux_sym_float_token1);
      if (lookahead == 'x') ADVANCE(55);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(51);
      END_STATE();
    case 51:
      ACCEPT_TOKEN(aux_sym_float_token1);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(51);
      END_STATE();
    case 52:
      ACCEPT_TOKEN(anon_sym_e);
      END_STATE();
    case 53:
      ACCEPT_TOKEN(anon_sym_PLUS);
      END_STATE();
    case 54:
      ACCEPT_TOKEN(aux_sym__decimal_integer_token1);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(54);
      END_STATE();
    case 55:
      ACCEPT_TOKEN(anon_sym_0x);
      END_STATE();
    case 56:
      ACCEPT_TOKEN(aux_sym__hex_integer_token1);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(56);
      END_STATE();
    case 57:
      ACCEPT_TOKEN(anon_sym_true);
      END_STATE();
    case 58:
      ACCEPT_TOKEN(anon_sym_false);
      END_STATE();
    case 59:
      ACCEPT_TOKEN(sym_null);
      END_STATE();
    case 60:
      ACCEPT_TOKEN(anon_sym_DOT_DOT);
      END_STATE();
    case 61:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(61);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 28},
  [2] = {.lex_state = 28},
  [3] = {.lex_state = 28},
  [4] = {.lex_state = 28},
  [5] = {.lex_state = 28},
  [6] = {.lex_state = 28},
  [7] = {.lex_state = 28},
  [8] = {.lex_state = 28},
  [9] = {.lex_state = 28},
  [10] = {.lex_state = 28},
  [11] = {.lex_state = 28},
  [12] = {.lex_state = 28},
  [13] = {.lex_state = 28},
  [14] = {.lex_state = 28},
  [15] = {.lex_state = 28},
  [16] = {.lex_state = 28},
  [17] = {.lex_state = 28},
  [18] = {.lex_state = 28},
  [19] = {.lex_state = 28},
  [20] = {.lex_state = 28},
  [21] = {.lex_state = 28},
  [22] = {.lex_state = 28},
  [23] = {.lex_state = 28},
  [24] = {.lex_state = 28},
  [25] = {.lex_state = 28},
  [26] = {.lex_state = 28},
  [27] = {.lex_state = 28},
  [28] = {.lex_state = 28},
  [29] = {.lex_state = 28},
  [30] = {.lex_state = 5},
  [31] = {.lex_state = 5},
  [32] = {.lex_state = 5},
  [33] = {.lex_state = 5},
  [34] = {.lex_state = 5},
  [35] = {.lex_state = 3},
  [36] = {.lex_state = 3},
  [37] = {.lex_state = 4},
  [38] = {.lex_state = 3},
  [39] = {.lex_state = 3},
  [40] = {.lex_state = 4},
  [41] = {.lex_state = 3},
  [42] = {.lex_state = 2},
  [43] = {.lex_state = 2},
  [44] = {.lex_state = 1},
  [45] = {.lex_state = 1},
  [46] = {.lex_state = 5},
  [47] = {.lex_state = 1},
  [48] = {.lex_state = 5},
  [49] = {.lex_state = 5},
  [50] = {.lex_state = 8},
  [51] = {.lex_state = 5},
  [52] = {.lex_state = 28},
  [53] = {.lex_state = 5},
  [54] = {.lex_state = 5},
  [55] = {.lex_state = 5},
  [56] = {.lex_state = 5},
  [57] = {.lex_state = 5},
  [58] = {.lex_state = 5},
  [59] = {.lex_state = 6},
  [60] = {.lex_state = 5},
  [61] = {.lex_state = 28},
  [62] = {.lex_state = 8},
  [63] = {.lex_state = 2},
  [64] = {.lex_state = 28},
  [65] = {.lex_state = 2},
  [66] = {.lex_state = 2},
  [67] = {.lex_state = 5},
  [68] = {.lex_state = 1},
  [69] = {.lex_state = 5},
  [70] = {.lex_state = 5},
  [71] = {.lex_state = 5},
  [72] = {.lex_state = 1},
  [73] = {.lex_state = 0},
  [74] = {.lex_state = 0},
  [75] = {.lex_state = 0},
  [76] = {.lex_state = 6},
  [77] = {.lex_state = 6},
  [78] = {.lex_state = 8},
  [79] = {.lex_state = 0},
  [80] = {.lex_state = 28},
  [81] = {.lex_state = 0},
  [82] = {.lex_state = 28},
  [83] = {.lex_state = 28},
  [84] = {.lex_state = 28},
  [85] = {.lex_state = 10},
  [86] = {.lex_state = 0},
  [87] = {.lex_state = 0},
  [88] = {.lex_state = 11},
  [89] = {.lex_state = 28},
  [90] = {.lex_state = 0},
  [91] = {.lex_state = 28},
  [92] = {.lex_state = 28},
  [93] = {.lex_state = 11},
  [94] = {.lex_state = 11},
  [95] = {.lex_state = 28},
  [96] = {.lex_state = 0},
  [97] = {.lex_state = 28},
  [98] = {.lex_state = 11},
  [99] = {.lex_state = 11},
  [100] = {.lex_state = 10},
  [101] = {.lex_state = 28},
  [102] = {.lex_state = 0},
  [103] = {.lex_state = 11},
  [104] = {.lex_state = 11},
  [105] = {.lex_state = 11},
  [106] = {.lex_state = 11},
  [107] = {.lex_state = 28},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [0] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_LBRACE] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [anon_sym_EQ] = ACTIONS(1),
    [anon_sym_LBRACK] = ACTIONS(1),
    [anon_sym_RBRACK] = ACTIONS(1),
    [anon_sym_DOT] = ACTIONS(1),
    [aux_sym_path_seg_token1] = ACTIONS(1),
    [anon_sym_SQUOTE] = ACTIONS(1),
    [anon_sym_DQUOTE] = ACTIONS(1),
    [anon_sym_DASH] = ACTIONS(1),
    [anon_sym_e] = ACTIONS(1),
    [anon_sym_PLUS] = ACTIONS(1),
    [aux_sym__decimal_integer_token1] = ACTIONS(1),
    [anon_sym_DOT_DOT] = ACTIONS(1),
    [sym_comment] = ACTIONS(3),
  },
  [1] = {
    [sym_source_file] = STATE(86),
    [sym_assign_block] = STATE(80),
    [sym_object] = STATE(102),
    [anon_sym_let] = ACTIONS(5),
    [anon_sym_LBRACE] = ACTIONS(7),
    [sym_comment] = ACTIONS(3),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 14,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(7), 1,
      anon_sym_LBRACE,
    ACTIONS(11), 1,
      anon_sym_LBRACK,
    ACTIONS(13), 1,
      anon_sym_RBRACK,
    ACTIONS(15), 1,
      anon_sym_DQUOTE,
    ACTIONS(17), 1,
      anon_sym_DASH,
    ACTIONS(19), 1,
      aux_sym_float_token1,
    ACTIONS(21), 1,
      anon_sym_0x,
    ACTIONS(25), 1,
      anon_sym_DOT_DOT,
    ACTIONS(9), 2,
      sym_input,
      sym_null,
    ACTIONS(23), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(21), 2,
      sym__decimal_integer,
      sym__hex_integer,
    STATE(4), 4,
      sym_value,
      sym__array_value,
      sym_spread,
      aux_sym_array_repeat1,
    STATE(19), 6,
      sym_object,
      sym_array,
      sym_string,
      sym_float,
      sym_integer,
      sym_boolean,
  [54] = 14,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(7), 1,
      anon_sym_LBRACE,
    ACTIONS(11), 1,
      anon_sym_LBRACK,
    ACTIONS(15), 1,
      anon_sym_DQUOTE,
    ACTIONS(17), 1,
      anon_sym_DASH,
    ACTIONS(19), 1,
      aux_sym_float_token1,
    ACTIONS(21), 1,
      anon_sym_0x,
    ACTIONS(25), 1,
      anon_sym_DOT_DOT,
    ACTIONS(27), 1,
      anon_sym_RBRACK,
    ACTIONS(9), 2,
      sym_input,
      sym_null,
    ACTIONS(23), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(21), 2,
      sym__decimal_integer,
      sym__hex_integer,
    STATE(5), 4,
      sym_value,
      sym__array_value,
      sym_spread,
      aux_sym_array_repeat1,
    STATE(19), 6,
      sym_object,
      sym_array,
      sym_string,
      sym_float,
      sym_integer,
      sym_boolean,
  [108] = 14,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(29), 1,
      anon_sym_LBRACE,
    ACTIONS(35), 1,
      anon_sym_LBRACK,
    ACTIONS(38), 1,
      anon_sym_RBRACK,
    ACTIONS(40), 1,
      anon_sym_DQUOTE,
    ACTIONS(43), 1,
      anon_sym_DASH,
    ACTIONS(46), 1,
      aux_sym_float_token1,
    ACTIONS(49), 1,
      anon_sym_0x,
    ACTIONS(55), 1,
      anon_sym_DOT_DOT,
    ACTIONS(32), 2,
      sym_input,
      sym_null,
    ACTIONS(52), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(21), 2,
      sym__decimal_integer,
      sym__hex_integer,
    STATE(4), 4,
      sym_value,
      sym__array_value,
      sym_spread,
      aux_sym_array_repeat1,
    STATE(19), 6,
      sym_object,
      sym_array,
      sym_string,
      sym_float,
      sym_integer,
      sym_boolean,
  [162] = 14,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(7), 1,
      anon_sym_LBRACE,
    ACTIONS(11), 1,
      anon_sym_LBRACK,
    ACTIONS(15), 1,
      anon_sym_DQUOTE,
    ACTIONS(17), 1,
      anon_sym_DASH,
    ACTIONS(19), 1,
      aux_sym_float_token1,
    ACTIONS(21), 1,
      anon_sym_0x,
    ACTIONS(25), 1,
      anon_sym_DOT_DOT,
    ACTIONS(58), 1,
      anon_sym_RBRACK,
    ACTIONS(9), 2,
      sym_input,
      sym_null,
    ACTIONS(23), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(21), 2,
      sym__decimal_integer,
      sym__hex_integer,
    STATE(4), 4,
      sym_value,
      sym__array_value,
      sym_spread,
      aux_sym_array_repeat1,
    STATE(19), 6,
      sym_object,
      sym_array,
      sym_string,
      sym_float,
      sym_integer,
      sym_boolean,
  [216] = 14,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(7), 1,
      anon_sym_LBRACE,
    ACTIONS(11), 1,
      anon_sym_LBRACK,
    ACTIONS(15), 1,
      anon_sym_DQUOTE,
    ACTIONS(17), 1,
      anon_sym_DASH,
    ACTIONS(19), 1,
      aux_sym_float_token1,
    ACTIONS(21), 1,
      anon_sym_0x,
    ACTIONS(25), 1,
      anon_sym_DOT_DOT,
    ACTIONS(60), 1,
      anon_sym_RBRACK,
    ACTIONS(9), 2,
      sym_input,
      sym_null,
    ACTIONS(23), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(21), 2,
      sym__decimal_integer,
      sym__hex_integer,
    STATE(2), 4,
      sym_value,
      sym__array_value,
      sym_spread,
      aux_sym_array_repeat1,
    STATE(19), 6,
      sym_object,
      sym_array,
      sym_string,
      sym_float,
      sym_integer,
      sym_boolean,
  [270] = 12,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(7), 1,
      anon_sym_LBRACE,
    ACTIONS(11), 1,
      anon_sym_LBRACK,
    ACTIONS(15), 1,
      anon_sym_DQUOTE,
    ACTIONS(21), 1,
      anon_sym_0x,
    ACTIONS(62), 1,
      anon_sym_DASH,
    ACTIONS(64), 1,
      aux_sym_float_token1,
    STATE(83), 1,
      sym_value,
    ACTIONS(9), 2,
      sym_input,
      sym_null,
    ACTIONS(23), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(21), 2,
      sym__decimal_integer,
      sym__hex_integer,
    STATE(19), 6,
      sym_object,
      sym_array,
      sym_string,
      sym_float,
      sym_integer,
      sym_boolean,
  [315] = 12,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(66), 1,
      anon_sym_LBRACE,
    ACTIONS(70), 1,
      anon_sym_LBRACK,
    ACTIONS(72), 1,
      anon_sym_DQUOTE,
    ACTIONS(74), 1,
      anon_sym_DASH,
    ACTIONS(76), 1,
      aux_sym_float_token1,
    ACTIONS(78), 1,
      anon_sym_0x,
    STATE(70), 1,
      sym_value,
    ACTIONS(68), 2,
      sym_input,
      sym_null,
    ACTIONS(80), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(71), 2,
      sym__decimal_integer,
      sym__hex_integer,
    STATE(67), 6,
      sym_object,
      sym_array,
      sym_string,
      sym_float,
      sym_integer,
      sym_boolean,
  [360] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(84), 1,
      anon_sym_DOT,
    ACTIONS(86), 1,
      aux_sym_float_token1,
    ACTIONS(88), 1,
      aux_sym__decimal_integer_token1,
    STATE(16), 1,
      aux_sym__decimal_integer_repeat1,
    ACTIONS(82), 11,
      anon_sym_LBRACE,
      sym_input,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_DQUOTE,
      anon_sym_DASH,
      anon_sym_0x,
      anon_sym_true,
      anon_sym_false,
      sym_null,
      anon_sym_DOT_DOT,
  [389] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(92), 1,
      aux_sym_float_token1,
    ACTIONS(94), 1,
      anon_sym_e,
    STATE(27), 1,
      sym__exponent,
    ACTIONS(90), 12,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      sym_input,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_DQUOTE,
      anon_sym_DASH,
      anon_sym_0x,
      anon_sym_true,
      anon_sym_false,
      sym_null,
      anon_sym_DOT_DOT,
  [416] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(94), 1,
      anon_sym_e,
    ACTIONS(98), 1,
      aux_sym_float_token1,
    STATE(26), 1,
      sym__exponent,
    ACTIONS(96), 12,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      sym_input,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_DQUOTE,
      anon_sym_DASH,
      anon_sym_0x,
      anon_sym_true,
      anon_sym_false,
      sym_null,
      anon_sym_DOT_DOT,
  [443] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(102), 1,
      anon_sym_DOT,
    ACTIONS(104), 1,
      aux_sym_float_token1,
    ACTIONS(106), 1,
      aux_sym__decimal_integer_token1,
    STATE(14), 1,
      aux_sym__decimal_integer_repeat1,
    ACTIONS(100), 11,
      anon_sym_LBRACE,
      sym_input,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_DQUOTE,
      anon_sym_DASH,
      anon_sym_0x,
      anon_sym_true,
      anon_sym_false,
      sym_null,
      anon_sym_DOT_DOT,
  [472] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(110), 1,
      aux_sym_float_token1,
    ACTIONS(108), 13,
      ts_builtin_sym_end,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      sym_input,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_DQUOTE,
      anon_sym_DASH,
      anon_sym_0x,
      anon_sym_true,
      anon_sym_false,
      sym_null,
      anon_sym_DOT_DOT,
  [494] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(114), 1,
      aux_sym_float_token1,
    ACTIONS(116), 1,
      aux_sym__decimal_integer_token1,
    STATE(17), 1,
      aux_sym__decimal_integer_repeat1,
    ACTIONS(112), 11,
      anon_sym_LBRACE,
      sym_input,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_DQUOTE,
      anon_sym_DASH,
      anon_sym_0x,
      anon_sym_true,
      anon_sym_false,
      sym_null,
      anon_sym_DOT_DOT,
  [520] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(120), 1,
      aux_sym_float_token1,
    ACTIONS(118), 13,
      ts_builtin_sym_end,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      sym_input,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_DQUOTE,
      anon_sym_DASH,
      anon_sym_0x,
      anon_sym_true,
      anon_sym_false,
      sym_null,
      anon_sym_DOT_DOT,
  [542] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(104), 1,
      aux_sym_float_token1,
    ACTIONS(116), 1,
      aux_sym__decimal_integer_token1,
    STATE(17), 1,
      aux_sym__decimal_integer_repeat1,
    ACTIONS(100), 11,
      anon_sym_LBRACE,
      sym_input,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_DQUOTE,
      anon_sym_DASH,
      anon_sym_0x,
      anon_sym_true,
      anon_sym_false,
      sym_null,
      anon_sym_DOT_DOT,
  [568] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(124), 1,
      aux_sym_float_token1,
    ACTIONS(126), 1,
      aux_sym__decimal_integer_token1,
    STATE(17), 1,
      aux_sym__decimal_integer_repeat1,
    ACTIONS(122), 11,
      anon_sym_LBRACE,
      sym_input,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_DQUOTE,
      anon_sym_DASH,
      anon_sym_0x,
      anon_sym_true,
      anon_sym_false,
      sym_null,
      anon_sym_DOT_DOT,
  [594] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(131), 1,
      aux_sym_float_token1,
    ACTIONS(129), 12,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      sym_input,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_DQUOTE,
      anon_sym_DASH,
      anon_sym_0x,
      anon_sym_true,
      anon_sym_false,
      sym_null,
      anon_sym_DOT_DOT,
  [615] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(135), 1,
      aux_sym_float_token1,
    ACTIONS(133), 12,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      sym_input,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_DQUOTE,
      anon_sym_DASH,
      anon_sym_0x,
      anon_sym_true,
      anon_sym_false,
      sym_null,
      anon_sym_DOT_DOT,
  [636] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(139), 1,
      aux_sym_float_token1,
    ACTIONS(137), 12,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      sym_input,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_DQUOTE,
      anon_sym_DASH,
      anon_sym_0x,
      anon_sym_true,
      anon_sym_false,
      sym_null,
      anon_sym_DOT_DOT,
  [657] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(143), 1,
      aux_sym_float_token1,
    ACTIONS(141), 12,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      sym_input,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_DQUOTE,
      anon_sym_DASH,
      anon_sym_0x,
      anon_sym_true,
      anon_sym_false,
      sym_null,
      anon_sym_DOT_DOT,
  [678] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(147), 1,
      aux_sym_float_token1,
    ACTIONS(145), 12,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      sym_input,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_DQUOTE,
      anon_sym_DASH,
      anon_sym_0x,
      anon_sym_true,
      anon_sym_false,
      sym_null,
      anon_sym_DOT_DOT,
  [699] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(151), 1,
      aux_sym_float_token1,
    ACTIONS(149), 12,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      sym_input,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_DQUOTE,
      anon_sym_DASH,
      anon_sym_0x,
      anon_sym_true,
      anon_sym_false,
      sym_null,
      anon_sym_DOT_DOT,
  [720] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(155), 1,
      aux_sym_float_token1,
    ACTIONS(153), 12,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      sym_input,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_DQUOTE,
      anon_sym_DASH,
      anon_sym_0x,
      anon_sym_true,
      anon_sym_false,
      sym_null,
      anon_sym_DOT_DOT,
  [741] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(159), 1,
      aux_sym_float_token1,
    ACTIONS(157), 12,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      sym_input,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_DQUOTE,
      anon_sym_DASH,
      anon_sym_0x,
      anon_sym_true,
      anon_sym_false,
      sym_null,
      anon_sym_DOT_DOT,
  [762] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(163), 1,
      aux_sym_float_token1,
    ACTIONS(161), 12,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      sym_input,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_DQUOTE,
      anon_sym_DASH,
      anon_sym_0x,
      anon_sym_true,
      anon_sym_false,
      sym_null,
      anon_sym_DOT_DOT,
  [783] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(98), 1,
      aux_sym_float_token1,
    ACTIONS(96), 12,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      sym_input,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_DQUOTE,
      anon_sym_DASH,
      anon_sym_0x,
      anon_sym_true,
      anon_sym_false,
      sym_null,
      anon_sym_DOT_DOT,
  [804] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(167), 1,
      aux_sym_float_token1,
    ACTIONS(165), 12,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      sym_input,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_DQUOTE,
      anon_sym_DASH,
      anon_sym_0x,
      anon_sym_true,
      anon_sym_false,
      sym_null,
      anon_sym_DOT_DOT,
  [825] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(171), 1,
      aux_sym_float_token1,
    ACTIONS(169), 11,
      anon_sym_LBRACE,
      sym_input,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_DQUOTE,
      anon_sym_DASH,
      anon_sym_0x,
      anon_sym_true,
      anon_sym_false,
      sym_null,
      anon_sym_DOT_DOT,
  [845] = 9,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(173), 1,
      anon_sym_RBRACE,
    ACTIONS(175), 1,
      aux_sym_path_seg_token1,
    ACTIONS(177), 1,
      anon_sym_SQUOTE,
    ACTIONS(179), 1,
      anon_sym_DOT_DOT,
    STATE(50), 1,
      aux_sym_path_seg_repeat1,
    STATE(75), 1,
      sym_path_seg,
    STATE(90), 1,
      sym_path,
    STATE(31), 4,
      sym__object_value,
      sym_pair,
      sym_spread,
      aux_sym_object_repeat1,
  [876] = 9,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(175), 1,
      aux_sym_path_seg_token1,
    ACTIONS(177), 1,
      anon_sym_SQUOTE,
    ACTIONS(179), 1,
      anon_sym_DOT_DOT,
    ACTIONS(181), 1,
      anon_sym_RBRACE,
    STATE(50), 1,
      aux_sym_path_seg_repeat1,
    STATE(75), 1,
      sym_path_seg,
    STATE(90), 1,
      sym_path,
    STATE(34), 4,
      sym__object_value,
      sym_pair,
      sym_spread,
      aux_sym_object_repeat1,
  [907] = 9,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(175), 1,
      aux_sym_path_seg_token1,
    ACTIONS(177), 1,
      anon_sym_SQUOTE,
    ACTIONS(179), 1,
      anon_sym_DOT_DOT,
    ACTIONS(183), 1,
      anon_sym_RBRACE,
    STATE(50), 1,
      aux_sym_path_seg_repeat1,
    STATE(75), 1,
      sym_path_seg,
    STATE(90), 1,
      sym_path,
    STATE(34), 4,
      sym__object_value,
      sym_pair,
      sym_spread,
      aux_sym_object_repeat1,
  [938] = 9,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(175), 1,
      aux_sym_path_seg_token1,
    ACTIONS(177), 1,
      anon_sym_SQUOTE,
    ACTIONS(179), 1,
      anon_sym_DOT_DOT,
    ACTIONS(185), 1,
      anon_sym_RBRACE,
    STATE(50), 1,
      aux_sym_path_seg_repeat1,
    STATE(75), 1,
      sym_path_seg,
    STATE(90), 1,
      sym_path,
    STATE(32), 4,
      sym__object_value,
      sym_pair,
      sym_spread,
      aux_sym_object_repeat1,
  [969] = 9,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(187), 1,
      anon_sym_RBRACE,
    ACTIONS(189), 1,
      aux_sym_path_seg_token1,
    ACTIONS(192), 1,
      anon_sym_SQUOTE,
    ACTIONS(195), 1,
      anon_sym_DOT_DOT,
    STATE(50), 1,
      aux_sym_path_seg_repeat1,
    STATE(75), 1,
      sym_path_seg,
    STATE(90), 1,
      sym_path,
    STATE(34), 4,
      sym__object_value,
      sym_pair,
      sym_spread,
      aux_sym_object_repeat1,
  [1000] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(86), 1,
      aux_sym_path_seg_token1,
    ACTIONS(198), 1,
      anon_sym_DOT,
    ACTIONS(200), 1,
      aux_sym__decimal_integer_token1,
    STATE(38), 1,
      aux_sym__decimal_integer_repeat1,
    ACTIONS(82), 3,
      anon_sym_RBRACE,
      anon_sym_SQUOTE,
      anon_sym_DOT_DOT,
  [1021] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(104), 1,
      aux_sym_path_seg_token1,
    ACTIONS(202), 1,
      anon_sym_DOT,
    ACTIONS(204), 1,
      aux_sym__decimal_integer_token1,
    STATE(41), 1,
      aux_sym__decimal_integer_repeat1,
    ACTIONS(100), 3,
      anon_sym_RBRACE,
      anon_sym_SQUOTE,
      anon_sym_DOT_DOT,
  [1042] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(98), 1,
      aux_sym_path_seg_token1,
    ACTIONS(206), 1,
      anon_sym_e,
    STATE(54), 1,
      sym__exponent,
    ACTIONS(96), 3,
      anon_sym_RBRACE,
      anon_sym_SQUOTE,
      anon_sym_DOT_DOT,
  [1060] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(104), 1,
      aux_sym_path_seg_token1,
    ACTIONS(208), 1,
      aux_sym__decimal_integer_token1,
    STATE(39), 1,
      aux_sym__decimal_integer_repeat1,
    ACTIONS(100), 3,
      anon_sym_RBRACE,
      anon_sym_SQUOTE,
      anon_sym_DOT_DOT,
  [1078] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(124), 1,
      aux_sym_path_seg_token1,
    ACTIONS(210), 1,
      aux_sym__decimal_integer_token1,
    STATE(39), 1,
      aux_sym__decimal_integer_repeat1,
    ACTIONS(122), 3,
      anon_sym_RBRACE,
      anon_sym_SQUOTE,
      anon_sym_DOT_DOT,
  [1096] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(92), 1,
      aux_sym_path_seg_token1,
    ACTIONS(206), 1,
      anon_sym_e,
    STATE(53), 1,
      sym__exponent,
    ACTIONS(90), 3,
      anon_sym_RBRACE,
      anon_sym_SQUOTE,
      anon_sym_DOT_DOT,
  [1114] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(114), 1,
      aux_sym_path_seg_token1,
    ACTIONS(208), 1,
      aux_sym__decimal_integer_token1,
    STATE(39), 1,
      aux_sym__decimal_integer_repeat1,
    ACTIONS(112), 3,
      anon_sym_RBRACE,
      anon_sym_SQUOTE,
      anon_sym_DOT_DOT,
  [1132] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(213), 1,
      anon_sym_DOT,
    ACTIONS(215), 1,
      aux_sym__decimal_integer_token1,
    STATE(63), 1,
      aux_sym__decimal_integer_repeat1,
    ACTIONS(82), 2,
      anon_sym_RBRACE,
      sym_input,
  [1149] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(217), 1,
      anon_sym_DOT,
    ACTIONS(219), 1,
      aux_sym__decimal_integer_token1,
    STATE(65), 1,
      aux_sym__decimal_integer_repeat1,
    ACTIONS(100), 2,
      anon_sym_RBRACE,
      sym_input,
  [1166] = 4,
    ACTIONS(224), 1,
      anon_sym_DQUOTE,
    ACTIONS(226), 1,
      sym_comment,
    STATE(44), 1,
      aux_sym_string_repeat1,
    ACTIONS(221), 2,
      sym_input,
      sym_char,
  [1180] = 4,
    ACTIONS(226), 1,
      sym_comment,
    ACTIONS(230), 1,
      anon_sym_DQUOTE,
    STATE(44), 1,
      aux_sym_string_repeat1,
    ACTIONS(228), 2,
      sym_input,
      sym_char,
  [1194] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(151), 1,
      aux_sym_path_seg_token1,
    ACTIONS(149), 3,
      anon_sym_RBRACE,
      anon_sym_SQUOTE,
      anon_sym_DOT_DOT,
  [1206] = 4,
    ACTIONS(226), 1,
      sym_comment,
    ACTIONS(232), 1,
      anon_sym_DQUOTE,
    STATE(44), 1,
      aux_sym_string_repeat1,
    ACTIONS(228), 2,
      sym_input,
      sym_char,
  [1220] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(131), 1,
      aux_sym_path_seg_token1,
    ACTIONS(129), 3,
      anon_sym_RBRACE,
      anon_sym_SQUOTE,
      anon_sym_DOT_DOT,
  [1232] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(155), 1,
      aux_sym_path_seg_token1,
    ACTIONS(153), 3,
      anon_sym_RBRACE,
      anon_sym_SQUOTE,
      anon_sym_DOT_DOT,
  [1244] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(236), 1,
      aux_sym_path_seg_token1,
    STATE(62), 1,
      aux_sym_path_seg_repeat1,
    ACTIONS(234), 2,
      anon_sym_EQ,
      anon_sym_DOT,
  [1258] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(159), 1,
      aux_sym_path_seg_token1,
    ACTIONS(157), 3,
      anon_sym_RBRACE,
      anon_sym_SQUOTE,
      anon_sym_DOT_DOT,
  [1270] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(238), 1,
      anon_sym_RBRACE,
    ACTIONS(240), 1,
      sym_input,
    STATE(64), 2,
      sym_assignment,
      aux_sym_assign_block_repeat1,
  [1284] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(98), 1,
      aux_sym_path_seg_token1,
    ACTIONS(96), 3,
      anon_sym_RBRACE,
      anon_sym_SQUOTE,
      anon_sym_DOT_DOT,
  [1296] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(163), 1,
      aux_sym_path_seg_token1,
    ACTIONS(161), 3,
      anon_sym_RBRACE,
      anon_sym_SQUOTE,
      anon_sym_DOT_DOT,
  [1308] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(167), 1,
      aux_sym_path_seg_token1,
    ACTIONS(165), 3,
      anon_sym_RBRACE,
      anon_sym_SQUOTE,
      anon_sym_DOT_DOT,
  [1320] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(120), 1,
      aux_sym_path_seg_token1,
    ACTIONS(118), 3,
      anon_sym_RBRACE,
      anon_sym_SQUOTE,
      anon_sym_DOT_DOT,
  [1332] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(171), 1,
      aux_sym_path_seg_token1,
    ACTIONS(169), 3,
      anon_sym_RBRACE,
      anon_sym_SQUOTE,
      anon_sym_DOT_DOT,
  [1344] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(110), 1,
      aux_sym_path_seg_token1,
    ACTIONS(108), 3,
      anon_sym_RBRACE,
      anon_sym_SQUOTE,
      anon_sym_DOT_DOT,
  [1356] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(175), 1,
      aux_sym_path_seg_token1,
    ACTIONS(177), 1,
      anon_sym_SQUOTE,
    STATE(50), 1,
      aux_sym_path_seg_repeat1,
    STATE(81), 1,
      sym_path_seg,
  [1372] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(147), 1,
      aux_sym_path_seg_token1,
    ACTIONS(145), 3,
      anon_sym_RBRACE,
      anon_sym_SQUOTE,
      anon_sym_DOT_DOT,
  [1384] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(240), 1,
      sym_input,
    ACTIONS(242), 1,
      anon_sym_RBRACE,
    STATE(52), 2,
      sym_assignment,
      aux_sym_assign_block_repeat1,
  [1398] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(246), 1,
      aux_sym_path_seg_token1,
    STATE(62), 1,
      aux_sym_path_seg_repeat1,
    ACTIONS(244), 2,
      anon_sym_EQ,
      anon_sym_DOT,
  [1412] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(249), 1,
      aux_sym__decimal_integer_token1,
    STATE(66), 1,
      aux_sym__decimal_integer_repeat1,
    ACTIONS(100), 2,
      anon_sym_RBRACE,
      sym_input,
  [1426] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(251), 1,
      anon_sym_RBRACE,
    ACTIONS(253), 1,
      sym_input,
    STATE(64), 2,
      sym_assignment,
      aux_sym_assign_block_repeat1,
  [1440] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(249), 1,
      aux_sym__decimal_integer_token1,
    STATE(66), 1,
      aux_sym__decimal_integer_repeat1,
    ACTIONS(112), 2,
      anon_sym_RBRACE,
      sym_input,
  [1454] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(256), 1,
      aux_sym__decimal_integer_token1,
    STATE(66), 1,
      aux_sym__decimal_integer_repeat1,
    ACTIONS(122), 2,
      anon_sym_RBRACE,
      sym_input,
  [1468] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(135), 1,
      aux_sym_path_seg_token1,
    ACTIONS(133), 3,
      anon_sym_RBRACE,
      anon_sym_SQUOTE,
      anon_sym_DOT_DOT,
  [1480] = 4,
    ACTIONS(226), 1,
      sym_comment,
    ACTIONS(261), 1,
      anon_sym_DQUOTE,
    STATE(47), 1,
      aux_sym_string_repeat1,
    ACTIONS(259), 2,
      sym_input,
      sym_char,
  [1494] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(139), 1,
      aux_sym_path_seg_token1,
    ACTIONS(137), 3,
      anon_sym_RBRACE,
      anon_sym_SQUOTE,
      anon_sym_DOT_DOT,
  [1506] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(265), 1,
      aux_sym_path_seg_token1,
    ACTIONS(263), 3,
      anon_sym_RBRACE,
      anon_sym_SQUOTE,
      anon_sym_DOT_DOT,
  [1518] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(143), 1,
      aux_sym_path_seg_token1,
    ACTIONS(141), 3,
      anon_sym_RBRACE,
      anon_sym_SQUOTE,
      anon_sym_DOT_DOT,
  [1530] = 4,
    ACTIONS(226), 1,
      sym_comment,
    ACTIONS(269), 1,
      anon_sym_DQUOTE,
    STATE(45), 1,
      aux_sym_string_repeat1,
    ACTIONS(267), 2,
      sym_input,
      sym_char,
  [1544] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(271), 1,
      anon_sym_EQ,
    ACTIONS(273), 1,
      anon_sym_DOT,
    STATE(74), 1,
      aux_sym_path_repeat1,
  [1557] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(275), 1,
      anon_sym_EQ,
    ACTIONS(277), 1,
      anon_sym_DOT,
    STATE(74), 1,
      aux_sym_path_repeat1,
  [1570] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(273), 1,
      anon_sym_DOT,
    ACTIONS(280), 1,
      anon_sym_EQ,
    STATE(73), 1,
      aux_sym_path_repeat1,
  [1583] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(244), 1,
      anon_sym_SQUOTE,
    ACTIONS(282), 1,
      aux_sym_path_seg_token1,
    STATE(76), 1,
      aux_sym_path_seg_repeat1,
  [1596] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(285), 1,
      aux_sym_path_seg_token1,
    ACTIONS(287), 1,
      anon_sym_SQUOTE,
    STATE(76), 1,
      aux_sym_path_seg_repeat1,
  [1609] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(289), 1,
      aux_sym_path_seg_token1,
    STATE(77), 1,
      aux_sym_path_seg_repeat1,
  [1619] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(291), 2,
      anon_sym_EQ,
      anon_sym_DOT,
  [1627] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(7), 1,
      anon_sym_LBRACE,
    STATE(96), 1,
      sym_object,
  [1637] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(275), 2,
      anon_sym_EQ,
      anon_sym_DOT,
  [1645] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(293), 2,
      anon_sym_DASH,
      anon_sym_PLUS,
  [1653] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(295), 2,
      anon_sym_RBRACE,
      sym_input,
  [1661] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(297), 2,
      anon_sym_DASH,
      anon_sym_PLUS,
  [1669] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(299), 1,
      aux_sym__hex_integer_token1,
  [1676] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(301), 1,
      ts_builtin_sym_end,
  [1683] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(303), 1,
      anon_sym_EQ,
  [1690] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(305), 1,
      aux_sym_float_token1,
  [1697] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(307), 1,
      sym_input,
  [1704] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(309), 1,
      anon_sym_EQ,
  [1711] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(311), 1,
      anon_sym_LBRACE,
  [1718] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(313), 1,
      anon_sym_in,
  [1725] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(315), 1,
      aux_sym_float_token1,
  [1732] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(317), 1,
      aux_sym_float_token1,
  [1739] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(319), 1,
      sym_input,
  [1746] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(321), 1,
      ts_builtin_sym_end,
  [1753] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(323), 1,
      anon_sym_LBRACE,
  [1760] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(325), 1,
      aux_sym_float_token1,
  [1767] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(327), 1,
      aux_sym_float_token1,
  [1774] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(329), 1,
      aux_sym__hex_integer_token1,
  [1781] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(331), 1,
      anon_sym_LBRACE,
  [1788] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(333), 1,
      ts_builtin_sym_end,
  [1795] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(335), 1,
      aux_sym_float_token1,
  [1802] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(337), 1,
      aux_sym_float_token1,
  [1809] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(339), 1,
      aux_sym_float_token1,
  [1816] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(341), 1,
      aux_sym_float_token1,
  [1823] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(343), 1,
      anon_sym_in,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 54,
  [SMALL_STATE(4)] = 108,
  [SMALL_STATE(5)] = 162,
  [SMALL_STATE(6)] = 216,
  [SMALL_STATE(7)] = 270,
  [SMALL_STATE(8)] = 315,
  [SMALL_STATE(9)] = 360,
  [SMALL_STATE(10)] = 389,
  [SMALL_STATE(11)] = 416,
  [SMALL_STATE(12)] = 443,
  [SMALL_STATE(13)] = 472,
  [SMALL_STATE(14)] = 494,
  [SMALL_STATE(15)] = 520,
  [SMALL_STATE(16)] = 542,
  [SMALL_STATE(17)] = 568,
  [SMALL_STATE(18)] = 594,
  [SMALL_STATE(19)] = 615,
  [SMALL_STATE(20)] = 636,
  [SMALL_STATE(21)] = 657,
  [SMALL_STATE(22)] = 678,
  [SMALL_STATE(23)] = 699,
  [SMALL_STATE(24)] = 720,
  [SMALL_STATE(25)] = 741,
  [SMALL_STATE(26)] = 762,
  [SMALL_STATE(27)] = 783,
  [SMALL_STATE(28)] = 804,
  [SMALL_STATE(29)] = 825,
  [SMALL_STATE(30)] = 845,
  [SMALL_STATE(31)] = 876,
  [SMALL_STATE(32)] = 907,
  [SMALL_STATE(33)] = 938,
  [SMALL_STATE(34)] = 969,
  [SMALL_STATE(35)] = 1000,
  [SMALL_STATE(36)] = 1021,
  [SMALL_STATE(37)] = 1042,
  [SMALL_STATE(38)] = 1060,
  [SMALL_STATE(39)] = 1078,
  [SMALL_STATE(40)] = 1096,
  [SMALL_STATE(41)] = 1114,
  [SMALL_STATE(42)] = 1132,
  [SMALL_STATE(43)] = 1149,
  [SMALL_STATE(44)] = 1166,
  [SMALL_STATE(45)] = 1180,
  [SMALL_STATE(46)] = 1194,
  [SMALL_STATE(47)] = 1206,
  [SMALL_STATE(48)] = 1220,
  [SMALL_STATE(49)] = 1232,
  [SMALL_STATE(50)] = 1244,
  [SMALL_STATE(51)] = 1258,
  [SMALL_STATE(52)] = 1270,
  [SMALL_STATE(53)] = 1284,
  [SMALL_STATE(54)] = 1296,
  [SMALL_STATE(55)] = 1308,
  [SMALL_STATE(56)] = 1320,
  [SMALL_STATE(57)] = 1332,
  [SMALL_STATE(58)] = 1344,
  [SMALL_STATE(59)] = 1356,
  [SMALL_STATE(60)] = 1372,
  [SMALL_STATE(61)] = 1384,
  [SMALL_STATE(62)] = 1398,
  [SMALL_STATE(63)] = 1412,
  [SMALL_STATE(64)] = 1426,
  [SMALL_STATE(65)] = 1440,
  [SMALL_STATE(66)] = 1454,
  [SMALL_STATE(67)] = 1468,
  [SMALL_STATE(68)] = 1480,
  [SMALL_STATE(69)] = 1494,
  [SMALL_STATE(70)] = 1506,
  [SMALL_STATE(71)] = 1518,
  [SMALL_STATE(72)] = 1530,
  [SMALL_STATE(73)] = 1544,
  [SMALL_STATE(74)] = 1557,
  [SMALL_STATE(75)] = 1570,
  [SMALL_STATE(76)] = 1583,
  [SMALL_STATE(77)] = 1596,
  [SMALL_STATE(78)] = 1609,
  [SMALL_STATE(79)] = 1619,
  [SMALL_STATE(80)] = 1627,
  [SMALL_STATE(81)] = 1637,
  [SMALL_STATE(82)] = 1645,
  [SMALL_STATE(83)] = 1653,
  [SMALL_STATE(84)] = 1661,
  [SMALL_STATE(85)] = 1669,
  [SMALL_STATE(86)] = 1676,
  [SMALL_STATE(87)] = 1683,
  [SMALL_STATE(88)] = 1690,
  [SMALL_STATE(89)] = 1697,
  [SMALL_STATE(90)] = 1704,
  [SMALL_STATE(91)] = 1711,
  [SMALL_STATE(92)] = 1718,
  [SMALL_STATE(93)] = 1725,
  [SMALL_STATE(94)] = 1732,
  [SMALL_STATE(95)] = 1739,
  [SMALL_STATE(96)] = 1746,
  [SMALL_STATE(97)] = 1753,
  [SMALL_STATE(98)] = 1760,
  [SMALL_STATE(99)] = 1767,
  [SMALL_STATE(100)] = 1774,
  [SMALL_STATE(101)] = 1781,
  [SMALL_STATE(102)] = 1788,
  [SMALL_STATE(103)] = 1795,
  [SMALL_STATE(104)] = 1802,
  [SMALL_STATE(105)] = 1809,
  [SMALL_STATE(106)] = 1816,
  [SMALL_STATE(107)] = 1823,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT_EXTRA(),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT(91),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(72),
  [17] = {.entry = {.count = 1, .reusable = true}}, SHIFT(106),
  [19] = {.entry = {.count = 1, .reusable = false}}, SHIFT(9),
  [21] = {.entry = {.count = 1, .reusable = true}}, SHIFT(100),
  [23] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [25] = {.entry = {.count = 1, .reusable = true}}, SHIFT(95),
  [27] = {.entry = {.count = 1, .reusable = true}}, SHIFT(60),
  [29] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_array_repeat1, 2, 0, 0), SHIFT_REPEAT(30),
  [32] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_array_repeat1, 2, 0, 0), SHIFT_REPEAT(19),
  [35] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_array_repeat1, 2, 0, 0), SHIFT_REPEAT(6),
  [38] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_array_repeat1, 2, 0, 0),
  [40] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_array_repeat1, 2, 0, 0), SHIFT_REPEAT(72),
  [43] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_array_repeat1, 2, 0, 0), SHIFT_REPEAT(106),
  [46] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_array_repeat1, 2, 0, 0), SHIFT_REPEAT(9),
  [49] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_array_repeat1, 2, 0, 0), SHIFT_REPEAT(100),
  [52] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_array_repeat1, 2, 0, 0), SHIFT_REPEAT(20),
  [55] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_array_repeat1, 2, 0, 0), SHIFT_REPEAT(95),
  [58] = {.entry = {.count = 1, .reusable = true}}, SHIFT(49),
  [60] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [62] = {.entry = {.count = 1, .reusable = true}}, SHIFT(99),
  [64] = {.entry = {.count = 1, .reusable = false}}, SHIFT(42),
  [66] = {.entry = {.count = 1, .reusable = true}}, SHIFT(33),
  [68] = {.entry = {.count = 1, .reusable = true}}, SHIFT(67),
  [70] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [72] = {.entry = {.count = 1, .reusable = true}}, SHIFT(68),
  [74] = {.entry = {.count = 1, .reusable = true}}, SHIFT(88),
  [76] = {.entry = {.count = 1, .reusable = false}}, SHIFT(35),
  [78] = {.entry = {.count = 1, .reusable = true}}, SHIFT(85),
  [80] = {.entry = {.count = 1, .reusable = true}}, SHIFT(69),
  [82] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__decimal_integer, 1, 0, 0),
  [84] = {.entry = {.count = 1, .reusable = false}}, SHIFT(103),
  [86] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__decimal_integer, 1, 0, 0),
  [88] = {.entry = {.count = 1, .reusable = false}}, SHIFT(16),
  [90] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_float, 3, 0, 0),
  [92] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_float, 3, 0, 0),
  [94] = {.entry = {.count = 1, .reusable = true}}, SHIFT(84),
  [96] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_float, 4, 0, 0),
  [98] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_float, 4, 0, 0),
  [100] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__decimal_integer, 2, 0, 0),
  [102] = {.entry = {.count = 1, .reusable = false}}, SHIFT(104),
  [104] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__decimal_integer, 2, 0, 0),
  [106] = {.entry = {.count = 1, .reusable = false}}, SHIFT(14),
  [108] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_object, 3, 0, 0),
  [110] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_object, 3, 0, 0),
  [112] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__decimal_integer, 3, 0, 0),
  [114] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__decimal_integer, 3, 0, 0),
  [116] = {.entry = {.count = 1, .reusable = false}}, SHIFT(17),
  [118] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_object, 2, 0, 0),
  [120] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_object, 2, 0, 0),
  [122] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym__decimal_integer_repeat1, 2, 0, 0),
  [124] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym__decimal_integer_repeat1, 2, 0, 0),
  [126] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym__decimal_integer_repeat1, 2, 0, 0), SHIFT_REPEAT(17),
  [129] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__hex_integer, 2, 0, 0),
  [131] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__hex_integer, 2, 0, 0),
  [133] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_value, 1, 0, 0),
  [135] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_value, 1, 0, 0),
  [137] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_boolean, 1, 0, 0),
  [139] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_boolean, 1, 0, 0),
  [141] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_integer, 1, 0, 0),
  [143] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_integer, 1, 0, 0),
  [145] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_array, 2, 0, 0),
  [147] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_array, 2, 0, 0),
  [149] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_string, 2, 0, 0),
  [151] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_string, 2, 0, 0),
  [153] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_array, 3, 0, 0),
  [155] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_array, 3, 0, 0),
  [157] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_string, 3, 0, 0),
  [159] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_string, 3, 0, 0),
  [161] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_float, 5, 0, 0),
  [163] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_float, 5, 0, 0),
  [165] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__exponent, 3, 0, 0),
  [167] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__exponent, 3, 0, 0),
  [169] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_spread, 2, 0, 0),
  [171] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_spread, 2, 0, 0),
  [173] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [175] = {.entry = {.count = 1, .reusable = false}}, SHIFT(50),
  [177] = {.entry = {.count = 1, .reusable = true}}, SHIFT(78),
  [179] = {.entry = {.count = 1, .reusable = true}}, SHIFT(89),
  [181] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [183] = {.entry = {.count = 1, .reusable = true}}, SHIFT(58),
  [185] = {.entry = {.count = 1, .reusable = true}}, SHIFT(56),
  [187] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_object_repeat1, 2, 0, 0),
  [189] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_object_repeat1, 2, 0, 0), SHIFT_REPEAT(50),
  [192] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_object_repeat1, 2, 0, 0), SHIFT_REPEAT(78),
  [195] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_object_repeat1, 2, 0, 0), SHIFT_REPEAT(89),
  [198] = {.entry = {.count = 1, .reusable = false}}, SHIFT(93),
  [200] = {.entry = {.count = 1, .reusable = false}}, SHIFT(38),
  [202] = {.entry = {.count = 1, .reusable = false}}, SHIFT(98),
  [204] = {.entry = {.count = 1, .reusable = false}}, SHIFT(41),
  [206] = {.entry = {.count = 1, .reusable = true}}, SHIFT(82),
  [208] = {.entry = {.count = 1, .reusable = false}}, SHIFT(39),
  [210] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym__decimal_integer_repeat1, 2, 0, 0), SHIFT_REPEAT(39),
  [213] = {.entry = {.count = 1, .reusable = true}}, SHIFT(103),
  [215] = {.entry = {.count = 1, .reusable = true}}, SHIFT(63),
  [217] = {.entry = {.count = 1, .reusable = true}}, SHIFT(104),
  [219] = {.entry = {.count = 1, .reusable = true}}, SHIFT(65),
  [221] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_string_repeat1, 2, 0, 0), SHIFT_REPEAT(44),
  [224] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_string_repeat1, 2, 0, 0),
  [226] = {.entry = {.count = 1, .reusable = false}}, SHIFT_EXTRA(),
  [228] = {.entry = {.count = 1, .reusable = false}}, SHIFT(44),
  [230] = {.entry = {.count = 1, .reusable = false}}, SHIFT(25),
  [232] = {.entry = {.count = 1, .reusable = false}}, SHIFT(51),
  [234] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_path_seg, 1, 0, 0),
  [236] = {.entry = {.count = 1, .reusable = false}}, SHIFT(62),
  [238] = {.entry = {.count = 1, .reusable = true}}, SHIFT(92),
  [240] = {.entry = {.count = 1, .reusable = true}}, SHIFT(87),
  [242] = {.entry = {.count = 1, .reusable = true}}, SHIFT(107),
  [244] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_path_seg_repeat1, 2, 0, 0),
  [246] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_path_seg_repeat1, 2, 0, 0), SHIFT_REPEAT(62),
  [249] = {.entry = {.count = 1, .reusable = true}}, SHIFT(66),
  [251] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_assign_block_repeat1, 2, 0, 0),
  [253] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_assign_block_repeat1, 2, 0, 0), SHIFT_REPEAT(87),
  [256] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__decimal_integer_repeat1, 2, 0, 0), SHIFT_REPEAT(66),
  [259] = {.entry = {.count = 1, .reusable = false}}, SHIFT(47),
  [261] = {.entry = {.count = 1, .reusable = false}}, SHIFT(46),
  [263] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_pair, 3, 0, 0),
  [265] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_pair, 3, 0, 0),
  [267] = {.entry = {.count = 1, .reusable = false}}, SHIFT(45),
  [269] = {.entry = {.count = 1, .reusable = false}}, SHIFT(23),
  [271] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_path, 2, 0, 0),
  [273] = {.entry = {.count = 1, .reusable = true}}, SHIFT(59),
  [275] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_path_repeat1, 2, 0, 0),
  [277] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_path_repeat1, 2, 0, 0), SHIFT_REPEAT(59),
  [280] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_path, 1, 0, 0),
  [282] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_path_seg_repeat1, 2, 0, 0), SHIFT_REPEAT(76),
  [285] = {.entry = {.count = 1, .reusable = false}}, SHIFT(76),
  [287] = {.entry = {.count = 1, .reusable = true}}, SHIFT(79),
  [289] = {.entry = {.count = 1, .reusable = false}}, SHIFT(77),
  [291] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_path_seg, 3, 0, 0),
  [293] = {.entry = {.count = 1, .reusable = true}}, SHIFT(94),
  [295] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_assignment, 3, 0, 0),
  [297] = {.entry = {.count = 1, .reusable = true}}, SHIFT(105),
  [299] = {.entry = {.count = 1, .reusable = true}}, SHIFT(48),
  [301] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [303] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [305] = {.entry = {.count = 1, .reusable = true}}, SHIFT(36),
  [307] = {.entry = {.count = 1, .reusable = true}}, SHIFT(57),
  [309] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [311] = {.entry = {.count = 1, .reusable = true}}, SHIFT(61),
  [313] = {.entry = {.count = 1, .reusable = true}}, SHIFT(101),
  [315] = {.entry = {.count = 1, .reusable = true}}, SHIFT(40),
  [317] = {.entry = {.count = 1, .reusable = true}}, SHIFT(55),
  [319] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [321] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 2, 0, 0),
  [323] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_assign_block, 4, 0, 0),
  [325] = {.entry = {.count = 1, .reusable = true}}, SHIFT(37),
  [327] = {.entry = {.count = 1, .reusable = true}}, SHIFT(43),
  [329] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [331] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_assign_block, 5, 0, 0),
  [333] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [335] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [337] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [339] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [341] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [343] = {.entry = {.count = 1, .reusable = true}}, SHIFT(97),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_corn(void) {
  static const TSLanguage language = {
    .version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
