#include "parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 14
#define STATE_COUNT 104
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 51
#define ALIAS_COUNT 0
#define TOKEN_COUNT 25
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 5
#define PRODUCTION_ID_COUNT 1

enum ts_symbol_identifiers {
  anon_sym_let = 1,
  anon_sym_LBRACE = 2,
  anon_sym_RBRACE = 3,
  anon_sym_in = 4,
  anon_sym_EQ = 5,
  sym_input = 6,
  anon_sym_LBRACK = 7,
  anon_sym_RBRACK = 8,
  anon_sym_DOT = 9,
  aux_sym_path_seg_token1 = 10,
  anon_sym_DQUOTE = 11,
  sym_char = 12,
  anon_sym_DASH = 13,
  aux_sym_float_token1 = 14,
  anon_sym_e = 15,
  anon_sym_PLUS = 16,
  aux_sym__decimal_integer_token1 = 17,
  anon_sym_0x = 18,
  aux_sym__hex_integer_token1 = 19,
  anon_sym_true = 20,
  anon_sym_false = 21,
  sym_null = 22,
  anon_sym_DOT_DOT = 23,
  sym_comment = 24,
  sym_source_file = 25,
  sym_assign_block = 26,
  sym_assignment = 27,
  sym_value = 28,
  sym_object = 29,
  sym__object_value = 30,
  sym_array = 31,
  sym__array_value = 32,
  sym_pair = 33,
  sym_path = 34,
  sym_path_seg = 35,
  sym_string = 36,
  sym_float = 37,
  sym__exponent = 38,
  sym_integer = 39,
  sym__decimal_integer = 40,
  sym__hex_integer = 41,
  sym_boolean = 42,
  sym_spread = 43,
  aux_sym_assign_block_repeat1 = 44,
  aux_sym_object_repeat1 = 45,
  aux_sym_array_repeat1 = 46,
  aux_sym_path_repeat1 = 47,
  aux_sym_path_seg_repeat1 = 48,
  aux_sym_string_repeat1 = 49,
  aux_sym__decimal_integer_repeat1 = 50,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_let] = "let",
  [anon_sym_LBRACE] = "{",
  [anon_sym_RBRACE] = "}",
  [anon_sym_in] = "in",
  [anon_sym_EQ] = "=",
  [sym_input] = "input",
  [anon_sym_LBRACK] = "[",
  [anon_sym_RBRACK] = "]",
  [anon_sym_DOT] = ".",
  [aux_sym_path_seg_token1] = "path_seg_token1",
  [anon_sym_DQUOTE] = "\"",
  [sym_char] = "char",
  [anon_sym_DASH] = "-",
  [aux_sym_float_token1] = "float_token1",
  [anon_sym_e] = "e",
  [anon_sym_PLUS] = "+",
  [aux_sym__decimal_integer_token1] = "_decimal_integer_token1",
  [anon_sym_0x] = "0x",
  [aux_sym__hex_integer_token1] = "_hex_integer_token1",
  [anon_sym_true] = "true",
  [anon_sym_false] = "false",
  [sym_null] = "null",
  [anon_sym_DOT_DOT] = "..",
  [sym_comment] = "comment",
  [sym_source_file] = "source_file",
  [sym_assign_block] = "assign_block",
  [sym_assignment] = "assignment",
  [sym_value] = "value",
  [sym_object] = "object",
  [sym__object_value] = "_object_value",
  [sym_array] = "array",
  [sym__array_value] = "_array_value",
  [sym_pair] = "pair",
  [sym_path] = "path",
  [sym_path_seg] = "path_seg",
  [sym_string] = "string",
  [sym_float] = "float",
  [sym__exponent] = "_exponent",
  [sym_integer] = "integer",
  [sym__decimal_integer] = "_decimal_integer",
  [sym__hex_integer] = "_hex_integer",
  [sym_boolean] = "boolean",
  [sym_spread] = "spread",
  [aux_sym_assign_block_repeat1] = "assign_block_repeat1",
  [aux_sym_object_repeat1] = "object_repeat1",
  [aux_sym_array_repeat1] = "array_repeat1",
  [aux_sym_path_repeat1] = "path_repeat1",
  [aux_sym_path_seg_repeat1] = "path_seg_repeat1",
  [aux_sym_string_repeat1] = "string_repeat1",
  [aux_sym__decimal_integer_repeat1] = "_decimal_integer_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_let] = anon_sym_let,
  [anon_sym_LBRACE] = anon_sym_LBRACE,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [anon_sym_in] = anon_sym_in,
  [anon_sym_EQ] = anon_sym_EQ,
  [sym_input] = sym_input,
  [anon_sym_LBRACK] = anon_sym_LBRACK,
  [anon_sym_RBRACK] = anon_sym_RBRACK,
  [anon_sym_DOT] = anon_sym_DOT,
  [aux_sym_path_seg_token1] = aux_sym_path_seg_token1,
  [anon_sym_DQUOTE] = anon_sym_DQUOTE,
  [sym_char] = sym_char,
  [anon_sym_DASH] = anon_sym_DASH,
  [aux_sym_float_token1] = aux_sym_float_token1,
  [anon_sym_e] = anon_sym_e,
  [anon_sym_PLUS] = anon_sym_PLUS,
  [aux_sym__decimal_integer_token1] = aux_sym__decimal_integer_token1,
  [anon_sym_0x] = anon_sym_0x,
  [aux_sym__hex_integer_token1] = aux_sym__hex_integer_token1,
  [anon_sym_true] = anon_sym_true,
  [anon_sym_false] = anon_sym_false,
  [sym_null] = sym_null,
  [anon_sym_DOT_DOT] = anon_sym_DOT_DOT,
  [sym_comment] = sym_comment,
  [sym_source_file] = sym_source_file,
  [sym_assign_block] = sym_assign_block,
  [sym_assignment] = sym_assignment,
  [sym_value] = sym_value,
  [sym_object] = sym_object,
  [sym__object_value] = sym__object_value,
  [sym_array] = sym_array,
  [sym__array_value] = sym__array_value,
  [sym_pair] = sym_pair,
  [sym_path] = sym_path,
  [sym_path_seg] = sym_path_seg,
  [sym_string] = sym_string,
  [sym_float] = sym_float,
  [sym__exponent] = sym__exponent,
  [sym_integer] = sym_integer,
  [sym__decimal_integer] = sym__decimal_integer,
  [sym__hex_integer] = sym__hex_integer,
  [sym_boolean] = sym_boolean,
  [sym_spread] = sym_spread,
  [aux_sym_assign_block_repeat1] = aux_sym_assign_block_repeat1,
  [aux_sym_object_repeat1] = aux_sym_object_repeat1,
  [aux_sym_array_repeat1] = aux_sym_array_repeat1,
  [aux_sym_path_repeat1] = aux_sym_path_repeat1,
  [aux_sym_path_seg_repeat1] = aux_sym_path_seg_repeat1,
  [aux_sym_string_repeat1] = aux_sym_string_repeat1,
  [aux_sym__decimal_integer_repeat1] = aux_sym__decimal_integer_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_let] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_in] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ] = {
    .visible = true,
    .named = false,
  },
  [sym_input] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_LBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DOT] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_path_seg_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_DQUOTE] = {
    .visible = true,
    .named = false,
  },
  [sym_char] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_DASH] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_float_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_e] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PLUS] = {
    .visible = true,
    .named = false,
  },
  [aux_sym__decimal_integer_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_0x] = {
    .visible = true,
    .named = false,
  },
  [aux_sym__hex_integer_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_true] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_false] = {
    .visible = true,
    .named = false,
  },
  [sym_null] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_DOT_DOT] = {
    .visible = true,
    .named = false,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym_assign_block] = {
    .visible = true,
    .named = true,
  },
  [sym_assignment] = {
    .visible = true,
    .named = true,
  },
  [sym_value] = {
    .visible = true,
    .named = true,
  },
  [sym_object] = {
    .visible = true,
    .named = true,
  },
  [sym__object_value] = {
    .visible = false,
    .named = true,
  },
  [sym_array] = {
    .visible = true,
    .named = true,
  },
  [sym__array_value] = {
    .visible = false,
    .named = true,
  },
  [sym_pair] = {
    .visible = true,
    .named = true,
  },
  [sym_path] = {
    .visible = true,
    .named = true,
  },
  [sym_path_seg] = {
    .visible = true,
    .named = true,
  },
  [sym_string] = {
    .visible = true,
    .named = true,
  },
  [sym_float] = {
    .visible = true,
    .named = true,
  },
  [sym__exponent] = {
    .visible = false,
    .named = true,
  },
  [sym_integer] = {
    .visible = true,
    .named = true,
  },
  [sym__decimal_integer] = {
    .visible = false,
    .named = true,
  },
  [sym__hex_integer] = {
    .visible = false,
    .named = true,
  },
  [sym_boolean] = {
    .visible = true,
    .named = true,
  },
  [sym_spread] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_assign_block_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_object_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_array_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_path_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_path_seg_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_string_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym__decimal_integer_repeat1] = {
    .visible = false,
    .named = false,
  },
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 2,
  [4] = 4,
  [5] = 5,
  [6] = 4,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 32,
  [34] = 31,
  [35] = 12,
  [36] = 9,
  [37] = 12,
  [38] = 11,
  [39] = 14,
  [40] = 9,
  [41] = 16,
  [42] = 15,
  [43] = 10,
  [44] = 44,
  [45] = 45,
  [46] = 46,
  [47] = 46,
  [48] = 45,
  [49] = 49,
  [50] = 50,
  [51] = 51,
  [52] = 16,
  [53] = 14,
  [54] = 54,
  [55] = 15,
  [56] = 56,
  [57] = 23,
  [58] = 21,
  [59] = 25,
  [60] = 60,
  [61] = 18,
  [62] = 26,
  [63] = 20,
  [64] = 19,
  [65] = 17,
  [66] = 66,
  [67] = 13,
  [68] = 27,
  [69] = 22,
  [70] = 70,
  [71] = 28,
  [72] = 24,
  [73] = 29,
  [74] = 74,
  [75] = 75,
  [76] = 76,
  [77] = 77,
  [78] = 78,
  [79] = 78,
  [80] = 80,
  [81] = 81,
  [82] = 82,
  [83] = 83,
  [84] = 84,
  [85] = 85,
  [86] = 86,
  [87] = 87,
  [88] = 88,
  [89] = 89,
  [90] = 90,
  [91] = 89,
  [92] = 92,
  [93] = 93,
  [94] = 94,
  [95] = 94,
  [96] = 96,
  [97] = 97,
  [98] = 98,
  [99] = 98,
  [100] = 82,
  [101] = 87,
  [102] = 94,
  [103] = 96,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(28);
      if (lookahead == '"') ADVANCE(42);
      if (lookahead == '+') ADVANCE(51);
      if (lookahead == '-') ADVANCE(47);
      if (lookahead == '.') ADVANCE(38);
      if (lookahead == '/') ADVANCE(40);
      if (lookahead == '=') ADVANCE(33);
      if (lookahead == '[') ADVANCE(35);
      if (lookahead == ']') ADVANCE(36);
      if (lookahead == '_') ADVANCE(41);
      if (lookahead == 'e') ADVANCE(50);
      if (lookahead == '{') ADVANCE(30);
      if (lookahead == '}') ADVANCE(31);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0)
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(41);
      if (lookahead != 0) ADVANCE(39);
      END_STATE();
    case 1:
      if (lookahead == '"') ADVANCE(42);
      if (lookahead == '$') ADVANCE(46);
      if (lookahead == '/') ADVANCE(45);
      if (lookahead == '\n' ||
          lookahead == '\r') SKIP(1)
      if (('\t' <= lookahead && lookahead <= '\f') ||
          lookahead == ' ') ADVANCE(44);
      if (lookahead != 0) ADVANCE(43);
      END_STATE();
    case 2:
      if (lookahead == '$') ADVANCE(25);
      if (lookahead == '.') ADVANCE(37);
      if (lookahead == '/') ADVANCE(8);
      if (lookahead == '_') ADVANCE(24);
      if (lookahead == '}') ADVANCE(31);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(2)
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(52);
      END_STATE();
    case 3:
      if (lookahead == '.') ADVANCE(38);
      if (lookahead == '/') ADVANCE(40);
      if (lookahead == '_') ADVANCE(41);
      if (lookahead == '}') ADVANCE(31);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(3)
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(41);
      if (lookahead != 0 &&
          lookahead != '=') ADVANCE(39);
      END_STATE();
    case 4:
      if (lookahead == '.') ADVANCE(58);
      END_STATE();
    case 5:
      if (lookahead == '.') ADVANCE(4);
      if (lookahead == '/') ADVANCE(40);
      if (lookahead == 'e') ADVANCE(50);
      if (lookahead == '}') ADVANCE(31);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(5)
      if (lookahead != 0 &&
          lookahead != '=') ADVANCE(39);
      END_STATE();
    case 6:
      if (lookahead == '.') ADVANCE(4);
      if (lookahead == '/') ADVANCE(40);
      if (lookahead == '}') ADVANCE(31);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(6)
      if (lookahead != 0 &&
          lookahead != '=') ADVANCE(39);
      END_STATE();
    case 7:
      if (lookahead == '.') ADVANCE(37);
      if (lookahead == '/') ADVANCE(40);
      if (lookahead == '=') ADVANCE(33);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(7)
      if (lookahead != 0) ADVANCE(39);
      END_STATE();
    case 8:
      if (lookahead == '/') ADVANCE(59);
      END_STATE();
    case 9:
      if (lookahead == '/') ADVANCE(8);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(9)
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(49);
      END_STATE();
    case 10:
      if (lookahead == '/') ADVANCE(8);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(10)
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(54);
      END_STATE();
    case 11:
      if (lookahead == 'a') ADVANCE(15);
      END_STATE();
    case 12:
      if (lookahead == 'e') ADVANCE(21);
      END_STATE();
    case 13:
      if (lookahead == 'e') ADVANCE(55);
      END_STATE();
    case 14:
      if (lookahead == 'e') ADVANCE(56);
      END_STATE();
    case 15:
      if (lookahead == 'l') ADVANCE(20);
      END_STATE();
    case 16:
      if (lookahead == 'l') ADVANCE(57);
      END_STATE();
    case 17:
      if (lookahead == 'l') ADVANCE(16);
      END_STATE();
    case 18:
      if (lookahead == 'n') ADVANCE(32);
      END_STATE();
    case 19:
      if (lookahead == 'r') ADVANCE(22);
      END_STATE();
    case 20:
      if (lookahead == 's') ADVANCE(14);
      END_STATE();
    case 21:
      if (lookahead == 't') ADVANCE(29);
      END_STATE();
    case 22:
      if (lookahead == 'u') ADVANCE(13);
      END_STATE();
    case 23:
      if (lookahead == 'u') ADVANCE(17);
      END_STATE();
    case 24:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(52);
      END_STATE();
    case 25:
      if (('A' <= lookahead && lookahead <= 'z')) ADVANCE(26);
      END_STATE();
    case 26:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'z')) ADVANCE(34);
      END_STATE();
    case 27:
      if (eof) ADVANCE(28);
      if (lookahead == '"') ADVANCE(42);
      if (lookahead == '$') ADVANCE(25);
      if (lookahead == '+') ADVANCE(51);
      if (lookahead == '-') ADVANCE(47);
      if (lookahead == '.') ADVANCE(38);
      if (lookahead == '/') ADVANCE(8);
      if (lookahead == '0') ADVANCE(48);
      if (lookahead == '[') ADVANCE(35);
      if (lookahead == ']') ADVANCE(36);
      if (lookahead == '_') ADVANCE(24);
      if (lookahead == 'e') ADVANCE(50);
      if (lookahead == 'f') ADVANCE(11);
      if (lookahead == 'i') ADVANCE(18);
      if (lookahead == 'l') ADVANCE(12);
      if (lookahead == 'n') ADVANCE(23);
      if (lookahead == 't') ADVANCE(19);
      if (lookahead == '{') ADVANCE(30);
      if (lookahead == '}') ADVANCE(31);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(27)
      if (('1' <= lookahead && lookahead <= '9')) ADVANCE(49);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(anon_sym_let);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(anon_sym_in);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(anon_sym_EQ);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(sym_input);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'z')) ADVANCE(34);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(anon_sym_LBRACK);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(anon_sym_RBRACK);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(anon_sym_DOT);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(anon_sym_DOT);
      if (lookahead == '.') ADVANCE(58);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(aux_sym_path_seg_token1);
      END_STATE();
    case 40:
      ACCEPT_TOKEN(aux_sym_path_seg_token1);
      if (lookahead == '/') ADVANCE(59);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(aux_sym_path_seg_token1);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(52);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(anon_sym_DQUOTE);
      END_STATE();
    case 43:
      ACCEPT_TOKEN(sym_char);
      END_STATE();
    case 44:
      ACCEPT_TOKEN(sym_char);
      if (lookahead == '$') ADVANCE(46);
      if (lookahead == '/') ADVANCE(45);
      if (lookahead == '\t' ||
          lookahead == 11 ||
          lookahead == '\f' ||
          lookahead == ' ') ADVANCE(44);
      if (lookahead != 0 &&
          (lookahead < '\n' || '\r' < lookahead) &&
          lookahead != '"') ADVANCE(43);
      END_STATE();
    case 45:
      ACCEPT_TOKEN(sym_char);
      if (lookahead == '/') ADVANCE(59);
      END_STATE();
    case 46:
      ACCEPT_TOKEN(sym_char);
      if (('A' <= lookahead && lookahead <= 'z')) ADVANCE(26);
      END_STATE();
    case 47:
      ACCEPT_TOKEN(anon_sym_DASH);
      END_STATE();
    case 48:
      ACCEPT_TOKEN(aux_sym_float_token1);
      if (lookahead == 'x') ADVANCE(53);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(49);
      END_STATE();
    case 49:
      ACCEPT_TOKEN(aux_sym_float_token1);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(49);
      END_STATE();
    case 50:
      ACCEPT_TOKEN(anon_sym_e);
      END_STATE();
    case 51:
      ACCEPT_TOKEN(anon_sym_PLUS);
      END_STATE();
    case 52:
      ACCEPT_TOKEN(aux_sym__decimal_integer_token1);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(52);
      END_STATE();
    case 53:
      ACCEPT_TOKEN(anon_sym_0x);
      END_STATE();
    case 54:
      ACCEPT_TOKEN(aux_sym__hex_integer_token1);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(54);
      END_STATE();
    case 55:
      ACCEPT_TOKEN(anon_sym_true);
      END_STATE();
    case 56:
      ACCEPT_TOKEN(anon_sym_false);
      END_STATE();
    case 57:
      ACCEPT_TOKEN(sym_null);
      END_STATE();
    case 58:
      ACCEPT_TOKEN(anon_sym_DOT_DOT);
      END_STATE();
    case 59:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(59);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 27},
  [2] = {.lex_state = 27},
  [3] = {.lex_state = 27},
  [4] = {.lex_state = 27},
  [5] = {.lex_state = 27},
  [6] = {.lex_state = 27},
  [7] = {.lex_state = 27},
  [8] = {.lex_state = 27},
  [9] = {.lex_state = 27},
  [10] = {.lex_state = 27},
  [11] = {.lex_state = 27},
  [12] = {.lex_state = 27},
  [13] = {.lex_state = 27},
  [14] = {.lex_state = 27},
  [15] = {.lex_state = 27},
  [16] = {.lex_state = 27},
  [17] = {.lex_state = 27},
  [18] = {.lex_state = 27},
  [19] = {.lex_state = 27},
  [20] = {.lex_state = 27},
  [21] = {.lex_state = 27},
  [22] = {.lex_state = 27},
  [23] = {.lex_state = 27},
  [24] = {.lex_state = 27},
  [25] = {.lex_state = 27},
  [26] = {.lex_state = 27},
  [27] = {.lex_state = 27},
  [28] = {.lex_state = 27},
  [29] = {.lex_state = 27},
  [30] = {.lex_state = 6},
  [31] = {.lex_state = 6},
  [32] = {.lex_state = 6},
  [33] = {.lex_state = 6},
  [34] = {.lex_state = 6},
  [35] = {.lex_state = 3},
  [36] = {.lex_state = 3},
  [37] = {.lex_state = 2},
  [38] = {.lex_state = 5},
  [39] = {.lex_state = 3},
  [40] = {.lex_state = 2},
  [41] = {.lex_state = 3},
  [42] = {.lex_state = 3},
  [43] = {.lex_state = 5},
  [44] = {.lex_state = 1},
  [45] = {.lex_state = 1},
  [46] = {.lex_state = 1},
  [47] = {.lex_state = 1},
  [48] = {.lex_state = 1},
  [49] = {.lex_state = 27},
  [50] = {.lex_state = 7},
  [51] = {.lex_state = 27},
  [52] = {.lex_state = 2},
  [53] = {.lex_state = 2},
  [54] = {.lex_state = 7},
  [55] = {.lex_state = 2},
  [56] = {.lex_state = 27},
  [57] = {.lex_state = 6},
  [58] = {.lex_state = 6},
  [59] = {.lex_state = 6},
  [60] = {.lex_state = 7},
  [61] = {.lex_state = 6},
  [62] = {.lex_state = 6},
  [63] = {.lex_state = 6},
  [64] = {.lex_state = 6},
  [65] = {.lex_state = 6},
  [66] = {.lex_state = 6},
  [67] = {.lex_state = 6},
  [68] = {.lex_state = 6},
  [69] = {.lex_state = 6},
  [70] = {.lex_state = 0},
  [71] = {.lex_state = 6},
  [72] = {.lex_state = 6},
  [73] = {.lex_state = 6},
  [74] = {.lex_state = 0},
  [75] = {.lex_state = 0},
  [76] = {.lex_state = 27},
  [77] = {.lex_state = 27},
  [78] = {.lex_state = 27},
  [79] = {.lex_state = 27},
  [80] = {.lex_state = 0},
  [81] = {.lex_state = 27},
  [82] = {.lex_state = 9},
  [83] = {.lex_state = 0},
  [84] = {.lex_state = 27},
  [85] = {.lex_state = 0},
  [86] = {.lex_state = 27},
  [87] = {.lex_state = 9},
  [88] = {.lex_state = 0},
  [89] = {.lex_state = 27},
  [90] = {.lex_state = 27},
  [91] = {.lex_state = 27},
  [92] = {.lex_state = 0},
  [93] = {.lex_state = 27},
  [94] = {.lex_state = 9},
  [95] = {.lex_state = 9},
  [96] = {.lex_state = 10},
  [97] = {.lex_state = 0},
  [98] = {.lex_state = 9},
  [99] = {.lex_state = 9},
  [100] = {.lex_state = 9},
  [101] = {.lex_state = 9},
  [102] = {.lex_state = 9},
  [103] = {.lex_state = 10},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [0] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_LBRACE] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [anon_sym_EQ] = ACTIONS(1),
    [anon_sym_LBRACK] = ACTIONS(1),
    [anon_sym_RBRACK] = ACTIONS(1),
    [anon_sym_DOT] = ACTIONS(1),
    [aux_sym_path_seg_token1] = ACTIONS(1),
    [anon_sym_DQUOTE] = ACTIONS(1),
    [anon_sym_DASH] = ACTIONS(1),
    [anon_sym_e] = ACTIONS(1),
    [anon_sym_PLUS] = ACTIONS(1),
    [aux_sym__decimal_integer_token1] = ACTIONS(1),
    [anon_sym_DOT_DOT] = ACTIONS(1),
    [sym_comment] = ACTIONS(3),
  },
  [1] = {
    [sym_source_file] = STATE(97),
    [sym_assign_block] = STATE(77),
    [sym_object] = STATE(92),
    [anon_sym_let] = ACTIONS(5),
    [anon_sym_LBRACE] = ACTIONS(7),
    [sym_comment] = ACTIONS(3),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 14,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(7), 1,
      anon_sym_LBRACE,
    ACTIONS(11), 1,
      anon_sym_LBRACK,
    ACTIONS(13), 1,
      anon_sym_RBRACK,
    ACTIONS(15), 1,
      anon_sym_DQUOTE,
    ACTIONS(17), 1,
      anon_sym_DASH,
    ACTIONS(19), 1,
      aux_sym_float_token1,
    ACTIONS(21), 1,
      anon_sym_0x,
    ACTIONS(25), 1,
      anon_sym_DOT_DOT,
    ACTIONS(9), 2,
      sym_input,
      sym_null,
    ACTIONS(23), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(25), 2,
      sym__decimal_integer,
      sym__hex_integer,
    STATE(5), 4,
      sym_value,
      sym__array_value,
      sym_spread,
      aux_sym_array_repeat1,
    STATE(28), 6,
      sym_object,
      sym_array,
      sym_string,
      sym_float,
      sym_integer,
      sym_boolean,
  [54] = 14,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(7), 1,
      anon_sym_LBRACE,
    ACTIONS(11), 1,
      anon_sym_LBRACK,
    ACTIONS(15), 1,
      anon_sym_DQUOTE,
    ACTIONS(17), 1,
      anon_sym_DASH,
    ACTIONS(19), 1,
      aux_sym_float_token1,
    ACTIONS(21), 1,
      anon_sym_0x,
    ACTIONS(25), 1,
      anon_sym_DOT_DOT,
    ACTIONS(27), 1,
      anon_sym_RBRACK,
    ACTIONS(9), 2,
      sym_input,
      sym_null,
    ACTIONS(23), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(25), 2,
      sym__decimal_integer,
      sym__hex_integer,
    STATE(5), 4,
      sym_value,
      sym__array_value,
      sym_spread,
      aux_sym_array_repeat1,
    STATE(28), 6,
      sym_object,
      sym_array,
      sym_string,
      sym_float,
      sym_integer,
      sym_boolean,
  [108] = 14,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(7), 1,
      anon_sym_LBRACE,
    ACTIONS(11), 1,
      anon_sym_LBRACK,
    ACTIONS(15), 1,
      anon_sym_DQUOTE,
    ACTIONS(17), 1,
      anon_sym_DASH,
    ACTIONS(19), 1,
      aux_sym_float_token1,
    ACTIONS(21), 1,
      anon_sym_0x,
    ACTIONS(25), 1,
      anon_sym_DOT_DOT,
    ACTIONS(29), 1,
      anon_sym_RBRACK,
    ACTIONS(9), 2,
      sym_input,
      sym_null,
    ACTIONS(23), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(25), 2,
      sym__decimal_integer,
      sym__hex_integer,
    STATE(2), 4,
      sym_value,
      sym__array_value,
      sym_spread,
      aux_sym_array_repeat1,
    STATE(28), 6,
      sym_object,
      sym_array,
      sym_string,
      sym_float,
      sym_integer,
      sym_boolean,
  [162] = 14,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(31), 1,
      anon_sym_LBRACE,
    ACTIONS(37), 1,
      anon_sym_LBRACK,
    ACTIONS(40), 1,
      anon_sym_RBRACK,
    ACTIONS(42), 1,
      anon_sym_DQUOTE,
    ACTIONS(45), 1,
      anon_sym_DASH,
    ACTIONS(48), 1,
      aux_sym_float_token1,
    ACTIONS(51), 1,
      anon_sym_0x,
    ACTIONS(57), 1,
      anon_sym_DOT_DOT,
    ACTIONS(34), 2,
      sym_input,
      sym_null,
    ACTIONS(54), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(25), 2,
      sym__decimal_integer,
      sym__hex_integer,
    STATE(5), 4,
      sym_value,
      sym__array_value,
      sym_spread,
      aux_sym_array_repeat1,
    STATE(28), 6,
      sym_object,
      sym_array,
      sym_string,
      sym_float,
      sym_integer,
      sym_boolean,
  [216] = 14,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(7), 1,
      anon_sym_LBRACE,
    ACTIONS(11), 1,
      anon_sym_LBRACK,
    ACTIONS(15), 1,
      anon_sym_DQUOTE,
    ACTIONS(17), 1,
      anon_sym_DASH,
    ACTIONS(19), 1,
      aux_sym_float_token1,
    ACTIONS(21), 1,
      anon_sym_0x,
    ACTIONS(25), 1,
      anon_sym_DOT_DOT,
    ACTIONS(60), 1,
      anon_sym_RBRACK,
    ACTIONS(9), 2,
      sym_input,
      sym_null,
    ACTIONS(23), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(25), 2,
      sym__decimal_integer,
      sym__hex_integer,
    STATE(3), 4,
      sym_value,
      sym__array_value,
      sym_spread,
      aux_sym_array_repeat1,
    STATE(28), 6,
      sym_object,
      sym_array,
      sym_string,
      sym_float,
      sym_integer,
      sym_boolean,
  [270] = 12,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(7), 1,
      anon_sym_LBRACE,
    ACTIONS(11), 1,
      anon_sym_LBRACK,
    ACTIONS(15), 1,
      anon_sym_DQUOTE,
    ACTIONS(21), 1,
      anon_sym_0x,
    ACTIONS(62), 1,
      anon_sym_DASH,
    ACTIONS(64), 1,
      aux_sym_float_token1,
    STATE(76), 1,
      sym_value,
    ACTIONS(9), 2,
      sym_input,
      sym_null,
    ACTIONS(23), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(25), 2,
      sym__decimal_integer,
      sym__hex_integer,
    STATE(28), 6,
      sym_object,
      sym_array,
      sym_string,
      sym_float,
      sym_integer,
      sym_boolean,
  [315] = 12,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(66), 1,
      anon_sym_LBRACE,
    ACTIONS(70), 1,
      anon_sym_LBRACK,
    ACTIONS(72), 1,
      anon_sym_DQUOTE,
    ACTIONS(74), 1,
      anon_sym_DASH,
    ACTIONS(76), 1,
      aux_sym_float_token1,
    ACTIONS(78), 1,
      anon_sym_0x,
    STATE(66), 1,
      sym_value,
    ACTIONS(68), 2,
      sym_input,
      sym_null,
    ACTIONS(80), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(59), 2,
      sym__decimal_integer,
      sym__hex_integer,
    STATE(71), 6,
      sym_object,
      sym_array,
      sym_string,
      sym_float,
      sym_integer,
      sym_boolean,
  [360] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(84), 1,
      anon_sym_DOT,
    ACTIONS(86), 1,
      aux_sym_float_token1,
    ACTIONS(88), 1,
      aux_sym__decimal_integer_token1,
    STATE(15), 1,
      aux_sym__decimal_integer_repeat1,
    ACTIONS(82), 11,
      anon_sym_LBRACE,
      sym_input,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_DQUOTE,
      anon_sym_DASH,
      anon_sym_0x,
      anon_sym_true,
      anon_sym_false,
      sym_null,
      anon_sym_DOT_DOT,
  [389] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(92), 1,
      aux_sym_float_token1,
    ACTIONS(94), 1,
      anon_sym_e,
    STATE(26), 1,
      sym__exponent,
    ACTIONS(90), 12,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      sym_input,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_DQUOTE,
      anon_sym_DASH,
      anon_sym_0x,
      anon_sym_true,
      anon_sym_false,
      sym_null,
      anon_sym_DOT_DOT,
  [416] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(94), 1,
      anon_sym_e,
    ACTIONS(98), 1,
      aux_sym_float_token1,
    STATE(23), 1,
      sym__exponent,
    ACTIONS(96), 12,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      sym_input,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_DQUOTE,
      anon_sym_DASH,
      anon_sym_0x,
      anon_sym_true,
      anon_sym_false,
      sym_null,
      anon_sym_DOT_DOT,
  [443] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(102), 1,
      anon_sym_DOT,
    ACTIONS(104), 1,
      aux_sym_float_token1,
    ACTIONS(106), 1,
      aux_sym__decimal_integer_token1,
    STATE(14), 1,
      aux_sym__decimal_integer_repeat1,
    ACTIONS(100), 11,
      anon_sym_LBRACE,
      sym_input,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_DQUOTE,
      anon_sym_DASH,
      anon_sym_0x,
      anon_sym_true,
      anon_sym_false,
      sym_null,
      anon_sym_DOT_DOT,
  [472] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(110), 1,
      aux_sym_float_token1,
    ACTIONS(108), 13,
      ts_builtin_sym_end,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      sym_input,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_DQUOTE,
      anon_sym_DASH,
      anon_sym_0x,
      anon_sym_true,
      anon_sym_false,
      sym_null,
      anon_sym_DOT_DOT,
  [494] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(114), 1,
      aux_sym_float_token1,
    ACTIONS(116), 1,
      aux_sym__decimal_integer_token1,
    STATE(16), 1,
      aux_sym__decimal_integer_repeat1,
    ACTIONS(112), 11,
      anon_sym_LBRACE,
      sym_input,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_DQUOTE,
      anon_sym_DASH,
      anon_sym_0x,
      anon_sym_true,
      anon_sym_false,
      sym_null,
      anon_sym_DOT_DOT,
  [520] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(104), 1,
      aux_sym_float_token1,
    ACTIONS(116), 1,
      aux_sym__decimal_integer_token1,
    STATE(16), 1,
      aux_sym__decimal_integer_repeat1,
    ACTIONS(100), 11,
      anon_sym_LBRACE,
      sym_input,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_DQUOTE,
      anon_sym_DASH,
      anon_sym_0x,
      anon_sym_true,
      anon_sym_false,
      sym_null,
      anon_sym_DOT_DOT,
  [546] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(120), 1,
      aux_sym_float_token1,
    ACTIONS(122), 1,
      aux_sym__decimal_integer_token1,
    STATE(16), 1,
      aux_sym__decimal_integer_repeat1,
    ACTIONS(118), 11,
      anon_sym_LBRACE,
      sym_input,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_DQUOTE,
      anon_sym_DASH,
      anon_sym_0x,
      anon_sym_true,
      anon_sym_false,
      sym_null,
      anon_sym_DOT_DOT,
  [572] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(127), 1,
      aux_sym_float_token1,
    ACTIONS(125), 13,
      ts_builtin_sym_end,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      sym_input,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_DQUOTE,
      anon_sym_DASH,
      anon_sym_0x,
      anon_sym_true,
      anon_sym_false,
      sym_null,
      anon_sym_DOT_DOT,
  [594] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(131), 1,
      aux_sym_float_token1,
    ACTIONS(129), 12,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      sym_input,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_DQUOTE,
      anon_sym_DASH,
      anon_sym_0x,
      anon_sym_true,
      anon_sym_false,
      sym_null,
      anon_sym_DOT_DOT,
  [615] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(135), 1,
      aux_sym_float_token1,
    ACTIONS(133), 12,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      sym_input,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_DQUOTE,
      anon_sym_DASH,
      anon_sym_0x,
      anon_sym_true,
      anon_sym_false,
      sym_null,
      anon_sym_DOT_DOT,
  [636] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(139), 1,
      aux_sym_float_token1,
    ACTIONS(137), 12,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      sym_input,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_DQUOTE,
      anon_sym_DASH,
      anon_sym_0x,
      anon_sym_true,
      anon_sym_false,
      sym_null,
      anon_sym_DOT_DOT,
  [657] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(143), 1,
      aux_sym_float_token1,
    ACTIONS(141), 12,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      sym_input,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_DQUOTE,
      anon_sym_DASH,
      anon_sym_0x,
      anon_sym_true,
      anon_sym_false,
      sym_null,
      anon_sym_DOT_DOT,
  [678] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(147), 1,
      aux_sym_float_token1,
    ACTIONS(145), 12,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      sym_input,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_DQUOTE,
      anon_sym_DASH,
      anon_sym_0x,
      anon_sym_true,
      anon_sym_false,
      sym_null,
      anon_sym_DOT_DOT,
  [699] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(92), 1,
      aux_sym_float_token1,
    ACTIONS(90), 12,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      sym_input,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_DQUOTE,
      anon_sym_DASH,
      anon_sym_0x,
      anon_sym_true,
      anon_sym_false,
      sym_null,
      anon_sym_DOT_DOT,
  [720] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(151), 1,
      aux_sym_float_token1,
    ACTIONS(149), 12,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      sym_input,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_DQUOTE,
      anon_sym_DASH,
      anon_sym_0x,
      anon_sym_true,
      anon_sym_false,
      sym_null,
      anon_sym_DOT_DOT,
  [741] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(155), 1,
      aux_sym_float_token1,
    ACTIONS(153), 12,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      sym_input,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_DQUOTE,
      anon_sym_DASH,
      anon_sym_0x,
      anon_sym_true,
      anon_sym_false,
      sym_null,
      anon_sym_DOT_DOT,
  [762] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(159), 1,
      aux_sym_float_token1,
    ACTIONS(157), 12,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      sym_input,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_DQUOTE,
      anon_sym_DASH,
      anon_sym_0x,
      anon_sym_true,
      anon_sym_false,
      sym_null,
      anon_sym_DOT_DOT,
  [783] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(163), 1,
      aux_sym_float_token1,
    ACTIONS(161), 12,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      sym_input,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_DQUOTE,
      anon_sym_DASH,
      anon_sym_0x,
      anon_sym_true,
      anon_sym_false,
      sym_null,
      anon_sym_DOT_DOT,
  [804] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(167), 1,
      aux_sym_float_token1,
    ACTIONS(165), 12,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      sym_input,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_DQUOTE,
      anon_sym_DASH,
      anon_sym_0x,
      anon_sym_true,
      anon_sym_false,
      sym_null,
      anon_sym_DOT_DOT,
  [825] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(171), 1,
      aux_sym_float_token1,
    ACTIONS(169), 11,
      anon_sym_LBRACE,
      sym_input,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_DQUOTE,
      anon_sym_DASH,
      anon_sym_0x,
      anon_sym_true,
      anon_sym_false,
      sym_null,
      anon_sym_DOT_DOT,
  [845] = 8,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(173), 1,
      anon_sym_RBRACE,
    ACTIONS(175), 1,
      aux_sym_path_seg_token1,
    ACTIONS(178), 1,
      anon_sym_DOT_DOT,
    STATE(50), 1,
      aux_sym_path_seg_repeat1,
    STATE(75), 1,
      sym_path_seg,
    STATE(88), 1,
      sym_path,
    STATE(30), 4,
      sym__object_value,
      sym_pair,
      sym_spread,
      aux_sym_object_repeat1,
  [873] = 8,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(181), 1,
      anon_sym_RBRACE,
    ACTIONS(183), 1,
      aux_sym_path_seg_token1,
    ACTIONS(185), 1,
      anon_sym_DOT_DOT,
    STATE(50), 1,
      aux_sym_path_seg_repeat1,
    STATE(75), 1,
      sym_path_seg,
    STATE(88), 1,
      sym_path,
    STATE(32), 4,
      sym__object_value,
      sym_pair,
      sym_spread,
      aux_sym_object_repeat1,
  [901] = 8,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(183), 1,
      aux_sym_path_seg_token1,
    ACTIONS(185), 1,
      anon_sym_DOT_DOT,
    ACTIONS(187), 1,
      anon_sym_RBRACE,
    STATE(50), 1,
      aux_sym_path_seg_repeat1,
    STATE(75), 1,
      sym_path_seg,
    STATE(88), 1,
      sym_path,
    STATE(30), 4,
      sym__object_value,
      sym_pair,
      sym_spread,
      aux_sym_object_repeat1,
  [929] = 8,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(183), 1,
      aux_sym_path_seg_token1,
    ACTIONS(185), 1,
      anon_sym_DOT_DOT,
    ACTIONS(189), 1,
      anon_sym_RBRACE,
    STATE(50), 1,
      aux_sym_path_seg_repeat1,
    STATE(75), 1,
      sym_path_seg,
    STATE(88), 1,
      sym_path,
    STATE(30), 4,
      sym__object_value,
      sym_pair,
      sym_spread,
      aux_sym_object_repeat1,
  [957] = 8,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(183), 1,
      aux_sym_path_seg_token1,
    ACTIONS(185), 1,
      anon_sym_DOT_DOT,
    ACTIONS(191), 1,
      anon_sym_RBRACE,
    STATE(50), 1,
      aux_sym_path_seg_repeat1,
    STATE(75), 1,
      sym_path_seg,
    STATE(88), 1,
      sym_path,
    STATE(33), 4,
      sym__object_value,
      sym_pair,
      sym_spread,
      aux_sym_object_repeat1,
  [985] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(104), 1,
      aux_sym_path_seg_token1,
    ACTIONS(193), 1,
      anon_sym_DOT,
    ACTIONS(195), 1,
      aux_sym__decimal_integer_token1,
    STATE(39), 1,
      aux_sym__decimal_integer_repeat1,
    ACTIONS(100), 2,
      anon_sym_RBRACE,
      anon_sym_DOT_DOT,
  [1005] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(86), 1,
      aux_sym_path_seg_token1,
    ACTIONS(197), 1,
      anon_sym_DOT,
    ACTIONS(199), 1,
      aux_sym__decimal_integer_token1,
    STATE(42), 1,
      aux_sym__decimal_integer_repeat1,
    ACTIONS(82), 2,
      anon_sym_RBRACE,
      anon_sym_DOT_DOT,
  [1025] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(201), 1,
      anon_sym_DOT,
    ACTIONS(203), 1,
      aux_sym__decimal_integer_token1,
    STATE(53), 1,
      aux_sym__decimal_integer_repeat1,
    ACTIONS(100), 2,
      anon_sym_RBRACE,
      sym_input,
  [1042] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(98), 1,
      aux_sym_path_seg_token1,
    ACTIONS(205), 1,
      anon_sym_e,
    STATE(57), 1,
      sym__exponent,
    ACTIONS(96), 2,
      anon_sym_RBRACE,
      anon_sym_DOT_DOT,
  [1059] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(114), 1,
      aux_sym_path_seg_token1,
    ACTIONS(207), 1,
      aux_sym__decimal_integer_token1,
    STATE(41), 1,
      aux_sym__decimal_integer_repeat1,
    ACTIONS(112), 2,
      anon_sym_RBRACE,
      anon_sym_DOT_DOT,
  [1076] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(209), 1,
      anon_sym_DOT,
    ACTIONS(211), 1,
      aux_sym__decimal_integer_token1,
    STATE(55), 1,
      aux_sym__decimal_integer_repeat1,
    ACTIONS(82), 2,
      anon_sym_RBRACE,
      sym_input,
  [1093] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(120), 1,
      aux_sym_path_seg_token1,
    ACTIONS(213), 1,
      aux_sym__decimal_integer_token1,
    STATE(41), 1,
      aux_sym__decimal_integer_repeat1,
    ACTIONS(118), 2,
      anon_sym_RBRACE,
      anon_sym_DOT_DOT,
  [1110] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(104), 1,
      aux_sym_path_seg_token1,
    ACTIONS(207), 1,
      aux_sym__decimal_integer_token1,
    STATE(41), 1,
      aux_sym__decimal_integer_repeat1,
    ACTIONS(100), 2,
      anon_sym_RBRACE,
      anon_sym_DOT_DOT,
  [1127] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(92), 1,
      aux_sym_path_seg_token1,
    ACTIONS(205), 1,
      anon_sym_e,
    STATE(62), 1,
      sym__exponent,
    ACTIONS(90), 2,
      anon_sym_RBRACE,
      anon_sym_DOT_DOT,
  [1144] = 4,
    ACTIONS(219), 1,
      anon_sym_DQUOTE,
    ACTIONS(221), 1,
      sym_comment,
    STATE(44), 1,
      aux_sym_string_repeat1,
    ACTIONS(216), 2,
      sym_input,
      sym_char,
  [1158] = 4,
    ACTIONS(221), 1,
      sym_comment,
    ACTIONS(225), 1,
      anon_sym_DQUOTE,
    STATE(47), 1,
      aux_sym_string_repeat1,
    ACTIONS(223), 2,
      sym_input,
      sym_char,
  [1172] = 4,
    ACTIONS(221), 1,
      sym_comment,
    ACTIONS(229), 1,
      anon_sym_DQUOTE,
    STATE(44), 1,
      aux_sym_string_repeat1,
    ACTIONS(227), 2,
      sym_input,
      sym_char,
  [1186] = 4,
    ACTIONS(221), 1,
      sym_comment,
    ACTIONS(231), 1,
      anon_sym_DQUOTE,
    STATE(44), 1,
      aux_sym_string_repeat1,
    ACTIONS(227), 2,
      sym_input,
      sym_char,
  [1200] = 4,
    ACTIONS(221), 1,
      sym_comment,
    ACTIONS(235), 1,
      anon_sym_DQUOTE,
    STATE(46), 1,
      aux_sym_string_repeat1,
    ACTIONS(233), 2,
      sym_input,
      sym_char,
  [1214] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(237), 1,
      anon_sym_RBRACE,
    ACTIONS(239), 1,
      sym_input,
    STATE(51), 2,
      sym_assignment,
      aux_sym_assign_block_repeat1,
  [1228] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(243), 1,
      aux_sym_path_seg_token1,
    STATE(54), 1,
      aux_sym_path_seg_repeat1,
    ACTIONS(241), 2,
      anon_sym_EQ,
      anon_sym_DOT,
  [1242] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(239), 1,
      sym_input,
    ACTIONS(245), 1,
      anon_sym_RBRACE,
    STATE(56), 2,
      sym_assignment,
      aux_sym_assign_block_repeat1,
  [1256] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(247), 1,
      aux_sym__decimal_integer_token1,
    STATE(52), 1,
      aux_sym__decimal_integer_repeat1,
    ACTIONS(118), 2,
      anon_sym_RBRACE,
      sym_input,
  [1270] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(250), 1,
      aux_sym__decimal_integer_token1,
    STATE(52), 1,
      aux_sym__decimal_integer_repeat1,
    ACTIONS(112), 2,
      anon_sym_RBRACE,
      sym_input,
  [1284] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(254), 1,
      aux_sym_path_seg_token1,
    STATE(54), 1,
      aux_sym_path_seg_repeat1,
    ACTIONS(252), 2,
      anon_sym_EQ,
      anon_sym_DOT,
  [1298] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(250), 1,
      aux_sym__decimal_integer_token1,
    STATE(52), 1,
      aux_sym__decimal_integer_repeat1,
    ACTIONS(100), 2,
      anon_sym_RBRACE,
      sym_input,
  [1312] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(257), 1,
      anon_sym_RBRACE,
    ACTIONS(259), 1,
      sym_input,
    STATE(56), 2,
      sym_assignment,
      aux_sym_assign_block_repeat1,
  [1326] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(92), 1,
      aux_sym_path_seg_token1,
    ACTIONS(90), 2,
      anon_sym_RBRACE,
      anon_sym_DOT_DOT,
  [1337] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(143), 1,
      aux_sym_path_seg_token1,
    ACTIONS(141), 2,
      anon_sym_RBRACE,
      anon_sym_DOT_DOT,
  [1348] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(155), 1,
      aux_sym_path_seg_token1,
    ACTIONS(153), 2,
      anon_sym_RBRACE,
      anon_sym_DOT_DOT,
  [1359] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(183), 1,
      aux_sym_path_seg_token1,
    STATE(50), 1,
      aux_sym_path_seg_repeat1,
    STATE(80), 1,
      sym_path_seg,
  [1372] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(131), 1,
      aux_sym_path_seg_token1,
    ACTIONS(129), 2,
      anon_sym_RBRACE,
      anon_sym_DOT_DOT,
  [1383] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(159), 1,
      aux_sym_path_seg_token1,
    ACTIONS(157), 2,
      anon_sym_RBRACE,
      anon_sym_DOT_DOT,
  [1394] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(139), 1,
      aux_sym_path_seg_token1,
    ACTIONS(137), 2,
      anon_sym_RBRACE,
      anon_sym_DOT_DOT,
  [1405] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(135), 1,
      aux_sym_path_seg_token1,
    ACTIONS(133), 2,
      anon_sym_RBRACE,
      anon_sym_DOT_DOT,
  [1416] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(127), 1,
      aux_sym_path_seg_token1,
    ACTIONS(125), 2,
      anon_sym_RBRACE,
      anon_sym_DOT_DOT,
  [1427] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(264), 1,
      aux_sym_path_seg_token1,
    ACTIONS(262), 2,
      anon_sym_RBRACE,
      anon_sym_DOT_DOT,
  [1438] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(110), 1,
      aux_sym_path_seg_token1,
    ACTIONS(108), 2,
      anon_sym_RBRACE,
      anon_sym_DOT_DOT,
  [1449] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(163), 1,
      aux_sym_path_seg_token1,
    ACTIONS(161), 2,
      anon_sym_RBRACE,
      anon_sym_DOT_DOT,
  [1460] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(147), 1,
      aux_sym_path_seg_token1,
    ACTIONS(145), 2,
      anon_sym_RBRACE,
      anon_sym_DOT_DOT,
  [1471] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(266), 1,
      anon_sym_EQ,
    ACTIONS(268), 1,
      anon_sym_DOT,
    STATE(74), 1,
      aux_sym_path_repeat1,
  [1484] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(167), 1,
      aux_sym_path_seg_token1,
    ACTIONS(165), 2,
      anon_sym_RBRACE,
      anon_sym_DOT_DOT,
  [1495] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(151), 1,
      aux_sym_path_seg_token1,
    ACTIONS(149), 2,
      anon_sym_RBRACE,
      anon_sym_DOT_DOT,
  [1506] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(171), 1,
      aux_sym_path_seg_token1,
    ACTIONS(169), 2,
      anon_sym_RBRACE,
      anon_sym_DOT_DOT,
  [1517] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(270), 1,
      anon_sym_EQ,
    ACTIONS(272), 1,
      anon_sym_DOT,
    STATE(74), 1,
      aux_sym_path_repeat1,
  [1530] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(268), 1,
      anon_sym_DOT,
    ACTIONS(275), 1,
      anon_sym_EQ,
    STATE(70), 1,
      aux_sym_path_repeat1,
  [1543] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(277), 2,
      anon_sym_RBRACE,
      sym_input,
  [1551] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(7), 1,
      anon_sym_LBRACE,
    STATE(85), 1,
      sym_object,
  [1561] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(279), 2,
      anon_sym_DASH,
      anon_sym_PLUS,
  [1569] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(281), 2,
      anon_sym_DASH,
      anon_sym_PLUS,
  [1577] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(270), 2,
      anon_sym_EQ,
      anon_sym_DOT,
  [1585] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(283), 1,
      anon_sym_LBRACE,
  [1592] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(285), 1,
      aux_sym_float_token1,
  [1599] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(287), 1,
      anon_sym_EQ,
  [1606] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(289), 1,
      anon_sym_in,
  [1613] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(291), 1,
      ts_builtin_sym_end,
  [1620] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(293), 1,
      anon_sym_LBRACE,
  [1627] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(295), 1,
      aux_sym_float_token1,
  [1634] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(297), 1,
      anon_sym_EQ,
  [1641] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(299), 1,
      sym_input,
  [1648] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(301), 1,
      anon_sym_LBRACE,
  [1655] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(303), 1,
      sym_input,
  [1662] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(305), 1,
      ts_builtin_sym_end,
  [1669] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(307), 1,
      anon_sym_in,
  [1676] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(309), 1,
      aux_sym_float_token1,
  [1683] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(311), 1,
      aux_sym_float_token1,
  [1690] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(313), 1,
      aux_sym__hex_integer_token1,
  [1697] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(315), 1,
      ts_builtin_sym_end,
  [1704] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(317), 1,
      aux_sym_float_token1,
  [1711] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(319), 1,
      aux_sym_float_token1,
  [1718] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(321), 1,
      aux_sym_float_token1,
  [1725] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(323), 1,
      aux_sym_float_token1,
  [1732] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(325), 1,
      aux_sym_float_token1,
  [1739] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(327), 1,
      aux_sym__hex_integer_token1,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 54,
  [SMALL_STATE(4)] = 108,
  [SMALL_STATE(5)] = 162,
  [SMALL_STATE(6)] = 216,
  [SMALL_STATE(7)] = 270,
  [SMALL_STATE(8)] = 315,
  [SMALL_STATE(9)] = 360,
  [SMALL_STATE(10)] = 389,
  [SMALL_STATE(11)] = 416,
  [SMALL_STATE(12)] = 443,
  [SMALL_STATE(13)] = 472,
  [SMALL_STATE(14)] = 494,
  [SMALL_STATE(15)] = 520,
  [SMALL_STATE(16)] = 546,
  [SMALL_STATE(17)] = 572,
  [SMALL_STATE(18)] = 594,
  [SMALL_STATE(19)] = 615,
  [SMALL_STATE(20)] = 636,
  [SMALL_STATE(21)] = 657,
  [SMALL_STATE(22)] = 678,
  [SMALL_STATE(23)] = 699,
  [SMALL_STATE(24)] = 720,
  [SMALL_STATE(25)] = 741,
  [SMALL_STATE(26)] = 762,
  [SMALL_STATE(27)] = 783,
  [SMALL_STATE(28)] = 804,
  [SMALL_STATE(29)] = 825,
  [SMALL_STATE(30)] = 845,
  [SMALL_STATE(31)] = 873,
  [SMALL_STATE(32)] = 901,
  [SMALL_STATE(33)] = 929,
  [SMALL_STATE(34)] = 957,
  [SMALL_STATE(35)] = 985,
  [SMALL_STATE(36)] = 1005,
  [SMALL_STATE(37)] = 1025,
  [SMALL_STATE(38)] = 1042,
  [SMALL_STATE(39)] = 1059,
  [SMALL_STATE(40)] = 1076,
  [SMALL_STATE(41)] = 1093,
  [SMALL_STATE(42)] = 1110,
  [SMALL_STATE(43)] = 1127,
  [SMALL_STATE(44)] = 1144,
  [SMALL_STATE(45)] = 1158,
  [SMALL_STATE(46)] = 1172,
  [SMALL_STATE(47)] = 1186,
  [SMALL_STATE(48)] = 1200,
  [SMALL_STATE(49)] = 1214,
  [SMALL_STATE(50)] = 1228,
  [SMALL_STATE(51)] = 1242,
  [SMALL_STATE(52)] = 1256,
  [SMALL_STATE(53)] = 1270,
  [SMALL_STATE(54)] = 1284,
  [SMALL_STATE(55)] = 1298,
  [SMALL_STATE(56)] = 1312,
  [SMALL_STATE(57)] = 1326,
  [SMALL_STATE(58)] = 1337,
  [SMALL_STATE(59)] = 1348,
  [SMALL_STATE(60)] = 1359,
  [SMALL_STATE(61)] = 1372,
  [SMALL_STATE(62)] = 1383,
  [SMALL_STATE(63)] = 1394,
  [SMALL_STATE(64)] = 1405,
  [SMALL_STATE(65)] = 1416,
  [SMALL_STATE(66)] = 1427,
  [SMALL_STATE(67)] = 1438,
  [SMALL_STATE(68)] = 1449,
  [SMALL_STATE(69)] = 1460,
  [SMALL_STATE(70)] = 1471,
  [SMALL_STATE(71)] = 1484,
  [SMALL_STATE(72)] = 1495,
  [SMALL_STATE(73)] = 1506,
  [SMALL_STATE(74)] = 1517,
  [SMALL_STATE(75)] = 1530,
  [SMALL_STATE(76)] = 1543,
  [SMALL_STATE(77)] = 1551,
  [SMALL_STATE(78)] = 1561,
  [SMALL_STATE(79)] = 1569,
  [SMALL_STATE(80)] = 1577,
  [SMALL_STATE(81)] = 1585,
  [SMALL_STATE(82)] = 1592,
  [SMALL_STATE(83)] = 1599,
  [SMALL_STATE(84)] = 1606,
  [SMALL_STATE(85)] = 1613,
  [SMALL_STATE(86)] = 1620,
  [SMALL_STATE(87)] = 1627,
  [SMALL_STATE(88)] = 1634,
  [SMALL_STATE(89)] = 1641,
  [SMALL_STATE(90)] = 1648,
  [SMALL_STATE(91)] = 1655,
  [SMALL_STATE(92)] = 1662,
  [SMALL_STATE(93)] = 1669,
  [SMALL_STATE(94)] = 1676,
  [SMALL_STATE(95)] = 1683,
  [SMALL_STATE(96)] = 1690,
  [SMALL_STATE(97)] = 1697,
  [SMALL_STATE(98)] = 1704,
  [SMALL_STATE(99)] = 1711,
  [SMALL_STATE(100)] = 1718,
  [SMALL_STATE(101)] = 1725,
  [SMALL_STATE(102)] = 1732,
  [SMALL_STATE(103)] = 1739,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT_EXTRA(),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT(86),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(48),
  [17] = {.entry = {.count = 1, .reusable = true}}, SHIFT(102),
  [19] = {.entry = {.count = 1, .reusable = false}}, SHIFT(9),
  [21] = {.entry = {.count = 1, .reusable = true}}, SHIFT(96),
  [23] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [25] = {.entry = {.count = 1, .reusable = true}}, SHIFT(91),
  [27] = {.entry = {.count = 1, .reusable = true}}, SHIFT(58),
  [29] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [31] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_array_repeat1, 2), SHIFT_REPEAT(31),
  [34] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_array_repeat1, 2), SHIFT_REPEAT(28),
  [37] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_array_repeat1, 2), SHIFT_REPEAT(4),
  [40] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_array_repeat1, 2),
  [42] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_array_repeat1, 2), SHIFT_REPEAT(48),
  [45] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_array_repeat1, 2), SHIFT_REPEAT(102),
  [48] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_array_repeat1, 2), SHIFT_REPEAT(9),
  [51] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_array_repeat1, 2), SHIFT_REPEAT(96),
  [54] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_array_repeat1, 2), SHIFT_REPEAT(27),
  [57] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_array_repeat1, 2), SHIFT_REPEAT(91),
  [60] = {.entry = {.count = 1, .reusable = true}}, SHIFT(61),
  [62] = {.entry = {.count = 1, .reusable = true}}, SHIFT(95),
  [64] = {.entry = {.count = 1, .reusable = false}}, SHIFT(40),
  [66] = {.entry = {.count = 1, .reusable = true}}, SHIFT(34),
  [68] = {.entry = {.count = 1, .reusable = true}}, SHIFT(71),
  [70] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [72] = {.entry = {.count = 1, .reusable = true}}, SHIFT(45),
  [74] = {.entry = {.count = 1, .reusable = true}}, SHIFT(94),
  [76] = {.entry = {.count = 1, .reusable = false}}, SHIFT(36),
  [78] = {.entry = {.count = 1, .reusable = true}}, SHIFT(103),
  [80] = {.entry = {.count = 1, .reusable = true}}, SHIFT(68),
  [82] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__decimal_integer, 1),
  [84] = {.entry = {.count = 1, .reusable = false}}, SHIFT(99),
  [86] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__decimal_integer, 1),
  [88] = {.entry = {.count = 1, .reusable = false}}, SHIFT(15),
  [90] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_float, 4),
  [92] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_float, 4),
  [94] = {.entry = {.count = 1, .reusable = true}}, SHIFT(78),
  [96] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_float, 3),
  [98] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_float, 3),
  [100] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__decimal_integer, 2),
  [102] = {.entry = {.count = 1, .reusable = false}}, SHIFT(100),
  [104] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__decimal_integer, 2),
  [106] = {.entry = {.count = 1, .reusable = false}}, SHIFT(14),
  [108] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_object, 3),
  [110] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_object, 3),
  [112] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__decimal_integer, 3),
  [114] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__decimal_integer, 3),
  [116] = {.entry = {.count = 1, .reusable = false}}, SHIFT(16),
  [118] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym__decimal_integer_repeat1, 2),
  [120] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym__decimal_integer_repeat1, 2),
  [122] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym__decimal_integer_repeat1, 2), SHIFT_REPEAT(16),
  [125] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_object, 2),
  [127] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_object, 2),
  [129] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_array, 2),
  [131] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_array, 2),
  [133] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__exponent, 3),
  [135] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__exponent, 3),
  [137] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_string, 3),
  [139] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_string, 3),
  [141] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_array, 3),
  [143] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_array, 3),
  [145] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__hex_integer, 2),
  [147] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__hex_integer, 2),
  [149] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_string, 2),
  [151] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_string, 2),
  [153] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_integer, 1),
  [155] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_integer, 1),
  [157] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_float, 5),
  [159] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_float, 5),
  [161] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_boolean, 1),
  [163] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_boolean, 1),
  [165] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_value, 1),
  [167] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_value, 1),
  [169] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_spread, 2),
  [171] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_spread, 2),
  [173] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_object_repeat1, 2),
  [175] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_object_repeat1, 2), SHIFT_REPEAT(50),
  [178] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_object_repeat1, 2), SHIFT_REPEAT(89),
  [181] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [183] = {.entry = {.count = 1, .reusable = false}}, SHIFT(50),
  [185] = {.entry = {.count = 1, .reusable = true}}, SHIFT(89),
  [187] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [189] = {.entry = {.count = 1, .reusable = true}}, SHIFT(67),
  [191] = {.entry = {.count = 1, .reusable = true}}, SHIFT(65),
  [193] = {.entry = {.count = 1, .reusable = false}}, SHIFT(82),
  [195] = {.entry = {.count = 1, .reusable = false}}, SHIFT(39),
  [197] = {.entry = {.count = 1, .reusable = false}}, SHIFT(98),
  [199] = {.entry = {.count = 1, .reusable = false}}, SHIFT(42),
  [201] = {.entry = {.count = 1, .reusable = true}}, SHIFT(100),
  [203] = {.entry = {.count = 1, .reusable = true}}, SHIFT(53),
  [205] = {.entry = {.count = 1, .reusable = true}}, SHIFT(79),
  [207] = {.entry = {.count = 1, .reusable = false}}, SHIFT(41),
  [209] = {.entry = {.count = 1, .reusable = true}}, SHIFT(99),
  [211] = {.entry = {.count = 1, .reusable = true}}, SHIFT(55),
  [213] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym__decimal_integer_repeat1, 2), SHIFT_REPEAT(41),
  [216] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_string_repeat1, 2), SHIFT_REPEAT(44),
  [219] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_string_repeat1, 2),
  [221] = {.entry = {.count = 1, .reusable = false}}, SHIFT_EXTRA(),
  [223] = {.entry = {.count = 1, .reusable = false}}, SHIFT(47),
  [225] = {.entry = {.count = 1, .reusable = false}}, SHIFT(72),
  [227] = {.entry = {.count = 1, .reusable = false}}, SHIFT(44),
  [229] = {.entry = {.count = 1, .reusable = false}}, SHIFT(20),
  [231] = {.entry = {.count = 1, .reusable = false}}, SHIFT(63),
  [233] = {.entry = {.count = 1, .reusable = false}}, SHIFT(46),
  [235] = {.entry = {.count = 1, .reusable = false}}, SHIFT(24),
  [237] = {.entry = {.count = 1, .reusable = true}}, SHIFT(84),
  [239] = {.entry = {.count = 1, .reusable = true}}, SHIFT(83),
  [241] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_path_seg, 1),
  [243] = {.entry = {.count = 1, .reusable = false}}, SHIFT(54),
  [245] = {.entry = {.count = 1, .reusable = true}}, SHIFT(93),
  [247] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__decimal_integer_repeat1, 2), SHIFT_REPEAT(52),
  [250] = {.entry = {.count = 1, .reusable = true}}, SHIFT(52),
  [252] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_path_seg_repeat1, 2),
  [254] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_path_seg_repeat1, 2), SHIFT_REPEAT(54),
  [257] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_assign_block_repeat1, 2),
  [259] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_assign_block_repeat1, 2), SHIFT_REPEAT(83),
  [262] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_pair, 3),
  [264] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_pair, 3),
  [266] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_path, 2),
  [268] = {.entry = {.count = 1, .reusable = true}}, SHIFT(60),
  [270] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_path_repeat1, 2),
  [272] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_path_repeat1, 2), SHIFT_REPEAT(60),
  [275] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_path, 1),
  [277] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_assignment, 3),
  [279] = {.entry = {.count = 1, .reusable = true}}, SHIFT(101),
  [281] = {.entry = {.count = 1, .reusable = true}}, SHIFT(87),
  [283] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_assign_block, 5),
  [285] = {.entry = {.count = 1, .reusable = true}}, SHIFT(43),
  [287] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [289] = {.entry = {.count = 1, .reusable = true}}, SHIFT(90),
  [291] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 2),
  [293] = {.entry = {.count = 1, .reusable = true}}, SHIFT(49),
  [295] = {.entry = {.count = 1, .reusable = true}}, SHIFT(64),
  [297] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [299] = {.entry = {.count = 1, .reusable = true}}, SHIFT(73),
  [301] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_assign_block, 4),
  [303] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [305] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1),
  [307] = {.entry = {.count = 1, .reusable = true}}, SHIFT(81),
  [309] = {.entry = {.count = 1, .reusable = true}}, SHIFT(35),
  [311] = {.entry = {.count = 1, .reusable = true}}, SHIFT(37),
  [313] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [315] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [317] = {.entry = {.count = 1, .reusable = true}}, SHIFT(38),
  [319] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [321] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [323] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [325] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [327] = {.entry = {.count = 1, .reusable = true}}, SHIFT(69),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef _WIN32
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_corn() {
  static const TSLanguage language = {
    .version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
