(comment) @comment
(include_stmt) @macro
(loose_name) @function
(ID) @variable
(QID) @variable
(C_STR_LIT) @string
(STR_LIT) @string
(BLOB_LIT) @constant
(data_type_any) @type
(AT_SENSITIVE) @type
(LET) @keyword
(SET) @keyword
(CREATE) @keyword
(TEMP) @keyword
(TABLE) @keyword
(WITHOUT) @keyword
(PRIMARY) @keyword
(KEY) @keyword
(TEMP) @keyword
(opt_if_not_exists) @keyword
(LIKE) @keyword
(WHERE) @keyword
(HAVING) @keyword
(FROM) @keyword
(WITH) @keyword
(USING) @keyword
(BEGIN) @keyword
(END) @keyword
(TRANSACTION) @keyword
(SELECT) @keyword
(ROWID) @keyword
(VAR) @keyword
(IF) @keyword
(ELSE) @keyword
(ELSE_IF) @keyword
(DELETE) @keyword
(THEN) @keyword
(SWITCH) @keyword
(WHILE) @keyword
(FOR) @keyword
(AS) @keyword
(LEAVE) @keyword
(RETURN) @keyword
(THROW) @keyword
(ROLLBACK) @keyword
(COMMIT) @keyword
(CONTINUE) @keyword
(UPDATE) @keyword
(LIMIT) @keyword
(GROUP) @keyword
(BY) @keyword
(ORDER) @keyword
(CALL) @keyword
(PROC) @keyword
(PROCEDURE) @keyword
(FUNC) @keyword
(FUNCTION) @keyword
(TRY) @keyword
(CATCH) @keyword
(DEFERRED) @keyword
(IMMEDIATE) @keyword
(EXCLUSIVE) @keyword
(SAVEPOINT) @keyword
(RELEASE) @keyword
(TO) @keyword
(AT_PROC) @macro
(AT_ID) @macro
(DECLARE) @keyword
(CURSOR) @keyword
(EXISTS) @operator
(FETCH) @keyword
(CAST) @operator
(DISTINCTROW) @operator
(DISTINCT) @operator
(RIGHT) @operator
(LEFT) @operator
(OUTER) @operator
(INNER) @operator
(CROSS) @operator
(JOIN) @operator
(CASE) @operator
(WHEN) @operator
(NOT) @operator
(BETWEEN) @operator
(AND) @operator
(OR) @operator
(INT_LIT) @constant
(REAL_LIT) @constant
(LONG_LIT) @constant
(TRUE) @constant
(FALSE) @constant
(ENUM) @keyword
(UNION) @keyword
(OFFSET) @keyword
(RECURSIVE) @keyword
(INSERT) @keyword
(INTO) @keyword
(VALUES) @keyword
(IGNORE) @keyword
(REPLACE) @keyword
(VIEW) @keyword
(INDEX) @keyword
(TRIGGER) @keyword
(ALTER) @keyword
(COLUMN) @keyword
(ADD) @keyword
(AT_CREATE) @macro
(AT_DELETE) @macro
(DROP) @keyword
(AT_PREVIOUS_SCHEMA) @macro
(AT_SCHEMA_UPGRADE_VERSION) @macro
(AT_SCHEMA_UPGRADE_SCRIPT) @macro
(ON) @keyword
(OUT) @attribute
(IN) @attribute
(UNIQUE) @keyword
(FOREIGN) @keyword
(DEFERRABLE) @keyword
(INITIALLY) @keyword
(DEFAULT) @keyword
(NULL) @constant
(ARGUMENTS) @variable
(MATCH) @operator
(GLOB) @operator
(REGEXP) @operator
(RAISE) @function
(FAIL) @keyword
(ABORT) @keyword
(AT_ATTRIBUTE) @macro
(AT_ENFORCE_STRICT) @macro
(AT_ENFORCE_NORMAL) @macro
(AT_ENFORCE_RESET) @macro
(AT_ENFORCE_PUSH) @macro
(AT_ENFORCE_POP) @macro
(AT_RC) @macro
(AT_DECLARE_SCHEMA_REGION) @macro
(AT_DECLARE_DEPLOYABLE_REGION) @macro
(AT_BEGIN_SCHEMA_REGION) @macro
(AT_END_SCHEMA_REGION) @macro
(AFTER) @keyword
(NOTHING) @keyword
(DO) @keyword
(EXPLAIN) @keyword
(QUERY_PLAN) @keyword
(AT_SCHEMA_AD_HOC_MIGRATION) @macro
(AT_RECREATE) @macro
(FILTER) @operator
(OVER) @operator
(RANGE) @operator
(PRECEDING) @operator
(FOLLOWING) @operator
(EXCLUDE_NO_OTHERS) @operator
(WINDOW) @keyword
(AT_DUMMY_SEED) @macro
(AT_DUMMY_DEFAULTS) @macro
(AT_DUMMY_NULLABLES) @macro
(COLLATE) @operator
(ROWS) @operator
(GROUPS) @operator
(PARTITION) @keyword
(CURRENT_ROW) @constant
(VIRTUAL) @keyword
(AT_EMIT_ENUMS) @macro
(CONSTRAINT) @keyword
(ON_CONFLICT) @keyword
(AUTOINCREMENT) @attribute
(IS_NOT) @operator
(IS) @operator
(NOT_BETWEEN) @operator
(NOT_DEFERRABLE) @operator
(IS_TRUE) @operator
(IS_FALSE) @operator
(IS_NOT_TRUE) @operator
(IS_NOT_FALSE) @operator
(ISNULL) @operator
(NOTNULL) @operator
(CHECK) @keyword
(NO) @keyword
(AT_EMIT_CONSTANTS) @macro
(CONST) @attribute
(AT_COLUMNS) @macro
(AT_UNSUB) @macro
(AT_BLOB_GET_KEY_TYPE) @macro
(AT_BLOB_GET_VAL_TYPE) @macro
(AT_BLOB_GET_KEY) @macro
(AT_BLOB_GET_VAL) @macro
(AT_BLOB_CREATE_KEY) @macro
(AT_BLOB_CREATE_VAL) @macro
(AT_BLOB_UPDATE_KEY) @macro
(AT_BLOB_UPDATE_VAL) @macro
(AT_KEEP_TABLE_NAME_IN_ALIASES) @macro
(cql_attr_key) @macro
(PRIVATE) @variable
(BEFORE) @keyword
(AT_ECHO) @macro
(AT_TEXT) @macro
(AT_OP) @macro
(AT_MACRO) @macro
(AT_IFDEF) @macro
(AT_IFNDEF) @macro
(AT_ELSE) @macro
(AT_ENDIF) @macro
