#include "parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 14
#define STATE_COUNT 50
#define LARGE_STATE_COUNT 5
#define SYMBOL_COUNT 35
#define ALIAS_COUNT 0
#define TOKEN_COUNT 23
#define EXTERNAL_TOKEN_COUNT 5
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 3
#define PRODUCTION_ID_COUNT 1

enum ts_symbol_identifiers {
  anon_sym_LBRACK = 1,
  anon_sym_RBRACK = 2,
  anon_sym_LBRACE = 3,
  anon_sym_RBRACE = 4,
  anon_sym_LT_LT = 5,
  anon_sym_GT_GT = 6,
  sym_operator = 7,
  sym_literal = 8,
  anon_sym_LPAREN = 9,
  anon_sym_RPAREN = 10,
  anon_sym_LT = 11,
  anon_sym_GT = 12,
  anon_sym_LT_TILDE = 13,
  anon_sym_TILDE_GT = 14,
  aux_sym_escape_sequence_token1 = 15,
  aux_sym_escape_sequence_token2 = 16,
  sym_comment = 17,
  sym_document_structure_comment = 18,
  sym_literal_string = 19,
  sym_hexadecimal_string = 20,
  sym_base85_string = 21,
  sym_numeric = 22,
  sym_document = 23,
  sym__element = 24,
  sym_array = 25,
  sym_procedure = 26,
  sym_dictionary = 27,
  sym_string = 28,
  sym_escape_sequence = 29,
  aux_sym_document_repeat1 = 30,
  aux_sym_array_repeat1 = 31,
  aux_sym_string_repeat1 = 32,
  aux_sym_string_repeat2 = 33,
  aux_sym_string_repeat3 = 34,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_LBRACK] = "[",
  [anon_sym_RBRACK] = "]",
  [anon_sym_LBRACE] = "{",
  [anon_sym_RBRACE] = "}",
  [anon_sym_LT_LT] = "<<",
  [anon_sym_GT_GT] = ">>",
  [sym_operator] = "operator",
  [sym_literal] = "literal",
  [anon_sym_LPAREN] = "(",
  [anon_sym_RPAREN] = ")",
  [anon_sym_LT] = "<",
  [anon_sym_GT] = ">",
  [anon_sym_LT_TILDE] = "<~",
  [anon_sym_TILDE_GT] = "~>",
  [aux_sym_escape_sequence_token1] = "escape_sequence_token1",
  [aux_sym_escape_sequence_token2] = "escape_sequence_token2",
  [sym_comment] = "comment",
  [sym_document_structure_comment] = "document_structure_comment",
  [sym_literal_string] = "literal_string",
  [sym_hexadecimal_string] = "hexadecimal_string",
  [sym_base85_string] = "base85_string",
  [sym_numeric] = "numeric",
  [sym_document] = "document",
  [sym__element] = "_element",
  [sym_array] = "array",
  [sym_procedure] = "procedure",
  [sym_dictionary] = "dictionary",
  [sym_string] = "string",
  [sym_escape_sequence] = "escape_sequence",
  [aux_sym_document_repeat1] = "document_repeat1",
  [aux_sym_array_repeat1] = "array_repeat1",
  [aux_sym_string_repeat1] = "string_repeat1",
  [aux_sym_string_repeat2] = "string_repeat2",
  [aux_sym_string_repeat3] = "string_repeat3",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_LBRACK] = anon_sym_LBRACK,
  [anon_sym_RBRACK] = anon_sym_RBRACK,
  [anon_sym_LBRACE] = anon_sym_LBRACE,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [anon_sym_LT_LT] = anon_sym_LT_LT,
  [anon_sym_GT_GT] = anon_sym_GT_GT,
  [sym_operator] = sym_operator,
  [sym_literal] = sym_literal,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [anon_sym_LT] = anon_sym_LT,
  [anon_sym_GT] = anon_sym_GT,
  [anon_sym_LT_TILDE] = anon_sym_LT_TILDE,
  [anon_sym_TILDE_GT] = anon_sym_TILDE_GT,
  [aux_sym_escape_sequence_token1] = aux_sym_escape_sequence_token1,
  [aux_sym_escape_sequence_token2] = aux_sym_escape_sequence_token2,
  [sym_comment] = sym_comment,
  [sym_document_structure_comment] = sym_document_structure_comment,
  [sym_literal_string] = sym_literal_string,
  [sym_hexadecimal_string] = sym_hexadecimal_string,
  [sym_base85_string] = sym_base85_string,
  [sym_numeric] = sym_numeric,
  [sym_document] = sym_document,
  [sym__element] = sym__element,
  [sym_array] = sym_array,
  [sym_procedure] = sym_procedure,
  [sym_dictionary] = sym_dictionary,
  [sym_string] = sym_string,
  [sym_escape_sequence] = sym_escape_sequence,
  [aux_sym_document_repeat1] = aux_sym_document_repeat1,
  [aux_sym_array_repeat1] = aux_sym_array_repeat1,
  [aux_sym_string_repeat1] = aux_sym_string_repeat1,
  [aux_sym_string_repeat2] = aux_sym_string_repeat2,
  [aux_sym_string_repeat3] = aux_sym_string_repeat3,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_LBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LT_LT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_GT_GT] = {
    .visible = true,
    .named = false,
  },
  [sym_operator] = {
    .visible = true,
    .named = true,
  },
  [sym_literal] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LT_TILDE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_TILDE_GT] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_escape_sequence_token1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_escape_sequence_token2] = {
    .visible = false,
    .named = false,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [sym_document_structure_comment] = {
    .visible = true,
    .named = true,
  },
  [sym_literal_string] = {
    .visible = true,
    .named = true,
  },
  [sym_hexadecimal_string] = {
    .visible = true,
    .named = true,
  },
  [sym_base85_string] = {
    .visible = true,
    .named = true,
  },
  [sym_numeric] = {
    .visible = true,
    .named = true,
  },
  [sym_document] = {
    .visible = true,
    .named = true,
  },
  [sym__element] = {
    .visible = false,
    .named = true,
  },
  [sym_array] = {
    .visible = true,
    .named = true,
  },
  [sym_procedure] = {
    .visible = true,
    .named = true,
  },
  [sym_dictionary] = {
    .visible = true,
    .named = true,
  },
  [sym_string] = {
    .visible = true,
    .named = true,
  },
  [sym_escape_sequence] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_document_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_array_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_string_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_string_repeat2] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_string_repeat3] = {
    .visible = false,
    .named = false,
  },
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 9,
  [12] = 7,
  [13] = 10,
  [14] = 5,
  [15] = 6,
  [16] = 8,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 18,
  [26] = 20,
  [27] = 21,
  [28] = 24,
  [29] = 22,
  [30] = 19,
  [31] = 23,
  [32] = 17,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 35,
  [37] = 34,
  [38] = 38,
  [39] = 39,
  [40] = 40,
  [41] = 41,
  [42] = 42,
  [43] = 43,
  [44] = 40,
  [45] = 45,
  [46] = 45,
  [47] = 42,
  [48] = 43,
  [49] = 49,
};

static TSCharacterRange sym_operator_character_set_1[] = {
  {'!', '$'}, {'&', '\''}, {'*', '.'}, {'0', ';'}, {'=', '='}, {'?', 'Z'}, {'^', 'z'}, {'|', '|'},
  {'~', '~'},
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(8);
      ADVANCE_MAP(
        '%', 27,
        '(', 17,
        ')', 18,
        '/', 3,
        '<', 19,
        '>', 20,
        '[', 9,
        '\\', 6,
        ']', 10,
        '{', 11,
        '}', 12,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      if (('!' <= lookahead && lookahead <= '~')) ADVANCE(15);
      END_STATE();
    case 1:
      ADVANCE_MAP(
        '%', 27,
        '(', 17,
        '/', 3,
        '<', 19,
        '>', 4,
        '[', 9,
        ']', 10,
        '{', 11,
        '}', 12,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(1);
      if (('!' <= lookahead && lookahead <= '\'') ||
          ('*' <= lookahead && lookahead <= 'Z') ||
          ('^' <= lookahead && lookahead <= '~')) ADVANCE(15);
      END_STATE();
    case 2:
      if (lookahead == '%') ADVANCE(27);
      if (lookahead == '~') ADVANCE(5);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(2);
      END_STATE();
    case 3:
      if (lookahead == '/') ADVANCE(7);
      if (set_contains(sym_operator_character_set_1, 9, lookahead)) ADVANCE(16);
      END_STATE();
    case 4:
      if (lookahead == '>') ADVANCE(14);
      END_STATE();
    case 5:
      if (lookahead == '>') ADVANCE(22);
      END_STATE();
    case 6:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(25);
      if (lookahead != 0) ADVANCE(26);
      END_STATE();
    case 7:
      if (set_contains(sym_operator_character_set_1, 9, lookahead)) ADVANCE(16);
      END_STATE();
    case 8:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 9:
      ACCEPT_TOKEN(anon_sym_LBRACK);
      END_STATE();
    case 10:
      ACCEPT_TOKEN(anon_sym_RBRACK);
      END_STATE();
    case 11:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      END_STATE();
    case 12:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 13:
      ACCEPT_TOKEN(anon_sym_LT_LT);
      END_STATE();
    case 14:
      ACCEPT_TOKEN(anon_sym_GT_GT);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(sym_operator);
      if (set_contains(sym_operator_character_set_1, 9, lookahead)) ADVANCE(15);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(sym_literal);
      if (set_contains(sym_operator_character_set_1, 9, lookahead)) ADVANCE(16);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(anon_sym_LT);
      if (lookahead == '<') ADVANCE(13);
      if (lookahead == '~') ADVANCE(21);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(anon_sym_GT);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(anon_sym_LT_TILDE);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(anon_sym_TILDE_GT);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(aux_sym_escape_sequence_token1);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(aux_sym_escape_sequence_token1);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(23);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(aux_sym_escape_sequence_token1);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(24);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(aux_sym_escape_sequence_token2);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(27);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0, .external_lex_state = 1},
  [1] = {.lex_state = 0, .external_lex_state = 2},
  [2] = {.lex_state = 1, .external_lex_state = 3},
  [3] = {.lex_state = 0, .external_lex_state = 2},
  [4] = {.lex_state = 0, .external_lex_state = 2},
  [5] = {.lex_state = 0, .external_lex_state = 3},
  [6] = {.lex_state = 0, .external_lex_state = 3},
  [7] = {.lex_state = 0, .external_lex_state = 3},
  [8] = {.lex_state = 0, .external_lex_state = 3},
  [9] = {.lex_state = 1, .external_lex_state = 3},
  [10] = {.lex_state = 1, .external_lex_state = 3},
  [11] = {.lex_state = 1, .external_lex_state = 3},
  [12] = {.lex_state = 0, .external_lex_state = 3},
  [13] = {.lex_state = 1, .external_lex_state = 3},
  [14] = {.lex_state = 0, .external_lex_state = 3},
  [15] = {.lex_state = 0, .external_lex_state = 3},
  [16] = {.lex_state = 0, .external_lex_state = 3},
  [17] = {.lex_state = 1, .external_lex_state = 3},
  [18] = {.lex_state = 1, .external_lex_state = 3},
  [19] = {.lex_state = 1, .external_lex_state = 3},
  [20] = {.lex_state = 1, .external_lex_state = 3},
  [21] = {.lex_state = 1, .external_lex_state = 3},
  [22] = {.lex_state = 1, .external_lex_state = 3},
  [23] = {.lex_state = 1, .external_lex_state = 3},
  [24] = {.lex_state = 1, .external_lex_state = 3},
  [25] = {.lex_state = 0, .external_lex_state = 2},
  [26] = {.lex_state = 0, .external_lex_state = 2},
  [27] = {.lex_state = 0, .external_lex_state = 2},
  [28] = {.lex_state = 0, .external_lex_state = 2},
  [29] = {.lex_state = 0, .external_lex_state = 2},
  [30] = {.lex_state = 0, .external_lex_state = 2},
  [31] = {.lex_state = 0, .external_lex_state = 2},
  [32] = {.lex_state = 0, .external_lex_state = 2},
  [33] = {.lex_state = 0, .external_lex_state = 4},
  [34] = {.lex_state = 0, .external_lex_state = 4},
  [35] = {.lex_state = 0, .external_lex_state = 4},
  [36] = {.lex_state = 0, .external_lex_state = 4},
  [37] = {.lex_state = 0, .external_lex_state = 4},
  [38] = {.lex_state = 0, .external_lex_state = 4},
  [39] = {.lex_state = 0, .external_lex_state = 5},
  [40] = {.lex_state = 2, .external_lex_state = 6},
  [41] = {.lex_state = 2, .external_lex_state = 6},
  [42] = {.lex_state = 0, .external_lex_state = 5},
  [43] = {.lex_state = 2, .external_lex_state = 6},
  [44] = {.lex_state = 2, .external_lex_state = 6},
  [45] = {.lex_state = 0, .external_lex_state = 5},
  [46] = {.lex_state = 0, .external_lex_state = 5},
  [47] = {.lex_state = 0, .external_lex_state = 5},
  [48] = {.lex_state = 2, .external_lex_state = 6},
  [49] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [0] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_LBRACK] = ACTIONS(1),
    [anon_sym_RBRACK] = ACTIONS(1),
    [anon_sym_LBRACE] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [anon_sym_LT_LT] = ACTIONS(1),
    [sym_operator] = ACTIONS(1),
    [sym_literal] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [anon_sym_LT] = ACTIONS(1),
    [anon_sym_GT] = ACTIONS(1),
    [anon_sym_LT_TILDE] = ACTIONS(1),
    [aux_sym_escape_sequence_token1] = ACTIONS(1),
    [aux_sym_escape_sequence_token2] = ACTIONS(1),
    [sym_comment] = ACTIONS(3),
    [sym_document_structure_comment] = ACTIONS(1),
    [sym_literal_string] = ACTIONS(1),
    [sym_hexadecimal_string] = ACTIONS(1),
    [sym_base85_string] = ACTIONS(1),
    [sym_numeric] = ACTIONS(1),
  },
  [1] = {
    [sym_document] = STATE(49),
    [sym__element] = STATE(4),
    [sym_array] = STATE(4),
    [sym_procedure] = STATE(4),
    [sym_dictionary] = STATE(4),
    [sym_string] = STATE(4),
    [aux_sym_document_repeat1] = STATE(4),
    [ts_builtin_sym_end] = ACTIONS(5),
    [anon_sym_LBRACK] = ACTIONS(7),
    [anon_sym_LBRACE] = ACTIONS(9),
    [anon_sym_LT_LT] = ACTIONS(11),
    [sym_operator] = ACTIONS(13),
    [sym_literal] = ACTIONS(13),
    [anon_sym_LPAREN] = ACTIONS(15),
    [anon_sym_LT] = ACTIONS(17),
    [anon_sym_LT_TILDE] = ACTIONS(19),
    [sym_comment] = ACTIONS(3),
    [sym_document_structure_comment] = ACTIONS(13),
    [sym_numeric] = ACTIONS(13),
  },
  [2] = {
    [sym__element] = STATE(2),
    [sym_array] = STATE(2),
    [sym_procedure] = STATE(2),
    [sym_dictionary] = STATE(2),
    [sym_string] = STATE(2),
    [aux_sym_array_repeat1] = STATE(2),
    [anon_sym_LBRACK] = ACTIONS(21),
    [anon_sym_RBRACK] = ACTIONS(24),
    [anon_sym_LBRACE] = ACTIONS(26),
    [anon_sym_RBRACE] = ACTIONS(24),
    [anon_sym_LT_LT] = ACTIONS(29),
    [anon_sym_GT_GT] = ACTIONS(24),
    [sym_operator] = ACTIONS(32),
    [sym_literal] = ACTIONS(32),
    [anon_sym_LPAREN] = ACTIONS(35),
    [anon_sym_LT] = ACTIONS(38),
    [anon_sym_LT_TILDE] = ACTIONS(41),
    [sym_comment] = ACTIONS(3),
    [sym_numeric] = ACTIONS(32),
  },
  [3] = {
    [sym__element] = STATE(3),
    [sym_array] = STATE(3),
    [sym_procedure] = STATE(3),
    [sym_dictionary] = STATE(3),
    [sym_string] = STATE(3),
    [aux_sym_document_repeat1] = STATE(3),
    [ts_builtin_sym_end] = ACTIONS(44),
    [anon_sym_LBRACK] = ACTIONS(46),
    [anon_sym_LBRACE] = ACTIONS(49),
    [anon_sym_LT_LT] = ACTIONS(52),
    [sym_operator] = ACTIONS(55),
    [sym_literal] = ACTIONS(55),
    [anon_sym_LPAREN] = ACTIONS(58),
    [anon_sym_LT] = ACTIONS(61),
    [anon_sym_LT_TILDE] = ACTIONS(64),
    [sym_comment] = ACTIONS(3),
    [sym_document_structure_comment] = ACTIONS(55),
    [sym_numeric] = ACTIONS(55),
  },
  [4] = {
    [sym__element] = STATE(3),
    [sym_array] = STATE(3),
    [sym_procedure] = STATE(3),
    [sym_dictionary] = STATE(3),
    [sym_string] = STATE(3),
    [aux_sym_document_repeat1] = STATE(3),
    [ts_builtin_sym_end] = ACTIONS(67),
    [anon_sym_LBRACK] = ACTIONS(7),
    [anon_sym_LBRACE] = ACTIONS(9),
    [anon_sym_LT_LT] = ACTIONS(11),
    [sym_operator] = ACTIONS(69),
    [sym_literal] = ACTIONS(69),
    [anon_sym_LPAREN] = ACTIONS(15),
    [anon_sym_LT] = ACTIONS(17),
    [anon_sym_LT_TILDE] = ACTIONS(19),
    [sym_comment] = ACTIONS(3),
    [sym_document_structure_comment] = ACTIONS(69),
    [sym_numeric] = ACTIONS(69),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 10,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(71), 1,
      anon_sym_LBRACK,
    ACTIONS(73), 1,
      anon_sym_RBRACK,
    ACTIONS(75), 1,
      anon_sym_LBRACE,
    ACTIONS(77), 1,
      anon_sym_LT_LT,
    ACTIONS(81), 1,
      anon_sym_LPAREN,
    ACTIONS(83), 1,
      anon_sym_LT,
    ACTIONS(85), 1,
      anon_sym_LT_TILDE,
    ACTIONS(79), 3,
      sym_numeric,
      sym_operator,
      sym_literal,
    STATE(7), 6,
      sym__element,
      sym_array,
      sym_procedure,
      sym_dictionary,
      sym_string,
      aux_sym_array_repeat1,
  [38] = 10,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(71), 1,
      anon_sym_LBRACK,
    ACTIONS(75), 1,
      anon_sym_LBRACE,
    ACTIONS(77), 1,
      anon_sym_LT_LT,
    ACTIONS(81), 1,
      anon_sym_LPAREN,
    ACTIONS(83), 1,
      anon_sym_LT,
    ACTIONS(85), 1,
      anon_sym_LT_TILDE,
    ACTIONS(87), 1,
      anon_sym_RBRACE,
    ACTIONS(89), 3,
      sym_numeric,
      sym_operator,
      sym_literal,
    STATE(8), 6,
      sym__element,
      sym_array,
      sym_procedure,
      sym_dictionary,
      sym_string,
      aux_sym_array_repeat1,
  [76] = 10,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(71), 1,
      anon_sym_LBRACK,
    ACTIONS(75), 1,
      anon_sym_LBRACE,
    ACTIONS(77), 1,
      anon_sym_LT_LT,
    ACTIONS(81), 1,
      anon_sym_LPAREN,
    ACTIONS(83), 1,
      anon_sym_LT,
    ACTIONS(85), 1,
      anon_sym_LT_TILDE,
    ACTIONS(91), 1,
      anon_sym_RBRACK,
    ACTIONS(93), 3,
      sym_numeric,
      sym_operator,
      sym_literal,
    STATE(2), 6,
      sym__element,
      sym_array,
      sym_procedure,
      sym_dictionary,
      sym_string,
      aux_sym_array_repeat1,
  [114] = 10,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(71), 1,
      anon_sym_LBRACK,
    ACTIONS(75), 1,
      anon_sym_LBRACE,
    ACTIONS(77), 1,
      anon_sym_LT_LT,
    ACTIONS(81), 1,
      anon_sym_LPAREN,
    ACTIONS(83), 1,
      anon_sym_LT,
    ACTIONS(85), 1,
      anon_sym_LT_TILDE,
    ACTIONS(95), 1,
      anon_sym_RBRACE,
    ACTIONS(93), 3,
      sym_numeric,
      sym_operator,
      sym_literal,
    STATE(2), 6,
      sym__element,
      sym_array,
      sym_procedure,
      sym_dictionary,
      sym_string,
      aux_sym_array_repeat1,
  [152] = 10,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(71), 1,
      anon_sym_LBRACK,
    ACTIONS(75), 1,
      anon_sym_LBRACE,
    ACTIONS(77), 1,
      anon_sym_LT_LT,
    ACTIONS(81), 1,
      anon_sym_LPAREN,
    ACTIONS(83), 1,
      anon_sym_LT,
    ACTIONS(85), 1,
      anon_sym_LT_TILDE,
    ACTIONS(97), 1,
      anon_sym_GT_GT,
    ACTIONS(93), 3,
      sym_numeric,
      sym_operator,
      sym_literal,
    STATE(2), 6,
      sym__element,
      sym_array,
      sym_procedure,
      sym_dictionary,
      sym_string,
      aux_sym_array_repeat1,
  [190] = 10,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(71), 1,
      anon_sym_LBRACK,
    ACTIONS(75), 1,
      anon_sym_LBRACE,
    ACTIONS(77), 1,
      anon_sym_LT_LT,
    ACTIONS(81), 1,
      anon_sym_LPAREN,
    ACTIONS(83), 1,
      anon_sym_LT,
    ACTIONS(85), 1,
      anon_sym_LT_TILDE,
    ACTIONS(99), 1,
      anon_sym_GT_GT,
    ACTIONS(101), 3,
      sym_numeric,
      sym_operator,
      sym_literal,
    STATE(9), 6,
      sym__element,
      sym_array,
      sym_procedure,
      sym_dictionary,
      sym_string,
      aux_sym_array_repeat1,
  [228] = 10,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(71), 1,
      anon_sym_LBRACK,
    ACTIONS(75), 1,
      anon_sym_LBRACE,
    ACTIONS(77), 1,
      anon_sym_LT_LT,
    ACTIONS(81), 1,
      anon_sym_LPAREN,
    ACTIONS(83), 1,
      anon_sym_LT,
    ACTIONS(85), 1,
      anon_sym_LT_TILDE,
    ACTIONS(103), 1,
      anon_sym_GT_GT,
    ACTIONS(93), 3,
      sym_numeric,
      sym_operator,
      sym_literal,
    STATE(2), 6,
      sym__element,
      sym_array,
      sym_procedure,
      sym_dictionary,
      sym_string,
      aux_sym_array_repeat1,
  [266] = 10,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(71), 1,
      anon_sym_LBRACK,
    ACTIONS(75), 1,
      anon_sym_LBRACE,
    ACTIONS(77), 1,
      anon_sym_LT_LT,
    ACTIONS(81), 1,
      anon_sym_LPAREN,
    ACTIONS(83), 1,
      anon_sym_LT,
    ACTIONS(85), 1,
      anon_sym_LT_TILDE,
    ACTIONS(105), 1,
      anon_sym_RBRACK,
    ACTIONS(93), 3,
      sym_numeric,
      sym_operator,
      sym_literal,
    STATE(2), 6,
      sym__element,
      sym_array,
      sym_procedure,
      sym_dictionary,
      sym_string,
      aux_sym_array_repeat1,
  [304] = 10,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(71), 1,
      anon_sym_LBRACK,
    ACTIONS(75), 1,
      anon_sym_LBRACE,
    ACTIONS(77), 1,
      anon_sym_LT_LT,
    ACTIONS(81), 1,
      anon_sym_LPAREN,
    ACTIONS(83), 1,
      anon_sym_LT,
    ACTIONS(85), 1,
      anon_sym_LT_TILDE,
    ACTIONS(107), 1,
      anon_sym_GT_GT,
    ACTIONS(109), 3,
      sym_numeric,
      sym_operator,
      sym_literal,
    STATE(11), 6,
      sym__element,
      sym_array,
      sym_procedure,
      sym_dictionary,
      sym_string,
      aux_sym_array_repeat1,
  [342] = 10,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(71), 1,
      anon_sym_LBRACK,
    ACTIONS(75), 1,
      anon_sym_LBRACE,
    ACTIONS(77), 1,
      anon_sym_LT_LT,
    ACTIONS(81), 1,
      anon_sym_LPAREN,
    ACTIONS(83), 1,
      anon_sym_LT,
    ACTIONS(85), 1,
      anon_sym_LT_TILDE,
    ACTIONS(111), 1,
      anon_sym_RBRACK,
    ACTIONS(113), 3,
      sym_numeric,
      sym_operator,
      sym_literal,
    STATE(12), 6,
      sym__element,
      sym_array,
      sym_procedure,
      sym_dictionary,
      sym_string,
      aux_sym_array_repeat1,
  [380] = 10,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(71), 1,
      anon_sym_LBRACK,
    ACTIONS(75), 1,
      anon_sym_LBRACE,
    ACTIONS(77), 1,
      anon_sym_LT_LT,
    ACTIONS(81), 1,
      anon_sym_LPAREN,
    ACTIONS(83), 1,
      anon_sym_LT,
    ACTIONS(85), 1,
      anon_sym_LT_TILDE,
    ACTIONS(115), 1,
      anon_sym_RBRACE,
    ACTIONS(117), 3,
      sym_numeric,
      sym_operator,
      sym_literal,
    STATE(16), 6,
      sym__element,
      sym_array,
      sym_procedure,
      sym_dictionary,
      sym_string,
      aux_sym_array_repeat1,
  [418] = 10,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(71), 1,
      anon_sym_LBRACK,
    ACTIONS(75), 1,
      anon_sym_LBRACE,
    ACTIONS(77), 1,
      anon_sym_LT_LT,
    ACTIONS(81), 1,
      anon_sym_LPAREN,
    ACTIONS(83), 1,
      anon_sym_LT,
    ACTIONS(85), 1,
      anon_sym_LT_TILDE,
    ACTIONS(119), 1,
      anon_sym_RBRACE,
    ACTIONS(93), 3,
      sym_numeric,
      sym_operator,
      sym_literal,
    STATE(2), 6,
      sym__element,
      sym_array,
      sym_procedure,
      sym_dictionary,
      sym_string,
      aux_sym_array_repeat1,
  [456] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(123), 1,
      anon_sym_LT,
    ACTIONS(121), 11,
      sym_numeric,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_LT_LT,
      anon_sym_GT_GT,
      sym_operator,
      sym_literal,
      anon_sym_LPAREN,
      anon_sym_LT_TILDE,
  [476] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(127), 1,
      anon_sym_LT,
    ACTIONS(125), 11,
      sym_numeric,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_LT_LT,
      anon_sym_GT_GT,
      sym_operator,
      sym_literal,
      anon_sym_LPAREN,
      anon_sym_LT_TILDE,
  [496] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(131), 1,
      anon_sym_LT,
    ACTIONS(129), 11,
      sym_numeric,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_LT_LT,
      anon_sym_GT_GT,
      sym_operator,
      sym_literal,
      anon_sym_LPAREN,
      anon_sym_LT_TILDE,
  [516] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(135), 1,
      anon_sym_LT,
    ACTIONS(133), 11,
      sym_numeric,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_LT_LT,
      anon_sym_GT_GT,
      sym_operator,
      sym_literal,
      anon_sym_LPAREN,
      anon_sym_LT_TILDE,
  [536] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(139), 1,
      anon_sym_LT,
    ACTIONS(137), 11,
      sym_numeric,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_LT_LT,
      anon_sym_GT_GT,
      sym_operator,
      sym_literal,
      anon_sym_LPAREN,
      anon_sym_LT_TILDE,
  [556] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(143), 1,
      anon_sym_LT,
    ACTIONS(141), 11,
      sym_numeric,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_LT_LT,
      anon_sym_GT_GT,
      sym_operator,
      sym_literal,
      anon_sym_LPAREN,
      anon_sym_LT_TILDE,
  [576] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(147), 1,
      anon_sym_LT,
    ACTIONS(145), 11,
      sym_numeric,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_LT_LT,
      anon_sym_GT_GT,
      sym_operator,
      sym_literal,
      anon_sym_LPAREN,
      anon_sym_LT_TILDE,
  [596] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(151), 1,
      anon_sym_LT,
    ACTIONS(149), 11,
      sym_numeric,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_LT_LT,
      anon_sym_GT_GT,
      sym_operator,
      sym_literal,
      anon_sym_LPAREN,
      anon_sym_LT_TILDE,
  [616] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(127), 1,
      anon_sym_LT,
    ACTIONS(125), 10,
      sym_document_structure_comment,
      sym_numeric,
      ts_builtin_sym_end,
      anon_sym_LBRACK,
      anon_sym_LBRACE,
      anon_sym_LT_LT,
      sym_operator,
      sym_literal,
      anon_sym_LPAREN,
      anon_sym_LT_TILDE,
  [635] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(135), 1,
      anon_sym_LT,
    ACTIONS(133), 10,
      sym_document_structure_comment,
      sym_numeric,
      ts_builtin_sym_end,
      anon_sym_LBRACK,
      anon_sym_LBRACE,
      anon_sym_LT_LT,
      sym_operator,
      sym_literal,
      anon_sym_LPAREN,
      anon_sym_LT_TILDE,
  [654] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(139), 1,
      anon_sym_LT,
    ACTIONS(137), 10,
      sym_document_structure_comment,
      sym_numeric,
      ts_builtin_sym_end,
      anon_sym_LBRACK,
      anon_sym_LBRACE,
      anon_sym_LT_LT,
      sym_operator,
      sym_literal,
      anon_sym_LPAREN,
      anon_sym_LT_TILDE,
  [673] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(151), 1,
      anon_sym_LT,
    ACTIONS(149), 10,
      sym_document_structure_comment,
      sym_numeric,
      ts_builtin_sym_end,
      anon_sym_LBRACK,
      anon_sym_LBRACE,
      anon_sym_LT_LT,
      sym_operator,
      sym_literal,
      anon_sym_LPAREN,
      anon_sym_LT_TILDE,
  [692] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(143), 1,
      anon_sym_LT,
    ACTIONS(141), 10,
      sym_document_structure_comment,
      sym_numeric,
      ts_builtin_sym_end,
      anon_sym_LBRACK,
      anon_sym_LBRACE,
      anon_sym_LT_LT,
      sym_operator,
      sym_literal,
      anon_sym_LPAREN,
      anon_sym_LT_TILDE,
  [711] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(131), 1,
      anon_sym_LT,
    ACTIONS(129), 10,
      sym_document_structure_comment,
      sym_numeric,
      ts_builtin_sym_end,
      anon_sym_LBRACK,
      anon_sym_LBRACE,
      anon_sym_LT_LT,
      sym_operator,
      sym_literal,
      anon_sym_LPAREN,
      anon_sym_LT_TILDE,
  [730] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(147), 1,
      anon_sym_LT,
    ACTIONS(145), 10,
      sym_document_structure_comment,
      sym_numeric,
      ts_builtin_sym_end,
      anon_sym_LBRACK,
      anon_sym_LBRACE,
      anon_sym_LT_LT,
      sym_operator,
      sym_literal,
      anon_sym_LPAREN,
      anon_sym_LT_TILDE,
  [749] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(123), 1,
      anon_sym_LT,
    ACTIONS(121), 10,
      sym_document_structure_comment,
      sym_numeric,
      ts_builtin_sym_end,
      anon_sym_LBRACK,
      anon_sym_LBRACE,
      anon_sym_LT_LT,
      sym_operator,
      sym_literal,
      anon_sym_LPAREN,
      anon_sym_LT_TILDE,
  [768] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(153), 1,
      anon_sym_RPAREN,
    ACTIONS(158), 1,
      sym_literal_string,
    ACTIONS(155), 2,
      aux_sym_escape_sequence_token1,
      aux_sym_escape_sequence_token2,
    STATE(33), 2,
      sym_escape_sequence,
      aux_sym_string_repeat1,
  [786] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(161), 1,
      anon_sym_RPAREN,
    ACTIONS(165), 1,
      sym_literal_string,
    ACTIONS(163), 2,
      aux_sym_escape_sequence_token1,
      aux_sym_escape_sequence_token2,
    STATE(33), 2,
      sym_escape_sequence,
      aux_sym_string_repeat1,
  [804] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(167), 1,
      anon_sym_RPAREN,
    ACTIONS(169), 1,
      sym_literal_string,
    ACTIONS(163), 2,
      aux_sym_escape_sequence_token1,
      aux_sym_escape_sequence_token2,
    STATE(37), 2,
      sym_escape_sequence,
      aux_sym_string_repeat1,
  [822] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(171), 1,
      anon_sym_RPAREN,
    ACTIONS(173), 1,
      sym_literal_string,
    ACTIONS(163), 2,
      aux_sym_escape_sequence_token1,
      aux_sym_escape_sequence_token2,
    STATE(34), 2,
      sym_escape_sequence,
      aux_sym_string_repeat1,
  [840] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(165), 1,
      sym_literal_string,
    ACTIONS(175), 1,
      anon_sym_RPAREN,
    ACTIONS(163), 2,
      aux_sym_escape_sequence_token1,
      aux_sym_escape_sequence_token2,
    STATE(33), 2,
      sym_escape_sequence,
      aux_sym_string_repeat1,
  [858] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(177), 4,
      sym_literal_string,
      anon_sym_RPAREN,
      aux_sym_escape_sequence_token1,
      aux_sym_escape_sequence_token2,
  [868] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(179), 1,
      anon_sym_GT,
    ACTIONS(181), 1,
      sym_hexadecimal_string,
    STATE(39), 1,
      aux_sym_string_repeat2,
  [881] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(171), 1,
      anon_sym_TILDE_GT,
    ACTIONS(184), 1,
      sym_base85_string,
    STATE(43), 1,
      aux_sym_string_repeat3,
  [894] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(186), 1,
      anon_sym_TILDE_GT,
    ACTIONS(188), 1,
      sym_base85_string,
    STATE(41), 1,
      aux_sym_string_repeat3,
  [907] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(161), 1,
      anon_sym_GT,
    ACTIONS(191), 1,
      sym_hexadecimal_string,
    STATE(39), 1,
      aux_sym_string_repeat2,
  [920] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(161), 1,
      anon_sym_TILDE_GT,
    ACTIONS(193), 1,
      sym_base85_string,
    STATE(41), 1,
      aux_sym_string_repeat3,
  [933] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(167), 1,
      anon_sym_TILDE_GT,
    ACTIONS(195), 1,
      sym_base85_string,
    STATE(48), 1,
      aux_sym_string_repeat3,
  [946] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(171), 1,
      anon_sym_GT,
    ACTIONS(197), 1,
      sym_hexadecimal_string,
    STATE(42), 1,
      aux_sym_string_repeat2,
  [959] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(167), 1,
      anon_sym_GT,
    ACTIONS(199), 1,
      sym_hexadecimal_string,
    STATE(47), 1,
      aux_sym_string_repeat2,
  [972] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(175), 1,
      anon_sym_GT,
    ACTIONS(191), 1,
      sym_hexadecimal_string,
    STATE(39), 1,
      aux_sym_string_repeat2,
  [985] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(175), 1,
      anon_sym_TILDE_GT,
    ACTIONS(193), 1,
      sym_base85_string,
    STATE(41), 1,
      aux_sym_string_repeat3,
  [998] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(201), 1,
      ts_builtin_sym_end,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(5)] = 0,
  [SMALL_STATE(6)] = 38,
  [SMALL_STATE(7)] = 76,
  [SMALL_STATE(8)] = 114,
  [SMALL_STATE(9)] = 152,
  [SMALL_STATE(10)] = 190,
  [SMALL_STATE(11)] = 228,
  [SMALL_STATE(12)] = 266,
  [SMALL_STATE(13)] = 304,
  [SMALL_STATE(14)] = 342,
  [SMALL_STATE(15)] = 380,
  [SMALL_STATE(16)] = 418,
  [SMALL_STATE(17)] = 456,
  [SMALL_STATE(18)] = 476,
  [SMALL_STATE(19)] = 496,
  [SMALL_STATE(20)] = 516,
  [SMALL_STATE(21)] = 536,
  [SMALL_STATE(22)] = 556,
  [SMALL_STATE(23)] = 576,
  [SMALL_STATE(24)] = 596,
  [SMALL_STATE(25)] = 616,
  [SMALL_STATE(26)] = 635,
  [SMALL_STATE(27)] = 654,
  [SMALL_STATE(28)] = 673,
  [SMALL_STATE(29)] = 692,
  [SMALL_STATE(30)] = 711,
  [SMALL_STATE(31)] = 730,
  [SMALL_STATE(32)] = 749,
  [SMALL_STATE(33)] = 768,
  [SMALL_STATE(34)] = 786,
  [SMALL_STATE(35)] = 804,
  [SMALL_STATE(36)] = 822,
  [SMALL_STATE(37)] = 840,
  [SMALL_STATE(38)] = 858,
  [SMALL_STATE(39)] = 868,
  [SMALL_STATE(40)] = 881,
  [SMALL_STATE(41)] = 894,
  [SMALL_STATE(42)] = 907,
  [SMALL_STATE(43)] = 920,
  [SMALL_STATE(44)] = 933,
  [SMALL_STATE(45)] = 946,
  [SMALL_STATE(46)] = 959,
  [SMALL_STATE(47)] = 972,
  [SMALL_STATE(48)] = 985,
  [SMALL_STATE(49)] = 998,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT_EXTRA(),
  [5] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_document, 0, 0, 0),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(36),
  [17] = {.entry = {.count = 1, .reusable = false}}, SHIFT(45),
  [19] = {.entry = {.count = 1, .reusable = true}}, SHIFT(40),
  [21] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_array_repeat1, 2, 0, 0), SHIFT_REPEAT(14),
  [24] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_array_repeat1, 2, 0, 0),
  [26] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_array_repeat1, 2, 0, 0), SHIFT_REPEAT(15),
  [29] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_array_repeat1, 2, 0, 0), SHIFT_REPEAT(13),
  [32] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_array_repeat1, 2, 0, 0), SHIFT_REPEAT(2),
  [35] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_array_repeat1, 2, 0, 0), SHIFT_REPEAT(35),
  [38] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_array_repeat1, 2, 0, 0), SHIFT_REPEAT(46),
  [41] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_array_repeat1, 2, 0, 0), SHIFT_REPEAT(44),
  [44] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0),
  [46] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0), SHIFT_REPEAT(5),
  [49] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0), SHIFT_REPEAT(6),
  [52] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0), SHIFT_REPEAT(10),
  [55] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0), SHIFT_REPEAT(3),
  [58] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0), SHIFT_REPEAT(36),
  [61] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0), SHIFT_REPEAT(45),
  [64] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0), SHIFT_REPEAT(40),
  [67] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_document, 1, 0, 0),
  [69] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [71] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [73] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
  [75] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [77] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [79] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [81] = {.entry = {.count = 1, .reusable = true}}, SHIFT(35),
  [83] = {.entry = {.count = 1, .reusable = false}}, SHIFT(46),
  [85] = {.entry = {.count = 1, .reusable = true}}, SHIFT(44),
  [87] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [89] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [91] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [93] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [95] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [97] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
  [99] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [101] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [103] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [105] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [107] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [109] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [111] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [113] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [115] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [117] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [119] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [121] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_array, 2, 0, 0),
  [123] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_array, 2, 0, 0),
  [125] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_procedure, 3, 0, 0),
  [127] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_procedure, 3, 0, 0),
  [129] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_array, 3, 0, 0),
  [131] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_array, 3, 0, 0),
  [133] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_string, 3, 0, 0),
  [135] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_string, 3, 0, 0),
  [137] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_string, 2, 0, 0),
  [139] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_string, 2, 0, 0),
  [141] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_dictionary, 2, 0, 0),
  [143] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_dictionary, 2, 0, 0),
  [145] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_dictionary, 3, 0, 0),
  [147] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_dictionary, 3, 0, 0),
  [149] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_procedure, 2, 0, 0),
  [151] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_procedure, 2, 0, 0),
  [153] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_string_repeat1, 2, 0, 0),
  [155] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_string_repeat1, 2, 0, 0), SHIFT_REPEAT(38),
  [158] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_string_repeat1, 2, 0, 0), SHIFT_REPEAT(33),
  [161] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [163] = {.entry = {.count = 1, .reusable = true}}, SHIFT(38),
  [165] = {.entry = {.count = 1, .reusable = true}}, SHIFT(33),
  [167] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [169] = {.entry = {.count = 1, .reusable = true}}, SHIFT(37),
  [171] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [173] = {.entry = {.count = 1, .reusable = true}}, SHIFT(34),
  [175] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [177] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_escape_sequence, 1, 0, 0),
  [179] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_string_repeat2, 2, 0, 0),
  [181] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_string_repeat2, 2, 0, 0), SHIFT_REPEAT(39),
  [184] = {.entry = {.count = 1, .reusable = true}}, SHIFT(43),
  [186] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_string_repeat3, 2, 0, 0),
  [188] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_string_repeat3, 2, 0, 0), SHIFT_REPEAT(41),
  [191] = {.entry = {.count = 1, .reusable = true}}, SHIFT(39),
  [193] = {.entry = {.count = 1, .reusable = true}}, SHIFT(41),
  [195] = {.entry = {.count = 1, .reusable = true}}, SHIFT(48),
  [197] = {.entry = {.count = 1, .reusable = true}}, SHIFT(42),
  [199] = {.entry = {.count = 1, .reusable = true}}, SHIFT(47),
  [201] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
};

enum ts_external_scanner_symbol_identifiers {
  ts_external_token_document_structure_comment = 0,
  ts_external_token_literal_string = 1,
  ts_external_token_hexadecimal_string = 2,
  ts_external_token_base85_string = 3,
  ts_external_token_numeric = 4,
};

static const TSSymbol ts_external_scanner_symbol_map[EXTERNAL_TOKEN_COUNT] = {
  [ts_external_token_document_structure_comment] = sym_document_structure_comment,
  [ts_external_token_literal_string] = sym_literal_string,
  [ts_external_token_hexadecimal_string] = sym_hexadecimal_string,
  [ts_external_token_base85_string] = sym_base85_string,
  [ts_external_token_numeric] = sym_numeric,
};

static const bool ts_external_scanner_states[7][EXTERNAL_TOKEN_COUNT] = {
  [1] = {
    [ts_external_token_document_structure_comment] = true,
    [ts_external_token_literal_string] = true,
    [ts_external_token_hexadecimal_string] = true,
    [ts_external_token_base85_string] = true,
    [ts_external_token_numeric] = true,
  },
  [2] = {
    [ts_external_token_document_structure_comment] = true,
    [ts_external_token_numeric] = true,
  },
  [3] = {
    [ts_external_token_numeric] = true,
  },
  [4] = {
    [ts_external_token_literal_string] = true,
  },
  [5] = {
    [ts_external_token_hexadecimal_string] = true,
  },
  [6] = {
    [ts_external_token_base85_string] = true,
  },
};

#ifdef __cplusplus
extern "C" {
#endif
void *tree_sitter_postscript_external_scanner_create(void);
void tree_sitter_postscript_external_scanner_destroy(void *);
bool tree_sitter_postscript_external_scanner_scan(void *, TSLexer *, const bool *);
unsigned tree_sitter_postscript_external_scanner_serialize(void *, char *);
void tree_sitter_postscript_external_scanner_deserialize(void *, const char *, unsigned);

#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_postscript(void) {
  static const TSLanguage language = {
    .version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = ts_lex_modes,
    .lex_fn = ts_lex,
    .external_scanner = {
      &ts_external_scanner_states[0][0],
      ts_external_scanner_symbol_map,
      tree_sitter_postscript_external_scanner_create,
      tree_sitter_postscript_external_scanner_destroy,
      tree_sitter_postscript_external_scanner_scan,
      tree_sitter_postscript_external_scanner_serialize,
      tree_sitter_postscript_external_scanner_deserialize,
    },
    .primary_state_ids = ts_primary_state_ids,
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
