(comment) @comment
(keyword) @keyword
(target_division) @function.builtin
(define_division) @function.builtin
(setup_division) @function.builtin
(print_division) @function.builtin
(select_division) @function.builtin
(sort_division) @function.builtin
(letter_division) @function.builtin
(total_division) @function.builtin
(field_name) @variable.member
(record_type) @type
(include_statement)  @include
(string_literal) @string
(data_type) @type
(array_type) @type
(number) @number
(procedure_call
  procedure_name: (identifier)) @function
(procedure_definition) @keyword
(while_statement) @repeat
(for_statement) @repeat
(if_statement) @conditional
(date) @string
(rate) @number
(money) @string
(identifier) @variable
(for_loop) @repeat
(poweron_function) @function
(setexp) @function
