#include "parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 14
#define STATE_COUNT 53
#define LARGE_STATE_COUNT 52
#define SYMBOL_COUNT 33
#define ALIAS_COUNT 0
#define TOKEN_COUNT 21
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 3
#define MAX_ALIAS_SEQUENCE_LENGTH 3
#define PRODUCTION_ID_COUNT 3

enum ts_symbol_identifiers {
  sym_symbol = 1,
  anon_sym_EQ_GT = 2,
  anon_sym_EQ = 3,
  anon_sym_LBRACE = 4,
  anon_sym_RBRACE = 5,
  anon_sym_LPAREN = 6,
  anon_sym_RPAREN = 7,
  anon_sym_LBRACK = 8,
  anon_sym_RBRACK = 9,
  anon_sym_do = 10,
  anon_sym_end = 11,
  sym_sigil = 12,
  sym_send = 13,
  sym_message = 14,
  sym_singlestring = 15,
  sym_doublestring = 16,
  sym_comment = 17,
  sym_operator = 18,
  sym__newline = 19,
  sym_number = 20,
  sym_source_file = 21,
  sym__expression = 22,
  sym_unary = 23,
  sym_binary = 24,
  sym_special_send = 25,
  sym_record = 26,
  sym_tuple = 27,
  sym_list = 28,
  sym_block = 29,
  sym_string = 30,
  aux_sym_source_file_repeat1 = 31,
  aux_sym_record_repeat1 = 32,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [sym_symbol] = "symbol",
  [anon_sym_EQ_GT] = "=>",
  [anon_sym_EQ] = "=",
  [anon_sym_LBRACE] = "{",
  [anon_sym_RBRACE] = "}",
  [anon_sym_LPAREN] = "(",
  [anon_sym_RPAREN] = ")",
  [anon_sym_LBRACK] = "[",
  [anon_sym_RBRACK] = "]",
  [anon_sym_do] = "do",
  [anon_sym_end] = "end",
  [sym_sigil] = "sigil",
  [sym_send] = "send",
  [sym_message] = "message",
  [sym_singlestring] = "singlestring",
  [sym_doublestring] = "doublestring",
  [sym_comment] = "comment",
  [sym_operator] = "operator",
  [sym__newline] = "_newline",
  [sym_number] = "number",
  [sym_source_file] = "source_file",
  [sym__expression] = "_expression",
  [sym_unary] = "unary",
  [sym_binary] = "binary",
  [sym_special_send] = "special_send",
  [sym_record] = "record",
  [sym_tuple] = "tuple",
  [sym_list] = "list",
  [sym_block] = "block",
  [sym_string] = "string",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_record_repeat1] = "record_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [sym_symbol] = sym_symbol,
  [anon_sym_EQ_GT] = anon_sym_EQ_GT,
  [anon_sym_EQ] = anon_sym_EQ,
  [anon_sym_LBRACE] = anon_sym_LBRACE,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [anon_sym_LBRACK] = anon_sym_LBRACK,
  [anon_sym_RBRACK] = anon_sym_RBRACK,
  [anon_sym_do] = anon_sym_do,
  [anon_sym_end] = anon_sym_end,
  [sym_sigil] = sym_sigil,
  [sym_send] = sym_send,
  [sym_message] = sym_message,
  [sym_singlestring] = sym_singlestring,
  [sym_doublestring] = sym_doublestring,
  [sym_comment] = sym_comment,
  [sym_operator] = sym_operator,
  [sym__newline] = sym__newline,
  [sym_number] = sym_number,
  [sym_source_file] = sym_source_file,
  [sym__expression] = sym__expression,
  [sym_unary] = sym_unary,
  [sym_binary] = sym_binary,
  [sym_special_send] = sym_special_send,
  [sym_record] = sym_record,
  [sym_tuple] = sym_tuple,
  [sym_list] = sym_list,
  [sym_block] = sym_block,
  [sym_string] = sym_string,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_record_repeat1] = aux_sym_record_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [sym_symbol] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_EQ_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_do] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_end] = {
    .visible = true,
    .named = false,
  },
  [sym_sigil] = {
    .visible = true,
    .named = true,
  },
  [sym_send] = {
    .visible = true,
    .named = true,
  },
  [sym_message] = {
    .visible = true,
    .named = true,
  },
  [sym_singlestring] = {
    .visible = true,
    .named = true,
  },
  [sym_doublestring] = {
    .visible = true,
    .named = true,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [sym_operator] = {
    .visible = true,
    .named = true,
  },
  [sym__newline] = {
    .visible = false,
    .named = true,
  },
  [sym_number] = {
    .visible = true,
    .named = true,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym__expression] = {
    .visible = false,
    .named = true,
  },
  [sym_unary] = {
    .visible = true,
    .named = true,
  },
  [sym_binary] = {
    .visible = true,
    .named = true,
  },
  [sym_special_send] = {
    .visible = true,
    .named = true,
  },
  [sym_record] = {
    .visible = true,
    .named = true,
  },
  [sym_tuple] = {
    .visible = true,
    .named = true,
  },
  [sym_list] = {
    .visible = true,
    .named = true,
  },
  [sym_block] = {
    .visible = true,
    .named = true,
  },
  [sym_string] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_record_repeat1] = {
    .visible = false,
    .named = false,
  },
};

enum ts_field_identifiers {
  field_lhs = 1,
  field_message = 2,
  field_rhs = 3,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_lhs] = "lhs",
  [field_message] = "message",
  [field_rhs] = "rhs",
};

static const TSFieldMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 2},
  [2] = {.index = 2, .length = 3},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_lhs, 0},
    {field_message, 1},
  [2] =
    {field_lhs, 0},
    {field_message, 1},
    {field_rhs, 2},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 2,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 6,
  [12] = 12,
  [13] = 9,
  [14] = 14,
  [15] = 8,
  [16] = 16,
  [17] = 7,
  [18] = 18,
  [19] = 5,
  [20] = 18,
  [21] = 12,
  [22] = 22,
  [23] = 14,
  [24] = 16,
  [25] = 25,
  [26] = 25,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 37,
  [40] = 28,
  [41] = 31,
  [42] = 36,
  [43] = 30,
  [44] = 29,
  [45] = 27,
  [46] = 46,
  [47] = 35,
  [48] = 34,
  [49] = 33,
  [50] = 32,
  [51] = 38,
  [52] = 52,
};

static TSCharacterRange sym_send_character_set_2[] = {
  {'!', '!'}, {'$', '&'}, {'*', '+'}, {'-', '-'}, {'/', '/'}, {'<', '@'}, {'^', '^'}, {'|', '|'},
  {'~', '~'},
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(6);
      ADVANCE_MAP(
        '\n', 31,
        '"', 1,
        '#', 26,
        '\'', 2,
        '(', 11,
        ')', 12,
        '.', 5,
        ':', 4,
        '=', 8,
        '[', 13,
        '\\', 23,
        ']', 14,
        '{', 9,
        '}', 10,
        ',', 30,
        ';', 30,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(33);
      if (('!' <= lookahead && lookahead <= '@') ||
          lookahead == '^' ||
          ('|' <= lookahead && lookahead <= '~')) ADVANCE(27);
      if (('A' <= lookahead && lookahead <= '_') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(29);
      END_STATE();
    case 1:
      if (lookahead == '"') ADVANCE(25);
      if (lookahead != 0) ADVANCE(1);
      END_STATE();
    case 2:
      if (lookahead == '\'') ADVANCE(24);
      if (lookahead != 0) ADVANCE(2);
      END_STATE();
    case 3:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(32);
      END_STATE();
    case 4:
      if (set_contains(sym_send_character_set_2, 9, lookahead)) ADVANCE(19);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(18);
      END_STATE();
    case 5:
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(16);
      END_STATE();
    case 6:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 7:
      ACCEPT_TOKEN(anon_sym_EQ_GT);
      if (set_contains(sym_send_character_set_2, 9, lookahead)) ADVANCE(27);
      END_STATE();
    case 8:
      ACCEPT_TOKEN(anon_sym_EQ);
      if (lookahead == '>') ADVANCE(7);
      if (set_contains(sym_send_character_set_2, 9, lookahead)) ADVANCE(27);
      END_STATE();
    case 9:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      END_STATE();
    case 10:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 11:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 12:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 13:
      ACCEPT_TOKEN(anon_sym_LBRACK);
      END_STATE();
    case 14:
      ACCEPT_TOKEN(anon_sym_RBRACK);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(sym_sigil);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(sym_sigil);
      if (lookahead == '!' ||
          lookahead == '?') ADVANCE(15);
      if (lookahead == '.' ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(16);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(sym_send);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(sym_send);
      if (lookahead == '!' ||
          lookahead == '?') ADVANCE(17);
      if (lookahead == '.' ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(18);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(sym_send);
      if (set_contains(sym_send_character_set_2, 9, lookahead)) ADVANCE(19);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(sym_message);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(sym_message);
      if (lookahead == '!' ||
          lookahead == '?') ADVANCE(20);
      if (lookahead == '.' ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(21);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(sym_message);
      if (set_contains(sym_send_character_set_2, 9, lookahead)) ADVANCE(22);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(sym_message);
      if (set_contains(sym_send_character_set_2, 9, lookahead)) ADVANCE(22);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(21);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(sym_singlestring);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(sym_doublestring);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(26);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(sym_operator);
      if (set_contains(sym_send_character_set_2, 9, lookahead)) ADVANCE(27);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(sym_symbol);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(sym_symbol);
      if (lookahead == '!' ||
          lookahead == '?') ADVANCE(28);
      if (lookahead == '.' ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(29);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(sym__newline);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(sym__newline);
      if (lookahead == '\n') ADVANCE(31);
      if (lookahead == ',' ||
          lookahead == ';') ADVANCE(30);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(sym_number);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(sym_number);
      if (lookahead == '.') ADVANCE(3);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(33);
      END_STATE();
    default:
      return false;
  }
}

static bool ts_lex_keywords(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (lookahead == 'd') ADVANCE(1);
      if (lookahead == 'e') ADVANCE(2);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      END_STATE();
    case 1:
      if (lookahead == 'o') ADVANCE(3);
      END_STATE();
    case 2:
      if (lookahead == 'n') ADVANCE(4);
      END_STATE();
    case 3:
      ACCEPT_TOKEN(anon_sym_do);
      END_STATE();
    case 4:
      if (lookahead == 'd') ADVANCE(5);
      END_STATE();
    case 5:
      ACCEPT_TOKEN(anon_sym_end);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 0},
  [2] = {.lex_state = 0},
  [3] = {.lex_state = 0},
  [4] = {.lex_state = 0},
  [5] = {.lex_state = 0},
  [6] = {.lex_state = 0},
  [7] = {.lex_state = 0},
  [8] = {.lex_state = 0},
  [9] = {.lex_state = 0},
  [10] = {.lex_state = 0},
  [11] = {.lex_state = 0},
  [12] = {.lex_state = 0},
  [13] = {.lex_state = 0},
  [14] = {.lex_state = 0},
  [15] = {.lex_state = 0},
  [16] = {.lex_state = 0},
  [17] = {.lex_state = 0},
  [18] = {.lex_state = 0},
  [19] = {.lex_state = 0},
  [20] = {.lex_state = 0},
  [21] = {.lex_state = 0},
  [22] = {.lex_state = 0},
  [23] = {.lex_state = 0},
  [24] = {.lex_state = 0},
  [25] = {.lex_state = 0},
  [26] = {.lex_state = 0},
  [27] = {.lex_state = 0},
  [28] = {.lex_state = 0},
  [29] = {.lex_state = 0},
  [30] = {.lex_state = 0},
  [31] = {.lex_state = 0},
  [32] = {.lex_state = 0},
  [33] = {.lex_state = 0},
  [34] = {.lex_state = 0},
  [35] = {.lex_state = 0},
  [36] = {.lex_state = 0},
  [37] = {.lex_state = 0},
  [38] = {.lex_state = 0},
  [39] = {.lex_state = 0},
  [40] = {.lex_state = 0},
  [41] = {.lex_state = 0},
  [42] = {.lex_state = 0},
  [43] = {.lex_state = 0},
  [44] = {.lex_state = 0},
  [45] = {.lex_state = 0},
  [46] = {.lex_state = 0},
  [47] = {.lex_state = 0},
  [48] = {.lex_state = 0},
  [49] = {.lex_state = 0},
  [50] = {.lex_state = 0},
  [51] = {.lex_state = 0},
  [52] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [0] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [sym_symbol] = ACTIONS(1),
    [anon_sym_EQ_GT] = ACTIONS(1),
    [anon_sym_EQ] = ACTIONS(1),
    [anon_sym_LBRACE] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [anon_sym_LBRACK] = ACTIONS(1),
    [anon_sym_RBRACK] = ACTIONS(1),
    [anon_sym_do] = ACTIONS(1),
    [anon_sym_end] = ACTIONS(1),
    [sym_sigil] = ACTIONS(1),
    [sym_send] = ACTIONS(1),
    [sym_message] = ACTIONS(1),
    [sym_singlestring] = ACTIONS(1),
    [sym_doublestring] = ACTIONS(1),
    [sym_comment] = ACTIONS(3),
    [sym_operator] = ACTIONS(1),
    [sym__newline] = ACTIONS(5),
    [sym_number] = ACTIONS(1),
  },
  [1] = {
    [sym_source_file] = STATE(52),
    [sym__expression] = STATE(51),
    [sym_unary] = STATE(51),
    [sym_binary] = STATE(51),
    [sym_special_send] = STATE(51),
    [sym_record] = STATE(51),
    [sym_tuple] = STATE(51),
    [sym_list] = STATE(51),
    [sym_block] = STATE(51),
    [sym_string] = STATE(51),
    [aux_sym_source_file_repeat1] = STATE(10),
    [ts_builtin_sym_end] = ACTIONS(7),
    [sym_symbol] = ACTIONS(9),
    [anon_sym_LBRACE] = ACTIONS(11),
    [anon_sym_LPAREN] = ACTIONS(13),
    [anon_sym_LBRACK] = ACTIONS(15),
    [anon_sym_do] = ACTIONS(17),
    [sym_sigil] = ACTIONS(9),
    [sym_message] = ACTIONS(9),
    [sym_singlestring] = ACTIONS(19),
    [sym_doublestring] = ACTIONS(19),
    [sym_comment] = ACTIONS(3),
    [sym__newline] = ACTIONS(5),
    [sym_number] = ACTIONS(9),
  },
  [2] = {
    [sym__expression] = STATE(29),
    [sym_unary] = STATE(29),
    [sym_binary] = STATE(29),
    [sym_special_send] = STATE(29),
    [sym_record] = STATE(29),
    [sym_tuple] = STATE(29),
    [sym_list] = STATE(29),
    [sym_block] = STATE(29),
    [sym_string] = STATE(29),
    [sym_symbol] = ACTIONS(21),
    [anon_sym_EQ_GT] = ACTIONS(23),
    [anon_sym_EQ] = ACTIONS(23),
    [anon_sym_LBRACE] = ACTIONS(25),
    [anon_sym_RBRACE] = ACTIONS(23),
    [anon_sym_LPAREN] = ACTIONS(27),
    [anon_sym_RPAREN] = ACTIONS(23),
    [anon_sym_LBRACK] = ACTIONS(29),
    [anon_sym_RBRACK] = ACTIONS(23),
    [anon_sym_do] = ACTIONS(31),
    [anon_sym_end] = ACTIONS(23),
    [sym_sigil] = ACTIONS(21),
    [sym_send] = ACTIONS(23),
    [sym_message] = ACTIONS(21),
    [sym_singlestring] = ACTIONS(33),
    [sym_doublestring] = ACTIONS(33),
    [sym_comment] = ACTIONS(3),
    [sym_operator] = ACTIONS(23),
    [sym__newline] = ACTIONS(5),
    [sym_number] = ACTIONS(21),
  },
  [3] = {
    [sym__expression] = STATE(44),
    [sym_unary] = STATE(44),
    [sym_binary] = STATE(44),
    [sym_special_send] = STATE(44),
    [sym_record] = STATE(44),
    [sym_tuple] = STATE(44),
    [sym_list] = STATE(44),
    [sym_block] = STATE(44),
    [sym_string] = STATE(44),
    [ts_builtin_sym_end] = ACTIONS(35),
    [sym_symbol] = ACTIONS(37),
    [anon_sym_EQ_GT] = ACTIONS(23),
    [anon_sym_EQ] = ACTIONS(23),
    [anon_sym_LBRACE] = ACTIONS(11),
    [anon_sym_LPAREN] = ACTIONS(13),
    [anon_sym_LBRACK] = ACTIONS(15),
    [anon_sym_do] = ACTIONS(17),
    [sym_sigil] = ACTIONS(37),
    [sym_send] = ACTIONS(23),
    [sym_message] = ACTIONS(37),
    [sym_singlestring] = ACTIONS(19),
    [sym_doublestring] = ACTIONS(19),
    [sym_comment] = ACTIONS(3),
    [sym_operator] = ACTIONS(23),
    [sym__newline] = ACTIONS(5),
    [sym_number] = ACTIONS(37),
  },
  [4] = {
    [sym__expression] = STATE(46),
    [sym_unary] = STATE(46),
    [sym_binary] = STATE(46),
    [sym_special_send] = STATE(46),
    [sym_record] = STATE(46),
    [sym_tuple] = STATE(46),
    [sym_list] = STATE(46),
    [sym_block] = STATE(46),
    [sym_string] = STATE(46),
    [sym_symbol] = ACTIONS(39),
    [anon_sym_EQ_GT] = ACTIONS(41),
    [anon_sym_EQ] = ACTIONS(41),
    [anon_sym_LBRACE] = ACTIONS(25),
    [anon_sym_LPAREN] = ACTIONS(27),
    [anon_sym_LBRACK] = ACTIONS(29),
    [anon_sym_do] = ACTIONS(31),
    [sym_sigil] = ACTIONS(39),
    [sym_send] = ACTIONS(43),
    [sym_message] = ACTIONS(39),
    [sym_singlestring] = ACTIONS(33),
    [sym_doublestring] = ACTIONS(33),
    [sym_comment] = ACTIONS(3),
    [sym_operator] = ACTIONS(43),
    [sym__newline] = ACTIONS(5),
    [sym_number] = ACTIONS(39),
  },
  [5] = {
    [sym__expression] = STATE(38),
    [sym_unary] = STATE(38),
    [sym_binary] = STATE(38),
    [sym_special_send] = STATE(38),
    [sym_record] = STATE(38),
    [sym_tuple] = STATE(38),
    [sym_list] = STATE(38),
    [sym_block] = STATE(38),
    [sym_string] = STATE(38),
    [aux_sym_source_file_repeat1] = STATE(5),
    [sym_symbol] = ACTIONS(45),
    [anon_sym_LBRACE] = ACTIONS(48),
    [anon_sym_LPAREN] = ACTIONS(51),
    [anon_sym_RPAREN] = ACTIONS(54),
    [anon_sym_LBRACK] = ACTIONS(56),
    [anon_sym_RBRACK] = ACTIONS(54),
    [anon_sym_do] = ACTIONS(59),
    [anon_sym_end] = ACTIONS(54),
    [sym_sigil] = ACTIONS(45),
    [sym_message] = ACTIONS(45),
    [sym_singlestring] = ACTIONS(62),
    [sym_doublestring] = ACTIONS(62),
    [sym_comment] = ACTIONS(3),
    [sym__newline] = ACTIONS(5),
    [sym_number] = ACTIONS(45),
  },
  [6] = {
    [sym__expression] = STATE(4),
    [sym_unary] = STATE(4),
    [sym_binary] = STATE(4),
    [sym_special_send] = STATE(4),
    [sym_record] = STATE(4),
    [sym_tuple] = STATE(4),
    [sym_list] = STATE(4),
    [sym_block] = STATE(4),
    [sym_string] = STATE(4),
    [aux_sym_record_repeat1] = STATE(22),
    [sym_symbol] = ACTIONS(65),
    [anon_sym_LBRACE] = ACTIONS(25),
    [anon_sym_RBRACE] = ACTIONS(67),
    [anon_sym_LPAREN] = ACTIONS(27),
    [anon_sym_LBRACK] = ACTIONS(29),
    [anon_sym_do] = ACTIONS(31),
    [sym_sigil] = ACTIONS(65),
    [sym_message] = ACTIONS(65),
    [sym_singlestring] = ACTIONS(33),
    [sym_doublestring] = ACTIONS(33),
    [sym_comment] = ACTIONS(3),
    [sym__newline] = ACTIONS(5),
    [sym_number] = ACTIONS(65),
  },
  [7] = {
    [sym__expression] = STATE(38),
    [sym_unary] = STATE(38),
    [sym_binary] = STATE(38),
    [sym_special_send] = STATE(38),
    [sym_record] = STATE(38),
    [sym_tuple] = STATE(38),
    [sym_list] = STATE(38),
    [sym_block] = STATE(38),
    [sym_string] = STATE(38),
    [aux_sym_source_file_repeat1] = STATE(5),
    [sym_symbol] = ACTIONS(69),
    [anon_sym_LBRACE] = ACTIONS(25),
    [anon_sym_LPAREN] = ACTIONS(27),
    [anon_sym_LBRACK] = ACTIONS(29),
    [anon_sym_do] = ACTIONS(31),
    [anon_sym_end] = ACTIONS(71),
    [sym_sigil] = ACTIONS(69),
    [sym_message] = ACTIONS(69),
    [sym_singlestring] = ACTIONS(33),
    [sym_doublestring] = ACTIONS(33),
    [sym_comment] = ACTIONS(3),
    [sym__newline] = ACTIONS(5),
    [sym_number] = ACTIONS(69),
  },
  [8] = {
    [sym__expression] = STATE(38),
    [sym_unary] = STATE(38),
    [sym_binary] = STATE(38),
    [sym_special_send] = STATE(38),
    [sym_record] = STATE(38),
    [sym_tuple] = STATE(38),
    [sym_list] = STATE(38),
    [sym_block] = STATE(38),
    [sym_string] = STATE(38),
    [aux_sym_source_file_repeat1] = STATE(5),
    [sym_symbol] = ACTIONS(69),
    [anon_sym_LBRACE] = ACTIONS(25),
    [anon_sym_LPAREN] = ACTIONS(27),
    [anon_sym_LBRACK] = ACTIONS(29),
    [anon_sym_RBRACK] = ACTIONS(73),
    [anon_sym_do] = ACTIONS(31),
    [sym_sigil] = ACTIONS(69),
    [sym_message] = ACTIONS(69),
    [sym_singlestring] = ACTIONS(33),
    [sym_doublestring] = ACTIONS(33),
    [sym_comment] = ACTIONS(3),
    [sym__newline] = ACTIONS(5),
    [sym_number] = ACTIONS(69),
  },
  [9] = {
    [sym__expression] = STATE(38),
    [sym_unary] = STATE(38),
    [sym_binary] = STATE(38),
    [sym_special_send] = STATE(38),
    [sym_record] = STATE(38),
    [sym_tuple] = STATE(38),
    [sym_list] = STATE(38),
    [sym_block] = STATE(38),
    [sym_string] = STATE(38),
    [aux_sym_source_file_repeat1] = STATE(5),
    [sym_symbol] = ACTIONS(69),
    [anon_sym_LBRACE] = ACTIONS(25),
    [anon_sym_LPAREN] = ACTIONS(27),
    [anon_sym_RPAREN] = ACTIONS(75),
    [anon_sym_LBRACK] = ACTIONS(29),
    [anon_sym_do] = ACTIONS(31),
    [sym_sigil] = ACTIONS(69),
    [sym_message] = ACTIONS(69),
    [sym_singlestring] = ACTIONS(33),
    [sym_doublestring] = ACTIONS(33),
    [sym_comment] = ACTIONS(3),
    [sym__newline] = ACTIONS(5),
    [sym_number] = ACTIONS(69),
  },
  [10] = {
    [sym__expression] = STATE(51),
    [sym_unary] = STATE(51),
    [sym_binary] = STATE(51),
    [sym_special_send] = STATE(51),
    [sym_record] = STATE(51),
    [sym_tuple] = STATE(51),
    [sym_list] = STATE(51),
    [sym_block] = STATE(51),
    [sym_string] = STATE(51),
    [aux_sym_source_file_repeat1] = STATE(19),
    [ts_builtin_sym_end] = ACTIONS(77),
    [sym_symbol] = ACTIONS(9),
    [anon_sym_LBRACE] = ACTIONS(11),
    [anon_sym_LPAREN] = ACTIONS(13),
    [anon_sym_LBRACK] = ACTIONS(15),
    [anon_sym_do] = ACTIONS(17),
    [sym_sigil] = ACTIONS(9),
    [sym_message] = ACTIONS(9),
    [sym_singlestring] = ACTIONS(19),
    [sym_doublestring] = ACTIONS(19),
    [sym_comment] = ACTIONS(3),
    [sym__newline] = ACTIONS(5),
    [sym_number] = ACTIONS(9),
  },
  [11] = {
    [sym__expression] = STATE(4),
    [sym_unary] = STATE(4),
    [sym_binary] = STATE(4),
    [sym_special_send] = STATE(4),
    [sym_record] = STATE(4),
    [sym_tuple] = STATE(4),
    [sym_list] = STATE(4),
    [sym_block] = STATE(4),
    [sym_string] = STATE(4),
    [aux_sym_record_repeat1] = STATE(22),
    [sym_symbol] = ACTIONS(65),
    [anon_sym_LBRACE] = ACTIONS(25),
    [anon_sym_RBRACE] = ACTIONS(79),
    [anon_sym_LPAREN] = ACTIONS(27),
    [anon_sym_LBRACK] = ACTIONS(29),
    [anon_sym_do] = ACTIONS(31),
    [sym_sigil] = ACTIONS(65),
    [sym_message] = ACTIONS(65),
    [sym_singlestring] = ACTIONS(33),
    [sym_doublestring] = ACTIONS(33),
    [sym_comment] = ACTIONS(3),
    [sym__newline] = ACTIONS(5),
    [sym_number] = ACTIONS(65),
  },
  [12] = {
    [sym__expression] = STATE(38),
    [sym_unary] = STATE(38),
    [sym_binary] = STATE(38),
    [sym_special_send] = STATE(38),
    [sym_record] = STATE(38),
    [sym_tuple] = STATE(38),
    [sym_list] = STATE(38),
    [sym_block] = STATE(38),
    [sym_string] = STATE(38),
    [aux_sym_source_file_repeat1] = STATE(7),
    [sym_symbol] = ACTIONS(69),
    [anon_sym_LBRACE] = ACTIONS(25),
    [anon_sym_LPAREN] = ACTIONS(27),
    [anon_sym_LBRACK] = ACTIONS(29),
    [anon_sym_do] = ACTIONS(31),
    [anon_sym_end] = ACTIONS(81),
    [sym_sigil] = ACTIONS(69),
    [sym_message] = ACTIONS(69),
    [sym_singlestring] = ACTIONS(33),
    [sym_doublestring] = ACTIONS(33),
    [sym_comment] = ACTIONS(3),
    [sym__newline] = ACTIONS(5),
    [sym_number] = ACTIONS(69),
  },
  [13] = {
    [sym__expression] = STATE(38),
    [sym_unary] = STATE(38),
    [sym_binary] = STATE(38),
    [sym_special_send] = STATE(38),
    [sym_record] = STATE(38),
    [sym_tuple] = STATE(38),
    [sym_list] = STATE(38),
    [sym_block] = STATE(38),
    [sym_string] = STATE(38),
    [aux_sym_source_file_repeat1] = STATE(5),
    [sym_symbol] = ACTIONS(69),
    [anon_sym_LBRACE] = ACTIONS(25),
    [anon_sym_LPAREN] = ACTIONS(27),
    [anon_sym_RPAREN] = ACTIONS(83),
    [anon_sym_LBRACK] = ACTIONS(29),
    [anon_sym_do] = ACTIONS(31),
    [sym_sigil] = ACTIONS(69),
    [sym_message] = ACTIONS(69),
    [sym_singlestring] = ACTIONS(33),
    [sym_doublestring] = ACTIONS(33),
    [sym_comment] = ACTIONS(3),
    [sym__newline] = ACTIONS(5),
    [sym_number] = ACTIONS(69),
  },
  [14] = {
    [sym__expression] = STATE(38),
    [sym_unary] = STATE(38),
    [sym_binary] = STATE(38),
    [sym_special_send] = STATE(38),
    [sym_record] = STATE(38),
    [sym_tuple] = STATE(38),
    [sym_list] = STATE(38),
    [sym_block] = STATE(38),
    [sym_string] = STATE(38),
    [aux_sym_source_file_repeat1] = STATE(8),
    [sym_symbol] = ACTIONS(69),
    [anon_sym_LBRACE] = ACTIONS(25),
    [anon_sym_LPAREN] = ACTIONS(27),
    [anon_sym_LBRACK] = ACTIONS(29),
    [anon_sym_RBRACK] = ACTIONS(85),
    [anon_sym_do] = ACTIONS(31),
    [sym_sigil] = ACTIONS(69),
    [sym_message] = ACTIONS(69),
    [sym_singlestring] = ACTIONS(33),
    [sym_doublestring] = ACTIONS(33),
    [sym_comment] = ACTIONS(3),
    [sym__newline] = ACTIONS(5),
    [sym_number] = ACTIONS(69),
  },
  [15] = {
    [sym__expression] = STATE(38),
    [sym_unary] = STATE(38),
    [sym_binary] = STATE(38),
    [sym_special_send] = STATE(38),
    [sym_record] = STATE(38),
    [sym_tuple] = STATE(38),
    [sym_list] = STATE(38),
    [sym_block] = STATE(38),
    [sym_string] = STATE(38),
    [aux_sym_source_file_repeat1] = STATE(5),
    [sym_symbol] = ACTIONS(69),
    [anon_sym_LBRACE] = ACTIONS(25),
    [anon_sym_LPAREN] = ACTIONS(27),
    [anon_sym_LBRACK] = ACTIONS(29),
    [anon_sym_RBRACK] = ACTIONS(87),
    [anon_sym_do] = ACTIONS(31),
    [sym_sigil] = ACTIONS(69),
    [sym_message] = ACTIONS(69),
    [sym_singlestring] = ACTIONS(33),
    [sym_doublestring] = ACTIONS(33),
    [sym_comment] = ACTIONS(3),
    [sym__newline] = ACTIONS(5),
    [sym_number] = ACTIONS(69),
  },
  [16] = {
    [sym__expression] = STATE(38),
    [sym_unary] = STATE(38),
    [sym_binary] = STATE(38),
    [sym_special_send] = STATE(38),
    [sym_record] = STATE(38),
    [sym_tuple] = STATE(38),
    [sym_list] = STATE(38),
    [sym_block] = STATE(38),
    [sym_string] = STATE(38),
    [aux_sym_source_file_repeat1] = STATE(9),
    [sym_symbol] = ACTIONS(69),
    [anon_sym_LBRACE] = ACTIONS(25),
    [anon_sym_LPAREN] = ACTIONS(27),
    [anon_sym_RPAREN] = ACTIONS(89),
    [anon_sym_LBRACK] = ACTIONS(29),
    [anon_sym_do] = ACTIONS(31),
    [sym_sigil] = ACTIONS(69),
    [sym_message] = ACTIONS(69),
    [sym_singlestring] = ACTIONS(33),
    [sym_doublestring] = ACTIONS(33),
    [sym_comment] = ACTIONS(3),
    [sym__newline] = ACTIONS(5),
    [sym_number] = ACTIONS(69),
  },
  [17] = {
    [sym__expression] = STATE(38),
    [sym_unary] = STATE(38),
    [sym_binary] = STATE(38),
    [sym_special_send] = STATE(38),
    [sym_record] = STATE(38),
    [sym_tuple] = STATE(38),
    [sym_list] = STATE(38),
    [sym_block] = STATE(38),
    [sym_string] = STATE(38),
    [aux_sym_source_file_repeat1] = STATE(5),
    [sym_symbol] = ACTIONS(69),
    [anon_sym_LBRACE] = ACTIONS(25),
    [anon_sym_LPAREN] = ACTIONS(27),
    [anon_sym_LBRACK] = ACTIONS(29),
    [anon_sym_do] = ACTIONS(31),
    [anon_sym_end] = ACTIONS(91),
    [sym_sigil] = ACTIONS(69),
    [sym_message] = ACTIONS(69),
    [sym_singlestring] = ACTIONS(33),
    [sym_doublestring] = ACTIONS(33),
    [sym_comment] = ACTIONS(3),
    [sym__newline] = ACTIONS(5),
    [sym_number] = ACTIONS(69),
  },
  [18] = {
    [sym__expression] = STATE(4),
    [sym_unary] = STATE(4),
    [sym_binary] = STATE(4),
    [sym_special_send] = STATE(4),
    [sym_record] = STATE(4),
    [sym_tuple] = STATE(4),
    [sym_list] = STATE(4),
    [sym_block] = STATE(4),
    [sym_string] = STATE(4),
    [aux_sym_record_repeat1] = STATE(6),
    [sym_symbol] = ACTIONS(65),
    [anon_sym_LBRACE] = ACTIONS(25),
    [anon_sym_RBRACE] = ACTIONS(93),
    [anon_sym_LPAREN] = ACTIONS(27),
    [anon_sym_LBRACK] = ACTIONS(29),
    [anon_sym_do] = ACTIONS(31),
    [sym_sigil] = ACTIONS(65),
    [sym_message] = ACTIONS(65),
    [sym_singlestring] = ACTIONS(33),
    [sym_doublestring] = ACTIONS(33),
    [sym_comment] = ACTIONS(3),
    [sym__newline] = ACTIONS(5),
    [sym_number] = ACTIONS(65),
  },
  [19] = {
    [sym__expression] = STATE(51),
    [sym_unary] = STATE(51),
    [sym_binary] = STATE(51),
    [sym_special_send] = STATE(51),
    [sym_record] = STATE(51),
    [sym_tuple] = STATE(51),
    [sym_list] = STATE(51),
    [sym_block] = STATE(51),
    [sym_string] = STATE(51),
    [aux_sym_source_file_repeat1] = STATE(19),
    [ts_builtin_sym_end] = ACTIONS(95),
    [sym_symbol] = ACTIONS(97),
    [anon_sym_LBRACE] = ACTIONS(100),
    [anon_sym_LPAREN] = ACTIONS(103),
    [anon_sym_LBRACK] = ACTIONS(106),
    [anon_sym_do] = ACTIONS(109),
    [sym_sigil] = ACTIONS(97),
    [sym_message] = ACTIONS(97),
    [sym_singlestring] = ACTIONS(112),
    [sym_doublestring] = ACTIONS(112),
    [sym_comment] = ACTIONS(3),
    [sym__newline] = ACTIONS(5),
    [sym_number] = ACTIONS(97),
  },
  [20] = {
    [sym__expression] = STATE(4),
    [sym_unary] = STATE(4),
    [sym_binary] = STATE(4),
    [sym_special_send] = STATE(4),
    [sym_record] = STATE(4),
    [sym_tuple] = STATE(4),
    [sym_list] = STATE(4),
    [sym_block] = STATE(4),
    [sym_string] = STATE(4),
    [aux_sym_record_repeat1] = STATE(11),
    [sym_symbol] = ACTIONS(65),
    [anon_sym_LBRACE] = ACTIONS(25),
    [anon_sym_RBRACE] = ACTIONS(115),
    [anon_sym_LPAREN] = ACTIONS(27),
    [anon_sym_LBRACK] = ACTIONS(29),
    [anon_sym_do] = ACTIONS(31),
    [sym_sigil] = ACTIONS(65),
    [sym_message] = ACTIONS(65),
    [sym_singlestring] = ACTIONS(33),
    [sym_doublestring] = ACTIONS(33),
    [sym_comment] = ACTIONS(3),
    [sym__newline] = ACTIONS(5),
    [sym_number] = ACTIONS(65),
  },
  [21] = {
    [sym__expression] = STATE(38),
    [sym_unary] = STATE(38),
    [sym_binary] = STATE(38),
    [sym_special_send] = STATE(38),
    [sym_record] = STATE(38),
    [sym_tuple] = STATE(38),
    [sym_list] = STATE(38),
    [sym_block] = STATE(38),
    [sym_string] = STATE(38),
    [aux_sym_source_file_repeat1] = STATE(17),
    [sym_symbol] = ACTIONS(69),
    [anon_sym_LBRACE] = ACTIONS(25),
    [anon_sym_LPAREN] = ACTIONS(27),
    [anon_sym_LBRACK] = ACTIONS(29),
    [anon_sym_do] = ACTIONS(31),
    [anon_sym_end] = ACTIONS(117),
    [sym_sigil] = ACTIONS(69),
    [sym_message] = ACTIONS(69),
    [sym_singlestring] = ACTIONS(33),
    [sym_doublestring] = ACTIONS(33),
    [sym_comment] = ACTIONS(3),
    [sym__newline] = ACTIONS(5),
    [sym_number] = ACTIONS(69),
  },
  [22] = {
    [sym__expression] = STATE(4),
    [sym_unary] = STATE(4),
    [sym_binary] = STATE(4),
    [sym_special_send] = STATE(4),
    [sym_record] = STATE(4),
    [sym_tuple] = STATE(4),
    [sym_list] = STATE(4),
    [sym_block] = STATE(4),
    [sym_string] = STATE(4),
    [aux_sym_record_repeat1] = STATE(22),
    [sym_symbol] = ACTIONS(119),
    [anon_sym_LBRACE] = ACTIONS(122),
    [anon_sym_RBRACE] = ACTIONS(125),
    [anon_sym_LPAREN] = ACTIONS(127),
    [anon_sym_LBRACK] = ACTIONS(130),
    [anon_sym_do] = ACTIONS(133),
    [sym_sigil] = ACTIONS(119),
    [sym_message] = ACTIONS(119),
    [sym_singlestring] = ACTIONS(136),
    [sym_doublestring] = ACTIONS(136),
    [sym_comment] = ACTIONS(3),
    [sym__newline] = ACTIONS(5),
    [sym_number] = ACTIONS(119),
  },
  [23] = {
    [sym__expression] = STATE(38),
    [sym_unary] = STATE(38),
    [sym_binary] = STATE(38),
    [sym_special_send] = STATE(38),
    [sym_record] = STATE(38),
    [sym_tuple] = STATE(38),
    [sym_list] = STATE(38),
    [sym_block] = STATE(38),
    [sym_string] = STATE(38),
    [aux_sym_source_file_repeat1] = STATE(15),
    [sym_symbol] = ACTIONS(69),
    [anon_sym_LBRACE] = ACTIONS(25),
    [anon_sym_LPAREN] = ACTIONS(27),
    [anon_sym_LBRACK] = ACTIONS(29),
    [anon_sym_RBRACK] = ACTIONS(139),
    [anon_sym_do] = ACTIONS(31),
    [sym_sigil] = ACTIONS(69),
    [sym_message] = ACTIONS(69),
    [sym_singlestring] = ACTIONS(33),
    [sym_doublestring] = ACTIONS(33),
    [sym_comment] = ACTIONS(3),
    [sym__newline] = ACTIONS(5),
    [sym_number] = ACTIONS(69),
  },
  [24] = {
    [sym__expression] = STATE(38),
    [sym_unary] = STATE(38),
    [sym_binary] = STATE(38),
    [sym_special_send] = STATE(38),
    [sym_record] = STATE(38),
    [sym_tuple] = STATE(38),
    [sym_list] = STATE(38),
    [sym_block] = STATE(38),
    [sym_string] = STATE(38),
    [aux_sym_source_file_repeat1] = STATE(13),
    [sym_symbol] = ACTIONS(69),
    [anon_sym_LBRACE] = ACTIONS(25),
    [anon_sym_LPAREN] = ACTIONS(27),
    [anon_sym_RPAREN] = ACTIONS(141),
    [anon_sym_LBRACK] = ACTIONS(29),
    [anon_sym_do] = ACTIONS(31),
    [sym_sigil] = ACTIONS(69),
    [sym_message] = ACTIONS(69),
    [sym_singlestring] = ACTIONS(33),
    [sym_doublestring] = ACTIONS(33),
    [sym_comment] = ACTIONS(3),
    [sym__newline] = ACTIONS(5),
    [sym_number] = ACTIONS(69),
  },
  [25] = {
    [sym__expression] = STATE(31),
    [sym_unary] = STATE(31),
    [sym_binary] = STATE(31),
    [sym_special_send] = STATE(31),
    [sym_record] = STATE(31),
    [sym_tuple] = STATE(31),
    [sym_list] = STATE(31),
    [sym_block] = STATE(31),
    [sym_string] = STATE(31),
    [sym_symbol] = ACTIONS(143),
    [anon_sym_LBRACE] = ACTIONS(25),
    [anon_sym_LPAREN] = ACTIONS(27),
    [anon_sym_LBRACK] = ACTIONS(29),
    [anon_sym_do] = ACTIONS(31),
    [sym_sigil] = ACTIONS(143),
    [sym_message] = ACTIONS(143),
    [sym_singlestring] = ACTIONS(33),
    [sym_doublestring] = ACTIONS(33),
    [sym_comment] = ACTIONS(3),
    [sym__newline] = ACTIONS(5),
    [sym_number] = ACTIONS(143),
  },
  [26] = {
    [sym__expression] = STATE(41),
    [sym_unary] = STATE(41),
    [sym_binary] = STATE(41),
    [sym_special_send] = STATE(41),
    [sym_record] = STATE(41),
    [sym_tuple] = STATE(41),
    [sym_list] = STATE(41),
    [sym_block] = STATE(41),
    [sym_string] = STATE(41),
    [sym_symbol] = ACTIONS(145),
    [anon_sym_LBRACE] = ACTIONS(11),
    [anon_sym_LPAREN] = ACTIONS(13),
    [anon_sym_LBRACK] = ACTIONS(15),
    [anon_sym_do] = ACTIONS(17),
    [sym_sigil] = ACTIONS(145),
    [sym_message] = ACTIONS(145),
    [sym_singlestring] = ACTIONS(19),
    [sym_doublestring] = ACTIONS(19),
    [sym_comment] = ACTIONS(3),
    [sym__newline] = ACTIONS(5),
    [sym_number] = ACTIONS(145),
  },
  [27] = {
    [sym_symbol] = ACTIONS(147),
    [anon_sym_EQ_GT] = ACTIONS(147),
    [anon_sym_EQ] = ACTIONS(147),
    [anon_sym_LBRACE] = ACTIONS(147),
    [anon_sym_RBRACE] = ACTIONS(147),
    [anon_sym_LPAREN] = ACTIONS(147),
    [anon_sym_RPAREN] = ACTIONS(147),
    [anon_sym_LBRACK] = ACTIONS(147),
    [anon_sym_RBRACK] = ACTIONS(147),
    [anon_sym_do] = ACTIONS(147),
    [anon_sym_end] = ACTIONS(147),
    [sym_sigil] = ACTIONS(147),
    [sym_send] = ACTIONS(147),
    [sym_message] = ACTIONS(147),
    [sym_singlestring] = ACTIONS(147),
    [sym_doublestring] = ACTIONS(147),
    [sym_comment] = ACTIONS(3),
    [sym_operator] = ACTIONS(147),
    [sym__newline] = ACTIONS(5),
    [sym_number] = ACTIONS(147),
  },
  [28] = {
    [sym_symbol] = ACTIONS(149),
    [anon_sym_EQ_GT] = ACTIONS(149),
    [anon_sym_EQ] = ACTIONS(149),
    [anon_sym_LBRACE] = ACTIONS(149),
    [anon_sym_RBRACE] = ACTIONS(149),
    [anon_sym_LPAREN] = ACTIONS(149),
    [anon_sym_RPAREN] = ACTIONS(149),
    [anon_sym_LBRACK] = ACTIONS(149),
    [anon_sym_RBRACK] = ACTIONS(149),
    [anon_sym_do] = ACTIONS(149),
    [anon_sym_end] = ACTIONS(149),
    [sym_sigil] = ACTIONS(149),
    [sym_send] = ACTIONS(149),
    [sym_message] = ACTIONS(149),
    [sym_singlestring] = ACTIONS(149),
    [sym_doublestring] = ACTIONS(149),
    [sym_comment] = ACTIONS(3),
    [sym_operator] = ACTIONS(149),
    [sym__newline] = ACTIONS(5),
    [sym_number] = ACTIONS(149),
  },
  [29] = {
    [sym_symbol] = ACTIONS(151),
    [anon_sym_EQ_GT] = ACTIONS(41),
    [anon_sym_EQ] = ACTIONS(41),
    [anon_sym_LBRACE] = ACTIONS(151),
    [anon_sym_RBRACE] = ACTIONS(151),
    [anon_sym_LPAREN] = ACTIONS(151),
    [anon_sym_RPAREN] = ACTIONS(151),
    [anon_sym_LBRACK] = ACTIONS(151),
    [anon_sym_RBRACK] = ACTIONS(151),
    [anon_sym_do] = ACTIONS(151),
    [anon_sym_end] = ACTIONS(151),
    [sym_sigil] = ACTIONS(151),
    [sym_send] = ACTIONS(151),
    [sym_message] = ACTIONS(151),
    [sym_singlestring] = ACTIONS(151),
    [sym_doublestring] = ACTIONS(151),
    [sym_comment] = ACTIONS(3),
    [sym_operator] = ACTIONS(151),
    [sym__newline] = ACTIONS(5),
    [sym_number] = ACTIONS(151),
  },
  [30] = {
    [sym_symbol] = ACTIONS(153),
    [anon_sym_EQ_GT] = ACTIONS(153),
    [anon_sym_EQ] = ACTIONS(153),
    [anon_sym_LBRACE] = ACTIONS(153),
    [anon_sym_RBRACE] = ACTIONS(153),
    [anon_sym_LPAREN] = ACTIONS(153),
    [anon_sym_RPAREN] = ACTIONS(153),
    [anon_sym_LBRACK] = ACTIONS(153),
    [anon_sym_RBRACK] = ACTIONS(153),
    [anon_sym_do] = ACTIONS(153),
    [anon_sym_end] = ACTIONS(153),
    [sym_sigil] = ACTIONS(153),
    [sym_send] = ACTIONS(153),
    [sym_message] = ACTIONS(153),
    [sym_singlestring] = ACTIONS(153),
    [sym_doublestring] = ACTIONS(153),
    [sym_comment] = ACTIONS(3),
    [sym_operator] = ACTIONS(153),
    [sym__newline] = ACTIONS(5),
    [sym_number] = ACTIONS(153),
  },
  [31] = {
    [sym_symbol] = ACTIONS(155),
    [anon_sym_EQ_GT] = ACTIONS(155),
    [anon_sym_EQ] = ACTIONS(155),
    [anon_sym_LBRACE] = ACTIONS(155),
    [anon_sym_RBRACE] = ACTIONS(155),
    [anon_sym_LPAREN] = ACTIONS(155),
    [anon_sym_RPAREN] = ACTIONS(155),
    [anon_sym_LBRACK] = ACTIONS(155),
    [anon_sym_RBRACK] = ACTIONS(155),
    [anon_sym_do] = ACTIONS(155),
    [anon_sym_end] = ACTIONS(155),
    [sym_sigil] = ACTIONS(155),
    [sym_send] = ACTIONS(155),
    [sym_message] = ACTIONS(155),
    [sym_singlestring] = ACTIONS(155),
    [sym_doublestring] = ACTIONS(155),
    [sym_comment] = ACTIONS(3),
    [sym_operator] = ACTIONS(155),
    [sym__newline] = ACTIONS(5),
    [sym_number] = ACTIONS(155),
  },
  [32] = {
    [sym_symbol] = ACTIONS(157),
    [anon_sym_EQ_GT] = ACTIONS(157),
    [anon_sym_EQ] = ACTIONS(157),
    [anon_sym_LBRACE] = ACTIONS(157),
    [anon_sym_RBRACE] = ACTIONS(157),
    [anon_sym_LPAREN] = ACTIONS(157),
    [anon_sym_RPAREN] = ACTIONS(157),
    [anon_sym_LBRACK] = ACTIONS(157),
    [anon_sym_RBRACK] = ACTIONS(157),
    [anon_sym_do] = ACTIONS(157),
    [anon_sym_end] = ACTIONS(157),
    [sym_sigil] = ACTIONS(157),
    [sym_send] = ACTIONS(157),
    [sym_message] = ACTIONS(157),
    [sym_singlestring] = ACTIONS(157),
    [sym_doublestring] = ACTIONS(157),
    [sym_comment] = ACTIONS(3),
    [sym_operator] = ACTIONS(157),
    [sym__newline] = ACTIONS(5),
    [sym_number] = ACTIONS(157),
  },
  [33] = {
    [sym_symbol] = ACTIONS(159),
    [anon_sym_EQ_GT] = ACTIONS(159),
    [anon_sym_EQ] = ACTIONS(159),
    [anon_sym_LBRACE] = ACTIONS(159),
    [anon_sym_RBRACE] = ACTIONS(159),
    [anon_sym_LPAREN] = ACTIONS(159),
    [anon_sym_RPAREN] = ACTIONS(159),
    [anon_sym_LBRACK] = ACTIONS(159),
    [anon_sym_RBRACK] = ACTIONS(159),
    [anon_sym_do] = ACTIONS(159),
    [anon_sym_end] = ACTIONS(159),
    [sym_sigil] = ACTIONS(159),
    [sym_send] = ACTIONS(159),
    [sym_message] = ACTIONS(159),
    [sym_singlestring] = ACTIONS(159),
    [sym_doublestring] = ACTIONS(159),
    [sym_comment] = ACTIONS(3),
    [sym_operator] = ACTIONS(159),
    [sym__newline] = ACTIONS(5),
    [sym_number] = ACTIONS(159),
  },
  [34] = {
    [sym_symbol] = ACTIONS(161),
    [anon_sym_EQ_GT] = ACTIONS(161),
    [anon_sym_EQ] = ACTIONS(161),
    [anon_sym_LBRACE] = ACTIONS(161),
    [anon_sym_RBRACE] = ACTIONS(161),
    [anon_sym_LPAREN] = ACTIONS(161),
    [anon_sym_RPAREN] = ACTIONS(161),
    [anon_sym_LBRACK] = ACTIONS(161),
    [anon_sym_RBRACK] = ACTIONS(161),
    [anon_sym_do] = ACTIONS(161),
    [anon_sym_end] = ACTIONS(161),
    [sym_sigil] = ACTIONS(161),
    [sym_send] = ACTIONS(161),
    [sym_message] = ACTIONS(161),
    [sym_singlestring] = ACTIONS(161),
    [sym_doublestring] = ACTIONS(161),
    [sym_comment] = ACTIONS(3),
    [sym_operator] = ACTIONS(161),
    [sym__newline] = ACTIONS(5),
    [sym_number] = ACTIONS(161),
  },
  [35] = {
    [sym_symbol] = ACTIONS(163),
    [anon_sym_EQ_GT] = ACTIONS(163),
    [anon_sym_EQ] = ACTIONS(163),
    [anon_sym_LBRACE] = ACTIONS(163),
    [anon_sym_RBRACE] = ACTIONS(163),
    [anon_sym_LPAREN] = ACTIONS(163),
    [anon_sym_RPAREN] = ACTIONS(163),
    [anon_sym_LBRACK] = ACTIONS(163),
    [anon_sym_RBRACK] = ACTIONS(163),
    [anon_sym_do] = ACTIONS(163),
    [anon_sym_end] = ACTIONS(163),
    [sym_sigil] = ACTIONS(163),
    [sym_send] = ACTIONS(163),
    [sym_message] = ACTIONS(163),
    [sym_singlestring] = ACTIONS(163),
    [sym_doublestring] = ACTIONS(163),
    [sym_comment] = ACTIONS(3),
    [sym_operator] = ACTIONS(163),
    [sym__newline] = ACTIONS(5),
    [sym_number] = ACTIONS(163),
  },
  [36] = {
    [sym_symbol] = ACTIONS(165),
    [anon_sym_EQ_GT] = ACTIONS(165),
    [anon_sym_EQ] = ACTIONS(165),
    [anon_sym_LBRACE] = ACTIONS(165),
    [anon_sym_RBRACE] = ACTIONS(165),
    [anon_sym_LPAREN] = ACTIONS(165),
    [anon_sym_RPAREN] = ACTIONS(165),
    [anon_sym_LBRACK] = ACTIONS(165),
    [anon_sym_RBRACK] = ACTIONS(165),
    [anon_sym_do] = ACTIONS(165),
    [anon_sym_end] = ACTIONS(165),
    [sym_sigil] = ACTIONS(165),
    [sym_send] = ACTIONS(165),
    [sym_message] = ACTIONS(165),
    [sym_singlestring] = ACTIONS(165),
    [sym_doublestring] = ACTIONS(165),
    [sym_comment] = ACTIONS(3),
    [sym_operator] = ACTIONS(165),
    [sym__newline] = ACTIONS(5),
    [sym_number] = ACTIONS(165),
  },
  [37] = {
    [sym_symbol] = ACTIONS(167),
    [anon_sym_EQ_GT] = ACTIONS(167),
    [anon_sym_EQ] = ACTIONS(167),
    [anon_sym_LBRACE] = ACTIONS(167),
    [anon_sym_RBRACE] = ACTIONS(167),
    [anon_sym_LPAREN] = ACTIONS(167),
    [anon_sym_RPAREN] = ACTIONS(167),
    [anon_sym_LBRACK] = ACTIONS(167),
    [anon_sym_RBRACK] = ACTIONS(167),
    [anon_sym_do] = ACTIONS(167),
    [anon_sym_end] = ACTIONS(167),
    [sym_sigil] = ACTIONS(167),
    [sym_send] = ACTIONS(167),
    [sym_message] = ACTIONS(167),
    [sym_singlestring] = ACTIONS(167),
    [sym_doublestring] = ACTIONS(167),
    [sym_comment] = ACTIONS(3),
    [sym_operator] = ACTIONS(167),
    [sym__newline] = ACTIONS(5),
    [sym_number] = ACTIONS(167),
  },
  [38] = {
    [sym_symbol] = ACTIONS(169),
    [anon_sym_EQ_GT] = ACTIONS(41),
    [anon_sym_EQ] = ACTIONS(41),
    [anon_sym_LBRACE] = ACTIONS(169),
    [anon_sym_LPAREN] = ACTIONS(169),
    [anon_sym_RPAREN] = ACTIONS(169),
    [anon_sym_LBRACK] = ACTIONS(169),
    [anon_sym_RBRACK] = ACTIONS(169),
    [anon_sym_do] = ACTIONS(169),
    [anon_sym_end] = ACTIONS(169),
    [sym_sigil] = ACTIONS(169),
    [sym_send] = ACTIONS(43),
    [sym_message] = ACTIONS(169),
    [sym_singlestring] = ACTIONS(169),
    [sym_doublestring] = ACTIONS(169),
    [sym_comment] = ACTIONS(3),
    [sym_operator] = ACTIONS(43),
    [sym__newline] = ACTIONS(5),
    [sym_number] = ACTIONS(169),
  },
  [39] = {
    [ts_builtin_sym_end] = ACTIONS(171),
    [sym_symbol] = ACTIONS(167),
    [anon_sym_EQ_GT] = ACTIONS(167),
    [anon_sym_EQ] = ACTIONS(167),
    [anon_sym_LBRACE] = ACTIONS(167),
    [anon_sym_LPAREN] = ACTIONS(167),
    [anon_sym_LBRACK] = ACTIONS(167),
    [anon_sym_do] = ACTIONS(167),
    [sym_sigil] = ACTIONS(167),
    [sym_send] = ACTIONS(167),
    [sym_message] = ACTIONS(167),
    [sym_singlestring] = ACTIONS(167),
    [sym_doublestring] = ACTIONS(167),
    [sym_comment] = ACTIONS(3),
    [sym_operator] = ACTIONS(167),
    [sym__newline] = ACTIONS(5),
    [sym_number] = ACTIONS(167),
  },
  [40] = {
    [ts_builtin_sym_end] = ACTIONS(173),
    [sym_symbol] = ACTIONS(149),
    [anon_sym_EQ_GT] = ACTIONS(149),
    [anon_sym_EQ] = ACTIONS(149),
    [anon_sym_LBRACE] = ACTIONS(149),
    [anon_sym_LPAREN] = ACTIONS(149),
    [anon_sym_LBRACK] = ACTIONS(149),
    [anon_sym_do] = ACTIONS(149),
    [sym_sigil] = ACTIONS(149),
    [sym_send] = ACTIONS(149),
    [sym_message] = ACTIONS(149),
    [sym_singlestring] = ACTIONS(149),
    [sym_doublestring] = ACTIONS(149),
    [sym_comment] = ACTIONS(3),
    [sym_operator] = ACTIONS(149),
    [sym__newline] = ACTIONS(5),
    [sym_number] = ACTIONS(149),
  },
  [41] = {
    [ts_builtin_sym_end] = ACTIONS(175),
    [sym_symbol] = ACTIONS(155),
    [anon_sym_EQ_GT] = ACTIONS(155),
    [anon_sym_EQ] = ACTIONS(155),
    [anon_sym_LBRACE] = ACTIONS(155),
    [anon_sym_LPAREN] = ACTIONS(155),
    [anon_sym_LBRACK] = ACTIONS(155),
    [anon_sym_do] = ACTIONS(155),
    [sym_sigil] = ACTIONS(155),
    [sym_send] = ACTIONS(155),
    [sym_message] = ACTIONS(155),
    [sym_singlestring] = ACTIONS(155),
    [sym_doublestring] = ACTIONS(155),
    [sym_comment] = ACTIONS(3),
    [sym_operator] = ACTIONS(155),
    [sym__newline] = ACTIONS(5),
    [sym_number] = ACTIONS(155),
  },
  [42] = {
    [ts_builtin_sym_end] = ACTIONS(177),
    [sym_symbol] = ACTIONS(165),
    [anon_sym_EQ_GT] = ACTIONS(165),
    [anon_sym_EQ] = ACTIONS(165),
    [anon_sym_LBRACE] = ACTIONS(165),
    [anon_sym_LPAREN] = ACTIONS(165),
    [anon_sym_LBRACK] = ACTIONS(165),
    [anon_sym_do] = ACTIONS(165),
    [sym_sigil] = ACTIONS(165),
    [sym_send] = ACTIONS(165),
    [sym_message] = ACTIONS(165),
    [sym_singlestring] = ACTIONS(165),
    [sym_doublestring] = ACTIONS(165),
    [sym_comment] = ACTIONS(3),
    [sym_operator] = ACTIONS(165),
    [sym__newline] = ACTIONS(5),
    [sym_number] = ACTIONS(165),
  },
  [43] = {
    [ts_builtin_sym_end] = ACTIONS(179),
    [sym_symbol] = ACTIONS(153),
    [anon_sym_EQ_GT] = ACTIONS(153),
    [anon_sym_EQ] = ACTIONS(153),
    [anon_sym_LBRACE] = ACTIONS(153),
    [anon_sym_LPAREN] = ACTIONS(153),
    [anon_sym_LBRACK] = ACTIONS(153),
    [anon_sym_do] = ACTIONS(153),
    [sym_sigil] = ACTIONS(153),
    [sym_send] = ACTIONS(153),
    [sym_message] = ACTIONS(153),
    [sym_singlestring] = ACTIONS(153),
    [sym_doublestring] = ACTIONS(153),
    [sym_comment] = ACTIONS(3),
    [sym_operator] = ACTIONS(153),
    [sym__newline] = ACTIONS(5),
    [sym_number] = ACTIONS(153),
  },
  [44] = {
    [ts_builtin_sym_end] = ACTIONS(181),
    [sym_symbol] = ACTIONS(151),
    [anon_sym_EQ_GT] = ACTIONS(183),
    [anon_sym_EQ] = ACTIONS(183),
    [anon_sym_LBRACE] = ACTIONS(151),
    [anon_sym_LPAREN] = ACTIONS(151),
    [anon_sym_LBRACK] = ACTIONS(151),
    [anon_sym_do] = ACTIONS(151),
    [sym_sigil] = ACTIONS(151),
    [sym_send] = ACTIONS(151),
    [sym_message] = ACTIONS(151),
    [sym_singlestring] = ACTIONS(151),
    [sym_doublestring] = ACTIONS(151),
    [sym_comment] = ACTIONS(3),
    [sym_operator] = ACTIONS(151),
    [sym__newline] = ACTIONS(5),
    [sym_number] = ACTIONS(151),
  },
  [45] = {
    [ts_builtin_sym_end] = ACTIONS(185),
    [sym_symbol] = ACTIONS(147),
    [anon_sym_EQ_GT] = ACTIONS(147),
    [anon_sym_EQ] = ACTIONS(147),
    [anon_sym_LBRACE] = ACTIONS(147),
    [anon_sym_LPAREN] = ACTIONS(147),
    [anon_sym_LBRACK] = ACTIONS(147),
    [anon_sym_do] = ACTIONS(147),
    [sym_sigil] = ACTIONS(147),
    [sym_send] = ACTIONS(147),
    [sym_message] = ACTIONS(147),
    [sym_singlestring] = ACTIONS(147),
    [sym_doublestring] = ACTIONS(147),
    [sym_comment] = ACTIONS(3),
    [sym_operator] = ACTIONS(147),
    [sym__newline] = ACTIONS(5),
    [sym_number] = ACTIONS(147),
  },
  [46] = {
    [sym_symbol] = ACTIONS(125),
    [anon_sym_EQ_GT] = ACTIONS(41),
    [anon_sym_EQ] = ACTIONS(41),
    [anon_sym_LBRACE] = ACTIONS(125),
    [anon_sym_RBRACE] = ACTIONS(125),
    [anon_sym_LPAREN] = ACTIONS(125),
    [anon_sym_LBRACK] = ACTIONS(125),
    [anon_sym_do] = ACTIONS(125),
    [sym_sigil] = ACTIONS(125),
    [sym_send] = ACTIONS(43),
    [sym_message] = ACTIONS(125),
    [sym_singlestring] = ACTIONS(125),
    [sym_doublestring] = ACTIONS(125),
    [sym_comment] = ACTIONS(3),
    [sym_operator] = ACTIONS(43),
    [sym__newline] = ACTIONS(5),
    [sym_number] = ACTIONS(125),
  },
  [47] = {
    [ts_builtin_sym_end] = ACTIONS(187),
    [sym_symbol] = ACTIONS(163),
    [anon_sym_EQ_GT] = ACTIONS(163),
    [anon_sym_EQ] = ACTIONS(163),
    [anon_sym_LBRACE] = ACTIONS(163),
    [anon_sym_LPAREN] = ACTIONS(163),
    [anon_sym_LBRACK] = ACTIONS(163),
    [anon_sym_do] = ACTIONS(163),
    [sym_sigil] = ACTIONS(163),
    [sym_send] = ACTIONS(163),
    [sym_message] = ACTIONS(163),
    [sym_singlestring] = ACTIONS(163),
    [sym_doublestring] = ACTIONS(163),
    [sym_comment] = ACTIONS(3),
    [sym_operator] = ACTIONS(163),
    [sym__newline] = ACTIONS(5),
    [sym_number] = ACTIONS(163),
  },
  [48] = {
    [ts_builtin_sym_end] = ACTIONS(189),
    [sym_symbol] = ACTIONS(161),
    [anon_sym_EQ_GT] = ACTIONS(161),
    [anon_sym_EQ] = ACTIONS(161),
    [anon_sym_LBRACE] = ACTIONS(161),
    [anon_sym_LPAREN] = ACTIONS(161),
    [anon_sym_LBRACK] = ACTIONS(161),
    [anon_sym_do] = ACTIONS(161),
    [sym_sigil] = ACTIONS(161),
    [sym_send] = ACTIONS(161),
    [sym_message] = ACTIONS(161),
    [sym_singlestring] = ACTIONS(161),
    [sym_doublestring] = ACTIONS(161),
    [sym_comment] = ACTIONS(3),
    [sym_operator] = ACTIONS(161),
    [sym__newline] = ACTIONS(5),
    [sym_number] = ACTIONS(161),
  },
  [49] = {
    [ts_builtin_sym_end] = ACTIONS(191),
    [sym_symbol] = ACTIONS(159),
    [anon_sym_EQ_GT] = ACTIONS(159),
    [anon_sym_EQ] = ACTIONS(159),
    [anon_sym_LBRACE] = ACTIONS(159),
    [anon_sym_LPAREN] = ACTIONS(159),
    [anon_sym_LBRACK] = ACTIONS(159),
    [anon_sym_do] = ACTIONS(159),
    [sym_sigil] = ACTIONS(159),
    [sym_send] = ACTIONS(159),
    [sym_message] = ACTIONS(159),
    [sym_singlestring] = ACTIONS(159),
    [sym_doublestring] = ACTIONS(159),
    [sym_comment] = ACTIONS(3),
    [sym_operator] = ACTIONS(159),
    [sym__newline] = ACTIONS(5),
    [sym_number] = ACTIONS(159),
  },
  [50] = {
    [ts_builtin_sym_end] = ACTIONS(193),
    [sym_symbol] = ACTIONS(157),
    [anon_sym_EQ_GT] = ACTIONS(157),
    [anon_sym_EQ] = ACTIONS(157),
    [anon_sym_LBRACE] = ACTIONS(157),
    [anon_sym_LPAREN] = ACTIONS(157),
    [anon_sym_LBRACK] = ACTIONS(157),
    [anon_sym_do] = ACTIONS(157),
    [sym_sigil] = ACTIONS(157),
    [sym_send] = ACTIONS(157),
    [sym_message] = ACTIONS(157),
    [sym_singlestring] = ACTIONS(157),
    [sym_doublestring] = ACTIONS(157),
    [sym_comment] = ACTIONS(3),
    [sym_operator] = ACTIONS(157),
    [sym__newline] = ACTIONS(5),
    [sym_number] = ACTIONS(157),
  },
  [51] = {
    [ts_builtin_sym_end] = ACTIONS(195),
    [sym_symbol] = ACTIONS(169),
    [anon_sym_EQ_GT] = ACTIONS(183),
    [anon_sym_EQ] = ACTIONS(183),
    [anon_sym_LBRACE] = ACTIONS(169),
    [anon_sym_LPAREN] = ACTIONS(169),
    [anon_sym_LBRACK] = ACTIONS(169),
    [anon_sym_do] = ACTIONS(169),
    [sym_sigil] = ACTIONS(169),
    [sym_send] = ACTIONS(197),
    [sym_message] = ACTIONS(169),
    [sym_singlestring] = ACTIONS(169),
    [sym_doublestring] = ACTIONS(169),
    [sym_comment] = ACTIONS(3),
    [sym_operator] = ACTIONS(197),
    [sym__newline] = ACTIONS(5),
    [sym_number] = ACTIONS(169),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(5), 1,
      sym__newline,
    ACTIONS(199), 1,
      ts_builtin_sym_end,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(52)] = 0,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = false}}, SHIFT_EXTRA(),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT_EXTRA(),
  [7] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0, 0, 0),
  [9] = {.entry = {.count = 1, .reusable = false}}, SHIFT(51),
  [11] = {.entry = {.count = 1, .reusable = false}}, SHIFT(18),
  [13] = {.entry = {.count = 1, .reusable = false}}, SHIFT(24),
  [15] = {.entry = {.count = 1, .reusable = false}}, SHIFT(23),
  [17] = {.entry = {.count = 1, .reusable = false}}, SHIFT(21),
  [19] = {.entry = {.count = 1, .reusable = false}}, SHIFT(43),
  [21] = {.entry = {.count = 1, .reusable = false}}, SHIFT(29),
  [23] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_unary, 2, 0, 1),
  [25] = {.entry = {.count = 1, .reusable = false}}, SHIFT(20),
  [27] = {.entry = {.count = 1, .reusable = false}}, SHIFT(16),
  [29] = {.entry = {.count = 1, .reusable = false}}, SHIFT(14),
  [31] = {.entry = {.count = 1, .reusable = false}}, SHIFT(12),
  [33] = {.entry = {.count = 1, .reusable = false}}, SHIFT(30),
  [35] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_unary, 2, 0, 1),
  [37] = {.entry = {.count = 1, .reusable = false}}, SHIFT(44),
  [39] = {.entry = {.count = 1, .reusable = false}}, SHIFT(46),
  [41] = {.entry = {.count = 1, .reusable = false}}, SHIFT(25),
  [43] = {.entry = {.count = 1, .reusable = false}}, SHIFT(2),
  [45] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(38),
  [48] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(20),
  [51] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(16),
  [54] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [56] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(14),
  [59] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(12),
  [62] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(30),
  [65] = {.entry = {.count = 1, .reusable = false}}, SHIFT(4),
  [67] = {.entry = {.count = 1, .reusable = false}}, SHIFT(45),
  [69] = {.entry = {.count = 1, .reusable = false}}, SHIFT(38),
  [71] = {.entry = {.count = 1, .reusable = false}}, SHIFT(36),
  [73] = {.entry = {.count = 1, .reusable = false}}, SHIFT(37),
  [75] = {.entry = {.count = 1, .reusable = false}}, SHIFT(28),
  [77] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [79] = {.entry = {.count = 1, .reusable = false}}, SHIFT(27),
  [81] = {.entry = {.count = 1, .reusable = false}}, SHIFT(35),
  [83] = {.entry = {.count = 1, .reusable = false}}, SHIFT(40),
  [85] = {.entry = {.count = 1, .reusable = false}}, SHIFT(34),
  [87] = {.entry = {.count = 1, .reusable = false}}, SHIFT(39),
  [89] = {.entry = {.count = 1, .reusable = false}}, SHIFT(33),
  [91] = {.entry = {.count = 1, .reusable = false}}, SHIFT(42),
  [93] = {.entry = {.count = 1, .reusable = false}}, SHIFT(50),
  [95] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [97] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(51),
  [100] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(18),
  [103] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(24),
  [106] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(23),
  [109] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(21),
  [112] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(43),
  [115] = {.entry = {.count = 1, .reusable = false}}, SHIFT(32),
  [117] = {.entry = {.count = 1, .reusable = false}}, SHIFT(47),
  [119] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_record_repeat1, 2, 0, 0), SHIFT_REPEAT(4),
  [122] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_record_repeat1, 2, 0, 0), SHIFT_REPEAT(20),
  [125] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_record_repeat1, 2, 0, 0),
  [127] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_record_repeat1, 2, 0, 0), SHIFT_REPEAT(16),
  [130] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_record_repeat1, 2, 0, 0), SHIFT_REPEAT(14),
  [133] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_record_repeat1, 2, 0, 0), SHIFT_REPEAT(12),
  [136] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_record_repeat1, 2, 0, 0), SHIFT_REPEAT(30),
  [139] = {.entry = {.count = 1, .reusable = false}}, SHIFT(48),
  [141] = {.entry = {.count = 1, .reusable = false}}, SHIFT(49),
  [143] = {.entry = {.count = 1, .reusable = false}}, SHIFT(31),
  [145] = {.entry = {.count = 1, .reusable = false}}, SHIFT(41),
  [147] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_record, 3, 0, 0),
  [149] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_tuple, 3, 0, 0),
  [151] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_binary, 3, 0, 2),
  [153] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_string, 1, 0, 0),
  [155] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_special_send, 3, 0, 2),
  [157] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_record, 2, 0, 0),
  [159] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_tuple, 2, 0, 0),
  [161] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_list, 2, 0, 0),
  [163] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_block, 2, 0, 0),
  [165] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_block, 3, 0, 0),
  [167] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_list, 3, 0, 0),
  [169] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 1, 0, 0),
  [171] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_list, 3, 0, 0),
  [173] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_tuple, 3, 0, 0),
  [175] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_special_send, 3, 0, 2),
  [177] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_block, 3, 0, 0),
  [179] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_string, 1, 0, 0),
  [181] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_binary, 3, 0, 2),
  [183] = {.entry = {.count = 1, .reusable = false}}, SHIFT(26),
  [185] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_record, 3, 0, 0),
  [187] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_block, 2, 0, 0),
  [189] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_list, 2, 0, 0),
  [191] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_tuple, 2, 0, 0),
  [193] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_record, 2, 0, 0),
  [195] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 1, 0, 0),
  [197] = {.entry = {.count = 1, .reusable = false}}, SHIFT(3),
  [199] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_gab(void) {
  static const TSLanguage language = {
    .version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = ts_lex_modes,
    .lex_fn = ts_lex,
    .keyword_lex_fn = ts_lex_keywords,
    .keyword_capture_token = sym_symbol,
    .primary_state_ids = ts_primary_state_ids,
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
