#include "parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 14
#define STATE_COUNT 70
#define LARGE_STATE_COUNT 5
#define SYMBOL_COUNT 34
#define ALIAS_COUNT 2
#define TOKEN_COUNT 17
#define EXTERNAL_TOKEN_COUNT 1
#define FIELD_COUNT 1
#define MAX_ALIAS_SEQUENCE_LENGTH 5
#define PRODUCTION_ID_COUNT 5

enum ts_symbol_identifiers {
  anon_sym_EQ = 1,
  anon_sym_COLON = 2,
  anon_sym_DOT = 3,
  anon_sym_LBRACK = 4,
  anon_sym_RBRACK = 5,
  anon_sym_DOLLAR_LBRACE = 6,
  anon_sym_RBRACE = 7,
  anon_sym_COLON_COLON = 8,
  anon_sym_BSLASH = 9,
  aux_sym_escape_token1 = 10,
  aux_sym_escape_token2 = 11,
  sym_comment = 12,
  sym__space = 13,
  aux_sym__char_token1 = 14,
  sym__eol = 15,
  sym__eof = 16,
  sym_file = 17,
  sym_property = 18,
  sym_key = 19,
  sym__index = 20,
  sym_value = 21,
  sym_substitution = 22,
  sym__default = 23,
  sym__secret = 24,
  aux_sym__content = 25,
  sym__linebreak = 26,
  sym_escape = 27,
  sym__char = 28,
  aux_sym_file_repeat1 = 29,
  aux_sym_key_repeat1 = 30,
  aux_sym__index_repeat1 = 31,
  aux_sym_value_repeat1 = 32,
  aux_sym_substitution_repeat1 = 33,
  alias_sym_index = 34,
  alias_sym_secret = 35,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_EQ] = "=",
  [anon_sym_COLON] = ":",
  [anon_sym_DOT] = ".",
  [anon_sym_LBRACK] = "[",
  [anon_sym_RBRACK] = "]",
  [anon_sym_DOLLAR_LBRACE] = "${",
  [anon_sym_RBRACE] = "}",
  [anon_sym_COLON_COLON] = "::",
  [anon_sym_BSLASH] = "\\",
  [aux_sym_escape_token1] = "escape_token1",
  [aux_sym_escape_token2] = "escape_token2",
  [sym_comment] = "comment",
  [sym__space] = "_space",
  [aux_sym__char_token1] = "_char_token1",
  [sym__eol] = "_eol",
  [sym__eof] = "_eof",
  [sym_file] = "file",
  [sym_property] = "property",
  [sym_key] = "key",
  [sym__index] = "_index",
  [sym_value] = "value",
  [sym_substitution] = "substitution",
  [sym__default] = "_default",
  [sym__secret] = "_secret",
  [aux_sym__content] = "_content",
  [sym__linebreak] = "_linebreak",
  [sym_escape] = "escape",
  [sym__char] = "_char",
  [aux_sym_file_repeat1] = "file_repeat1",
  [aux_sym_key_repeat1] = "key_repeat1",
  [aux_sym__index_repeat1] = "_index_repeat1",
  [aux_sym_value_repeat1] = "value_repeat1",
  [aux_sym_substitution_repeat1] = "substitution_repeat1",
  [alias_sym_index] = "index",
  [alias_sym_secret] = "secret",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_EQ] = anon_sym_EQ,
  [anon_sym_COLON] = anon_sym_COLON,
  [anon_sym_DOT] = anon_sym_DOT,
  [anon_sym_LBRACK] = anon_sym_LBRACK,
  [anon_sym_RBRACK] = anon_sym_RBRACK,
  [anon_sym_DOLLAR_LBRACE] = anon_sym_DOLLAR_LBRACE,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [anon_sym_COLON_COLON] = anon_sym_COLON_COLON,
  [anon_sym_BSLASH] = anon_sym_BSLASH,
  [aux_sym_escape_token1] = aux_sym_escape_token1,
  [aux_sym_escape_token2] = aux_sym_escape_token2,
  [sym_comment] = sym_comment,
  [sym__space] = sym__space,
  [aux_sym__char_token1] = aux_sym__char_token1,
  [sym__eol] = sym__eol,
  [sym__eof] = sym__eof,
  [sym_file] = sym_file,
  [sym_property] = sym_property,
  [sym_key] = sym_key,
  [sym__index] = sym__index,
  [sym_value] = sym_value,
  [sym_substitution] = sym_substitution,
  [sym__default] = sym__default,
  [sym__secret] = sym__secret,
  [aux_sym__content] = aux_sym__content,
  [sym__linebreak] = sym__linebreak,
  [sym_escape] = sym_escape,
  [sym__char] = sym__char,
  [aux_sym_file_repeat1] = aux_sym_file_repeat1,
  [aux_sym_key_repeat1] = aux_sym_key_repeat1,
  [aux_sym__index_repeat1] = aux_sym__index_repeat1,
  [aux_sym_value_repeat1] = aux_sym_value_repeat1,
  [aux_sym_substitution_repeat1] = aux_sym_substitution_repeat1,
  [alias_sym_index] = alias_sym_index,
  [alias_sym_secret] = alias_sym_secret,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COLON] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DOT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DOLLAR_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COLON_COLON] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_BSLASH] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_escape_token1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_escape_token2] = {
    .visible = false,
    .named = false,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [sym__space] = {
    .visible = false,
    .named = true,
  },
  [aux_sym__char_token1] = {
    .visible = false,
    .named = false,
  },
  [sym__eol] = {
    .visible = false,
    .named = true,
  },
  [sym__eof] = {
    .visible = false,
    .named = true,
  },
  [sym_file] = {
    .visible = true,
    .named = true,
  },
  [sym_property] = {
    .visible = true,
    .named = true,
  },
  [sym_key] = {
    .visible = true,
    .named = true,
  },
  [sym__index] = {
    .visible = false,
    .named = true,
  },
  [sym_value] = {
    .visible = true,
    .named = true,
  },
  [sym_substitution] = {
    .visible = true,
    .named = true,
  },
  [sym__default] = {
    .visible = false,
    .named = true,
  },
  [sym__secret] = {
    .visible = false,
    .named = true,
  },
  [aux_sym__content] = {
    .visible = false,
    .named = false,
  },
  [sym__linebreak] = {
    .visible = false,
    .named = true,
  },
  [sym_escape] = {
    .visible = true,
    .named = true,
  },
  [sym__char] = {
    .visible = false,
    .named = true,
  },
  [aux_sym_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_key_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym__index_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_value_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_substitution_repeat1] = {
    .visible = false,
    .named = false,
  },
  [alias_sym_index] = {
    .visible = true,
    .named = true,
  },
  [alias_sym_secret] = {
    .visible = true,
    .named = true,
  },
};

enum ts_field_identifiers {
  field_default = 1,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_default] = "default",
};

static const TSFieldMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [2] = {.index = 0, .length = 1},
  [4] = {.index = 1, .length = 1},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_default, 1},
  [1] =
    {field_default, 2, .inherited = true},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
  [1] = {
    [1] = alias_sym_index,
  },
  [3] = {
    [1] = alias_sym_secret,
  },
};

static const uint16_t ts_non_terminal_alias_map[] = {
  aux_sym__content, 2,
    aux_sym__content,
    alias_sym_secret,
  aux_sym__index_repeat1, 2,
    aux_sym__index_repeat1,
    alias_sym_index,
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 2,
  [4] = 2,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 11,
  [19] = 10,
  [20] = 16,
  [21] = 16,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 25,
  [33] = 33,
  [34] = 23,
  [35] = 35,
  [36] = 26,
  [37] = 37,
  [38] = 38,
  [39] = 39,
  [40] = 40,
  [41] = 26,
  [42] = 35,
  [43] = 30,
  [44] = 33,
  [45] = 35,
  [46] = 33,
  [47] = 47,
  [48] = 30,
  [49] = 26,
  [50] = 50,
  [51] = 50,
  [52] = 52,
  [53] = 53,
  [54] = 52,
  [55] = 55,
  [56] = 56,
  [57] = 57,
  [58] = 58,
  [59] = 59,
  [60] = 60,
  [61] = 61,
  [62] = 62,
  [63] = 63,
  [64] = 64,
  [65] = 65,
  [66] = 64,
  [67] = 63,
  [68] = 63,
  [69] = 64,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(16);
      ADVANCE_MAP(
        '\n', 36,
        '\r', 33,
        '$', 35,
        '.', 20,
        ':', 19,
        '=', 17,
        '[', 21,
        '\\', 26,
        ']', 22,
        '}', 24,
        '!', 30,
        '#', 30,
        '\t', 31,
        '\f', 31,
        ' ', 31,
      );
      if (lookahead != 0) ADVANCE(32);
      END_STATE();
    case 1:
      ADVANCE_MAP(
        '\n', 36,
        '\r', 33,
        '$', 35,
        '.', 20,
        ':', 18,
        '=', 17,
        '[', 21,
        '\\', 26,
        '\t', 31,
        '\f', 31,
        ' ', 31,
      );
      if (lookahead != 0) ADVANCE(32);
      END_STATE();
    case 2:
      ADVANCE_MAP(
        '\n', 36,
        '\r', 33,
        '$', 35,
        ':', 18,
        '=', 17,
        '\\', 26,
        '\t', 31,
        '\f', 31,
        ' ', 31,
      );
      if (lookahead != 0) ADVANCE(32);
      END_STATE();
    case 3:
      if (lookahead == '\n') ADVANCE(36);
      if (lookahead == '\r') ADVANCE(33);
      if (lookahead == '$') ADVANCE(35);
      if (lookahead == '\\') ADVANCE(26);
      if (lookahead == '\t' ||
          lookahead == '\f' ||
          lookahead == ' ') ADVANCE(31);
      if (lookahead != 0) ADVANCE(32);
      END_STATE();
    case 4:
      if (lookahead == '\n') ADVANCE(36);
      if (lookahead == '\r') ADVANCE(33);
      if (lookahead == '$') ADVANCE(35);
      if (lookahead == '\\') ADVANCE(26);
      if (lookahead != 0) ADVANCE(32);
      END_STATE();
    case 5:
      if (lookahead == '\n') ADVANCE(36);
      if (lookahead == '\r') ADVANCE(33);
      if (lookahead == '.') ADVANCE(20);
      if (lookahead == '[') ADVANCE(21);
      if (lookahead == '\\') ADVANCE(34);
      if (lookahead == '!' ||
          lookahead == '#') ADVANCE(30);
      if (lookahead != 0) ADVANCE(32);
      END_STATE();
    case 6:
      if (lookahead == '\n') ADVANCE(36);
      if (lookahead == '\r') ADVANCE(37);
      END_STATE();
    case 7:
      if (lookahead == '$') ADVANCE(35);
      if (lookahead == '.') ADVANCE(20);
      if (lookahead == ':') ADVANCE(19);
      if (lookahead == '[') ADVANCE(21);
      if (lookahead == '\\') ADVANCE(34);
      if (lookahead == '}') ADVANCE(24);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(32);
      END_STATE();
    case 8:
      if (lookahead == '$') ADVANCE(35);
      if (lookahead == '.') ADVANCE(20);
      if (lookahead == '[') ADVANCE(21);
      if (lookahead == '\\') ADVANCE(34);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(32);
      END_STATE();
    case 9:
      if (lookahead == '$') ADVANCE(35);
      if (lookahead == '\\') ADVANCE(34);
      if (lookahead == '}') ADVANCE(24);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(32);
      END_STATE();
    case 10:
      if (lookahead == '$') ADVANCE(35);
      if (lookahead == '\\') ADVANCE(34);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(32);
      END_STATE();
    case 11:
      if (lookahead == ']') ADVANCE(22);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(32);
      END_STATE();
    case 12:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(29);
      END_STATE();
    case 13:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(12);
      END_STATE();
    case 14:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(13);
      END_STATE();
    case 15:
      if (eof) ADVANCE(16);
      ADVANCE_MAP(
        '\n', 36,
        '\r', 33,
        '.', 20,
        '[', 21,
        '\\', 34,
        '!', 30,
        '#', 30,
        '\t', 31,
        '\f', 31,
        ' ', 31,
      );
      if (lookahead != 0) ADVANCE(32);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(anon_sym_EQ);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(anon_sym_COLON);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(anon_sym_COLON);
      if (lookahead == ':') ADVANCE(25);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(anon_sym_DOT);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(anon_sym_LBRACK);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(anon_sym_RBRACK);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(anon_sym_DOLLAR_LBRACE);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(anon_sym_COLON_COLON);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(anon_sym_BSLASH);
      if (lookahead == 'u') ADVANCE(28);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(27);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(aux_sym_escape_token1);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(aux_sym_escape_token1);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(14);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(aux_sym_escape_token2);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(30);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(sym__space);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(aux_sym__char_token1);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(aux_sym__char_token1);
      if (lookahead == '\n') ADVANCE(36);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(aux_sym__char_token1);
      if (lookahead == 'u') ADVANCE(28);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(27);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(aux_sym__char_token1);
      if (lookahead == '{') ADVANCE(23);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(sym__eol);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(sym__eol);
      if (lookahead == '\n') ADVANCE(36);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0, .external_lex_state = 1},
  [1] = {.lex_state = 15, .external_lex_state = 1},
  [2] = {.lex_state = 7},
  [3] = {.lex_state = 7},
  [4] = {.lex_state = 7},
  [5] = {.lex_state = 15, .external_lex_state = 1},
  [6] = {.lex_state = 15, .external_lex_state = 1},
  [7] = {.lex_state = 7},
  [8] = {.lex_state = 2, .external_lex_state = 1},
  [9] = {.lex_state = 2, .external_lex_state = 1},
  [10] = {.lex_state = 1, .external_lex_state = 1},
  [11] = {.lex_state = 1, .external_lex_state = 1},
  [12] = {.lex_state = 5, .external_lex_state = 1},
  [13] = {.lex_state = 3, .external_lex_state = 1},
  [14] = {.lex_state = 3, .external_lex_state = 1},
  [15] = {.lex_state = 4, .external_lex_state = 1},
  [16] = {.lex_state = 8},
  [17] = {.lex_state = 4, .external_lex_state = 1},
  [18] = {.lex_state = 7},
  [19] = {.lex_state = 7},
  [20] = {.lex_state = 8},
  [21] = {.lex_state = 8},
  [22] = {.lex_state = 4, .external_lex_state = 1},
  [23] = {.lex_state = 1, .external_lex_state = 1},
  [24] = {.lex_state = 4, .external_lex_state = 1},
  [25] = {.lex_state = 1, .external_lex_state = 1},
  [26] = {.lex_state = 1, .external_lex_state = 1},
  [27] = {.lex_state = 15, .external_lex_state = 1},
  [28] = {.lex_state = 15, .external_lex_state = 1},
  [29] = {.lex_state = 9},
  [30] = {.lex_state = 7},
  [31] = {.lex_state = 9},
  [32] = {.lex_state = 7},
  [33] = {.lex_state = 7},
  [34] = {.lex_state = 7},
  [35] = {.lex_state = 7},
  [36] = {.lex_state = 7},
  [37] = {.lex_state = 9},
  [38] = {.lex_state = 10},
  [39] = {.lex_state = 10},
  [40] = {.lex_state = 4, .external_lex_state = 1},
  [41] = {.lex_state = 4, .external_lex_state = 1},
  [42] = {.lex_state = 4, .external_lex_state = 1},
  [43] = {.lex_state = 4, .external_lex_state = 1},
  [44] = {.lex_state = 4, .external_lex_state = 1},
  [45] = {.lex_state = 9},
  [46] = {.lex_state = 9},
  [47] = {.lex_state = 9},
  [48] = {.lex_state = 9},
  [49] = {.lex_state = 9},
  [50] = {.lex_state = 11},
  [51] = {.lex_state = 11},
  [52] = {.lex_state = 11},
  [53] = {.lex_state = 11},
  [54] = {.lex_state = 11},
  [55] = {.lex_state = 6, .external_lex_state = 1},
  [56] = {.lex_state = 6, .external_lex_state = 1},
  [57] = {.lex_state = 6, .external_lex_state = 1},
  [58] = {.lex_state = 11},
  [59] = {.lex_state = 6, .external_lex_state = 1},
  [60] = {.lex_state = 6, .external_lex_state = 1},
  [61] = {.lex_state = 6, .external_lex_state = 1},
  [62] = {.lex_state = 6},
  [63] = {.lex_state = 0},
  [64] = {.lex_state = 0},
  [65] = {.lex_state = 0},
  [66] = {.lex_state = 0},
  [67] = {.lex_state = 0},
  [68] = {.lex_state = 0},
  [69] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [0] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_EQ] = ACTIONS(1),
    [anon_sym_COLON] = ACTIONS(1),
    [anon_sym_DOT] = ACTIONS(1),
    [anon_sym_LBRACK] = ACTIONS(1),
    [anon_sym_RBRACK] = ACTIONS(1),
    [anon_sym_DOLLAR_LBRACE] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [anon_sym_COLON_COLON] = ACTIONS(1),
    [anon_sym_BSLASH] = ACTIONS(1),
    [aux_sym_escape_token1] = ACTIONS(1),
    [aux_sym_escape_token2] = ACTIONS(1),
    [sym_comment] = ACTIONS(1),
    [sym__space] = ACTIONS(1),
    [aux_sym__char_token1] = ACTIONS(1),
    [sym__eol] = ACTIONS(1),
    [sym__eof] = ACTIONS(1),
  },
  [1] = {
    [sym_file] = STATE(65),
    [sym_property] = STATE(59),
    [sym_key] = STATE(8),
    [sym__index] = STATE(11),
    [sym_escape] = STATE(11),
    [sym__char] = STATE(11),
    [aux_sym_file_repeat1] = STATE(5),
    [aux_sym_key_repeat1] = STATE(11),
    [ts_builtin_sym_end] = ACTIONS(3),
    [anon_sym_DOT] = ACTIONS(5),
    [anon_sym_LBRACK] = ACTIONS(7),
    [aux_sym_escape_token1] = ACTIONS(9),
    [aux_sym_escape_token2] = ACTIONS(11),
    [sym_comment] = ACTIONS(13),
    [sym__space] = ACTIONS(15),
    [aux_sym__char_token1] = ACTIONS(17),
    [sym__eol] = ACTIONS(19),
    [sym__eof] = ACTIONS(21),
  },
  [2] = {
    [sym_key] = STATE(7),
    [sym__index] = STATE(18),
    [sym_substitution] = STATE(7),
    [sym__default] = STATE(66),
    [sym__secret] = STATE(67),
    [sym_escape] = STATE(18),
    [sym__char] = STATE(18),
    [aux_sym_key_repeat1] = STATE(18),
    [aux_sym_substitution_repeat1] = STATE(7),
    [anon_sym_COLON] = ACTIONS(23),
    [anon_sym_DOT] = ACTIONS(25),
    [anon_sym_LBRACK] = ACTIONS(27),
    [anon_sym_DOLLAR_LBRACE] = ACTIONS(29),
    [anon_sym_RBRACE] = ACTIONS(31),
    [anon_sym_COLON_COLON] = ACTIONS(33),
    [aux_sym_escape_token1] = ACTIONS(35),
    [aux_sym_escape_token2] = ACTIONS(37),
    [aux_sym__char_token1] = ACTIONS(39),
  },
  [3] = {
    [sym_key] = STATE(7),
    [sym__index] = STATE(18),
    [sym_substitution] = STATE(7),
    [sym__default] = STATE(69),
    [sym__secret] = STATE(63),
    [sym_escape] = STATE(18),
    [sym__char] = STATE(18),
    [aux_sym_key_repeat1] = STATE(18),
    [aux_sym_substitution_repeat1] = STATE(7),
    [anon_sym_COLON] = ACTIONS(23),
    [anon_sym_DOT] = ACTIONS(25),
    [anon_sym_LBRACK] = ACTIONS(27),
    [anon_sym_DOLLAR_LBRACE] = ACTIONS(29),
    [anon_sym_RBRACE] = ACTIONS(41),
    [anon_sym_COLON_COLON] = ACTIONS(33),
    [aux_sym_escape_token1] = ACTIONS(35),
    [aux_sym_escape_token2] = ACTIONS(37),
    [aux_sym__char_token1] = ACTIONS(39),
  },
  [4] = {
    [sym_key] = STATE(7),
    [sym__index] = STATE(18),
    [sym_substitution] = STATE(7),
    [sym__default] = STATE(64),
    [sym__secret] = STATE(68),
    [sym_escape] = STATE(18),
    [sym__char] = STATE(18),
    [aux_sym_key_repeat1] = STATE(18),
    [aux_sym_substitution_repeat1] = STATE(7),
    [anon_sym_COLON] = ACTIONS(23),
    [anon_sym_DOT] = ACTIONS(25),
    [anon_sym_LBRACK] = ACTIONS(27),
    [anon_sym_DOLLAR_LBRACE] = ACTIONS(29),
    [anon_sym_RBRACE] = ACTIONS(43),
    [anon_sym_COLON_COLON] = ACTIONS(33),
    [aux_sym_escape_token1] = ACTIONS(35),
    [aux_sym_escape_token2] = ACTIONS(37),
    [aux_sym__char_token1] = ACTIONS(39),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 14,
    ACTIONS(5), 1,
      anon_sym_DOT,
    ACTIONS(7), 1,
      anon_sym_LBRACK,
    ACTIONS(9), 1,
      aux_sym_escape_token1,
    ACTIONS(11), 1,
      aux_sym_escape_token2,
    ACTIONS(13), 1,
      sym_comment,
    ACTIONS(15), 1,
      sym__space,
    ACTIONS(17), 1,
      aux_sym__char_token1,
    ACTIONS(45), 1,
      ts_builtin_sym_end,
    ACTIONS(47), 1,
      sym__eol,
    ACTIONS(49), 1,
      sym__eof,
    STATE(6), 1,
      aux_sym_file_repeat1,
    STATE(8), 1,
      sym_key,
    STATE(59), 1,
      sym_property,
    STATE(11), 4,
      sym__index,
      sym_escape,
      sym__char,
      aux_sym_key_repeat1,
  [46] = 14,
    ACTIONS(51), 1,
      ts_builtin_sym_end,
    ACTIONS(53), 1,
      anon_sym_DOT,
    ACTIONS(56), 1,
      anon_sym_LBRACK,
    ACTIONS(59), 1,
      aux_sym_escape_token1,
    ACTIONS(62), 1,
      aux_sym_escape_token2,
    ACTIONS(65), 1,
      sym_comment,
    ACTIONS(68), 1,
      sym__space,
    ACTIONS(71), 1,
      aux_sym__char_token1,
    ACTIONS(74), 1,
      sym__eol,
    ACTIONS(77), 1,
      sym__eof,
    STATE(6), 1,
      aux_sym_file_repeat1,
    STATE(8), 1,
      sym_key,
    STATE(59), 1,
      sym_property,
    STATE(11), 4,
      sym__index,
      sym_escape,
      sym__char,
      aux_sym_key_repeat1,
  [92] = 10,
    ACTIONS(80), 1,
      anon_sym_COLON,
    ACTIONS(82), 1,
      anon_sym_DOT,
    ACTIONS(85), 1,
      anon_sym_LBRACK,
    ACTIONS(88), 1,
      anon_sym_DOLLAR_LBRACE,
    ACTIONS(93), 1,
      aux_sym_escape_token1,
    ACTIONS(96), 1,
      aux_sym_escape_token2,
    ACTIONS(99), 1,
      aux_sym__char_token1,
    ACTIONS(91), 2,
      anon_sym_RBRACE,
      anon_sym_COLON_COLON,
    STATE(7), 3,
      sym_key,
      sym_substitution,
      aux_sym_substitution_repeat1,
    STATE(18), 4,
      sym__index,
      sym_escape,
      sym__char,
      aux_sym_key_repeat1,
  [129] = 11,
    ACTIONS(104), 1,
      anon_sym_DOLLAR_LBRACE,
    ACTIONS(106), 1,
      anon_sym_BSLASH,
    ACTIONS(108), 1,
      aux_sym_escape_token1,
    ACTIONS(110), 1,
      aux_sym_escape_token2,
    ACTIONS(112), 1,
      sym__space,
    ACTIONS(114), 1,
      aux_sym__char_token1,
    ACTIONS(116), 1,
      sym__eol,
    ACTIONS(118), 1,
      sym__eof,
    STATE(57), 1,
      sym_value,
    ACTIONS(102), 2,
      anon_sym_EQ,
      anon_sym_COLON,
    STATE(22), 5,
      sym_substitution,
      sym__linebreak,
      sym_escape,
      sym__char,
      aux_sym_value_repeat1,
  [168] = 11,
    ACTIONS(104), 1,
      anon_sym_DOLLAR_LBRACE,
    ACTIONS(106), 1,
      anon_sym_BSLASH,
    ACTIONS(108), 1,
      aux_sym_escape_token1,
    ACTIONS(110), 1,
      aux_sym_escape_token2,
    ACTIONS(114), 1,
      aux_sym__char_token1,
    ACTIONS(122), 1,
      sym__space,
    ACTIONS(124), 1,
      sym__eol,
    ACTIONS(126), 1,
      sym__eof,
    STATE(55), 1,
      sym_value,
    ACTIONS(120), 2,
      anon_sym_EQ,
      anon_sym_COLON,
    STATE(22), 5,
      sym_substitution,
      sym__linebreak,
      sym_escape,
      sym__char,
      aux_sym_value_repeat1,
  [207] = 8,
    ACTIONS(130), 1,
      anon_sym_DOT,
    ACTIONS(133), 1,
      anon_sym_LBRACK,
    ACTIONS(138), 1,
      aux_sym_escape_token1,
    ACTIONS(141), 1,
      aux_sym_escape_token2,
    ACTIONS(144), 1,
      aux_sym__char_token1,
    ACTIONS(136), 2,
      anon_sym_BSLASH,
      sym__eol,
    STATE(10), 4,
      sym__index,
      sym_escape,
      sym__char,
      aux_sym_key_repeat1,
    ACTIONS(128), 5,
      sym__eof,
      anon_sym_EQ,
      anon_sym_COLON,
      anon_sym_DOLLAR_LBRACE,
      sym__space,
  [240] = 8,
    ACTIONS(7), 1,
      anon_sym_LBRACK,
    ACTIONS(9), 1,
      aux_sym_escape_token1,
    ACTIONS(11), 1,
      aux_sym_escape_token2,
    ACTIONS(149), 1,
      anon_sym_DOT,
    ACTIONS(153), 1,
      aux_sym__char_token1,
    ACTIONS(151), 2,
      anon_sym_BSLASH,
      sym__eol,
    STATE(10), 4,
      sym__index,
      sym_escape,
      sym__char,
      aux_sym_key_repeat1,
    ACTIONS(147), 5,
      sym__eof,
      anon_sym_EQ,
      anon_sym_COLON,
      anon_sym_DOLLAR_LBRACE,
      sym__space,
  [273] = 11,
    ACTIONS(5), 1,
      anon_sym_DOT,
    ACTIONS(7), 1,
      anon_sym_LBRACK,
    ACTIONS(9), 1,
      aux_sym_escape_token1,
    ACTIONS(11), 1,
      aux_sym_escape_token2,
    ACTIONS(17), 1,
      aux_sym__char_token1,
    ACTIONS(155), 1,
      sym_comment,
    ACTIONS(157), 1,
      sym__eol,
    ACTIONS(159), 1,
      sym__eof,
    STATE(8), 1,
      sym_key,
    STATE(61), 1,
      sym_property,
    STATE(11), 4,
      sym__index,
      sym_escape,
      sym__char,
      aux_sym_key_repeat1,
  [310] = 10,
    ACTIONS(104), 1,
      anon_sym_DOLLAR_LBRACE,
    ACTIONS(106), 1,
      anon_sym_BSLASH,
    ACTIONS(108), 1,
      aux_sym_escape_token1,
    ACTIONS(110), 1,
      aux_sym_escape_token2,
    ACTIONS(114), 1,
      aux_sym__char_token1,
    ACTIONS(161), 1,
      sym__space,
    ACTIONS(163), 1,
      sym__eol,
    ACTIONS(165), 1,
      sym__eof,
    STATE(60), 1,
      sym_value,
    STATE(22), 5,
      sym_substitution,
      sym__linebreak,
      sym_escape,
      sym__char,
      aux_sym_value_repeat1,
  [345] = 10,
    ACTIONS(104), 1,
      anon_sym_DOLLAR_LBRACE,
    ACTIONS(106), 1,
      anon_sym_BSLASH,
    ACTIONS(108), 1,
      aux_sym_escape_token1,
    ACTIONS(110), 1,
      aux_sym_escape_token2,
    ACTIONS(114), 1,
      aux_sym__char_token1,
    ACTIONS(122), 1,
      sym__space,
    ACTIONS(124), 1,
      sym__eol,
    ACTIONS(126), 1,
      sym__eof,
    STATE(55), 1,
      sym_value,
    STATE(22), 5,
      sym_substitution,
      sym__linebreak,
      sym_escape,
      sym__char,
      aux_sym_value_repeat1,
  [380] = 9,
    ACTIONS(104), 1,
      anon_sym_DOLLAR_LBRACE,
    ACTIONS(106), 1,
      anon_sym_BSLASH,
    ACTIONS(108), 1,
      aux_sym_escape_token1,
    ACTIONS(110), 1,
      aux_sym_escape_token2,
    ACTIONS(114), 1,
      aux_sym__char_token1,
    ACTIONS(163), 1,
      sym__eol,
    ACTIONS(165), 1,
      sym__eof,
    STATE(60), 1,
      sym_value,
    STATE(22), 5,
      sym_substitution,
      sym__linebreak,
      sym_escape,
      sym__char,
      aux_sym_value_repeat1,
  [412] = 8,
    ACTIONS(25), 1,
      anon_sym_DOT,
    ACTIONS(27), 1,
      anon_sym_LBRACK,
    ACTIONS(29), 1,
      anon_sym_DOLLAR_LBRACE,
    ACTIONS(35), 1,
      aux_sym_escape_token1,
    ACTIONS(37), 1,
      aux_sym_escape_token2,
    ACTIONS(39), 1,
      aux_sym__char_token1,
    STATE(3), 3,
      sym_key,
      sym_substitution,
      aux_sym_substitution_repeat1,
    STATE(18), 4,
      sym__index,
      sym_escape,
      sym__char,
      aux_sym_key_repeat1,
  [442] = 9,
    ACTIONS(104), 1,
      anon_sym_DOLLAR_LBRACE,
    ACTIONS(106), 1,
      anon_sym_BSLASH,
    ACTIONS(108), 1,
      aux_sym_escape_token1,
    ACTIONS(110), 1,
      aux_sym_escape_token2,
    ACTIONS(114), 1,
      aux_sym__char_token1,
    ACTIONS(167), 1,
      sym__eol,
    ACTIONS(169), 1,
      sym__eof,
    STATE(56), 1,
      sym_value,
    STATE(22), 5,
      sym_substitution,
      sym__linebreak,
      sym_escape,
      sym__char,
      aux_sym_value_repeat1,
  [474] = 8,
    ACTIONS(27), 1,
      anon_sym_LBRACK,
    ACTIONS(35), 1,
      aux_sym_escape_token1,
    ACTIONS(37), 1,
      aux_sym_escape_token2,
    ACTIONS(151), 1,
      anon_sym_COLON,
    ACTIONS(171), 1,
      anon_sym_DOT,
    ACTIONS(173), 1,
      aux_sym__char_token1,
    ACTIONS(147), 3,
      anon_sym_DOLLAR_LBRACE,
      anon_sym_RBRACE,
      anon_sym_COLON_COLON,
    STATE(19), 4,
      sym__index,
      sym_escape,
      sym__char,
      aux_sym_key_repeat1,
  [504] = 8,
    ACTIONS(136), 1,
      anon_sym_COLON,
    ACTIONS(175), 1,
      anon_sym_DOT,
    ACTIONS(178), 1,
      anon_sym_LBRACK,
    ACTIONS(181), 1,
      aux_sym_escape_token1,
    ACTIONS(184), 1,
      aux_sym_escape_token2,
    ACTIONS(187), 1,
      aux_sym__char_token1,
    ACTIONS(128), 3,
      anon_sym_DOLLAR_LBRACE,
      anon_sym_RBRACE,
      anon_sym_COLON_COLON,
    STATE(19), 4,
      sym__index,
      sym_escape,
      sym__char,
      aux_sym_key_repeat1,
  [534] = 8,
    ACTIONS(25), 1,
      anon_sym_DOT,
    ACTIONS(27), 1,
      anon_sym_LBRACK,
    ACTIONS(29), 1,
      anon_sym_DOLLAR_LBRACE,
    ACTIONS(35), 1,
      aux_sym_escape_token1,
    ACTIONS(37), 1,
      aux_sym_escape_token2,
    ACTIONS(39), 1,
      aux_sym__char_token1,
    STATE(4), 3,
      sym_key,
      sym_substitution,
      aux_sym_substitution_repeat1,
    STATE(18), 4,
      sym__index,
      sym_escape,
      sym__char,
      aux_sym_key_repeat1,
  [564] = 8,
    ACTIONS(25), 1,
      anon_sym_DOT,
    ACTIONS(27), 1,
      anon_sym_LBRACK,
    ACTIONS(29), 1,
      anon_sym_DOLLAR_LBRACE,
    ACTIONS(35), 1,
      aux_sym_escape_token1,
    ACTIONS(37), 1,
      aux_sym_escape_token2,
    ACTIONS(39), 1,
      aux_sym__char_token1,
    STATE(2), 3,
      sym_key,
      sym_substitution,
      aux_sym_substitution_repeat1,
    STATE(18), 4,
      sym__index,
      sym_escape,
      sym__char,
      aux_sym_key_repeat1,
  [594] = 8,
    ACTIONS(104), 1,
      anon_sym_DOLLAR_LBRACE,
    ACTIONS(106), 1,
      anon_sym_BSLASH,
    ACTIONS(108), 1,
      aux_sym_escape_token1,
    ACTIONS(110), 1,
      aux_sym_escape_token2,
    ACTIONS(190), 1,
      aux_sym__char_token1,
    ACTIONS(192), 1,
      sym__eol,
    ACTIONS(194), 1,
      sym__eof,
    STATE(24), 5,
      sym_substitution,
      sym__linebreak,
      sym_escape,
      sym__char,
      aux_sym_value_repeat1,
  [623] = 2,
    ACTIONS(198), 4,
      anon_sym_BSLASH,
      aux_sym_escape_token1,
      aux_sym__char_token1,
      sym__eol,
    ACTIONS(196), 8,
      sym__eof,
      anon_sym_EQ,
      anon_sym_COLON,
      anon_sym_DOT,
      anon_sym_LBRACK,
      anon_sym_DOLLAR_LBRACE,
      aux_sym_escape_token2,
      sym__space,
  [640] = 8,
    ACTIONS(200), 1,
      anon_sym_DOLLAR_LBRACE,
    ACTIONS(203), 1,
      anon_sym_BSLASH,
    ACTIONS(206), 1,
      aux_sym_escape_token1,
    ACTIONS(209), 1,
      aux_sym_escape_token2,
    ACTIONS(212), 1,
      aux_sym__char_token1,
    ACTIONS(215), 1,
      sym__eol,
    ACTIONS(217), 1,
      sym__eof,
    STATE(24), 5,
      sym_substitution,
      sym__linebreak,
      sym_escape,
      sym__char,
      aux_sym_value_repeat1,
  [669] = 2,
    ACTIONS(221), 4,
      anon_sym_BSLASH,
      aux_sym_escape_token1,
      aux_sym__char_token1,
      sym__eol,
    ACTIONS(219), 8,
      sym__eof,
      anon_sym_EQ,
      anon_sym_COLON,
      anon_sym_DOT,
      anon_sym_LBRACK,
      anon_sym_DOLLAR_LBRACE,
      aux_sym_escape_token2,
      sym__space,
  [686] = 2,
    ACTIONS(225), 4,
      anon_sym_BSLASH,
      aux_sym_escape_token1,
      aux_sym__char_token1,
      sym__eol,
    ACTIONS(223), 8,
      sym__eof,
      anon_sym_EQ,
      anon_sym_COLON,
      anon_sym_DOT,
      anon_sym_LBRACK,
      anon_sym_DOLLAR_LBRACE,
      aux_sym_escape_token2,
      sym__space,
  [703] = 2,
    ACTIONS(229), 3,
      aux_sym_escape_token1,
      aux_sym__char_token1,
      sym__eol,
    ACTIONS(227), 7,
      sym__eof,
      ts_builtin_sym_end,
      anon_sym_DOT,
      anon_sym_LBRACK,
      aux_sym_escape_token2,
      sym_comment,
      sym__space,
  [718] = 2,
    ACTIONS(231), 3,
      aux_sym_escape_token1,
      aux_sym__char_token1,
      sym__eol,
    ACTIONS(51), 7,
      sym__eof,
      ts_builtin_sym_end,
      anon_sym_DOT,
      anon_sym_LBRACK,
      aux_sym_escape_token2,
      sym_comment,
      sym__space,
  [733] = 7,
    ACTIONS(233), 1,
      anon_sym_DOLLAR_LBRACE,
    ACTIONS(235), 1,
      anon_sym_RBRACE,
    ACTIONS(237), 1,
      aux_sym_escape_token1,
    ACTIONS(239), 1,
      aux_sym_escape_token2,
    ACTIONS(241), 1,
      aux_sym__char_token1,
    STATE(31), 1,
      aux_sym__content,
    STATE(47), 3,
      sym_substitution,
      sym_escape,
      sym__char,
  [757] = 2,
    ACTIONS(243), 3,
      anon_sym_COLON,
      aux_sym_escape_token1,
      aux_sym__char_token1,
    ACTIONS(245), 6,
      anon_sym_DOT,
      anon_sym_LBRACK,
      anon_sym_DOLLAR_LBRACE,
      anon_sym_RBRACE,
      anon_sym_COLON_COLON,
      aux_sym_escape_token2,
  [771] = 7,
    ACTIONS(247), 1,
      anon_sym_DOLLAR_LBRACE,
    ACTIONS(250), 1,
      anon_sym_RBRACE,
    ACTIONS(252), 1,
      aux_sym_escape_token1,
    ACTIONS(255), 1,
      aux_sym_escape_token2,
    ACTIONS(258), 1,
      aux_sym__char_token1,
    STATE(31), 1,
      aux_sym__content,
    STATE(47), 3,
      sym_substitution,
      sym_escape,
      sym__char,
  [795] = 2,
    ACTIONS(221), 3,
      anon_sym_COLON,
      aux_sym_escape_token1,
      aux_sym__char_token1,
    ACTIONS(219), 6,
      anon_sym_DOT,
      anon_sym_LBRACK,
      anon_sym_DOLLAR_LBRACE,
      anon_sym_RBRACE,
      anon_sym_COLON_COLON,
      aux_sym_escape_token2,
  [809] = 2,
    ACTIONS(261), 3,
      anon_sym_COLON,
      aux_sym_escape_token1,
      aux_sym__char_token1,
    ACTIONS(263), 6,
      anon_sym_DOT,
      anon_sym_LBRACK,
      anon_sym_DOLLAR_LBRACE,
      anon_sym_RBRACE,
      anon_sym_COLON_COLON,
      aux_sym_escape_token2,
  [823] = 2,
    ACTIONS(198), 3,
      anon_sym_COLON,
      aux_sym_escape_token1,
      aux_sym__char_token1,
    ACTIONS(196), 6,
      anon_sym_DOT,
      anon_sym_LBRACK,
      anon_sym_DOLLAR_LBRACE,
      anon_sym_RBRACE,
      anon_sym_COLON_COLON,
      aux_sym_escape_token2,
  [837] = 2,
    ACTIONS(265), 3,
      anon_sym_COLON,
      aux_sym_escape_token1,
      aux_sym__char_token1,
    ACTIONS(267), 6,
      anon_sym_DOT,
      anon_sym_LBRACK,
      anon_sym_DOLLAR_LBRACE,
      anon_sym_RBRACE,
      anon_sym_COLON_COLON,
      aux_sym_escape_token2,
  [851] = 2,
    ACTIONS(225), 3,
      anon_sym_COLON,
      aux_sym_escape_token1,
      aux_sym__char_token1,
    ACTIONS(223), 6,
      anon_sym_DOT,
      anon_sym_LBRACK,
      anon_sym_DOLLAR_LBRACE,
      anon_sym_RBRACE,
      anon_sym_COLON_COLON,
      aux_sym_escape_token2,
  [865] = 7,
    ACTIONS(233), 1,
      anon_sym_DOLLAR_LBRACE,
    ACTIONS(237), 1,
      aux_sym_escape_token1,
    ACTIONS(239), 1,
      aux_sym_escape_token2,
    ACTIONS(241), 1,
      aux_sym__char_token1,
    ACTIONS(269), 1,
      anon_sym_RBRACE,
    STATE(31), 1,
      aux_sym__content,
    STATE(47), 3,
      sym_substitution,
      sym_escape,
      sym__char,
  [889] = 6,
    ACTIONS(233), 1,
      anon_sym_DOLLAR_LBRACE,
    ACTIONS(237), 1,
      aux_sym_escape_token1,
    ACTIONS(239), 1,
      aux_sym_escape_token2,
    ACTIONS(241), 1,
      aux_sym__char_token1,
    STATE(29), 1,
      aux_sym__content,
    STATE(47), 3,
      sym_substitution,
      sym_escape,
      sym__char,
  [910] = 6,
    ACTIONS(233), 1,
      anon_sym_DOLLAR_LBRACE,
    ACTIONS(237), 1,
      aux_sym_escape_token1,
    ACTIONS(239), 1,
      aux_sym_escape_token2,
    ACTIONS(241), 1,
      aux_sym__char_token1,
    STATE(37), 1,
      aux_sym__content,
    STATE(47), 3,
      sym_substitution,
      sym_escape,
      sym__char,
  [931] = 2,
    ACTIONS(271), 3,
      sym__eof,
      anon_sym_DOLLAR_LBRACE,
      aux_sym_escape_token2,
    ACTIONS(273), 4,
      anon_sym_BSLASH,
      aux_sym_escape_token1,
      aux_sym__char_token1,
      sym__eol,
  [943] = 2,
    ACTIONS(223), 3,
      sym__eof,
      anon_sym_DOLLAR_LBRACE,
      aux_sym_escape_token2,
    ACTIONS(225), 4,
      anon_sym_BSLASH,
      aux_sym_escape_token1,
      aux_sym__char_token1,
      sym__eol,
  [955] = 2,
    ACTIONS(267), 3,
      sym__eof,
      anon_sym_DOLLAR_LBRACE,
      aux_sym_escape_token2,
    ACTIONS(265), 4,
      anon_sym_BSLASH,
      aux_sym_escape_token1,
      aux_sym__char_token1,
      sym__eol,
  [967] = 2,
    ACTIONS(245), 3,
      sym__eof,
      anon_sym_DOLLAR_LBRACE,
      aux_sym_escape_token2,
    ACTIONS(243), 4,
      anon_sym_BSLASH,
      aux_sym_escape_token1,
      aux_sym__char_token1,
      sym__eol,
  [979] = 2,
    ACTIONS(263), 3,
      sym__eof,
      anon_sym_DOLLAR_LBRACE,
      aux_sym_escape_token2,
    ACTIONS(261), 4,
      anon_sym_BSLASH,
      aux_sym_escape_token1,
      aux_sym__char_token1,
      sym__eol,
  [991] = 2,
    ACTIONS(265), 2,
      aux_sym_escape_token1,
      aux_sym__char_token1,
    ACTIONS(267), 3,
      anon_sym_DOLLAR_LBRACE,
      anon_sym_RBRACE,
      aux_sym_escape_token2,
  [1001] = 2,
    ACTIONS(261), 2,
      aux_sym_escape_token1,
      aux_sym__char_token1,
    ACTIONS(263), 3,
      anon_sym_DOLLAR_LBRACE,
      anon_sym_RBRACE,
      aux_sym_escape_token2,
  [1011] = 2,
    ACTIONS(277), 2,
      aux_sym_escape_token1,
      aux_sym__char_token1,
    ACTIONS(275), 3,
      anon_sym_DOLLAR_LBRACE,
      anon_sym_RBRACE,
      aux_sym_escape_token2,
  [1021] = 2,
    ACTIONS(243), 2,
      aux_sym_escape_token1,
      aux_sym__char_token1,
    ACTIONS(245), 3,
      anon_sym_DOLLAR_LBRACE,
      anon_sym_RBRACE,
      aux_sym_escape_token2,
  [1031] = 2,
    ACTIONS(225), 2,
      aux_sym_escape_token1,
      aux_sym__char_token1,
    ACTIONS(223), 3,
      anon_sym_DOLLAR_LBRACE,
      anon_sym_RBRACE,
      aux_sym_escape_token2,
  [1041] = 4,
    ACTIONS(279), 1,
      anon_sym_RBRACK,
    ACTIONS(281), 1,
      aux_sym__char_token1,
    STATE(54), 1,
      aux_sym__index_repeat1,
    STATE(58), 1,
      sym__char,
  [1054] = 4,
    ACTIONS(281), 1,
      aux_sym__char_token1,
    ACTIONS(283), 1,
      anon_sym_RBRACK,
    STATE(52), 1,
      aux_sym__index_repeat1,
    STATE(58), 1,
      sym__char,
  [1067] = 4,
    ACTIONS(281), 1,
      aux_sym__char_token1,
    ACTIONS(285), 1,
      anon_sym_RBRACK,
    STATE(53), 1,
      aux_sym__index_repeat1,
    STATE(58), 1,
      sym__char,
  [1080] = 4,
    ACTIONS(287), 1,
      anon_sym_RBRACK,
    ACTIONS(289), 1,
      aux_sym__char_token1,
    STATE(53), 1,
      aux_sym__index_repeat1,
    STATE(58), 1,
      sym__char,
  [1093] = 4,
    ACTIONS(281), 1,
      aux_sym__char_token1,
    ACTIONS(292), 1,
      anon_sym_RBRACK,
    STATE(53), 1,
      aux_sym__index_repeat1,
    STATE(58), 1,
      sym__char,
  [1106] = 1,
    ACTIONS(165), 2,
      sym__eof,
      sym__eol,
  [1111] = 1,
    ACTIONS(294), 2,
      sym__eof,
      sym__eol,
  [1116] = 1,
    ACTIONS(126), 2,
      sym__eof,
      sym__eol,
  [1121] = 2,
    ACTIONS(296), 1,
      anon_sym_RBRACK,
    ACTIONS(298), 1,
      aux_sym__char_token1,
  [1128] = 1,
    ACTIONS(159), 2,
      sym__eof,
      sym__eol,
  [1133] = 1,
    ACTIONS(169), 2,
      sym__eof,
      sym__eol,
  [1138] = 1,
    ACTIONS(300), 2,
      sym__eof,
      sym__eol,
  [1143] = 1,
    ACTIONS(302), 1,
      sym__eol,
  [1147] = 1,
    ACTIONS(304), 1,
      anon_sym_RBRACE,
  [1151] = 1,
    ACTIONS(306), 1,
      anon_sym_RBRACE,
  [1155] = 1,
    ACTIONS(308), 1,
      ts_builtin_sym_end,
  [1159] = 1,
    ACTIONS(310), 1,
      anon_sym_RBRACE,
  [1163] = 1,
    ACTIONS(312), 1,
      anon_sym_RBRACE,
  [1167] = 1,
    ACTIONS(314), 1,
      anon_sym_RBRACE,
  [1171] = 1,
    ACTIONS(316), 1,
      anon_sym_RBRACE,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(5)] = 0,
  [SMALL_STATE(6)] = 46,
  [SMALL_STATE(7)] = 92,
  [SMALL_STATE(8)] = 129,
  [SMALL_STATE(9)] = 168,
  [SMALL_STATE(10)] = 207,
  [SMALL_STATE(11)] = 240,
  [SMALL_STATE(12)] = 273,
  [SMALL_STATE(13)] = 310,
  [SMALL_STATE(14)] = 345,
  [SMALL_STATE(15)] = 380,
  [SMALL_STATE(16)] = 412,
  [SMALL_STATE(17)] = 442,
  [SMALL_STATE(18)] = 474,
  [SMALL_STATE(19)] = 504,
  [SMALL_STATE(20)] = 534,
  [SMALL_STATE(21)] = 564,
  [SMALL_STATE(22)] = 594,
  [SMALL_STATE(23)] = 623,
  [SMALL_STATE(24)] = 640,
  [SMALL_STATE(25)] = 669,
  [SMALL_STATE(26)] = 686,
  [SMALL_STATE(27)] = 703,
  [SMALL_STATE(28)] = 718,
  [SMALL_STATE(29)] = 733,
  [SMALL_STATE(30)] = 757,
  [SMALL_STATE(31)] = 771,
  [SMALL_STATE(32)] = 795,
  [SMALL_STATE(33)] = 809,
  [SMALL_STATE(34)] = 823,
  [SMALL_STATE(35)] = 837,
  [SMALL_STATE(36)] = 851,
  [SMALL_STATE(37)] = 865,
  [SMALL_STATE(38)] = 889,
  [SMALL_STATE(39)] = 910,
  [SMALL_STATE(40)] = 931,
  [SMALL_STATE(41)] = 943,
  [SMALL_STATE(42)] = 955,
  [SMALL_STATE(43)] = 967,
  [SMALL_STATE(44)] = 979,
  [SMALL_STATE(45)] = 991,
  [SMALL_STATE(46)] = 1001,
  [SMALL_STATE(47)] = 1011,
  [SMALL_STATE(48)] = 1021,
  [SMALL_STATE(49)] = 1031,
  [SMALL_STATE(50)] = 1041,
  [SMALL_STATE(51)] = 1054,
  [SMALL_STATE(52)] = 1067,
  [SMALL_STATE(53)] = 1080,
  [SMALL_STATE(54)] = 1093,
  [SMALL_STATE(55)] = 1106,
  [SMALL_STATE(56)] = 1111,
  [SMALL_STATE(57)] = 1116,
  [SMALL_STATE(58)] = 1121,
  [SMALL_STATE(59)] = 1128,
  [SMALL_STATE(60)] = 1133,
  [SMALL_STATE(61)] = 1138,
  [SMALL_STATE(62)] = 1143,
  [SMALL_STATE(63)] = 1147,
  [SMALL_STATE(64)] = 1151,
  [SMALL_STATE(65)] = 1155,
  [SMALL_STATE(66)] = 1159,
  [SMALL_STATE(67)] = 1163,
  [SMALL_STATE(68)] = 1167,
  [SMALL_STATE(69)] = 1171,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_file, 0, 0, 0),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(51),
  [9] = {.entry = {.count = 1, .reusable = false}}, SHIFT(26),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(59),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [17] = {.entry = {.count = 1, .reusable = false}}, SHIFT(11),
  [19] = {.entry = {.count = 1, .reusable = false}}, SHIFT(5),
  [21] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [23] = {.entry = {.count = 1, .reusable = false}}, SHIFT(39),
  [25] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [27] = {.entry = {.count = 1, .reusable = true}}, SHIFT(50),
  [29] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [31] = {.entry = {.count = 1, .reusable = true}}, SHIFT(48),
  [33] = {.entry = {.count = 1, .reusable = true}}, SHIFT(38),
  [35] = {.entry = {.count = 1, .reusable = false}}, SHIFT(36),
  [37] = {.entry = {.count = 1, .reusable = true}}, SHIFT(36),
  [39] = {.entry = {.count = 1, .reusable = false}}, SHIFT(18),
  [41] = {.entry = {.count = 1, .reusable = true}}, SHIFT(43),
  [43] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [45] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_file, 1, 0, 0),
  [47] = {.entry = {.count = 1, .reusable = false}}, SHIFT(6),
  [49] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [51] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_file_repeat1, 2, 0, 0),
  [53] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_file_repeat1, 2, 0, 0), SHIFT_REPEAT(11),
  [56] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_file_repeat1, 2, 0, 0), SHIFT_REPEAT(51),
  [59] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_file_repeat1, 2, 0, 0), SHIFT_REPEAT(26),
  [62] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_file_repeat1, 2, 0, 0), SHIFT_REPEAT(26),
  [65] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_file_repeat1, 2, 0, 0), SHIFT_REPEAT(59),
  [68] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_file_repeat1, 2, 0, 0), SHIFT_REPEAT(12),
  [71] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_file_repeat1, 2, 0, 0), SHIFT_REPEAT(11),
  [74] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_file_repeat1, 2, 0, 0), SHIFT_REPEAT(6),
  [77] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_file_repeat1, 2, 0, 0), SHIFT_REPEAT(6),
  [80] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_substitution_repeat1, 2, 0, 0),
  [82] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_substitution_repeat1, 2, 0, 0), SHIFT_REPEAT(18),
  [85] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_substitution_repeat1, 2, 0, 0), SHIFT_REPEAT(50),
  [88] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_substitution_repeat1, 2, 0, 0), SHIFT_REPEAT(20),
  [91] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_substitution_repeat1, 2, 0, 0),
  [93] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_substitution_repeat1, 2, 0, 0), SHIFT_REPEAT(36),
  [96] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_substitution_repeat1, 2, 0, 0), SHIFT_REPEAT(36),
  [99] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_substitution_repeat1, 2, 0, 0), SHIFT_REPEAT(18),
  [102] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [104] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [106] = {.entry = {.count = 1, .reusable = false}}, SHIFT(62),
  [108] = {.entry = {.count = 1, .reusable = false}}, SHIFT(41),
  [110] = {.entry = {.count = 1, .reusable = true}}, SHIFT(41),
  [112] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [114] = {.entry = {.count = 1, .reusable = false}}, SHIFT(22),
  [116] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_property, 1, 0, 0),
  [118] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_property, 1, 0, 0),
  [120] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [122] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [124] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_property, 2, 0, 0),
  [126] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_property, 2, 0, 0),
  [128] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_key_repeat1, 2, 0, 0),
  [130] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_key_repeat1, 2, 0, 0), SHIFT_REPEAT(10),
  [133] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_key_repeat1, 2, 0, 0), SHIFT_REPEAT(51),
  [136] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_key_repeat1, 2, 0, 0),
  [138] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_key_repeat1, 2, 0, 0), SHIFT_REPEAT(26),
  [141] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_key_repeat1, 2, 0, 0), SHIFT_REPEAT(26),
  [144] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_key_repeat1, 2, 0, 0), SHIFT_REPEAT(10),
  [147] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_key, 1, 0, 0),
  [149] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [151] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_key, 1, 0, 0),
  [153] = {.entry = {.count = 1, .reusable = false}}, SHIFT(10),
  [155] = {.entry = {.count = 1, .reusable = true}}, SHIFT(61),
  [157] = {.entry = {.count = 1, .reusable = false}}, SHIFT(28),
  [159] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [161] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [163] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_property, 3, 0, 0),
  [165] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_property, 3, 0, 0),
  [167] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_property, 4, 0, 0),
  [169] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_property, 4, 0, 0),
  [171] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [173] = {.entry = {.count = 1, .reusable = false}}, SHIFT(19),
  [175] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_key_repeat1, 2, 0, 0), SHIFT_REPEAT(19),
  [178] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_key_repeat1, 2, 0, 0), SHIFT_REPEAT(50),
  [181] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_key_repeat1, 2, 0, 0), SHIFT_REPEAT(36),
  [184] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_key_repeat1, 2, 0, 0), SHIFT_REPEAT(36),
  [187] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_key_repeat1, 2, 0, 0), SHIFT_REPEAT(19),
  [190] = {.entry = {.count = 1, .reusable = false}}, SHIFT(24),
  [192] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_value, 1, 0, 0),
  [194] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_value, 1, 0, 0),
  [196] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__index, 3, 0, 1),
  [198] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__index, 3, 0, 1),
  [200] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_value_repeat1, 2, 0, 0), SHIFT_REPEAT(16),
  [203] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_value_repeat1, 2, 0, 0), SHIFT_REPEAT(62),
  [206] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_value_repeat1, 2, 0, 0), SHIFT_REPEAT(41),
  [209] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_value_repeat1, 2, 0, 0), SHIFT_REPEAT(41),
  [212] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_value_repeat1, 2, 0, 0), SHIFT_REPEAT(24),
  [215] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_value_repeat1, 2, 0, 0),
  [217] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_value_repeat1, 2, 0, 0),
  [219] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__index, 2, 0, 0),
  [221] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__index, 2, 0, 0),
  [223] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_escape, 1, 0, 0),
  [225] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_escape, 1, 0, 0),
  [227] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_file_repeat1, 3, 0, 0),
  [229] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_file_repeat1, 3, 0, 0),
  [231] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_file_repeat1, 2, 0, 0),
  [233] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [235] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__secret, 2, 0, 3),
  [237] = {.entry = {.count = 1, .reusable = false}}, SHIFT(49),
  [239] = {.entry = {.count = 1, .reusable = true}}, SHIFT(49),
  [241] = {.entry = {.count = 1, .reusable = false}}, SHIFT(47),
  [243] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_substitution, 3, 0, 0),
  [245] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_substitution, 3, 0, 0),
  [247] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__content, 2, 0, 0), SHIFT_REPEAT(21),
  [250] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym__content, 2, 0, 0),
  [252] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym__content, 2, 0, 0), SHIFT_REPEAT(49),
  [255] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__content, 2, 0, 0), SHIFT_REPEAT(49),
  [258] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym__content, 2, 0, 0), SHIFT_REPEAT(47),
  [261] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_substitution, 4, 0, 4),
  [263] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_substitution, 4, 0, 4),
  [265] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_substitution, 4, 0, 0),
  [267] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_substitution, 4, 0, 0),
  [269] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__default, 2, 0, 2),
  [271] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__linebreak, 2, 0, 0),
  [273] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__linebreak, 2, 0, 0),
  [275] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym__content, 1, 0, 0),
  [277] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym__content, 1, 0, 0),
  [279] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
  [281] = {.entry = {.count = 1, .reusable = false}}, SHIFT(58),
  [283] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [285] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [287] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym__index_repeat1, 2, 0, 0),
  [289] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym__index_repeat1, 2, 0, 0), SHIFT_REPEAT(58),
  [292] = {.entry = {.count = 1, .reusable = true}}, SHIFT(34),
  [294] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_property, 5, 0, 0),
  [296] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym__index_repeat1, 1, 0, 0),
  [298] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym__index_repeat1, 1, 0, 0),
  [300] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [302] = {.entry = {.count = 1, .reusable = true}}, SHIFT(40),
  [304] = {.entry = {.count = 1, .reusable = true}}, SHIFT(42),
  [306] = {.entry = {.count = 1, .reusable = true}}, SHIFT(33),
  [308] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [310] = {.entry = {.count = 1, .reusable = true}}, SHIFT(46),
  [312] = {.entry = {.count = 1, .reusable = true}}, SHIFT(45),
  [314] = {.entry = {.count = 1, .reusable = true}}, SHIFT(35),
  [316] = {.entry = {.count = 1, .reusable = true}}, SHIFT(44),
};

enum ts_external_scanner_symbol_identifiers {
  ts_external_token__eof = 0,
};

static const TSSymbol ts_external_scanner_symbol_map[EXTERNAL_TOKEN_COUNT] = {
  [ts_external_token__eof] = sym__eof,
};

static const bool ts_external_scanner_states[2][EXTERNAL_TOKEN_COUNT] = {
  [1] = {
    [ts_external_token__eof] = true,
  },
};

#ifdef __cplusplus
extern "C" {
#endif
void *tree_sitter_properties_external_scanner_create(void);
void tree_sitter_properties_external_scanner_destroy(void *);
bool tree_sitter_properties_external_scanner_scan(void *, TSLexer *, const bool *);
unsigned tree_sitter_properties_external_scanner_serialize(void *, char *);
void tree_sitter_properties_external_scanner_deserialize(void *, const char *, unsigned);

#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_properties(void) {
  static const TSLanguage language = {
    .version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = ts_lex_modes,
    .lex_fn = ts_lex,
    .external_scanner = {
      &ts_external_scanner_states[0][0],
      ts_external_scanner_symbol_map,
      tree_sitter_properties_external_scanner_create,
      tree_sitter_properties_external_scanner_destroy,
      tree_sitter_properties_external_scanner_scan,
      tree_sitter_properties_external_scanner_serialize,
      tree_sitter_properties_external_scanner_deserialize,
    },
    .primary_state_ids = ts_primary_state_ids,
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
