#include "parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 14
#define STATE_COUNT 98
#define LARGE_STATE_COUNT 13
#define SYMBOL_COUNT 49
#define ALIAS_COUNT 0
#define TOKEN_COUNT 24
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 12
#define MAX_ALIAS_SEQUENCE_LENGTH 6
#define PRODUCTION_ID_COUNT 10

enum ts_symbol_identifiers {
  sym_symbol = 1,
  anon_sym_GT = 2,
  anon_sym_PLUS = 3,
  anon_sym_DASH = 4,
  anon_sym_STAR = 5,
  anon_sym_SLASH = 6,
  anon_sym_not = 7,
  anon_sym_LPAREN = 8,
  anon_sym_RPAREN = 9,
  sym_int = 10,
  sym_float = 11,
  sym_str = 12,
  anon_sym_true = 13,
  anon_sym_false = 14,
  anon_sym_COLON = 15,
  anon_sym_COMMA = 16,
  anon_sym_LBRACE = 17,
  anon_sym_RBRACE = 18,
  anon_sym_fn = 19,
  anon_sym_EQ = 20,
  anon_sym_struct = 21,
  anon_sym_LBRACK = 22,
  anon_sym_RBRACK = 23,
  sym_source_file = 24,
  sym_expr = 25,
  sym_binary_op = 26,
  sym_unary_op = 27,
  sym_paren = 28,
  sym_bool = 29,
  sym_param = 30,
  sym_params = 31,
  sym_block = 32,
  sym_fn = 33,
  sym_args = 34,
  sym_call = 35,
  sym_def = 36,
  sym_field = 37,
  sym_fields = 38,
  sym_struct = 39,
  sym_array = 40,
  sym_pair = 41,
  sym_pairs = 42,
  sym_map = 43,
  aux_sym_source_file_repeat1 = 44,
  aux_sym_params_repeat1 = 45,
  aux_sym_args_repeat1 = 46,
  aux_sym_fields_repeat1 = 47,
  aux_sym_pairs_repeat1 = 48,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [sym_symbol] = "symbol",
  [anon_sym_GT] = ">",
  [anon_sym_PLUS] = "+",
  [anon_sym_DASH] = "-",
  [anon_sym_STAR] = "*",
  [anon_sym_SLASH] = "/",
  [anon_sym_not] = "not",
  [anon_sym_LPAREN] = "(",
  [anon_sym_RPAREN] = ")",
  [sym_int] = "int",
  [sym_float] = "float",
  [sym_str] = "str",
  [anon_sym_true] = "true",
  [anon_sym_false] = "false",
  [anon_sym_COLON] = ":",
  [anon_sym_COMMA] = ",",
  [anon_sym_LBRACE] = "{",
  [anon_sym_RBRACE] = "}",
  [anon_sym_fn] = "fn",
  [anon_sym_EQ] = "=",
  [anon_sym_struct] = "struct",
  [anon_sym_LBRACK] = "[",
  [anon_sym_RBRACK] = "]",
  [sym_source_file] = "source_file",
  [sym_expr] = "expr",
  [sym_binary_op] = "binary_op",
  [sym_unary_op] = "unary_op",
  [sym_paren] = "paren",
  [sym_bool] = "bool",
  [sym_param] = "param",
  [sym_params] = "params",
  [sym_block] = "block",
  [sym_fn] = "fn",
  [sym_args] = "args",
  [sym_call] = "call",
  [sym_def] = "def",
  [sym_field] = "field",
  [sym_fields] = "fields",
  [sym_struct] = "struct",
  [sym_array] = "array",
  [sym_pair] = "pair",
  [sym_pairs] = "pairs",
  [sym_map] = "map",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_params_repeat1] = "params_repeat1",
  [aux_sym_args_repeat1] = "args_repeat1",
  [aux_sym_fields_repeat1] = "fields_repeat1",
  [aux_sym_pairs_repeat1] = "pairs_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [sym_symbol] = sym_symbol,
  [anon_sym_GT] = anon_sym_GT,
  [anon_sym_PLUS] = anon_sym_PLUS,
  [anon_sym_DASH] = anon_sym_DASH,
  [anon_sym_STAR] = anon_sym_STAR,
  [anon_sym_SLASH] = anon_sym_SLASH,
  [anon_sym_not] = anon_sym_not,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [sym_int] = sym_int,
  [sym_float] = sym_float,
  [sym_str] = sym_str,
  [anon_sym_true] = anon_sym_true,
  [anon_sym_false] = anon_sym_false,
  [anon_sym_COLON] = anon_sym_COLON,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [anon_sym_LBRACE] = anon_sym_LBRACE,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [anon_sym_fn] = anon_sym_fn,
  [anon_sym_EQ] = anon_sym_EQ,
  [anon_sym_struct] = anon_sym_struct,
  [anon_sym_LBRACK] = anon_sym_LBRACK,
  [anon_sym_RBRACK] = anon_sym_RBRACK,
  [sym_source_file] = sym_source_file,
  [sym_expr] = sym_expr,
  [sym_binary_op] = sym_binary_op,
  [sym_unary_op] = sym_unary_op,
  [sym_paren] = sym_paren,
  [sym_bool] = sym_bool,
  [sym_param] = sym_param,
  [sym_params] = sym_params,
  [sym_block] = sym_block,
  [sym_fn] = sym_fn,
  [sym_args] = sym_args,
  [sym_call] = sym_call,
  [sym_def] = sym_def,
  [sym_field] = sym_field,
  [sym_fields] = sym_fields,
  [sym_struct] = sym_struct,
  [sym_array] = sym_array,
  [sym_pair] = sym_pair,
  [sym_pairs] = sym_pairs,
  [sym_map] = sym_map,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_params_repeat1] = aux_sym_params_repeat1,
  [aux_sym_args_repeat1] = aux_sym_args_repeat1,
  [aux_sym_fields_repeat1] = aux_sym_fields_repeat1,
  [aux_sym_pairs_repeat1] = aux_sym_pairs_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [sym_symbol] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PLUS] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_STAR] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SLASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_not] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [sym_int] = {
    .visible = true,
    .named = true,
  },
  [sym_float] = {
    .visible = true,
    .named = true,
  },
  [sym_str] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_true] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_false] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COLON] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_fn] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_struct] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACK] = {
    .visible = true,
    .named = false,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym_expr] = {
    .visible = true,
    .named = true,
  },
  [sym_binary_op] = {
    .visible = true,
    .named = true,
  },
  [sym_unary_op] = {
    .visible = true,
    .named = true,
  },
  [sym_paren] = {
    .visible = true,
    .named = true,
  },
  [sym_bool] = {
    .visible = true,
    .named = true,
  },
  [sym_param] = {
    .visible = true,
    .named = true,
  },
  [sym_params] = {
    .visible = true,
    .named = true,
  },
  [sym_block] = {
    .visible = true,
    .named = true,
  },
  [sym_fn] = {
    .visible = true,
    .named = true,
  },
  [sym_args] = {
    .visible = true,
    .named = true,
  },
  [sym_call] = {
    .visible = true,
    .named = true,
  },
  [sym_def] = {
    .visible = true,
    .named = true,
  },
  [sym_field] = {
    .visible = true,
    .named = true,
  },
  [sym_fields] = {
    .visible = true,
    .named = true,
  },
  [sym_struct] = {
    .visible = true,
    .named = true,
  },
  [sym_array] = {
    .visible = true,
    .named = true,
  },
  [sym_pair] = {
    .visible = true,
    .named = true,
  },
  [sym_pairs] = {
    .visible = true,
    .named = true,
  },
  [sym_map] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_params_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_args_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_fields_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_pairs_repeat1] = {
    .visible = false,
    .named = false,
  },
};

enum ts_field_identifiers {
  field_args = 1,
  field_body = 2,
  field_fn = 3,
  field_key = 4,
  field_left = 5,
  field_name = 6,
  field_operator = 7,
  field_params = 8,
  field_return_type = 9,
  field_right = 10,
  field_type = 11,
  field_value = 12,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_args] = "args",
  [field_body] = "body",
  [field_fn] = "fn",
  [field_key] = "key",
  [field_left] = "left",
  [field_name] = "name",
  [field_operator] = "operator",
  [field_params] = "params",
  [field_return_type] = "return_type",
  [field_right] = "right",
  [field_type] = "type",
  [field_value] = "value",
};

static const TSFieldMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 2},
  [2] = {.index = 2, .length = 3},
  [3] = {.index = 5, .length = 1},
  [4] = {.index = 6, .length = 2},
  [5] = {.index = 8, .length = 2},
  [6] = {.index = 10, .length = 3},
  [7] = {.index = 13, .length = 2},
  [8] = {.index = 15, .length = 2},
  [9] = {.index = 17, .length = 3},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_name, 0},
    {field_value, 2},
  [2] =
    {field_left, 0},
    {field_operator, 1},
    {field_right, 2},
  [5] =
    {field_fn, 0},
  [6] =
    {field_key, 0},
    {field_value, 2},
  [8] =
    {field_args, 2},
    {field_fn, 0},
  [10] =
    {field_name, 0},
    {field_type, 2},
    {field_value, 4},
  [13] =
    {field_body, 4},
    {field_return_type, 3},
  [15] =
    {field_name, 0},
    {field_type, 2},
  [17] =
    {field_body, 5},
    {field_params, 2},
    {field_return_type, 4},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 39,
  [40] = 40,
  [41] = 41,
  [42] = 42,
  [43] = 43,
  [44] = 44,
  [45] = 45,
  [46] = 46,
  [47] = 47,
  [48] = 48,
  [49] = 49,
  [50] = 50,
  [51] = 51,
  [52] = 52,
  [53] = 53,
  [54] = 54,
  [55] = 55,
  [56] = 56,
  [57] = 57,
  [58] = 58,
  [59] = 59,
  [60] = 60,
  [61] = 61,
  [62] = 62,
  [63] = 63,
  [64] = 64,
  [65] = 65,
  [66] = 66,
  [67] = 67,
  [68] = 68,
  [69] = 69,
  [70] = 70,
  [71] = 71,
  [72] = 72,
  [73] = 73,
  [74] = 74,
  [75] = 75,
  [76] = 76,
  [77] = 77,
  [78] = 78,
  [79] = 79,
  [80] = 80,
  [81] = 81,
  [82] = 82,
  [83] = 83,
  [84] = 84,
  [85] = 85,
  [86] = 86,
  [87] = 87,
  [88] = 88,
  [89] = 89,
  [90] = 90,
  [91] = 91,
  [92] = 92,
  [93] = 93,
  [94] = 94,
  [95] = 95,
  [96] = 96,
  [97] = 97,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(3);
      if (lookahead == '"') ADVANCE(1);
      if (lookahead == '(') ADVANCE(9);
      if (lookahead == ')') ADVANCE(10);
      if (lookahead == '*') ADVANCE(7);
      if (lookahead == '+') ADVANCE(5);
      if (lookahead == ',') ADVANCE(16);
      if (lookahead == '-') ADVANCE(6);
      if (lookahead == '/') ADVANCE(8);
      if (lookahead == ':') ADVANCE(15);
      if (lookahead == '=') ADVANCE(19);
      if (lookahead == '>') ADVANCE(4);
      if (lookahead == '[') ADVANCE(20);
      if (lookahead == ']') ADVANCE(21);
      if (lookahead == '{') ADVANCE(17);
      if (lookahead == '}') ADVANCE(18);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0)
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(11);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(14);
      END_STATE();
    case 1:
      if (lookahead == '"') ADVANCE(13);
      if (lookahead != 0) ADVANCE(1);
      END_STATE();
    case 2:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(12);
      END_STATE();
    case 3:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 4:
      ACCEPT_TOKEN(anon_sym_GT);
      END_STATE();
    case 5:
      ACCEPT_TOKEN(anon_sym_PLUS);
      END_STATE();
    case 6:
      ACCEPT_TOKEN(anon_sym_DASH);
      END_STATE();
    case 7:
      ACCEPT_TOKEN(anon_sym_STAR);
      END_STATE();
    case 8:
      ACCEPT_TOKEN(anon_sym_SLASH);
      END_STATE();
    case 9:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 10:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 11:
      ACCEPT_TOKEN(sym_int);
      if (lookahead == '.') ADVANCE(2);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(11);
      END_STATE();
    case 12:
      ACCEPT_TOKEN(sym_float);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(12);
      END_STATE();
    case 13:
      ACCEPT_TOKEN(sym_str);
      END_STATE();
    case 14:
      ACCEPT_TOKEN(sym_symbol);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(14);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(anon_sym_COLON);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(anon_sym_EQ);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(anon_sym_LBRACK);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(anon_sym_RBRACK);
      END_STATE();
    default:
      return false;
  }
}

static bool ts_lex_keywords(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (lookahead == 'f') ADVANCE(1);
      if (lookahead == 'n') ADVANCE(2);
      if (lookahead == 's') ADVANCE(3);
      if (lookahead == 't') ADVANCE(4);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0)
      END_STATE();
    case 1:
      if (lookahead == 'a') ADVANCE(5);
      if (lookahead == 'n') ADVANCE(6);
      END_STATE();
    case 2:
      if (lookahead == 'o') ADVANCE(7);
      END_STATE();
    case 3:
      if (lookahead == 't') ADVANCE(8);
      END_STATE();
    case 4:
      if (lookahead == 'r') ADVANCE(9);
      END_STATE();
    case 5:
      if (lookahead == 'l') ADVANCE(10);
      END_STATE();
    case 6:
      ACCEPT_TOKEN(anon_sym_fn);
      END_STATE();
    case 7:
      if (lookahead == 't') ADVANCE(11);
      END_STATE();
    case 8:
      if (lookahead == 'r') ADVANCE(12);
      END_STATE();
    case 9:
      if (lookahead == 'u') ADVANCE(13);
      END_STATE();
    case 10:
      if (lookahead == 's') ADVANCE(14);
      END_STATE();
    case 11:
      ACCEPT_TOKEN(anon_sym_not);
      END_STATE();
    case 12:
      if (lookahead == 'u') ADVANCE(15);
      END_STATE();
    case 13:
      if (lookahead == 'e') ADVANCE(16);
      END_STATE();
    case 14:
      if (lookahead == 'e') ADVANCE(17);
      END_STATE();
    case 15:
      if (lookahead == 'c') ADVANCE(18);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(anon_sym_true);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(anon_sym_false);
      END_STATE();
    case 18:
      if (lookahead == 't') ADVANCE(19);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(anon_sym_struct);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 0},
  [2] = {.lex_state = 0},
  [3] = {.lex_state = 0},
  [4] = {.lex_state = 0},
  [5] = {.lex_state = 0},
  [6] = {.lex_state = 0},
  [7] = {.lex_state = 0},
  [8] = {.lex_state = 0},
  [9] = {.lex_state = 0},
  [10] = {.lex_state = 0},
  [11] = {.lex_state = 0},
  [12] = {.lex_state = 0},
  [13] = {.lex_state = 0},
  [14] = {.lex_state = 0},
  [15] = {.lex_state = 0},
  [16] = {.lex_state = 0},
  [17] = {.lex_state = 0},
  [18] = {.lex_state = 0},
  [19] = {.lex_state = 0},
  [20] = {.lex_state = 0},
  [21] = {.lex_state = 0},
  [22] = {.lex_state = 0},
  [23] = {.lex_state = 0},
  [24] = {.lex_state = 0},
  [25] = {.lex_state = 0},
  [26] = {.lex_state = 0},
  [27] = {.lex_state = 0},
  [28] = {.lex_state = 0},
  [29] = {.lex_state = 0},
  [30] = {.lex_state = 0},
  [31] = {.lex_state = 0},
  [32] = {.lex_state = 0},
  [33] = {.lex_state = 0},
  [34] = {.lex_state = 0},
  [35] = {.lex_state = 0},
  [36] = {.lex_state = 0},
  [37] = {.lex_state = 0},
  [38] = {.lex_state = 0},
  [39] = {.lex_state = 0},
  [40] = {.lex_state = 0},
  [41] = {.lex_state = 0},
  [42] = {.lex_state = 0},
  [43] = {.lex_state = 0},
  [44] = {.lex_state = 0},
  [45] = {.lex_state = 0},
  [46] = {.lex_state = 0},
  [47] = {.lex_state = 0},
  [48] = {.lex_state = 0},
  [49] = {.lex_state = 0},
  [50] = {.lex_state = 0},
  [51] = {.lex_state = 0},
  [52] = {.lex_state = 0},
  [53] = {.lex_state = 0},
  [54] = {.lex_state = 0},
  [55] = {.lex_state = 0},
  [56] = {.lex_state = 0},
  [57] = {.lex_state = 0},
  [58] = {.lex_state = 0},
  [59] = {.lex_state = 0},
  [60] = {.lex_state = 0},
  [61] = {.lex_state = 0},
  [62] = {.lex_state = 0},
  [63] = {.lex_state = 0},
  [64] = {.lex_state = 0},
  [65] = {.lex_state = 0},
  [66] = {.lex_state = 0},
  [67] = {.lex_state = 0},
  [68] = {.lex_state = 0},
  [69] = {.lex_state = 0},
  [70] = {.lex_state = 0},
  [71] = {.lex_state = 0},
  [72] = {.lex_state = 0},
  [73] = {.lex_state = 0},
  [74] = {.lex_state = 0},
  [75] = {.lex_state = 0},
  [76] = {.lex_state = 0},
  [77] = {.lex_state = 0},
  [78] = {.lex_state = 0},
  [79] = {.lex_state = 0},
  [80] = {.lex_state = 0},
  [81] = {.lex_state = 0},
  [82] = {.lex_state = 0},
  [83] = {.lex_state = 0},
  [84] = {.lex_state = 0},
  [85] = {.lex_state = 0},
  [86] = {.lex_state = 0},
  [87] = {.lex_state = 0},
  [88] = {.lex_state = 0},
  [89] = {.lex_state = 0},
  [90] = {.lex_state = 0},
  [91] = {.lex_state = 0},
  [92] = {.lex_state = 0},
  [93] = {.lex_state = 0},
  [94] = {.lex_state = 0},
  [95] = {.lex_state = 0},
  [96] = {.lex_state = 0},
  [97] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [0] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [sym_symbol] = ACTIONS(1),
    [anon_sym_GT] = ACTIONS(1),
    [anon_sym_PLUS] = ACTIONS(1),
    [anon_sym_DASH] = ACTIONS(1),
    [anon_sym_STAR] = ACTIONS(1),
    [anon_sym_SLASH] = ACTIONS(1),
    [anon_sym_not] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [sym_int] = ACTIONS(1),
    [sym_float] = ACTIONS(1),
    [sym_str] = ACTIONS(1),
    [anon_sym_true] = ACTIONS(1),
    [anon_sym_false] = ACTIONS(1),
    [anon_sym_COLON] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
    [anon_sym_LBRACE] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [anon_sym_fn] = ACTIONS(1),
    [anon_sym_EQ] = ACTIONS(1),
    [anon_sym_struct] = ACTIONS(1),
    [anon_sym_LBRACK] = ACTIONS(1),
    [anon_sym_RBRACK] = ACTIONS(1),
  },
  [1] = {
    [sym_source_file] = STATE(97),
    [sym_expr] = STATE(51),
    [sym_binary_op] = STATE(50),
    [sym_unary_op] = STATE(50),
    [sym_paren] = STATE(50),
    [sym_bool] = STATE(50),
    [sym_fn] = STATE(50),
    [sym_call] = STATE(50),
    [sym_def] = STATE(50),
    [sym_struct] = STATE(50),
    [sym_array] = STATE(50),
    [sym_map] = STATE(50),
    [aux_sym_source_file_repeat1] = STATE(4),
    [ts_builtin_sym_end] = ACTIONS(3),
    [sym_symbol] = ACTIONS(5),
    [anon_sym_DASH] = ACTIONS(7),
    [anon_sym_not] = ACTIONS(9),
    [anon_sym_LPAREN] = ACTIONS(11),
    [sym_int] = ACTIONS(13),
    [sym_float] = ACTIONS(15),
    [sym_str] = ACTIONS(15),
    [anon_sym_true] = ACTIONS(17),
    [anon_sym_false] = ACTIONS(17),
    [anon_sym_LBRACE] = ACTIONS(19),
    [anon_sym_fn] = ACTIONS(21),
    [anon_sym_struct] = ACTIONS(23),
    [anon_sym_LBRACK] = ACTIONS(25),
  },
  [2] = {
    [sym_expr] = STATE(51),
    [sym_binary_op] = STATE(50),
    [sym_unary_op] = STATE(50),
    [sym_paren] = STATE(50),
    [sym_bool] = STATE(50),
    [sym_fn] = STATE(50),
    [sym_call] = STATE(50),
    [sym_def] = STATE(50),
    [sym_struct] = STATE(50),
    [sym_array] = STATE(50),
    [sym_map] = STATE(50),
    [aux_sym_source_file_repeat1] = STATE(2),
    [ts_builtin_sym_end] = ACTIONS(27),
    [sym_symbol] = ACTIONS(29),
    [anon_sym_DASH] = ACTIONS(32),
    [anon_sym_not] = ACTIONS(35),
    [anon_sym_LPAREN] = ACTIONS(38),
    [sym_int] = ACTIONS(41),
    [sym_float] = ACTIONS(44),
    [sym_str] = ACTIONS(44),
    [anon_sym_true] = ACTIONS(47),
    [anon_sym_false] = ACTIONS(47),
    [anon_sym_LBRACE] = ACTIONS(50),
    [anon_sym_RBRACE] = ACTIONS(27),
    [anon_sym_fn] = ACTIONS(53),
    [anon_sym_struct] = ACTIONS(56),
    [anon_sym_LBRACK] = ACTIONS(59),
  },
  [3] = {
    [sym_expr] = STATE(54),
    [sym_binary_op] = STATE(50),
    [sym_unary_op] = STATE(50),
    [sym_paren] = STATE(50),
    [sym_bool] = STATE(50),
    [sym_fn] = STATE(50),
    [sym_call] = STATE(50),
    [sym_def] = STATE(50),
    [sym_struct] = STATE(50),
    [sym_array] = STATE(50),
    [sym_map] = STATE(50),
    [aux_sym_args_repeat1] = STATE(72),
    [sym_symbol] = ACTIONS(5),
    [anon_sym_DASH] = ACTIONS(7),
    [anon_sym_not] = ACTIONS(9),
    [anon_sym_LPAREN] = ACTIONS(11),
    [sym_int] = ACTIONS(13),
    [sym_float] = ACTIONS(15),
    [sym_str] = ACTIONS(15),
    [anon_sym_true] = ACTIONS(17),
    [anon_sym_false] = ACTIONS(17),
    [anon_sym_COMMA] = ACTIONS(62),
    [anon_sym_LBRACE] = ACTIONS(19),
    [anon_sym_fn] = ACTIONS(21),
    [anon_sym_struct] = ACTIONS(23),
    [anon_sym_LBRACK] = ACTIONS(25),
    [anon_sym_RBRACK] = ACTIONS(64),
  },
  [4] = {
    [sym_expr] = STATE(51),
    [sym_binary_op] = STATE(50),
    [sym_unary_op] = STATE(50),
    [sym_paren] = STATE(50),
    [sym_bool] = STATE(50),
    [sym_fn] = STATE(50),
    [sym_call] = STATE(50),
    [sym_def] = STATE(50),
    [sym_struct] = STATE(50),
    [sym_array] = STATE(50),
    [sym_map] = STATE(50),
    [aux_sym_source_file_repeat1] = STATE(2),
    [ts_builtin_sym_end] = ACTIONS(66),
    [sym_symbol] = ACTIONS(5),
    [anon_sym_DASH] = ACTIONS(7),
    [anon_sym_not] = ACTIONS(9),
    [anon_sym_LPAREN] = ACTIONS(11),
    [sym_int] = ACTIONS(13),
    [sym_float] = ACTIONS(15),
    [sym_str] = ACTIONS(15),
    [anon_sym_true] = ACTIONS(17),
    [anon_sym_false] = ACTIONS(17),
    [anon_sym_LBRACE] = ACTIONS(19),
    [anon_sym_fn] = ACTIONS(21),
    [anon_sym_struct] = ACTIONS(23),
    [anon_sym_LBRACK] = ACTIONS(25),
  },
  [5] = {
    [sym_expr] = STATE(51),
    [sym_binary_op] = STATE(50),
    [sym_unary_op] = STATE(50),
    [sym_paren] = STATE(50),
    [sym_bool] = STATE(50),
    [sym_fn] = STATE(50),
    [sym_call] = STATE(50),
    [sym_def] = STATE(50),
    [sym_struct] = STATE(50),
    [sym_array] = STATE(50),
    [sym_map] = STATE(50),
    [aux_sym_source_file_repeat1] = STATE(2),
    [sym_symbol] = ACTIONS(5),
    [anon_sym_DASH] = ACTIONS(7),
    [anon_sym_not] = ACTIONS(9),
    [anon_sym_LPAREN] = ACTIONS(11),
    [sym_int] = ACTIONS(13),
    [sym_float] = ACTIONS(15),
    [sym_str] = ACTIONS(15),
    [anon_sym_true] = ACTIONS(17),
    [anon_sym_false] = ACTIONS(17),
    [anon_sym_LBRACE] = ACTIONS(19),
    [anon_sym_RBRACE] = ACTIONS(68),
    [anon_sym_fn] = ACTIONS(21),
    [anon_sym_struct] = ACTIONS(23),
    [anon_sym_LBRACK] = ACTIONS(25),
  },
  [6] = {
    [sym_expr] = STATE(53),
    [sym_binary_op] = STATE(50),
    [sym_unary_op] = STATE(50),
    [sym_paren] = STATE(50),
    [sym_bool] = STATE(50),
    [sym_fn] = STATE(50),
    [sym_args] = STATE(93),
    [sym_call] = STATE(50),
    [sym_def] = STATE(50),
    [sym_struct] = STATE(50),
    [sym_array] = STATE(50),
    [sym_map] = STATE(50),
    [sym_symbol] = ACTIONS(5),
    [anon_sym_DASH] = ACTIONS(7),
    [anon_sym_not] = ACTIONS(9),
    [anon_sym_LPAREN] = ACTIONS(11),
    [anon_sym_RPAREN] = ACTIONS(70),
    [sym_int] = ACTIONS(13),
    [sym_float] = ACTIONS(15),
    [sym_str] = ACTIONS(15),
    [anon_sym_true] = ACTIONS(17),
    [anon_sym_false] = ACTIONS(17),
    [anon_sym_LBRACE] = ACTIONS(19),
    [anon_sym_fn] = ACTIONS(21),
    [anon_sym_struct] = ACTIONS(23),
    [anon_sym_LBRACK] = ACTIONS(25),
  },
  [7] = {
    [sym_expr] = STATE(51),
    [sym_binary_op] = STATE(50),
    [sym_unary_op] = STATE(50),
    [sym_paren] = STATE(50),
    [sym_bool] = STATE(50),
    [sym_fn] = STATE(50),
    [sym_call] = STATE(50),
    [sym_def] = STATE(50),
    [sym_struct] = STATE(50),
    [sym_array] = STATE(50),
    [sym_map] = STATE(50),
    [aux_sym_source_file_repeat1] = STATE(5),
    [sym_symbol] = ACTIONS(5),
    [anon_sym_DASH] = ACTIONS(7),
    [anon_sym_not] = ACTIONS(9),
    [anon_sym_LPAREN] = ACTIONS(11),
    [sym_int] = ACTIONS(13),
    [sym_float] = ACTIONS(15),
    [sym_str] = ACTIONS(15),
    [anon_sym_true] = ACTIONS(17),
    [anon_sym_false] = ACTIONS(17),
    [anon_sym_LBRACE] = ACTIONS(19),
    [anon_sym_RBRACE] = ACTIONS(72),
    [anon_sym_fn] = ACTIONS(21),
    [anon_sym_struct] = ACTIONS(23),
    [anon_sym_LBRACK] = ACTIONS(25),
  },
  [8] = {
    [sym_expr] = STATE(52),
    [sym_binary_op] = STATE(50),
    [sym_unary_op] = STATE(50),
    [sym_paren] = STATE(50),
    [sym_bool] = STATE(50),
    [sym_fn] = STATE(50),
    [sym_call] = STATE(50),
    [sym_def] = STATE(50),
    [sym_struct] = STATE(50),
    [sym_array] = STATE(50),
    [sym_map] = STATE(50),
    [sym_symbol] = ACTIONS(5),
    [anon_sym_DASH] = ACTIONS(7),
    [anon_sym_not] = ACTIONS(9),
    [anon_sym_LPAREN] = ACTIONS(11),
    [sym_int] = ACTIONS(13),
    [sym_float] = ACTIONS(15),
    [sym_str] = ACTIONS(15),
    [anon_sym_true] = ACTIONS(17),
    [anon_sym_false] = ACTIONS(17),
    [anon_sym_LBRACE] = ACTIONS(19),
    [anon_sym_fn] = ACTIONS(21),
    [anon_sym_struct] = ACTIONS(23),
    [anon_sym_LBRACK] = ACTIONS(25),
    [anon_sym_RBRACK] = ACTIONS(74),
  },
  [9] = {
    [sym_expr] = STATE(52),
    [sym_binary_op] = STATE(50),
    [sym_unary_op] = STATE(50),
    [sym_paren] = STATE(50),
    [sym_bool] = STATE(50),
    [sym_fn] = STATE(50),
    [sym_call] = STATE(50),
    [sym_def] = STATE(50),
    [sym_struct] = STATE(50),
    [sym_array] = STATE(50),
    [sym_map] = STATE(50),
    [sym_symbol] = ACTIONS(5),
    [anon_sym_DASH] = ACTIONS(7),
    [anon_sym_not] = ACTIONS(9),
    [anon_sym_LPAREN] = ACTIONS(11),
    [anon_sym_RPAREN] = ACTIONS(76),
    [sym_int] = ACTIONS(13),
    [sym_float] = ACTIONS(15),
    [sym_str] = ACTIONS(15),
    [anon_sym_true] = ACTIONS(17),
    [anon_sym_false] = ACTIONS(17),
    [anon_sym_LBRACE] = ACTIONS(19),
    [anon_sym_fn] = ACTIONS(21),
    [anon_sym_struct] = ACTIONS(23),
    [anon_sym_LBRACK] = ACTIONS(25),
  },
  [10] = {
    [sym_expr] = STATE(52),
    [sym_binary_op] = STATE(50),
    [sym_unary_op] = STATE(50),
    [sym_paren] = STATE(50),
    [sym_bool] = STATE(50),
    [sym_fn] = STATE(50),
    [sym_call] = STATE(50),
    [sym_def] = STATE(50),
    [sym_struct] = STATE(50),
    [sym_array] = STATE(50),
    [sym_map] = STATE(50),
    [sym_symbol] = ACTIONS(5),
    [anon_sym_DASH] = ACTIONS(7),
    [anon_sym_not] = ACTIONS(9),
    [anon_sym_LPAREN] = ACTIONS(11),
    [anon_sym_RPAREN] = ACTIONS(78),
    [sym_int] = ACTIONS(13),
    [sym_float] = ACTIONS(15),
    [sym_str] = ACTIONS(15),
    [anon_sym_true] = ACTIONS(17),
    [anon_sym_false] = ACTIONS(17),
    [anon_sym_LBRACE] = ACTIONS(19),
    [anon_sym_fn] = ACTIONS(21),
    [anon_sym_struct] = ACTIONS(23),
    [anon_sym_LBRACK] = ACTIONS(25),
  },
  [11] = {
    [sym_expr] = STATE(52),
    [sym_binary_op] = STATE(50),
    [sym_unary_op] = STATE(50),
    [sym_paren] = STATE(50),
    [sym_bool] = STATE(50),
    [sym_fn] = STATE(50),
    [sym_call] = STATE(50),
    [sym_def] = STATE(50),
    [sym_struct] = STATE(50),
    [sym_array] = STATE(50),
    [sym_map] = STATE(50),
    [sym_symbol] = ACTIONS(5),
    [anon_sym_DASH] = ACTIONS(7),
    [anon_sym_not] = ACTIONS(9),
    [anon_sym_LPAREN] = ACTIONS(11),
    [sym_int] = ACTIONS(13),
    [sym_float] = ACTIONS(15),
    [sym_str] = ACTIONS(15),
    [anon_sym_true] = ACTIONS(17),
    [anon_sym_false] = ACTIONS(17),
    [anon_sym_LBRACE] = ACTIONS(19),
    [anon_sym_fn] = ACTIONS(21),
    [anon_sym_struct] = ACTIONS(23),
    [anon_sym_LBRACK] = ACTIONS(25),
    [anon_sym_RBRACK] = ACTIONS(80),
  },
  [12] = {
    [sym_expr] = STATE(52),
    [sym_binary_op] = STATE(50),
    [sym_unary_op] = STATE(50),
    [sym_paren] = STATE(50),
    [sym_bool] = STATE(50),
    [sym_fn] = STATE(50),
    [sym_call] = STATE(50),
    [sym_def] = STATE(50),
    [sym_struct] = STATE(50),
    [sym_array] = STATE(50),
    [sym_map] = STATE(50),
    [sym_symbol] = ACTIONS(5),
    [anon_sym_DASH] = ACTIONS(7),
    [anon_sym_not] = ACTIONS(9),
    [anon_sym_LPAREN] = ACTIONS(11),
    [sym_int] = ACTIONS(13),
    [sym_float] = ACTIONS(15),
    [sym_str] = ACTIONS(15),
    [anon_sym_true] = ACTIONS(17),
    [anon_sym_false] = ACTIONS(17),
    [anon_sym_LBRACE] = ACTIONS(19),
    [anon_sym_fn] = ACTIONS(21),
    [anon_sym_struct] = ACTIONS(23),
    [anon_sym_LBRACK] = ACTIONS(25),
    [anon_sym_RBRACK] = ACTIONS(82),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 13,
    ACTIONS(5), 1,
      sym_symbol,
    ACTIONS(7), 1,
      anon_sym_DASH,
    ACTIONS(9), 1,
      anon_sym_not,
    ACTIONS(11), 1,
      anon_sym_LPAREN,
    ACTIONS(13), 1,
      sym_int,
    ACTIONS(19), 1,
      anon_sym_LBRACE,
    ACTIONS(21), 1,
      anon_sym_fn,
    ACTIONS(23), 1,
      anon_sym_struct,
    ACTIONS(25), 1,
      anon_sym_LBRACK,
    STATE(57), 1,
      sym_expr,
    ACTIONS(15), 2,
      sym_float,
      sym_str,
    ACTIONS(17), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(50), 10,
      sym_binary_op,
      sym_unary_op,
      sym_paren,
      sym_bool,
      sym_fn,
      sym_call,
      sym_def,
      sym_struct,
      sym_array,
      sym_map,
  [51] = 13,
    ACTIONS(5), 1,
      sym_symbol,
    ACTIONS(7), 1,
      anon_sym_DASH,
    ACTIONS(9), 1,
      anon_sym_not,
    ACTIONS(11), 1,
      anon_sym_LPAREN,
    ACTIONS(13), 1,
      sym_int,
    ACTIONS(19), 1,
      anon_sym_LBRACE,
    ACTIONS(21), 1,
      anon_sym_fn,
    ACTIONS(23), 1,
      anon_sym_struct,
    ACTIONS(25), 1,
      anon_sym_LBRACK,
    STATE(47), 1,
      sym_expr,
    ACTIONS(15), 2,
      sym_float,
      sym_str,
    ACTIONS(17), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(50), 10,
      sym_binary_op,
      sym_unary_op,
      sym_paren,
      sym_bool,
      sym_fn,
      sym_call,
      sym_def,
      sym_struct,
      sym_array,
      sym_map,
  [102] = 13,
    ACTIONS(5), 1,
      sym_symbol,
    ACTIONS(7), 1,
      anon_sym_DASH,
    ACTIONS(9), 1,
      anon_sym_not,
    ACTIONS(11), 1,
      anon_sym_LPAREN,
    ACTIONS(13), 1,
      sym_int,
    ACTIONS(19), 1,
      anon_sym_LBRACE,
    ACTIONS(21), 1,
      anon_sym_fn,
    ACTIONS(23), 1,
      anon_sym_struct,
    ACTIONS(25), 1,
      anon_sym_LBRACK,
    STATE(56), 1,
      sym_expr,
    ACTIONS(15), 2,
      sym_float,
      sym_str,
    ACTIONS(17), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(50), 10,
      sym_binary_op,
      sym_unary_op,
      sym_paren,
      sym_bool,
      sym_fn,
      sym_call,
      sym_def,
      sym_struct,
      sym_array,
      sym_map,
  [153] = 13,
    ACTIONS(5), 1,
      sym_symbol,
    ACTIONS(7), 1,
      anon_sym_DASH,
    ACTIONS(9), 1,
      anon_sym_not,
    ACTIONS(11), 1,
      anon_sym_LPAREN,
    ACTIONS(13), 1,
      sym_int,
    ACTIONS(19), 1,
      anon_sym_LBRACE,
    ACTIONS(21), 1,
      anon_sym_fn,
    ACTIONS(23), 1,
      anon_sym_struct,
    ACTIONS(25), 1,
      anon_sym_LBRACK,
    STATE(61), 1,
      sym_expr,
    ACTIONS(15), 2,
      sym_float,
      sym_str,
    ACTIONS(17), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(50), 10,
      sym_binary_op,
      sym_unary_op,
      sym_paren,
      sym_bool,
      sym_fn,
      sym_call,
      sym_def,
      sym_struct,
      sym_array,
      sym_map,
  [204] = 13,
    ACTIONS(5), 1,
      sym_symbol,
    ACTIONS(7), 1,
      anon_sym_DASH,
    ACTIONS(9), 1,
      anon_sym_not,
    ACTIONS(11), 1,
      anon_sym_LPAREN,
    ACTIONS(13), 1,
      sym_int,
    ACTIONS(19), 1,
      anon_sym_LBRACE,
    ACTIONS(21), 1,
      anon_sym_fn,
    ACTIONS(23), 1,
      anon_sym_struct,
    ACTIONS(25), 1,
      anon_sym_LBRACK,
    STATE(37), 1,
      sym_expr,
    ACTIONS(15), 2,
      sym_float,
      sym_str,
    ACTIONS(17), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(50), 10,
      sym_binary_op,
      sym_unary_op,
      sym_paren,
      sym_bool,
      sym_fn,
      sym_call,
      sym_def,
      sym_struct,
      sym_array,
      sym_map,
  [255] = 13,
    ACTIONS(5), 1,
      sym_symbol,
    ACTIONS(7), 1,
      anon_sym_DASH,
    ACTIONS(9), 1,
      anon_sym_not,
    ACTIONS(11), 1,
      anon_sym_LPAREN,
    ACTIONS(13), 1,
      sym_int,
    ACTIONS(19), 1,
      anon_sym_LBRACE,
    ACTIONS(21), 1,
      anon_sym_fn,
    ACTIONS(23), 1,
      anon_sym_struct,
    ACTIONS(25), 1,
      anon_sym_LBRACK,
    STATE(55), 1,
      sym_expr,
    ACTIONS(15), 2,
      sym_float,
      sym_str,
    ACTIONS(17), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(50), 10,
      sym_binary_op,
      sym_unary_op,
      sym_paren,
      sym_bool,
      sym_fn,
      sym_call,
      sym_def,
      sym_struct,
      sym_array,
      sym_map,
  [306] = 13,
    ACTIONS(5), 1,
      sym_symbol,
    ACTIONS(7), 1,
      anon_sym_DASH,
    ACTIONS(9), 1,
      anon_sym_not,
    ACTIONS(11), 1,
      anon_sym_LPAREN,
    ACTIONS(13), 1,
      sym_int,
    ACTIONS(19), 1,
      anon_sym_LBRACE,
    ACTIONS(21), 1,
      anon_sym_fn,
    ACTIONS(23), 1,
      anon_sym_struct,
    ACTIONS(25), 1,
      anon_sym_LBRACK,
    STATE(42), 1,
      sym_expr,
    ACTIONS(15), 2,
      sym_float,
      sym_str,
    ACTIONS(17), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(50), 10,
      sym_binary_op,
      sym_unary_op,
      sym_paren,
      sym_bool,
      sym_fn,
      sym_call,
      sym_def,
      sym_struct,
      sym_array,
      sym_map,
  [357] = 13,
    ACTIONS(5), 1,
      sym_symbol,
    ACTIONS(7), 1,
      anon_sym_DASH,
    ACTIONS(9), 1,
      anon_sym_not,
    ACTIONS(11), 1,
      anon_sym_LPAREN,
    ACTIONS(13), 1,
      sym_int,
    ACTIONS(19), 1,
      anon_sym_LBRACE,
    ACTIONS(21), 1,
      anon_sym_fn,
    ACTIONS(23), 1,
      anon_sym_struct,
    ACTIONS(25), 1,
      anon_sym_LBRACK,
    STATE(33), 1,
      sym_expr,
    ACTIONS(15), 2,
      sym_float,
      sym_str,
    ACTIONS(17), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(50), 10,
      sym_binary_op,
      sym_unary_op,
      sym_paren,
      sym_bool,
      sym_fn,
      sym_call,
      sym_def,
      sym_struct,
      sym_array,
      sym_map,
  [408] = 13,
    ACTIONS(5), 1,
      sym_symbol,
    ACTIONS(7), 1,
      anon_sym_DASH,
    ACTIONS(9), 1,
      anon_sym_not,
    ACTIONS(11), 1,
      anon_sym_LPAREN,
    ACTIONS(13), 1,
      sym_int,
    ACTIONS(19), 1,
      anon_sym_LBRACE,
    ACTIONS(21), 1,
      anon_sym_fn,
    ACTIONS(23), 1,
      anon_sym_struct,
    ACTIONS(25), 1,
      anon_sym_LBRACK,
    STATE(46), 1,
      sym_expr,
    ACTIONS(15), 2,
      sym_float,
      sym_str,
    ACTIONS(17), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(50), 10,
      sym_binary_op,
      sym_unary_op,
      sym_paren,
      sym_bool,
      sym_fn,
      sym_call,
      sym_def,
      sym_struct,
      sym_array,
      sym_map,
  [459] = 13,
    ACTIONS(5), 1,
      sym_symbol,
    ACTIONS(7), 1,
      anon_sym_DASH,
    ACTIONS(9), 1,
      anon_sym_not,
    ACTIONS(11), 1,
      anon_sym_LPAREN,
    ACTIONS(13), 1,
      sym_int,
    ACTIONS(19), 1,
      anon_sym_LBRACE,
    ACTIONS(21), 1,
      anon_sym_fn,
    ACTIONS(23), 1,
      anon_sym_struct,
    ACTIONS(25), 1,
      anon_sym_LBRACK,
    STATE(44), 1,
      sym_expr,
    ACTIONS(15), 2,
      sym_float,
      sym_str,
    ACTIONS(17), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(50), 10,
      sym_binary_op,
      sym_unary_op,
      sym_paren,
      sym_bool,
      sym_fn,
      sym_call,
      sym_def,
      sym_struct,
      sym_array,
      sym_map,
  [510] = 13,
    ACTIONS(5), 1,
      sym_symbol,
    ACTIONS(7), 1,
      anon_sym_DASH,
    ACTIONS(9), 1,
      anon_sym_not,
    ACTIONS(11), 1,
      anon_sym_LPAREN,
    ACTIONS(13), 1,
      sym_int,
    ACTIONS(19), 1,
      anon_sym_LBRACE,
    ACTIONS(21), 1,
      anon_sym_fn,
    ACTIONS(23), 1,
      anon_sym_struct,
    ACTIONS(25), 1,
      anon_sym_LBRACK,
    STATE(52), 1,
      sym_expr,
    ACTIONS(15), 2,
      sym_float,
      sym_str,
    ACTIONS(17), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(50), 10,
      sym_binary_op,
      sym_unary_op,
      sym_paren,
      sym_bool,
      sym_fn,
      sym_call,
      sym_def,
      sym_struct,
      sym_array,
      sym_map,
  [561] = 4,
    ACTIONS(88), 1,
      anon_sym_COLON,
    ACTIONS(90), 1,
      anon_sym_EQ,
    ACTIONS(86), 7,
      anon_sym_not,
      sym_int,
      anon_sym_true,
      anon_sym_false,
      sym_symbol,
      anon_sym_fn,
      anon_sym_struct,
    ACTIONS(84), 15,
      ts_builtin_sym_end,
      anon_sym_GT,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      sym_float,
      sym_str,
      anon_sym_COMMA,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
  [594] = 13,
    ACTIONS(5), 1,
      sym_symbol,
    ACTIONS(7), 1,
      anon_sym_DASH,
    ACTIONS(9), 1,
      anon_sym_not,
    ACTIONS(11), 1,
      anon_sym_LPAREN,
    ACTIONS(13), 1,
      sym_int,
    ACTIONS(19), 1,
      anon_sym_LBRACE,
    ACTIONS(21), 1,
      anon_sym_fn,
    ACTIONS(23), 1,
      anon_sym_struct,
    ACTIONS(25), 1,
      anon_sym_LBRACK,
    STATE(60), 1,
      sym_expr,
    ACTIONS(15), 2,
      sym_float,
      sym_str,
    ACTIONS(17), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(50), 10,
      sym_binary_op,
      sym_unary_op,
      sym_paren,
      sym_bool,
      sym_fn,
      sym_call,
      sym_def,
      sym_struct,
      sym_array,
      sym_map,
  [645] = 13,
    ACTIONS(5), 1,
      sym_symbol,
    ACTIONS(7), 1,
      anon_sym_DASH,
    ACTIONS(9), 1,
      anon_sym_not,
    ACTIONS(11), 1,
      anon_sym_LPAREN,
    ACTIONS(13), 1,
      sym_int,
    ACTIONS(19), 1,
      anon_sym_LBRACE,
    ACTIONS(21), 1,
      anon_sym_fn,
    ACTIONS(23), 1,
      anon_sym_struct,
    ACTIONS(25), 1,
      anon_sym_LBRACK,
    STATE(59), 1,
      sym_expr,
    ACTIONS(15), 2,
      sym_float,
      sym_str,
    ACTIONS(17), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(50), 10,
      sym_binary_op,
      sym_unary_op,
      sym_paren,
      sym_bool,
      sym_fn,
      sym_call,
      sym_def,
      sym_struct,
      sym_array,
      sym_map,
  [696] = 13,
    ACTIONS(5), 1,
      sym_symbol,
    ACTIONS(7), 1,
      anon_sym_DASH,
    ACTIONS(9), 1,
      anon_sym_not,
    ACTIONS(11), 1,
      anon_sym_LPAREN,
    ACTIONS(13), 1,
      sym_int,
    ACTIONS(19), 1,
      anon_sym_LBRACE,
    ACTIONS(21), 1,
      anon_sym_fn,
    ACTIONS(23), 1,
      anon_sym_struct,
    ACTIONS(25), 1,
      anon_sym_LBRACK,
    STATE(58), 1,
      sym_expr,
    ACTIONS(15), 2,
      sym_float,
      sym_str,
    ACTIONS(17), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(50), 10,
      sym_binary_op,
      sym_unary_op,
      sym_paren,
      sym_bool,
      sym_fn,
      sym_call,
      sym_def,
      sym_struct,
      sym_array,
      sym_map,
  [747] = 2,
    ACTIONS(94), 7,
      anon_sym_not,
      sym_int,
      anon_sym_true,
      anon_sym_false,
      sym_symbol,
      anon_sym_fn,
      anon_sym_struct,
    ACTIONS(92), 16,
      ts_builtin_sym_end,
      anon_sym_GT,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      sym_float,
      sym_str,
      anon_sym_COMMA,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_EQ,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
  [775] = 2,
    ACTIONS(98), 7,
      anon_sym_not,
      sym_int,
      anon_sym_true,
      anon_sym_false,
      sym_symbol,
      anon_sym_fn,
      anon_sym_struct,
    ACTIONS(96), 16,
      ts_builtin_sym_end,
      anon_sym_GT,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      sym_float,
      sym_str,
      anon_sym_COMMA,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_EQ,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
  [803] = 2,
    ACTIONS(102), 7,
      anon_sym_not,
      sym_int,
      anon_sym_true,
      anon_sym_false,
      sym_symbol,
      anon_sym_fn,
      anon_sym_struct,
    ACTIONS(100), 16,
      ts_builtin_sym_end,
      anon_sym_GT,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      sym_float,
      sym_str,
      anon_sym_COMMA,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_EQ,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
  [831] = 2,
    ACTIONS(106), 7,
      anon_sym_not,
      sym_int,
      anon_sym_true,
      anon_sym_false,
      sym_symbol,
      anon_sym_fn,
      anon_sym_struct,
    ACTIONS(104), 16,
      ts_builtin_sym_end,
      anon_sym_GT,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      sym_float,
      sym_str,
      anon_sym_COMMA,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_EQ,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
  [859] = 2,
    ACTIONS(110), 7,
      anon_sym_not,
      sym_int,
      anon_sym_true,
      anon_sym_false,
      sym_symbol,
      anon_sym_fn,
      anon_sym_struct,
    ACTIONS(108), 16,
      ts_builtin_sym_end,
      anon_sym_GT,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      sym_float,
      sym_str,
      anon_sym_COMMA,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_EQ,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
  [887] = 3,
    ACTIONS(116), 1,
      anon_sym_LPAREN,
    ACTIONS(114), 7,
      anon_sym_not,
      sym_int,
      anon_sym_true,
      anon_sym_false,
      sym_symbol,
      anon_sym_fn,
      anon_sym_struct,
    ACTIONS(112), 15,
      ts_builtin_sym_end,
      anon_sym_GT,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_RPAREN,
      sym_float,
      sym_str,
      anon_sym_COMMA,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_EQ,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
  [917] = 2,
    ACTIONS(120), 7,
      anon_sym_not,
      sym_int,
      anon_sym_true,
      anon_sym_false,
      sym_symbol,
      anon_sym_fn,
      anon_sym_struct,
    ACTIONS(118), 16,
      ts_builtin_sym_end,
      anon_sym_GT,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      sym_float,
      sym_str,
      anon_sym_COMMA,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_EQ,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
  [945] = 2,
    ACTIONS(124), 7,
      anon_sym_not,
      sym_int,
      anon_sym_true,
      anon_sym_false,
      sym_symbol,
      anon_sym_fn,
      anon_sym_struct,
    ACTIONS(122), 16,
      ts_builtin_sym_end,
      anon_sym_GT,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      sym_float,
      sym_str,
      anon_sym_COMMA,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_EQ,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
  [973] = 2,
    ACTIONS(128), 7,
      anon_sym_not,
      sym_int,
      anon_sym_true,
      anon_sym_false,
      sym_symbol,
      anon_sym_fn,
      anon_sym_struct,
    ACTIONS(126), 16,
      ts_builtin_sym_end,
      anon_sym_GT,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      sym_float,
      sym_str,
      anon_sym_COMMA,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_EQ,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
  [1001] = 6,
    ACTIONS(116), 1,
      anon_sym_LPAREN,
    ACTIONS(134), 1,
      anon_sym_GT,
    ACTIONS(136), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(138), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
    ACTIONS(132), 7,
      anon_sym_not,
      sym_int,
      anon_sym_true,
      anon_sym_false,
      sym_symbol,
      anon_sym_fn,
      anon_sym_struct,
    ACTIONS(130), 10,
      ts_builtin_sym_end,
      anon_sym_RPAREN,
      sym_float,
      sym_str,
      anon_sym_COMMA,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_EQ,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
  [1037] = 2,
    ACTIONS(142), 7,
      anon_sym_not,
      sym_int,
      anon_sym_true,
      anon_sym_false,
      sym_symbol,
      anon_sym_fn,
      anon_sym_struct,
    ACTIONS(140), 16,
      ts_builtin_sym_end,
      anon_sym_GT,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      sym_float,
      sym_str,
      anon_sym_COMMA,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_EQ,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
  [1065] = 2,
    ACTIONS(146), 7,
      anon_sym_not,
      sym_int,
      anon_sym_true,
      anon_sym_false,
      sym_symbol,
      anon_sym_fn,
      anon_sym_struct,
    ACTIONS(144), 16,
      ts_builtin_sym_end,
      anon_sym_GT,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      sym_float,
      sym_str,
      anon_sym_COMMA,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_EQ,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
  [1093] = 2,
    ACTIONS(150), 7,
      anon_sym_not,
      sym_int,
      anon_sym_true,
      anon_sym_false,
      sym_symbol,
      anon_sym_fn,
      anon_sym_struct,
    ACTIONS(148), 16,
      ts_builtin_sym_end,
      anon_sym_GT,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      sym_float,
      sym_str,
      anon_sym_COMMA,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_EQ,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
  [1121] = 2,
    ACTIONS(154), 7,
      anon_sym_not,
      sym_int,
      anon_sym_true,
      anon_sym_false,
      sym_symbol,
      anon_sym_fn,
      anon_sym_struct,
    ACTIONS(152), 16,
      ts_builtin_sym_end,
      anon_sym_GT,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      sym_float,
      sym_str,
      anon_sym_COMMA,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_EQ,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
  [1149] = 6,
    ACTIONS(116), 1,
      anon_sym_LPAREN,
    ACTIONS(134), 1,
      anon_sym_GT,
    ACTIONS(136), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(138), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
    ACTIONS(158), 7,
      anon_sym_not,
      sym_int,
      anon_sym_true,
      anon_sym_false,
      sym_symbol,
      anon_sym_fn,
      anon_sym_struct,
    ACTIONS(156), 10,
      ts_builtin_sym_end,
      anon_sym_RPAREN,
      sym_float,
      sym_str,
      anon_sym_COMMA,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_EQ,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
  [1185] = 2,
    ACTIONS(162), 7,
      anon_sym_not,
      sym_int,
      anon_sym_true,
      anon_sym_false,
      sym_symbol,
      anon_sym_fn,
      anon_sym_struct,
    ACTIONS(160), 16,
      ts_builtin_sym_end,
      anon_sym_GT,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      sym_float,
      sym_str,
      anon_sym_COMMA,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_EQ,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
  [1213] = 3,
    ACTIONS(116), 1,
      anon_sym_LPAREN,
    ACTIONS(166), 7,
      anon_sym_not,
      sym_int,
      anon_sym_true,
      anon_sym_false,
      sym_symbol,
      anon_sym_fn,
      anon_sym_struct,
    ACTIONS(164), 15,
      ts_builtin_sym_end,
      anon_sym_GT,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_RPAREN,
      sym_float,
      sym_str,
      anon_sym_COMMA,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_EQ,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
  [1243] = 2,
    ACTIONS(170), 7,
      anon_sym_not,
      sym_int,
      anon_sym_true,
      anon_sym_false,
      sym_symbol,
      anon_sym_fn,
      anon_sym_struct,
    ACTIONS(168), 16,
      ts_builtin_sym_end,
      anon_sym_GT,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      sym_float,
      sym_str,
      anon_sym_COMMA,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_EQ,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
  [1271] = 4,
    ACTIONS(116), 1,
      anon_sym_LPAREN,
    ACTIONS(138), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
    ACTIONS(166), 7,
      anon_sym_not,
      sym_int,
      anon_sym_true,
      anon_sym_false,
      sym_symbol,
      anon_sym_fn,
      anon_sym_struct,
    ACTIONS(164), 13,
      ts_builtin_sym_end,
      anon_sym_GT,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_RPAREN,
      sym_float,
      sym_str,
      anon_sym_COMMA,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_EQ,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
  [1303] = 5,
    ACTIONS(116), 1,
      anon_sym_LPAREN,
    ACTIONS(136), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(138), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
    ACTIONS(166), 7,
      anon_sym_not,
      sym_int,
      anon_sym_true,
      anon_sym_false,
      sym_symbol,
      anon_sym_fn,
      anon_sym_struct,
    ACTIONS(164), 11,
      ts_builtin_sym_end,
      anon_sym_GT,
      anon_sym_RPAREN,
      sym_float,
      sym_str,
      anon_sym_COMMA,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_EQ,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
  [1337] = 2,
    ACTIONS(174), 7,
      anon_sym_not,
      sym_int,
      anon_sym_true,
      anon_sym_false,
      sym_symbol,
      anon_sym_fn,
      anon_sym_struct,
    ACTIONS(172), 16,
      ts_builtin_sym_end,
      anon_sym_GT,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      sym_float,
      sym_str,
      anon_sym_COMMA,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_EQ,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
  [1365] = 2,
    ACTIONS(178), 7,
      anon_sym_not,
      sym_int,
      anon_sym_true,
      anon_sym_false,
      sym_symbol,
      anon_sym_fn,
      anon_sym_struct,
    ACTIONS(176), 16,
      ts_builtin_sym_end,
      anon_sym_GT,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      sym_float,
      sym_str,
      anon_sym_COMMA,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_EQ,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
  [1393] = 2,
    ACTIONS(86), 7,
      anon_sym_not,
      sym_int,
      anon_sym_true,
      anon_sym_false,
      sym_symbol,
      anon_sym_fn,
      anon_sym_struct,
    ACTIONS(84), 16,
      ts_builtin_sym_end,
      anon_sym_GT,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      sym_float,
      sym_str,
      anon_sym_COMMA,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_EQ,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
  [1421] = 6,
    ACTIONS(116), 1,
      anon_sym_LPAREN,
    ACTIONS(134), 1,
      anon_sym_GT,
    ACTIONS(136), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(138), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
    ACTIONS(180), 6,
      ts_builtin_sym_end,
      sym_float,
      sym_str,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_LBRACK,
    ACTIONS(182), 7,
      anon_sym_not,
      sym_int,
      anon_sym_true,
      anon_sym_false,
      sym_symbol,
      anon_sym_fn,
      anon_sym_struct,
  [1453] = 5,
    ACTIONS(116), 1,
      anon_sym_LPAREN,
    ACTIONS(134), 1,
      anon_sym_GT,
    ACTIONS(136), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(138), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
    ACTIONS(184), 3,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_RBRACK,
  [1473] = 7,
    ACTIONS(116), 1,
      anon_sym_LPAREN,
    ACTIONS(134), 1,
      anon_sym_GT,
    ACTIONS(186), 1,
      anon_sym_RPAREN,
    ACTIONS(188), 1,
      anon_sym_COMMA,
    STATE(67), 1,
      aux_sym_args_repeat1,
    ACTIONS(136), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(138), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
  [1497] = 7,
    ACTIONS(74), 1,
      anon_sym_RBRACK,
    ACTIONS(116), 1,
      anon_sym_LPAREN,
    ACTIONS(134), 1,
      anon_sym_GT,
    ACTIONS(190), 1,
      anon_sym_COMMA,
    STATE(78), 1,
      aux_sym_args_repeat1,
    ACTIONS(136), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(138), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
  [1521] = 5,
    ACTIONS(116), 1,
      anon_sym_LPAREN,
    ACTIONS(134), 1,
      anon_sym_GT,
    ACTIONS(136), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(138), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
    ACTIONS(192), 2,
      anon_sym_RPAREN,
      anon_sym_COMMA,
  [1540] = 6,
    ACTIONS(116), 1,
      anon_sym_LPAREN,
    ACTIONS(134), 1,
      anon_sym_GT,
    ACTIONS(194), 1,
      anon_sym_LBRACE,
    STATE(38), 1,
      sym_block,
    ACTIONS(136), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(138), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
  [1561] = 5,
    ACTIONS(116), 1,
      anon_sym_LPAREN,
    ACTIONS(134), 1,
      anon_sym_GT,
    ACTIONS(136), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(138), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
    ACTIONS(196), 2,
      anon_sym_COMMA,
      anon_sym_RBRACE,
  [1580] = 5,
    ACTIONS(116), 1,
      anon_sym_LPAREN,
    ACTIONS(134), 1,
      anon_sym_GT,
    ACTIONS(136), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(138), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
    ACTIONS(198), 2,
      anon_sym_COMMA,
      anon_sym_RBRACE,
  [1599] = 6,
    ACTIONS(116), 1,
      anon_sym_LPAREN,
    ACTIONS(134), 1,
      anon_sym_GT,
    ACTIONS(194), 1,
      anon_sym_LBRACE,
    STATE(49), 1,
      sym_block,
    ACTIONS(136), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(138), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
  [1620] = 5,
    ACTIONS(116), 1,
      anon_sym_LPAREN,
    ACTIONS(134), 1,
      anon_sym_GT,
    ACTIONS(200), 1,
      anon_sym_RPAREN,
    ACTIONS(136), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(138), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
  [1638] = 5,
    ACTIONS(116), 1,
      anon_sym_LPAREN,
    ACTIONS(134), 1,
      anon_sym_GT,
    ACTIONS(202), 1,
      anon_sym_EQ,
    ACTIONS(136), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(138), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
  [1656] = 3,
    ACTIONS(204), 1,
      anon_sym_COMMA,
    STATE(62), 1,
      aux_sym_args_repeat1,
    ACTIONS(184), 2,
      anon_sym_RPAREN,
      anon_sym_RBRACK,
  [1667] = 4,
    ACTIONS(207), 1,
      sym_symbol,
    ACTIONS(209), 1,
      anon_sym_RBRACE,
    STATE(79), 1,
      sym_pair,
    STATE(88), 1,
      sym_pairs,
  [1680] = 4,
    ACTIONS(211), 1,
      sym_symbol,
    ACTIONS(213), 1,
      anon_sym_RBRACE,
    STATE(69), 1,
      sym_field,
    STATE(89), 1,
      sym_fields,
  [1693] = 4,
    ACTIONS(215), 1,
      sym_symbol,
    ACTIONS(217), 1,
      anon_sym_RPAREN,
    STATE(81), 1,
      sym_param,
    STATE(92), 1,
      sym_params,
  [1706] = 3,
    ACTIONS(207), 1,
      sym_symbol,
    ACTIONS(219), 1,
      anon_sym_RBRACE,
    STATE(83), 1,
      sym_pair,
  [1716] = 3,
    ACTIONS(78), 1,
      anon_sym_RPAREN,
    ACTIONS(221), 1,
      anon_sym_COMMA,
    STATE(62), 1,
      aux_sym_args_repeat1,
  [1726] = 3,
    ACTIONS(207), 1,
      sym_symbol,
    ACTIONS(223), 1,
      anon_sym_RBRACE,
    STATE(83), 1,
      sym_pair,
  [1736] = 3,
    ACTIONS(225), 1,
      anon_sym_COMMA,
    ACTIONS(227), 1,
      anon_sym_RBRACE,
    STATE(71), 1,
      aux_sym_fields_repeat1,
  [1746] = 3,
    ACTIONS(211), 1,
      sym_symbol,
    ACTIONS(229), 1,
      anon_sym_RBRACE,
    STATE(87), 1,
      sym_field,
  [1756] = 3,
    ACTIONS(229), 1,
      anon_sym_RBRACE,
    ACTIONS(231), 1,
      anon_sym_COMMA,
    STATE(80), 1,
      aux_sym_fields_repeat1,
  [1766] = 3,
    ACTIONS(74), 1,
      anon_sym_RBRACK,
    ACTIONS(190), 1,
      anon_sym_COMMA,
    STATE(62), 1,
      aux_sym_args_repeat1,
  [1776] = 3,
    ACTIONS(233), 1,
      anon_sym_COMMA,
    ACTIONS(236), 1,
      anon_sym_RBRACE,
    STATE(73), 1,
      aux_sym_pairs_repeat1,
  [1786] = 3,
    ACTIONS(238), 1,
      anon_sym_RPAREN,
    ACTIONS(240), 1,
      anon_sym_COMMA,
    STATE(75), 1,
      aux_sym_params_repeat1,
  [1796] = 3,
    ACTIONS(242), 1,
      anon_sym_RPAREN,
    ACTIONS(244), 1,
      anon_sym_COMMA,
    STATE(75), 1,
      aux_sym_params_repeat1,
  [1806] = 3,
    ACTIONS(223), 1,
      anon_sym_RBRACE,
    ACTIONS(247), 1,
      anon_sym_COMMA,
    STATE(73), 1,
      aux_sym_pairs_repeat1,
  [1816] = 3,
    ACTIONS(211), 1,
      sym_symbol,
    ACTIONS(249), 1,
      anon_sym_RBRACE,
    STATE(87), 1,
      sym_field,
  [1826] = 3,
    ACTIONS(80), 1,
      anon_sym_RBRACK,
    ACTIONS(251), 1,
      anon_sym_COMMA,
    STATE(62), 1,
      aux_sym_args_repeat1,
  [1836] = 3,
    ACTIONS(253), 1,
      anon_sym_COMMA,
    ACTIONS(255), 1,
      anon_sym_RBRACE,
    STATE(76), 1,
      aux_sym_pairs_repeat1,
  [1846] = 3,
    ACTIONS(257), 1,
      anon_sym_COMMA,
    ACTIONS(260), 1,
      anon_sym_RBRACE,
    STATE(80), 1,
      aux_sym_fields_repeat1,
  [1856] = 3,
    ACTIONS(240), 1,
      anon_sym_COMMA,
    ACTIONS(262), 1,
      anon_sym_RPAREN,
    STATE(74), 1,
      aux_sym_params_repeat1,
  [1866] = 2,
    ACTIONS(207), 1,
      sym_symbol,
    STATE(83), 1,
      sym_pair,
  [1873] = 1,
    ACTIONS(236), 2,
      anon_sym_COMMA,
      anon_sym_RBRACE,
  [1878] = 1,
    ACTIONS(242), 2,
      anon_sym_RPAREN,
      anon_sym_COMMA,
  [1883] = 2,
    ACTIONS(211), 1,
      sym_symbol,
    STATE(87), 1,
      sym_field,
  [1890] = 2,
    ACTIONS(215), 1,
      sym_symbol,
    STATE(84), 1,
      sym_param,
  [1897] = 1,
    ACTIONS(260), 2,
      anon_sym_COMMA,
      anon_sym_RBRACE,
  [1902] = 1,
    ACTIONS(264), 1,
      anon_sym_RBRACE,
  [1906] = 1,
    ACTIONS(266), 1,
      anon_sym_RBRACE,
  [1910] = 1,
    ACTIONS(268), 1,
      anon_sym_COLON,
  [1914] = 1,
    ACTIONS(270), 1,
      anon_sym_COLON,
  [1918] = 1,
    ACTIONS(272), 1,
      anon_sym_RPAREN,
  [1922] = 1,
    ACTIONS(274), 1,
      anon_sym_RPAREN,
  [1926] = 1,
    ACTIONS(276), 1,
      anon_sym_COLON,
  [1930] = 1,
    ACTIONS(278), 1,
      anon_sym_LPAREN,
  [1934] = 1,
    ACTIONS(280), 1,
      anon_sym_LBRACE,
  [1938] = 1,
    ACTIONS(282), 1,
      ts_builtin_sym_end,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(13)] = 0,
  [SMALL_STATE(14)] = 51,
  [SMALL_STATE(15)] = 102,
  [SMALL_STATE(16)] = 153,
  [SMALL_STATE(17)] = 204,
  [SMALL_STATE(18)] = 255,
  [SMALL_STATE(19)] = 306,
  [SMALL_STATE(20)] = 357,
  [SMALL_STATE(21)] = 408,
  [SMALL_STATE(22)] = 459,
  [SMALL_STATE(23)] = 510,
  [SMALL_STATE(24)] = 561,
  [SMALL_STATE(25)] = 594,
  [SMALL_STATE(26)] = 645,
  [SMALL_STATE(27)] = 696,
  [SMALL_STATE(28)] = 747,
  [SMALL_STATE(29)] = 775,
  [SMALL_STATE(30)] = 803,
  [SMALL_STATE(31)] = 831,
  [SMALL_STATE(32)] = 859,
  [SMALL_STATE(33)] = 887,
  [SMALL_STATE(34)] = 917,
  [SMALL_STATE(35)] = 945,
  [SMALL_STATE(36)] = 973,
  [SMALL_STATE(37)] = 1001,
  [SMALL_STATE(38)] = 1037,
  [SMALL_STATE(39)] = 1065,
  [SMALL_STATE(40)] = 1093,
  [SMALL_STATE(41)] = 1121,
  [SMALL_STATE(42)] = 1149,
  [SMALL_STATE(43)] = 1185,
  [SMALL_STATE(44)] = 1213,
  [SMALL_STATE(45)] = 1243,
  [SMALL_STATE(46)] = 1271,
  [SMALL_STATE(47)] = 1303,
  [SMALL_STATE(48)] = 1337,
  [SMALL_STATE(49)] = 1365,
  [SMALL_STATE(50)] = 1393,
  [SMALL_STATE(51)] = 1421,
  [SMALL_STATE(52)] = 1453,
  [SMALL_STATE(53)] = 1473,
  [SMALL_STATE(54)] = 1497,
  [SMALL_STATE(55)] = 1521,
  [SMALL_STATE(56)] = 1540,
  [SMALL_STATE(57)] = 1561,
  [SMALL_STATE(58)] = 1580,
  [SMALL_STATE(59)] = 1599,
  [SMALL_STATE(60)] = 1620,
  [SMALL_STATE(61)] = 1638,
  [SMALL_STATE(62)] = 1656,
  [SMALL_STATE(63)] = 1667,
  [SMALL_STATE(64)] = 1680,
  [SMALL_STATE(65)] = 1693,
  [SMALL_STATE(66)] = 1706,
  [SMALL_STATE(67)] = 1716,
  [SMALL_STATE(68)] = 1726,
  [SMALL_STATE(69)] = 1736,
  [SMALL_STATE(70)] = 1746,
  [SMALL_STATE(71)] = 1756,
  [SMALL_STATE(72)] = 1766,
  [SMALL_STATE(73)] = 1776,
  [SMALL_STATE(74)] = 1786,
  [SMALL_STATE(75)] = 1796,
  [SMALL_STATE(76)] = 1806,
  [SMALL_STATE(77)] = 1816,
  [SMALL_STATE(78)] = 1826,
  [SMALL_STATE(79)] = 1836,
  [SMALL_STATE(80)] = 1846,
  [SMALL_STATE(81)] = 1856,
  [SMALL_STATE(82)] = 1866,
  [SMALL_STATE(83)] = 1873,
  [SMALL_STATE(84)] = 1878,
  [SMALL_STATE(85)] = 1883,
  [SMALL_STATE(86)] = 1890,
  [SMALL_STATE(87)] = 1897,
  [SMALL_STATE(88)] = 1902,
  [SMALL_STATE(89)] = 1906,
  [SMALL_STATE(90)] = 1910,
  [SMALL_STATE(91)] = 1914,
  [SMALL_STATE(92)] = 1918,
  [SMALL_STATE(93)] = 1922,
  [SMALL_STATE(94)] = 1926,
  [SMALL_STATE(95)] = 1930,
  [SMALL_STATE(96)] = 1934,
  [SMALL_STATE(97)] = 1938,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0),
  [5] = {.entry = {.count = 1, .reusable = false}}, SHIFT(24),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [9] = {.entry = {.count = 1, .reusable = false}}, SHIFT(20),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [13] = {.entry = {.count = 1, .reusable = false}}, SHIFT(50),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(50),
  [17] = {.entry = {.count = 1, .reusable = false}}, SHIFT(39),
  [19] = {.entry = {.count = 1, .reusable = true}}, SHIFT(63),
  [21] = {.entry = {.count = 1, .reusable = false}}, SHIFT(95),
  [23] = {.entry = {.count = 1, .reusable = false}}, SHIFT(96),
  [25] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [27] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2),
  [29] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(24),
  [32] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(20),
  [35] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(20),
  [38] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(25),
  [41] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(50),
  [44] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(50),
  [47] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(39),
  [50] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(63),
  [53] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(95),
  [56] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(96),
  [59] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(3),
  [62] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [64] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
  [66] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1),
  [68] = {.entry = {.count = 1, .reusable = true}}, SHIFT(34),
  [70] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [72] = {.entry = {.count = 1, .reusable = true}}, SHIFT(41),
  [74] = {.entry = {.count = 1, .reusable = true}}, SHIFT(48),
  [76] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_args, 3),
  [78] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_args, 2),
  [80] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [82] = {.entry = {.count = 1, .reusable = true}}, SHIFT(43),
  [84] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_expr, 1),
  [86] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_expr, 1),
  [88] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [90] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [92] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_array, 4),
  [94] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_array, 4),
  [96] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_call, 3, .production_id = 3),
  [98] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_call, 3, .production_id = 3),
  [100] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_map, 2),
  [102] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_map, 2),
  [104] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_struct, 4),
  [106] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_struct, 4),
  [108] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_array, 2),
  [110] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_array, 2),
  [112] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_unary_op, 2),
  [114] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_unary_op, 2),
  [116] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [118] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_block, 3),
  [120] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_block, 3),
  [122] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_paren, 3),
  [124] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_paren, 3),
  [126] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_call, 4, .production_id = 5),
  [128] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_call, 4, .production_id = 5),
  [130] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_def, 3, .production_id = 1),
  [132] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_def, 3, .production_id = 1),
  [134] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [136] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [138] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [140] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_fn, 6, .production_id = 9),
  [142] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_fn, 6, .production_id = 9),
  [144] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_bool, 1),
  [146] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_bool, 1),
  [148] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_map, 3),
  [150] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_map, 3),
  [152] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_block, 2),
  [154] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_block, 2),
  [156] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_def, 5, .production_id = 6),
  [158] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_def, 5, .production_id = 6),
  [160] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_array, 5),
  [162] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_array, 5),
  [164] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_binary_op, 3, .production_id = 2),
  [166] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_binary_op, 3, .production_id = 2),
  [168] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_struct, 3),
  [170] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_struct, 3),
  [172] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_array, 3),
  [174] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_array, 3),
  [176] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_fn, 5, .production_id = 7),
  [178] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_fn, 5, .production_id = 7),
  [180] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 1),
  [182] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 1),
  [184] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_args_repeat1, 2),
  [186] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_args, 1),
  [188] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [190] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [192] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_param, 3, .production_id = 8),
  [194] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [196] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_field, 3, .production_id = 8),
  [198] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_pair, 3, .production_id = 4),
  [200] = {.entry = {.count = 1, .reusable = true}}, SHIFT(35),
  [202] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [204] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_args_repeat1, 2), SHIFT_REPEAT(23),
  [207] = {.entry = {.count = 1, .reusable = true}}, SHIFT(90),
  [209] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [211] = {.entry = {.count = 1, .reusable = true}}, SHIFT(91),
  [213] = {.entry = {.count = 1, .reusable = true}}, SHIFT(45),
  [215] = {.entry = {.count = 1, .reusable = true}}, SHIFT(94),
  [217] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [219] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_pairs, 3),
  [221] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [223] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_pairs, 2),
  [225] = {.entry = {.count = 1, .reusable = true}}, SHIFT(70),
  [227] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_fields, 1),
  [229] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_fields, 2),
  [231] = {.entry = {.count = 1, .reusable = true}}, SHIFT(77),
  [233] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_pairs_repeat1, 2), SHIFT_REPEAT(82),
  [236] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_pairs_repeat1, 2),
  [238] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_params, 2),
  [240] = {.entry = {.count = 1, .reusable = true}}, SHIFT(86),
  [242] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_params_repeat1, 2),
  [244] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_params_repeat1, 2), SHIFT_REPEAT(86),
  [247] = {.entry = {.count = 1, .reusable = true}}, SHIFT(66),
  [249] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_fields, 3),
  [251] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [253] = {.entry = {.count = 1, .reusable = true}}, SHIFT(68),
  [255] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_pairs, 1),
  [257] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_fields_repeat1, 2), SHIFT_REPEAT(85),
  [260] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_fields_repeat1, 2),
  [262] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_params, 1),
  [264] = {.entry = {.count = 1, .reusable = true}}, SHIFT(40),
  [266] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
  [268] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [270] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [272] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [274] = {.entry = {.count = 1, .reusable = true}}, SHIFT(36),
  [276] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [278] = {.entry = {.count = 1, .reusable = true}}, SHIFT(65),
  [280] = {.entry = {.count = 1, .reusable = true}}, SHIFT(64),
  [282] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_smith() {
  static const TSLanguage language = {
    .version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = ts_lex_modes,
    .lex_fn = ts_lex,
    .keyword_lex_fn = ts_lex_keywords,
    .keyword_capture_token = sym_symbol,
    .primary_state_ids = ts_primary_state_ids,
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
