(linenum) @tag
(op_error) @operator
(statement (statement_gosub) (integer) @tag)
(statement (statement_goto) (integer) @tag)
(comment_text) @comment
(string) @string
(integer) @number
(str_name) @variable
(int_name) @variable
(sep_statement) @punctuation.delimiter
(com_load) @keyword.builtin
(com_save) @keyword.builtin
(com_con) @keyword.builtin
(com_run_line) @keyword.builtin
(com_run) @keyword.builtin
(com_del) @keyword.builtin
(sep_del) @punctuation.delimiter
(com_new) @keyword.builtin
(com_clr) @keyword.builtin
(com_auto) @keyword.builtin
(sep_auto) @punctuation.delimiter
(com_man) @keyword.builtin
(com_himem) @keyword.builtin
(com_lomem) @keyword.builtin
(op_plus) @operator
(op_minus) @operator
(op_times) @operator
(op_div) @operator
(op_aeq) @operator
(op_aneq) @operator
(op_gtreq) @operator
(op_gtr) @operator
(op_lesseq) @operator
(op_neq) @operator
(op_less) @operator
(op_and) @operator
(op_or) @operator
(op_mod) @operator
(op_pow) @operator
(sep_slice) @punctuation.delimiter
(statement_then_line) @keyword.builtin
(statement_then) @keyword.builtin
(sep_input_str) @punctuation.delimiter
(sep_input_int) @punctuation.delimiter
(fcall_peek) @function.builtin
(fcall_rnd) @function.builtin
(fcall_sgn) @function.builtin
(fcall_abs) @function.builtin
(fcall_pdl) @function.builtin
(op_unary_plus) @operator
(op_unary_minus) @operator
(op_not) @operator
(op_seq) @operator
(op_sneq) @operator
(fcall_lenp) @function.builtin
(fcall_ascp) @function.builtin
(fcall_scrnp) @function.builtin
(sep_scrn) @punctuation.delimiter
(sep_dim_str) @punctuation.delimiter
(sep_dim_int) @punctuation.delimiter
(sep_print_str) @punctuation.delimiter
(sep_print_int) @punctuation.delimiter
(sep_print_null) @punctuation.delimiter
(sep_tab_str) @punctuation.delimiter
(sep_tab_int) @punctuation.delimiter
(sep_tab_null) @punctuation.delimiter
(statement_text) @keyword.builtin
(statement_gr) @keyword.builtin
(statement_call) @keyword.builtin
(statement_dim_str) @keyword.builtin
(statement_dim_int) @keyword.builtin
(statement_tab) @keyword.builtin
(statement_end) @keyword.builtin
(statement_input_str) @keyword.builtin
(statement_input_prompt) @keyword.builtin
(statement_input_int) @keyword.builtin
(statement_for) @keyword.builtin
(op_eq_for) @operator
(op_to) @operator
(op_step) @operator
(statement_next) @keyword.builtin
(sep_next) @punctuation.delimiter
(statement_return) @keyword.builtin
(statement_gosub) @keyword.builtin
(statement_rem) @keyword.builtin
(statement_let) @keyword.builtin
(statement_goto) @keyword.builtin
(statement_if) @keyword.builtin
(statement_print_str) @keyword.builtin
(statement_print_int) @keyword.builtin
(statement_print_null) @keyword.builtin
(statement_poke) @keyword.builtin
(sep_poke) @punctuation.delimiter
(statement_coloreq) @keyword.builtin
(statement_plot) @keyword.builtin
(sep_plot) @punctuation.delimiter
(statement_hlin) @keyword.builtin
(sep_hlin) @punctuation.delimiter
(op_hlin_at) @operator
(statement_vlin) @keyword.builtin
(sep_vlin) @punctuation.delimiter
(op_vlin_at) @operator
(statement_vtab) @keyword.builtin
(op_eq_assign_str) @operator
(op_eq_assign_int) @operator
(statement_list_line) @keyword.builtin
(sep_list) @punctuation.delimiter
(statement_list) @keyword.builtin
(statement_pop) @keyword.builtin
(statement_nodsp_str) @keyword.builtin
(statement_nodsp_int) @keyword.builtin
(statement_notrace) @keyword.builtin
(statement_dsp_str) @keyword.builtin
(statement_dsp_int) @keyword.builtin
(statement_trace) @keyword.builtin
(statement_prn) @keyword.builtin
(statement_inn) @keyword.builtin
