(macro_def) @function
(macro_ref) @function
(label_def (global_label)) @type
(label_ref (global_label)) @type
(current_addr) @type
(local_label) @variable.parameter
(var_label) @variable.builtin
(var_mac) @variable.builtin
(var_cnt) @variable.builtin
(num) @number
(hex_data) @number
(dstring) @string
(arg_literal) @string
(pchar) @string
(nchar) @string
(literal) @string
(filename) @string
(trailing) @string
(heading) @comment
(comment) @comment
(eop_plus) @operator
(eop_minus) @operator
(eop_times) @operator
(eop_div) @operator
(eop_or) @operator
(eop_and) @operator
(eop_xor) @operator
(mode) @keyword
(imm_prefix) @keyword
(addr_prefix) @keyword
(data_prefix) @keyword
(num_str_prefix) @keyword
(ERROR) @error
(op_adc) @keyword
(op_and) @keyword
(op_asl) @keyword
(op_bcc) @keyword
(op_bcs) @keyword
(op_beq) @keyword
(op_bit) @keyword
(op_bmi) @keyword
(op_bne) @keyword
(op_bpl) @keyword
(op_bra) @keyword
(op_brk) @keyword
(op_brl) @keyword
(op_bvc) @keyword
(op_bvs) @keyword
(op_clc) @keyword
(op_cld) @keyword
(op_cli) @keyword
(op_clv) @keyword
(op_cmp) @keyword
(op_cop) @keyword
(op_cpx) @keyword
(op_cpy) @keyword
(op_dec) @keyword
(op_dex) @keyword
(op_dey) @keyword
(op_eor) @keyword
(op_inc) @keyword
(op_inx) @keyword
(op_iny) @keyword
(op_jml) @keyword
(op_jmp) @keyword
(op_jsl) @keyword
(op_jsr) @keyword
(op_lda) @keyword
(op_ldx) @keyword
(op_ldy) @keyword
(op_lsr) @keyword
(op_mvn) @keyword
(op_mvp) @keyword
(op_nop) @keyword
(op_ora) @keyword
(op_pea) @keyword
(op_pei) @keyword
(op_per) @keyword
(op_pha) @keyword
(op_phb) @keyword
(op_phd) @keyword
(op_phk) @keyword
(op_php) @keyword
(op_phx) @keyword
(op_phy) @keyword
(op_pla) @keyword
(op_plb) @keyword
(op_pld) @keyword
(op_plp) @keyword
(op_plx) @keyword
(op_ply) @keyword
(op_rep) @keyword
(op_rol) @keyword
(op_ror) @keyword
(op_rti) @keyword
(op_rtl) @keyword
(op_rts) @keyword
(op_sbc) @keyword
(op_sec) @keyword
(op_sed) @keyword
(op_sei) @keyword
(op_sep) @keyword
(op_sta) @keyword
(op_stx) @keyword
(op_sty) @keyword
(op_stz) @keyword
(op_tax) @keyword
(op_tay) @keyword
(op_tcd) @keyword
(op_tcs) @keyword
(op_tdc) @keyword
(op_trb) @keyword
(op_tsb) @keyword
(op_tsc) @keyword
(op_tsx) @keyword
(op_txa) @keyword
(op_txs) @keyword
(op_txy) @keyword
(op_tya) @keyword
(op_tyx) @keyword
(op_wai) @keyword
(op_wdm) @keyword
(op_xba) @keyword
(op_xce) @keyword
(psop_end_lup) @function.builtin
(psop_adr) @function.builtin
(psop_adrl) @function.builtin
(psop_asc) @function.builtin
(psop_ast) @function.builtin
(psop_cas) @function.builtin
(psop_chk) @function.builtin
(psop_cyc) @function.builtin
(psop_da) @function.builtin
(psop_dat) @function.builtin
(psop_dci) @function.builtin
(psop_ddb) @function.builtin
(psop_dend) @function.builtin
(psop_dfb) @function.builtin
(psop_do) @function.builtin
(psop_ds) @function.builtin
(psop_dsk) @function.builtin
(psop_dum) @function.builtin
(psop_else) @function.builtin
(psop_end) @function.builtin
(psop_ent) @function.builtin
(psop_eom) @function.builtin
(psop_equ) @function.builtin
(psop_err) @function.builtin
(psop_exd) @function.builtin
(psop_exp) @function.builtin
(psop_ext) @function.builtin
(psop_fin) @function.builtin
(psop_flo) @function.builtin
(psop_fls) @function.builtin
(psop_hex) @function.builtin
(psop_if) @function.builtin
(psop_inv) @function.builtin
(psop_kbd) @function.builtin
(psop_lst) @function.builtin
(psop_lstdo) @function.builtin
(psop_lup) @function.builtin
(psop_mac) @function.builtin
(psop_mx) @function.builtin
(psop_obj) @function.builtin
(psop_org) @function.builtin
(psop_pag) @function.builtin
(psop_pau) @function.builtin
(psop_pmc) @function.builtin
(psop_put) @function.builtin
(psop_rel) @function.builtin
(psop_rev) @function.builtin
(psop_sav) @function.builtin
(psop_skp) @function.builtin
(psop_str) @function.builtin
(psop_strl) @function.builtin
(psop_sw) @function.builtin
(psop_tr) @function.builtin
(psop_ttl) @function.builtin
(psop_typ) @function.builtin
(psop_use) @function.builtin
(psop_usr) @function.builtin
(psop_var) @function.builtin
(psop_xc) @function.builtin
