#include "parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 14
#define STATE_COUNT 101
#define LARGE_STATE_COUNT 9
#define SYMBOL_COUNT 43
#define ALIAS_COUNT 0
#define TOKEN_COUNT 25
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 6
#define PRODUCTION_ID_COUNT 1

enum ts_symbol_identifiers {
  sym_identifier = 1,
  sym_number = 2,
  anon_sym_SQUOTE = 3,
  aux_sym_string_token1 = 4,
  anon_sym_DQUOTE = 5,
  aux_sym_string_token2 = 6,
  anon_sym_SLASH_SLASH = 7,
  aux_sym_comment_token1 = 8,
  anon_sym_SLASH_STAR = 9,
  aux_sym_comment_token2 = 10,
  anon_sym_SLASH = 11,
  anon_sym_EQ = 12,
  anon_sym_POUND = 13,
  anon_sym_LPAREN = 14,
  anon_sym_RPAREN = 15,
  anon_sym_println = 16,
  anon_sym_return = 17,
  anon_sym_PLUS = 18,
  anon_sym_DASH = 19,
  anon_sym_STAR = 20,
  anon_sym_def = 21,
  anon_sym_COMMA = 22,
  anon_sym_LBRACE = 23,
  anon_sym_RBRACE = 24,
  sym_source_file = 25,
  sym_string = 26,
  sym_comment = 27,
  sym__statement = 28,
  sym__assignment_definition = 29,
  sym_left_hand_side = 30,
  sym_right_hand_side = 31,
  sym_hash_like_function = 32,
  sym__simple_statement = 33,
  sym_print_statement = 34,
  sym_return_statement = 35,
  sym__expression = 36,
  sym_binary_expression = 37,
  sym_function_definition = 38,
  sym_parameters = 39,
  sym_function_body = 40,
  aux_sym_source_file_repeat1 = 41,
  aux_sym_parameters_repeat1 = 42,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [sym_identifier] = "identifier",
  [sym_number] = "number",
  [anon_sym_SQUOTE] = "'",
  [aux_sym_string_token1] = "string_token1",
  [anon_sym_DQUOTE] = "\"",
  [aux_sym_string_token2] = "string_token2",
  [anon_sym_SLASH_SLASH] = "//",
  [aux_sym_comment_token1] = "comment_token1",
  [anon_sym_SLASH_STAR] = "/*",
  [aux_sym_comment_token2] = "comment_token2",
  [anon_sym_SLASH] = "/",
  [anon_sym_EQ] = "=",
  [anon_sym_POUND] = "#",
  [anon_sym_LPAREN] = "(",
  [anon_sym_RPAREN] = ")",
  [anon_sym_println] = "println",
  [anon_sym_return] = "return",
  [anon_sym_PLUS] = "+",
  [anon_sym_DASH] = "-",
  [anon_sym_STAR] = "*",
  [anon_sym_def] = "def",
  [anon_sym_COMMA] = ",",
  [anon_sym_LBRACE] = "{",
  [anon_sym_RBRACE] = "}",
  [sym_source_file] = "source_file",
  [sym_string] = "string",
  [sym_comment] = "comment",
  [sym__statement] = "_statement",
  [sym__assignment_definition] = "_assignment_definition",
  [sym_left_hand_side] = "left_hand_side",
  [sym_right_hand_side] = "right_hand_side",
  [sym_hash_like_function] = "hash_like_function",
  [sym__simple_statement] = "_simple_statement",
  [sym_print_statement] = "print_statement",
  [sym_return_statement] = "return_statement",
  [sym__expression] = "_expression",
  [sym_binary_expression] = "binary_expression",
  [sym_function_definition] = "function_definition",
  [sym_parameters] = "parameters",
  [sym_function_body] = "function_body",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_parameters_repeat1] = "parameters_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [sym_identifier] = sym_identifier,
  [sym_number] = sym_number,
  [anon_sym_SQUOTE] = anon_sym_SQUOTE,
  [aux_sym_string_token1] = aux_sym_string_token1,
  [anon_sym_DQUOTE] = anon_sym_DQUOTE,
  [aux_sym_string_token2] = aux_sym_string_token2,
  [anon_sym_SLASH_SLASH] = anon_sym_SLASH_SLASH,
  [aux_sym_comment_token1] = aux_sym_comment_token1,
  [anon_sym_SLASH_STAR] = anon_sym_SLASH_STAR,
  [aux_sym_comment_token2] = aux_sym_comment_token2,
  [anon_sym_SLASH] = anon_sym_SLASH,
  [anon_sym_EQ] = anon_sym_EQ,
  [anon_sym_POUND] = anon_sym_POUND,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [anon_sym_println] = anon_sym_println,
  [anon_sym_return] = anon_sym_return,
  [anon_sym_PLUS] = anon_sym_PLUS,
  [anon_sym_DASH] = anon_sym_DASH,
  [anon_sym_STAR] = anon_sym_STAR,
  [anon_sym_def] = anon_sym_def,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [anon_sym_LBRACE] = anon_sym_LBRACE,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [sym_source_file] = sym_source_file,
  [sym_string] = sym_string,
  [sym_comment] = sym_comment,
  [sym__statement] = sym__statement,
  [sym__assignment_definition] = sym__assignment_definition,
  [sym_left_hand_side] = sym_left_hand_side,
  [sym_right_hand_side] = sym_right_hand_side,
  [sym_hash_like_function] = sym_hash_like_function,
  [sym__simple_statement] = sym__simple_statement,
  [sym_print_statement] = sym_print_statement,
  [sym_return_statement] = sym_return_statement,
  [sym__expression] = sym__expression,
  [sym_binary_expression] = sym_binary_expression,
  [sym_function_definition] = sym_function_definition,
  [sym_parameters] = sym_parameters,
  [sym_function_body] = sym_function_body,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_parameters_repeat1] = aux_sym_parameters_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [sym_number] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_SQUOTE] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_string_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_DQUOTE] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_string_token2] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_SLASH_SLASH] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_comment_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_SLASH_STAR] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_comment_token2] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_SLASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_POUND] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_println] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_return] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PLUS] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_STAR] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_def] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym_string] = {
    .visible = true,
    .named = true,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [sym__statement] = {
    .visible = false,
    .named = true,
  },
  [sym__assignment_definition] = {
    .visible = false,
    .named = true,
  },
  [sym_left_hand_side] = {
    .visible = true,
    .named = true,
  },
  [sym_right_hand_side] = {
    .visible = true,
    .named = true,
  },
  [sym_hash_like_function] = {
    .visible = true,
    .named = true,
  },
  [sym__simple_statement] = {
    .visible = false,
    .named = true,
  },
  [sym_print_statement] = {
    .visible = true,
    .named = true,
  },
  [sym_return_statement] = {
    .visible = true,
    .named = true,
  },
  [sym__expression] = {
    .visible = false,
    .named = true,
  },
  [sym_binary_expression] = {
    .visible = true,
    .named = true,
  },
  [sym_function_definition] = {
    .visible = true,
    .named = true,
  },
  [sym_parameters] = {
    .visible = true,
    .named = true,
  },
  [sym_function_body] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_parameters_repeat1] = {
    .visible = false,
    .named = false,
  },
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 2,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 5,
  [8] = 6,
  [9] = 9,
  [10] = 9,
  [11] = 11,
  [12] = 11,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 16,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 18,
  [22] = 14,
  [23] = 20,
  [24] = 13,
  [25] = 19,
  [26] = 15,
  [27] = 27,
  [28] = 27,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 31,
  [35] = 35,
  [36] = 32,
  [37] = 35,
  [38] = 38,
  [39] = 39,
  [40] = 40,
  [41] = 41,
  [42] = 30,
  [43] = 39,
  [44] = 41,
  [45] = 45,
  [46] = 33,
  [47] = 40,
  [48] = 29,
  [49] = 45,
  [50] = 38,
  [51] = 51,
  [52] = 51,
  [53] = 53,
  [54] = 53,
  [55] = 55,
  [56] = 55,
  [57] = 57,
  [58] = 57,
  [59] = 59,
  [60] = 60,
  [61] = 61,
  [62] = 60,
  [63] = 63,
  [64] = 64,
  [65] = 65,
  [66] = 66,
  [67] = 67,
  [68] = 64,
  [69] = 67,
  [70] = 70,
  [71] = 71,
  [72] = 72,
  [73] = 73,
  [74] = 74,
  [75] = 75,
  [76] = 76,
  [77] = 77,
  [78] = 78,
  [79] = 79,
  [80] = 80,
  [81] = 81,
  [82] = 82,
  [83] = 72,
  [84] = 76,
  [85] = 85,
  [86] = 78,
  [87] = 87,
  [88] = 88,
  [89] = 74,
  [90] = 90,
  [91] = 90,
  [92] = 70,
  [93] = 93,
  [94] = 81,
  [95] = 95,
  [96] = 87,
  [97] = 93,
  [98] = 82,
  [99] = 99,
  [100] = 100,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(7);
      ADVANCE_MAP(
        '"', 27,
        '#', 47,
        '\'', 23,
        '(', 48,
        ')', 49,
        '*', 54,
        '+', 52,
        ',', 56,
        '-', 53,
        '/', 45,
        '=', 46,
        'd', 8,
        'p', 16,
        'r', 9,
        '{', 57,
        '}', 58,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(22);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(21);
      END_STATE();
    case 1:
      if (lookahead == '"') ADVANCE(27);
      if (lookahead == '\'') ADVANCE(23);
      if (lookahead == '(') ADVANCE(48);
      if (lookahead == ')') ADVANCE(49);
      if (lookahead == '/') ADVANCE(3);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(1);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(22);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(21);
      END_STATE();
    case 2:
      if (lookahead == '"') ADVANCE(27);
      if (lookahead == '\'') ADVANCE(23);
      if (lookahead == '(') ADVANCE(48);
      if (lookahead == '/') ADVANCE(3);
      if (lookahead == 'p') ADVANCE(16);
      if (lookahead == 'r') ADVANCE(9);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(2);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(22);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(21);
      END_STATE();
    case 3:
      if (lookahead == '*') ADVANCE(39);
      if (lookahead == '/') ADVANCE(31);
      END_STATE();
    case 4:
      if (lookahead == '*') ADVANCE(44);
      if (lookahead == '/') ADVANCE(6);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(4);
      if (lookahead != 0) ADVANCE(5);
      END_STATE();
    case 5:
      if (lookahead == '*') ADVANCE(44);
      if (lookahead != 0) ADVANCE(5);
      END_STATE();
    case 6:
      if (lookahead == '*') ADVANCE(40);
      if (lookahead == '/') ADVANCE(32);
      if (lookahead != 0) ADVANCE(5);
      END_STATE();
    case 7:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 8:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'e') ADVANCE(10);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(21);
      END_STATE();
    case 9:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'e') ADVANCE(18);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(21);
      END_STATE();
    case 10:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'f') ADVANCE(55);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(21);
      END_STATE();
    case 11:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'i') ADVANCE(15);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(21);
      END_STATE();
    case 12:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'l') ADVANCE(14);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(21);
      END_STATE();
    case 13:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'n') ADVANCE(51);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(21);
      END_STATE();
    case 14:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'n') ADVANCE(50);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(21);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'n') ADVANCE(19);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(21);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'r') ADVANCE(11);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(21);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'r') ADVANCE(13);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(21);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 't') ADVANCE(20);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(21);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 't') ADVANCE(12);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(21);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'u') ADVANCE(17);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(21);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(sym_identifier);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(21);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(sym_number);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(22);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(anon_sym_SQUOTE);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(aux_sym_string_token1);
      if (lookahead == '*') ADVANCE(43);
      if (lookahead == '/') ADVANCE(35);
      if (lookahead != 0 &&
          lookahead != '\'') ADVANCE(26);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(aux_sym_string_token1);
      if (lookahead == '/') ADVANCE(24);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(25);
      if (lookahead != 0 &&
          lookahead != '\'') ADVANCE(26);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(aux_sym_string_token1);
      if (lookahead != 0 &&
          lookahead != '\'') ADVANCE(26);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(anon_sym_DQUOTE);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(aux_sym_string_token2);
      if (lookahead == '*') ADVANCE(42);
      if (lookahead == '/') ADVANCE(34);
      if (lookahead != 0 &&
          lookahead != '"') ADVANCE(30);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(aux_sym_string_token2);
      if (lookahead == '/') ADVANCE(28);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(29);
      if (lookahead != 0 &&
          lookahead != '"') ADVANCE(30);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(aux_sym_string_token2);
      if (lookahead != 0 &&
          lookahead != '"') ADVANCE(30);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(anon_sym_SLASH_SLASH);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(anon_sym_SLASH_SLASH);
      if (lookahead == '*') ADVANCE(44);
      if (lookahead != 0) ADVANCE(5);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(anon_sym_SLASH_SLASH);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(38);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(anon_sym_SLASH_SLASH);
      if (lookahead != 0 &&
          lookahead != '"') ADVANCE(30);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(anon_sym_SLASH_SLASH);
      if (lookahead != 0 &&
          lookahead != '\'') ADVANCE(26);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(aux_sym_comment_token1);
      if (lookahead == '*') ADVANCE(41);
      if (lookahead == '/') ADVANCE(33);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(38);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(aux_sym_comment_token1);
      if (lookahead == '/') ADVANCE(36);
      if (lookahead == '\t' ||
          (0x0b <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(37);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead)) ADVANCE(38);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(aux_sym_comment_token1);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(38);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(anon_sym_SLASH_STAR);
      END_STATE();
    case 40:
      ACCEPT_TOKEN(anon_sym_SLASH_STAR);
      if (lookahead == '*') ADVANCE(44);
      if (lookahead != 0 &&
          lookahead != '/') ADVANCE(5);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(anon_sym_SLASH_STAR);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(38);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(anon_sym_SLASH_STAR);
      if (lookahead != 0 &&
          lookahead != '"') ADVANCE(30);
      END_STATE();
    case 43:
      ACCEPT_TOKEN(anon_sym_SLASH_STAR);
      if (lookahead != 0 &&
          lookahead != '\'') ADVANCE(26);
      END_STATE();
    case 44:
      ACCEPT_TOKEN(aux_sym_comment_token2);
      if (lookahead == '*') ADVANCE(44);
      if (lookahead != 0 &&
          lookahead != '/') ADVANCE(5);
      END_STATE();
    case 45:
      ACCEPT_TOKEN(anon_sym_SLASH);
      if (lookahead == '*') ADVANCE(39);
      if (lookahead == '/') ADVANCE(31);
      END_STATE();
    case 46:
      ACCEPT_TOKEN(anon_sym_EQ);
      END_STATE();
    case 47:
      ACCEPT_TOKEN(anon_sym_POUND);
      END_STATE();
    case 48:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 49:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 50:
      ACCEPT_TOKEN(anon_sym_println);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(21);
      END_STATE();
    case 51:
      ACCEPT_TOKEN(anon_sym_return);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(21);
      END_STATE();
    case 52:
      ACCEPT_TOKEN(anon_sym_PLUS);
      END_STATE();
    case 53:
      ACCEPT_TOKEN(anon_sym_DASH);
      END_STATE();
    case 54:
      ACCEPT_TOKEN(anon_sym_STAR);
      END_STATE();
    case 55:
      ACCEPT_TOKEN(anon_sym_def);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(21);
      END_STATE();
    case 56:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 57:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      END_STATE();
    case 58:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 0},
  [2] = {.lex_state = 0},
  [3] = {.lex_state = 0},
  [4] = {.lex_state = 0},
  [5] = {.lex_state = 0},
  [6] = {.lex_state = 0},
  [7] = {.lex_state = 0},
  [8] = {.lex_state = 0},
  [9] = {.lex_state = 0},
  [10] = {.lex_state = 0},
  [11] = {.lex_state = 0},
  [12] = {.lex_state = 0},
  [13] = {.lex_state = 0},
  [14] = {.lex_state = 0},
  [15] = {.lex_state = 0},
  [16] = {.lex_state = 0},
  [17] = {.lex_state = 0},
  [18] = {.lex_state = 0},
  [19] = {.lex_state = 0},
  [20] = {.lex_state = 0},
  [21] = {.lex_state = 0},
  [22] = {.lex_state = 0},
  [23] = {.lex_state = 0},
  [24] = {.lex_state = 0},
  [25] = {.lex_state = 0},
  [26] = {.lex_state = 0},
  [27] = {.lex_state = 2},
  [28] = {.lex_state = 2},
  [29] = {.lex_state = 0},
  [30] = {.lex_state = 0},
  [31] = {.lex_state = 0},
  [32] = {.lex_state = 0},
  [33] = {.lex_state = 0},
  [34] = {.lex_state = 0},
  [35] = {.lex_state = 0},
  [36] = {.lex_state = 0},
  [37] = {.lex_state = 0},
  [38] = {.lex_state = 0},
  [39] = {.lex_state = 0},
  [40] = {.lex_state = 0},
  [41] = {.lex_state = 0},
  [42] = {.lex_state = 0},
  [43] = {.lex_state = 0},
  [44] = {.lex_state = 0},
  [45] = {.lex_state = 0},
  [46] = {.lex_state = 0},
  [47] = {.lex_state = 0},
  [48] = {.lex_state = 0},
  [49] = {.lex_state = 0},
  [50] = {.lex_state = 0},
  [51] = {.lex_state = 1},
  [52] = {.lex_state = 1},
  [53] = {.lex_state = 1},
  [54] = {.lex_state = 1},
  [55] = {.lex_state = 0},
  [56] = {.lex_state = 0},
  [57] = {.lex_state = 0},
  [58] = {.lex_state = 0},
  [59] = {.lex_state = 0},
  [60] = {.lex_state = 1},
  [61] = {.lex_state = 0},
  [62] = {.lex_state = 1},
  [63] = {.lex_state = 0},
  [64] = {.lex_state = 0},
  [65] = {.lex_state = 0},
  [66] = {.lex_state = 1},
  [67] = {.lex_state = 0},
  [68] = {.lex_state = 0},
  [69] = {.lex_state = 0},
  [70] = {.lex_state = 29},
  [71] = {.lex_state = 0},
  [72] = {.lex_state = 0},
  [73] = {.lex_state = 1},
  [74] = {.lex_state = 0},
  [75] = {.lex_state = 0},
  [76] = {.lex_state = 0},
  [77] = {.lex_state = 0},
  [78] = {.lex_state = 0},
  [79] = {.lex_state = 37},
  [80] = {.lex_state = 4},
  [81] = {.lex_state = 0},
  [82] = {.lex_state = 1},
  [83] = {.lex_state = 0},
  [84] = {.lex_state = 0},
  [85] = {.lex_state = 0},
  [86] = {.lex_state = 0},
  [87] = {.lex_state = 0},
  [88] = {.lex_state = 0},
  [89] = {.lex_state = 0},
  [90] = {.lex_state = 25},
  [91] = {.lex_state = 25},
  [92] = {.lex_state = 29},
  [93] = {.lex_state = 0},
  [94] = {.lex_state = 0},
  [95] = {.lex_state = 0},
  [96] = {.lex_state = 0},
  [97] = {.lex_state = 0},
  [98] = {.lex_state = 1},
  [99] = {(TSStateId)(-1)},
  [100] = {(TSStateId)(-1)},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [0] = {
    [sym_comment] = STATE(0),
    [ts_builtin_sym_end] = ACTIONS(1),
    [sym_identifier] = ACTIONS(1),
    [sym_number] = ACTIONS(1),
    [anon_sym_SQUOTE] = ACTIONS(1),
    [anon_sym_DQUOTE] = ACTIONS(1),
    [anon_sym_SLASH_SLASH] = ACTIONS(3),
    [anon_sym_SLASH_STAR] = ACTIONS(5),
    [anon_sym_SLASH] = ACTIONS(1),
    [anon_sym_EQ] = ACTIONS(1),
    [anon_sym_POUND] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [anon_sym_println] = ACTIONS(1),
    [anon_sym_return] = ACTIONS(1),
    [anon_sym_PLUS] = ACTIONS(1),
    [anon_sym_DASH] = ACTIONS(1),
    [anon_sym_STAR] = ACTIONS(1),
    [anon_sym_def] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
    [anon_sym_LBRACE] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
  },
  [1] = {
    [sym_source_file] = STATE(88),
    [sym_string] = STATE(16),
    [sym_comment] = STATE(1),
    [sym__statement] = STATE(31),
    [sym__assignment_definition] = STATE(37),
    [sym_left_hand_side] = STATE(94),
    [sym_hash_like_function] = STATE(71),
    [sym__simple_statement] = STATE(37),
    [sym_print_statement] = STATE(32),
    [sym_return_statement] = STATE(32),
    [sym__expression] = STATE(20),
    [sym_binary_expression] = STATE(16),
    [sym_function_definition] = STATE(37),
    [aux_sym_source_file_repeat1] = STATE(4),
    [ts_builtin_sym_end] = ACTIONS(7),
    [sym_identifier] = ACTIONS(9),
    [sym_number] = ACTIONS(11),
    [anon_sym_SQUOTE] = ACTIONS(13),
    [anon_sym_DQUOTE] = ACTIONS(15),
    [anon_sym_SLASH_SLASH] = ACTIONS(3),
    [anon_sym_SLASH_STAR] = ACTIONS(5),
    [anon_sym_POUND] = ACTIONS(17),
    [anon_sym_LPAREN] = ACTIONS(19),
    [anon_sym_println] = ACTIONS(21),
    [anon_sym_return] = ACTIONS(23),
    [anon_sym_def] = ACTIONS(25),
  },
  [2] = {
    [sym_string] = STATE(17),
    [sym_comment] = STATE(2),
    [sym__statement] = STATE(34),
    [sym__assignment_definition] = STATE(35),
    [sym_left_hand_side] = STATE(81),
    [sym_hash_like_function] = STATE(71),
    [sym__simple_statement] = STATE(35),
    [sym_print_statement] = STATE(36),
    [sym_return_statement] = STATE(36),
    [sym__expression] = STATE(23),
    [sym_binary_expression] = STATE(17),
    [sym_function_definition] = STATE(35),
    [aux_sym_source_file_repeat1] = STATE(7),
    [sym_identifier] = ACTIONS(27),
    [sym_number] = ACTIONS(29),
    [anon_sym_SQUOTE] = ACTIONS(31),
    [anon_sym_DQUOTE] = ACTIONS(33),
    [anon_sym_SLASH_SLASH] = ACTIONS(3),
    [anon_sym_SLASH_STAR] = ACTIONS(5),
    [anon_sym_POUND] = ACTIONS(17),
    [anon_sym_LPAREN] = ACTIONS(35),
    [anon_sym_println] = ACTIONS(37),
    [anon_sym_return] = ACTIONS(39),
    [anon_sym_def] = ACTIONS(41),
    [anon_sym_RBRACE] = ACTIONS(43),
  },
  [3] = {
    [sym_string] = STATE(17),
    [sym_comment] = STATE(3),
    [sym__statement] = STATE(34),
    [sym__assignment_definition] = STATE(35),
    [sym_left_hand_side] = STATE(81),
    [sym_hash_like_function] = STATE(71),
    [sym__simple_statement] = STATE(35),
    [sym_print_statement] = STATE(36),
    [sym_return_statement] = STATE(36),
    [sym__expression] = STATE(23),
    [sym_binary_expression] = STATE(17),
    [sym_function_definition] = STATE(35),
    [aux_sym_source_file_repeat1] = STATE(7),
    [sym_identifier] = ACTIONS(27),
    [sym_number] = ACTIONS(29),
    [anon_sym_SQUOTE] = ACTIONS(31),
    [anon_sym_DQUOTE] = ACTIONS(33),
    [anon_sym_SLASH_SLASH] = ACTIONS(3),
    [anon_sym_SLASH_STAR] = ACTIONS(5),
    [anon_sym_POUND] = ACTIONS(17),
    [anon_sym_LPAREN] = ACTIONS(35),
    [anon_sym_println] = ACTIONS(37),
    [anon_sym_return] = ACTIONS(39),
    [anon_sym_def] = ACTIONS(41),
    [anon_sym_RBRACE] = ACTIONS(45),
  },
  [4] = {
    [sym_string] = STATE(16),
    [sym_comment] = STATE(4),
    [sym__statement] = STATE(31),
    [sym__assignment_definition] = STATE(37),
    [sym_left_hand_side] = STATE(94),
    [sym_hash_like_function] = STATE(71),
    [sym__simple_statement] = STATE(37),
    [sym_print_statement] = STATE(32),
    [sym_return_statement] = STATE(32),
    [sym__expression] = STATE(20),
    [sym_binary_expression] = STATE(16),
    [sym_function_definition] = STATE(37),
    [aux_sym_source_file_repeat1] = STATE(5),
    [ts_builtin_sym_end] = ACTIONS(47),
    [sym_identifier] = ACTIONS(9),
    [sym_number] = ACTIONS(11),
    [anon_sym_SQUOTE] = ACTIONS(13),
    [anon_sym_DQUOTE] = ACTIONS(15),
    [anon_sym_SLASH_SLASH] = ACTIONS(3),
    [anon_sym_SLASH_STAR] = ACTIONS(5),
    [anon_sym_POUND] = ACTIONS(17),
    [anon_sym_LPAREN] = ACTIONS(19),
    [anon_sym_println] = ACTIONS(21),
    [anon_sym_return] = ACTIONS(23),
    [anon_sym_def] = ACTIONS(25),
  },
  [5] = {
    [sym_string] = STATE(16),
    [sym_comment] = STATE(5),
    [sym__statement] = STATE(31),
    [sym__assignment_definition] = STATE(37),
    [sym_left_hand_side] = STATE(94),
    [sym_hash_like_function] = STATE(71),
    [sym__simple_statement] = STATE(37),
    [sym_print_statement] = STATE(32),
    [sym_return_statement] = STATE(32),
    [sym__expression] = STATE(20),
    [sym_binary_expression] = STATE(16),
    [sym_function_definition] = STATE(37),
    [aux_sym_source_file_repeat1] = STATE(5),
    [ts_builtin_sym_end] = ACTIONS(49),
    [sym_identifier] = ACTIONS(51),
    [sym_number] = ACTIONS(54),
    [anon_sym_SQUOTE] = ACTIONS(57),
    [anon_sym_DQUOTE] = ACTIONS(60),
    [anon_sym_SLASH_SLASH] = ACTIONS(3),
    [anon_sym_SLASH_STAR] = ACTIONS(5),
    [anon_sym_POUND] = ACTIONS(63),
    [anon_sym_LPAREN] = ACTIONS(66),
    [anon_sym_println] = ACTIONS(69),
    [anon_sym_return] = ACTIONS(72),
    [anon_sym_def] = ACTIONS(75),
  },
  [6] = {
    [sym_string] = STATE(17),
    [sym_comment] = STATE(6),
    [sym__statement] = STATE(34),
    [sym__assignment_definition] = STATE(35),
    [sym_left_hand_side] = STATE(81),
    [sym_hash_like_function] = STATE(71),
    [sym__simple_statement] = STATE(35),
    [sym_print_statement] = STATE(36),
    [sym_return_statement] = STATE(36),
    [sym__expression] = STATE(23),
    [sym_binary_expression] = STATE(17),
    [sym_function_definition] = STATE(35),
    [aux_sym_source_file_repeat1] = STATE(2),
    [sym_identifier] = ACTIONS(27),
    [sym_number] = ACTIONS(29),
    [anon_sym_SQUOTE] = ACTIONS(31),
    [anon_sym_DQUOTE] = ACTIONS(33),
    [anon_sym_SLASH_SLASH] = ACTIONS(3),
    [anon_sym_SLASH_STAR] = ACTIONS(5),
    [anon_sym_POUND] = ACTIONS(17),
    [anon_sym_LPAREN] = ACTIONS(35),
    [anon_sym_println] = ACTIONS(37),
    [anon_sym_return] = ACTIONS(39),
    [anon_sym_def] = ACTIONS(41),
    [anon_sym_RBRACE] = ACTIONS(78),
  },
  [7] = {
    [sym_string] = STATE(17),
    [sym_comment] = STATE(7),
    [sym__statement] = STATE(34),
    [sym__assignment_definition] = STATE(35),
    [sym_left_hand_side] = STATE(81),
    [sym_hash_like_function] = STATE(71),
    [sym__simple_statement] = STATE(35),
    [sym_print_statement] = STATE(36),
    [sym_return_statement] = STATE(36),
    [sym__expression] = STATE(23),
    [sym_binary_expression] = STATE(17),
    [sym_function_definition] = STATE(35),
    [aux_sym_source_file_repeat1] = STATE(7),
    [sym_identifier] = ACTIONS(80),
    [sym_number] = ACTIONS(83),
    [anon_sym_SQUOTE] = ACTIONS(86),
    [anon_sym_DQUOTE] = ACTIONS(89),
    [anon_sym_SLASH_SLASH] = ACTIONS(3),
    [anon_sym_SLASH_STAR] = ACTIONS(5),
    [anon_sym_POUND] = ACTIONS(63),
    [anon_sym_LPAREN] = ACTIONS(92),
    [anon_sym_println] = ACTIONS(95),
    [anon_sym_return] = ACTIONS(98),
    [anon_sym_def] = ACTIONS(101),
    [anon_sym_RBRACE] = ACTIONS(49),
  },
  [8] = {
    [sym_string] = STATE(17),
    [sym_comment] = STATE(8),
    [sym__statement] = STATE(34),
    [sym__assignment_definition] = STATE(35),
    [sym_left_hand_side] = STATE(81),
    [sym_hash_like_function] = STATE(71),
    [sym__simple_statement] = STATE(35),
    [sym_print_statement] = STATE(36),
    [sym_return_statement] = STATE(36),
    [sym__expression] = STATE(23),
    [sym_binary_expression] = STATE(17),
    [sym_function_definition] = STATE(35),
    [aux_sym_source_file_repeat1] = STATE(3),
    [sym_identifier] = ACTIONS(27),
    [sym_number] = ACTIONS(29),
    [anon_sym_SQUOTE] = ACTIONS(31),
    [anon_sym_DQUOTE] = ACTIONS(33),
    [anon_sym_SLASH_SLASH] = ACTIONS(3),
    [anon_sym_SLASH_STAR] = ACTIONS(5),
    [anon_sym_POUND] = ACTIONS(17),
    [anon_sym_LPAREN] = ACTIONS(35),
    [anon_sym_println] = ACTIONS(37),
    [anon_sym_return] = ACTIONS(39),
    [anon_sym_def] = ACTIONS(41),
    [anon_sym_RBRACE] = ACTIONS(104),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 16,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(11), 1,
      sym_number,
    ACTIONS(13), 1,
      anon_sym_SQUOTE,
    ACTIONS(15), 1,
      anon_sym_DQUOTE,
    ACTIONS(19), 1,
      anon_sym_LPAREN,
    ACTIONS(21), 1,
      anon_sym_println,
    ACTIONS(23), 1,
      anon_sym_return,
    ACTIONS(25), 1,
      anon_sym_def,
    ACTIONS(106), 1,
      sym_identifier,
    STATE(9), 1,
      sym_comment,
    STATE(19), 1,
      sym__expression,
    STATE(30), 1,
      sym_right_hand_side,
    STATE(16), 2,
      sym_string,
      sym_binary_expression,
    STATE(32), 2,
      sym_print_statement,
      sym_return_statement,
    STATE(39), 2,
      sym__simple_statement,
      sym_function_definition,
  [52] = 16,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(29), 1,
      sym_number,
    ACTIONS(31), 1,
      anon_sym_SQUOTE,
    ACTIONS(33), 1,
      anon_sym_DQUOTE,
    ACTIONS(35), 1,
      anon_sym_LPAREN,
    ACTIONS(37), 1,
      anon_sym_println,
    ACTIONS(39), 1,
      anon_sym_return,
    ACTIONS(41), 1,
      anon_sym_def,
    ACTIONS(108), 1,
      sym_identifier,
    STATE(10), 1,
      sym_comment,
    STATE(25), 1,
      sym__expression,
    STATE(42), 1,
      sym_right_hand_side,
    STATE(17), 2,
      sym_string,
      sym_binary_expression,
    STATE(36), 2,
      sym_print_statement,
      sym_return_statement,
    STATE(43), 2,
      sym__simple_statement,
      sym_function_definition,
  [104] = 6,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(114), 1,
      anon_sym_EQ,
    STATE(11), 1,
      sym_comment,
    ACTIONS(112), 5,
      sym_identifier,
      anon_sym_SLASH,
      anon_sym_println,
      anon_sym_return,
      anon_sym_def,
    ACTIONS(110), 9,
      ts_builtin_sym_end,
      sym_number,
      anon_sym_SQUOTE,
      anon_sym_DQUOTE,
      anon_sym_POUND,
      anon_sym_LPAREN,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
  [135] = 6,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(114), 1,
      anon_sym_EQ,
    STATE(12), 1,
      sym_comment,
    ACTIONS(112), 5,
      sym_identifier,
      anon_sym_SLASH,
      anon_sym_println,
      anon_sym_return,
      anon_sym_def,
    ACTIONS(110), 9,
      sym_number,
      anon_sym_SQUOTE,
      anon_sym_DQUOTE,
      anon_sym_POUND,
      anon_sym_LPAREN,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_RBRACE,
  [166] = 5,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    STATE(13), 1,
      sym_comment,
    ACTIONS(118), 5,
      sym_identifier,
      anon_sym_SLASH,
      anon_sym_println,
      anon_sym_return,
      anon_sym_def,
    ACTIONS(116), 10,
      ts_builtin_sym_end,
      sym_number,
      anon_sym_SQUOTE,
      anon_sym_DQUOTE,
      anon_sym_POUND,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
  [195] = 5,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    STATE(14), 1,
      sym_comment,
    ACTIONS(122), 5,
      sym_identifier,
      anon_sym_SLASH,
      anon_sym_println,
      anon_sym_return,
      anon_sym_def,
    ACTIONS(120), 10,
      ts_builtin_sym_end,
      sym_number,
      anon_sym_SQUOTE,
      anon_sym_DQUOTE,
      anon_sym_POUND,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
  [224] = 5,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    STATE(15), 1,
      sym_comment,
    ACTIONS(126), 5,
      sym_identifier,
      anon_sym_SLASH,
      anon_sym_println,
      anon_sym_return,
      anon_sym_def,
    ACTIONS(124), 10,
      ts_builtin_sym_end,
      sym_number,
      anon_sym_SQUOTE,
      anon_sym_DQUOTE,
      anon_sym_POUND,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
  [253] = 5,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    STATE(16), 1,
      sym_comment,
    ACTIONS(112), 5,
      sym_identifier,
      anon_sym_SLASH,
      anon_sym_println,
      anon_sym_return,
      anon_sym_def,
    ACTIONS(110), 10,
      ts_builtin_sym_end,
      sym_number,
      anon_sym_SQUOTE,
      anon_sym_DQUOTE,
      anon_sym_POUND,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
  [282] = 5,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    STATE(17), 1,
      sym_comment,
    ACTIONS(112), 5,
      sym_identifier,
      anon_sym_SLASH,
      anon_sym_println,
      anon_sym_return,
      anon_sym_def,
    ACTIONS(110), 9,
      sym_number,
      anon_sym_SQUOTE,
      anon_sym_DQUOTE,
      anon_sym_POUND,
      anon_sym_LPAREN,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_RBRACE,
  [310] = 7,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(132), 1,
      anon_sym_SLASH,
    STATE(18), 1,
      sym_comment,
    ACTIONS(134), 3,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
    ACTIONS(130), 4,
      sym_identifier,
      anon_sym_println,
      anon_sym_return,
      anon_sym_def,
    ACTIONS(128), 6,
      ts_builtin_sym_end,
      sym_number,
      anon_sym_SQUOTE,
      anon_sym_DQUOTE,
      anon_sym_POUND,
      anon_sym_LPAREN,
  [342] = 7,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(132), 1,
      anon_sym_SLASH,
    STATE(19), 1,
      sym_comment,
    ACTIONS(134), 3,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
    ACTIONS(138), 4,
      sym_identifier,
      anon_sym_println,
      anon_sym_return,
      anon_sym_def,
    ACTIONS(136), 6,
      ts_builtin_sym_end,
      sym_number,
      anon_sym_SQUOTE,
      anon_sym_DQUOTE,
      anon_sym_POUND,
      anon_sym_LPAREN,
  [374] = 7,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(132), 1,
      anon_sym_SLASH,
    STATE(20), 1,
      sym_comment,
    ACTIONS(134), 3,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
    ACTIONS(142), 4,
      sym_identifier,
      anon_sym_println,
      anon_sym_return,
      anon_sym_def,
    ACTIONS(140), 6,
      ts_builtin_sym_end,
      sym_number,
      anon_sym_SQUOTE,
      anon_sym_DQUOTE,
      anon_sym_POUND,
      anon_sym_LPAREN,
  [406] = 7,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(144), 1,
      anon_sym_SLASH,
    STATE(21), 1,
      sym_comment,
    ACTIONS(146), 3,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
    ACTIONS(130), 4,
      sym_identifier,
      anon_sym_println,
      anon_sym_return,
      anon_sym_def,
    ACTIONS(128), 6,
      sym_number,
      anon_sym_SQUOTE,
      anon_sym_DQUOTE,
      anon_sym_POUND,
      anon_sym_LPAREN,
      anon_sym_RBRACE,
  [438] = 5,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    STATE(22), 1,
      sym_comment,
    ACTIONS(122), 5,
      sym_identifier,
      anon_sym_SLASH,
      anon_sym_println,
      anon_sym_return,
      anon_sym_def,
    ACTIONS(120), 9,
      sym_number,
      anon_sym_SQUOTE,
      anon_sym_DQUOTE,
      anon_sym_POUND,
      anon_sym_LPAREN,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_RBRACE,
  [466] = 7,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(144), 1,
      anon_sym_SLASH,
    STATE(23), 1,
      sym_comment,
    ACTIONS(146), 3,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
    ACTIONS(142), 4,
      sym_identifier,
      anon_sym_println,
      anon_sym_return,
      anon_sym_def,
    ACTIONS(140), 6,
      sym_number,
      anon_sym_SQUOTE,
      anon_sym_DQUOTE,
      anon_sym_POUND,
      anon_sym_LPAREN,
      anon_sym_RBRACE,
  [498] = 5,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    STATE(24), 1,
      sym_comment,
    ACTIONS(118), 5,
      sym_identifier,
      anon_sym_SLASH,
      anon_sym_println,
      anon_sym_return,
      anon_sym_def,
    ACTIONS(116), 9,
      sym_number,
      anon_sym_SQUOTE,
      anon_sym_DQUOTE,
      anon_sym_POUND,
      anon_sym_LPAREN,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_RBRACE,
  [526] = 7,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(144), 1,
      anon_sym_SLASH,
    STATE(25), 1,
      sym_comment,
    ACTIONS(146), 3,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
    ACTIONS(138), 4,
      sym_identifier,
      anon_sym_println,
      anon_sym_return,
      anon_sym_def,
    ACTIONS(136), 6,
      sym_number,
      anon_sym_SQUOTE,
      anon_sym_DQUOTE,
      anon_sym_POUND,
      anon_sym_LPAREN,
      anon_sym_RBRACE,
  [558] = 5,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    STATE(26), 1,
      sym_comment,
    ACTIONS(126), 5,
      sym_identifier,
      anon_sym_SLASH,
      anon_sym_println,
      anon_sym_return,
      anon_sym_def,
    ACTIONS(124), 9,
      sym_number,
      anon_sym_SQUOTE,
      anon_sym_DQUOTE,
      anon_sym_POUND,
      anon_sym_LPAREN,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_RBRACE,
  [586] = 14,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(11), 1,
      sym_number,
    ACTIONS(13), 1,
      anon_sym_SQUOTE,
    ACTIONS(15), 1,
      anon_sym_DQUOTE,
    ACTIONS(19), 1,
      anon_sym_LPAREN,
    ACTIONS(21), 1,
      anon_sym_println,
    ACTIONS(23), 1,
      anon_sym_return,
    ACTIONS(106), 1,
      sym_identifier,
    STATE(18), 1,
      sym__expression,
    STATE(27), 1,
      sym_comment,
    STATE(50), 1,
      sym__simple_statement,
    STATE(16), 2,
      sym_string,
      sym_binary_expression,
    STATE(32), 2,
      sym_print_statement,
      sym_return_statement,
  [631] = 14,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(29), 1,
      sym_number,
    ACTIONS(31), 1,
      anon_sym_SQUOTE,
    ACTIONS(33), 1,
      anon_sym_DQUOTE,
    ACTIONS(35), 1,
      anon_sym_LPAREN,
    ACTIONS(37), 1,
      anon_sym_println,
    ACTIONS(39), 1,
      anon_sym_return,
    ACTIONS(108), 1,
      sym_identifier,
    STATE(21), 1,
      sym__expression,
    STATE(28), 1,
      sym_comment,
    STATE(38), 1,
      sym__simple_statement,
    STATE(17), 2,
      sym_string,
      sym_binary_expression,
    STATE(36), 2,
      sym_print_statement,
      sym_return_statement,
  [676] = 5,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    STATE(29), 1,
      sym_comment,
    ACTIONS(148), 4,
      sym_identifier,
      anon_sym_println,
      anon_sym_return,
      anon_sym_def,
    ACTIONS(150), 6,
      sym_number,
      anon_sym_SQUOTE,
      anon_sym_DQUOTE,
      anon_sym_POUND,
      anon_sym_LPAREN,
      anon_sym_RBRACE,
  [700] = 5,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    STATE(30), 1,
      sym_comment,
    ACTIONS(154), 4,
      sym_identifier,
      anon_sym_println,
      anon_sym_return,
      anon_sym_def,
    ACTIONS(152), 6,
      ts_builtin_sym_end,
      sym_number,
      anon_sym_SQUOTE,
      anon_sym_DQUOTE,
      anon_sym_POUND,
      anon_sym_LPAREN,
  [724] = 5,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    STATE(31), 1,
      sym_comment,
    ACTIONS(158), 4,
      sym_identifier,
      anon_sym_println,
      anon_sym_return,
      anon_sym_def,
    ACTIONS(156), 6,
      ts_builtin_sym_end,
      sym_number,
      anon_sym_SQUOTE,
      anon_sym_DQUOTE,
      anon_sym_POUND,
      anon_sym_LPAREN,
  [748] = 5,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    STATE(32), 1,
      sym_comment,
    ACTIONS(162), 4,
      sym_identifier,
      anon_sym_println,
      anon_sym_return,
      anon_sym_def,
    ACTIONS(160), 6,
      ts_builtin_sym_end,
      sym_number,
      anon_sym_SQUOTE,
      anon_sym_DQUOTE,
      anon_sym_POUND,
      anon_sym_LPAREN,
  [772] = 5,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    STATE(33), 1,
      sym_comment,
    ACTIONS(166), 4,
      sym_identifier,
      anon_sym_println,
      anon_sym_return,
      anon_sym_def,
    ACTIONS(164), 6,
      ts_builtin_sym_end,
      sym_number,
      anon_sym_SQUOTE,
      anon_sym_DQUOTE,
      anon_sym_POUND,
      anon_sym_LPAREN,
  [796] = 5,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    STATE(34), 1,
      sym_comment,
    ACTIONS(158), 4,
      sym_identifier,
      anon_sym_println,
      anon_sym_return,
      anon_sym_def,
    ACTIONS(156), 6,
      sym_number,
      anon_sym_SQUOTE,
      anon_sym_DQUOTE,
      anon_sym_POUND,
      anon_sym_LPAREN,
      anon_sym_RBRACE,
  [820] = 5,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    STATE(35), 1,
      sym_comment,
    ACTIONS(142), 4,
      sym_identifier,
      anon_sym_println,
      anon_sym_return,
      anon_sym_def,
    ACTIONS(140), 6,
      sym_number,
      anon_sym_SQUOTE,
      anon_sym_DQUOTE,
      anon_sym_POUND,
      anon_sym_LPAREN,
      anon_sym_RBRACE,
  [844] = 5,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    STATE(36), 1,
      sym_comment,
    ACTIONS(162), 4,
      sym_identifier,
      anon_sym_println,
      anon_sym_return,
      anon_sym_def,
    ACTIONS(160), 6,
      sym_number,
      anon_sym_SQUOTE,
      anon_sym_DQUOTE,
      anon_sym_POUND,
      anon_sym_LPAREN,
      anon_sym_RBRACE,
  [868] = 5,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    STATE(37), 1,
      sym_comment,
    ACTIONS(142), 4,
      sym_identifier,
      anon_sym_println,
      anon_sym_return,
      anon_sym_def,
    ACTIONS(140), 6,
      ts_builtin_sym_end,
      sym_number,
      anon_sym_SQUOTE,
      anon_sym_DQUOTE,
      anon_sym_POUND,
      anon_sym_LPAREN,
  [892] = 5,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    STATE(38), 1,
      sym_comment,
    ACTIONS(130), 4,
      sym_identifier,
      anon_sym_println,
      anon_sym_return,
      anon_sym_def,
    ACTIONS(128), 6,
      sym_number,
      anon_sym_SQUOTE,
      anon_sym_DQUOTE,
      anon_sym_POUND,
      anon_sym_LPAREN,
      anon_sym_RBRACE,
  [916] = 5,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    STATE(39), 1,
      sym_comment,
    ACTIONS(138), 4,
      sym_identifier,
      anon_sym_println,
      anon_sym_return,
      anon_sym_def,
    ACTIONS(136), 6,
      ts_builtin_sym_end,
      sym_number,
      anon_sym_SQUOTE,
      anon_sym_DQUOTE,
      anon_sym_POUND,
      anon_sym_LPAREN,
  [940] = 5,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    STATE(40), 1,
      sym_comment,
    ACTIONS(170), 4,
      sym_identifier,
      anon_sym_println,
      anon_sym_return,
      anon_sym_def,
    ACTIONS(168), 6,
      ts_builtin_sym_end,
      sym_number,
      anon_sym_SQUOTE,
      anon_sym_DQUOTE,
      anon_sym_POUND,
      anon_sym_LPAREN,
  [964] = 5,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    STATE(41), 1,
      sym_comment,
    ACTIONS(174), 4,
      sym_identifier,
      anon_sym_println,
      anon_sym_return,
      anon_sym_def,
    ACTIONS(172), 6,
      ts_builtin_sym_end,
      sym_number,
      anon_sym_SQUOTE,
      anon_sym_DQUOTE,
      anon_sym_POUND,
      anon_sym_LPAREN,
  [988] = 5,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    STATE(42), 1,
      sym_comment,
    ACTIONS(154), 4,
      sym_identifier,
      anon_sym_println,
      anon_sym_return,
      anon_sym_def,
    ACTIONS(152), 6,
      sym_number,
      anon_sym_SQUOTE,
      anon_sym_DQUOTE,
      anon_sym_POUND,
      anon_sym_LPAREN,
      anon_sym_RBRACE,
  [1012] = 5,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    STATE(43), 1,
      sym_comment,
    ACTIONS(138), 4,
      sym_identifier,
      anon_sym_println,
      anon_sym_return,
      anon_sym_def,
    ACTIONS(136), 6,
      sym_number,
      anon_sym_SQUOTE,
      anon_sym_DQUOTE,
      anon_sym_POUND,
      anon_sym_LPAREN,
      anon_sym_RBRACE,
  [1036] = 5,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    STATE(44), 1,
      sym_comment,
    ACTIONS(174), 4,
      sym_identifier,
      anon_sym_println,
      anon_sym_return,
      anon_sym_def,
    ACTIONS(172), 6,
      sym_number,
      anon_sym_SQUOTE,
      anon_sym_DQUOTE,
      anon_sym_POUND,
      anon_sym_LPAREN,
      anon_sym_RBRACE,
  [1060] = 5,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    STATE(45), 1,
      sym_comment,
    ACTIONS(178), 4,
      sym_identifier,
      anon_sym_println,
      anon_sym_return,
      anon_sym_def,
    ACTIONS(176), 6,
      ts_builtin_sym_end,
      sym_number,
      anon_sym_SQUOTE,
      anon_sym_DQUOTE,
      anon_sym_POUND,
      anon_sym_LPAREN,
  [1084] = 5,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    STATE(46), 1,
      sym_comment,
    ACTIONS(166), 4,
      sym_identifier,
      anon_sym_println,
      anon_sym_return,
      anon_sym_def,
    ACTIONS(164), 6,
      sym_number,
      anon_sym_SQUOTE,
      anon_sym_DQUOTE,
      anon_sym_POUND,
      anon_sym_LPAREN,
      anon_sym_RBRACE,
  [1108] = 5,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    STATE(47), 1,
      sym_comment,
    ACTIONS(170), 4,
      sym_identifier,
      anon_sym_println,
      anon_sym_return,
      anon_sym_def,
    ACTIONS(168), 6,
      sym_number,
      anon_sym_SQUOTE,
      anon_sym_DQUOTE,
      anon_sym_POUND,
      anon_sym_LPAREN,
      anon_sym_RBRACE,
  [1132] = 5,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    STATE(48), 1,
      sym_comment,
    ACTIONS(148), 4,
      sym_identifier,
      anon_sym_println,
      anon_sym_return,
      anon_sym_def,
    ACTIONS(150), 6,
      ts_builtin_sym_end,
      sym_number,
      anon_sym_SQUOTE,
      anon_sym_DQUOTE,
      anon_sym_POUND,
      anon_sym_LPAREN,
  [1156] = 5,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    STATE(49), 1,
      sym_comment,
    ACTIONS(178), 4,
      sym_identifier,
      anon_sym_println,
      anon_sym_return,
      anon_sym_def,
    ACTIONS(176), 6,
      sym_number,
      anon_sym_SQUOTE,
      anon_sym_DQUOTE,
      anon_sym_POUND,
      anon_sym_LPAREN,
      anon_sym_RBRACE,
  [1180] = 5,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    STATE(50), 1,
      sym_comment,
    ACTIONS(130), 4,
      sym_identifier,
      anon_sym_println,
      anon_sym_return,
      anon_sym_def,
    ACTIONS(128), 6,
      ts_builtin_sym_end,
      sym_number,
      anon_sym_SQUOTE,
      anon_sym_DQUOTE,
      anon_sym_POUND,
      anon_sym_LPAREN,
  [1204] = 9,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(13), 1,
      anon_sym_SQUOTE,
    ACTIONS(15), 1,
      anon_sym_DQUOTE,
    ACTIONS(19), 1,
      anon_sym_LPAREN,
    STATE(15), 1,
      sym__expression,
    STATE(51), 1,
      sym_comment,
    ACTIONS(11), 2,
      sym_identifier,
      sym_number,
    STATE(16), 2,
      sym_string,
      sym_binary_expression,
  [1234] = 9,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(31), 1,
      anon_sym_SQUOTE,
    ACTIONS(33), 1,
      anon_sym_DQUOTE,
    ACTIONS(35), 1,
      anon_sym_LPAREN,
    STATE(26), 1,
      sym__expression,
    STATE(52), 1,
      sym_comment,
    ACTIONS(29), 2,
      sym_identifier,
      sym_number,
    STATE(17), 2,
      sym_string,
      sym_binary_expression,
  [1264] = 9,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(13), 1,
      anon_sym_SQUOTE,
    ACTIONS(15), 1,
      anon_sym_DQUOTE,
    ACTIONS(19), 1,
      anon_sym_LPAREN,
    STATE(53), 1,
      sym_comment,
    STATE(55), 1,
      sym__expression,
    ACTIONS(11), 2,
      sym_identifier,
      sym_number,
    STATE(16), 2,
      sym_string,
      sym_binary_expression,
  [1294] = 9,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(13), 1,
      anon_sym_SQUOTE,
    ACTIONS(15), 1,
      anon_sym_DQUOTE,
    ACTIONS(19), 1,
      anon_sym_LPAREN,
    STATE(54), 1,
      sym_comment,
    STATE(56), 1,
      sym__expression,
    ACTIONS(11), 2,
      sym_identifier,
      sym_number,
    STATE(16), 2,
      sym_string,
      sym_binary_expression,
  [1324] = 6,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(132), 1,
      anon_sym_SLASH,
    ACTIONS(180), 1,
      anon_sym_RPAREN,
    STATE(55), 1,
      sym_comment,
    ACTIONS(134), 3,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
  [1345] = 6,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(132), 1,
      anon_sym_SLASH,
    ACTIONS(182), 1,
      anon_sym_RPAREN,
    STATE(56), 1,
      sym_comment,
    ACTIONS(134), 3,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
  [1366] = 7,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(13), 1,
      anon_sym_SQUOTE,
    ACTIONS(15), 1,
      anon_sym_DQUOTE,
    ACTIONS(184), 1,
      sym_number,
    STATE(57), 1,
      sym_comment,
    STATE(78), 1,
      sym_string,
  [1388] = 7,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(13), 1,
      anon_sym_SQUOTE,
    ACTIONS(15), 1,
      anon_sym_DQUOTE,
    ACTIONS(186), 1,
      sym_number,
    STATE(58), 1,
      sym_comment,
    STATE(86), 1,
      sym_string,
  [1410] = 5,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(188), 1,
      anon_sym_RPAREN,
    ACTIONS(190), 1,
      anon_sym_COMMA,
    STATE(59), 2,
      sym_comment,
      aux_sym_parameters_repeat1,
  [1427] = 6,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(193), 1,
      sym_identifier,
    ACTIONS(195), 1,
      anon_sym_RPAREN,
    STATE(60), 1,
      sym_comment,
    STATE(89), 1,
      sym_parameters,
  [1446] = 6,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(197), 1,
      anon_sym_RPAREN,
    ACTIONS(199), 1,
      anon_sym_COMMA,
    STATE(61), 1,
      sym_comment,
    STATE(63), 1,
      aux_sym_parameters_repeat1,
  [1465] = 6,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(193), 1,
      sym_identifier,
    ACTIONS(201), 1,
      anon_sym_RPAREN,
    STATE(62), 1,
      sym_comment,
    STATE(74), 1,
      sym_parameters,
  [1484] = 6,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(199), 1,
      anon_sym_COMMA,
    ACTIONS(203), 1,
      anon_sym_RPAREN,
    STATE(59), 1,
      aux_sym_parameters_repeat1,
    STATE(63), 1,
      sym_comment,
  [1503] = 5,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(205), 1,
      anon_sym_LBRACE,
    STATE(40), 1,
      sym_function_body,
    STATE(64), 1,
      sym_comment,
  [1519] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    STATE(65), 1,
      sym_comment,
    ACTIONS(188), 2,
      anon_sym_RPAREN,
      anon_sym_COMMA,
  [1533] = 5,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(193), 1,
      sym_identifier,
    STATE(66), 1,
      sym_comment,
    STATE(77), 1,
      sym_parameters,
  [1549] = 5,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(205), 1,
      anon_sym_LBRACE,
    STATE(45), 1,
      sym_function_body,
    STATE(67), 1,
      sym_comment,
  [1565] = 5,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(207), 1,
      anon_sym_LBRACE,
    STATE(47), 1,
      sym_function_body,
    STATE(68), 1,
      sym_comment,
  [1581] = 5,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(207), 1,
      anon_sym_LBRACE,
    STATE(49), 1,
      sym_function_body,
    STATE(69), 1,
      sym_comment,
  [1597] = 4,
    ACTIONS(209), 1,
      aux_sym_string_token2,
    ACTIONS(211), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(213), 1,
      anon_sym_SLASH_STAR,
    STATE(70), 1,
      sym_comment,
  [1610] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(114), 1,
      anon_sym_EQ,
    STATE(71), 1,
      sym_comment,
  [1623] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(215), 1,
      anon_sym_SQUOTE,
    STATE(72), 1,
      sym_comment,
  [1636] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(217), 1,
      sym_identifier,
    STATE(73), 1,
      sym_comment,
  [1649] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(219), 1,
      anon_sym_RPAREN,
    STATE(74), 1,
      sym_comment,
  [1662] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(221), 1,
      anon_sym_EQ,
    STATE(75), 1,
      sym_comment,
  [1675] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(215), 1,
      anon_sym_DQUOTE,
    STATE(76), 1,
      sym_comment,
  [1688] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(223), 1,
      anon_sym_RPAREN,
    STATE(77), 1,
      sym_comment,
  [1701] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(225), 1,
      anon_sym_RPAREN,
    STATE(78), 1,
      sym_comment,
  [1714] = 4,
    ACTIONS(211), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(213), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(227), 1,
      aux_sym_comment_token1,
    STATE(79), 1,
      sym_comment,
  [1727] = 4,
    ACTIONS(211), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(213), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(229), 1,
      aux_sym_comment_token2,
    STATE(80), 1,
      sym_comment,
  [1740] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(231), 1,
      anon_sym_EQ,
    STATE(81), 1,
      sym_comment,
  [1753] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(233), 1,
      sym_identifier,
    STATE(82), 1,
      sym_comment,
  [1766] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(235), 1,
      anon_sym_SQUOTE,
    STATE(83), 1,
      sym_comment,
  [1779] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(235), 1,
      anon_sym_DQUOTE,
    STATE(84), 1,
      sym_comment,
  [1792] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(237), 1,
      anon_sym_LPAREN,
    STATE(85), 1,
      sym_comment,
  [1805] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(239), 1,
      anon_sym_RPAREN,
    STATE(86), 1,
      sym_comment,
  [1818] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(241), 1,
      anon_sym_LPAREN,
    STATE(87), 1,
      sym_comment,
  [1831] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(243), 1,
      ts_builtin_sym_end,
    STATE(88), 1,
      sym_comment,
  [1844] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(245), 1,
      anon_sym_RPAREN,
    STATE(89), 1,
      sym_comment,
  [1857] = 4,
    ACTIONS(211), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(213), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(247), 1,
      aux_sym_string_token1,
    STATE(90), 1,
      sym_comment,
  [1870] = 4,
    ACTIONS(211), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(213), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(249), 1,
      aux_sym_string_token1,
    STATE(91), 1,
      sym_comment,
  [1883] = 4,
    ACTIONS(211), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(213), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(251), 1,
      aux_sym_string_token2,
    STATE(92), 1,
      sym_comment,
  [1896] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(253), 1,
      anon_sym_LPAREN,
    STATE(93), 1,
      sym_comment,
  [1909] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(255), 1,
      anon_sym_EQ,
    STATE(94), 1,
      sym_comment,
  [1922] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(257), 1,
      anon_sym_SLASH,
    STATE(95), 1,
      sym_comment,
  [1935] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(259), 1,
      anon_sym_LPAREN,
    STATE(96), 1,
      sym_comment,
  [1948] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(261), 1,
      anon_sym_LPAREN,
    STATE(97), 1,
      sym_comment,
  [1961] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(263), 1,
      sym_identifier,
    STATE(98), 1,
      sym_comment,
  [1974] = 1,
    ACTIONS(265), 1,
      ts_builtin_sym_end,
  [1978] = 1,
    ACTIONS(267), 1,
      ts_builtin_sym_end,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(9)] = 0,
  [SMALL_STATE(10)] = 52,
  [SMALL_STATE(11)] = 104,
  [SMALL_STATE(12)] = 135,
  [SMALL_STATE(13)] = 166,
  [SMALL_STATE(14)] = 195,
  [SMALL_STATE(15)] = 224,
  [SMALL_STATE(16)] = 253,
  [SMALL_STATE(17)] = 282,
  [SMALL_STATE(18)] = 310,
  [SMALL_STATE(19)] = 342,
  [SMALL_STATE(20)] = 374,
  [SMALL_STATE(21)] = 406,
  [SMALL_STATE(22)] = 438,
  [SMALL_STATE(23)] = 466,
  [SMALL_STATE(24)] = 498,
  [SMALL_STATE(25)] = 526,
  [SMALL_STATE(26)] = 558,
  [SMALL_STATE(27)] = 586,
  [SMALL_STATE(28)] = 631,
  [SMALL_STATE(29)] = 676,
  [SMALL_STATE(30)] = 700,
  [SMALL_STATE(31)] = 724,
  [SMALL_STATE(32)] = 748,
  [SMALL_STATE(33)] = 772,
  [SMALL_STATE(34)] = 796,
  [SMALL_STATE(35)] = 820,
  [SMALL_STATE(36)] = 844,
  [SMALL_STATE(37)] = 868,
  [SMALL_STATE(38)] = 892,
  [SMALL_STATE(39)] = 916,
  [SMALL_STATE(40)] = 940,
  [SMALL_STATE(41)] = 964,
  [SMALL_STATE(42)] = 988,
  [SMALL_STATE(43)] = 1012,
  [SMALL_STATE(44)] = 1036,
  [SMALL_STATE(45)] = 1060,
  [SMALL_STATE(46)] = 1084,
  [SMALL_STATE(47)] = 1108,
  [SMALL_STATE(48)] = 1132,
  [SMALL_STATE(49)] = 1156,
  [SMALL_STATE(50)] = 1180,
  [SMALL_STATE(51)] = 1204,
  [SMALL_STATE(52)] = 1234,
  [SMALL_STATE(53)] = 1264,
  [SMALL_STATE(54)] = 1294,
  [SMALL_STATE(55)] = 1324,
  [SMALL_STATE(56)] = 1345,
  [SMALL_STATE(57)] = 1366,
  [SMALL_STATE(58)] = 1388,
  [SMALL_STATE(59)] = 1410,
  [SMALL_STATE(60)] = 1427,
  [SMALL_STATE(61)] = 1446,
  [SMALL_STATE(62)] = 1465,
  [SMALL_STATE(63)] = 1484,
  [SMALL_STATE(64)] = 1503,
  [SMALL_STATE(65)] = 1519,
  [SMALL_STATE(66)] = 1533,
  [SMALL_STATE(67)] = 1549,
  [SMALL_STATE(68)] = 1565,
  [SMALL_STATE(69)] = 1581,
  [SMALL_STATE(70)] = 1597,
  [SMALL_STATE(71)] = 1610,
  [SMALL_STATE(72)] = 1623,
  [SMALL_STATE(73)] = 1636,
  [SMALL_STATE(74)] = 1649,
  [SMALL_STATE(75)] = 1662,
  [SMALL_STATE(76)] = 1675,
  [SMALL_STATE(77)] = 1688,
  [SMALL_STATE(78)] = 1701,
  [SMALL_STATE(79)] = 1714,
  [SMALL_STATE(80)] = 1727,
  [SMALL_STATE(81)] = 1740,
  [SMALL_STATE(82)] = 1753,
  [SMALL_STATE(83)] = 1766,
  [SMALL_STATE(84)] = 1779,
  [SMALL_STATE(85)] = 1792,
  [SMALL_STATE(86)] = 1805,
  [SMALL_STATE(87)] = 1818,
  [SMALL_STATE(88)] = 1831,
  [SMALL_STATE(89)] = 1844,
  [SMALL_STATE(90)] = 1857,
  [SMALL_STATE(91)] = 1870,
  [SMALL_STATE(92)] = 1883,
  [SMALL_STATE(93)] = 1896,
  [SMALL_STATE(94)] = 1909,
  [SMALL_STATE(95)] = 1922,
  [SMALL_STATE(96)] = 1935,
  [SMALL_STATE(97)] = 1948,
  [SMALL_STATE(98)] = 1961,
  [SMALL_STATE(99)] = 1974,
  [SMALL_STATE(100)] = 1978,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT(79),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT(80),
  [7] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0, 0, 0),
  [9] = {.entry = {.count = 1, .reusable = false}}, SHIFT(11),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(90),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(70),
  [17] = {.entry = {.count = 1, .reusable = true}}, SHIFT(85),
  [19] = {.entry = {.count = 1, .reusable = true}}, SHIFT(53),
  [21] = {.entry = {.count = 1, .reusable = false}}, SHIFT(87),
  [23] = {.entry = {.count = 1, .reusable = false}}, SHIFT(27),
  [25] = {.entry = {.count = 1, .reusable = false}}, SHIFT(82),
  [27] = {.entry = {.count = 1, .reusable = false}}, SHIFT(12),
  [29] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [31] = {.entry = {.count = 1, .reusable = true}}, SHIFT(91),
  [33] = {.entry = {.count = 1, .reusable = true}}, SHIFT(92),
  [35] = {.entry = {.count = 1, .reusable = true}}, SHIFT(54),
  [37] = {.entry = {.count = 1, .reusable = false}}, SHIFT(96),
  [39] = {.entry = {.count = 1, .reusable = false}}, SHIFT(28),
  [41] = {.entry = {.count = 1, .reusable = false}}, SHIFT(98),
  [43] = {.entry = {.count = 1, .reusable = true}}, SHIFT(48),
  [45] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [47] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [49] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [51] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(11),
  [54] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(16),
  [57] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(90),
  [60] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(70),
  [63] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(85),
  [66] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(53),
  [69] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(87),
  [72] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(27),
  [75] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(82),
  [78] = {.entry = {.count = 1, .reusable = true}}, SHIFT(41),
  [80] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(12),
  [83] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(17),
  [86] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(91),
  [89] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(92),
  [92] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(54),
  [95] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(96),
  [98] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(28),
  [101] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(98),
  [104] = {.entry = {.count = 1, .reusable = true}}, SHIFT(44),
  [106] = {.entry = {.count = 1, .reusable = false}}, SHIFT(16),
  [108] = {.entry = {.count = 1, .reusable = false}}, SHIFT(17),
  [110] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__expression, 1, 0, 0),
  [112] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__expression, 1, 0, 0),
  [114] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_left_hand_side, 1, 0, 0),
  [116] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_string, 3, 0, 0),
  [118] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_string, 3, 0, 0),
  [120] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__expression, 3, 0, 0),
  [122] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__expression, 3, 0, 0),
  [124] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_binary_expression, 3, 0, 0),
  [126] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_binary_expression, 3, 0, 0),
  [128] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_return_statement, 2, 0, 0),
  [130] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_return_statement, 2, 0, 0),
  [132] = {.entry = {.count = 1, .reusable = false}}, SHIFT(51),
  [134] = {.entry = {.count = 1, .reusable = true}}, SHIFT(51),
  [136] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_right_hand_side, 1, 0, 0),
  [138] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_right_hand_side, 1, 0, 0),
  [140] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__statement, 1, 0, 0),
  [142] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__statement, 1, 0, 0),
  [144] = {.entry = {.count = 1, .reusable = false}}, SHIFT(52),
  [146] = {.entry = {.count = 1, .reusable = true}}, SHIFT(52),
  [148] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_function_body, 3, 0, 0),
  [150] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function_body, 3, 0, 0),
  [152] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__assignment_definition, 3, 0, 0),
  [154] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__assignment_definition, 3, 0, 0),
  [156] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 1, 0, 0),
  [158] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 1, 0, 0),
  [160] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__simple_statement, 1, 0, 0),
  [162] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__simple_statement, 1, 0, 0),
  [164] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_print_statement, 4, 0, 0),
  [166] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_print_statement, 4, 0, 0),
  [168] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function_definition, 5, 0, 0),
  [170] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_function_definition, 5, 0, 0),
  [172] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function_body, 2, 0, 0),
  [174] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_function_body, 2, 0, 0),
  [176] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function_definition, 6, 0, 0),
  [178] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_function_definition, 6, 0, 0),
  [180] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [182] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [184] = {.entry = {.count = 1, .reusable = true}}, SHIFT(78),
  [186] = {.entry = {.count = 1, .reusable = true}}, SHIFT(86),
  [188] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_parameters_repeat1, 2, 0, 0),
  [190] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_parameters_repeat1, 2, 0, 0), SHIFT_REPEAT(73),
  [193] = {.entry = {.count = 1, .reusable = true}}, SHIFT(61),
  [195] = {.entry = {.count = 1, .reusable = true}}, SHIFT(68),
  [197] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_parameters, 1, 0, 0),
  [199] = {.entry = {.count = 1, .reusable = true}}, SHIFT(73),
  [201] = {.entry = {.count = 1, .reusable = true}}, SHIFT(64),
  [203] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_parameters, 2, 0, 0),
  [205] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [207] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [209] = {.entry = {.count = 1, .reusable = false}}, SHIFT(76),
  [211] = {.entry = {.count = 1, .reusable = false}}, SHIFT(79),
  [213] = {.entry = {.count = 1, .reusable = false}}, SHIFT(80),
  [215] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [217] = {.entry = {.count = 1, .reusable = true}}, SHIFT(65),
  [219] = {.entry = {.count = 1, .reusable = true}}, SHIFT(67),
  [221] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_hash_like_function, 4, 0, 0),
  [223] = {.entry = {.count = 1, .reusable = true}}, SHIFT(75),
  [225] = {.entry = {.count = 1, .reusable = true}}, SHIFT(33),
  [227] = {.entry = {.count = 1, .reusable = false}}, SHIFT(100),
  [229] = {.entry = {.count = 1, .reusable = false}}, SHIFT(95),
  [231] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [233] = {.entry = {.count = 1, .reusable = true}}, SHIFT(93),
  [235] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [237] = {.entry = {.count = 1, .reusable = true}}, SHIFT(66),
  [239] = {.entry = {.count = 1, .reusable = true}}, SHIFT(46),
  [241] = {.entry = {.count = 1, .reusable = true}}, SHIFT(57),
  [243] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [245] = {.entry = {.count = 1, .reusable = true}}, SHIFT(69),
  [247] = {.entry = {.count = 1, .reusable = false}}, SHIFT(72),
  [249] = {.entry = {.count = 1, .reusable = false}}, SHIFT(83),
  [251] = {.entry = {.count = 1, .reusable = false}}, SHIFT(84),
  [253] = {.entry = {.count = 1, .reusable = true}}, SHIFT(62),
  [255] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [257] = {.entry = {.count = 1, .reusable = false}}, SHIFT(99),
  [259] = {.entry = {.count = 1, .reusable = true}}, SHIFT(58),
  [261] = {.entry = {.count = 1, .reusable = true}}, SHIFT(60),
  [263] = {.entry = {.count = 1, .reusable = true}}, SHIFT(97),
  [265] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_comment, 3, 0, 0),
  [267] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_comment, 2, 0, 0),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_zoomba(void) {
  static const TSLanguage language = {
    .version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
