#include "parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 14
#define STATE_COUNT 69
#define LARGE_STATE_COUNT 4
#define SYMBOL_COUNT 28
#define ALIAS_COUNT 0
#define TOKEN_COUNT 12
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 6
#define MAX_ALIAS_SEQUENCE_LENGTH 5
#define PRODUCTION_ID_COUNT 11

enum ts_symbol_identifiers {
  sym__token = 1,
  anon_sym_DASH_GT = 2,
  anon_sym_LBRACK = 3,
  anon_sym_COLON = 4,
  anon_sym_RBRACK = 5,
  anon_sym_PIPE = 6,
  sym__strict_token = 7,
  sym_info_comment = 8,
  sym_simple_comment = 9,
  sym__lf = 10,
  sym__ws = 11,
  sym_source_file = 12,
  sym__line = 13,
  sym__statement = 14,
  sym_stmt_plain = 15,
  sym_stmt_translation = 16,
  sym_stmt_complex = 17,
  sym_text = 18,
  sym_strict_text = 19,
  sym__orthogram = 20,
  sym_ortho_gap = 21,
  sym_ortho_choice = 22,
  aux_sym_source_file_repeat1 = 23,
  aux_sym_stmt_complex_repeat1 = 24,
  aux_sym_text_repeat1 = 25,
  aux_sym_strict_text_repeat1 = 26,
  aux_sym_ortho_choice_repeat1 = 27,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [sym__token] = "_token",
  [anon_sym_DASH_GT] = "->",
  [anon_sym_LBRACK] = "[",
  [anon_sym_COLON] = ":",
  [anon_sym_RBRACK] = "]",
  [anon_sym_PIPE] = "|",
  [sym__strict_token] = "_strict_token",
  [sym_info_comment] = "info_comment",
  [sym_simple_comment] = "simple_comment",
  [sym__lf] = "_lf",
  [sym__ws] = "_ws",
  [sym_source_file] = "source_file",
  [sym__line] = "_line",
  [sym__statement] = "_statement",
  [sym_stmt_plain] = "stmt_plain",
  [sym_stmt_translation] = "stmt_translation",
  [sym_stmt_complex] = "stmt_complex",
  [sym_text] = "text",
  [sym_strict_text] = "strict_text",
  [sym__orthogram] = "_orthogram",
  [sym_ortho_gap] = "ortho_gap",
  [sym_ortho_choice] = "ortho_choice",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_stmt_complex_repeat1] = "stmt_complex_repeat1",
  [aux_sym_text_repeat1] = "text_repeat1",
  [aux_sym_strict_text_repeat1] = "strict_text_repeat1",
  [aux_sym_ortho_choice_repeat1] = "ortho_choice_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [sym__token] = sym__token,
  [anon_sym_DASH_GT] = anon_sym_DASH_GT,
  [anon_sym_LBRACK] = anon_sym_LBRACK,
  [anon_sym_COLON] = anon_sym_COLON,
  [anon_sym_RBRACK] = anon_sym_RBRACK,
  [anon_sym_PIPE] = anon_sym_PIPE,
  [sym__strict_token] = sym__strict_token,
  [sym_info_comment] = sym_info_comment,
  [sym_simple_comment] = sym_simple_comment,
  [sym__lf] = sym__lf,
  [sym__ws] = sym__ws,
  [sym_source_file] = sym_source_file,
  [sym__line] = sym__line,
  [sym__statement] = sym__statement,
  [sym_stmt_plain] = sym_stmt_plain,
  [sym_stmt_translation] = sym_stmt_translation,
  [sym_stmt_complex] = sym_stmt_complex,
  [sym_text] = sym_text,
  [sym_strict_text] = sym_strict_text,
  [sym__orthogram] = sym__orthogram,
  [sym_ortho_gap] = sym_ortho_gap,
  [sym_ortho_choice] = sym_ortho_choice,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_stmt_complex_repeat1] = aux_sym_stmt_complex_repeat1,
  [aux_sym_text_repeat1] = aux_sym_text_repeat1,
  [aux_sym_strict_text_repeat1] = aux_sym_strict_text_repeat1,
  [aux_sym_ortho_choice_repeat1] = aux_sym_ortho_choice_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [sym__token] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_DASH_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COLON] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PIPE] = {
    .visible = true,
    .named = false,
  },
  [sym__strict_token] = {
    .visible = false,
    .named = true,
  },
  [sym_info_comment] = {
    .visible = true,
    .named = true,
  },
  [sym_simple_comment] = {
    .visible = true,
    .named = true,
  },
  [sym__lf] = {
    .visible = false,
    .named = true,
  },
  [sym__ws] = {
    .visible = false,
    .named = true,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym__line] = {
    .visible = false,
    .named = true,
  },
  [sym__statement] = {
    .visible = false,
    .named = true,
  },
  [sym_stmt_plain] = {
    .visible = true,
    .named = true,
  },
  [sym_stmt_translation] = {
    .visible = true,
    .named = true,
  },
  [sym_stmt_complex] = {
    .visible = true,
    .named = true,
  },
  [sym_text] = {
    .visible = true,
    .named = true,
  },
  [sym_strict_text] = {
    .visible = true,
    .named = true,
  },
  [sym__orthogram] = {
    .visible = false,
    .named = true,
  },
  [sym_ortho_gap] = {
    .visible = true,
    .named = true,
  },
  [sym_ortho_choice] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_stmt_complex_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_text_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_strict_text_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_ortho_choice_repeat1] = {
    .visible = false,
    .named = false,
  },
};

enum ts_field_identifiers {
  field_answer = 1,
  field_comment = 2,
  field_original = 3,
  field_right_answer = 4,
  field_translation = 5,
  field_wrong_answer = 6,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_answer] = "answer",
  [field_comment] = "comment",
  [field_original] = "original",
  [field_right_answer] = "right_answer",
  [field_translation] = "translation",
  [field_wrong_answer] = "wrong_answer",
};

static const TSFieldMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 1},
  [2] = {.index = 1, .length = 1},
  [3] = {.index = 2, .length = 1},
  [4] = {.index = 3, .length = 1},
  [5] = {.index = 4, .length = 1},
  [6] = {.index = 5, .length = 2},
  [7] = {.index = 7, .length = 2},
  [8] = {.index = 9, .length = 1},
  [9] = {.index = 10, .length = 2},
  [10] = {.index = 12, .length = 2},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_original, 0},
  [1] =
    {field_wrong_answer, 1},
  [2] =
    {field_answer, 1},
  [3] =
    {field_right_answer, 1},
  [4] =
    {field_wrong_answer, 1, .inherited = true},
  [5] =
    {field_wrong_answer, 0, .inherited = true},
    {field_wrong_answer, 1, .inherited = true},
  [7] =
    {field_original, 0},
    {field_translation, 2},
  [9] =
    {field_comment, 2},
  [10] =
    {field_right_answer, 1},
    {field_wrong_answer, 2, .inherited = true},
  [12] =
    {field_answer, 1},
    {field_comment, 3},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 4,
  [7] = 5,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 11,
  [13] = 13,
  [14] = 8,
  [15] = 15,
  [16] = 13,
  [17] = 9,
  [18] = 13,
  [19] = 9,
  [20] = 10,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 15,
  [31] = 31,
  [32] = 9,
  [33] = 13,
  [34] = 23,
  [35] = 35,
  [36] = 36,
  [37] = 22,
  [38] = 24,
  [39] = 26,
  [40] = 21,
  [41] = 27,
  [42] = 28,
  [43] = 9,
  [44] = 13,
  [45] = 35,
  [46] = 36,
  [47] = 47,
  [48] = 48,
  [49] = 49,
  [50] = 50,
  [51] = 51,
  [52] = 52,
  [53] = 50,
  [54] = 54,
  [55] = 54,
  [56] = 56,
  [57] = 47,
  [58] = 49,
  [59] = 59,
  [60] = 60,
  [61] = 61,
  [62] = 62,
  [63] = 63,
  [64] = 64,
  [65] = 65,
  [66] = 64,
  [67] = 67,
  [68] = 67,
};

static TSCharacterRange sym__token_character_set_1[] = {
  {'!', '"'}, {'$', 'Z'}, {'\\', '\\'}, {'^', '~'}, {0xa1, 0xac}, {0xae, 0x5ff}, {0x606, 0x61b}, {0x61d, 0x6dc},
  {0x6de, 0x70e}, {0x710, 0x88f}, {0x892, 0x8e1}, {0x8e3, 0x167f}, {0x1681, 0x180d}, {0x180f, 0x1fff}, {0x2010, 0x2027}, {0x2030, 0x205e},
  {0x2065, 0x2065}, {0x2070, 0x2fff}, {0x3001, 0xd7ff}, {0xe001, 0xf8fe}, {0xf900, 0xfefe}, {0xff00, 0xfff8}, {0xfffc, 0x10ffff},
};

static TSCharacterRange sym__strict_token_character_set_1[] = {
  {'!', '"'}, {'$', '9'}, {';', 'Z'}, {'\\', '\\'}, {'^', '{'}, {'}', '~'}, {0xa1, 0xac}, {0xae, 0x5ff},
  {0x606, 0x61b}, {0x61d, 0x6dc}, {0x6de, 0x70e}, {0x710, 0x88f}, {0x892, 0x8e1}, {0x8e3, 0x167f}, {0x1681, 0x180d}, {0x180f, 0x1fff},
  {0x2010, 0x2027}, {0x2030, 0x205e}, {0x2065, 0x2065}, {0x2070, 0x2fff}, {0x3001, 0xd7ff}, {0xe001, 0xf8fe}, {0xf900, 0xfefe}, {0xff00, 0xfff8},
  {0xfffc, 0x10ffff},
};

static TSCharacterRange sym__ws_character_set_1[] = {
  {'\t', '\t'}, {' ', ' '}, {0xa0, 0xa0}, {0x1680, 0x1680}, {0x2000, 0x200a}, {0x2028, 0x2029}, {0x202f, 0x202f}, {0x205f, 0x205f},
  {0x3000, 0x3000},
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(7);
      ADVANCE_MAP(
        '\n', 23,
        '\r', 24,
        '#', 20,
        '-', 16,
        ':', 12,
        '[', 10,
        ']', 13,
        '|', 15,
      );
      if (set_contains(sym__ws_character_set_1, 9, lookahead)) ADVANCE(25);
      if (set_contains(sym__strict_token_character_set_1, 25, lookahead)) ADVANCE(17);
      END_STATE();
    case 1:
      if (lookahead == '#') ADVANCE(21);
      if (lookahead == '[') ADVANCE(10);
      if (lookahead == ']') ADVANCE(13);
      if (set_contains(sym__ws_character_set_1, 9, lookahead)) ADVANCE(25);
      if (set_contains(sym__token_character_set_1, 23, lookahead)) ADVANCE(17);
      END_STATE();
    case 2:
      if (lookahead == '>') ADVANCE(8);
      END_STATE();
    case 3:
      if (eof) ADVANCE(7);
      if (lookahead == '\n') ADVANCE(23);
      if (lookahead == '\r') ADVANCE(24);
      if (lookahead == '#') ADVANCE(20);
      if (lookahead == '-') ADVANCE(16);
      if (lookahead == '[') ADVANCE(10);
      if (set_contains(sym__ws_character_set_1, 9, lookahead)) ADVANCE(25);
      if (set_contains(sym__token_character_set_1, 23, lookahead)) ADVANCE(17);
      END_STATE();
    case 4:
      if (eof) ADVANCE(7);
      if (lookahead == '\n') ADVANCE(23);
      if (lookahead == '\r') ADVANCE(24);
      if (lookahead == '#') ADVANCE(20);
      if (lookahead == '-') ADVANCE(2);
      if (lookahead == '[') ADVANCE(10);
      if (set_contains(sym__ws_character_set_1, 9, lookahead)) ADVANCE(25);
      END_STATE();
    case 5:
      if (eof) ADVANCE(7);
      if (lookahead == '\n') ADVANCE(23);
      if (lookahead == '\r') ADVANCE(24);
      if (lookahead == '#') ADVANCE(20);
      if (lookahead == '[') ADVANCE(10);
      if (set_contains(sym__ws_character_set_1, 9, lookahead)) ADVANCE(25);
      if (set_contains(sym__token_character_set_1, 23, lookahead)) ADVANCE(17);
      END_STATE();
    case 6:
      if (eof) ADVANCE(7);
      if (lookahead == '\n') ADVANCE(23);
      if (lookahead == '\r') ADVANCE(24);
      if (lookahead == '#') ADVANCE(21);
      if (lookahead == ':') ADVANCE(11);
      if (lookahead == '[') ADVANCE(10);
      if (lookahead == ']') ADVANCE(13);
      if (lookahead == '|') ADVANCE(14);
      if (set_contains(sym__ws_character_set_1, 9, lookahead)) ADVANCE(25);
      if (set_contains(sym__strict_token_character_set_1, 25, lookahead)) ADVANCE(18);
      END_STATE();
    case 7:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 8:
      ACCEPT_TOKEN(anon_sym_DASH_GT);
      END_STATE();
    case 9:
      ACCEPT_TOKEN(anon_sym_DASH_GT);
      if (set_contains(sym__token_character_set_1, 23, lookahead)) ADVANCE(17);
      END_STATE();
    case 10:
      ACCEPT_TOKEN(anon_sym_LBRACK);
      END_STATE();
    case 11:
      ACCEPT_TOKEN(anon_sym_COLON);
      END_STATE();
    case 12:
      ACCEPT_TOKEN(anon_sym_COLON);
      if (set_contains(sym__token_character_set_1, 23, lookahead)) ADVANCE(17);
      END_STATE();
    case 13:
      ACCEPT_TOKEN(anon_sym_RBRACK);
      END_STATE();
    case 14:
      ACCEPT_TOKEN(anon_sym_PIPE);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(anon_sym_PIPE);
      if (set_contains(sym__token_character_set_1, 23, lookahead)) ADVANCE(17);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(sym__token);
      if (lookahead == '>') ADVANCE(9);
      if (set_contains(sym__token_character_set_1, 23, lookahead)) ADVANCE(17);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(sym__token);
      if (set_contains(sym__token_character_set_1, 23, lookahead)) ADVANCE(17);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(sym__strict_token);
      if (set_contains(sym__strict_token_character_set_1, 25, lookahead)) ADVANCE(18);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(sym_info_comment);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(19);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(sym_simple_comment);
      if (lookahead == '!') ADVANCE(19);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(22);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(sym_simple_comment);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != '!') ADVANCE(22);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(sym_simple_comment);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(22);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(sym__lf);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(sym__lf);
      if (lookahead == '\n') ADVANCE(23);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(sym__ws);
      if (set_contains(sym__ws_character_set_1, 9, lookahead)) ADVANCE(25);
      END_STATE();
    default:
      return false;
  }
}

static bool ts_lex_keywords(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 5},
  [2] = {.lex_state = 5},
  [3] = {.lex_state = 5},
  [4] = {.lex_state = 5},
  [5] = {.lex_state = 5},
  [6] = {.lex_state = 5},
  [7] = {.lex_state = 5},
  [8] = {.lex_state = 4},
  [9] = {.lex_state = 3},
  [10] = {.lex_state = 0},
  [11] = {.lex_state = 6},
  [12] = {.lex_state = 6},
  [13] = {.lex_state = 3},
  [14] = {.lex_state = 4},
  [15] = {.lex_state = 5},
  [16] = {.lex_state = 5},
  [17] = {.lex_state = 3},
  [18] = {.lex_state = 3},
  [19] = {.lex_state = 5},
  [20] = {.lex_state = 0},
  [21] = {.lex_state = 5},
  [22] = {.lex_state = 5},
  [23] = {.lex_state = 5},
  [24] = {.lex_state = 5},
  [25] = {.lex_state = 6},
  [26] = {.lex_state = 5},
  [27] = {.lex_state = 5},
  [28] = {.lex_state = 5},
  [29] = {.lex_state = 6},
  [30] = {.lex_state = 5},
  [31] = {.lex_state = 5},
  [32] = {.lex_state = 5},
  [33] = {.lex_state = 5},
  [34] = {.lex_state = 5},
  [35] = {.lex_state = 6},
  [36] = {.lex_state = 6},
  [37] = {.lex_state = 5},
  [38] = {.lex_state = 5},
  [39] = {.lex_state = 5},
  [40] = {.lex_state = 5},
  [41] = {.lex_state = 5},
  [42] = {.lex_state = 5},
  [43] = {.lex_state = 1},
  [44] = {.lex_state = 1},
  [45] = {.lex_state = 6},
  [46] = {.lex_state = 6},
  [47] = {.lex_state = 1},
  [48] = {.lex_state = 6},
  [49] = {.lex_state = 1},
  [50] = {.lex_state = 6},
  [51] = {.lex_state = 0},
  [52] = {.lex_state = 6},
  [53] = {.lex_state = 6},
  [54] = {.lex_state = 6},
  [55] = {.lex_state = 6},
  [56] = {.lex_state = 0},
  [57] = {.lex_state = 1},
  [58] = {.lex_state = 1},
  [59] = {.lex_state = 6},
  [60] = {.lex_state = 6},
  [61] = {.lex_state = 6},
  [62] = {.lex_state = 6},
  [63] = {.lex_state = 6},
  [64] = {.lex_state = 6},
  [65] = {.lex_state = 6},
  [66] = {.lex_state = 6},
  [67] = {.lex_state = 6},
  [68] = {.lex_state = 6},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [0] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [sym__token] = ACTIONS(1),
    [anon_sym_DASH_GT] = ACTIONS(1),
    [anon_sym_LBRACK] = ACTIONS(1),
    [anon_sym_COLON] = ACTIONS(1),
    [anon_sym_RBRACK] = ACTIONS(1),
    [anon_sym_PIPE] = ACTIONS(1),
    [sym_info_comment] = ACTIONS(1),
    [sym_simple_comment] = ACTIONS(3),
    [sym__lf] = ACTIONS(1),
    [sym__ws] = ACTIONS(5),
  },
  [1] = {
    [sym_source_file] = STATE(63),
    [sym__line] = STATE(61),
    [sym__statement] = STATE(56),
    [sym_stmt_plain] = STATE(56),
    [sym_stmt_translation] = STATE(56),
    [sym_stmt_complex] = STATE(56),
    [sym_text] = STATE(8),
    [sym__orthogram] = STATE(4),
    [sym_ortho_gap] = STATE(4),
    [sym_ortho_choice] = STATE(4),
    [aux_sym_source_file_repeat1] = STATE(3),
    [aux_sym_stmt_complex_repeat1] = STATE(4),
    [aux_sym_text_repeat1] = STATE(9),
    [ts_builtin_sym_end] = ACTIONS(7),
    [sym__token] = ACTIONS(9),
    [anon_sym_LBRACK] = ACTIONS(11),
    [sym_info_comment] = ACTIONS(13),
    [sym_simple_comment] = ACTIONS(3),
    [sym__lf] = ACTIONS(15),
    [sym__ws] = ACTIONS(5),
  },
  [2] = {
    [sym__line] = STATE(65),
    [sym__statement] = STATE(56),
    [sym_stmt_plain] = STATE(56),
    [sym_stmt_translation] = STATE(56),
    [sym_stmt_complex] = STATE(56),
    [sym_text] = STATE(14),
    [sym__orthogram] = STATE(6),
    [sym_ortho_gap] = STATE(6),
    [sym_ortho_choice] = STATE(6),
    [aux_sym_source_file_repeat1] = STATE(2),
    [aux_sym_stmt_complex_repeat1] = STATE(6),
    [aux_sym_text_repeat1] = STATE(17),
    [ts_builtin_sym_end] = ACTIONS(17),
    [sym__token] = ACTIONS(19),
    [anon_sym_LBRACK] = ACTIONS(22),
    [sym_info_comment] = ACTIONS(25),
    [sym_simple_comment] = ACTIONS(3),
    [sym__lf] = ACTIONS(28),
    [sym__ws] = ACTIONS(5),
  },
  [3] = {
    [sym__line] = STATE(62),
    [sym__statement] = STATE(56),
    [sym_stmt_plain] = STATE(56),
    [sym_stmt_translation] = STATE(56),
    [sym_stmt_complex] = STATE(56),
    [sym_text] = STATE(8),
    [sym__orthogram] = STATE(4),
    [sym_ortho_gap] = STATE(4),
    [sym_ortho_choice] = STATE(4),
    [aux_sym_source_file_repeat1] = STATE(2),
    [aux_sym_stmt_complex_repeat1] = STATE(4),
    [aux_sym_text_repeat1] = STATE(9),
    [ts_builtin_sym_end] = ACTIONS(31),
    [sym__token] = ACTIONS(9),
    [anon_sym_LBRACK] = ACTIONS(11),
    [sym_info_comment] = ACTIONS(33),
    [sym_simple_comment] = ACTIONS(3),
    [sym__lf] = ACTIONS(35),
    [sym__ws] = ACTIONS(5),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 8,
    ACTIONS(3), 1,
      sym_simple_comment,
    ACTIONS(5), 1,
      sym__ws,
    ACTIONS(11), 1,
      anon_sym_LBRACK,
    ACTIONS(39), 1,
      sym__token,
    STATE(10), 1,
      sym_text,
    STATE(19), 1,
      aux_sym_text_repeat1,
    ACTIONS(37), 3,
      ts_builtin_sym_end,
      sym_info_comment,
      sym__lf,
    STATE(5), 4,
      sym__orthogram,
      sym_ortho_gap,
      sym_ortho_choice,
      aux_sym_stmt_complex_repeat1,
  [30] = 8,
    ACTIONS(3), 1,
      sym_simple_comment,
    ACTIONS(5), 1,
      sym__ws,
    ACTIONS(43), 1,
      sym__token,
    ACTIONS(46), 1,
      anon_sym_LBRACK,
    STATE(43), 1,
      aux_sym_text_repeat1,
    STATE(45), 1,
      sym_text,
    ACTIONS(41), 3,
      ts_builtin_sym_end,
      sym_info_comment,
      sym__lf,
    STATE(5), 4,
      sym__orthogram,
      sym_ortho_gap,
      sym_ortho_choice,
      aux_sym_stmt_complex_repeat1,
  [60] = 8,
    ACTIONS(3), 1,
      sym_simple_comment,
    ACTIONS(5), 1,
      sym__ws,
    ACTIONS(49), 1,
      sym__token,
    ACTIONS(51), 1,
      anon_sym_LBRACK,
    STATE(20), 1,
      sym_text,
    STATE(32), 1,
      aux_sym_text_repeat1,
    ACTIONS(37), 2,
      sym_info_comment,
      sym__lf,
    STATE(7), 4,
      sym__orthogram,
      sym_ortho_gap,
      sym_ortho_choice,
      aux_sym_stmt_complex_repeat1,
  [89] = 8,
    ACTIONS(3), 1,
      sym_simple_comment,
    ACTIONS(5), 1,
      sym__ws,
    ACTIONS(43), 1,
      sym__token,
    ACTIONS(53), 1,
      anon_sym_LBRACK,
    STATE(35), 1,
      sym_text,
    STATE(43), 1,
      aux_sym_text_repeat1,
    ACTIONS(41), 2,
      sym_info_comment,
      sym__lf,
    STATE(7), 4,
      sym__orthogram,
      sym_ortho_gap,
      sym_ortho_choice,
      aux_sym_stmt_complex_repeat1,
  [118] = 6,
    ACTIONS(3), 1,
      sym_simple_comment,
    ACTIONS(5), 1,
      sym__ws,
    ACTIONS(11), 1,
      anon_sym_LBRACK,
    ACTIONS(58), 1,
      anon_sym_DASH_GT,
    ACTIONS(56), 3,
      ts_builtin_sym_end,
      sym_info_comment,
      sym__lf,
    STATE(22), 3,
      sym__orthogram,
      sym_ortho_gap,
      sym_ortho_choice,
  [141] = 6,
    ACTIONS(3), 1,
      sym_simple_comment,
    ACTIONS(5), 1,
      sym__ws,
    ACTIONS(62), 1,
      sym__token,
    ACTIONS(64), 1,
      anon_sym_DASH_GT,
    STATE(13), 1,
      aux_sym_text_repeat1,
    ACTIONS(60), 4,
      ts_builtin_sym_end,
      anon_sym_LBRACK,
      sym_info_comment,
      sym__lf,
  [163] = 5,
    ACTIONS(3), 1,
      sym_simple_comment,
    ACTIONS(5), 1,
      sym__ws,
    ACTIONS(11), 1,
      anon_sym_LBRACK,
    ACTIONS(66), 3,
      ts_builtin_sym_end,
      sym_info_comment,
      sym__lf,
    STATE(22), 3,
      sym__orthogram,
      sym_ortho_gap,
      sym_ortho_choice,
  [183] = 8,
    ACTIONS(68), 1,
      anon_sym_COLON,
    ACTIONS(70), 1,
      anon_sym_RBRACK,
    ACTIONS(72), 1,
      anon_sym_PIPE,
    ACTIONS(74), 1,
      sym__strict_token,
    STATE(29), 1,
      aux_sym_strict_text_repeat1,
    STATE(36), 1,
      sym_strict_text,
    STATE(50), 1,
      aux_sym_ortho_choice_repeat1,
    ACTIONS(5), 2,
      sym_simple_comment,
      sym__ws,
  [209] = 8,
    ACTIONS(72), 1,
      anon_sym_PIPE,
    ACTIONS(74), 1,
      sym__strict_token,
    ACTIONS(76), 1,
      anon_sym_COLON,
    ACTIONS(78), 1,
      anon_sym_RBRACK,
    STATE(29), 1,
      aux_sym_strict_text_repeat1,
    STATE(46), 1,
      sym_strict_text,
    STATE(53), 1,
      aux_sym_ortho_choice_repeat1,
    ACTIONS(5), 2,
      sym_simple_comment,
      sym__ws,
  [235] = 6,
    ACTIONS(3), 1,
      sym_simple_comment,
    ACTIONS(5), 1,
      sym__ws,
    ACTIONS(82), 1,
      sym__token,
    ACTIONS(85), 1,
      anon_sym_DASH_GT,
    STATE(13), 1,
      aux_sym_text_repeat1,
    ACTIONS(80), 4,
      ts_builtin_sym_end,
      anon_sym_LBRACK,
      sym_info_comment,
      sym__lf,
  [257] = 6,
    ACTIONS(3), 1,
      sym_simple_comment,
    ACTIONS(5), 1,
      sym__ws,
    ACTIONS(51), 1,
      anon_sym_LBRACK,
    ACTIONS(87), 1,
      anon_sym_DASH_GT,
    ACTIONS(56), 2,
      sym_info_comment,
      sym__lf,
    STATE(37), 3,
      sym__orthogram,
      sym_ortho_gap,
      sym_ortho_choice,
  [279] = 6,
    ACTIONS(3), 1,
      sym_simple_comment,
    ACTIONS(5), 1,
      sym__ws,
    ACTIONS(39), 1,
      sym__token,
    STATE(19), 1,
      aux_sym_text_repeat1,
    STATE(51), 1,
      sym_text,
    ACTIONS(89), 3,
      ts_builtin_sym_end,
      sym_info_comment,
      sym__lf,
  [300] = 5,
    ACTIONS(3), 1,
      sym_simple_comment,
    ACTIONS(5), 1,
      sym__ws,
    ACTIONS(91), 1,
      sym__token,
    STATE(16), 1,
      aux_sym_text_repeat1,
    ACTIONS(80), 4,
      ts_builtin_sym_end,
      anon_sym_LBRACK,
      sym_info_comment,
      sym__lf,
  [319] = 6,
    ACTIONS(3), 1,
      sym_simple_comment,
    ACTIONS(5), 1,
      sym__ws,
    ACTIONS(64), 1,
      anon_sym_DASH_GT,
    ACTIONS(94), 1,
      sym__token,
    STATE(18), 1,
      aux_sym_text_repeat1,
    ACTIONS(60), 3,
      anon_sym_LBRACK,
      sym_info_comment,
      sym__lf,
  [340] = 6,
    ACTIONS(3), 1,
      sym_simple_comment,
    ACTIONS(5), 1,
      sym__ws,
    ACTIONS(85), 1,
      anon_sym_DASH_GT,
    ACTIONS(96), 1,
      sym__token,
    STATE(18), 1,
      aux_sym_text_repeat1,
    ACTIONS(80), 3,
      anon_sym_LBRACK,
      sym_info_comment,
      sym__lf,
  [361] = 5,
    ACTIONS(3), 1,
      sym_simple_comment,
    ACTIONS(5), 1,
      sym__ws,
    ACTIONS(99), 1,
      sym__token,
    STATE(16), 1,
      aux_sym_text_repeat1,
    ACTIONS(60), 4,
      ts_builtin_sym_end,
      anon_sym_LBRACK,
      sym_info_comment,
      sym__lf,
  [380] = 5,
    ACTIONS(3), 1,
      sym_simple_comment,
    ACTIONS(5), 1,
      sym__ws,
    ACTIONS(51), 1,
      anon_sym_LBRACK,
    ACTIONS(66), 2,
      sym_info_comment,
      sym__lf,
    STATE(37), 3,
      sym__orthogram,
      sym_ortho_gap,
      sym_ortho_choice,
  [399] = 3,
    ACTIONS(3), 1,
      sym_simple_comment,
    ACTIONS(5), 1,
      sym__ws,
    ACTIONS(101), 5,
      ts_builtin_sym_end,
      anon_sym_LBRACK,
      sym__token,
      sym_info_comment,
      sym__lf,
  [413] = 3,
    ACTIONS(3), 1,
      sym_simple_comment,
    ACTIONS(5), 1,
      sym__ws,
    ACTIONS(41), 5,
      ts_builtin_sym_end,
      anon_sym_LBRACK,
      sym__token,
      sym_info_comment,
      sym__lf,
  [427] = 3,
    ACTIONS(3), 1,
      sym_simple_comment,
    ACTIONS(5), 1,
      sym__ws,
    ACTIONS(103), 5,
      ts_builtin_sym_end,
      anon_sym_LBRACK,
      sym__token,
      sym_info_comment,
      sym__lf,
  [441] = 3,
    ACTIONS(3), 1,
      sym_simple_comment,
    ACTIONS(5), 1,
      sym__ws,
    ACTIONS(106), 5,
      ts_builtin_sym_end,
      anon_sym_LBRACK,
      sym__token,
      sym_info_comment,
      sym__lf,
  [455] = 4,
    ACTIONS(111), 1,
      sym__strict_token,
    STATE(25), 1,
      aux_sym_strict_text_repeat1,
    ACTIONS(5), 2,
      sym_simple_comment,
      sym__ws,
    ACTIONS(109), 3,
      anon_sym_COLON,
      anon_sym_RBRACK,
      anon_sym_PIPE,
  [471] = 3,
    ACTIONS(3), 1,
      sym_simple_comment,
    ACTIONS(5), 1,
      sym__ws,
    ACTIONS(114), 5,
      ts_builtin_sym_end,
      anon_sym_LBRACK,
      sym__token,
      sym_info_comment,
      sym__lf,
  [485] = 3,
    ACTIONS(3), 1,
      sym_simple_comment,
    ACTIONS(5), 1,
      sym__ws,
    ACTIONS(116), 5,
      ts_builtin_sym_end,
      anon_sym_LBRACK,
      sym__token,
      sym_info_comment,
      sym__lf,
  [499] = 3,
    ACTIONS(3), 1,
      sym_simple_comment,
    ACTIONS(5), 1,
      sym__ws,
    ACTIONS(118), 5,
      ts_builtin_sym_end,
      anon_sym_LBRACK,
      sym__token,
      sym_info_comment,
      sym__lf,
  [513] = 4,
    ACTIONS(122), 1,
      sym__strict_token,
    STATE(25), 1,
      aux_sym_strict_text_repeat1,
    ACTIONS(5), 2,
      sym_simple_comment,
      sym__ws,
    ACTIONS(120), 3,
      anon_sym_COLON,
      anon_sym_RBRACK,
      anon_sym_PIPE,
  [529] = 6,
    ACTIONS(3), 1,
      sym_simple_comment,
    ACTIONS(5), 1,
      sym__ws,
    ACTIONS(49), 1,
      sym__token,
    STATE(32), 1,
      aux_sym_text_repeat1,
    STATE(51), 1,
      sym_text,
    ACTIONS(89), 2,
      sym_info_comment,
      sym__lf,
  [549] = 3,
    ACTIONS(3), 1,
      sym_simple_comment,
    ACTIONS(5), 1,
      sym__ws,
    ACTIONS(17), 5,
      ts_builtin_sym_end,
      anon_sym_LBRACK,
      sym__token,
      sym_info_comment,
      sym__lf,
  [563] = 5,
    ACTIONS(3), 1,
      sym_simple_comment,
    ACTIONS(5), 1,
      sym__ws,
    ACTIONS(124), 1,
      sym__token,
    STATE(33), 1,
      aux_sym_text_repeat1,
    ACTIONS(60), 3,
      anon_sym_LBRACK,
      sym_info_comment,
      sym__lf,
  [581] = 5,
    ACTIONS(3), 1,
      sym_simple_comment,
    ACTIONS(5), 1,
      sym__ws,
    ACTIONS(126), 1,
      sym__token,
    STATE(33), 1,
      aux_sym_text_repeat1,
    ACTIONS(80), 3,
      anon_sym_LBRACK,
      sym_info_comment,
      sym__lf,
  [599] = 3,
    ACTIONS(3), 1,
      sym_simple_comment,
    ACTIONS(5), 1,
      sym__ws,
    ACTIONS(103), 4,
      anon_sym_LBRACK,
      sym__token,
      sym_info_comment,
      sym__lf,
  [612] = 3,
    ACTIONS(51), 1,
      anon_sym_LBRACK,
    ACTIONS(5), 2,
      sym_simple_comment,
      sym__ws,
    STATE(37), 3,
      sym__orthogram,
      sym_ortho_gap,
      sym_ortho_choice,
  [625] = 5,
    ACTIONS(72), 1,
      anon_sym_PIPE,
    ACTIONS(129), 1,
      anon_sym_COLON,
    ACTIONS(131), 1,
      anon_sym_RBRACK,
    STATE(54), 1,
      aux_sym_ortho_choice_repeat1,
    ACTIONS(5), 2,
      sym_simple_comment,
      sym__ws,
  [642] = 3,
    ACTIONS(3), 1,
      sym_simple_comment,
    ACTIONS(5), 1,
      sym__ws,
    ACTIONS(41), 4,
      anon_sym_LBRACK,
      sym__token,
      sym_info_comment,
      sym__lf,
  [655] = 3,
    ACTIONS(3), 1,
      sym_simple_comment,
    ACTIONS(5), 1,
      sym__ws,
    ACTIONS(106), 4,
      anon_sym_LBRACK,
      sym__token,
      sym_info_comment,
      sym__lf,
  [668] = 3,
    ACTIONS(3), 1,
      sym_simple_comment,
    ACTIONS(5), 1,
      sym__ws,
    ACTIONS(114), 4,
      anon_sym_LBRACK,
      sym__token,
      sym_info_comment,
      sym__lf,
  [681] = 3,
    ACTIONS(3), 1,
      sym_simple_comment,
    ACTIONS(5), 1,
      sym__ws,
    ACTIONS(101), 4,
      anon_sym_LBRACK,
      sym__token,
      sym_info_comment,
      sym__lf,
  [694] = 3,
    ACTIONS(3), 1,
      sym_simple_comment,
    ACTIONS(5), 1,
      sym__ws,
    ACTIONS(116), 4,
      anon_sym_LBRACK,
      sym__token,
      sym_info_comment,
      sym__lf,
  [707] = 3,
    ACTIONS(3), 1,
      sym_simple_comment,
    ACTIONS(5), 1,
      sym__ws,
    ACTIONS(118), 4,
      anon_sym_LBRACK,
      sym__token,
      sym_info_comment,
      sym__lf,
  [720] = 4,
    ACTIONS(133), 1,
      sym__token,
    STATE(44), 1,
      aux_sym_text_repeat1,
    ACTIONS(5), 2,
      sym_simple_comment,
      sym__ws,
    ACTIONS(60), 2,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
  [735] = 4,
    ACTIONS(135), 1,
      sym__token,
    STATE(44), 1,
      aux_sym_text_repeat1,
    ACTIONS(5), 2,
      sym_simple_comment,
      sym__ws,
    ACTIONS(80), 2,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
  [750] = 3,
    ACTIONS(11), 1,
      anon_sym_LBRACK,
    ACTIONS(5), 2,
      sym_simple_comment,
      sym__ws,
    STATE(22), 3,
      sym__orthogram,
      sym_ortho_gap,
      sym_ortho_choice,
  [763] = 5,
    ACTIONS(72), 1,
      anon_sym_PIPE,
    ACTIONS(138), 1,
      anon_sym_COLON,
    ACTIONS(140), 1,
      anon_sym_RBRACK,
    STATE(55), 1,
      aux_sym_ortho_choice_repeat1,
    ACTIONS(5), 2,
      sym_simple_comment,
      sym__ws,
  [780] = 4,
    ACTIONS(142), 1,
      sym__token,
    STATE(43), 1,
      aux_sym_text_repeat1,
    STATE(64), 1,
      sym_text,
    ACTIONS(5), 2,
      sym_simple_comment,
      sym__ws,
  [794] = 4,
    ACTIONS(74), 1,
      sym__strict_token,
    STATE(29), 1,
      aux_sym_strict_text_repeat1,
    STATE(59), 1,
      sym_strict_text,
    ACTIONS(5), 2,
      sym_simple_comment,
      sym__ws,
  [808] = 4,
    ACTIONS(142), 1,
      sym__token,
    STATE(43), 1,
      aux_sym_text_repeat1,
    STATE(67), 1,
      sym_text,
    ACTIONS(5), 2,
      sym_simple_comment,
      sym__ws,
  [822] = 4,
    ACTIONS(72), 1,
      anon_sym_PIPE,
    ACTIONS(144), 1,
      anon_sym_RBRACK,
    STATE(52), 1,
      aux_sym_ortho_choice_repeat1,
    ACTIONS(5), 2,
      sym_simple_comment,
      sym__ws,
  [836] = 3,
    ACTIONS(3), 1,
      sym_simple_comment,
    ACTIONS(5), 1,
      sym__ws,
    ACTIONS(146), 3,
      ts_builtin_sym_end,
      sym_info_comment,
      sym__lf,
  [848] = 4,
    ACTIONS(148), 1,
      anon_sym_RBRACK,
    ACTIONS(150), 1,
      anon_sym_PIPE,
    STATE(52), 1,
      aux_sym_ortho_choice_repeat1,
    ACTIONS(5), 2,
      sym_simple_comment,
      sym__ws,
  [862] = 4,
    ACTIONS(72), 1,
      anon_sym_PIPE,
    ACTIONS(153), 1,
      anon_sym_RBRACK,
    STATE(52), 1,
      aux_sym_ortho_choice_repeat1,
    ACTIONS(5), 2,
      sym_simple_comment,
      sym__ws,
  [876] = 4,
    ACTIONS(72), 1,
      anon_sym_PIPE,
    ACTIONS(155), 1,
      anon_sym_RBRACK,
    STATE(52), 1,
      aux_sym_ortho_choice_repeat1,
    ACTIONS(5), 2,
      sym_simple_comment,
      sym__ws,
  [890] = 4,
    ACTIONS(72), 1,
      anon_sym_PIPE,
    ACTIONS(157), 1,
      anon_sym_RBRACK,
    STATE(52), 1,
      aux_sym_ortho_choice_repeat1,
    ACTIONS(5), 2,
      sym_simple_comment,
      sym__ws,
  [904] = 4,
    ACTIONS(3), 1,
      sym_simple_comment,
    ACTIONS(5), 1,
      sym__ws,
    ACTIONS(161), 1,
      sym_info_comment,
    ACTIONS(159), 2,
      ts_builtin_sym_end,
      sym__lf,
  [918] = 4,
    ACTIONS(142), 1,
      sym__token,
    STATE(43), 1,
      aux_sym_text_repeat1,
    STATE(66), 1,
      sym_text,
    ACTIONS(5), 2,
      sym_simple_comment,
      sym__ws,
  [932] = 4,
    ACTIONS(142), 1,
      sym__token,
    STATE(43), 1,
      aux_sym_text_repeat1,
    STATE(68), 1,
      sym_text,
    ACTIONS(5), 2,
      sym_simple_comment,
      sym__ws,
  [946] = 2,
    ACTIONS(5), 2,
      sym_simple_comment,
      sym__ws,
    ACTIONS(163), 2,
      anon_sym_RBRACK,
      anon_sym_PIPE,
  [955] = 2,
    ACTIONS(5), 2,
      sym_simple_comment,
      sym__ws,
    ACTIONS(165), 2,
      ts_builtin_sym_end,
      sym__lf,
  [964] = 3,
    ACTIONS(31), 1,
      ts_builtin_sym_end,
    ACTIONS(167), 1,
      sym__lf,
    ACTIONS(5), 2,
      sym_simple_comment,
      sym__ws,
  [975] = 3,
    ACTIONS(167), 1,
      sym__lf,
    ACTIONS(169), 1,
      ts_builtin_sym_end,
    ACTIONS(5), 2,
      sym_simple_comment,
      sym__ws,
  [986] = 2,
    ACTIONS(171), 1,
      ts_builtin_sym_end,
    ACTIONS(5), 2,
      sym_simple_comment,
      sym__ws,
  [994] = 2,
    ACTIONS(173), 1,
      anon_sym_RBRACK,
    ACTIONS(5), 2,
      sym_simple_comment,
      sym__ws,
  [1002] = 2,
    ACTIONS(167), 1,
      sym__lf,
    ACTIONS(5), 2,
      sym_simple_comment,
      sym__ws,
  [1010] = 2,
    ACTIONS(175), 1,
      anon_sym_RBRACK,
    ACTIONS(5), 2,
      sym_simple_comment,
      sym__ws,
  [1018] = 2,
    ACTIONS(177), 1,
      anon_sym_RBRACK,
    ACTIONS(5), 2,
      sym_simple_comment,
      sym__ws,
  [1026] = 2,
    ACTIONS(179), 1,
      anon_sym_RBRACK,
    ACTIONS(5), 2,
      sym_simple_comment,
      sym__ws,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(4)] = 0,
  [SMALL_STATE(5)] = 30,
  [SMALL_STATE(6)] = 60,
  [SMALL_STATE(7)] = 89,
  [SMALL_STATE(8)] = 118,
  [SMALL_STATE(9)] = 141,
  [SMALL_STATE(10)] = 163,
  [SMALL_STATE(11)] = 183,
  [SMALL_STATE(12)] = 209,
  [SMALL_STATE(13)] = 235,
  [SMALL_STATE(14)] = 257,
  [SMALL_STATE(15)] = 279,
  [SMALL_STATE(16)] = 300,
  [SMALL_STATE(17)] = 319,
  [SMALL_STATE(18)] = 340,
  [SMALL_STATE(19)] = 361,
  [SMALL_STATE(20)] = 380,
  [SMALL_STATE(21)] = 399,
  [SMALL_STATE(22)] = 413,
  [SMALL_STATE(23)] = 427,
  [SMALL_STATE(24)] = 441,
  [SMALL_STATE(25)] = 455,
  [SMALL_STATE(26)] = 471,
  [SMALL_STATE(27)] = 485,
  [SMALL_STATE(28)] = 499,
  [SMALL_STATE(29)] = 513,
  [SMALL_STATE(30)] = 529,
  [SMALL_STATE(31)] = 549,
  [SMALL_STATE(32)] = 563,
  [SMALL_STATE(33)] = 581,
  [SMALL_STATE(34)] = 599,
  [SMALL_STATE(35)] = 612,
  [SMALL_STATE(36)] = 625,
  [SMALL_STATE(37)] = 642,
  [SMALL_STATE(38)] = 655,
  [SMALL_STATE(39)] = 668,
  [SMALL_STATE(40)] = 681,
  [SMALL_STATE(41)] = 694,
  [SMALL_STATE(42)] = 707,
  [SMALL_STATE(43)] = 720,
  [SMALL_STATE(44)] = 735,
  [SMALL_STATE(45)] = 750,
  [SMALL_STATE(46)] = 763,
  [SMALL_STATE(47)] = 780,
  [SMALL_STATE(48)] = 794,
  [SMALL_STATE(49)] = 808,
  [SMALL_STATE(50)] = 822,
  [SMALL_STATE(51)] = 836,
  [SMALL_STATE(52)] = 848,
  [SMALL_STATE(53)] = 862,
  [SMALL_STATE(54)] = 876,
  [SMALL_STATE(55)] = 890,
  [SMALL_STATE(56)] = 904,
  [SMALL_STATE(57)] = 918,
  [SMALL_STATE(58)] = 932,
  [SMALL_STATE(59)] = 946,
  [SMALL_STATE(60)] = 955,
  [SMALL_STATE(61)] = 964,
  [SMALL_STATE(62)] = 975,
  [SMALL_STATE(63)] = 986,
  [SMALL_STATE(64)] = 994,
  [SMALL_STATE(65)] = 1002,
  [SMALL_STATE(66)] = 1010,
  [SMALL_STATE(67)] = 1018,
  [SMALL_STATE(68)] = 1026,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = false}}, SHIFT_EXTRA(),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT_EXTRA(),
  [7] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0, 0, 0),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(61),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [17] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [19] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(17),
  [22] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(12),
  [25] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(65),
  [28] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(2),
  [31] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [33] = {.entry = {.count = 1, .reusable = true}}, SHIFT(62),
  [35] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [37] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_stmt_complex, 1, 0, 0),
  [39] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [41] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_stmt_complex_repeat1, 2, 0, 0),
  [43] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_stmt_complex_repeat1, 2, 0, 0), SHIFT_REPEAT(43),
  [46] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_stmt_complex_repeat1, 2, 0, 0), SHIFT_REPEAT(11),
  [49] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
  [51] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [53] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_stmt_complex_repeat1, 2, 0, 0), SHIFT_REPEAT(12),
  [56] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_stmt_plain, 1, 0, 0),
  [58] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [60] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_text, 1, 0, 0),
  [62] = {.entry = {.count = 1, .reusable = false}}, SHIFT(13),
  [64] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_text, 1, 0, 0),
  [66] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_stmt_complex, 2, 0, 0),
  [68] = {.entry = {.count = 1, .reusable = true}}, SHIFT(47),
  [70] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [72] = {.entry = {.count = 1, .reusable = true}}, SHIFT(48),
  [74] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [76] = {.entry = {.count = 1, .reusable = true}}, SHIFT(57),
  [78] = {.entry = {.count = 1, .reusable = true}}, SHIFT(34),
  [80] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_text_repeat1, 2, 0, 0),
  [82] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_text_repeat1, 2, 0, 0), SHIFT_REPEAT(13),
  [85] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_text_repeat1, 2, 0, 0),
  [87] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [89] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_stmt_translation, 2, 0, 1),
  [91] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_text_repeat1, 2, 0, 0), SHIFT_REPEAT(16),
  [94] = {.entry = {.count = 1, .reusable = false}}, SHIFT(18),
  [96] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_text_repeat1, 2, 0, 0), SHIFT_REPEAT(18),
  [99] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [101] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_ortho_gap, 4, 0, 8),
  [103] = {.entry = {.count = 2, .reusable = true}}, REDUCE(sym_ortho_gap, 2, 0, 0), REDUCE(sym_ortho_choice, 2, 0, 0),
  [106] = {.entry = {.count = 2, .reusable = true}}, REDUCE(sym_ortho_gap, 3, 0, 3), REDUCE(sym_ortho_choice, 3, 0, 4),
  [109] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_strict_text_repeat1, 2, 0, 0),
  [111] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_strict_text_repeat1, 2, 0, 0), SHIFT_REPEAT(25),
  [114] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_ortho_choice, 3, 0, 5),
  [116] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_ortho_choice, 4, 0, 9),
  [118] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_ortho_gap, 5, 0, 10),
  [120] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_strict_text, 1, 0, 0),
  [122] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [124] = {.entry = {.count = 1, .reusable = true}}, SHIFT(33),
  [126] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_text_repeat1, 2, 0, 0), SHIFT_REPEAT(33),
  [129] = {.entry = {.count = 1, .reusable = true}}, SHIFT(49),
  [131] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [133] = {.entry = {.count = 1, .reusable = true}}, SHIFT(44),
  [135] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_text_repeat1, 2, 0, 0), SHIFT_REPEAT(44),
  [138] = {.entry = {.count = 1, .reusable = true}}, SHIFT(58),
  [140] = {.entry = {.count = 1, .reusable = true}}, SHIFT(38),
  [142] = {.entry = {.count = 1, .reusable = true}}, SHIFT(43),
  [144] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [146] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_stmt_translation, 3, 0, 7),
  [148] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_ortho_choice_repeat1, 2, 0, 6),
  [150] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_ortho_choice_repeat1, 2, 0, 6), SHIFT_REPEAT(48),
  [153] = {.entry = {.count = 1, .reusable = true}}, SHIFT(39),
  [155] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [157] = {.entry = {.count = 1, .reusable = true}}, SHIFT(41),
  [159] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__line, 1, 0, 0),
  [161] = {.entry = {.count = 1, .reusable = true}}, SHIFT(60),
  [163] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_ortho_choice_repeat1, 2, 0, 2),
  [165] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__line, 2, 0, 0),
  [167] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
  [169] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 2, 0, 0),
  [171] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [173] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [175] = {.entry = {.count = 1, .reusable = true}}, SHIFT(40),
  [177] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [179] = {.entry = {.count = 1, .reusable = true}}, SHIFT(42),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_tort(void) {
  static const TSLanguage language = {
    .version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = ts_lex_modes,
    .lex_fn = ts_lex,
    .keyword_lex_fn = ts_lex_keywords,
    .keyword_capture_token = sym__token,
    .primary_state_ids = ts_primary_state_ids,
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
