(linenum) @tag
(name_fn) @function
(name_amp) @string
(comment_text) @comment

(int) @number
(real) @number
(str) @string
(data_literal) @string
(data_real) @number
(data_int) @number
(data_str) @string

(name_real) @variable
(name_int) @variable
(name_str) @variable

(tok_rem) @comment
(tok_plus) @operator
(tok_minus) @operator
(tok_times) @operator
(tok_div) @operator
(tok_pow) @operator
(tok_gtr) @operator
(tok_eq) @operator
(tok_less) @operator
(tok_and) @operator
(tok_or) @operator
(tok_not) @operator
(tok_end) @keyword.builtin
(tok_for) @keyword.builtin
(tok_next) @keyword.builtin
(tok_data) @keyword.builtin
(tok_input) @keyword.builtin
(tok_del) @keyword.builtin
(tok_dim) @keyword.builtin
(tok_read) @keyword.builtin
(tok_gr) @keyword.builtin
(tok_text) @keyword.builtin
(tok_prn) @keyword.builtin
(tok_inn) @keyword.builtin
(tok_call) @keyword.builtin
(tok_plot) @keyword.builtin
(tok_hlin) @keyword.builtin
(tok_vlin) @keyword.builtin
(tok_hgr2) @keyword.builtin
(tok_hgr) @keyword.builtin
(tok_hcoloreq) @keyword.builtin
(tok_hplot) @keyword.builtin
(tok_draw) @keyword.builtin
(tok_xdraw) @keyword.builtin
(tok_htab) @keyword.builtin
(tok_home) @keyword.builtin
(tok_roteq) @keyword.builtin
(tok_scaleeq) @keyword.builtin
(tok_shload) @keyword.builtin
(tok_trace) @keyword.builtin
(tok_notrace) @keyword.builtin
(tok_normal) @keyword.builtin
(tok_inverse) @keyword.builtin
(tok_flash) @keyword.builtin
(tok_coloreq) @keyword.builtin
(tok_pop) @keyword.builtin
(tok_vtab) @keyword.builtin
(tok_himem) @keyword.builtin
(tok_lomem) @keyword.builtin
(tok_onerr) @keyword.builtin
(tok_resume) @keyword.builtin
(tok_recall) @keyword.builtin
(tok_store) @keyword.builtin
(tok_speedeq) @keyword.builtin
(tok_let) @keyword.builtin
(tok_goto) @keyword.builtin
(tok_run) @keyword.builtin
(tok_if) @keyword.builtin
(tok_restore) @keyword.builtin
(tok_amp) @keyword.builtin
(tok_gosub) @keyword.builtin
(tok_return) @keyword.builtin
(tok_stop) @keyword.builtin
(tok_on) @keyword.builtin
(tok_wait) @keyword.builtin
(tok_load) @keyword.builtin
(tok_save) @keyword.builtin
(tok_def) @keyword.builtin
(tok_poke) @keyword.builtin
(tok_print) @keyword.builtin
(tok_cont) @keyword.builtin
(tok_list) @keyword.builtin
(tok_clear) @keyword.builtin
(tok_get) @keyword.builtin
(tok_new) @keyword.builtin
(tok_tabp) @keyword.builtin
(tok_to) @keyword.builtin
(tok_fn) @keyword.builtin
(tok_spcp) @keyword.builtin
(tok_then) @keyword.builtin
(tok_at) @keyword.builtin
(tok_step) @keyword.builtin
(tok_sgn) @function.builtin
(tok_int) @function.builtin
(tok_abs) @function.builtin
(tok_usr) @function.builtin
(tok_fre) @function.builtin
(tok_scrnp) @function.builtin
(tok_pdl) @function.builtin
(tok_pos) @function.builtin
(tok_sqr) @function.builtin
(tok_rnd) @function.builtin
(tok_log) @function.builtin
(tok_exp) @function.builtin
(tok_cos) @function.builtin
(tok_sin) @function.builtin
(tok_tan) @function.builtin
(tok_atn) @function.builtin
(tok_peek) @function.builtin
(tok_len) @function.builtin
(tok_str) @function.builtin
(tok_val) @function.builtin
(tok_asc) @function.builtin
(tok_chr) @function.builtin
(tok_left) @function.builtin
(tok_right) @function.builtin
(tok_mid) @function.builtin
