#include "parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 14
#define STATE_COUNT 86
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 46
#define ALIAS_COUNT 0
#define TOKEN_COUNT 21
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 1
#define MAX_ALIAS_SEQUENCE_LENGTH 3
#define PRODUCTION_ID_COUNT 2

enum ts_symbol_identifiers {
  anon_sym_POUND = 1,
  aux_sym_comment_token1 = 2,
  anon_sym_LBRACE = 3,
  anon_sym_COMMA = 4,
  anon_sym_RBRACE = 5,
  anon_sym_EQ = 6,
  anon_sym_pattern = 7,
  anon_sym_file = 8,
  sym_identifier = 9,
  sym__bareword = 10,
  anon_sym_DQUOTE = 11,
  aux_sym_quoted_string_text_fragment_token1 = 12,
  anon_sym_BSLASH = 13,
  anon_sym_BSLASH_DQUOTE = 14,
  anon_sym_BSLASH_BSLASH = 15,
  anon_sym_DOLLAR_LBRACE = 16,
  aux_sym_macro_expansion_token1 = 17,
  anon_sym_DOLLAR_LPAREN = 18,
  aux_sym_macro_expansion_token2 = 19,
  anon_sym_RPAREN = 20,
  sym_source_file = 21,
  sym_comment = 22,
  sym_regular = 23,
  sym__regular_assignment = 24,
  sym_pattern = 25,
  sym_pattern_variables = 26,
  sym_pattern_values = 27,
  sym_db_template = 28,
  sym_substitutions = 29,
  sym_string = 30,
  sym_quoted_string = 31,
  sym_quoted_string_text_fragment = 32,
  sym_escape_sequence = 33,
  sym_macro_expansion = 34,
  aux_sym_source_file_repeat1 = 35,
  aux_sym_source_file_repeat2 = 36,
  aux_sym_source_file_repeat3 = 37,
  aux_sym_regular_repeat1 = 38,
  aux_sym_pattern_repeat1 = 39,
  aux_sym_pattern_variables_repeat1 = 40,
  aux_sym_pattern_values_repeat1 = 41,
  aux_sym_quoted_string_repeat1 = 42,
  aux_sym_quoted_string_text_fragment_repeat1 = 43,
  aux_sym_macro_expansion_repeat1 = 44,
  aux_sym_macro_expansion_repeat2 = 45,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_POUND] = "#",
  [aux_sym_comment_token1] = "comment_token1",
  [anon_sym_LBRACE] = "{",
  [anon_sym_COMMA] = ",",
  [anon_sym_RBRACE] = "}",
  [anon_sym_EQ] = "=",
  [anon_sym_pattern] = "pattern",
  [anon_sym_file] = "file",
  [sym_identifier] = "identifier",
  [sym__bareword] = "_bareword",
  [anon_sym_DQUOTE] = "\"",
  [aux_sym_quoted_string_text_fragment_token1] = "quoted_string_text_fragment_token1",
  [anon_sym_BSLASH] = "\\",
  [anon_sym_BSLASH_DQUOTE] = "\\\"",
  [anon_sym_BSLASH_BSLASH] = "\\\\",
  [anon_sym_DOLLAR_LBRACE] = "${",
  [aux_sym_macro_expansion_token1] = "macro_expansion_token1",
  [anon_sym_DOLLAR_LPAREN] = "$(",
  [aux_sym_macro_expansion_token2] = "macro_expansion_token2",
  [anon_sym_RPAREN] = ")",
  [sym_source_file] = "source_file",
  [sym_comment] = "comment",
  [sym_regular] = "regular",
  [sym__regular_assignment] = "_regular_assignment",
  [sym_pattern] = "pattern",
  [sym_pattern_variables] = "pattern_variables",
  [sym_pattern_values] = "pattern_values",
  [sym_db_template] = "db_template",
  [sym_substitutions] = "substitutions",
  [sym_string] = "string",
  [sym_quoted_string] = "quoted_string",
  [sym_quoted_string_text_fragment] = "quoted_string_text_fragment",
  [sym_escape_sequence] = "escape_sequence",
  [sym_macro_expansion] = "macro_expansion",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_source_file_repeat2] = "source_file_repeat2",
  [aux_sym_source_file_repeat3] = "source_file_repeat3",
  [aux_sym_regular_repeat1] = "regular_repeat1",
  [aux_sym_pattern_repeat1] = "pattern_repeat1",
  [aux_sym_pattern_variables_repeat1] = "pattern_variables_repeat1",
  [aux_sym_pattern_values_repeat1] = "pattern_values_repeat1",
  [aux_sym_quoted_string_repeat1] = "quoted_string_repeat1",
  [aux_sym_quoted_string_text_fragment_repeat1] = "quoted_string_text_fragment_repeat1",
  [aux_sym_macro_expansion_repeat1] = "macro_expansion_repeat1",
  [aux_sym_macro_expansion_repeat2] = "macro_expansion_repeat2",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_POUND] = anon_sym_POUND,
  [aux_sym_comment_token1] = aux_sym_comment_token1,
  [anon_sym_LBRACE] = anon_sym_LBRACE,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [anon_sym_EQ] = anon_sym_EQ,
  [anon_sym_pattern] = anon_sym_pattern,
  [anon_sym_file] = anon_sym_file,
  [sym_identifier] = sym_identifier,
  [sym__bareword] = sym__bareword,
  [anon_sym_DQUOTE] = anon_sym_DQUOTE,
  [aux_sym_quoted_string_text_fragment_token1] = aux_sym_quoted_string_text_fragment_token1,
  [anon_sym_BSLASH] = anon_sym_BSLASH,
  [anon_sym_BSLASH_DQUOTE] = anon_sym_BSLASH_DQUOTE,
  [anon_sym_BSLASH_BSLASH] = anon_sym_BSLASH_BSLASH,
  [anon_sym_DOLLAR_LBRACE] = anon_sym_DOLLAR_LBRACE,
  [aux_sym_macro_expansion_token1] = aux_sym_macro_expansion_token1,
  [anon_sym_DOLLAR_LPAREN] = anon_sym_DOLLAR_LPAREN,
  [aux_sym_macro_expansion_token2] = aux_sym_macro_expansion_token2,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [sym_source_file] = sym_source_file,
  [sym_comment] = sym_comment,
  [sym_regular] = sym_regular,
  [sym__regular_assignment] = sym__regular_assignment,
  [sym_pattern] = sym_pattern,
  [sym_pattern_variables] = sym_pattern_variables,
  [sym_pattern_values] = sym_pattern_values,
  [sym_db_template] = sym_db_template,
  [sym_substitutions] = sym_substitutions,
  [sym_string] = sym_string,
  [sym_quoted_string] = sym_quoted_string,
  [sym_quoted_string_text_fragment] = sym_quoted_string_text_fragment,
  [sym_escape_sequence] = sym_escape_sequence,
  [sym_macro_expansion] = sym_macro_expansion,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_source_file_repeat2] = aux_sym_source_file_repeat2,
  [aux_sym_source_file_repeat3] = aux_sym_source_file_repeat3,
  [aux_sym_regular_repeat1] = aux_sym_regular_repeat1,
  [aux_sym_pattern_repeat1] = aux_sym_pattern_repeat1,
  [aux_sym_pattern_variables_repeat1] = aux_sym_pattern_variables_repeat1,
  [aux_sym_pattern_values_repeat1] = aux_sym_pattern_values_repeat1,
  [aux_sym_quoted_string_repeat1] = aux_sym_quoted_string_repeat1,
  [aux_sym_quoted_string_text_fragment_repeat1] = aux_sym_quoted_string_text_fragment_repeat1,
  [aux_sym_macro_expansion_repeat1] = aux_sym_macro_expansion_repeat1,
  [aux_sym_macro_expansion_repeat2] = aux_sym_macro_expansion_repeat2,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_POUND] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_comment_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_pattern] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_file] = {
    .visible = true,
    .named = false,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [sym__bareword] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_DQUOTE] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_quoted_string_text_fragment_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_BSLASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_BSLASH_DQUOTE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_BSLASH_BSLASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DOLLAR_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_macro_expansion_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_DOLLAR_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_macro_expansion_token2] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [sym_regular] = {
    .visible = true,
    .named = true,
  },
  [sym__regular_assignment] = {
    .visible = false,
    .named = true,
  },
  [sym_pattern] = {
    .visible = true,
    .named = true,
  },
  [sym_pattern_variables] = {
    .visible = true,
    .named = true,
  },
  [sym_pattern_values] = {
    .visible = true,
    .named = true,
  },
  [sym_db_template] = {
    .visible = true,
    .named = true,
  },
  [sym_substitutions] = {
    .visible = true,
    .named = true,
  },
  [sym_string] = {
    .visible = true,
    .named = true,
  },
  [sym_quoted_string] = {
    .visible = true,
    .named = true,
  },
  [sym_quoted_string_text_fragment] = {
    .visible = true,
    .named = true,
  },
  [sym_escape_sequence] = {
    .visible = true,
    .named = true,
  },
  [sym_macro_expansion] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_source_file_repeat2] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_source_file_repeat3] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_regular_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_pattern_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_pattern_variables_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_pattern_values_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_quoted_string_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_quoted_string_text_fragment_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_macro_expansion_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_macro_expansion_repeat2] = {
    .visible = false,
    .named = false,
  },
};

enum ts_field_identifiers {
  field_file = 1,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_file] = "file",
};

static const TSFieldMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 1},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_file, 1},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 2,
  [6] = 3,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 39,
  [40] = 40,
  [41] = 29,
  [42] = 36,
  [43] = 40,
  [44] = 44,
  [45] = 45,
  [46] = 46,
  [47] = 47,
  [48] = 48,
  [49] = 49,
  [50] = 50,
  [51] = 51,
  [52] = 52,
  [53] = 53,
  [54] = 54,
  [55] = 55,
  [56] = 56,
  [57] = 57,
  [58] = 52,
  [59] = 55,
  [60] = 60,
  [61] = 52,
  [62] = 55,
  [63] = 63,
  [64] = 64,
  [65] = 65,
  [66] = 66,
  [67] = 67,
  [68] = 68,
  [69] = 69,
  [70] = 70,
  [71] = 69,
  [72] = 72,
  [73] = 73,
  [74] = 74,
  [75] = 75,
  [76] = 76,
  [77] = 65,
  [78] = 75,
  [79] = 65,
  [80] = 75,
  [81] = 81,
  [82] = 82,
  [83] = 83,
  [84] = 69,
  [85] = 85,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(17);
      ADVANCE_MAP(
        '"', 34,
        '#', 18,
        '$', 6,
        ')', 54,
        ',', 27,
        '=', 29,
        '\\', 37,
        'f', 10,
        'p', 7,
        '{', 26,
        '}', 28,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(16);
      END_STATE();
    case 1:
      if (lookahead == '"') ADVANCE(34);
      if (lookahead == '#') ADVANCE(18);
      if (lookahead == '$') ADVANCE(6);
      if (lookahead == ',') ADVANCE(27);
      if (lookahead == '}') ADVANCE(28);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(1);
      if (('+' <= lookahead && lookahead <= '<') ||
          lookahead == '>' ||
          ('A' <= lookahead && lookahead <= ']') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(33);
      END_STATE();
    case 2:
      if (lookahead == '"') ADVANCE(34);
      if (lookahead == '#') ADVANCE(19);
      if (lookahead == '$') ADVANCE(6);
      if (lookahead == '\\') ADVANCE(37);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(35);
      if (lookahead != 0) ADVANCE(36);
      END_STATE();
    case 3:
      if (lookahead == '#') ADVANCE(18);
      if (lookahead == '$') ADVANCE(6);
      if (lookahead == ',') ADVANCE(27);
      if (lookahead == '{') ADVANCE(26);
      if (lookahead == '}') ADVANCE(28);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(3);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(32);
      END_STATE();
    case 4:
      if (lookahead == '#') ADVANCE(22);
      if (lookahead == '$') ADVANCE(45);
      if (lookahead == '}') ADVANCE(28);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(44);
      if (lookahead != 0) ADVANCE(46);
      END_STATE();
    case 5:
      if (lookahead == '#') ADVANCE(21);
      if (lookahead == '$') ADVANCE(52);
      if (lookahead == ')') ADVANCE(54);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(51);
      if (lookahead != 0) ADVANCE(53);
      END_STATE();
    case 6:
      if (lookahead == '(') ADVANCE(47);
      if (lookahead == '{') ADVANCE(40);
      END_STATE();
    case 7:
      if (lookahead == 'a') ADVANCE(14);
      END_STATE();
    case 8:
      if (lookahead == 'e') ADVANCE(31);
      END_STATE();
    case 9:
      if (lookahead == 'e') ADVANCE(13);
      END_STATE();
    case 10:
      if (lookahead == 'i') ADVANCE(11);
      END_STATE();
    case 11:
      if (lookahead == 'l') ADVANCE(8);
      END_STATE();
    case 12:
      if (lookahead == 'n') ADVANCE(30);
      END_STATE();
    case 13:
      if (lookahead == 'r') ADVANCE(12);
      END_STATE();
    case 14:
      if (lookahead == 't') ADVANCE(15);
      END_STATE();
    case 15:
      if (lookahead == 't') ADVANCE(9);
      END_STATE();
    case 16:
      if (eof) ADVANCE(17);
      ADVANCE_MAP(
        '"', 34,
        '#', 18,
        '$', 6,
        ')', 54,
        ',', 27,
        '=', 29,
        'f', 10,
        'p', 7,
        '{', 26,
        '}', 28,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(16);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(anon_sym_POUND);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(anon_sym_POUND);
      if (lookahead != 0 &&
          lookahead != '"' &&
          lookahead != '$' &&
          lookahead != '\\') ADVANCE(36);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(anon_sym_POUND);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(25);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(anon_sym_POUND);
      if (lookahead != 0 &&
          lookahead != ')') ADVANCE(53);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(anon_sym_POUND);
      if (lookahead != 0 &&
          lookahead != '}') ADVANCE(46);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(aux_sym_comment_token1);
      if (lookahead == '#') ADVANCE(20);
      if (lookahead == '$') ADVANCE(24);
      if (lookahead == '\t' ||
          (0x0b <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(23);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead)) ADVANCE(25);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(aux_sym_comment_token1);
      if (lookahead == '(') ADVANCE(48);
      if (lookahead == '{') ADVANCE(41);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(25);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(aux_sym_comment_token1);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(25);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(anon_sym_EQ);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(anon_sym_pattern);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(anon_sym_file);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(sym_identifier);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(32);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(sym__bareword);
      if (lookahead == '+' ||
          ('-' <= lookahead && lookahead <= '<') ||
          lookahead == '>' ||
          ('A' <= lookahead && lookahead <= ']') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(33);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(anon_sym_DQUOTE);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(aux_sym_quoted_string_text_fragment_token1);
      if (lookahead == '#') ADVANCE(19);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(35);
      if (lookahead != 0 &&
          (lookahead < '"' || '$' < lookahead) &&
          lookahead != '\\') ADVANCE(36);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(aux_sym_quoted_string_text_fragment_token1);
      if (lookahead != 0 &&
          lookahead != '"' &&
          lookahead != '$' &&
          lookahead != '\\') ADVANCE(36);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(anon_sym_BSLASH);
      if (lookahead == '"') ADVANCE(38);
      if (lookahead == '\\') ADVANCE(39);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(anon_sym_BSLASH_DQUOTE);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(anon_sym_BSLASH_BSLASH);
      END_STATE();
    case 40:
      ACCEPT_TOKEN(anon_sym_DOLLAR_LBRACE);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(anon_sym_DOLLAR_LBRACE);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(25);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(anon_sym_DOLLAR_LBRACE);
      if (lookahead != 0 &&
          lookahead != ')') ADVANCE(53);
      END_STATE();
    case 43:
      ACCEPT_TOKEN(anon_sym_DOLLAR_LBRACE);
      if (lookahead != 0 &&
          lookahead != '}') ADVANCE(46);
      END_STATE();
    case 44:
      ACCEPT_TOKEN(aux_sym_macro_expansion_token1);
      if (lookahead == '#') ADVANCE(22);
      if (lookahead == '$') ADVANCE(45);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(44);
      if (lookahead != 0 &&
          lookahead != '}') ADVANCE(46);
      END_STATE();
    case 45:
      ACCEPT_TOKEN(aux_sym_macro_expansion_token1);
      if (lookahead == '(') ADVANCE(50);
      if (lookahead == '{') ADVANCE(43);
      if (lookahead != 0 &&
          lookahead != '}') ADVANCE(46);
      END_STATE();
    case 46:
      ACCEPT_TOKEN(aux_sym_macro_expansion_token1);
      if (lookahead != 0 &&
          lookahead != '}') ADVANCE(46);
      END_STATE();
    case 47:
      ACCEPT_TOKEN(anon_sym_DOLLAR_LPAREN);
      END_STATE();
    case 48:
      ACCEPT_TOKEN(anon_sym_DOLLAR_LPAREN);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(25);
      END_STATE();
    case 49:
      ACCEPT_TOKEN(anon_sym_DOLLAR_LPAREN);
      if (lookahead != 0 &&
          lookahead != ')') ADVANCE(53);
      END_STATE();
    case 50:
      ACCEPT_TOKEN(anon_sym_DOLLAR_LPAREN);
      if (lookahead != 0 &&
          lookahead != '}') ADVANCE(46);
      END_STATE();
    case 51:
      ACCEPT_TOKEN(aux_sym_macro_expansion_token2);
      if (lookahead == '#') ADVANCE(21);
      if (lookahead == '$') ADVANCE(52);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(51);
      if (lookahead != 0 &&
          lookahead != ')') ADVANCE(53);
      END_STATE();
    case 52:
      ACCEPT_TOKEN(aux_sym_macro_expansion_token2);
      if (lookahead == '(') ADVANCE(49);
      if (lookahead == '{') ADVANCE(42);
      if (lookahead != 0 &&
          lookahead != '(' &&
          lookahead != ')') ADVANCE(53);
      END_STATE();
    case 53:
      ACCEPT_TOKEN(aux_sym_macro_expansion_token2);
      if (lookahead != 0 &&
          lookahead != ')') ADVANCE(53);
      END_STATE();
    case 54:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 0},
  [2] = {.lex_state = 2},
  [3] = {.lex_state = 2},
  [4] = {.lex_state = 2},
  [5] = {.lex_state = 2},
  [6] = {.lex_state = 2},
  [7] = {.lex_state = 0},
  [8] = {.lex_state = 0},
  [9] = {.lex_state = 1},
  [10] = {.lex_state = 0},
  [11] = {.lex_state = 1},
  [12] = {.lex_state = 2},
  [13] = {.lex_state = 1},
  [14] = {.lex_state = 0},
  [15] = {.lex_state = 2},
  [16] = {.lex_state = 0},
  [17] = {.lex_state = 0},
  [18] = {.lex_state = 2},
  [19] = {.lex_state = 2},
  [20] = {.lex_state = 2},
  [21] = {.lex_state = 1},
  [22] = {.lex_state = 3},
  [23] = {.lex_state = 3},
  [24] = {.lex_state = 0},
  [25] = {.lex_state = 1},
  [26] = {.lex_state = 3},
  [27] = {.lex_state = 0},
  [28] = {.lex_state = 0},
  [29] = {.lex_state = 3},
  [30] = {.lex_state = 0},
  [31] = {.lex_state = 0},
  [32] = {.lex_state = 0},
  [33] = {.lex_state = 0},
  [34] = {.lex_state = 0},
  [35] = {.lex_state = 1},
  [36] = {.lex_state = 3},
  [37] = {.lex_state = 0},
  [38] = {.lex_state = 0},
  [39] = {.lex_state = 0},
  [40] = {.lex_state = 1},
  [41] = {.lex_state = 1},
  [42] = {.lex_state = 1},
  [43] = {.lex_state = 3},
  [44] = {.lex_state = 0},
  [45] = {.lex_state = 0},
  [46] = {.lex_state = 4},
  [47] = {.lex_state = 3},
  [48] = {.lex_state = 5},
  [49] = {.lex_state = 3},
  [50] = {.lex_state = 3},
  [51] = {.lex_state = 0},
  [52] = {.lex_state = 4},
  [53] = {.lex_state = 1},
  [54] = {.lex_state = 3},
  [55] = {.lex_state = 5},
  [56] = {.lex_state = 3},
  [57] = {.lex_state = 3},
  [58] = {.lex_state = 4},
  [59] = {.lex_state = 5},
  [60] = {.lex_state = 0},
  [61] = {.lex_state = 4},
  [62] = {.lex_state = 5},
  [63] = {.lex_state = 5},
  [64] = {.lex_state = 0},
  [65] = {.lex_state = 4},
  [66] = {.lex_state = 3},
  [67] = {.lex_state = 0},
  [68] = {.lex_state = 4},
  [69] = {.lex_state = 4},
  [70] = {.lex_state = 3},
  [71] = {.lex_state = 5},
  [72] = {.lex_state = 0},
  [73] = {.lex_state = 0},
  [74] = {.lex_state = 0},
  [75] = {.lex_state = 5},
  [76] = {.lex_state = 0},
  [77] = {.lex_state = 4},
  [78] = {.lex_state = 5},
  [79] = {.lex_state = 4},
  [80] = {.lex_state = 5},
  [81] = {.lex_state = 0},
  [82] = {.lex_state = 0},
  [83] = {.lex_state = 23},
  [84] = {(TSStateId)(-1)},
  [85] = {(TSStateId)(-1)},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [0] = {
    [sym_comment] = STATE(0),
    [sym_macro_expansion] = STATE(0),
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_POUND] = ACTIONS(3),
    [anon_sym_LBRACE] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [anon_sym_EQ] = ACTIONS(1),
    [anon_sym_pattern] = ACTIONS(1),
    [anon_sym_file] = ACTIONS(1),
    [anon_sym_DQUOTE] = ACTIONS(1),
    [anon_sym_BSLASH] = ACTIONS(1),
    [anon_sym_BSLASH_DQUOTE] = ACTIONS(1),
    [anon_sym_BSLASH_BSLASH] = ACTIONS(1),
    [anon_sym_DOLLAR_LBRACE] = ACTIONS(5),
    [anon_sym_DOLLAR_LPAREN] = ACTIONS(7),
    [anon_sym_RPAREN] = ACTIONS(1),
  },
  [1] = {
    [sym_source_file] = STATE(82),
    [sym_comment] = STATE(1),
    [sym_regular] = STATE(44),
    [sym_pattern] = STATE(45),
    [sym_db_template] = STATE(72),
    [sym_macro_expansion] = STATE(1),
    [aux_sym_source_file_repeat1] = STATE(30),
    [aux_sym_source_file_repeat2] = STATE(31),
    [aux_sym_source_file_repeat3] = STATE(32),
    [ts_builtin_sym_end] = ACTIONS(9),
    [anon_sym_POUND] = ACTIONS(3),
    [anon_sym_LBRACE] = ACTIONS(11),
    [anon_sym_pattern] = ACTIONS(13),
    [anon_sym_file] = ACTIONS(15),
    [anon_sym_DOLLAR_LBRACE] = ACTIONS(5),
    [anon_sym_DOLLAR_LPAREN] = ACTIONS(7),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 10,
    ACTIONS(17), 1,
      anon_sym_POUND,
    ACTIONS(19), 1,
      anon_sym_DQUOTE,
    ACTIONS(25), 1,
      anon_sym_DOLLAR_LBRACE,
    ACTIONS(27), 1,
      anon_sym_DOLLAR_LPAREN,
    STATE(3), 1,
      aux_sym_quoted_string_repeat1,
    STATE(12), 1,
      aux_sym_quoted_string_text_fragment_repeat1,
    ACTIONS(21), 2,
      aux_sym_quoted_string_text_fragment_token1,
      anon_sym_BSLASH,
    ACTIONS(23), 2,
      anon_sym_BSLASH_DQUOTE,
      anon_sym_BSLASH_BSLASH,
    STATE(2), 2,
      sym_comment,
      sym_macro_expansion,
    STATE(20), 2,
      sym_quoted_string_text_fragment,
      sym_escape_sequence,
  [35] = 10,
    ACTIONS(17), 1,
      anon_sym_POUND,
    ACTIONS(25), 1,
      anon_sym_DOLLAR_LBRACE,
    ACTIONS(27), 1,
      anon_sym_DOLLAR_LPAREN,
    ACTIONS(29), 1,
      anon_sym_DQUOTE,
    STATE(4), 1,
      aux_sym_quoted_string_repeat1,
    STATE(12), 1,
      aux_sym_quoted_string_text_fragment_repeat1,
    ACTIONS(21), 2,
      aux_sym_quoted_string_text_fragment_token1,
      anon_sym_BSLASH,
    ACTIONS(23), 2,
      anon_sym_BSLASH_DQUOTE,
      anon_sym_BSLASH_BSLASH,
    STATE(3), 2,
      sym_comment,
      sym_macro_expansion,
    STATE(20), 2,
      sym_quoted_string_text_fragment,
      sym_escape_sequence,
  [70] = 9,
    ACTIONS(17), 1,
      anon_sym_POUND,
    ACTIONS(25), 1,
      anon_sym_DOLLAR_LBRACE,
    ACTIONS(27), 1,
      anon_sym_DOLLAR_LPAREN,
    ACTIONS(31), 1,
      anon_sym_DQUOTE,
    STATE(12), 1,
      aux_sym_quoted_string_text_fragment_repeat1,
    ACTIONS(33), 2,
      aux_sym_quoted_string_text_fragment_token1,
      anon_sym_BSLASH,
    ACTIONS(36), 2,
      anon_sym_BSLASH_DQUOTE,
      anon_sym_BSLASH_BSLASH,
    STATE(20), 2,
      sym_quoted_string_text_fragment,
      sym_escape_sequence,
    STATE(4), 3,
      sym_comment,
      sym_macro_expansion,
      aux_sym_quoted_string_repeat1,
  [103] = 10,
    ACTIONS(17), 1,
      anon_sym_POUND,
    ACTIONS(25), 1,
      anon_sym_DOLLAR_LBRACE,
    ACTIONS(27), 1,
      anon_sym_DOLLAR_LPAREN,
    ACTIONS(39), 1,
      anon_sym_DQUOTE,
    STATE(6), 1,
      aux_sym_quoted_string_repeat1,
    STATE(12), 1,
      aux_sym_quoted_string_text_fragment_repeat1,
    ACTIONS(21), 2,
      aux_sym_quoted_string_text_fragment_token1,
      anon_sym_BSLASH,
    ACTIONS(23), 2,
      anon_sym_BSLASH_DQUOTE,
      anon_sym_BSLASH_BSLASH,
    STATE(5), 2,
      sym_comment,
      sym_macro_expansion,
    STATE(20), 2,
      sym_quoted_string_text_fragment,
      sym_escape_sequence,
  [138] = 10,
    ACTIONS(17), 1,
      anon_sym_POUND,
    ACTIONS(25), 1,
      anon_sym_DOLLAR_LBRACE,
    ACTIONS(27), 1,
      anon_sym_DOLLAR_LPAREN,
    ACTIONS(41), 1,
      anon_sym_DQUOTE,
    STATE(4), 1,
      aux_sym_quoted_string_repeat1,
    STATE(12), 1,
      aux_sym_quoted_string_text_fragment_repeat1,
    ACTIONS(21), 2,
      aux_sym_quoted_string_text_fragment_token1,
      anon_sym_BSLASH,
    ACTIONS(23), 2,
      anon_sym_BSLASH_DQUOTE,
      anon_sym_BSLASH_BSLASH,
    STATE(6), 2,
      sym_comment,
      sym_macro_expansion,
    STATE(20), 2,
      sym_quoted_string_text_fragment,
      sym_escape_sequence,
  [173] = 11,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(5), 1,
      anon_sym_DOLLAR_LBRACE,
    ACTIONS(7), 1,
      anon_sym_DOLLAR_LPAREN,
    ACTIONS(11), 1,
      anon_sym_LBRACE,
    ACTIONS(13), 1,
      anon_sym_pattern,
    ACTIONS(43), 1,
      anon_sym_RBRACE,
    STATE(37), 1,
      aux_sym_source_file_repeat1,
    STATE(38), 1,
      aux_sym_source_file_repeat2,
    STATE(44), 1,
      sym_regular,
    STATE(45), 1,
      sym_pattern,
    STATE(7), 2,
      sym_comment,
      sym_macro_expansion,
  [208] = 8,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(5), 1,
      anon_sym_DOLLAR_LBRACE,
    ACTIONS(7), 1,
      anon_sym_DOLLAR_LPAREN,
    ACTIONS(47), 1,
      anon_sym_LBRACE,
    STATE(10), 1,
      aux_sym_pattern_repeat1,
    STATE(28), 1,
      sym_pattern_values,
    STATE(8), 2,
      sym_comment,
      sym_macro_expansion,
    ACTIONS(45), 3,
      ts_builtin_sym_end,
      anon_sym_RBRACE,
      anon_sym_pattern,
  [236] = 10,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(5), 1,
      anon_sym_DOLLAR_LBRACE,
    ACTIONS(7), 1,
      anon_sym_DOLLAR_LPAREN,
    ACTIONS(49), 1,
      anon_sym_RBRACE,
    ACTIONS(51), 1,
      sym__bareword,
    ACTIONS(53), 1,
      anon_sym_DQUOTE,
    STATE(13), 1,
      aux_sym_pattern_values_repeat1,
    STATE(35), 1,
      sym_string,
    STATE(40), 1,
      sym_quoted_string,
    STATE(9), 2,
      sym_comment,
      sym_macro_expansion,
  [268] = 8,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(5), 1,
      anon_sym_DOLLAR_LBRACE,
    ACTIONS(7), 1,
      anon_sym_DOLLAR_LPAREN,
    ACTIONS(47), 1,
      anon_sym_LBRACE,
    STATE(14), 1,
      aux_sym_pattern_repeat1,
    STATE(28), 1,
      sym_pattern_values,
    STATE(10), 2,
      sym_comment,
      sym_macro_expansion,
    ACTIONS(55), 3,
      ts_builtin_sym_end,
      anon_sym_RBRACE,
      anon_sym_pattern,
  [296] = 9,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(5), 1,
      anon_sym_DOLLAR_LBRACE,
    ACTIONS(7), 1,
      anon_sym_DOLLAR_LPAREN,
    ACTIONS(57), 1,
      anon_sym_RBRACE,
    ACTIONS(59), 1,
      sym__bareword,
    ACTIONS(62), 1,
      anon_sym_DQUOTE,
    STATE(35), 1,
      sym_string,
    STATE(40), 1,
      sym_quoted_string,
    STATE(11), 3,
      sym_comment,
      sym_macro_expansion,
      aux_sym_pattern_values_repeat1,
  [326] = 8,
    ACTIONS(17), 1,
      anon_sym_POUND,
    ACTIONS(25), 1,
      anon_sym_DOLLAR_LBRACE,
    ACTIONS(27), 1,
      anon_sym_DOLLAR_LPAREN,
    ACTIONS(65), 1,
      anon_sym_DQUOTE,
    STATE(15), 1,
      aux_sym_quoted_string_text_fragment_repeat1,
    ACTIONS(21), 2,
      aux_sym_quoted_string_text_fragment_token1,
      anon_sym_BSLASH,
    ACTIONS(67), 2,
      anon_sym_BSLASH_DQUOTE,
      anon_sym_BSLASH_BSLASH,
    STATE(12), 2,
      sym_comment,
      sym_macro_expansion,
  [354] = 10,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(5), 1,
      anon_sym_DOLLAR_LBRACE,
    ACTIONS(7), 1,
      anon_sym_DOLLAR_LPAREN,
    ACTIONS(51), 1,
      sym__bareword,
    ACTIONS(53), 1,
      anon_sym_DQUOTE,
    ACTIONS(69), 1,
      anon_sym_RBRACE,
    STATE(11), 1,
      aux_sym_pattern_values_repeat1,
    STATE(35), 1,
      sym_string,
    STATE(40), 1,
      sym_quoted_string,
    STATE(13), 2,
      sym_comment,
      sym_macro_expansion,
  [386] = 7,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(5), 1,
      anon_sym_DOLLAR_LBRACE,
    ACTIONS(7), 1,
      anon_sym_DOLLAR_LPAREN,
    ACTIONS(73), 1,
      anon_sym_LBRACE,
    STATE(28), 1,
      sym_pattern_values,
    ACTIONS(71), 3,
      ts_builtin_sym_end,
      anon_sym_RBRACE,
      anon_sym_pattern,
    STATE(14), 3,
      sym_comment,
      sym_macro_expansion,
      aux_sym_pattern_repeat1,
  [412] = 7,
    ACTIONS(17), 1,
      anon_sym_POUND,
    ACTIONS(25), 1,
      anon_sym_DOLLAR_LBRACE,
    ACTIONS(27), 1,
      anon_sym_DOLLAR_LPAREN,
    ACTIONS(76), 1,
      anon_sym_DQUOTE,
    ACTIONS(78), 2,
      aux_sym_quoted_string_text_fragment_token1,
      anon_sym_BSLASH,
    ACTIONS(81), 2,
      anon_sym_BSLASH_DQUOTE,
      anon_sym_BSLASH_BSLASH,
    STATE(15), 3,
      sym_comment,
      sym_macro_expansion,
      aux_sym_quoted_string_text_fragment_repeat1,
  [438] = 7,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(5), 1,
      anon_sym_DOLLAR_LBRACE,
    ACTIONS(7), 1,
      anon_sym_DOLLAR_LPAREN,
    ACTIONS(85), 1,
      anon_sym_pattern,
    STATE(45), 1,
      sym_pattern,
    ACTIONS(83), 2,
      ts_builtin_sym_end,
      anon_sym_RBRACE,
    STATE(16), 3,
      sym_comment,
      sym_macro_expansion,
      aux_sym_source_file_repeat2,
  [463] = 7,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(5), 1,
      anon_sym_DOLLAR_LBRACE,
    ACTIONS(7), 1,
      anon_sym_DOLLAR_LPAREN,
    ACTIONS(90), 1,
      anon_sym_LBRACE,
    STATE(44), 1,
      sym_regular,
    ACTIONS(88), 2,
      ts_builtin_sym_end,
      anon_sym_RBRACE,
    STATE(17), 3,
      sym_comment,
      sym_macro_expansion,
      aux_sym_source_file_repeat1,
  [488] = 6,
    ACTIONS(17), 1,
      anon_sym_POUND,
    ACTIONS(25), 1,
      anon_sym_DOLLAR_LBRACE,
    ACTIONS(27), 1,
      anon_sym_DOLLAR_LPAREN,
    ACTIONS(95), 2,
      anon_sym_BSLASH_DQUOTE,
      anon_sym_BSLASH_BSLASH,
    STATE(18), 2,
      sym_comment,
      sym_macro_expansion,
    ACTIONS(93), 3,
      anon_sym_DQUOTE,
      aux_sym_quoted_string_text_fragment_token1,
      anon_sym_BSLASH,
  [511] = 6,
    ACTIONS(17), 1,
      anon_sym_POUND,
    ACTIONS(25), 1,
      anon_sym_DOLLAR_LBRACE,
    ACTIONS(27), 1,
      anon_sym_DOLLAR_LPAREN,
    ACTIONS(99), 2,
      anon_sym_BSLASH_DQUOTE,
      anon_sym_BSLASH_BSLASH,
    STATE(19), 2,
      sym_comment,
      sym_macro_expansion,
    ACTIONS(97), 3,
      anon_sym_DQUOTE,
      aux_sym_quoted_string_text_fragment_token1,
      anon_sym_BSLASH,
  [534] = 6,
    ACTIONS(17), 1,
      anon_sym_POUND,
    ACTIONS(25), 1,
      anon_sym_DOLLAR_LBRACE,
    ACTIONS(27), 1,
      anon_sym_DOLLAR_LPAREN,
    ACTIONS(103), 2,
      anon_sym_BSLASH_DQUOTE,
      anon_sym_BSLASH_BSLASH,
    STATE(20), 2,
      sym_comment,
      sym_macro_expansion,
    ACTIONS(101), 3,
      anon_sym_DQUOTE,
      aux_sym_quoted_string_text_fragment_token1,
      anon_sym_BSLASH,
  [557] = 8,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(5), 1,
      anon_sym_DOLLAR_LBRACE,
    ACTIONS(7), 1,
      anon_sym_DOLLAR_LPAREN,
    ACTIONS(105), 1,
      sym__bareword,
    ACTIONS(107), 1,
      anon_sym_DQUOTE,
    STATE(43), 1,
      sym_quoted_string,
    STATE(76), 1,
      sym_string,
    STATE(21), 2,
      sym_comment,
      sym_macro_expansion,
  [583] = 8,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(5), 1,
      anon_sym_DOLLAR_LBRACE,
    ACTIONS(7), 1,
      anon_sym_DOLLAR_LPAREN,
    ACTIONS(109), 1,
      anon_sym_RBRACE,
    ACTIONS(111), 1,
      sym_identifier,
    STATE(26), 1,
      aux_sym_regular_repeat1,
    STATE(50), 1,
      sym__regular_assignment,
    STATE(22), 2,
      sym_comment,
      sym_macro_expansion,
  [609] = 8,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(5), 1,
      anon_sym_DOLLAR_LBRACE,
    ACTIONS(7), 1,
      anon_sym_DOLLAR_LPAREN,
    ACTIONS(111), 1,
      sym_identifier,
    ACTIONS(113), 1,
      anon_sym_RBRACE,
    STATE(22), 1,
      aux_sym_regular_repeat1,
    STATE(50), 1,
      sym__regular_assignment,
    STATE(23), 2,
      sym_comment,
      sym_macro_expansion,
  [635] = 7,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(5), 1,
      anon_sym_DOLLAR_LBRACE,
    ACTIONS(7), 1,
      anon_sym_DOLLAR_LPAREN,
    ACTIONS(115), 1,
      ts_builtin_sym_end,
    ACTIONS(117), 1,
      anon_sym_file,
    STATE(72), 1,
      sym_db_template,
    STATE(24), 3,
      sym_comment,
      sym_macro_expansion,
      aux_sym_source_file_repeat3,
  [659] = 8,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(5), 1,
      anon_sym_DOLLAR_LBRACE,
    ACTIONS(7), 1,
      anon_sym_DOLLAR_LPAREN,
    ACTIONS(105), 1,
      sym__bareword,
    ACTIONS(107), 1,
      anon_sym_DQUOTE,
    STATE(43), 1,
      sym_quoted_string,
    STATE(47), 1,
      sym_string,
    STATE(25), 2,
      sym_comment,
      sym_macro_expansion,
  [685] = 7,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(5), 1,
      anon_sym_DOLLAR_LBRACE,
    ACTIONS(7), 1,
      anon_sym_DOLLAR_LPAREN,
    ACTIONS(120), 1,
      anon_sym_RBRACE,
    ACTIONS(122), 1,
      sym_identifier,
    STATE(50), 1,
      sym__regular_assignment,
    STATE(26), 3,
      sym_comment,
      sym_macro_expansion,
      aux_sym_regular_repeat1,
  [709] = 5,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(5), 1,
      anon_sym_DOLLAR_LBRACE,
    ACTIONS(7), 1,
      anon_sym_DOLLAR_LPAREN,
    STATE(27), 2,
      sym_comment,
      sym_macro_expansion,
    ACTIONS(125), 4,
      ts_builtin_sym_end,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_pattern,
  [729] = 5,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(5), 1,
      anon_sym_DOLLAR_LBRACE,
    ACTIONS(7), 1,
      anon_sym_DOLLAR_LPAREN,
    STATE(28), 2,
      sym_comment,
      sym_macro_expansion,
    ACTIONS(127), 4,
      ts_builtin_sym_end,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_pattern,
  [749] = 5,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(5), 1,
      anon_sym_DOLLAR_LBRACE,
    ACTIONS(7), 1,
      anon_sym_DOLLAR_LPAREN,
    STATE(29), 2,
      sym_comment,
      sym_macro_expansion,
    ACTIONS(129), 4,
      anon_sym_LBRACE,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      sym_identifier,
  [769] = 8,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(5), 1,
      anon_sym_DOLLAR_LBRACE,
    ACTIONS(7), 1,
      anon_sym_DOLLAR_LPAREN,
    ACTIONS(11), 1,
      anon_sym_LBRACE,
    ACTIONS(131), 1,
      ts_builtin_sym_end,
    STATE(17), 1,
      aux_sym_source_file_repeat1,
    STATE(44), 1,
      sym_regular,
    STATE(30), 2,
      sym_comment,
      sym_macro_expansion,
  [795] = 8,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(5), 1,
      anon_sym_DOLLAR_LBRACE,
    ACTIONS(7), 1,
      anon_sym_DOLLAR_LPAREN,
    ACTIONS(13), 1,
      anon_sym_pattern,
    ACTIONS(131), 1,
      ts_builtin_sym_end,
    STATE(16), 1,
      aux_sym_source_file_repeat2,
    STATE(45), 1,
      sym_pattern,
    STATE(31), 2,
      sym_comment,
      sym_macro_expansion,
  [821] = 8,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(5), 1,
      anon_sym_DOLLAR_LBRACE,
    ACTIONS(7), 1,
      anon_sym_DOLLAR_LPAREN,
    ACTIONS(15), 1,
      anon_sym_file,
    ACTIONS(131), 1,
      ts_builtin_sym_end,
    STATE(24), 1,
      aux_sym_source_file_repeat3,
    STATE(72), 1,
      sym_db_template,
    STATE(32), 2,
      sym_comment,
      sym_macro_expansion,
  [847] = 5,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(5), 1,
      anon_sym_DOLLAR_LBRACE,
    ACTIONS(7), 1,
      anon_sym_DOLLAR_LPAREN,
    STATE(33), 2,
      sym_comment,
      sym_macro_expansion,
    ACTIONS(133), 4,
      ts_builtin_sym_end,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_pattern,
  [867] = 5,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(5), 1,
      anon_sym_DOLLAR_LBRACE,
    ACTIONS(7), 1,
      anon_sym_DOLLAR_LPAREN,
    STATE(34), 2,
      sym_comment,
      sym_macro_expansion,
    ACTIONS(135), 4,
      ts_builtin_sym_end,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_pattern,
  [887] = 6,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(5), 1,
      anon_sym_DOLLAR_LBRACE,
    ACTIONS(7), 1,
      anon_sym_DOLLAR_LPAREN,
    ACTIONS(137), 1,
      anon_sym_COMMA,
    STATE(35), 2,
      sym_comment,
      sym_macro_expansion,
    ACTIONS(139), 3,
      anon_sym_RBRACE,
      sym__bareword,
      anon_sym_DQUOTE,
  [909] = 5,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(5), 1,
      anon_sym_DOLLAR_LBRACE,
    ACTIONS(7), 1,
      anon_sym_DOLLAR_LPAREN,
    STATE(36), 2,
      sym_comment,
      sym_macro_expansion,
    ACTIONS(141), 4,
      anon_sym_LBRACE,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      sym_identifier,
  [929] = 8,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(5), 1,
      anon_sym_DOLLAR_LBRACE,
    ACTIONS(7), 1,
      anon_sym_DOLLAR_LPAREN,
    ACTIONS(11), 1,
      anon_sym_LBRACE,
    ACTIONS(143), 1,
      anon_sym_RBRACE,
    STATE(17), 1,
      aux_sym_source_file_repeat1,
    STATE(44), 1,
      sym_regular,
    STATE(37), 2,
      sym_comment,
      sym_macro_expansion,
  [955] = 8,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(5), 1,
      anon_sym_DOLLAR_LBRACE,
    ACTIONS(7), 1,
      anon_sym_DOLLAR_LPAREN,
    ACTIONS(13), 1,
      anon_sym_pattern,
    ACTIONS(143), 1,
      anon_sym_RBRACE,
    STATE(16), 1,
      aux_sym_source_file_repeat2,
    STATE(45), 1,
      sym_pattern,
    STATE(38), 2,
      sym_comment,
      sym_macro_expansion,
  [981] = 5,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(5), 1,
      anon_sym_DOLLAR_LBRACE,
    ACTIONS(7), 1,
      anon_sym_DOLLAR_LPAREN,
    STATE(39), 2,
      sym_comment,
      sym_macro_expansion,
    ACTIONS(145), 4,
      ts_builtin_sym_end,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_pattern,
  [1001] = 5,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(5), 1,
      anon_sym_DOLLAR_LBRACE,
    ACTIONS(7), 1,
      anon_sym_DOLLAR_LPAREN,
    STATE(40), 2,
      sym_comment,
      sym_macro_expansion,
    ACTIONS(147), 4,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      sym__bareword,
      anon_sym_DQUOTE,
  [1021] = 5,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(5), 1,
      anon_sym_DOLLAR_LBRACE,
    ACTIONS(7), 1,
      anon_sym_DOLLAR_LPAREN,
    STATE(41), 2,
      sym_comment,
      sym_macro_expansion,
    ACTIONS(129), 4,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      sym__bareword,
      anon_sym_DQUOTE,
  [1041] = 5,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(5), 1,
      anon_sym_DOLLAR_LBRACE,
    ACTIONS(7), 1,
      anon_sym_DOLLAR_LPAREN,
    STATE(42), 2,
      sym_comment,
      sym_macro_expansion,
    ACTIONS(141), 4,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      sym__bareword,
      anon_sym_DQUOTE,
  [1061] = 5,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(5), 1,
      anon_sym_DOLLAR_LBRACE,
    ACTIONS(7), 1,
      anon_sym_DOLLAR_LPAREN,
    STATE(43), 2,
      sym_comment,
      sym_macro_expansion,
    ACTIONS(147), 4,
      anon_sym_LBRACE,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      sym_identifier,
  [1081] = 5,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(5), 1,
      anon_sym_DOLLAR_LBRACE,
    ACTIONS(7), 1,
      anon_sym_DOLLAR_LPAREN,
    STATE(44), 2,
      sym_comment,
      sym_macro_expansion,
    ACTIONS(149), 3,
      ts_builtin_sym_end,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
  [1100] = 5,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(5), 1,
      anon_sym_DOLLAR_LBRACE,
    ACTIONS(7), 1,
      anon_sym_DOLLAR_LPAREN,
    STATE(45), 2,
      sym_comment,
      sym_macro_expansion,
    ACTIONS(151), 3,
      ts_builtin_sym_end,
      anon_sym_RBRACE,
      anon_sym_pattern,
  [1119] = 6,
    ACTIONS(17), 1,
      anon_sym_POUND,
    ACTIONS(153), 1,
      anon_sym_RBRACE,
    ACTIONS(155), 1,
      anon_sym_DOLLAR_LBRACE,
    ACTIONS(158), 1,
      aux_sym_macro_expansion_token1,
    ACTIONS(161), 1,
      anon_sym_DOLLAR_LPAREN,
    STATE(46), 3,
      sym_comment,
      sym_macro_expansion,
      aux_sym_macro_expansion_repeat1,
  [1140] = 5,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(5), 1,
      anon_sym_DOLLAR_LBRACE,
    ACTIONS(7), 1,
      anon_sym_DOLLAR_LPAREN,
    STATE(47), 2,
      sym_comment,
      sym_macro_expansion,
    ACTIONS(164), 3,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      sym_identifier,
  [1159] = 6,
    ACTIONS(17), 1,
      anon_sym_POUND,
    ACTIONS(166), 1,
      anon_sym_DOLLAR_LBRACE,
    ACTIONS(169), 1,
      anon_sym_DOLLAR_LPAREN,
    ACTIONS(172), 1,
      aux_sym_macro_expansion_token2,
    ACTIONS(175), 1,
      anon_sym_RPAREN,
    STATE(48), 3,
      sym_comment,
      sym_macro_expansion,
      aux_sym_macro_expansion_repeat2,
  [1180] = 6,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(5), 1,
      anon_sym_DOLLAR_LBRACE,
    ACTIONS(7), 1,
      anon_sym_DOLLAR_LPAREN,
    ACTIONS(177), 1,
      anon_sym_RBRACE,
    ACTIONS(179), 1,
      sym_identifier,
    STATE(49), 3,
      sym_comment,
      sym_macro_expansion,
      aux_sym_pattern_variables_repeat1,
  [1201] = 6,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(5), 1,
      anon_sym_DOLLAR_LBRACE,
    ACTIONS(7), 1,
      anon_sym_DOLLAR_LPAREN,
    ACTIONS(182), 1,
      anon_sym_COMMA,
    ACTIONS(184), 2,
      anon_sym_RBRACE,
      sym_identifier,
    STATE(50), 2,
      sym_comment,
      sym_macro_expansion,
  [1222] = 5,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(5), 1,
      anon_sym_DOLLAR_LBRACE,
    ACTIONS(7), 1,
      anon_sym_DOLLAR_LPAREN,
    STATE(51), 2,
      sym_comment,
      sym_macro_expansion,
    ACTIONS(186), 3,
      ts_builtin_sym_end,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
  [1241] = 7,
    ACTIONS(17), 1,
      anon_sym_POUND,
    ACTIONS(188), 1,
      anon_sym_RBRACE,
    ACTIONS(190), 1,
      anon_sym_DOLLAR_LBRACE,
    ACTIONS(192), 1,
      aux_sym_macro_expansion_token1,
    ACTIONS(194), 1,
      anon_sym_DOLLAR_LPAREN,
    STATE(46), 1,
      aux_sym_macro_expansion_repeat1,
    STATE(52), 2,
      sym_comment,
      sym_macro_expansion,
  [1264] = 5,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(5), 1,
      anon_sym_DOLLAR_LBRACE,
    ACTIONS(7), 1,
      anon_sym_DOLLAR_LPAREN,
    STATE(53), 2,
      sym_comment,
      sym_macro_expansion,
    ACTIONS(57), 3,
      anon_sym_RBRACE,
      sym__bareword,
      anon_sym_DQUOTE,
  [1283] = 6,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(5), 1,
      anon_sym_DOLLAR_LBRACE,
    ACTIONS(7), 1,
      anon_sym_DOLLAR_LPAREN,
    ACTIONS(196), 1,
      anon_sym_COMMA,
    ACTIONS(198), 2,
      anon_sym_RBRACE,
      sym_identifier,
    STATE(54), 2,
      sym_comment,
      sym_macro_expansion,
  [1304] = 7,
    ACTIONS(17), 1,
      anon_sym_POUND,
    ACTIONS(188), 1,
      anon_sym_RPAREN,
    ACTIONS(200), 1,
      anon_sym_DOLLAR_LBRACE,
    ACTIONS(202), 1,
      anon_sym_DOLLAR_LPAREN,
    ACTIONS(204), 1,
      aux_sym_macro_expansion_token2,
    STATE(48), 1,
      aux_sym_macro_expansion_repeat2,
    STATE(55), 2,
      sym_comment,
      sym_macro_expansion,
  [1327] = 7,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(5), 1,
      anon_sym_DOLLAR_LBRACE,
    ACTIONS(7), 1,
      anon_sym_DOLLAR_LPAREN,
    ACTIONS(206), 1,
      anon_sym_RBRACE,
    ACTIONS(208), 1,
      sym_identifier,
    STATE(49), 1,
      aux_sym_pattern_variables_repeat1,
    STATE(56), 2,
      sym_comment,
      sym_macro_expansion,
  [1350] = 7,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(5), 1,
      anon_sym_DOLLAR_LBRACE,
    ACTIONS(7), 1,
      anon_sym_DOLLAR_LPAREN,
    ACTIONS(208), 1,
      sym_identifier,
    ACTIONS(210), 1,
      anon_sym_RBRACE,
    STATE(56), 1,
      aux_sym_pattern_variables_repeat1,
    STATE(57), 2,
      sym_comment,
      sym_macro_expansion,
  [1373] = 7,
    ACTIONS(17), 1,
      anon_sym_POUND,
    ACTIONS(190), 1,
      anon_sym_DOLLAR_LBRACE,
    ACTIONS(192), 1,
      aux_sym_macro_expansion_token1,
    ACTIONS(194), 1,
      anon_sym_DOLLAR_LPAREN,
    ACTIONS(212), 1,
      anon_sym_RBRACE,
    STATE(46), 1,
      aux_sym_macro_expansion_repeat1,
    STATE(58), 2,
      sym_comment,
      sym_macro_expansion,
  [1396] = 7,
    ACTIONS(17), 1,
      anon_sym_POUND,
    ACTIONS(200), 1,
      anon_sym_DOLLAR_LBRACE,
    ACTIONS(202), 1,
      anon_sym_DOLLAR_LPAREN,
    ACTIONS(204), 1,
      aux_sym_macro_expansion_token2,
    ACTIONS(212), 1,
      anon_sym_RPAREN,
    STATE(48), 1,
      aux_sym_macro_expansion_repeat2,
    STATE(59), 2,
      sym_comment,
      sym_macro_expansion,
  [1419] = 5,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(5), 1,
      anon_sym_DOLLAR_LBRACE,
    ACTIONS(7), 1,
      anon_sym_DOLLAR_LPAREN,
    STATE(60), 2,
      sym_comment,
      sym_macro_expansion,
    ACTIONS(214), 3,
      ts_builtin_sym_end,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
  [1438] = 7,
    ACTIONS(17), 1,
      anon_sym_POUND,
    ACTIONS(190), 1,
      anon_sym_DOLLAR_LBRACE,
    ACTIONS(192), 1,
      aux_sym_macro_expansion_token1,
    ACTIONS(194), 1,
      anon_sym_DOLLAR_LPAREN,
    ACTIONS(216), 1,
      anon_sym_RBRACE,
    STATE(46), 1,
      aux_sym_macro_expansion_repeat1,
    STATE(61), 2,
      sym_comment,
      sym_macro_expansion,
  [1461] = 7,
    ACTIONS(17), 1,
      anon_sym_POUND,
    ACTIONS(200), 1,
      anon_sym_DOLLAR_LBRACE,
    ACTIONS(202), 1,
      anon_sym_DOLLAR_LPAREN,
    ACTIONS(204), 1,
      aux_sym_macro_expansion_token2,
    ACTIONS(216), 1,
      anon_sym_RPAREN,
    STATE(48), 1,
      aux_sym_macro_expansion_repeat2,
    STATE(62), 2,
      sym_comment,
      sym_macro_expansion,
  [1484] = 3,
    ACTIONS(17), 1,
      anon_sym_POUND,
    STATE(63), 2,
      sym_comment,
      sym_macro_expansion,
    ACTIONS(218), 4,
      anon_sym_DOLLAR_LBRACE,
      anon_sym_DOLLAR_LPAREN,
      aux_sym_macro_expansion_token2,
      anon_sym_RPAREN,
  [1498] = 5,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(5), 1,
      anon_sym_DOLLAR_LBRACE,
    ACTIONS(7), 1,
      anon_sym_DOLLAR_LPAREN,
    ACTIONS(220), 2,
      ts_builtin_sym_end,
      anon_sym_file,
    STATE(64), 2,
      sym_comment,
      sym_macro_expansion,
  [1516] = 6,
    ACTIONS(17), 1,
      anon_sym_POUND,
    ACTIONS(190), 1,
      anon_sym_DOLLAR_LBRACE,
    ACTIONS(192), 1,
      aux_sym_macro_expansion_token1,
    ACTIONS(194), 1,
      anon_sym_DOLLAR_LPAREN,
    STATE(52), 1,
      aux_sym_macro_expansion_repeat1,
    STATE(65), 2,
      sym_comment,
      sym_macro_expansion,
  [1536] = 5,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(5), 1,
      anon_sym_DOLLAR_LBRACE,
    ACTIONS(7), 1,
      anon_sym_DOLLAR_LPAREN,
    ACTIONS(120), 2,
      anon_sym_RBRACE,
      sym_identifier,
    STATE(66), 2,
      sym_comment,
      sym_macro_expansion,
  [1554] = 5,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(5), 1,
      anon_sym_DOLLAR_LBRACE,
    ACTIONS(7), 1,
      anon_sym_DOLLAR_LPAREN,
    ACTIONS(222), 2,
      ts_builtin_sym_end,
      anon_sym_file,
    STATE(67), 2,
      sym_comment,
      sym_macro_expansion,
  [1572] = 3,
    ACTIONS(17), 1,
      anon_sym_POUND,
    STATE(68), 2,
      sym_comment,
      sym_macro_expansion,
    ACTIONS(224), 4,
      anon_sym_RBRACE,
      anon_sym_DOLLAR_LBRACE,
      aux_sym_macro_expansion_token1,
      anon_sym_DOLLAR_LPAREN,
  [1586] = 3,
    ACTIONS(17), 1,
      anon_sym_POUND,
    STATE(69), 2,
      sym_comment,
      sym_macro_expansion,
    ACTIONS(226), 4,
      anon_sym_RBRACE,
      anon_sym_DOLLAR_LBRACE,
      aux_sym_macro_expansion_token1,
      anon_sym_DOLLAR_LPAREN,
  [1600] = 5,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(5), 1,
      anon_sym_DOLLAR_LBRACE,
    ACTIONS(7), 1,
      anon_sym_DOLLAR_LPAREN,
    ACTIONS(177), 2,
      anon_sym_RBRACE,
      sym_identifier,
    STATE(70), 2,
      sym_comment,
      sym_macro_expansion,
  [1618] = 3,
    ACTIONS(17), 1,
      anon_sym_POUND,
    STATE(71), 2,
      sym_comment,
      sym_macro_expansion,
    ACTIONS(226), 4,
      anon_sym_DOLLAR_LBRACE,
      anon_sym_DOLLAR_LPAREN,
      aux_sym_macro_expansion_token2,
      anon_sym_RPAREN,
  [1632] = 5,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(5), 1,
      anon_sym_DOLLAR_LBRACE,
    ACTIONS(7), 1,
      anon_sym_DOLLAR_LPAREN,
    ACTIONS(228), 2,
      ts_builtin_sym_end,
      anon_sym_file,
    STATE(72), 2,
      sym_comment,
      sym_macro_expansion,
  [1650] = 6,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(5), 1,
      anon_sym_DOLLAR_LBRACE,
    ACTIONS(7), 1,
      anon_sym_DOLLAR_LPAREN,
    ACTIONS(230), 1,
      anon_sym_LBRACE,
    STATE(8), 1,
      sym_pattern_variables,
    STATE(73), 2,
      sym_comment,
      sym_macro_expansion,
  [1670] = 5,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(5), 1,
      anon_sym_DOLLAR_LBRACE,
    ACTIONS(7), 1,
      anon_sym_DOLLAR_LPAREN,
    ACTIONS(232), 2,
      ts_builtin_sym_end,
      anon_sym_file,
    STATE(74), 2,
      sym_comment,
      sym_macro_expansion,
  [1688] = 6,
    ACTIONS(17), 1,
      anon_sym_POUND,
    ACTIONS(200), 1,
      anon_sym_DOLLAR_LBRACE,
    ACTIONS(202), 1,
      anon_sym_DOLLAR_LPAREN,
    ACTIONS(204), 1,
      aux_sym_macro_expansion_token2,
    STATE(55), 1,
      aux_sym_macro_expansion_repeat2,
    STATE(75), 2,
      sym_comment,
      sym_macro_expansion,
  [1708] = 6,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(5), 1,
      anon_sym_DOLLAR_LBRACE,
    ACTIONS(7), 1,
      anon_sym_DOLLAR_LPAREN,
    ACTIONS(234), 1,
      anon_sym_LBRACE,
    STATE(64), 1,
      sym_substitutions,
    STATE(76), 2,
      sym_comment,
      sym_macro_expansion,
  [1728] = 6,
    ACTIONS(17), 1,
      anon_sym_POUND,
    ACTIONS(190), 1,
      anon_sym_DOLLAR_LBRACE,
    ACTIONS(192), 1,
      aux_sym_macro_expansion_token1,
    ACTIONS(194), 1,
      anon_sym_DOLLAR_LPAREN,
    STATE(58), 1,
      aux_sym_macro_expansion_repeat1,
    STATE(77), 2,
      sym_comment,
      sym_macro_expansion,
  [1748] = 6,
    ACTIONS(17), 1,
      anon_sym_POUND,
    ACTIONS(200), 1,
      anon_sym_DOLLAR_LBRACE,
    ACTIONS(202), 1,
      anon_sym_DOLLAR_LPAREN,
    ACTIONS(204), 1,
      aux_sym_macro_expansion_token2,
    STATE(59), 1,
      aux_sym_macro_expansion_repeat2,
    STATE(78), 2,
      sym_comment,
      sym_macro_expansion,
  [1768] = 6,
    ACTIONS(17), 1,
      anon_sym_POUND,
    ACTIONS(190), 1,
      anon_sym_DOLLAR_LBRACE,
    ACTIONS(192), 1,
      aux_sym_macro_expansion_token1,
    ACTIONS(194), 1,
      anon_sym_DOLLAR_LPAREN,
    STATE(61), 1,
      aux_sym_macro_expansion_repeat1,
    STATE(79), 2,
      sym_comment,
      sym_macro_expansion,
  [1788] = 6,
    ACTIONS(17), 1,
      anon_sym_POUND,
    ACTIONS(200), 1,
      anon_sym_DOLLAR_LBRACE,
    ACTIONS(202), 1,
      anon_sym_DOLLAR_LPAREN,
    ACTIONS(204), 1,
      aux_sym_macro_expansion_token2,
    STATE(62), 1,
      aux_sym_macro_expansion_repeat2,
    STATE(80), 2,
      sym_comment,
      sym_macro_expansion,
  [1808] = 5,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(5), 1,
      anon_sym_DOLLAR_LBRACE,
    ACTIONS(7), 1,
      anon_sym_DOLLAR_LPAREN,
    ACTIONS(236), 1,
      anon_sym_EQ,
    STATE(81), 2,
      sym_comment,
      sym_macro_expansion,
  [1825] = 5,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(5), 1,
      anon_sym_DOLLAR_LBRACE,
    ACTIONS(7), 1,
      anon_sym_DOLLAR_LPAREN,
    ACTIONS(238), 1,
      ts_builtin_sym_end,
    STATE(82), 2,
      sym_comment,
      sym_macro_expansion,
  [1842] = 5,
    ACTIONS(17), 1,
      anon_sym_POUND,
    ACTIONS(25), 1,
      anon_sym_DOLLAR_LBRACE,
    ACTIONS(27), 1,
      anon_sym_DOLLAR_LPAREN,
    ACTIONS(240), 1,
      aux_sym_comment_token1,
    STATE(83), 2,
      sym_comment,
      sym_macro_expansion,
  [1859] = 1,
    ACTIONS(242), 1,
      ts_builtin_sym_end,
  [1863] = 1,
    ACTIONS(244), 1,
      ts_builtin_sym_end,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 35,
  [SMALL_STATE(4)] = 70,
  [SMALL_STATE(5)] = 103,
  [SMALL_STATE(6)] = 138,
  [SMALL_STATE(7)] = 173,
  [SMALL_STATE(8)] = 208,
  [SMALL_STATE(9)] = 236,
  [SMALL_STATE(10)] = 268,
  [SMALL_STATE(11)] = 296,
  [SMALL_STATE(12)] = 326,
  [SMALL_STATE(13)] = 354,
  [SMALL_STATE(14)] = 386,
  [SMALL_STATE(15)] = 412,
  [SMALL_STATE(16)] = 438,
  [SMALL_STATE(17)] = 463,
  [SMALL_STATE(18)] = 488,
  [SMALL_STATE(19)] = 511,
  [SMALL_STATE(20)] = 534,
  [SMALL_STATE(21)] = 557,
  [SMALL_STATE(22)] = 583,
  [SMALL_STATE(23)] = 609,
  [SMALL_STATE(24)] = 635,
  [SMALL_STATE(25)] = 659,
  [SMALL_STATE(26)] = 685,
  [SMALL_STATE(27)] = 709,
  [SMALL_STATE(28)] = 729,
  [SMALL_STATE(29)] = 749,
  [SMALL_STATE(30)] = 769,
  [SMALL_STATE(31)] = 795,
  [SMALL_STATE(32)] = 821,
  [SMALL_STATE(33)] = 847,
  [SMALL_STATE(34)] = 867,
  [SMALL_STATE(35)] = 887,
  [SMALL_STATE(36)] = 909,
  [SMALL_STATE(37)] = 929,
  [SMALL_STATE(38)] = 955,
  [SMALL_STATE(39)] = 981,
  [SMALL_STATE(40)] = 1001,
  [SMALL_STATE(41)] = 1021,
  [SMALL_STATE(42)] = 1041,
  [SMALL_STATE(43)] = 1061,
  [SMALL_STATE(44)] = 1081,
  [SMALL_STATE(45)] = 1100,
  [SMALL_STATE(46)] = 1119,
  [SMALL_STATE(47)] = 1140,
  [SMALL_STATE(48)] = 1159,
  [SMALL_STATE(49)] = 1180,
  [SMALL_STATE(50)] = 1201,
  [SMALL_STATE(51)] = 1222,
  [SMALL_STATE(52)] = 1241,
  [SMALL_STATE(53)] = 1264,
  [SMALL_STATE(54)] = 1283,
  [SMALL_STATE(55)] = 1304,
  [SMALL_STATE(56)] = 1327,
  [SMALL_STATE(57)] = 1350,
  [SMALL_STATE(58)] = 1373,
  [SMALL_STATE(59)] = 1396,
  [SMALL_STATE(60)] = 1419,
  [SMALL_STATE(61)] = 1438,
  [SMALL_STATE(62)] = 1461,
  [SMALL_STATE(63)] = 1484,
  [SMALL_STATE(64)] = 1498,
  [SMALL_STATE(65)] = 1516,
  [SMALL_STATE(66)] = 1536,
  [SMALL_STATE(67)] = 1554,
  [SMALL_STATE(68)] = 1572,
  [SMALL_STATE(69)] = 1586,
  [SMALL_STATE(70)] = 1600,
  [SMALL_STATE(71)] = 1618,
  [SMALL_STATE(72)] = 1632,
  [SMALL_STATE(73)] = 1650,
  [SMALL_STATE(74)] = 1670,
  [SMALL_STATE(75)] = 1688,
  [SMALL_STATE(76)] = 1708,
  [SMALL_STATE(77)] = 1728,
  [SMALL_STATE(78)] = 1748,
  [SMALL_STATE(79)] = 1768,
  [SMALL_STATE(80)] = 1788,
  [SMALL_STATE(81)] = 1808,
  [SMALL_STATE(82)] = 1825,
  [SMALL_STATE(83)] = 1842,
  [SMALL_STATE(84)] = 1859,
  [SMALL_STATE(85)] = 1863,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT(83),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT(65),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(75),
  [9] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0, 0, 0),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(73),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [17] = {.entry = {.count = 1, .reusable = false}}, SHIFT(83),
  [19] = {.entry = {.count = 1, .reusable = false}}, SHIFT(29),
  [21] = {.entry = {.count = 1, .reusable = false}}, SHIFT(18),
  [23] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [25] = {.entry = {.count = 1, .reusable = false}}, SHIFT(65),
  [27] = {.entry = {.count = 1, .reusable = false}}, SHIFT(75),
  [29] = {.entry = {.count = 1, .reusable = false}}, SHIFT(36),
  [31] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_quoted_string_repeat1, 2, 0, 0),
  [33] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_quoted_string_repeat1, 2, 0, 0), SHIFT_REPEAT(18),
  [36] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_quoted_string_repeat1, 2, 0, 0), SHIFT_REPEAT(19),
  [39] = {.entry = {.count = 1, .reusable = false}}, SHIFT(41),
  [41] = {.entry = {.count = 1, .reusable = false}}, SHIFT(42),
  [43] = {.entry = {.count = 1, .reusable = true}}, SHIFT(74),
  [45] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_pattern, 2, 0, 0),
  [47] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [49] = {.entry = {.count = 1, .reusable = true}}, SHIFT(34),
  [51] = {.entry = {.count = 1, .reusable = true}}, SHIFT(40),
  [53] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [55] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_pattern, 3, 0, 0),
  [57] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_pattern_values_repeat1, 2, 0, 0),
  [59] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_pattern_values_repeat1, 2, 0, 0), SHIFT_REPEAT(40),
  [62] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_pattern_values_repeat1, 2, 0, 0), SHIFT_REPEAT(5),
  [65] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_quoted_string_text_fragment, 1, 0, 0),
  [67] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_quoted_string_text_fragment, 1, 0, 0),
  [69] = {.entry = {.count = 1, .reusable = true}}, SHIFT(39),
  [71] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_pattern_repeat1, 2, 0, 0),
  [73] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_pattern_repeat1, 2, 0, 0), SHIFT_REPEAT(9),
  [76] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_quoted_string_text_fragment_repeat1, 2, 0, 0),
  [78] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_quoted_string_text_fragment_repeat1, 2, 0, 0), SHIFT_REPEAT(18),
  [81] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_quoted_string_text_fragment_repeat1, 2, 0, 0),
  [83] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat2, 2, 0, 0),
  [85] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat2, 2, 0, 0), SHIFT_REPEAT(73),
  [88] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [90] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(23),
  [93] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_quoted_string_text_fragment_repeat1, 1, 0, 0),
  [95] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_quoted_string_text_fragment_repeat1, 1, 0, 0),
  [97] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_escape_sequence, 1, 0, 0),
  [99] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_escape_sequence, 1, 0, 0),
  [101] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_quoted_string_repeat1, 1, 0, 0),
  [103] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_quoted_string_repeat1, 1, 0, 0),
  [105] = {.entry = {.count = 1, .reusable = true}}, SHIFT(43),
  [107] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [109] = {.entry = {.count = 1, .reusable = true}}, SHIFT(51),
  [111] = {.entry = {.count = 1, .reusable = true}}, SHIFT(81),
  [113] = {.entry = {.count = 1, .reusable = true}}, SHIFT(60),
  [115] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat3, 2, 0, 0),
  [117] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat3, 2, 0, 0), SHIFT_REPEAT(21),
  [120] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_regular_repeat1, 2, 0, 0),
  [122] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_regular_repeat1, 2, 0, 0), SHIFT_REPEAT(81),
  [125] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_pattern_variables, 2, 0, 0),
  [127] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_pattern_repeat1, 1, 0, 0),
  [129] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_quoted_string, 2, 0, 0),
  [131] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [133] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_pattern_variables, 3, 0, 0),
  [135] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_pattern_values, 2, 0, 0),
  [137] = {.entry = {.count = 1, .reusable = true}}, SHIFT(53),
  [139] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_pattern_values_repeat1, 1, 0, 0),
  [141] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_quoted_string, 3, 0, 0),
  [143] = {.entry = {.count = 1, .reusable = true}}, SHIFT(67),
  [145] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_pattern_values, 3, 0, 0),
  [147] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_string, 1, 0, 0),
  [149] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 1, 0, 0),
  [151] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat2, 1, 0, 0),
  [153] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_macro_expansion_repeat1, 2, 0, 0),
  [155] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_macro_expansion_repeat1, 2, 0, 0), SHIFT_REPEAT(77),
  [158] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_macro_expansion_repeat1, 2, 0, 0), SHIFT_REPEAT(68),
  [161] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_macro_expansion_repeat1, 2, 0, 0), SHIFT_REPEAT(78),
  [164] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__regular_assignment, 3, 0, 0),
  [166] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_macro_expansion_repeat2, 2, 0, 0), SHIFT_REPEAT(79),
  [169] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_macro_expansion_repeat2, 2, 0, 0), SHIFT_REPEAT(80),
  [172] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_macro_expansion_repeat2, 2, 0, 0), SHIFT_REPEAT(63),
  [175] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_macro_expansion_repeat2, 2, 0, 0),
  [177] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_pattern_variables_repeat1, 2, 0, 0),
  [179] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_pattern_variables_repeat1, 2, 0, 0), SHIFT_REPEAT(54),
  [182] = {.entry = {.count = 1, .reusable = true}}, SHIFT(66),
  [184] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_regular_repeat1, 1, 0, 0),
  [186] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_regular, 3, 0, 0),
  [188] = {.entry = {.count = 1, .reusable = false}}, SHIFT(84),
  [190] = {.entry = {.count = 1, .reusable = false}}, SHIFT(77),
  [192] = {.entry = {.count = 1, .reusable = false}}, SHIFT(68),
  [194] = {.entry = {.count = 1, .reusable = false}}, SHIFT(78),
  [196] = {.entry = {.count = 1, .reusable = true}}, SHIFT(70),
  [198] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_pattern_variables_repeat1, 1, 0, 0),
  [200] = {.entry = {.count = 1, .reusable = false}}, SHIFT(79),
  [202] = {.entry = {.count = 1, .reusable = false}}, SHIFT(80),
  [204] = {.entry = {.count = 1, .reusable = false}}, SHIFT(63),
  [206] = {.entry = {.count = 1, .reusable = true}}, SHIFT(33),
  [208] = {.entry = {.count = 1, .reusable = true}}, SHIFT(54),
  [210] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [212] = {.entry = {.count = 1, .reusable = false}}, SHIFT(69),
  [214] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_regular, 2, 0, 0),
  [216] = {.entry = {.count = 1, .reusable = false}}, SHIFT(71),
  [218] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_macro_expansion_repeat2, 1, 0, 0),
  [220] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_db_template, 3, 0, 1),
  [222] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_substitutions, 3, 0, 0),
  [224] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_macro_expansion_repeat1, 1, 0, 0),
  [226] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_macro_expansion, 3, 0, 0),
  [228] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat3, 1, 0, 0),
  [230] = {.entry = {.count = 1, .reusable = true}}, SHIFT(57),
  [232] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_substitutions, 2, 0, 0),
  [234] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [236] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [238] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [240] = {.entry = {.count = 1, .reusable = false}}, SHIFT(85),
  [242] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_macro_expansion, 3, 0, 0),
  [244] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_comment, 2, 0, 0),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_epics_msi_substitution(void) {
  static const TSLanguage language = {
    .version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
