(function) @function
(type_alias) @type
(type_enum) @type
(type_struct) @type
(constant) @constant
(validator) @function.special
(test) @function.test
(identifier) @variable
(type_identifier) @type
(string) @string
(int) @number
(bytes) @string.special
(any_comment) @comment
(comment) @comment
"use" @keyword
"pub" @keyword
"opaque" @keyword
"type" @keyword
"fn" @keyword
"validator" @keyword
"test" @keyword
"let" @keyword
"expect" @keyword
"when" @keyword
"is" @keyword
"if" @keyword
"else" @keyword
"trace" @keyword
"fail" @keyword
"as" @keyword
["!" "-" "+" "*" "/" "%" "==" "!=" "<" "<=" ">" ">=" "&&" "||" "|>" "->"] @operator
